ZAP: sema::anonymous_namespace{binder_exprs.cpp} Namespace Reference
sema::anonymous_namespace{binder_exprs.cpp} Namespace Reference
Classes
struct TypeLayout
Functions
uint64_t alignTo (uint64_t value, uint64_t alignment)
TypeLayout layoutOfType (const std::shared_ptr< zir::Type > &type)
TypeLayout layoutOfAggregateField (const std::shared_ptr< zir::Type > &type)
TypeLayout layoutOfRecord (const zir::RecordType &record)
TypeLayout layoutOfTaggedUnion (const zir::TaggedUnionType &taggedUnion)
Function Documentation
alignTo()
uint64_t sema::anonymous_namespace{binder_exprs.cpp}::alignTo (uint64_t value, uint64_t alignment)
Definition at line 24 of file binder_exprs.cpp.
{
  if (alignment <= 1) {
    return value;
  }
  return ((value + alignment - 1) / alignment) * alignment;
}
References alignTo().
Referenced by alignTo(), layoutOfRecord(), and layoutOfTaggedUnion().
layoutOfAggregateField()
TypeLayout sema::anonymous_namespace{binder_exprs.cpp}::layoutOfAggregateField (const std::shared_ptr< zir::Type > & type)
Definition at line 33 of file binder_exprs.cpp.
{
  if (type && type->getKind() == zir::TypeKind::Void) {
    return {1, 1};
  }
  return layoutOfType(type);
}
References layoutOfAggregateField(), layoutOfType(), and zir::Void.
Referenced by layoutOfAggregateField(), layoutOfRecord(), layoutOfTaggedUnion(), and layoutOfType().
layoutOfRecord()
TypeLayout sema::anonymous_namespace{binder_exprs.cpp}::layoutOfRecord (const zir::RecordType & record)
Definition at line 40 of file binder_exprs.cpp.
{
  if (zap::text::isStringRecordName(record.getName())) {
    return {16, 8};
  }
  uint64_t offset = 0;
  uint64_t maxAlign = 1;
  for (const auto &field : record.getFields()) {
    auto fieldLayout = layoutOfAggregateField(field.type);
    maxAlign = std::max(maxAlign, fieldLayout.align);
    if (!record.isPacked) {
      offset = alignTo(offset, fieldLayout.align);
    }
    offset += fieldLayout.size;
  }
  if (!record.isPacked) {
    offset = alignTo(offset, maxAlign);
  }
  return {offset, record.isPacked ? 1 : maxAlign};
}
References alignTo(), zir::RecordType::getFields(), zir::RecordType::getName(), zir::RecordType::isPacked, zap::text::isStringRecordName(), layoutOfAggregateField(), and layoutOfRecord().
Referenced by layoutOfRecord(), and layoutOfType().
layoutOfTaggedUnion()
TypeLayout sema::anonymous_namespace{binder_exprs.cpp}::layoutOfTaggedUnion (const zir::TaggedUnionType & taggedUnion)
Definition at line 62 of file binder_exprs.cpp.
{
  TypeLayout payloadLayout{1, 1};
  for (const auto &variant : taggedUnion.getVariants()) {
    if (!variant.payloadType) {
      continue;
    }
    auto candidate = layoutOfAggregateField(variant.payloadType);
    if (candidate.size > payloadLayout.size ||
        (candidate.size == payloadLayout.size &&
         candidate.align > payloadLayout.align)) {
      payloadLayout = candidate;
    }
  }
  uint64_t offset = 4;
  const uint64_t structAlign = std::max<uint64_t>(4, payloadLayout.align);
  offset = alignTo(offset, payloadLayout.align);
  offset += payloadLayout.size;
  return {alignTo(offset, structAlign), structAlign};
}
References sema::anonymous_namespace{binder_exprs.cpp}::TypeLayout::align, alignTo(), zir::TaggedUnionType::getVariants(), layoutOfAggregateField(), layoutOfTaggedUnion(), and sema::anonymous_namespace{binder_exprs.cpp}::TypeLayout::size.
Referenced by layoutOfTaggedUnion(), and layoutOfType().
layoutOfType()
TypeLayout sema::anonymous_namespace{binder_exprs.cpp}::layoutOfType (const std::shared_ptr< zir::Type > & type)
Definition at line 83 of file binder_exprs.cpp.
{
  if (!type) {
    return {0, 1};
  }
  switch (type->getKind()) {
  case zir::TypeKind::Void:
    return {0, 1};
  case zir::TypeKind::Bool:
  case zir::TypeKind::Char:
  case zir::TypeKind::Int8:
  case zir::TypeKind::UInt8:
    return {1, 1};
  case zir::TypeKind::Int16:
  case zir::TypeKind::UInt16:
    return {2, 2};
  case zir::TypeKind::Int32:
  case zir::TypeKind::UInt32:
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
    return {4, 4};
  case zir::TypeKind::Int:
  case zir::TypeKind::UInt:
  case zir::TypeKind::Int64:
  case zir::TypeKind::UInt64:
  case zir::TypeKind::Float64:
  case zir::TypeKind::Pointer:
  case zir::TypeKind::NullPtr:
  case zir::TypeKind::FunctionPointer:
  case zir::TypeKind::Class:
    return {8, 8};
  case zir::TypeKind::Enum:
    return std::static_pointer_cast<zir::EnumType>(type)->hasReprC
               ? TypeLayout{4, 4}
               : TypeLayout{8, 8};
  case zir::TypeKind::Record:
    return layoutOfRecord(*std::static_pointer_cast<zir::RecordType>(type));
  case zir::TypeKind::TaggedUnion:
    return layoutOfTaggedUnion(
        *std::static_pointer_cast<zir::TaggedUnionType>(type));
  case zir::TypeKind::Array: {
    auto array = std::static_pointer_cast<zir::ArrayType>(type);
    auto elementLayout = layoutOfAggregateField(array->getBaseType());
    return {elementLayout.size * array->getSize(), elementLayout.align};
  }
  }
  return {0, 1};
}
References zir::Array, zir::Bool, zir::Char, zir::Class, zir::Enum, zir::Float, zir::Float32, zir::Float64, zir::FunctionPointer, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, layoutOfAggregateField(), layoutOfRecord(), layoutOfTaggedUnion(), layoutOfType(), zir::NullPtr, zir::Pointer, zir::Record, zir::TaggedUnion, zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, zir::UInt8, and zir::Void.
Referenced by layoutOfAggregateField(), and layoutOfType().