ZAP: sema Namespace Reference
sema Namespace Reference
Namespaces
namespace anonymous_namespace{binder_exprs.cpp}
Classes
class Binder
class BoundVisitor
class BoundNode
class BoundExpression
class BoundStatement
class BoundExpressionStatement
class BoundBlock
class BoundLiteral
class BoundCast
class BoundVariableExpression
class BoundCompoundTargetLoad
class BoundModuleReference
class BoundBinaryExpression
class BoundTernaryExpression
class BoundUnaryExpression
class BoundFunctionCall
class BoundIndirectCall
class BoundFunctionReference
class BoundArrayLiteral
class BoundNewExpression
class BoundWeakLockExpression
class BoundWeakAliveExpression
class BoundIndexAccess
class BoundTryExpression
class BoundFallbackExpression
class BoundFailableHandleExpression
class BoundVariableDeclaration
class BoundReturnStatement
class BoundFailStatement
class BoundAssignment
class BoundIfStatement
class BoundWhileStatement
class BoundForStatement
class BoundBreakStatement
struct BoundAsmOperand
class BoundAsmStatement
class BoundContinueStatement
class BoundFunctionDeclaration
class BoundExternalFunctionDeclaration
class BoundRecordDeclaration
class BoundEnumDeclaration
class BoundTaggedUnionDeclaration
class BoundMemberAccess
class BoundTaggedUnionLiteral
class BoundStructLiteral
class BoundRootNode
struct ResolvedImport
struct ModuleInfo
struct SemanticInfo
class Symbol
class VariableSymbol
class FunctionSymbol
class OverloadSetSymbol
class TypeSymbol
class ModuleSymbol
class SymbolTable
Enumerations
enum class SymbolKind {
Variable ,
Function ,
OverloadSet ,
Type ,
Module
}
Functions
std::string abiTypeKey (const std::shared_ptr< zir::Type > &type)
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isFailableType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::Type > failableValueType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::Type > failableErrorType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::RecordType > makeFailableType (const std::shared_ptr< zir::Type > &valueType, const std::shared_ptr< zir::Type > &errorType)
std::string sanitizeTypeName (const std::string &value)
std::string renderGenericTypeName (const std::string &baseName, const std::vector< std::shared_ptr< zir::Type > > &arguments)
std::string renderGenericCodegenName (const std::string &baseName, const std::vector< std::shared_ptr< zir::Type > > &arguments)
std::shared_ptr< zir::RecordType > makeVariadicViewType (const std::shared_ptr< zir::Type > &elementType)
bool isVariadicViewType (const std::shared_ptr< zir::Type > &type)
std::unique_ptr< BoundExpression > makeDefaultValueExpr (const std::shared_ptr< zir::Type > &type)
std::unique_ptr< BoundExpression > makeFailableValueExpr (std::unique_ptr< BoundExpression > valueExpr, const std::shared_ptr< zir::Type > &failableType)
std::unique_ptr< BoundExpression > makeFailableErrorExpr (std::unique_ptr< BoundExpression > errorExpr, const std::shared_ptr< zir::Type > &failableType)
std::vector< std::string > splitQualified (const std::string &value)
bool extractQualifiedPath (const ExpressionNode *expr, std::vector< std::string > &parts)
std::vector< std::shared_ptr< FunctionSymbol > > collectOverloads (const std::shared_ptr< Symbol > &symbol)
bool sameFunctionSignature (const FunctionSymbol &lhs, const FunctionSymbol &rhs)
bool blockAlwaysReturns (const BoundBlock *block)
bool stmtAlwaysReturns (const BoundStatement *stmt)
std::unique_ptr< BoundExpression > deriveValueExpressionFromIf (const BoundIfStatement &stmt)
std::unique_ptr< BoundExpression > deriveValueExpressionFromBlock (const BoundBlock &block)
bool sameMethodDispatchSignature (const FunctionSymbol &lhs, const FunctionSymbol &rhs)
Enumeration Type Documentation
SymbolKind
enum class sema::SymbolKind strong
Enumerator
Variable
Function
OverloadSet
Type
Module
Definition at line 12 of file symbol.hpp.
{ Variable, Function, OverloadSet, Type, Module };
Function Documentation
abiTypeKey()
std::string sema::abiTypeKey (const std::shared_ptr< zir::Type > & type)
Definition at line 19 of file binder.cpp.
{
  if (!type) {
    return "void";
  }
  switch (type->getKind()) {
  case zir::TypeKind::Void:
    return "v";
  case zir::TypeKind::Bool:
    return "b1";
  case zir::TypeKind::Char:
    return "c8";
  case zir::TypeKind::Int8:
    return "i8";
  case zir::TypeKind::Int16:
    return "i16";
  case zir::TypeKind::Int32:
    return "i32";
  case zir::TypeKind::Int64:
    return "i64";
  case zir::TypeKind::UInt8:
    return "u8";
  case zir::TypeKind::UInt16:
    return "u16";
  case zir::TypeKind::UInt32:
    return "u32";
  case zir::TypeKind::UInt64:
    return "u64";
  case zir::TypeKind::Int:
    return "is";
  case zir::TypeKind::UInt:
    return "us";
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
    return "f32";
  case zir::TypeKind::Float64:
    return "f64";
  case zir::TypeKind::NullPtr:
    return "np";
  case zir::TypeKind::Pointer: {
    auto p = std::static_pointer_cast<zir::PointerType>(type);
    return "p_" + abiTypeKey(p->getBaseType());
  }
  case zir::TypeKind::Array: {
    auto a = std::static_pointer_cast<zir::ArrayType>(type);
    return "a" + std::to_string(a->getSize()) + "_" +
           abiTypeKey(a->getBaseType());
  }
  case zir::TypeKind::FunctionPointer: {
    auto fn = std::static_pointer_cast<zir::FunctionPointerType>(type);
    std::string out = "fp_";
    out += abiTypeKey(fn->getReturnType());
    out += "_";
    for (size_t i = 0; i < fn->getParams().size(); ++i) {
      if (i != 0) {
        out += "_";
      }
      out += abiTypeKey(fn->getParams()[i]);
    }
    return out;
  }
  case zir::TypeKind::Record: {
    auto r = std::static_pointer_cast<zir::RecordType>(type);
    return "r_" + sanitizeTypeName(r->getCodegenName());
  }
  case zir::TypeKind::Class: {
    auto c = std::static_pointer_cast<zir::ClassType>(type);
    return std::string(c->isWeak() ? "wc_" : "c_") +
           sanitizeTypeName(c->getCodegenName());
  }
  case zir::TypeKind::Enum: {
    auto e = std::static_pointer_cast<zir::EnumType>(type);
    return "e_" + sanitizeTypeName(e->getCodegenName());
  }
  }
  return sanitizeTypeName(type->toString());
}
References abiTypeKey(), zir::Array, zir::Bool, zir::Char, zir::Class, zir::Enum, zir::Float, zir::Float32, zir::Float64, zir::FunctionPointer, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, zir::NullPtr, zir::Pointer, zir::Record, sanitizeTypeName(), zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, zir::UInt8, and zir::Void.
Referenced by abiTypeKey(), sema::Binder::ensureGenericFunctionInstantiation(), and sema::Binder::functionSignatureKey().
blockAlwaysReturns()
bool sema::blockAlwaysReturns (const BoundBlock * block)
Definition at line 316 of file binder.cpp.
{
  if (!block)
    return false;
  if (block->result)
    return true;
  for (const auto &s : block->statements) {
    if (stmtAlwaysReturns(s.get()))
      return true;
  }
  return false;
}
References sema::BoundBlock::result, sema::BoundBlock::statements, and stmtAlwaysReturns().
Referenced by sema::Binder::ensureGenericFunctionInstantiation(), sema::Binder::instantiateGenericTypeSymbol(), stmtAlwaysReturns(), sema::Binder::visit(), and sema::Binder::visit().
collectOverloads()
std::vector< std::shared_ptr< FunctionSymbol > > sema::collectOverloads (const std::shared_ptr< Symbol > & symbol)
Definition at line 282 of file binder.cpp.
{
  if (!symbol) {
    return {};
  }
  if (auto function = std::dynamic_pointer_cast<FunctionSymbol>(symbol)) {
    return {function};
  }
  if (auto set = std::dynamic_pointer_cast<OverloadSetSymbol>(symbol)) {
    return set->overloads;
  }
  return {};
}
Referenced by sema::Binder::findFunctionBySignature(), sema::Binder::findOverriddenVtableSlot(), sema::Binder::visit(), and sema::Binder::visit().
deriveValueExpressionFromBlock()
std::unique_ptr< BoundExpression > sema::deriveValueExpressionFromBlock (const BoundBlock & block)
Definition at line 364 of file binder.cpp.
{
  if (block.result && block.statements.empty()) {
    return block.result->clone();
  }
  if (block.result) {
    return nullptr;
  }
  if (block.statements.empty()) {
    return nullptr;
  }
  const auto *tail = block.statements.back().get();
  if (auto *exprStmt = dynamic_cast<const BoundExpressionStatement *>(tail)) {
    return exprStmt->expression ? exprStmt->expression->clone() : nullptr;
  }
  if (auto *ifStmt = dynamic_cast<const BoundIfStatement *>(tail)) {
    return deriveValueExpressionFromIf(*ifStmt);
  }
  return nullptr;
}
References deriveValueExpressionFromIf(), sema::BoundBlock::result, and sema::BoundBlock::statements.
Referenced by deriveValueExpressionFromIf(), and sema::Binder::visit().
deriveValueExpressionFromIf()
std::unique_ptr< BoundExpression > sema::deriveValueExpressionFromIf (const BoundIfStatement & stmt)
Definition at line 342 of file binder.cpp.
{
  if (!stmt.thenBody || !stmt.elseBody) {
    return nullptr;
  }
  auto thenExpr = deriveValueExpressionFromBlock(*stmt.thenBody);
  auto elseExpr = deriveValueExpressionFromBlock(*stmt.elseBody);
  if (!thenExpr || !elseExpr || !thenExpr->type || !elseExpr->type) {
    return nullptr;
  }
  if (thenExpr->type->toString() != elseExpr->type->toString()) {
    return nullptr;
  }
  auto resultType = thenExpr->type;
  return std::make_unique<BoundTernaryExpression>(
      stmt.condition->clone(), std::move(thenExpr), std::move(elseExpr),
      resultType);
}
References sema::BoundIfStatement::condition, deriveValueExpressionFromBlock(), sema::BoundIfStatement::elseBody, and sema::BoundIfStatement::thenBody.
Referenced by deriveValueExpressionFromBlock().
extractQualifiedPath()
bool sema::extractQualifiedPath (const ExpressionNode * expr, std::vector< std::string > & parts)
Definition at line 263 of file binder.cpp.
{
  if (auto id = dynamic_cast<const ConstId *>(expr)) {
    parts.push_back(id->value_);
    return true;
  }
  if (auto member = dynamic_cast<const MemberAccessNode *>(expr)) {
    if (!extractQualifiedPath(member->left_.get(), parts)) {
      return false;
    }
    parts.push_back(member->member_);
    return true;
  }
  return false;
}
References extractQualifiedPath().
Referenced by extractQualifiedPath(), and sema::Binder::visit().
failableErrorType()
std::shared_ptr< zir::Type > sema::failableErrorType (const std::shared_ptr< zir::Type > & type)
Definition at line 113 of file binder.cpp.
{
  auto layout = zir::getFailableTypeLayout(type);
  return layout ? layout->errorType : nullptr;
}
References zir::getFailableTypeLayout().
Referenced by sema::Binder::canConvert(), makeDefaultValueExpr(), makeFailableValueExpr(), sema::Binder::visit(), sema::Binder::visit(), sema::Binder::visit(), and sema::Binder::visit().
failableValueType()
std::shared_ptr< zir::Type > sema::failableValueType (const std::shared_ptr< zir::Type > & type)
Definition at line 107 of file binder.cpp.
{
  auto layout = zir::getFailableTypeLayout(type);
  return layout ? layout->valueType : nullptr;
}
References zir::getFailableTypeLayout().
Referenced by sema::Binder::canConvert(), makeDefaultValueExpr(), makeFailableErrorExpr(), makeFailableValueExpr(), sema::Binder::visit(), sema::Binder::visit(), sema::Binder::visit(), and sema::Binder::visit().
isFailableType()
bool sema::isFailableType (const std::shared_ptr< zir::Type > & type)
Definition at line 102 of file binder.cpp.
{
  return zir::getFailableTypeLayout(type).has_value();
}
References zir::getFailableTypeLayout().
Referenced by sema::Binder::canConvert(), makeDefaultValueExpr(), sema::Binder::visit(), sema::Binder::visit(), sema::Binder::visit(), sema::Binder::visit(), and sema::Binder::visit().
isStringType()
bool sema::isStringType (const std::shared_ptr< zir::Type > & type)
Definition at line 98 of file binder.cpp.
{
  return zap::text::isStringType(type);
}
References zap::text::isStringType().
Referenced by sema::Binder::buildBinaryExpression(), sema::Binder::canConvert(), sema::Binder::conversionCost(), sema::Binder::foldConstantBinary(), sema::Binder::getCVariadicArgumentType(), sema::Binder::visit(), sema::Binder::visit(), and sema::Binder::visit().
isVariadicViewType()
bool sema::isVariadicViewType (const std::shared_ptr< zir::Type > & type)
Definition at line 176 of file binder.cpp.
{
  return type && type->getKind() == zir::TypeKind::Record &&
         static_cast<zir::RecordType *>(type.get())
                 ->getName()
                 .rfind("__zap_varargs_", 0) == 0;
}
References zir::RecordType::getName(), and zir::Record.
Referenced by sema::Binder::buildGenericBindings(), sema::Binder::canConvert(), sema::Binder::visit(), sema::Binder::visit(), and sema::Binder::visit().
makeDefaultValueExpr()
std::unique_ptr< BoundExpression > sema::makeDefaultValueExpr (const std::shared_ptr< zir::Type > & type)
Definition at line 184 of file binder.cpp.
{
  if (!type) {
    return std::make_unique<BoundLiteral>(
        "0", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void));
  }
  switch (type->getKind()) {
  case zir::TypeKind::Bool:
    return std::make_unique<BoundLiteral>(
        "false", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool));
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
  case zir::TypeKind::Float64:
    return std::make_unique<BoundLiteral>("0.0", type);
  case zir::TypeKind::Pointer:
  case zir::TypeKind::NullPtr:
  case zir::TypeKind::Class:
    return std::make_unique<BoundLiteral>(
        "0", std::make_shared<zir::PrimitiveType>(zir::TypeKind::NullPtr));
  case zir::TypeKind::Record:
    if (sema::isFailableType(type)) {
      auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
      auto valueType = sema::failableValueType(type);
      auto errorType = sema::failableErrorType(type);
      std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>>
          fields;
      fields.push_back({"ok", std::make_unique<BoundLiteral>("false", okType)});
      fields.push_back({"value", makeDefaultValueExpr(valueType)});
      fields.push_back({"error", makeDefaultValueExpr(errorType)});
      return std::make_unique<BoundStructLiteral>(std::move(fields), type);
    }
    return std::make_unique<BoundLiteral>("0", type);
  default:
    if (type->isInteger() || type->getKind() == zir::TypeKind::Enum) {
      return std::make_unique<BoundLiteral>("0", type);
    }
    return std::make_unique<BoundLiteral>("0", type);
  }
}
References zir::Bool, zir::Class, zir::Enum, failableErrorType(), failableValueType(), zir::Float, zir::Float32, zir::Float64, isFailableType(), makeDefaultValueExpr(), zir::NullPtr, zir::Pointer, zir::Record, and zir::Void.
Referenced by makeDefaultValueExpr(), makeFailableErrorExpr(), makeFailableValueExpr(), sema::Binder::visit(), and sema::Binder::visit().
makeFailableErrorExpr()
std::unique_ptr< BoundExpression > sema::makeFailableErrorExpr (std::unique_ptr< BoundExpression > errorExpr, const std::shared_ptr< zir::Type > & failableType)
Definition at line 239 of file binder.cpp.
{
  auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  auto valueType = sema::failableValueType(failableType);
  std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>> fields;
  fields.push_back({"ok", std::make_unique<BoundLiteral>("false", okType)});
  fields.push_back({"value", makeDefaultValueExpr(valueType)});
  fields.push_back({"error", std::move(errorExpr)});
  return std::make_unique<BoundStructLiteral>(std::move(fields), failableType);
}
References zir::Bool, failableValueType(), and makeDefaultValueExpr().
makeFailableType()
std::shared_ptr< zir::RecordType > sema::makeFailableType (const std::shared_ptr< zir::Type > & valueType, const std::shared_ptr< zir::Type > & errorType)
Definition at line 119 of file binder.cpp.
{
  return zir::makeFailableRecordType(valueType, errorType);
}
References zir::makeFailableRecordType().
Referenced by sema::Binder::mapType().
makeFailableValueExpr()
std::unique_ptr< BoundExpression > sema::makeFailableValueExpr (std::unique_ptr< BoundExpression > valueExpr, const std::shared_ptr< zir::Type > & failableType)
Definition at line 225 of file binder.cpp.
{
  auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  auto valueType = sema::failableValueType(failableType);
  auto errorType = sema::failableErrorType(failableType);
  std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>> fields;
  fields.push_back({"ok", std::make_unique<BoundLiteral>("true", okType)});
  fields.push_back({"value", std::move(valueExpr)});
  fields.push_back({"error", makeDefaultValueExpr(errorType)});
  return std::make_unique<BoundStructLiteral>(std::move(fields), failableType);
}
References zir::Bool, failableErrorType(), failableValueType(), and makeDefaultValueExpr().
Referenced by sema::Binder::visit().
makeVariadicViewType()
std::shared_ptr< zir::RecordType > sema::makeVariadicViewType (const std::shared_ptr< zir::Type > & elementType)
Definition at line 166 of file binder.cpp.
{
  auto suffix = sanitizeTypeName(elementType->toString());
  auto type = std::make_shared<zir::RecordType>("__zap_varargs_" + suffix,
                                                "__zap_varargs_" + suffix);
  type->addField("data", std::make_shared<zir::PointerType>(elementType));
  type->addField("len",
                 std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int));
  return type;
}
References zir::Int, and sanitizeTypeName().
Referenced by sema::Binder::mapType(), sema::Binder::predeclareModuleValues(), sema::Binder::visit(), and sema::Binder::visit().
renderGenericCodegenName()
std::string sema::renderGenericCodegenName (const std::string & baseName, const std::vector< std::shared_ptr< zir::Type > > & arguments)
Definition at line 151 of file binder.cpp.
{
  std::string suffix;
  for (size_t i = 0; i < arguments.size(); ++i) {
    if (i != 0) {
      suffix += "$";
    }
    suffix += sanitizeTypeName(arguments[i] ? arguments[i]->toString()
                                            : std::string("<?>"));
  }
  return baseName + "$g$" + suffix;
}
References sanitizeTypeName().
Referenced by sema::Binder::instantiateGenericTypeSymbol(), and sema::Binder::substituteGenericType().
renderGenericTypeName()
std::string sema::renderGenericTypeName (const std::string & baseName, const std::vector< std::shared_ptr< zir::Type > > & arguments)
Definition at line 137 of file binder.cpp.
{
  std::string name = baseName + "<";
  for (size_t i = 0; i < arguments.size(); ++i) {
    if (i != 0) {
      name += ", ";
    }
    name += arguments[i] ? arguments[i]->toString() : "<?>";
  }
  name += ">";
  return name;
}
Referenced by sema::Binder::instantiateGenericTypeSymbol(), and sema::Binder::substituteGenericType().
sameFunctionSignature()
bool sema::sameFunctionSignature (const FunctionSymbol & lhs, const FunctionSymbol & rhs)
Definition at line 295 of file binder.cpp.
{
  if (lhs.parameters.size() != rhs.parameters.size() ||
      lhs.isCVariadic != rhs.isCVariadic) {
    return false;
  }
  for (size_t i = 0; i < lhs.parameters.size(); ++i) {
    const auto &left = lhs.parameters[i];
    const auto &right = rhs.parameters[i];
    if (left->is_ref != right->is_ref ||
        left->is_variadic_pack != right->is_variadic_pack) {
      return false;
    }
    if (!left->type || !right->type ||
        left->type->toString() != right->type->toString()) {
      return false;
    }
  }
  return true;
}
References sema::FunctionSymbol::isCVariadic, and sema::FunctionSymbol::parameters.
Referenced by sema::Binder::findFunctionBySignature().
sameMethodDispatchSignature()
bool sema::sameMethodDispatchSignature (const FunctionSymbol & lhs, const FunctionSymbol & rhs)
Definition at line 685 of file binder.cpp.
{
  const size_t lhsOffset = lhs.isMethod ? 1 : 0;
  const size_t rhsOffset = rhs.isMethod ? 1 : 0;
  if (lhs.parameters.size() < lhsOffset || rhs.parameters.size() < rhsOffset) {
    return false;
  }
  if (lhs.parameters.size() - lhsOffset != rhs.parameters.size() - rhsOffset ||
      lhs.isCVariadic != rhs.isCVariadic) {
    return false;
  }
  for (size_t i = 0; i + lhsOffset < lhs.parameters.size(); ++i) {
    const auto &left = lhs.parameters[i + lhsOffset];
    const auto &right = rhs.parameters[i + rhsOffset];
    if (left->is_ref != right->is_ref ||
        left->is_variadic_pack != right->is_variadic_pack || !left->type ||
        !right->type || left->type->toString() != right->type->toString()) {
      return false;
    }
  }
  return true;
}
References sema::FunctionSymbol::isCVariadic, sema::FunctionSymbol::isMethod, and sema::FunctionSymbol::parameters.
Referenced by sema::Binder::findOverriddenVtableSlot().
sanitizeTypeName()
std::string sema::sanitizeTypeName (const std::string & value)
Definition at line 124 of file binder.cpp.
{
  std::string out;
  out.reserve(value.size());
  for (char ch : value) {
    if (std::isalnum(static_cast<unsigned char>(ch))) {
      out.push_back(ch);
    } else {
      out.push_back('_');
    }
  }
  return out;
}
Referenced by abiTypeKey(), sema::Binder::ensureGenericFunctionInstantiation(), sema::Binder::instantiateGenericTypeSymbol(), makeVariadicViewType(), sema::Binder::mangleFunctionName(), renderGenericCodegenName(), and sema::Binder::substituteGenericType().
splitQualified()
std::vector< std::string > sema::splitQualified (const std::string & value)
Definition at line 251 of file binder.cpp.
{
  std::vector<std::string> parts;
  std::stringstream ss(value);
  std::string item;
  while (std::getline(ss, item, '.')) {
    if (!item.empty()) {
      parts.push_back(item);
    }
  }
  return parts;
}
Referenced by sema::Binder::visit().
stmtAlwaysReturns()
bool sema::stmtAlwaysReturns (const BoundStatement * stmt)
Definition at line 328 of file binder.cpp.
{
  if (!stmt)
    return false;
  if (dynamic_cast<const BoundReturnStatement *>(stmt))
    return true;
  if (auto *blk = dynamic_cast<const BoundBlock *>(stmt))
    return blockAlwaysReturns(blk);
  if (auto *ifStmt = dynamic_cast<const BoundIfStatement *>(stmt))
    return ifStmt->elseBody && blockAlwaysReturns(ifStmt->thenBody.get()) &&
           blockAlwaysReturns(ifStmt->elseBody.get());
  return false;
}
References blockAlwaysReturns().
Referenced by blockAlwaysReturns().