ZAP: zap::DiagnosticEngine Class Reference
zap::DiagnosticEngine Class Reference
#include <diagnostics.hpp>
Public Member Functions
DiagnosticEngine (const std::string &src, const std::string &fname="input")
void registerSource (const std::string &name, const std::string &text)
void report (SourceSpan span, DiagnosticLevel level, const std::string &message)
void report (SourceSpan span, DiagnosticLevel level, const std::string &code, const std::string &message)
bool hadErrors () const
bool empty () const
const std::vector< Diagnostic > & diagnostics () const
const std::string & sourceText () const
const std::string & sourceName () const
void printText (std::ostream &os) const
void printText (Stream &os) const
std::string toJson () const
Private Member Functions
void addNote (SourceSpan span, const std::string &message)
void maybeAddHelpHint (SourceSpan span, const std::string &message)
const std::string & sourceFor (const SourceSpan &span) const
std::string fileNameFor (const SourceSpan &span) const
DiagnosticRange makeRange (SourceSpan span, const std::string &rangeSource) const
Static Private Member Functions
static std::string defaultCodeFor (DiagnosticLevel level, const std::string &message)
static std::string levelToString (DiagnosticLevel level)
static void appendJsonEscaped (std::string &json, const std::string &value)
static void appendJsonField (std::string &json, const std::string &key, const std::string &value)
static void appendJsonPosition (std::string &json, const DiagnosticPosition &p)
Private Attributes
const std::string & source
std::string fileName
std::unordered_map< std::string, std::string > sources_
std::vector< Diagnostic > diagnostics_
size_t errorCount = 0
bool errorCapReached_ = false
Static Private Attributes
static constexpr size_t MAX_ERRORS = 50
static constexpr size_t MAX_DIAGNOSTICS = 200
Detailed Description
Definition at line 403 of file diagnostics.hpp.
Constructor & Destructor Documentation
DiagnosticEngine()
zap::DiagnosticEngine::DiagnosticEngine (const std::string & src, const std::string & fname = "input") inline
Definition at line 416 of file diagnostics.hpp.
      : source(src), fileName(fname) {
    sources_[fileName] = source;
  }
References fileName, source, and sources_.
Member Function Documentation
addNote()
void zap::DiagnosticEngine::addNote (SourceSpan span, const std::string & message) inline private
Definition at line 522 of file diagnostics.hpp.
{
    for (const auto &existing : diagnostics_) {
      if (existing.level == DiagnosticLevel::Note &&
          existing.message == message && existing.span.line == span.line &&
          existing.span.column == span.column &&
          existing.span.offset == span.offset &&
          existing.span.length == span.length) {
        return;
      }
    }
    if (diagnostics_.size() >= MAX_DIAGNOSTICS) {
      return;
    }
    const auto &noteSource = sourceFor(span);
    diagnostics_.push_back(Diagnostic{
        DiagnosticLevel::Note, defaultCodeFor(DiagnosticLevel::Note, message),
        message, fileNameFor(span), noteSource, span,
        makeRange(span, noteSource)});
  }
References SourceSpan::column, defaultCodeFor(), diagnostics_, fileNameFor(), SourceSpan::length, SourceSpan::line, makeRange(), MAX_DIAGNOSTICS, zap::Note, SourceSpan::offset, and sourceFor().
Referenced by maybeAddHelpHint().
appendJsonEscaped()
void zap::DiagnosticEngine::appendJsonEscaped (std::string & json, const std::string & value) inline static private
Definition at line 728 of file diagnostics.hpp.
{
    json += '"';
    for (char ch : value) {
      switch (ch) {
      case '\\':
        json += "\\\\";
        break;
      case '"':
        json += "\\\"";
        break;
      case '\n':
        json += "\\n";
        break;
      case '\r':
        json += "\\r";
        break;
      case '\t':
        json += "\\t";
        break;
      default:
        json += ch;
        break;
      }
    }
    json += '"';
  }
Referenced by appendJsonField().
appendJsonField()
void zap::DiagnosticEngine::appendJsonField (std::string & json, const std::string & key, const std::string & value) inline static private
Definition at line 755 of file diagnostics.hpp.
{
    appendJsonEscaped(json, key);
    json += ":";
    appendJsonEscaped(json, value);
  }
References appendJsonEscaped().
Referenced by toJson().
appendJsonPosition()
void zap::DiagnosticEngine::appendJsonPosition (std::string & json, const DiagnosticPosition & p) inline static private
Definition at line 762 of file diagnostics.hpp.
{
    json += "{";
    json += "\"line\":";
    json += std::to_string(p.line);
    json += ",\"column\":";
    json += std::to_string(p.column);
    json += ",\"offset\":";
    json += std::to_string(p.offset);
    json += "}";
  }
References zap::DiagnosticPosition::column, zap::DiagnosticPosition::line, and zap::DiagnosticPosition::offset.
Referenced by toJson().
defaultCodeFor()
std::string zap::DiagnosticEngine::defaultCodeFor (DiagnosticLevel level, const std::string & message) inline static private
Definition at line 584 of file diagnostics.hpp.
{
    if (level == DiagnosticLevel::Warning) {
      if (message.find("has non-void return type but no return") !=
          std::string::npos) {
        return "W1001";
      }
      return "W0000";
    }
    if (level == DiagnosticLevel::Note) {
      if (message.find("help:") == 0) {
        return "N1000";
      }
      if (message.find("Too many errors emitted; stopping after") !=
          std::string::npos) {
        return "N1001";
      }
      return "N0000";
    }
    // More specific semantic diagnostics must be checked before generic parser
    // "Expected ... but got ..." classification.
    if (message.find("Undefined identifier") != std::string::npos) {
      return "S2001";
    }
    if (message.find("Cannot assign expression of type") != std::string::npos ||
        message.find("Cannot assign type") != std::string::npos) {
      return "S2002";
    }
    if (message.find("If condition must be Bool") != std::string::npos ||
        message.find("While condition must be Bool") != std::string::npos ||
        message.find("Ternary condition must be Bool") != std::string::npos) {
      return "S2003";
    }
    if (message.find("Cannot compare") != std::string::npos) {
      return "S2004";
    }
    if (message.find("Operator '") != std::string::npos &&
        message.find("cannot be applied") != std::string::npos) {
      return "S2005";
    }
    if (message.find("Cannot cast from '") != std::string::npos) {
      return "S2006";
    }
    if (message.find("does not support indexing") != std::string::npos) {
      return "S2007";
    }
    if (message.find("Array index must be an integer") != std::string::npos) {
      return "S2008";
    }
    if (message.find("Array elements must have the same type") !=
        std::string::npos) {
      return "S2009";
    }
    if (message.find("Cannot dereference non-pointer type") !=
        std::string::npos) {
      return "S2010";
    }
    if (message.find("Weak references cannot") != std::string::npos) {
      return "S2011";
    }
    if (message.find("No matching overload for function") !=
        std::string::npos) {
      return "S2012";
    }
    if (message.find("Call to function '") != std::string::npos &&
        message.find("' is ambiguous between ") != std::string::npos) {
      return "S2013";
    }
    if (message.find("Expected ';'") != std::string::npos) {
      return "P1001";
    }
    if (message.find("Expected primary expression") != std::string::npos) {
      return "P1002";
    }
    if (message.find("Unexpected token") != std::string::npos) {
      return "P1003";
    }
    if (message.find("Expected ") != std::string::npos &&
        message.find(" but got ") != std::string::npos) {
      return "P1004";
    }
    if (message.find("reached end of file") != std::string::npos) {
      return "P1005";
    }
    return "E0000";
  }
References zap::Note, and zap::Warning.
Referenced by addNote(), and report().
diagnostics()
const std::vector< Diagnostic > & zap::DiagnosticEngine::diagnostics () const inline
Definition at line 481 of file diagnostics.hpp.
{ return diagnostics_; }
References diagnostics_.
Referenced by zap::lsp::Workspace::analyze(), and zap::lsp::Workspace::loadModuleGraph().
empty()
bool zap::DiagnosticEngine::empty () const inline
Definition at line 479 of file diagnostics.hpp.
{ return diagnostics_.empty(); }
References diagnostics_.
fileNameFor()
std::string zap::DiagnosticEngine::fileNameFor (const SourceSpan & span) const inline private
Definition at line 696 of file diagnostics.hpp.
{
    return span.sourceName.empty() ? fileName : span.sourceName;
  }
References fileName, and SourceSpan::sourceName.
Referenced by addNote(), and report().
hadErrors()
bool zap::DiagnosticEngine::hadErrors () const inline
Definition at line 477 of file diagnostics.hpp.
{ return errorCount > 0; }
References errorCount.
Referenced by zap::driver::compileSourceFile(), zap::anonymous_namespace{driver.cpp}::loadModuleGraph(), and zap::lsp::Workspace::loadModuleGraph().
levelToString()
std::string zap::DiagnosticEngine::levelToString (DiagnosticLevel level) inline static private
Definition at line 674 of file diagnostics.hpp.
{
    switch (level) {
    case DiagnosticLevel::Note:
      return "note";
    case DiagnosticLevel::Warning:
      return "warning";
    case DiagnosticLevel::Error:
      return "error";
    }
    return "unknown";
  }
References zap::Error, zap::Note, and zap::Warning.
Referenced by toJson().
makeRange()
DiagnosticRange zap::DiagnosticEngine::makeRange (SourceSpan span, const std::string & rangeSource) const inline private
Definition at line 700 of file diagnostics.hpp.
{
    DiagnosticPosition start{span.line, span.column, span.offset};
    size_t endOffset = std::min(span.offset, rangeSource.size());
    size_t remaining = span.length;
    size_t line = start.line;
    size_t column = start.column;
    while (endOffset < rangeSource.size() && remaining > 0) {
      if (rangeSource[endOffset] == '\n') {
        ++line;
        column = 1;
      } else {
        ++column;
      }
      ++endOffset;
      --remaining;
    }
    if (span.length == 0) {
      ++column;
    }
    return DiagnosticRange{start, DiagnosticPosition{line, column, endOffset}};
  }
References SourceSpan::column, zap::DiagnosticPosition::column, SourceSpan::length, SourceSpan::line, zap::DiagnosticPosition::line, and SourceSpan::offset.
Referenced by addNote(), and report().
maybeAddHelpHint()
void zap::DiagnosticEngine::maybeAddHelpHint (SourceSpan span, const std::string & message) inline private
Definition at line 544 of file diagnostics.hpp.
{
    if (message.find("Expected ';'") != std::string::npos) {
      addNote(span, "help: add ';' at the end of the statement.");
      return;
    }
    if (message.find("Expected primary expression") != std::string::npos) {
      addNote(
          span,
          "help: insert an expression (identifier, literal, or call) here.");
      return;
    }
    if (message.find("Undefined identifier") != std::string::npos) {
      addNote(span,
              "help: check spelling or declare the identifier before use.");
      return;
    }
    if (message.find("Cannot assign expression of type") != std::string::npos) {
      addNote(span, "help: change the variable type or cast/convert the "
                    "assigned expression.");
      return;
    }
    if (message.find("If condition must be Bool") != std::string::npos ||
        message.find("While condition must be Bool") != std::string::npos) {
      addNote(span,
              "help: use a Bool expression, e.g. comparison like 'x != 0'.");
      return;
    }
    if (message.find("Cannot compare") != std::string::npos) {
      addNote(
          span,
          "help: ensure both operands are comparable and of compatible types.");
      return;
    }
  }
References addNote().
Referenced by report().
printText() [1/2]
void zap::DiagnosticEngine::printText (std::ostream & os) const inline
Definition at line 487 of file diagnostics.hpp.
{
    DiagnosticTextFormatter::print(os, diagnostics_);
  }
References diagnostics_, and zap::DiagnosticTextFormatter::print().
Referenced by zap::driver::compileLoadedModules, zap::driver::compileSourceFile(), and zap::anonymous_namespace{driver.cpp}::loadModuleGraph().
printText() [2/2]
void zap::DiagnosticEngine::printText (Stream & os) const inline
Definition at line 491 of file diagnostics.hpp.
{
    DiagnosticTextFormatter::print(os, diagnostics_);
  }
References diagnostics_, and zap::DiagnosticTextFormatter::print().
registerSource()
void zap::DiagnosticEngine::registerSource (const std::string & name, const std::string & text) inline
Definition at line 421 of file diagnostics.hpp.
{
    if (!name.empty()) {
      sources_[name] = text;
    }
  }
References sources_.
Referenced by zap::lsp::Workspace::analyze(), zap::driver::compileLoadedModules, and zap::lsp::Workspace::loadProject().
report() [1/2]
void zap::DiagnosticEngine::report (SourceSpan span, DiagnosticLevel level, const std::string & code, const std::string & message) inline
Definition at line 432 of file diagnostics.hpp.
{
    // Deduplicate identical diagnostics (same level, message and span).
    for (const auto &existing : diagnostics_) {
      if (existing.level == level && existing.message == message &&
          existing.span.line == span.line &&
          existing.span.column == span.column &&
          existing.span.offset == span.offset &&
          existing.span.length == span.length) {
        return;
      }
    }
    // Stop flooding on errors, but emit one explanatory note once.
    if (level == DiagnosticLevel::Error && errorCount >= MAX_ERRORS) {
      if (!errorCapReached_) {
        errorCapReached_ = true;
        const SourceSpan capSpan = span;
        const auto &capSource = sourceFor(capSpan);
        diagnostics_.push_back(Diagnostic{
            DiagnosticLevel::Note, "N0001",
            "Too many errors emitted; stopping after " +
                std::to_string(MAX_ERRORS) +
                " errors. Fix the first errors and re-run for more details.",
            fileNameFor(capSpan), capSource, capSpan,
            makeRange(capSpan, capSource)});
      }
      return;
    }
    if (diagnostics_.size() >= MAX_DIAGNOSTICS) {
      return;
    }
    const auto &diagnosticSource = sourceFor(span);
    diagnostics_.push_back(Diagnostic{level, code, message, fileNameFor(span),
                                      diagnosticSource, span,
                                      makeRange(span, diagnosticSource)});
    if (level == DiagnosticLevel::Error) {
      ++errorCount;
      maybeAddHelpHint(span, message);
    }
  }
References SourceSpan::column, diagnostics_, zap::Error, errorCapReached_, errorCount, fileNameFor(), SourceSpan::length, SourceSpan::line, makeRange(), MAX_DIAGNOSTICS, MAX_ERRORS, maybeAddHelpHint(), zap::Note, SourceSpan::offset, and sourceFor().
report() [2/2]
void zap::DiagnosticEngine::report (SourceSpan span, DiagnosticLevel level, const std::string & message) inline
Definition at line 427 of file diagnostics.hpp.
{
    report(span, level, defaultCodeFor(level, message), message);
  }
References defaultCodeFor(), and report().
Referenced by report().
sourceFor()
const std::string & zap::DiagnosticEngine::sourceFor (const SourceSpan & span) const inline private
Definition at line 686 of file diagnostics.hpp.
{
    const std::string &name =
        span.sourceName.empty() ? fileName : span.sourceName;
    auto it = sources_.find(name);
    if (it != sources_.end()) {
      return it->second;
    }
    return source;
  }
References fileName, source, SourceSpan::sourceName, and sources_.
Referenced by addNote(), and report().
sourceName()
const std::string & zap::DiagnosticEngine::sourceName () const inline
Definition at line 485 of file diagnostics.hpp.
{ return fileName; }
References fileName.
sourceText()
const std::string & zap::DiagnosticEngine::sourceText () const inline
Definition at line 483 of file diagnostics.hpp.
{ return source; }
References source.
toJson()
std::string zap::DiagnosticEngine::toJson () const inline
Definition at line 495 of file diagnostics.hpp.
{
    std::string json = "[";
    for (size_t i = 0; i < diagnostics_.size(); ++i) {
      if (i > 0)
        json += ',';
      const auto &d = diagnostics_[i];
      json += "{";
      appendJsonField(json, "level", levelToString(d.level));
      json += ",";
      appendJsonField(json, "message", d.message);
      json += ",";
      appendJsonField(json, "code", d.code);
      json += ",";
      appendJsonField(json, "fileName", d.fileName);
      json += ",\"range\":{";
      json += "\"start\":";
      appendJsonPosition(json, d.range.start);
      json += ",\"end\":";
      appendJsonPosition(json, d.range.end);
      json += "}}";
    }
    json += "]";
    return json;
  }
References appendJsonField(), appendJsonPosition(), diagnostics_, and levelToString().
Member Data Documentation
diagnostics_
std::vector<Diagnostic> zap::DiagnosticEngine::diagnostics_ private
Definition at line 408 of file diagnostics.hpp.
Referenced by addNote(), diagnostics(), empty(), printText(), printText(), report(), and toJson().
errorCapReached_
bool zap::DiagnosticEngine::errorCapReached_ = false private
Definition at line 410 of file diagnostics.hpp.
Referenced by report().
errorCount
size_t zap::DiagnosticEngine::errorCount = 0 private
Definition at line 409 of file diagnostics.hpp.
Referenced by hadErrors(), and report().
fileName
std::string zap::DiagnosticEngine::fileName private
Definition at line 406 of file diagnostics.hpp.
Referenced by DiagnosticEngine(), fileNameFor(), sourceFor(), and sourceName().
MAX_DIAGNOSTICS
size_t zap::DiagnosticEngine::MAX_DIAGNOSTICS = 200 static constexpr private
Definition at line 413 of file diagnostics.hpp.
Referenced by addNote(), and report().
MAX_ERRORS
size_t zap::DiagnosticEngine::MAX_ERRORS = 50 static constexpr private
Definition at line 412 of file diagnostics.hpp.
Referenced by report().
source
const std::string& zap::DiagnosticEngine::source private
Definition at line 405 of file diagnostics.hpp.
Referenced by DiagnosticEngine(), sourceFor(), and sourceText().
sources_
std::unordered_map<std::string, std::string> zap::DiagnosticEngine::sources_ private
Definition at line 407 of file diagnostics.hpp.
Referenced by DiagnosticEngine(), registerSource(), and sourceFor().
The documentation for this class was generated from the following file:
src/utils/diagnostics.hpp