ZAP: zap::lsp::Workspace Class Reference
zap::lsp::Workspace Class Reference
#include <workspace.hpp>
Classes
struct CachedFile
Public Member Functions
const DocumentState * document (const std::string &uri) const
void open (const std::string &uri, std::filesystem::path path, std::string text, int64_t version)
void update (const std::string &uri, std::string text, int64_t version)
void close (const std::string &uri)
bool contains (const std::string &uri) const
std::optional< ProjectState > loadProject (const std::string &uri, bool allowEntryErrors=false) const
AnalysisResult analyze (const std::string &uri) const
Private Member Functions
zap::frontend::RuntimePaths runtimePaths () const
std::optional< std::string > sourceForPath (const std::filesystem::path &path) const
bool loadModuleGraph (const std::filesystem::path &modulePath, std::map< std::string, std::unique_ptr< sema::ModuleInfo > > &modules, std::set< std::string > &visiting, AnalysisResult &result, const std::string &entryUri, const zap::args::ImportMap &importMap, bool allowEntryErrors=false) const
Private Attributes
std::unordered_map< std::string, DocumentState > documentsByUri_
std::unordered_map< std::string, std::string > uriByCanonicalPath_
std::unordered_map< std::string, CachedFile > fileContentCache_
Detailed Description
Definition at line 17 of file workspace.hpp.
Member Function Documentation
analyze()
AnalysisResult zap::lsp::Workspace::analyze (const std::string & uri) const
Definition at line 248 of file workspace.cpp.
{
  AnalysisResult result;
  auto docIt = documentsByUri_.find(uri);
  if (docIt == documentsByUri_.end()) {
    return result;
  }
  auto flags = findAndReadFlags(docIt->second.path);
  std::map<std::string, std::unique_ptr<sema::ModuleInfo>> moduleMap;
  std::set<std::string> visiting;
  if (!loadModuleGraph(docIt->second.path, moduleMap, visiting, result, uri,
                       flags.importMap, false)) {
    if (result.diagnosticsByUri.find(uri) == result.diagnosticsByUri.end()) {
      result.diagnosticsByUri[uri] = {};
    }
    return result;
  }
  std::string entryId =
      std::filesystem::weakly_canonical(docIt->second.path).string();
  auto entrySource = sourceForPath(docIt->second.path);
  if (!entrySource) {
    result.diagnosticsByUri[uri] = {};
    return result;
  }
  auto entryModuleIt = moduleMap.find(entryId);
  if (entryModuleIt == moduleMap.end()) {
    return result;
  }
  entryModuleIt->second->isEntry = true;
  zap::DiagnosticEngine diagnostics(*entrySource, docIt->second.path.string());
  std::vector<sema::ModuleInfo> modules;
  modules.reserve(moduleMap.size());
  for (auto &[_, modulePtr] : moduleMap) {
    diagnostics.registerSource(modulePtr->sourceName, modulePtr->sourceText);
    modules.push_back(std::move(*modulePtr));
  }
  sema::Binder binder(diagnostics);
  auto boundAst = binder.bind(modules);
  (void)boundAst;
  result.diagnosticsByUri[uri] = diagnostics.diagnostics();
  return result;
}
References sema::Binder::bind(), zap::DiagnosticEngine::diagnostics(), zap::lsp::AnalysisResult::diagnosticsByUri, documentsByUri_, zap::lsp::findAndReadFlags(), loadModuleGraph(), zap::DiagnosticEngine::registerSource(), and sourceForPath().
Referenced by main().
close()
void zap::lsp::Workspace::close (const std::string & uri)
Definition at line 174 of file workspace.cpp.
{
  auto it = documentsByUri_.find(uri);
  if (it == documentsByUri_.end()) {
    return;
  }
  std::string canonicalKey = it->second.path.string();
  auto pathIt = uriByCanonicalPath_.find(canonicalKey);
  if (pathIt != uriByCanonicalPath_.end() && pathIt->second == uri) {
    uriByCanonicalPath_.erase(pathIt);
  }
  documentsByUri_.erase(it);
}
References documentsByUri_, and uriByCanonicalPath_.
Referenced by main().
contains()
bool zap::lsp::Workspace::contains (const std::string & uri) const
Definition at line 189 of file workspace.cpp.
{
  return documentsByUri_.find(uri) != documentsByUri_.end();
}
References documentsByUri_.
Referenced by main().
document()
const DocumentState * zap::lsp::Workspace::document (const std::string & uri) const
Definition at line 141 of file workspace.cpp.
{
  auto it = documentsByUri_.find(uri);
  return it == documentsByUri_.end() ? nullptr : &it->second;
}
References documentsByUri_.
Referenced by main(), and zap::lsp::resolveDefinition().
loadModuleGraph()
bool zap::lsp::Workspace::loadModuleGraph (const std::filesystem::path & modulePath, std::map< std::string, std::unique_ptr< sema::ModuleInfo > > & modules, std::set< std::string > & visiting, AnalysisResult & result, const std::string & entryUri, const zap::args::ImportMap & importMap, bool allowEntryErrors = false) const private
Definition at line 49 of file workspace.cpp.
{
  std::filesystem::path canonicalPath =
      std::filesystem::weakly_canonical(modulePath);
  std::string moduleId = canonicalPath.string();
  std::string entryModuleId =
      std::filesystem::weakly_canonical(documentsByUri_.at(entryUri).path)
          .string();
  bool isEntryModule = moduleId == entryModuleId;
  if (modules.find(moduleId) != modules.end()) {
    return true;
  }
  if (visiting.count(moduleId)) {
    return false;
  }
  visiting.insert(moduleId);
  auto source = sourceForPath(canonicalPath);
  if (!source) {
    visiting.erase(moduleId);
    return false;
  }
  zap::DiagnosticEngine diagnostics(*source, canonicalPath.string());
  Lexer lex(diagnostics);
  auto tokens = lex.tokenize(*source);
  zap::Parser parser(tokens, diagnostics);
  auto ast = parser.parse();
  auto uriIt = uriByCanonicalPath_.find(moduleId);
  if (uriIt != uriByCanonicalPath_.end()) {
    result.diagnosticsByUri[uriIt->second] = diagnostics.diagnostics();
  } else if (moduleId == std::filesystem::weakly_canonical(
                             documentsByUri_.at(entryUri).path)
                             .string()) {
    result.diagnosticsByUri[entryUri] = diagnostics.diagnostics();
  }
  if (!ast ||
      (diagnostics.hadErrors() && !(allowEntryErrors && isEntryModule))) {
    visiting.erase(moduleId);
    return false;
  }
  auto module = std::make_unique<sema::ModuleInfo>();
  module->moduleId = moduleId;
  module->moduleName = canonicalPath.stem().string();
  module->linkPath = zap::frontend::computeLogicalModulePath(
      canonicalPath, runtimePaths(), importMap);
  module->sourceName = canonicalPath.string();
  module->sourceText = *source;
  module->root = std::move(ast);
  zap::frontend::injectImplicitPreludeImportIfNeeded(*module, true);
  for (const auto &child : module->root->children) {
    auto importNode = dynamic_cast<ImportNode *>(child.get());
    if (!importNode) {
      continue;
    }
    std::vector<std::filesystem::path> importTargets;
    if (!zap::frontend::resolveImportTargets(canonicalPath, *importNode,
                                             importTargets, importMap,
                                             runtimePaths())) {
      continue;
    }
    module->imports.push_back(
        zap::frontend::makeResolvedImport(*importNode, importTargets));
  }
  for (const auto &import : module->imports) {
    for (const auto &targetId : import.targetModuleIds) {
      if (!loadModuleGraph(targetId, modules, visiting, result, entryUri,
                           importMap, allowEntryErrors)) {
        visiting.erase(moduleId);
        return false;
      }
    }
  }
  visiting.erase(moduleId);
  modules[moduleId] = std::move(module);
  return true;
}
References zap::DiagnosticEngine::diagnostics(), zap::lsp::AnalysisResult::diagnosticsByUri, documentsByUri_, zap::DiagnosticEngine::hadErrors(), zap::frontend::injectImplicitPreludeImportIfNeeded(), loadModuleGraph(), zap::Parser::parse(), zap::frontend::resolveImportTargets(), runtimePaths(), sourceForPath(), Lexer::tokenize(), and uriByCanonicalPath_.
Referenced by analyze(), loadModuleGraph(), and loadProject().
loadProject()
std::optional< ProjectState > zap::lsp::Workspace::loadProject (const std::string & uri, bool allowEntryErrors = false) const
Definition at line 194 of file workspace.cpp.
{
  auto docIt = documentsByUri_.find(uri);
  if (docIt == documentsByUri_.end()) {
    return std::nullopt;
  }
  auto flags = findAndReadFlags(docIt->second.path);
  ProjectState state;
  std::set<std::string> visiting;
  if (!loadModuleGraph(docIt->second.path, state.moduleMap, visiting,
                       state.analysis, uri, flags.importMap,
                       allowEntryErrors)) {
    if (state.analysis.diagnosticsByUri.find(uri) ==
        state.analysis.diagnosticsByUri.end()) {
      state.analysis.diagnosticsByUri[uri] = {};
    }
    return state;
  }
  for (const auto &[moduleId, _] : state.moduleMap) {
    auto uriIt = uriByCanonicalPath_.find(moduleId);
    if (uriIt != uriByCanonicalPath_.end()) {
      state.uriByModuleId[moduleId] = uriIt->second;
    } else {
      state.uriByModuleId[moduleId] = pathToUri(moduleId);
    }
  }
  auto entrySource = sourceForPath(docIt->second.path);
  if (entrySource) {
    auto entryId =
        std::filesystem::weakly_canonical(docIt->second.path).string();
    auto entryModuleIt = state.moduleMap.find(entryId);
    if (entryModuleIt != state.moduleMap.end()) {
      entryModuleIt->second->isEntry = true;
    }
    zap::DiagnosticEngine diagnostics(*entrySource,
                                      docIt->second.path.string());
    std::vector<sema::ModuleInfo *> modules;
    modules.reserve(state.moduleMap.size());
    for (auto &[_, modulePtr] : state.moduleMap) {
      diagnostics.registerSource(modulePtr->sourceName, modulePtr->sourceText);
      modules.push_back(modulePtr.get());
    }
    sema::Binder binder(diagnostics, true, &state.semanticInfo);
    auto boundAst = binder.bind(std::move(modules));
    (void)boundAst;
  }
  return state;
}
References zap::lsp::ProjectState::analysis, sema::Binder::bind(), zap::lsp::AnalysisResult::diagnosticsByUri, documentsByUri_, zap::lsp::findAndReadFlags(), loadModuleGraph(), zap::lsp::ProjectState::moduleMap, zap::lsp::pathToUri(), zap::DiagnosticEngine::registerSource(), zap::lsp::ProjectState::semanticInfo, sourceForPath(), uriByCanonicalPath_, and zap::lsp::ProjectState::uriByModuleId.
Referenced by main().
open()
void zap::lsp::Workspace::open (const std::string & uri, std::filesystem::path path, std::string text, int64_t version)
Definition at line 146 of file workspace.cpp.
{
  std::filesystem::path canonicalPath = std::filesystem::weakly_canonical(path);
  std::string canonicalKey = canonicalPath.string();
  auto existingUriIt = uriByCanonicalPath_.find(canonicalKey);
  if (existingUriIt != uriByCanonicalPath_.end() &&
      existingUriIt->second != uri) {
    documentsByUri_.erase(existingUriIt->second);
    existingUriIt->second = uri;
  } else {
    uriByCanonicalPath_[canonicalKey] = uri;
  }
  documentsByUri_[uri] =
      DocumentState{uri, std::move(canonicalPath), std::move(text), version};
}
References documentsByUri_, and uriByCanonicalPath_.
Referenced by main().
runtimePaths()
zap::frontend::RuntimePaths zap::lsp::Workspace::runtimePaths () const private
Definition at line 12 of file workspace.cpp.
{
  return zap::frontend::RuntimePaths{
      std::filesystem::path(), std::filesystem::path(ZAPC_CORE_DIR),
      std::filesystem::path(ZAPC_STDLIB_DIR), std::filesystem::path()};
}
Referenced by loadModuleGraph().
sourceForPath()
std::optional< std::string > zap::lsp::Workspace::sourceForPath (const std::filesystem::path & path) const private
Definition at line 19 of file workspace.cpp.
{
  std::string key = std::filesystem::weakly_canonical(path).string();
  auto uriIt = uriByCanonicalPath_.find(key);
  if (uriIt != uriByCanonicalPath_.end()) {
    auto docIt = documentsByUri_.find(uriIt->second);
    if (docIt != documentsByUri_.end()) {
      return docIt->second.text;
    }
  }
  std::error_code ec;
  auto writeTime = std::filesystem::last_write_time(path, ec);
  if (!ec) {
    auto cacheIt = fileContentCache_.find(key);
    if (cacheIt != fileContentCache_.end() &&
        cacheIt->second.lastWriteTime == writeTime) {
      return cacheIt->second.content;
    }
  }
  std::string content;
  if (!readSourceFile(path, content)) {
    return std::nullopt;
  }
  if (!ec) {
    fileContentCache_[key] = CachedFile{writeTime, content};
  }
  return content;
}
References documentsByUri_, fileContentCache_, zap::lsp::readSourceFile(), and uriByCanonicalPath_.
Referenced by analyze(), loadModuleGraph(), and loadProject().
update()
void zap::lsp::Workspace::update (const std::string & uri, std::string text, int64_t version)
Definition at line 164 of file workspace.cpp.
{
  auto it = documentsByUri_.find(uri);
  if (it == documentsByUri_.end()) {
    return;
  }
  it->second.text = std::move(text);
  it->second.version = version;
}
References documentsByUri_.
Referenced by main().
Member Data Documentation
documentsByUri_
std::unordered_map<std::string, DocumentState> zap::lsp::Workspace::documentsByUri_ private
Definition at line 23 of file workspace.hpp.
Referenced by analyze(), close(), contains(), document(), loadModuleGraph(), loadProject(), open(), sourceForPath(), and update().
fileContentCache_
std::unordered_map<std::string, CachedFile> zap::lsp::Workspace::fileContentCache_ mutable private
Definition at line 25 of file workspace.hpp.
Referenced by sourceForPath().
uriByCanonicalPath_
std::unordered_map<std::string, std::string> zap::lsp::Workspace::uriByCanonicalPath_ private
Definition at line 24 of file workspace.hpp.
Referenced by close(), loadModuleGraph(), loadProject(), open(), and sourceForPath().
The documentation for this class was generated from the following files:
src/lsp/workspace.hpp
src/lsp/workspace.cpp