ZAP: src/lsp/lsp-main.cpp File Reference
lsp-main.cpp File Reference
#include "lexer/lexer.hpp"
#include "lsp.hpp"
#include "parser/parser.hpp"
#include "sema/binder.hpp"
#include "sema/module_info.hpp"
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <unistd.h>
Classes
struct anonymous_namespace{lsp-main.cpp}::DocumentState
struct anonymous_namespace{lsp-main.cpp}::LspFlags
struct anonymous_namespace{lsp-main.cpp}::AnalysisResult
struct anonymous_namespace{lsp-main.cpp}::ProjectState
struct anonymous_namespace{lsp-main.cpp}::LspSymbol
struct anonymous_namespace{lsp-main.cpp}::LspSignature
struct anonymous_namespace{lsp-main.cpp}::CallContext
struct anonymous_namespace{lsp-main.cpp}::HoverInfo
class anonymous_namespace{lsp-main.cpp}::Workspace
Namespaces
namespace anonymous_namespace{lsp-main.cpp}
Typedefs
using anonymous_namespace{lsp-main.cpp}::JsonObject = zap::lsp::JsonObject
Functions
const JsonObject * anonymous_namespace{lsp-main.cpp}::getField (const JsonObject &object, std::string_view key)
const JsonObject * anonymous_namespace{lsp-main.cpp}::getPath (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::getStringField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< int64_t > anonymous_namespace{lsp-main.cpp}::getIntegerField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::string anonymous_namespace{lsp-main.cpp}::stripSourceExtension (const std::filesystem::path &path)
std::filesystem::path anonymous_namespace{lsp-main.cpp}::stdlibRootPath ()
std::string anonymous_namespace{lsp-main.cpp}::computeLogicalModulePath (const std::filesystem::path &canonicalPath)
std::optional< std::filesystem::path > anonymous_namespace{lsp-main.cpp}::uriToPath (std::string_view uri)
bool anonymous_namespace{lsp-main.cpp}::readSourceFile (const std::filesystem::path &path, std::string &content)
LspFlags anonymous_namespace{lsp-main.cpp}::readFlagsFromFile (const std::filesystem::path &path)
LspFlags anonymous_namespace{lsp-main.cpp}::findAndReadFlags (std::filesystem::path startPath)
bool anonymous_namespace{lsp-main.cpp}::resolveImportTargets (const std::filesystem::path &modulePath, const ImportNode &importNode, std::vector< std::filesystem::path > &targets)
std::string anonymous_namespace{lsp-main.cpp}::effectiveImportAlias (const sema::ResolvedImport &import, const sema::ModuleInfo &target)
size_t anonymous_namespace{lsp-main.cpp}::offsetFromPosition (const std::string &text, int64_t line, int64_t character)
bool anonymous_namespace{lsp-main.cpp}::containsOffset (const SourceSpan &span, size_t offset)
bool anonymous_namespace{lsp-main.cpp}::isIdentifierChar (char ch)
std::string anonymous_namespace{lsp-main.cpp}::pathToUri (const std::filesystem::path &path)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::identifierAt (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > anonymous_namespace{lsp-main.cpp}::memberAccessBeforeCursor (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > anonymous_namespace{lsp-main.cpp}::qualifiedIdentifierAtOffset (const std::string &source, size_t offset)
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::makeSymbol (const std::string &uri, const std::string &name, const SourceSpan &span, int64_t kind, Visibility visibility=Visibility::Private)
std::string anonymous_namespace{lsp-main.cpp}::renderType (const TypeNode *type)
std::string anonymous_namespace{lsp-main.cpp}::renderParameter (const ParameterNode *param)
std::optional< LspSignature > anonymous_namespace{lsp-main.cpp}::signatureForNode (const Node *node)
std::vector< LspSignature > anonymous_namespace{lsp-main.cpp}::findTopLevelSignatures (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::topLevelNameForNode (const Node *node)
const ClassDecl * anonymous_namespace{lsp-main.cpp}::findClassDecl (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
const sema::ModuleInfo * anonymous_namespace{lsp-main.cpp}::findImportedModuleByAlias (const ProjectState &project, const sema::ModuleInfo &module, std::string_view alias)
std::pair< std::string, std::string > anonymous_namespace{lsp-main.cpp}::splitQualifiedName (std::string_view qualifiedName)
const ClassDecl * anonymous_namespace{lsp-main.cpp}::resolveClassByTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName, bool publicOnly=false)
bool anonymous_namespace{lsp-main.cpp}::isClassTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::resolveClassTypeNameFromTypeNode (const ProjectState &project, const sema::ModuleInfo &module, const TypeNode *type)
const ClassDecl * anonymous_namespace{lsp-main.cpp}::enclosingClassAtOffset (const RootNode &root, size_t offset)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::lookupTypeInBody (const ProjectState &project, const sema::ModuleInfo &module, const BodyNode *body, size_t offset, std::string_view name)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::lookupTypeInNode (const ProjectState &project, const sema::ModuleInfo &module, const Node *node, size_t offset, std::string_view name)
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::resolveVariableClassType (const ProjectState &project, const sema::ModuleInfo &module, size_t offset, std::string_view name)
const ParameterNode * anonymous_namespace{lsp-main.cpp}::findClassField (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
const FunDecl * anonymous_namespace{lsp-main.cpp}::findClassMethod (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::hoverForClassMember (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::optional< CallContext > anonymous_namespace{lsp-main.cpp}::callContextAtOffset (const std::string &source, size_t offset)
std::optional< CallContext > anonymous_namespace{lsp-main.cpp}::callContextNearOffset (const std::string &source, size_t offset)
std::vector< LspSignature > anonymous_namespace{lsp-main.cpp}::resolveSignatures (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset, int64_t &activeParameter)
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::hoverForNode (const Node *node)
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::findTopLevelHover (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
JsonObject anonymous_namespace{lsp-main.cpp}::makeHover (const HoverInfo &hover)
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::resolveHover (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset)
JsonObject anonymous_namespace{lsp-main.cpp}::makeSignatureHelp (const std::vector< LspSignature > &signatures, int64_t activeSignature, int64_t activeParameter)
JsonObject anonymous_namespace{lsp-main.cpp}::makeRange (const zap::DiagnosticRange &range)
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::topLevelSymbolForNode (const Node *node, const std::string &uri)
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectTopLevelSymbols (const sema::ModuleInfo &module, const std::string &uri, bool publicOnly=false)
void anonymous_namespace{lsp-main.cpp}::collectLocalsInBody (const BodyNode *body, size_t offset, const std::string &uri, std::vector< LspSymbol > &symbols)
void anonymous_namespace{lsp-main.cpp}::collectLocalsFromNode (const Node *node, size_t offset, const std::string &uri, std::vector< LspSymbol > &symbols)
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectLocalSymbols (const RootNode &root, size_t offset, const std::string &uri)
JsonObject anonymous_namespace{lsp-main.cpp}::makeLocation (const std::string &uri, const SourceSpan &span)
JsonObject anonymous_namespace{lsp-main.cpp}::makeCompletionItem (const LspSymbol &symbol, const std::string &detail="")
JsonObject anonymous_namespace{lsp-main.cpp}::makeResponse (const JsonObject *id, JsonObject result)
JsonObject anonymous_namespace{lsp-main.cpp}::makeNotification (std::string method, JsonObject params)
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectImportedSymbols (const ProjectState &project, const sema::ModuleInfo &module)
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectCompletionSymbols (const std::string &uri, const ProjectState &project, size_t offset)
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::resolveDefinition (const Workspace &workspace, const std::string &uri, const ProjectState &project, size_t offset)
int64_t anonymous_namespace{lsp-main.cpp}::toLspSeverity (zap::DiagnosticLevel level)
JsonObject anonymous_namespace{lsp-main.cpp}::makeDiagnostic (const zap::Diagnostic &diagnostic)
JsonObject anonymous_namespace{lsp-main.cpp}::makePublishDiagnostics (std::string uri, const std::vector< zap::Diagnostic > &diagnostics)
void anonymous_namespace{lsp-main.cpp}::publishAnalysis (Server &server, const AnalysisResult &result)
int main ()
Function Documentation
main()
int main ()
Definition at line 1978 of file lsp-main.cpp.
           {
  std::setvbuf(stdout, nullptr, _IONBF, 0);
  Server server;
  Workspace workspace;
  bool running = true;
  bool shutdownRequested = false;
  std::string line;
  while (running) {
    std::string message = server.processMessage(line);
    if (message.empty()) {
      break;
    }
    JsonRPC rpc(message);
    const JsonObject &request = rpc.object();
    auto method = getStringField(request, {"method"});
    const JsonObject *id = getField(request, "id");
    if (!method) {
      continue;
    }
    if (*method == "initialize") {
      shutdownRequested = false;
      JsonObject::Object syncOptions;
      syncOptions.emplace("openClose", JsonObject(true));
      syncOptions.emplace("change", JsonObject(int64_t(1)));
      JsonObject::Object capabilities;
      capabilities.emplace("textDocumentSync",
                           JsonObject(std::move(syncOptions)));
      capabilities.emplace("definitionProvider", JsonObject(true));
      capabilities.emplace("hoverProvider", JsonObject(true));
      JsonObject::Object completionOptions;
      completionOptions.emplace("resolveProvider", JsonObject(false));
      completionOptions.emplace(
          "triggerCharacters",
          JsonObject(JsonObject::List{
              JsonObject("."), JsonObject("_"), JsonObject("a"),
              JsonObject("b"), JsonObject("c"), JsonObject("d"),
              JsonObject("e"), JsonObject("f"), JsonObject("g"),
              JsonObject("h"), JsonObject("i"), JsonObject("j"),
              JsonObject("k"), JsonObject("l"), JsonObject("m"),
              JsonObject("n"), JsonObject("o"), JsonObject("p"),
              JsonObject("q"), JsonObject("r"), JsonObject("s"),
              JsonObject("t"), JsonObject("u"), JsonObject("v"),
              JsonObject("w"), JsonObject("x"), JsonObject("y"),
              JsonObject("z"), JsonObject("A"), JsonObject("B"),
              JsonObject("C"), JsonObject("D"), JsonObject("E"),
              JsonObject("F"), JsonObject("G"), JsonObject("H"),
              JsonObject("I"), JsonObject("J"), JsonObject("K"),
              JsonObject("L"), JsonObject("M"), JsonObject("N"),
              JsonObject("O"), JsonObject("P"), JsonObject("Q"),
              JsonObject("R"), JsonObject("S"), JsonObject("T"),
              JsonObject("U"), JsonObject("V"), JsonObject("W"),
              JsonObject("X"), JsonObject("Y"), JsonObject("Z")}));
      capabilities.emplace("completionProvider",
                           JsonObject(std::move(completionOptions)));
      JsonObject::Object signatureHelpOptions;
      signatureHelpOptions.emplace(
          "triggerCharacters",
          JsonObject(JsonObject::List{JsonObject("("), JsonObject(",")}));
      capabilities.emplace("signatureHelpProvider",
                           JsonObject(std::move(signatureHelpOptions)));
      JsonObject::Object serverInfo;
      serverInfo.emplace("name", JsonObject("zap-lsp"));
      JsonObject::Object result;
      result.emplace("capabilities", JsonObject(std::move(capabilities)));
      result.emplace("serverInfo", JsonObject(std::move(serverInfo)));
      server.sendMessage(makeResponse(id, JsonObject(std::move(result))));
    } else if (*method == "initialized") {
      continue;
    } else if (*method == "shutdown") {
      shutdownRequested = true;
      server.sendMessage(makeResponse(id, JsonObject(nullptr)));
    } else if (*method == "exit") {
      running = false;
    } else if (*method == "textDocument/didOpen") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto text = getStringField(request, {"params", "textDocument", "text"});
      auto version =
          getIntegerField(request, {"params", "textDocument", "version"})
              .value_or(0);
      if (uri && text) {
        auto path = uriToPath(*uri);
        if (path) {
          workspace.open(*uri, *path, *text, version);
          publishAnalysis(server, workspace.analyze(*uri));
        }
      }
    } else if (*method == "textDocument/didChange") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto version =
          getIntegerField(request, {"params", "textDocument", "version"})
              .value_or(0);
      const JsonObject *changes =
          getPath(request, {"params", "contentChanges"});
      if (uri && changes && changes->isList() &&
          !changes->getAsList().empty()) {
        const JsonObject &lastChange = changes->getAsList().back();
        auto text = getStringField(lastChange, {"text"});
        if (text && workspace.contains(*uri)) {
          workspace.update(*uri, *text, version);
          publishAnalysis(server, workspace.analyze(*uri));
        }
      }
    } else if (*method == "textDocument/didClose") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      if (uri) {
        workspace.close(*uri);
        server.sendMessage(makePublishDiagnostics(*uri, {}));
      }
    } else if (*method == "textDocument/completion") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto line = getIntegerField(request, {"params", "position", "line"});
      auto character =
          getIntegerField(request, {"params", "position", "character"});
      if (id && uri && line && character) {
        JsonObject::List items;
        if (const auto *document = workspace.document(*uri)) {
          auto project = workspace.loadProject(*uri, true);
          if (project) {
            size_t offset =
                offsetFromPosition(document->text, *line, *character);
            if (auto member =
                    memberAccessBeforeCursor(document->text, offset)) {
              const auto &[base, _] = *member;
              std::string moduleId;
              auto path = uriToPath(*uri);
              if (path) {
                moduleId = std::filesystem::weakly_canonical(*path).string();
              }
              auto moduleIt = project->moduleMap.find(moduleId);
              if (moduleIt != project->moduleMap.end()) {
                for (const auto &import : moduleIt->second->imports) {
                  for (const auto &targetId : import.targetModuleIds) {
                    auto targetIt = project->moduleMap.find(targetId);
                    if (targetIt == project->moduleMap.end()) {
                      continue;
                    }
                    if (effectiveImportAlias(import, *targetIt->second) !=
                        base) {
                      continue;
                    }
                    auto targetUriIt = project->uriByModuleId.find(targetId);
                    std::string targetUri =
                        targetUriIt == project->uriByModuleId.end()
                            ? pathToUri(targetId)
                            : targetUriIt->second;
                    for (const auto &symbol : collectTopLevelSymbols(
                             *targetIt->second, targetUri, true)) {
                      items.push_back(
                          makeCompletionItem(symbol, "imported member"));
                    }
                  }
                }
                if (base.find('.') == std::string::npos) {
                  if (auto classType = resolveVariableClassType(
                          *project, *moduleIt->second, offset, base)) {
                    if (auto cls = resolveClassByTypeName(
                            *project, *moduleIt->second, *classType)) {
                      std::set<std::string> seenMembers;
                      const ClassDecl *current = cls;
                      while (current) {
                        for (const auto &field : current->fields_) {
                          if (!field ||
                              !seenMembers.insert(field->name).second) {
                            continue;
                          }
                          items.push_back(makeCompletionItem(
                              *makeSymbol(*uri, field->name, field->span, 8,
                                          field->visibility_),
                              "field"));
                        }
                        for (const auto &method : current->methods_) {
                          if (!method ||
                              !seenMembers.insert(method->name_).second) {
                            continue;
                          }
                          auto detail = method->name_;
                          if (auto signature = signatureForNode(method.get())) {
                            detail = signature->label;
                          }
                          items.push_back(makeCompletionItem(
                              *makeSymbol(*uri, method->name_, method->span, 2,
                                          method->visibility_),
                              detail));
                        }
                        if (!current->baseType_) {
                          break;
                        }
                        current = resolveClassByTypeName(
                            *project, *moduleIt->second,
                            current->baseType_->qualifiedName());
                      }
                    }
                  }
                }
              }
            } else {
              std::vector<LspSymbol> symbols =
                  collectCompletionSymbols(*uri, *project, offset);
              std::set<std::string> seen;
              static constexpr const char *keywords[] = {
                  "fun",    "return",   "if",   "else",  "while", "var",
                  "const",  "import",   "pub",  "priv",  "prot",  "struct",
                  "record", "class",    "enum", "alias", "ext",   "global",
                  "break",  "continue", "ref",  "as",    "new",   "self"};
              for (const char *keyword : keywords) {
                if (seen.insert(keyword).second) {
                  items.push_back(makeCompletionItem(
                      *makeSymbol(*uri, keyword, SourceSpan(), 14), "keyword"));
                }
              }
              for (const auto &symbol : symbols) {
                if (seen.insert(symbol.name).second) {
                  items.push_back(makeCompletionItem(symbol));
                }
              }
            }
          }
        }
        server.sendMessage(makeResponse(id, JsonObject(std::move(items))));
      }
    } else if (*method == "textDocument/definition") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto line = getIntegerField(request, {"params", "position", "line"});
      auto character =
          getIntegerField(request, {"params", "position", "character"});
      if (id && uri && line && character) {
        JsonObject result(nullptr);
        if (const auto *document = workspace.document(*uri)) {
          auto project = workspace.loadProject(*uri, true);
          if (project) {
            size_t offset =
                offsetFromPosition(document->text, *line, *character);
            auto symbol = resolveDefinition(workspace, *uri, *project, offset);
            if (symbol) {
              result = makeLocation(symbol->uri, symbol->span);
            }
          }
        }
        server.sendMessage(makeResponse(id, std::move(result)));
      }
    } else if (*method == "textDocument/hover") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto line = getIntegerField(request, {"params", "position", "line"});
      auto character =
          getIntegerField(request, {"params", "position", "character"});
      if (id && uri && line && character) {
        JsonObject result(nullptr);
        if (const auto *document = workspace.document(*uri)) {
          auto project = workspace.loadProject(*uri, true);
          if (project) {
            size_t offset =
                offsetFromPosition(document->text, *line, *character);
            auto hover = resolveHover(document->text, *uri, *project, offset);
            if (hover) {
              result = makeHover(*hover);
            }
          }
        }
        server.sendMessage(makeResponse(id, std::move(result)));
      }
    } else if (*method == "textDocument/signatureHelp") {
      auto uri = getStringField(request, {"params", "textDocument", "uri"});
      auto line = getIntegerField(request, {"params", "position", "line"});
      auto character =
          getIntegerField(request, {"params", "position", "character"});
      if (id && uri && line && character) {
        JsonObject result(nullptr);
        if (const auto *document = workspace.document(*uri)) {
          auto project = workspace.loadProject(*uri, true);
          if (project) {
            size_t offset =
                offsetFromPosition(document->text, *line, *character);
            int64_t activeParameter = 0;
            auto signatures = resolveSignatures(document->text, *uri, *project,
                                                offset, activeParameter);
            if (!signatures.empty()) {
              int64_t activeSignature = 0;
              for (size_t i = 0; i < signatures.size(); ++i) {
                if (activeParameter <
                    static_cast<int64_t>(std::max<size_t>(
                        size_t(1), signatures[i].parameters.size()))) {
                  activeSignature = static_cast<int64_t>(i);
                  break;
                }
              }
              result = makeSignatureHelp(signatures, activeSignature,
                                         activeParameter);
            }
          }
        }
        server.sendMessage(makeResponse(id, std::move(result)));
      }
    } else {
      if (id) {
        JsonObject::Object error;
        error.emplace("code", JsonObject(int64_t(JsonRPC::MethodNotFound)));
        error.emplace("message", JsonObject("Method not found"));
        JsonObject::Object response;
        response.emplace("jsonrpc", JsonObject("2.0"));
        response.emplace("id", *id);
        response.emplace("error", JsonObject(std::move(error)));
        server.sendMessage(JsonObject(std::move(response)));
      }
    }
    server.send();
  }
  return shutdownRequested ? 0 : 0;
}
References ClassDecl::baseType_, anonymous_namespace{lsp-main.cpp}::collectCompletionSymbols(), anonymous_namespace{lsp-main.cpp}::collectTopLevelSymbols(), anonymous_namespace{lsp-main.cpp}::Workspace::document(), anonymous_namespace{lsp-main.cpp}::effectiveImportAlias(), ClassDecl::fields_, zap::lsp::JsonObject::getAsList(), anonymous_namespace{lsp-main.cpp}::getField(), anonymous_namespace{lsp-main.cpp}::getIntegerField(), anonymous_namespace{lsp-main.cpp}::getPath(), anonymous_namespace{lsp-main.cpp}::getStringField(), zap::lsp::JsonObject::isList(), anonymous_namespace{lsp-main.cpp}::makeCompletionItem(), anonymous_namespace{lsp-main.cpp}::makeHover(), anonymous_namespace{lsp-main.cpp}::makeLocation(), anonymous_namespace{lsp-main.cpp}::makePublishDiagnostics(), anonymous_namespace{lsp-main.cpp}::makeResponse(), anonymous_namespace{lsp-main.cpp}::makeSignatureHelp(), anonymous_namespace{lsp-main.cpp}::makeSymbol(), anonymous_namespace{lsp-main.cpp}::memberAccessBeforeCursor(), zap::lsp::JsonRPC::MethodNotFound, ClassDecl::methods_, zap::lsp::JsonRPC::object(), anonymous_namespace{lsp-main.cpp}::offsetFromPosition(), anonymous_namespace{lsp-main.cpp}::pathToUri(), zap::lsp::Server::processMessage(), anonymous_namespace{lsp-main.cpp}::publishAnalysis(), anonymous_namespace{lsp-main.cpp}::resolveClassByTypeName(), anonymous_namespace{lsp-main.cpp}::resolveDefinition(), anonymous_namespace{lsp-main.cpp}::resolveHover(), anonymous_namespace{lsp-main.cpp}::resolveSignatures(), anonymous_namespace{lsp-main.cpp}::resolveVariableClassType(), zap::lsp::Server::send(), zap::lsp::Server::sendMessage(), anonymous_namespace{lsp-main.cpp}::signatureForNode(), anonymous_namespace{lsp-main.cpp}::DocumentState::text, and anonymous_namespace{lsp-main.cpp}::uriToPath().