ZAP: UnaryExpr Class Reference
UnaryExpr Class Reference
#include <unary_expr.hpp>
Public Member Functions
UnaryExpr () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
UnaryExpr (std::string op, std::unique_ptr< ExpressionNode > expr)
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string op_
std::unique_ptr< ExpressionNode > expr_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 6 of file unary_expr.hpp.
Constructor & Destructor Documentation
UnaryExpr() [1/2]
UnaryExpr::UnaryExpr () const default noexcept
Referenced by UnaryExpr().
UnaryExpr() [2/2]
UnaryExpr::UnaryExpr (std::string op, std::unique_ptr< ExpressionNode > expr) inline
Definition at line 11 of file unary_expr.hpp.
      : op_(op), expr_(std::move(expr)) {}
References expr_, ExpressionNode::ExpressionNode(), op_, and UnaryExpr().
Member Function Documentation
accept()
void UnaryExpr::accept (Visitor & v) inline override virtual
Reimplemented from ExpressionNode.
Definition at line 14 of file unary_expr.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
expr_
std::unique_ptr<ExpressionNode> UnaryExpr::expr_
Definition at line 9 of file unary_expr.hpp.
Referenced by UnaryExpr(), and sema::Binder::visit().
op_
std::string UnaryExpr::op_
Definition at line 8 of file unary_expr.hpp.
Referenced by UnaryExpr(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/unary_expr.hpp