ZAP: ExtDecl Class Reference
ExtDecl Class Reference
#include <ext_decl.hpp>
Public Member Functions
ExtDecl () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
ExtDecl (const std::string &name, std::vector< std::unique_ptr< ParameterNode > > params, std::unique_ptr< TypeNode > returnType, bool isPublic=false)
void accept (Visitor &v) override
Public Member Functions inherited from TopLevel
virtual ~TopLevel () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string name_
std::vector< std::unique_ptr< ParameterNode > > params_
std::unique_ptr< TypeNode > returnType_
bool isPublic_ = false
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 9 of file ext_decl.hpp.
Constructor & Destructor Documentation
ExtDecl() [1/2]
ExtDecl::ExtDecl () const default noexcept
Referenced by ExtDecl().
ExtDecl() [2/2]
ExtDecl::ExtDecl (const std::string & name, std::vector< std::unique_ptr< ParameterNode > > params, std::unique_ptr< TypeNode > returnType, bool isPublic = false) inline
Definition at line 19 of file ext_decl.hpp.
        : name_(name), params_(std::move(params)),
          returnType_(std::move(returnType)), isPublic_(isPublic) {}
References ExtDecl(), isPublic_, name_, params_, and returnType_.
Member Function Documentation
accept()
void ExtDecl::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 25 of file ext_decl.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
isPublic_
bool ExtDecl::isPublic_ = false
Definition at line 15 of file ext_decl.hpp.
Referenced by ExtDecl().
name_
std::string ExtDecl::name_
Definition at line 12 of file ext_decl.hpp.
Referenced by ExtDecl(), and sema::Binder::visit().
params_
std::vector<std::unique_ptr<ParameterNode> > ExtDecl::params_
Definition at line 13 of file ext_decl.hpp.
Referenced by ExtDecl().
returnType_
std::unique_ptr<TypeNode> ExtDecl::returnType_
Definition at line 14 of file ext_decl.hpp.
Referenced by ExtDecl().
The documentation for this class was generated from the following file:
src/ast/ext_decl.hpp