ZAP: zap::lsp::anonymous_namespace{protocol_utils.cpp} Namespace Reference
zap::lsp::anonymous_namespace{protocol_utils.cpp} Namespace Reference
Functions
zap::args::CmdlineArgs readFlagsFromFile (const std::filesystem::path &path)
Function Documentation
readFlagsFromFile()
zap::args::CmdlineArgs zap::lsp::anonymous_namespace{protocol_utils.cpp}::readFlagsFromFile (const std::filesystem::path & path)
Definition at line 131 of file protocol_utils.cpp.
{
  zap::args::CmdlineArgs args;
  std::ifstream file(path);
  if (!file) {
    return args;
  }
  std::vector<std::string> argv;
  argv.push_back("zapc");
  std::string word;
  while (file >> word) {
    argv.push_back(word);
  }
  zap::args::parse(argv, args);
  auto baseDir = path.parent_path();
  for (auto &[alias, target] : args.importMap) {
    std::filesystem::path targetPath(target);
    if (!target.empty() && !targetPath.is_absolute()) {
      target = (baseDir / targetPath).lexically_normal().generic_string();
    }
  }
  return args;
}
References argv(), zap::args::parse(), and readFlagsFromFile().
Referenced by readFlagsFromFile().