ZAP: codegen::anonymous_namespace{llvm_codegen_constants.cpp} Namespace Reference
codegen::anonymous_namespace{llvm_codegen_constants.cpp} Namespace Reference
Functions
uint64_t parseIntegerLiteral (const std::string &literal)
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isStringRecordName (const std::string &full)
Function Documentation
isStringRecordName()
bool codegen::anonymous_namespace{llvm_codegen_constants.cpp}::isStringRecordName (const std::string & full)
Definition at line 29 of file llvm_codegen_constants.cpp.
{
  return zap::text::isStringRecordName(full);
}
References isStringRecordName(), and zap::text::isStringRecordName().
Referenced by isStringRecordName().
isStringType()
bool codegen::anonymous_namespace{llvm_codegen_constants.cpp}::isStringType (const std::shared_ptr< zir::Type > & type)
Definition at line 25 of file llvm_codegen_constants.cpp.
{
  return zap::text::isStringType(type);
}
References isStringType(), and zap::text::isStringType().
Referenced by isStringType().
parseIntegerLiteral()
uint64_t codegen::anonymous_namespace{llvm_codegen_constants.cpp}::parseIntegerLiteral (const std::string & literal)
Definition at line 10 of file llvm_codegen_constants.cpp.
{
  if (literal.size() > 2 && literal[0] == '0') {
    if (literal[1] == 'x' || literal[1] == 'X') {
      return std::stoull(literal, nullptr, 16);
    }
    if (literal[1] == 'b' || literal[1] == 'B') {
      return std::stoull(literal.substr(2), nullptr, 2);
    }
    if (literal[1] == 'o' || literal[1] == 'O') {
      return std::stoull(literal.substr(2), nullptr, 8);
    }
  }
  return std::stoull(literal, nullptr, 10);
}
References parseIntegerLiteral().
Referenced by parseIntegerLiteral().