ZAP: SourceSpan Struct Reference
SourceSpan Struct Reference
Contains in-file related information like line, column, offset, and length.
#include <token.hpp>
Public Member Functions
SourceSpan (size_t l=0, size_t c=0, size_t o=0, size_t len=0) noexcept
Basic constructor of the source span.
Static Public Member Functions
static SourceSpan merge (const SourceSpan &start, const SourceSpan &end) noexcept
Merges two 'SourceSpan' classes.
Public Attributes
size_t line
Line of the source in the file.
size_t column
Column of the source in the file.
size_t offset
Offset of the source in the file.
size_t length
Length of the source.
Detailed Description
Contains in-file related information like line, column, offset, and length.
Definition at line 75 of file token.hpp.
Constructor & Destructor Documentation
SourceSpan()
SourceSpan::SourceSpan (size_t l = 0, size_t c = 0, size_t o = 0, size_t len = 0) inline noexcept
Basic constructor of the source span.
Parameters
l Line.
c Column.
o Offset.
len Length.
Definition at line 86 of file token.hpp.
      : line(l), column(c), offset(o), length(len) {}
References column, length, line, and offset.
Referenced by merge().
Member Function Documentation
merge()
SourceSpan SourceSpan::merge (const SourceSpan & start, const SourceSpan & end) inline static noexcept
Merges two 'SourceSpan' classes.
Parameters
start From.
end To.
Returns
Merged 'SourceSpan'.
Definition at line 93 of file token.hpp.
  {
    size_t newLen = (end.offset + end.length) - start.offset;
    return SourceSpan(start.line, start.column, start.offset, newLen);
  }
References SourceSpan().
Referenced by zap::Parser::parse(), zap::Parser::parseArrayLiteral(), zap::Parser::parseAssign(), zap::Parser::parseBinaryExpression(), zap::Parser::parseBody(), zap::Parser::parseBreak(), zap::Parser::parseConstDecl(), zap::Parser::parseContinue(), zap::Parser::parseEnumDecl(), zap::Parser::parseExtDecl(), zap::Parser::parseFunDecl(), zap::Parser::parseIf(), zap::Parser::parseParameter(), zap::Parser::parsePostfixExpression(), zap::Parser::parsePrimaryExpression(), zap::Parser::parseRecordDecl(), zap::Parser::parseReturnStmt(), zap::Parser::parseTernaryExpression(), zap::Parser::parseType(), zap::Parser::parseTypeAliasDecl(), zap::Parser::parseUnaryExpression(), zap::Parser::parseVarDecl(), and zap::Parser::parseWhile().
Member Data Documentation
column
size_t SourceSpan::column
Column of the source in the file.
Definition at line 77 of file token.hpp.
Referenced by zap::DiagnosticEngine::printContext(), zap::DiagnosticEngine::report(), and SourceSpan().
length
size_t SourceSpan::length
Length of the source.
Definition at line 79 of file token.hpp.
Referenced by zap::DiagnosticEngine::printContext(), and SourceSpan().
line
size_t SourceSpan::line
Line of the source in the file.
Definition at line 76 of file token.hpp.
Referenced by zap::DiagnosticEngine::printContext(), zap::DiagnosticEngine::report(), and SourceSpan().
offset
size_t SourceSpan::offset
Offset of the source in the file.
Definition at line 78 of file token.hpp.
Referenced by SourceSpan().
The documentation for this struct was generated from the following file:
src/token/token.hpp