ZAP: zap::anonymous_namespace{driver.cpp} Namespace Reference
zap::anonymous_namespace{driver.cpp} Namespace Reference
Functions
std::optional< std::filesystem::path > currentExecutablePath (const std::filesystem::path &argv0Hint)
std::filesystem::path stdlibRootPath (const std::filesystem::path &argv0Hint)
std::string stripSourceExtension (const std::filesystem::path &path)
std::string computeLogicalModulePath (const std::filesystem::path &canonicalPath)
bool readSourceFile (const std::filesystem::path &path, std::string &content)
bool resolveImportTargets (const std::filesystem::path &modulePath, const ImportNode &importNode, std::vector< std::filesystem::path > &targets)
bool loadModuleGraph (const std::filesystem::path &entryPath, std::map< std::string, std::unique_ptr< sema::ModuleInfo > > &modules, std::set< std::string > &visiting)
Variables
std::filesystem::path g_executable_path
Function Documentation
computeLogicalModulePath()
std::string zap::anonymous_namespace{driver.cpp}::computeLogicalModulePath (const std::filesystem::path & canonicalPath)
Definition at line 73 of file driver.cpp.
{
  auto stdRoot = std::filesystem::weakly_canonical(stdlibRootPath(g_executable_path));
  auto cwdRoot = std::filesystem::weakly_canonical(std::filesystem::current_path());
  auto buildRelative = [&](const std::filesystem::path &root,
                           const std::string &prefix = "")
      -> std::optional<std::string> {
    auto rootText = root.generic_string();
    auto pathText = canonicalPath.generic_string();
    if (pathText == rootText || pathText.rfind(rootText + "/", 0) != 0) {
      return std::nullopt;
    }
    auto rel = std::filesystem::relative(canonicalPath, root);
    auto stripped = stripSourceExtension(rel);
    if (prefix.empty()) {
      return stripped;
    }
    return prefix + "/" + stripped;
  };
  if (auto logical = buildRelative(stdRoot, "std")) {
    return *logical;
  }
  if (auto logical = buildRelative(cwdRoot)) {
    return *logical;
  }
  return stripSourceExtension(canonicalPath.filename());
}
References computeLogicalModulePath(), g_executable_path, stdlibRootPath(), and stripSourceExtension().
Referenced by computeLogicalModulePath().
currentExecutablePath()
std::optional< std::filesystem::path > zap::anonymous_namespace{driver.cpp}::currentExecutablePath (const std::filesystem::path & argv0Hint)
Definition at line 29 of file driver.cpp.
{
  std::error_code ec;
  auto procPath = std::filesystem::read_symlink("/proc/self/exe", ec);
  if (!ec && !procPath.empty()) {
    return std::filesystem::weakly_canonical(procPath);
  }
  if (!argv0Hint.empty()) {
    auto resolved = argv0Hint.is_absolute()
                        ? argv0Hint
                        : std::filesystem::current_path() / argv0Hint;
    return std::filesystem::weakly_canonical(resolved, ec);
  }
  return std::nullopt;
}
References currentExecutablePath().
Referenced by currentExecutablePath(), and stdlibRootPath().
loadModuleGraph()
bool zap::anonymous_namespace{driver.cpp}::loadModuleGraph (const std::filesystem::path & entryPath, std::map< std::string, std::unique_ptr< sema::ModuleInfo > > & modules, std::set< std::string > & visiting)
Definition at line 170 of file driver.cpp.
{
  auto canonicalPath = std::filesystem::weakly_canonical(entryPath);
  auto moduleId = canonicalPath.string();
  if (modules.find(moduleId) != modules.end()) {
    return false;
  }
  if (visiting.count(moduleId)) {
    driver::reportError("cyclic import detected involving ", canonicalPath);
    return true;
  }
  visiting.insert(moduleId);
  std::string source;
  if (readSourceFile(canonicalPath, source)) {
    return true;
  }
  DiagnosticEngine diagnostics(source, canonicalPath.string());
  Lexer lex(diagnostics);
  auto tokens = lex.tokenize(source);
  Parser parser(tokens, diagnostics);
  auto ast = parser.parse();
  if (diagnostics.hadErrors() || !ast) {
    diagnostics.printText(err());
    return true;
  }
  auto module = std::make_unique<sema::ModuleInfo>();
  module->moduleId = moduleId;
  module->moduleName = canonicalPath.stem().string();
  module->linkPath = computeLogicalModulePath(canonicalPath);
  module->sourceName = canonicalPath.string();
  module->root = std::move(ast);
  for (const auto &child : module->root->children) {
    auto importNode = dynamic_cast<ImportNode *>(child.get());
    if (!importNode) {
      continue;
    }
    sema::ResolvedImport resolved;
    resolved.rawPath = importNode->path;
    resolved.moduleAlias = importNode->moduleAlias;
    resolved.visibility = importNode->visibility_;
    resolved.span = importNode->span;
    for (const auto &binding : importNode->bindings) {
      resolved.bindings.push_back({binding.sourceName, binding.localName});
    }
    std::vector<std::filesystem::path> importTargets;
    if (resolveImportTargets(canonicalPath, *importNode, importTargets)) {
      return true;
    }
    for (const auto &target : importTargets) {
      resolved.targetModuleIds.push_back(target.string());
    }
    module->imports.push_back(std::move(resolved));
  }
  for (const auto &import : module->imports) {
    for (const auto &targetId : import.targetModuleIds) {
      if (loadModuleGraph(targetId, modules, visiting)) {
        return true;
      }
    }
  }
  visiting.erase(moduleId);
  modules[moduleId] = std::move(module);
  return false;
}
References sema::ResolvedImport::bindings, zap::err(), zap::DiagnosticEngine::hadErrors(), loadModuleGraph(), sema::ResolvedImport::moduleAlias, zap::Parser::parse(), zap::DiagnosticEngine::printText(), sema::ResolvedImport::rawPath, readSourceFile(), zap::driver::reportError(), resolveImportTargets(), sema::ResolvedImport::span, sema::ResolvedImport::targetModuleIds, Lexer::tokenize(), and sema::ResolvedImport::visibility.
Referenced by loadModuleGraph().
readSourceFile()
bool zap::anonymous_namespace{driver.cpp}::readSourceFile (const std::filesystem::path & path, std::string & content)
Definition at line 103 of file driver.cpp.
{
  std::ifstream file(path, std::ios::binary | std::ios::ate);
  if (!file) {
    driver::reportError("couldn't open the provided file: ", path,
                        "\nreason: ", strerror(errno));
    return true;
  }
  auto size = file.tellg();
  content.assign(static_cast<size_t>(std::max<std::streamsize>(size, 0)), '\0');
  if (size == 0) {
    err() << "warning: provided file is empty: " << path << '\n';
  } else {
    file.seekg(0);
    file.read(content.data(), size);
  }
  return false;
}
References zap::err(), readSourceFile(), and zap::driver::reportError().
Referenced by loadModuleGraph(), and readSourceFile().
resolveImportTargets()
bool zap::anonymous_namespace{driver.cpp}::resolveImportTargets (const std::filesystem::path & modulePath, const ImportNode & importNode, std::vector< std::filesystem::path > & targets)
Definition at line 124 of file driver.cpp.
{
  std::filesystem::path resolvedPath;
  if (importNode.path.rfind("std/", 0) == 0) {
    resolvedPath = stdlibRootPath(g_executable_path) /
                   importNode.path.substr(std::string("std/").size());
  } else {
    resolvedPath = modulePath.parent_path() / importNode.path;
  }
  resolvedPath = resolvedPath.lexically_normal();
  auto tryFile = [&](const std::filesystem::path &path) -> bool {
    if (std::filesystem::exists(path) && std::filesystem::is_regular_file(path)) {
      targets.push_back(std::filesystem::weakly_canonical(path));
      return true;
    }
    return false;
  };
  if (tryFile(resolvedPath)) {
    return false;
  }
  if (resolvedPath.extension() != ".zp" && tryFile(resolvedPath.string() + ".zp")) {
    return false;
  }
  if (std::filesystem::exists(resolvedPath) &&
      std::filesystem::is_directory(resolvedPath)) {
    for (const auto &entry : std::filesystem::directory_iterator(resolvedPath)) {
      if (!entry.is_regular_file()) {
        continue;
      }
      if (entry.path().extension() == ".zp") {
        targets.push_back(std::filesystem::weakly_canonical(entry.path()));
      }
    }
    std::sort(targets.begin(), targets.end());
    return false;
  }
  driver::reportError("import path not found: ", resolvedPath);
  return true;
}
References g_executable_path, ImportNode::path, zap::driver::reportError(), resolveImportTargets(), and stdlibRootPath().
Referenced by loadModuleGraph(), and resolveImportTargets().
stdlibRootPath()
std::filesystem::path zap::anonymous_namespace{driver.cpp}::stdlibRootPath (const std::filesystem::path & argv0Hint)
Definition at line 47 of file driver.cpp.
{
  if (const char *configured = std::getenv("ZAPC_STDLIB_DIR")) {
    if (*configured != '\0') {
      return std::filesystem::path(configured);
    }
  }
  if (auto exePath = currentExecutablePath(argv0Hint)) {
    auto siblingStd = exePath->parent_path() / "std";
    if (std::filesystem::exists(siblingStd) &&
        std::filesystem::is_directory(siblingStd)) {
      return siblingStd;
    }
  }
  return std::filesystem::path(ZAPC_STDLIB_DIR);
}
References currentExecutablePath(), and stdlibRootPath().
Referenced by computeLogicalModulePath(), resolveImportTargets(), and stdlibRootPath().
stripSourceExtension()
std::string zap::anonymous_namespace{driver.cpp}::stripSourceExtension (const std::filesystem::path & path)
Definition at line 65 of file driver.cpp.
{
  auto normalized = path.generic_string();
  if (path.extension() == ".zp" && normalized.size() >= 4) {
    normalized.resize(normalized.size() - 4);
  }
  return normalized;
}
References stripSourceExtension().
Referenced by computeLogicalModulePath(), and stripSourceExtension().
Variable Documentation
g_executable_path
std::filesystem::path zap::anonymous_namespace{driver.cpp}::g_executable_path
Definition at line 27 of file driver.cpp.
Referenced by computeLogicalModulePath(), and resolveImportTargets().