ZAP: ImportNode Class Reference
ImportNode Class Reference
#include <import_node.hpp>
Public Member Functions
ImportNode () noexcept=default
ImportNode (std::string importPath, std::string alias="", std::vector< ImportBinding > importBindings={})
~ImportNode () noexcept override=default
void accept (Visitor &v) override
Public Member Functions inherited from TopLevel
virtual ~TopLevel () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string path
std::string moduleAlias
std::vector< ImportBinding > bindings
Public Attributes inherited from TopLevel
Visibility visibility_ = Visibility::Private
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 13 of file import_node.hpp.
Constructor & Destructor Documentation
ImportNode() [1/2]
ImportNode::ImportNode () default noexcept
Referenced by ImportNode().
ImportNode() [2/2]
ImportNode::ImportNode (std::string importPath, std::string alias = "", std::vector< ImportBinding > importBindings = {}) inline
Definition at line 20 of file import_node.hpp.
                                                       {})
      : path(std::move(importPath)), moduleAlias(std::move(alias)),
        bindings(std::move(importBindings)) {}
References ImportNode().
~ImportNode()
ImportNode::~ImportNode () override default noexcept
Member Function Documentation
accept()
void ImportNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 27 of file import_node.hpp.
{ v.visit(*this); }
References accept().
Referenced by accept().
Member Data Documentation
bindings
std::vector<ImportBinding> ImportNode::bindings
Definition at line 17 of file import_node.hpp.
moduleAlias
std::string ImportNode::moduleAlias
Definition at line 16 of file import_node.hpp.
path
std::string ImportNode::path
Definition at line 15 of file import_node.hpp.
Referenced by anonymous_namespace{lsp-main.cpp}::resolveImportTargets(), and zap::anonymous_namespace{driver.cpp}::resolveImportTargets().
The documentation for this class was generated from the following file:
src/ast/import_node.hpp