ZAP: sema::Binder Class Reference
sema::Binder Class Reference
#include <binder.hpp>
Classes
struct ModuleState
struct ClassInfo
struct PairHash
Public Member Functions
Binder (zap::DiagnosticEngine &diag, bool allowUnsafe=true, SemanticInfo *semanticInfo=nullptr)
std::unique_ptr< BoundRootNode > bind (RootNode &root)
std::unique_ptr< BoundRootNode > bind (std::vector< ModuleInfo > &modules)
std::unique_ptr< BoundRootNode > bind (std::vector< ModuleInfo * > modules)
void visit (RootNode &node) override
void visit (ImportNode &node) override
void visit (FunDecl &node) override
void visit (ExtDecl &node) override
void visit (BodyNode &node) override
void visit (VarDecl &node) override
void visit (ConstDecl &node) override
void visit (ReturnNode &node) override
void visit (BinExpr &node) override
void visit (TernaryExpr &node) override
void visit (ConstInt &node) override
void visit (ConstBool &node) override
void visit (IfNode &node) override
void visit (IfTypeNode &node) override
void visit (WhileNode &node) override
void visit (ForNode &node) override
void visit (ForInNode &node) override
void visit (MemberAccessNode &node) override
void visit (IndexAccessNode &node) override
void visit (BreakNode &node) override
void visit (ContinueNode &node) override
void visit (AssignNode &node) override
void visit (FunCall &node) override
void visit (ConstId &node) override
void visit (ConstFloat &node) override
void visit (ConstString &node) override
void visit (ConstChar &node) override
void visit (UnaryExpr &node) override
void visit (CastExpr &node) override
void visit (ArrayLiteralNode &node) override
void visit (ConstNull &node) override
void visit (EnumDecl &node) override
void visit (TypeAliasDecl &node) override
void visit (RecordDecl &node) override
void visit (StructDeclarationNode &node) override
void visit (ClassDecl &node) override
void visit (StructLiteralNode &node) override
void visit (UnsafeBlockNode &node) override
void visit (AsmStmtNode &node) override
void visit (NewExpr &node) override
void visit (TryExpr &node) override
void visit (FallbackExpr &node) override
void visit (FailableHandleExpr &node) override
void visit (FailNode &node) override
Public Member Functions inherited from Visitor
virtual ~Visitor () noexcept=default
virtual void visit (Node &)
virtual void visit (TopLevel &)
virtual void visit (StatementNode &)
virtual void visit (ParameterNode &)
virtual void visit (TypeNode &)
virtual void visit (ExpressionNode &)
Private Member Functions
void pushScope ()
void popScope ()
std::shared_ptr< zir::Type > mapType (const TypeNode &typeNode)
std::shared_ptr< zir::Type > mapTypeWithGenericBindings (const TypeNode &typeNode, const std::unordered_map< std::string, std::shared_ptr< zir::Type > > &genericBindings)
bool isGenericTypeParameterName (std::string_view name) const
std::shared_ptr< Symbol > resolveQualifiedSymbol (const std::vector< std::string > &parts, SourceSpan span, SymbolKind expectedKind=SymbolKind::Variable, bool allowAnyKind=false)
std::shared_ptr< Symbol > resolveModuleMember (const std::string &moduleName, const std::string &memberName, SourceSpan span)
std::optional< int64_t > evaluateConstantInt (const BoundExpression *expr)
std::unique_ptr< BoundExpression > foldConstantBinary (const BoundBinaryExpression *binary)
std::string makeSyntheticLoopName (std::string_view prefix)
std::unique_ptr< BoundExpression > wrapInCast (std::unique_ptr< BoundExpression > expr, std::shared_ptr< zir::Type > targetType)
std::unique_ptr< BoundExpression > buildBinaryExpression (std::unique_ptr< BoundExpression > left, const std::string &op, std::unique_ptr< BoundExpression > right, SourceSpan leftSpan, SourceSpan rightSpan)
void error (SourceSpan span, const std::string &message)
std::string mangleName (const std::string &modulePath, const std::string &name) const
std::string mangleFunctionName (const std::string &modulePath, const FunctionSymbol &function) const
std::string currentModuleLinkPath () const
std::string displayTypeName (const std::string &moduleName, const std::string &name) const
std::string renderTypeForUser (const std::shared_ptr< zir::Type > &type) const
std::string functionSignatureKey (const FunctionSymbol &function) const
std::string renderFunctionSignature (const FunctionSymbol &function) const
std::shared_ptr< FunctionSymbol > findFunctionBySignature (const std::shared_ptr< Symbol > &symbol, const FunctionSymbol &prototype) const
std::shared_ptr< OverloadSetSymbol > addClassMethodOverload (ClassInfo &classInfo, const std::shared_ptr< FunctionSymbol > &method)
int findOverriddenVtableSlot (const ClassInfo &classInfo, const FunctionSymbol &method) const
std::shared_ptr< FunctionSymbol > ensureGenericFunctionInstantiation (const std::shared_ptr< FunctionSymbol > &baseFunction, const std::vector< std::pair< std::string, std::shared_ptr< zir::Type > > > &genericBindings, SourceSpan callSpan)
std::unordered_map< std::string, std::shared_ptr< zir::Type > > buildGenericBindings (const FunctionSymbol &function, const std::vector< std::unique_ptr< BoundExpression > > &arguments, const std::vector< std::unique_ptr< TypeNode > > &explicitTypeArgs, SourceSpan callSpan, std::string *failureReason=nullptr)
std::vector< std::pair< std::string, std::shared_ptr< zir::Type > > > orderedGenericBindings (const std::unordered_map< std::string, std::shared_ptr< zir::Type > > &genericBindings) const
std::shared_ptr< zir::Type > substituteGenericType (std::shared_ptr< zir::Type > type, const std::unordered_map< std::string, std::shared_ptr< zir::Type > > &genericBindings) const
bool validateGenericConstraints (const std::vector< GenericConstraint > &constraints, std::unordered_map< std::string, std::shared_ptr< zir::Type > > &bindings, std::string *failureReason=nullptr)
std::shared_ptr< TypeSymbol > instantiateGenericTypeSymbol (const std::shared_ptr< TypeSymbol > &baseSymbol, const TypeNode &typeNode)
std::unique_ptr< BoundExpression > bindExpressionWithExpected (ExpressionNode *expr, std::shared_ptr< zir::Type > expectedType)
std::shared_ptr< zir::Type > currentExpectedExpressionType () const
bool bindSizeOfBuiltinCall (FunCall &node)
bool bindWeakBuiltinCall (FunCall &node)
int conversionCost (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const
bool isSignedIntegerType (std::shared_ptr< zir::Type > type) const
bool isUnsignedIntegerType (std::shared_ptr< zir::Type > type) const
int typeBitWidth (std::shared_ptr< zir::Type > type) const
std::string describeConversion (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const
std::unique_ptr< BoundBlock > bindBody (BodyNode *body, bool createScope)
void initializeBuiltins ()
void predeclareModuleTypes (ModuleState &module)
void predeclareModuleAliases (ModuleState &module)
void predeclareModuleValues (ModuleState &module)
void applyImports (ModuleState &module, bool allowIncomplete=false)
void ensureModuleValuesReady (ModuleState &module)
std::shared_ptr< Symbol > lookupVisibleSymbol (const std::string &name) const
bool isNumeric (std::shared_ptr< zir::Type > type) const
bool isPointerType (std::shared_ptr< zir::Type > type) const
bool isNullType (std::shared_ptr< zir::Type > type) const
bool isUnsafeActive () const
void requireUnsafeEnabled (SourceSpan span, const std::string &feature)
void requireUnsafeContext (SourceSpan span, const std::string &feature)
bool canConvert (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const
std::shared_ptr< zir::Type > getPromotedType (std::shared_ptr< zir::Type > t1, std::shared_ptr< zir::Type > t2)
std::shared_ptr< zir::Type > getCVariadicArgumentType (std::shared_ptr< zir::Type > type)
bool isSupportedBuiltInAttribute (const std::string &name) const
void warnUnknownAttributes (const TopLevel &node)
void validateAndApplyTypeAttributes (const TopLevel &node, const std::shared_ptr< TypeSymbol > &symbol, bool allowErrorAttribute)
void validateAndApplyFunctionAttributes (const TopLevel &node, const std::shared_ptr< FunctionSymbol > &symbol, bool isExternalDeclaration)
Private Attributes
zap::DiagnosticEngine & _diag
SemanticInfo * semanticInfo_ = nullptr
std::shared_ptr< SymbolTable > currentScope_
std::shared_ptr< SymbolTable > builtinScope_
std::unique_ptr< BoundRootNode > boundRoot_
std::stack< std::unique_ptr< BoundExpression > > expressionStack_
std::stack< std::unique_ptr< BoundStatement > > statementStack_
std::unique_ptr< BoundBlock > currentBlock_
std::vector< std::shared_ptr< zir::Type > > expectedExpressionTypes_
int loopDepth_ = 0
size_t syntheticLoopCounter_ = 0
int unsafeDepth_ = 0
int unsafeTypeContextDepth_ = 0
int externTypeContextDepth_ = 0
bool allowUnsafe_ = true
std::shared_ptr< FunctionSymbol > currentFunction_ = nullptr
std::string currentModuleId_
std::map< std::string, ModuleState > modules_
std::unordered_map< const Node *, std::shared_ptr< FunctionSymbol > > declaredFunctionSymbols_
std::unordered_map< const TypeSymbol *, const RecordDecl * > recordTypeDeclarationNodes_
std::unordered_map< const TypeSymbol *, const StructDeclarationNode * > structTypeDeclarationNodes_
std::unordered_map< const TypeSymbol *, const ClassDecl * > classTypeDeclarationNodes_
std::unordered_map< const TypeSymbol *, std::string > typeDeclarationModuleIds_
std::unordered_map< const FunctionSymbol *, const FunDecl * > functionDeclarationNodes_
std::unordered_map< const FunctionSymbol *, std::string > functionDeclarationModuleIds_
std::unordered_map< const FunctionSymbol *, std::vector< std::string > > functionGenericParamNames_
std::unordered_map< std::string, std::shared_ptr< FunctionSymbol > > genericFunctionInstantiations_
std::unordered_map< std::string, std::shared_ptr< TypeSymbol > > genericTypeInstantiations_
std::unordered_map< const FunctionSymbol *, std::string > genericFunctionDeclarationKeys_
std::unordered_map< const FunctionSymbol *, bool > genericInstantiationEmitted_
std::vector< std::unordered_map< std::string, std::shared_ptr< zir::Type > > > activeGenericBindingsStack_
std::vector< std::string > genericInstantiationInProgress_
std::unordered_map< std::string, ClassInfo > classInfos_
std::vector< std::string > currentClassStack_
std::unordered_map< std::pair< const zir::Type *, const zir::Type * >, bool, PairHash > canConvertCache_
std::unordered_map< const TypeNode *, std::shared_ptr< zir::Type > > mapTypeCache_
bool hadError_ = false
bool sawPrivacyError_ = false
Detailed Description
Definition at line 62 of file binder.hpp.
Constructor & Destructor Documentation
Binder()
sema::Binder::Binder (zap::DiagnosticEngine & diag, bool allowUnsafe = true, SemanticInfo * semanticInfo = nullptr)
Definition at line 390 of file binder.cpp.
    : _diag(diag), semanticInfo_(semanticInfo), allowUnsafe_(allowUnsafe),
      hadError_(false) {}
References _diag, allowUnsafe_, hadError_, and semanticInfo_.
Member Function Documentation
addClassMethodOverload()
std::shared_ptr< OverloadSetSymbol > sema::Binder::addClassMethodOverload (ClassInfo & classInfo, const std::shared_ptr< FunctionSymbol > & method) private
Definition at line 709 of file binder.cpp.
{
  if (!method) {
    return nullptr;
  }
  auto &entry = classInfo.methods[method->name];
  auto overloads = std::dynamic_pointer_cast<OverloadSetSymbol>(entry);
  auto updated = std::make_shared<OverloadSetSymbol>(
      method->name, method->moduleName, method->visibility);
  if (overloads) {
    updated->overloads = overloads->overloads;
  } else if (auto existing = std::dynamic_pointer_cast<FunctionSymbol>(entry)) {
    updated->addOverload(existing);
  }
  updated->overloads.erase(
      std::remove_if(updated->overloads.begin(), updated->overloads.end(),
                     [&](const std::shared_ptr<FunctionSymbol> &candidate) {
                       return candidate &&
                              sameMethodDispatchSignature(*candidate, *method);
                     }),
      updated->overloads.end());
  updated->addOverload(method);
  entry = updated;
  return updated;
}
References sema::Binder::ClassInfo::methods.
Referenced by instantiateGenericTypeSymbol().
applyImports()
void sema::Binder::applyImports (ModuleState & module, bool allowIncomplete = false) private
Definition at line 291 of file binder_decls.cpp.
{
  std::map<std::string, std::string> namespaceOwners;
  for (const auto &import : module.info->imports) {
    if (!import.moduleAlias.empty() && import.targetModuleIds.size() != 1) {
      if (!allowIncomplete) {
        error(import.span, "Module alias imports are only allowed when the "
                           "path resolves to a single module.");
      }
      continue;
    }
    for (const auto &targetId : import.targetModuleIds) {
      auto targetIt = modules_.find(targetId);
      if (targetIt == modules_.end()) {
        continue;
      }
      auto &target = targetIt->second;
      auto alias = import.moduleAlias.empty() ? target.info->moduleName
                                              : import.moduleAlias;
      auto existingOwner = namespaceOwners.find(alias);
      if (existingOwner != namespaceOwners.end() &&
          existingOwner->second != targetId) {
        if (!allowIncomplete) {
          error(import.span, "Import namespace '" + alias +
                                 "' is ambiguous because multiple files share "
                                 "that module name.");
        }
        continue;
      }
      if (!module.scope->lookupLocal(alias)) {
        module.scope->declare(alias, target.symbol);
        namespaceOwners[alias] = targetId;
      } else if (module.scope->lookupLocal(alias) != target.symbol) {
        if (!allowIncomplete) {
          error(import.span, "Cannot import module '" + alias +
                                 "' because that name is already declared in "
                                 "the current file.");
        }
        continue;
      }
      if (import.bindings.empty()) {
        bool isImplicitStdImport =
            import.rawPath == "std/prelude" && import.moduleAlias.empty();
        if (isImplicitStdImport) {
          for (const auto &exported : target.symbol->exports) {
            if (!module.scope->lookupLocal(exported.first)) {
              module.scope->declare(exported.first, exported.second);
            }
          }
        }
        if (import.visibility == Visibility::Public) {
          module.symbol->exports[alias] = target.symbol;
          for (const auto &exported : target.symbol->exports) {
            module.symbol->exports[exported.first] = exported.second;
          }
        }
        continue;
      }
      if (import.targetModuleIds.size() != 1) {
        if (!allowIncomplete) {
          error(import.span, "Selective imports are only allowed when the path "
                             "resolves to a single module.");
        }
        continue;
      }
      for (const auto &binding : import.bindings) {
        auto exportedIt = target.symbol->exports.find(binding.sourceName);
        if (exportedIt == target.symbol->exports.end()) {
          if (allowIncomplete) {
            continue;
          }
          auto memberIt = target.symbol->members.find(binding.sourceName);
          if (memberIt != target.symbol->members.end() &&
              memberIt->second->visibility != Visibility::Public) {
            error(import.span, "Member '" + binding.sourceName +
                                   "' of module '" + alias + "' is private.");
          } else {
            error(import.span, "Module '" + alias + "' has no public member '" +
                                   binding.sourceName + "'.");
          }
          continue;
        }
        auto existing = module.scope->lookupLocal(binding.localName);
        if (existing && existing != exportedIt->second) {
          if (!allowIncomplete) {
            error(import.span, "Imported name '" + binding.localName +
                                   "' conflicts with an existing declaration "
                                   "in the current file.");
          }
          continue;
        }
        if (!existing) {
          module.scope->declare(binding.localName, exportedIt->second);
        }
        if (import.visibility == Visibility::Public) {
          module.symbol->exports[binding.localName] = exportedIt->second;
        }
      }
    }
  }
}
References error(), sema::ModuleInfo::imports, sema::Binder::ModuleState::info, modules_, Public, and sema::Binder::ModuleState::scope.
Referenced by bind(), and ensureModuleValuesReady().
bind() [1/3]
std::unique_ptr< BoundRootNode > sema::Binder::bind (RootNode & root)
Definition at line 395 of file binder.cpp.
{
  (void)root;
  _diag.report(
      SourceSpan(), zap::DiagnosticLevel::Error,
      "Internal error: single-file binder entry point is unsupported.");
  return nullptr;
}
References _diag, and zap::Error.
Referenced by zap::lsp::Workspace::analyze(), bind(), zap::driver::compileLoadedModules, zap::driver::compileSourceFile(), and zap::lsp::Workspace::loadProject().
bind() [2/3]
std::unique_ptr< BoundRootNode > sema::Binder::bind (std::vector< ModuleInfo * > modules)
Definition at line 412 of file binder.cpp.
{
  hadError_ = false;
  boundRoot_ = std::make_unique<BoundRootNode>();
  modules_.clear();
  currentScope_.reset();
  currentFunction_.reset();
  currentModuleId_.clear();
  declaredFunctionSymbols_.clear();
  recordTypeDeclarationNodes_.clear();
  structTypeDeclarationNodes_.clear();
  classTypeDeclarationNodes_.clear();
  typeDeclarationModuleIds_.clear();
  functionDeclarationNodes_.clear();
  functionGenericParamNames_.clear();
  genericFunctionInstantiations_.clear();
  genericTypeInstantiations_.clear();
  genericFunctionDeclarationKeys_.clear();
  genericInstantiationEmitted_.clear();
  genericInstantiationInProgress_.clear();
  activeGenericBindingsStack_.clear();
  syntheticLoopCounter_ = 0;
  unsafeDepth_ = 0;
  unsafeTypeContextDepth_ = 0;
  externTypeContextDepth_ = 0;
  sawPrivacyError_ = false;
  initializeBuiltins();
  for (auto *module : modules) {
    if (!module) {
      continue;
    }
    ModuleState state;
    state.info = module;
    state.scope = std::make_shared<SymbolTable>(builtinScope_);
    state.symbol =
        std::make_shared<ModuleSymbol>(module->moduleName, module->moduleId);
    modules_[module->moduleId] = state;
  }
  for (auto &[_, module] : modules_) {
    predeclareModuleTypes(module);
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    applyImports(module, true);
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    predeclareModuleAliases(module);
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    applyImports(module, true);
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    ensureModuleValuesReady(module);
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    currentModuleId_ = module.info->moduleId;
    currentScope_ = module.scope;
    for (const auto &child : module.info->root->children) {
      if (dynamic_cast<RecordDecl *>(child.get()) ||
          dynamic_cast<StructDeclarationNode *>(child.get()) ||
          dynamic_cast<EnumDecl *>(child.get())) {
        child->accept(*this);
      }
    }
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    currentModuleId_ = module.info->moduleId;
    currentScope_ = module.scope;
    for (const auto &child : module.info->root->children) {
      if (dynamic_cast<ClassDecl *>(child.get())) {
        child->accept(*this);
      }
    }
  }
  if (hadError_ || _diag.hadErrors()) {
    return nullptr;
  }
  for (auto &[_, module] : modules_) {
    currentModuleId_ = module.info->moduleId;
    currentScope_ = module.scope;
    for (const auto &child : module.info->root->children) {
      if (dynamic_cast<ImportNode *>(child.get()) ||
          dynamic_cast<RecordDecl *>(child.get()) ||
          dynamic_cast<ClassDecl *>(child.get()) ||
          dynamic_cast<StructDeclarationNode *>(child.get()) ||
          dynamic_cast<EnumDecl *>(child.get()) ||
          dynamic_cast<TypeAliasDecl *>(child.get())) {
        continue;
      }
      child->accept(*this);
    }
  }
  return (hadError_ || _diag.hadErrors()) ? nullptr : std::move(boundRoot_);
}
References _diag, activeGenericBindingsStack_, applyImports(), boundRoot_, builtinScope_, classTypeDeclarationNodes_, currentFunction_, currentModuleId_, currentScope_, declaredFunctionSymbols_, ensureModuleValuesReady(), externTypeContextDepth_, functionDeclarationNodes_, functionGenericParamNames_, genericFunctionDeclarationKeys_, genericFunctionInstantiations_, genericInstantiationEmitted_, genericInstantiationInProgress_, genericTypeInstantiations_, hadError_, sema::Binder::ModuleState::info, initializeBuiltins(), modules_, predeclareModuleAliases(), predeclareModuleTypes(), recordTypeDeclarationNodes_, sawPrivacyError_, sema::Binder::ModuleState::scope, structTypeDeclarationNodes_, sema::Binder::ModuleState::symbol, syntheticLoopCounter_, typeDeclarationModuleIds_, unsafeDepth_, and unsafeTypeContextDepth_.
bind() [3/3]
std::unique_ptr< BoundRootNode > sema::Binder::bind (std::vector< ModuleInfo > & modules)
Definition at line 403 of file binder.cpp.
{
  std::vector<ModuleInfo *> modulePtrs;
  modulePtrs.reserve(modules.size());
  for (auto &module : modules) {
    modulePtrs.push_back(&module);
  }
  return bind(std::move(modulePtrs));
}
References bind().
bindBody()
std::unique_ptr< BoundBlock > sema::Binder::bindBody (BodyNode * body, bool createScope) private
Definition at line 18 of file binder_stmts.cpp.
{
  auto savedBlock = std::move(currentBlock_);
  if (createScope) {
    pushScope();
  }
  if (body) {
    body->accept(*this);
  }
  auto boundBody = std::make_unique<BoundBlock>();
  if (currentBlock_) {
    boundBody = std::move(currentBlock_);
  }
  if (createScope) {
    popScope();
  }
  currentBlock_ = std::move(savedBlock);
  return boundBody;
}
References BodyNode::accept(), currentBlock_, popScope(), and pushScope().
Referenced by ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
bindExpressionWithExpected()
std::unique_ptr< BoundExpression > sema::Binder::bindExpressionWithExpected (ExpressionNode * expr, std::shared_ptr< zir::Type > expectedType) private
Definition at line 136 of file binder_exprs.cpp.
{
  if (!expr) {
    return nullptr;
  }
  expectedExpressionTypes_.push_back(std::move(expectedType));
  expr->accept(*this);
  expectedExpressionTypes_.pop_back();
  if (expressionStack_.empty()) {
    return nullptr;
  }
  auto boundExpr = std::move(expressionStack_.top());
  expressionStack_.pop();
  return boundExpr;
}
References ExpressionNode::accept(), expectedExpressionTypes_, and expressionStack_.
Referenced by bindSizeOfBuiltinCall(), bindWeakBuiltinCall(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
bindSizeOfBuiltinCall()
bool sema::Binder::bindSizeOfBuiltinCall (FunCall & node) private
Definition at line 1755 of file binder_exprs.cpp.
{
  auto *calleeId = dynamic_cast<ConstId *>(node.callee_.get());
  if (!calleeId || calleeId->value_ != "sizeof") {
    return false;
  }
  if (node.params_.size() != 1 || node.params_[0]->isRef ||
      node.params_[0]->isSpread || !node.params_[0]->name.empty()) {
    error(node.span, "'sizeof' expects exactly one positional argument.");
    return true;
  }
  auto argument =
      bindExpressionWithExpected(node.params_[0]->value.get(), nullptr);
  if (!argument) {
    return true;
  }
  auto layout = layoutOfType(argument->type);
  expressionStack_.push(std::make_unique<BoundLiteral>(
      std::to_string(layout.size),
      std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int)));
  return true;
}
References bindExpressionWithExpected(), bindSizeOfBuiltinCall(), FunCall::callee_, error(), expressionStack_, zir::Int, FunCall::params_, and Node::span.
Referenced by bindSizeOfBuiltinCall(), and visit().
bindWeakBuiltinCall()
bool sema::Binder::bindWeakBuiltinCall (FunCall & node) private
Definition at line 1780 of file binder_exprs.cpp.
{
  auto *calleeId = dynamic_cast<ConstId *>(node.callee_.get());
  if (!calleeId) {
    return false;
  }
  const bool isLock = calleeId->value_ == "lock";
  const bool isAlive = calleeId->value_ == "alive";
  if (!isLock && !isAlive) {
    return false;
  }
  if (node.params_.size() != 1 || node.params_[0]->isRef ||
      node.params_[0]->isSpread || !node.params_[0]->name.empty()) {
    error(node.span, "'" + calleeId->value_ +
                         "' expects exactly one positional argument.");
    return true;
  }
  auto weakExpr =
      bindExpressionWithExpected(node.params_[0]->value.get(), nullptr);
  if (!weakExpr) {
    return true;
  }
  if (weakExpr->type->getKind() != zir::TypeKind::Class) {
    error(node.params_[0]->value->span,
          "'" + calleeId->value_ + "' expects a weak class reference.");
    return true;
  }
  auto weakClassType = std::static_pointer_cast<zir::ClassType>(weakExpr->type);
  if (!weakClassType->isWeak()) {
    error(node.params_[0]->value->span,
          "'" + calleeId->value_ + "' expects a weak class reference.");
    return true;
  }
  if (isAlive) {
    expressionStack_.push(
        std::make_unique<BoundWeakAliveExpression>(std::move(weakExpr)));
    return true;
  }
  auto strongType = std::make_shared<zir::ClassType>(*weakClassType);
  strongType->setWeak(false);
  expressionStack_.push(std::make_unique<BoundWeakLockExpression>(
      std::move(weakExpr), strongType));
  return true;
}
References bindExpressionWithExpected(), bindWeakBuiltinCall(), FunCall::callee_, zir::Class, error(), expressionStack_, FunCall::params_, Node::span, and ConstId::value_.
Referenced by bindWeakBuiltinCall(), and visit().
buildBinaryExpression()
std::unique_ptr< BoundExpression > sema::Binder::buildBinaryExpression (std::unique_ptr< BoundExpression > left, const std::string & op, std::unique_ptr< BoundExpression > right, SourceSpan leftSpan, SourceSpan rightSpan) private
Definition at line 205 of file binder_exprs.cpp.
{
  auto leftType = left->type;
  auto rightType = right->type;
  std::shared_ptr<zir::Type> resultType = leftType;
  if (op == "+" &&
      ((isStringType(leftType) || leftType->getKind() == zir::TypeKind::Char) ||
       (isStringType(rightType) ||
        rightType->getKind() == zir::TypeKind::Char))) {
    bool leftOk =
        isStringType(leftType) || leftType->getKind() == zir::TypeKind::Char;
    bool rightOk =
        isStringType(rightType) || rightType->getKind() == zir::TypeKind::Char;
    bool hasString = isStringType(leftType) || isStringType(rightType);
    if (!leftOk || !rightOk || !hasString) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Concatenation requires String and/or Char operands with at least "
            "one String, got '" +
                renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    }
    resultType = std::make_shared<zir::RecordType>("String", "String");
  } else if ((op == "+" || op == "-") &&
             (isPointerType(leftType) || isPointerType(rightType))) {
    if (op == "+" && isPointerType(leftType) && rightType->isInteger()) {
      resultType = leftType;
    } else if (op == "+" && leftType->isInteger() && isPointerType(rightType)) {
      std::swap(left, right);
      std::swap(leftType, rightType);
      resultType = leftType;
    } else if (op == "-" && isPointerType(leftType) && rightType->isInteger()) {
      resultType = leftType;
    } else if (op == "-" && isPointerType(leftType) &&
               isPointerType(rightType)) {
      if (leftType->toString() != rightType->toString()) {
        error(SourceSpan::merge(leftSpan, rightSpan),
              "Pointer subtraction requires operands of the same type.");
      }
      resultType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
    } else {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Invalid pointer arithmetic between '" +
                renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    }
  } else if (op == "+" || op == "-" || op == "*" || op == "/" || op == "%") {
    if (!isNumeric(leftType) || !isNumeric(rightType)) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Operator '" + op + "' cannot be applied to '" +
                renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    } else {
      resultType = getPromotedType(leftType, rightType);
      left = wrapInCast(std::move(left), resultType);
      right = wrapInCast(std::move(right), resultType);
    }
  } else if (op == "&" || op == "|" || op == "^") {
    if (!leftType->isInteger() || !rightType->isInteger()) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Bitwise operator '" + op + "' requires integer operands, got '" +
                renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    } else {
      resultType = getPromotedType(leftType, rightType);
      left = wrapInCast(std::move(left), resultType);
      right = wrapInCast(std::move(right), resultType);
    }
  } else if (op == "<<" || op == ">>") {
    if (!leftType->isInteger() || !rightType->isInteger()) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Shift operator '" + op + "' requires integer operands, got '" +
                renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    } else {
      // Keep the left-hand integer type for shift results.
      resultType = leftType;
      right = wrapInCast(std::move(right), resultType);
      if (auto shiftAmount = evaluateConstantInt(right.get())) {
        if (*shiftAmount < 0) {
          error(SourceSpan::merge(leftSpan, rightSpan),
                "Shift amount must be non-negative, got '" +
                    std::to_string(*shiftAmount) + "'.");
        } else {
          unsigned width = static_cast<unsigned>(typeBitWidth(resultType));
          if (width == 0 || static_cast<uint64_t>(*shiftAmount) >= width) {
            error(SourceSpan::merge(leftSpan, rightSpan),
                  "Shift amount '" + std::to_string(*shiftAmount) +
                      "' is out of range for type '" +
                      renderTypeForUser(resultType) + "' (" +
                      std::to_string(width) + "-bit width).");
          }
        }
      }
    }
  } else if (op == "==" || op == "!=" || op == "<" || op == "<=" || op == ">" ||
             op == ">=") {
    bool classOrNullComparison =
        (leftType->getKind() == zir::TypeKind::Class &&
         isNullType(rightType)) ||
        (rightType->getKind() == zir::TypeKind::Class && isNullType(leftType));
    if (!classOrNullComparison &&
        (isPointerType(leftType) || isPointerType(rightType) ||
         isNullType(leftType) || isNullType(rightType))) {
    }
    bool stringComparison = isStringType(leftType) && isStringType(rightType) &&
                            (op == "==" || op == "!=");
    // Reject comparisons of struct types except String/StringView equality.
    if (!stringComparison && (leftType->getKind() == zir::TypeKind::Record ||
                              rightType->getKind() == zir::TypeKind::Record)) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Cannot compare struct types '" + renderTypeForUser(leftType) +
                "' and '" + renderTypeForUser(rightType) + "'");
    }
    if (!canConvert(leftType, rightType) && !canConvert(rightType, leftType)) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Cannot compare '" + renderTypeForUser(leftType) + "' and '" +
                renderTypeForUser(rightType) + "'");
    } else if (isNullType(leftType) && isPointerType(rightType)) {
      left = wrapInCast(std::move(left), rightType);
    } else if (isNullType(rightType) && isPointerType(leftType)) {
      right = wrapInCast(std::move(right), leftType);
    } else if (isNullType(leftType) &&
               rightType->getKind() == zir::TypeKind::Class) {
      left = wrapInCast(std::move(left), rightType);
    } else if (isNullType(rightType) &&
               leftType->getKind() == zir::TypeKind::Class) {
      right = wrapInCast(std::move(right), leftType);
    } else if ((leftType->isInteger() && rightType->isInteger()) ||
               (leftType->isFloatingPoint() && rightType->isFloatingPoint()) ||
               (leftType->isInteger() && rightType->isFloatingPoint()) ||
               (leftType->isFloatingPoint() && rightType->isInteger())) {
      auto promotedType = getPromotedType(leftType, rightType);
      left = wrapInCast(std::move(left), promotedType);
      right = wrapInCast(std::move(right), promotedType);
    } else if (stringComparison) {
      auto stringViewType =
          std::make_shared<zir::RecordType>("StringView", "StringView");
      left = wrapInCast(std::move(left), stringViewType);
      right = wrapInCast(std::move(right), stringViewType);
    }
    resultType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  } else if (op == "&&" || op == "||") {
    if (leftType->getKind() != zir::TypeKind::Bool ||
        rightType->getKind() != zir::TypeKind::Bool) {
      error(SourceSpan::merge(leftSpan, rightSpan),
            "Logical operator '" + op + "' requires Bool operands.");
    }
    resultType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  }
  auto result = std::make_unique<BoundBinaryExpression>(
      std::move(left), op, std::move(right), resultType);
  if (auto folded = foldConstantBinary(result.get()))
    return folded;
  return result;
}
References zir::Bool, canConvert(), zir::Char, zir::Class, error(), evaluateConstantInt(), foldConstantBinary(), getPromotedType(), zir::Int, isNullType(), isNumeric(), isPointerType(), sema::isStringType(), SourceSpan::merge(), zir::Record, renderTypeForUser(), typeBitWidth(), and wrapInCast().
Referenced by visit(), and visit().
buildGenericBindings()
std::unordered_map< std::string, std::shared_ptr< zir::Type > > sema::Binder::buildGenericBindings (const FunctionSymbol & function, const std::vector< std::unique_ptr< BoundExpression > > & arguments, const std::vector< std::unique_ptr< TypeNode > > & explicitTypeArgs, SourceSpan callSpan, std::string * failureReason = nullptr) private
Definition at line 880 of file binder_types.cpp.
{
  (void)callSpan;
  std::unordered_map<std::string, std::shared_ptr<zir::Type>> bindings;
  if (function.genericParameterNames.empty()) {
    return bindings;
  }
  if (explicitTypeArgs.size() > function.genericParameterNames.size()) {
    if (failureReason) {
      *failureReason = "explicit generic argument count mismatch";
    }
    return {};
  }
  for (size_t i = 0; i < explicitTypeArgs.size(); ++i) {
    if (!explicitTypeArgs[i]) {
      continue;
    }
    auto mapped = mapType(*explicitTypeArgs[i]);
    if (!mapped) {
      if (failureReason) {
        *failureReason = "unknown generic type argument";
      }
      return {};
    }
    bindings[function.genericParameterNames[i]] = mapped;
  }
  auto declIt = functionDeclarationNodes_.find(&function);
  const auto *decl =
      declIt == functionDeclarationNodes_.end() ? nullptr : declIt->second;
  std::function<bool(const std::shared_ptr<zir::Type> &,
                     const std::shared_ptr<zir::Type> &)>
      inferFrom = [&](const std::shared_ptr<zir::Type> &paramType,
                      const std::shared_ptr<zir::Type> &argType) -> bool {
    if (!paramType || !argType) {
      return true;
    }
    if (paramType->getKind() == zir::TypeKind::Record) {
      auto rec = std::static_pointer_cast<zir::RecordType>(paramType);
      if (isVariadicViewType(paramType)) {
        const auto &fields = rec->getFields();
        if (fields.size() < 2 ||
            fields[0].type->getKind() != zir::TypeKind::Pointer) {
          return false;
        }
        auto dataPtr =
            std::static_pointer_cast<zir::PointerType>(fields[0].type);
        if (argType->getKind() == zir::TypeKind::Array) {
          auto aa = std::static_pointer_cast<zir::ArrayType>(argType);
          return inferFrom(dataPtr->getBaseType(), aa->getBaseType());
        }
        if (argType->getKind() == zir::TypeKind::Record &&
            isVariadicViewType(argType)) {
          auto argRec = std::static_pointer_cast<zir::RecordType>(argType);
          const auto &argFields = argRec->getFields();
          if (argFields.size() < 2 ||
              argFields[0].type->getKind() != zir::TypeKind::Pointer) {
            return false;
          }
          auto argDataPtr =
              std::static_pointer_cast<zir::PointerType>(argFields[0].type);
          return inferFrom(dataPtr->getBaseType(), argDataPtr->getBaseType());
        }
      }
      if (rec->isGenericInstance() &&
          argType->getKind() == zir::TypeKind::Record) {
        auto argRecord = std::static_pointer_cast<zir::RecordType>(argType);
        if (!argRecord->isGenericInstance() ||
            rec->getGenericBaseName() != argRecord->getGenericBaseName() ||
            rec->getGenericArguments().size() !=
                argRecord->getGenericArguments().size()) {
          return false;
        }
        for (size_t i = 0; i < rec->getGenericArguments().size(); ++i) {
          if (!inferFrom(rec->getGenericArguments()[i],
                         argRecord->getGenericArguments()[i])) {
            return false;
          }
        }
        return true;
      }
      auto paramName = rec->getName();
      std::string normalizedParamName =
          (!paramName.empty() && paramName[0] == '%') ? paramName.substr(1)
                                                      : paramName;
      auto isGenericName = std::find(function.genericParameterNames.begin(),
                                     function.genericParameterNames.end(),
                                     normalizedParamName) !=
                           function.genericParameterNames.end();
      if (isGenericName) {
        auto it = bindings.find(normalizedParamName);
        if (it == bindings.end()) {
          bindings[normalizedParamName] = argType;
          return true;
        }
        return it->second->toString() == argType->toString();
      }
      return true;
    }
    if (paramType->getKind() == zir::TypeKind::Class) {
      auto cls = std::static_pointer_cast<zir::ClassType>(paramType);
      if (cls->isGenericInstance() &&
          argType->getKind() == zir::TypeKind::Class) {
        auto argClass = std::static_pointer_cast<zir::ClassType>(argType);
        std::shared_ptr<zir::ClassType> matchingArgClass = argClass;
        while (matchingArgClass &&
               (!matchingArgClass->isGenericInstance() ||
                cls->getGenericBaseName() !=
                    matchingArgClass->getGenericBaseName())) {
          matchingArgClass = matchingArgClass->getBase();
        }
        if (!matchingArgClass ||
            matchingArgClass->getGenericArguments().size() !=
                cls->getGenericArguments().size()) {
          return false;
        }
        for (size_t i = 0; i < cls->getGenericArguments().size(); ++i) {
          if (!inferFrom(cls->getGenericArguments()[i],
                         matchingArgClass->getGenericArguments()[i])) {
            return false;
          }
        }
        return true;
      }
      auto paramName = cls->getName();
      std::string normalizedParamName =
          (!paramName.empty() && paramName[0] == '%') ? paramName.substr(1)
                                                      : paramName;
      auto isGenericName = std::find(function.genericParameterNames.begin(),
                                     function.genericParameterNames.end(),
                                     normalizedParamName) !=
                           function.genericParameterNames.end();
      if (isGenericName) {
        auto it = bindings.find(normalizedParamName);
        if (it == bindings.end()) {
          bindings[normalizedParamName] = argType;
          return true;
        }
        return it->second->toString() == argType->toString();
      }
      return true;
    }
    if (paramType->getKind() == zir::TypeKind::Pointer &&
        argType->getKind() == zir::TypeKind::Pointer) {
      auto pp = std::static_pointer_cast<zir::PointerType>(paramType);
      auto ap = std::static_pointer_cast<zir::PointerType>(argType);
      return inferFrom(pp->getBaseType(), ap->getBaseType());
    }
    if (paramType->getKind() == zir::TypeKind::Array &&
        argType->getKind() == zir::TypeKind::Array) {
      auto pa = std::static_pointer_cast<zir::ArrayType>(paramType);
      auto aa = std::static_pointer_cast<zir::ArrayType>(argType);
      if (pa->getSize() != aa->getSize()) {
        return false;
      }
      return inferFrom(pa->getBaseType(), aa->getBaseType());
    }
    return true;
  };
  size_t fixedCount = function.fixedParameterCount();
  for (size_t i = 0; i < arguments.size() && i < fixedCount; ++i) {
    if (!inferFrom(function.parameters[i]->type, arguments[i]->type)) {
      if (failureReason) {
        *failureReason = "conflicting generic type inference";
      }
      return {};
    }
  }
  for (const auto &name : function.genericParameterNames) {
    if (bindings.find(name) == bindings.end()) {
      bool filledFromDefault = false;
      if (decl) {
        auto paramIndex = static_cast<size_t>(std::distance(
            function.genericParameterNames.begin(),
            std::find(function.genericParameterNames.begin(),
                      function.genericParameterNames.end(), name)));
        if (paramIndex < decl->genericParams_.size() &&
            decl->genericParams_[paramIndex] &&
            decl->genericParams_[paramIndex]->defaultType) {
          activeGenericBindingsStack_.push_back(bindings);
          auto mapped = mapType(*decl->genericParams_[paramIndex]->defaultType);
          activeGenericBindingsStack_.pop_back();
          if (mapped) {
            bindings[name] = mapped;
            filledFromDefault = true;
          }
        }
      }
      if (!filledFromDefault) {
        if (failureReason) {
          *failureReason = "cannot infer generic type parameter '" + name + "'";
        }
        return {};
      }
    }
  }
  if (decl) {
    if (!validateGenericConstraints(decl->genericConstraints_, bindings,
                                    failureReason)) {
      return {};
    }
  }
  return bindings;
}
References activeGenericBindingsStack_, zir::Array, zir::Class, sema::FunctionSymbol::fixedParameterCount(), functionDeclarationNodes_, sema::FunctionSymbol::genericParameterNames, sema::isVariadicViewType(), mapType(), sema::FunctionSymbol::parameters, zir::Pointer, zir::Record, and validateGenericConstraints().
Referenced by visit().
canConvert()
bool sema::Binder::canConvert (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const private
Definition at line 1622 of file binder_types.cpp.
{
  if (!from || !to)
    return false;
  if (from->getKind() == to->getKind() && from->toString() == to->toString())
    return true;
  auto key = std::make_pair(from.get(), to.get());
  auto cacheIt = canConvertCache_.find(key);
  if (cacheIt != canConvertCache_.end())
    return cacheIt->second;
  auto &cached = canConvertCache_[key];
  if (isNullType(from) &&
      (isPointerType(to) || to->getKind() == zir::TypeKind::Class))
    return cached = true;
  if (isStringType(from) && isStringType(to))
    return cached = true;
  if (isStringType(from) && isPointerType(to)) {
    auto ptrType = std::static_pointer_cast<zir::PointerType>(to);
    return cached = (ptrType &&
                     ptrType->getBaseType()->getKind() == zir::TypeKind::Char);
  }
  if (from->getKind() == zir::TypeKind::Class &&
      to->getKind() == zir::TypeKind::Class) {
    auto fromClass = std::static_pointer_cast<zir::ClassType>(from);
    auto toClass = std::static_pointer_cast<zir::ClassType>(to);
    if (fromClass->isWeak() && !toClass->isWeak())
      return cached = false;
    for (auto current = fromClass; current; current = current->getBase()) {
      if (current->getName() == toClass->getName())
        return cached = true;
    }
  }
  if (from->getKind() == zir::TypeKind::Array && isVariadicViewType(to)) {
    auto arrayType = std::static_pointer_cast<zir::ArrayType>(from);
    auto viewType = std::static_pointer_cast<zir::RecordType>(to);
    if (!viewType->getFields().empty() &&
        viewType->getFields()[0].type->getKind() == zir::TypeKind::Pointer) {
      auto dataType = std::static_pointer_cast<zir::PointerType>(
          viewType->getFields()[0].type);
      return cached = (arrayType->getBaseType()->toString() ==
                       dataType->getBaseType()->toString());
    }
  }
  if (isFailableType(from) && isFailableType(to)) {
    auto fromValueType = failableValueType(from);
    auto fromErrorType = failableErrorType(from);
    auto toValueType = failableValueType(to);
    auto toErrorType = failableErrorType(to);
    return cached = (canConvert(fromValueType, toValueType) &&
                     canConvert(fromErrorType, toErrorType));
  }
  if (isNumeric(from) && isNumeric(to))
    return cached = true;
  if (from->getKind() == zir::TypeKind::Enum &&
      to->getKind() == zir::TypeKind::Int)
    return cached = true;
  return cached = false;
}
References zir::Array, canConvert(), canConvertCache_, zir::Char, zir::Class, zir::Enum, sema::failableErrorType(), sema::failableValueType(), zir::Int, sema::isFailableType(), isNullType(), isNumeric(), isPointerType(), sema::isStringType(), sema::isVariadicViewType(), and zir::Pointer.
Referenced by buildBinaryExpression(), canConvert(), conversionCost(), validateGenericConstraints(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
conversionCost()
int sema::Binder::conversionCost (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const private
Definition at line 1157 of file binder_types.cpp.
{
  if (!from || !to) {
    return 1000;
  }
  if (from->toString() == to->toString()) {
    return 0;
  }
  if (isNullType(from) && isPointerType(to)) {
    return 3;
  }
  if (!canConvert(from, to)) {
    return 1000;
  }
  if (isStringType(from) && isStringType(to)) {
    return zap::text::isStringViewType(to) ? 0 : 1;
  }
  if (from->getKind() == zir::TypeKind::Enum && to->isInteger()) {
    return 1;
  }
  if (from->isFloatingPoint() && to->isFloatingPoint()) {
    return typeBitWidth(to) >= typeBitWidth(from) ? 1 : 5;
  }
  if (isSignedIntegerType(from) && isSignedIntegerType(to)) {
    return typeBitWidth(to) >= typeBitWidth(from) ? 1 : 4;
  }
  if (isUnsignedIntegerType(from) && isUnsignedIntegerType(to)) {
    return typeBitWidth(to) >= typeBitWidth(from) ? 1 : 4;
  }
  if (from->isInteger() && to->isFloatingPoint()) {
    return typeBitWidth(to) >= typeBitWidth(from) ? 2 : 5;
  }
  if (from->isFloatingPoint() && to->isInteger()) {
    return 6;
  }
  if (from->isInteger() && to->isInteger()) {
    return 5;
  }
  return 7;
}
References canConvert(), zir::Enum, isNullType(), isPointerType(), isSignedIntegerType(), sema::isStringType(), zap::text::isStringViewType(), isUnsignedIntegerType(), and typeBitWidth().
Referenced by describeConversion(), visit(), and visit().
currentExpectedExpressionType()
std::shared_ptr< zir::Type > sema::Binder::currentExpectedExpressionType () const private
Definition at line 155 of file binder_exprs.cpp.
{
  if (expectedExpressionTypes_.empty()) {
    return nullptr;
  }
  return expectedExpressionTypes_.back();
}
References expectedExpressionTypes_.
Referenced by visit(), visit(), visit(), and visit().
currentModuleLinkPath()
std::string sema::Binder::currentModuleLinkPath () const private
Definition at line 830 of file binder.cpp.
{
  auto it = modules_.find(currentModuleId_);
  if (it == modules_.end() || !it->second.info) {
    return currentModuleId_;
  }
  return it->second.info->linkPath.empty() ? it->second.info->moduleId
                                           : it->second.info->linkPath;
}
References currentModuleId_, and modules_.
Referenced by visit(), and visit().
describeConversion()
std::string sema::Binder::describeConversion (std::shared_ptr< zir::Type > from, std::shared_ptr< zir::Type > to) const private
Definition at line 1206 of file binder_types.cpp.
{
  if (!from || !to) {
    return "invalid conversion";
  }
  int cost = conversionCost(from, to);
  if (cost == 0) {
    return "exact match";
  }
  if (isNullType(from) &&
      (isPointerType(to) || to->getKind() == zir::TypeKind::Class)) {
    return "null-to-reference conversion";
  }
  if (from->isFloatingPoint() && to->isFloatingPoint()) {
    return typeBitWidth(to) >= typeBitWidth(from) ? "floating widening"
                                                  : "floating narrowing";
  }
  if (isSignedIntegerType(from) && isSignedIntegerType(to)) {
    return typeBitWidth(to) >= typeBitWidth(from) ? "signed widening"
                                                  : "signed narrowing";
  }
  if (isUnsignedIntegerType(from) && isUnsignedIntegerType(to)) {
    return typeBitWidth(to) >= typeBitWidth(from) ? "unsigned widening"
                                                  : "unsigned narrowing";
  }
  if (from->isInteger() && to->isFloatingPoint()) {
    return "integer-to-float conversion";
  }
  if (from->isFloatingPoint() && to->isInteger()) {
    return "float-to-integer conversion";
  }
  if (from->isInteger() && to->isInteger()) {
    return "signedness-changing integer conversion";
  }
  return cost >= 1000 ? "not convertible" : "implicit conversion";
}
References zir::Class, conversionCost(), isNullType(), isPointerType(), isSignedIntegerType(), isUnsignedIntegerType(), and typeBitWidth().
Referenced by visit().
displayTypeName()
std::string sema::Binder::displayTypeName (const std::string & moduleName, const std::string & name) const private
Definition at line 752 of file binder.cpp.
{
  if (moduleName.empty() || moduleName == "__single_module__") {
    return name;
  }
  return moduleName + "." + name;
}
Referenced by predeclareModuleTypes().
ensureGenericFunctionInstantiation()
std::shared_ptr< FunctionSymbol > sema::Binder::ensureGenericFunctionInstantiation (const std::shared_ptr< FunctionSymbol > & baseFunction, const std::vector< std::pair< std::string, std::shared_ptr< zir::Type > > > & genericBindings, SourceSpan callSpan) private
Definition at line 18 of file binder_types.cpp.
{
  if (!baseFunction) {
    return nullptr;
  }
  if (baseFunction->genericParameterNames.empty()) {
    return baseFunction;
  }
  std::vector<std::string> missing;
  for (const auto &name : baseFunction->genericParameterNames) {
    auto it =
        std::find_if(genericBindings.begin(), genericBindings.end(),
                     [&](const auto &entry) { return entry.first == name; });
    if (it == genericBindings.end()) {
      missing.push_back(name);
    }
  }
  if (!missing.empty()) {
    std::string msg;
    msg.reserve(64);
    msg += "Missing generic type arguments for function '";
    msg += baseFunction->name;
    msg += "': ";
    for (size_t i = 0; i < missing.size(); ++i) {
      if (i != 0)
        msg += ", ";
      msg += missing[i];
    }
    error(callSpan, msg);
    return nullptr;
  }
  std::string cacheKey;
  {
    size_t estimatedSize = baseFunction->linkName.size() + 2 +
                           baseFunction->genericParameterNames.size() * 16;
    cacheKey.reserve(estimatedSize);
    cacheKey += baseFunction->linkName;
    cacheKey += '<';
    for (size_t i = 0; i < baseFunction->genericParameterNames.size(); ++i) {
      if (i != 0)
        cacheKey += ',';
      const auto &name = baseFunction->genericParameterNames[i];
      auto it =
          std::find_if(genericBindings.begin(), genericBindings.end(),
                       [&](const auto &entry) { return entry.first == name; });
      cacheKey += name;
      cacheKey += '=';
      cacheKey += (it != genericBindings.end() && it->second)
                      ? it->second->toString()
                      : "<?>";
    }
    cacheKey += '>';
  }
  auto cachedIt = genericFunctionInstantiations_.find(cacheKey);
  if (cachedIt != genericFunctionInstantiations_.end()) {
    return cachedIt->second;
  }
  auto declIt = functionDeclarationNodes_.find(baseFunction.get());
  if (declIt == functionDeclarationNodes_.end() || !declIt->second) {
    error(callSpan,
          "Internal error: missing declaration for generic function '" +
              baseFunction->name + "'.");
    return nullptr;
  }
  auto moduleIdIt = functionDeclarationModuleIds_.find(baseFunction.get());
  auto moduleId = moduleIdIt == functionDeclarationModuleIds_.end()
                      ? currentModuleId_
                      : moduleIdIt->second;
  auto moduleIt = modules_.find(moduleId);
  if (moduleIt == modules_.end() || !moduleIt->second.info) {
    error(
        callSpan,
        "Internal error: current module not found for generic instantiation.");
    return nullptr;
  }
  std::unordered_map<std::string, std::shared_ptr<zir::Type>> genericBindingMap;
  genericBindingMap.reserve(genericBindings.size());
  for (const auto &[name, type] : genericBindings) {
    genericBindingMap[name] = type;
  }
  std::vector<std::shared_ptr<VariableSymbol>> instantiatedParams;
  instantiatedParams.reserve(baseFunction->parameters.size());
  for (const auto &param : baseFunction->parameters) {
    auto instType = substituteGenericType(param->type, genericBindingMap);
    auto instParam = std::make_shared<VariableSymbol>(
        param->name, instType, param->is_const, param->is_ref, param->linkName,
        param->moduleName, param->visibility);
    instParam->is_variadic_pack = param->is_variadic_pack;
    instParam->variadic_element_type =
        substituteGenericType(param->variadic_element_type, genericBindingMap);
    instantiatedParams.push_back(std::move(instParam));
  }
  auto instantiatedReturn =
      substituteGenericType(baseFunction->returnType, genericBindingMap);
  auto instantiated = std::make_shared<FunctionSymbol>(
      baseFunction->name, std::move(instantiatedParams), instantiatedReturn, "",
      baseFunction->moduleName, baseFunction->visibility,
      baseFunction->isUnsafe, baseFunction->isCVariadic);
  instantiated->isMethod = baseFunction->isMethod;
  instantiated->isStatic = baseFunction->isStatic;
  instantiated->isConstructor = baseFunction->isConstructor;
  instantiated->isDestructor = baseFunction->isDestructor;
  instantiated->vtableSlot = -1;
  instantiated->ownerTypeName = baseFunction->ownerTypeName;
  instantiated->isGenericInstantiation = true;
  instantiated->genericArguments.clear();
  for (const auto &[name, type] : genericBindings) {
    instantiated->genericArguments[name] = type;
  }
  std::string genericSuffix;
  for (size_t i = 0; i < baseFunction->genericParameterNames.size(); ++i) {
    if (i != 0) {
      genericSuffix += "$";
    }
    const auto &name = baseFunction->genericParameterNames[i];
    auto it =
        std::find_if(genericBindings.begin(), genericBindings.end(),
                     [&](const auto &entry) { return entry.first == name; });
    if (it == genericBindings.end() || !it->second) {
      error(callSpan, "Missing binding for generic parameter '" + name + "'.");
      return nullptr;
    }
    genericSuffix += sanitizeTypeName(name + "_" + abiTypeKey(it->second));
  }
  instantiated->linkName = baseFunction->linkName + "$g$" + genericSuffix;
  genericFunctionInstantiations_[cacheKey] = instantiated;
  functionGenericParamNames_[instantiated.get()] = {};
  functionDeclarationNodes_[instantiated.get()] = declIt->second;
  functionDeclarationModuleIds_[instantiated.get()] = moduleId;
  auto inProgressIt =
      std::find(genericInstantiationInProgress_.begin(),
                genericInstantiationInProgress_.end(), cacheKey);
  if (inProgressIt != genericInstantiationInProgress_.end()) {
    return instantiated;
  }
  auto emittedIt = genericInstantiationEmitted_.find(instantiated.get());
  if (emittedIt != genericInstantiationEmitted_.end() && emittedIt->second) {
    return instantiated;
  }
  genericInstantiationInProgress_.push_back(cacheKey);
  auto oldScope = currentScope_;
  auto oldFunction = currentFunction_;
  auto oldModuleId = currentModuleId_;
  int oldUnsafeDepth = unsafeDepth_;
  currentModuleId_ = moduleIt->second.info->moduleId;
  currentScope_ = moduleIt->second.scope;
  currentFunction_ = instantiated;
  if (instantiated->isUnsafe) {
    ++unsafeDepth_;
  }
  pushScope();
  for (const auto &param : instantiated->parameters) {
    if (!currentScope_->declare(param->name, param)) {
      error(callSpan, "Parameter '" + param->name +
                          "' already declared in generic instantiation.");
    }
  }
  activeGenericBindingsStack_.push_back(
      std::unordered_map<std::string, std::shared_ptr<zir::Type>>(
          genericBindings.begin(), genericBindings.end()));
  auto boundBody = bindBody(declIt->second->body_.get(), false);
  activeGenericBindingsStack_.pop_back();
  popScope();
  currentScope_ = oldScope;
  currentFunction_ = oldFunction;
  currentModuleId_ = oldModuleId;
  unsafeDepth_ = oldUnsafeDepth;
  bool hasReturn = blockAlwaysReturns(boundBody.get());
  if (!hasReturn && instantiated->linkName == "main" &&
      instantiated->returnType->isInteger()) {
    auto intType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
    auto lit = std::make_unique<BoundLiteral>("0", intType);
    boundBody->statements.push_back(
        std::make_unique<BoundReturnStatement>(std::move(lit)));
    hasReturn = true;
  }
  if (!hasReturn &&
      instantiated->returnType->getKind() != zir::TypeKind::Void) {
    auto kind = instantiated->returnType->getKind();
    if (instantiated->returnType->isInteger() || kind == zir::TypeKind::Float ||
        kind == zir::TypeKind::Bool) {
      std::string litVal = "0";
      if (kind == zir::TypeKind::Float)
        litVal = "0.0";
      else if (kind == zir::TypeKind::Bool)
        litVal = "false";
      auto lit =
          std::make_unique<BoundLiteral>(litVal, instantiated->returnType);
      boundBody->statements.push_back(
          std::make_unique<BoundReturnStatement>(std::move(lit)));
    }
    _diag.report(callSpan, zap::DiagnosticLevel::Warning,
                 "Generic function '" + instantiated->name +
                     "' has non-void return type but no return on some paths.");
  }
  boundRoot_->functions.push_back(std::make_unique<BoundFunctionDeclaration>(
      instantiated, std::move(boundBody)));
  genericInstantiationEmitted_[instantiated.get()] = true;
  genericInstantiationInProgress_.pop_back();
  return instantiated;
}
References _diag, sema::abiTypeKey(), activeGenericBindingsStack_, bindBody(), sema::blockAlwaysReturns(), zir::Bool, boundRoot_, currentFunction_, currentModuleId_, currentScope_, error(), zir::Float, functionDeclarationModuleIds_, functionDeclarationNodes_, functionGenericParamNames_, genericFunctionInstantiations_, genericInstantiationEmitted_, genericInstantiationInProgress_, zir::Int, modules_, popScope(), pushScope(), sema::sanitizeTypeName(), substituteGenericType(), unsafeDepth_, zir::Void, and zap::Warning.
Referenced by visit().
ensureModuleValuesReady()
void sema::Binder::ensureModuleValuesReady (ModuleState & module) private
Definition at line 402 of file binder_decls.cpp.
{
  if (module.finalImportsApplied) {
    return;
  }
  if (module.valuesPreparationInProgress) {
    return;
  }
  module.valuesPreparationInProgress = true;
  for (const auto &import : module.info->imports) {
    for (const auto &targetId : import.targetModuleIds) {
      auto targetIt = modules_.find(targetId);
      if (targetIt != modules_.end()) {
        ensureModuleValuesReady(targetIt->second);
      }
    }
  }
  if (!module.valuesPredeclared) {
    predeclareModuleValues(module);
    module.valuesPredeclared = true;
  }
  if (!module.finalImportsApplied) {
    applyImports(module, false);
    module.finalImportsApplied = true;
  }
  module.valuesPreparationInProgress = false;
}
References applyImports(), ensureModuleValuesReady(), sema::Binder::ModuleState::finalImportsApplied, sema::ModuleInfo::imports, sema::Binder::ModuleState::info, modules_, predeclareModuleValues(), sema::Binder::ModuleState::valuesPredeclared, and sema::Binder::ModuleState::valuesPreparationInProgress.
Referenced by bind(), and ensureModuleValuesReady().
error()
void sema::Binder::error (SourceSpan span, const std::string & message) private
Definition at line 1048 of file binder.cpp.
{
  if (message.find(" is private.") != std::string::npos) {
    sawPrivacyError_ = true;
  }
  if (sawPrivacyError_ &&
      (message.find("Undefined identifier: ") != std::string::npos ||
       message.find("Unknown type: ") != std::string::npos ||
       message.find("Unknown return type in function ") != std::string::npos ||
       message.find("Unknown generic type argument in type ") !=
           std::string::npos)) {
    return;
  }
  hadError_ = true;
  _diag.report(span, zap::DiagnosticLevel::Error, message);
}
References _diag, zap::Error, hadError_, and sawPrivacyError_.
Referenced by applyImports(), bindSizeOfBuiltinCall(), bindWeakBuiltinCall(), buildBinaryExpression(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), mapType(), predeclareModuleAliases(), predeclareModuleTypes(), predeclareModuleValues(), requireUnsafeContext(), requireUnsafeEnabled(), resolveModuleMember(), resolveQualifiedSymbol(), validateAndApplyFunctionAttributes(), validateAndApplyTypeAttributes(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
evaluateConstantInt()
std::optional< int64_t > sema::Binder::evaluateConstantInt (const BoundExpression * expr) private
Definition at line 936 of file binder.cpp.
{
  if (auto lit = dynamic_cast<const BoundLiteral *>(expr)) {
    try {
      const std::string &v = lit->value;
      if (v.size() > 2 && v[0] == '0') {
        if (v[1] == 'x' || v[1] == 'X') {
          return static_cast<int64_t>(std::stoull(v, nullptr, 16));
        }
        if (v[1] == 'b' || v[1] == 'B') {
          return static_cast<int64_t>(std::stoull(v.substr(2), nullptr, 2));
        }
        if (v[1] == 'o' || v[1] == 'O') {
          return static_cast<int64_t>(std::stoull(v.substr(2), nullptr, 8));
        }
      }
      return std::stoll(v);
    } catch (...) {
      return std::nullopt;
    }
  }
  if (auto unary = dynamic_cast<const BoundUnaryExpression *>(expr)) {
    auto inner = evaluateConstantInt(unary->expr.get());
    if (!inner)
      return std::nullopt;
    if (unary->op == "-")
      return -*inner;
    return inner;
  }
  if (auto binary = dynamic_cast<const BoundBinaryExpression *>(expr)) {
    auto left = evaluateConstantInt(binary->left.get());
    auto right = evaluateConstantInt(binary->right.get());
    if (!left || !right)
      return std::nullopt;
    if (binary->op == "+")
      return *left + *right;
    if (binary->op == "-")
      return *left - *right;
    if (binary->op == "*")
      return *left * *right;
    if (binary->op == "/")
      return *right == 0 ? std::nullopt
                         : std::optional<int64_t>(*left / *right);
    if (binary->op == "%")
      return *right == 0 ? std::nullopt
                         : std::optional<int64_t>(*left % *right);
    if (binary->op == "&")
      return *left & *right;
    if (binary->op == "|")
      return *left | *right;
    if (binary->op == "^")
      return *left ^ *right;
    if (binary->op == "<<") {
      if (*right < 0)
        return std::nullopt;
      unsigned width =
          binary->left->type
              ? static_cast<unsigned>(typeBitWidth(binary->left->type))
              : 0u;
      if (width == 0 || static_cast<uint64_t>(*right) >= width)
        return std::nullopt;
      return static_cast<int64_t>(static_cast<uint64_t>(*left)
                                  << static_cast<uint64_t>(*right));
    }
    if (binary->op == ">>") {
      if (*right < 0)
        return std::nullopt;
      unsigned width =
          binary->left->type
              ? static_cast<unsigned>(typeBitWidth(binary->left->type))
              : 0u;
      if (width == 0 || static_cast<uint64_t>(*right) >= width)
        return std::nullopt;
      return *left >> static_cast<uint64_t>(*right);
    }
  }
  return std::nullopt;
}
References evaluateConstantInt(), and typeBitWidth().
Referenced by buildBinaryExpression(), evaluateConstantInt(), foldConstantBinary(), and mapType().
findFunctionBySignature()
std::shared_ptr< FunctionSymbol > sema::Binder::findFunctionBySignature (const std::shared_ptr< Symbol > & symbol, const FunctionSymbol & prototype) const private
Definition at line 675 of file binder.cpp.
{
  for (const auto &candidate : collectOverloads(symbol)) {
    if (candidate && sameFunctionSignature(*candidate, prototype)) {
      return candidate;
    }
  }
  return nullptr;
}
References sema::collectOverloads(), and sema::sameFunctionSignature().
Referenced by predeclareModuleValues().
findOverriddenVtableSlot()
int sema::Binder::findOverriddenVtableSlot (const ClassInfo & classInfo, const FunctionSymbol & method) const private
Definition at line 736 of file binder.cpp.
{
  auto existingIt = classInfo.methods.find(method.name);
  if (existingIt == classInfo.methods.end()) {
    return -1;
  }
  for (const auto &candidate : collectOverloads(existingIt->second)) {
    if (candidate && candidate->vtableSlot >= 0 &&
        sameMethodDispatchSignature(*candidate, method)) {
      return candidate->vtableSlot;
    }
  }
  return -1;
}
References sema::collectOverloads(), sema::Binder::ClassInfo::methods, sema::Symbol::name, and sema::sameMethodDispatchSignature().
Referenced by instantiateGenericTypeSymbol().
foldConstantBinary()
std::unique_ptr< BoundExpression > sema::Binder::foldConstantBinary (const BoundBinaryExpression * binary) private
Definition at line 1019 of file binder.cpp.
{
  if (!binary)
    return nullptr;
  auto *left = dynamic_cast<const BoundLiteral *>(binary->left.get());
  auto *right = dynamic_cast<const BoundLiteral *>(binary->right.get());
  if (!left || !right)
    return nullptr;
  // String literal concatenation.
  if (binary->op == "+" && isStringType(binary->type)) {
    if (isStringType(left->type) && isStringType(right->type)) {
      return std::make_unique<BoundLiteral>(
          left->value + right->value,
          std::make_shared<zir::RecordType>("StringView", "StringView"));
    }
    return nullptr;
  }
  // Integer arithmetic/bitwise.
  if (binary->type && binary->type->isInteger()) {
    if (auto value = evaluateConstantInt(binary))
      return std::make_unique<BoundLiteral>(std::to_string(*value),
                                            binary->type);
  }
  return nullptr;
}
References evaluateConstantInt(), sema::isStringType(), sema::BoundBinaryExpression::left, sema::BoundBinaryExpression::op, sema::BoundBinaryExpression::right, and sema::BoundExpression::type.
Referenced by buildBinaryExpression().
functionSignatureKey()
std::string sema::Binder::functionSignatureKey (const FunctionSymbol & function) const private
Definition at line 593 of file binder.cpp.
{
  std::string key;
  for (const auto &param : function.parameters) {
    if (!key.empty()) {
      key += "|";
    }
    if (param->is_ref) {
      key += "ref:";
    }
    if (param->is_variadic_pack) {
      key += "varargs:";
    }
    key += abiTypeKey(param->type);
  }
  if (function.isCVariadic) {
    if (!key.empty()) {
      key += "|";
    }
    key += "cvarargs";
  }
  return key;
}
References sema::abiTypeKey(), sema::FunctionSymbol::isCVariadic, and sema::FunctionSymbol::parameters.
Referenced by instantiateGenericTypeSymbol(), and mangleFunctionName().
getCVariadicArgumentType()
std::shared_ptr< zir::Type > sema::Binder::getCVariadicArgumentType (std::shared_ptr< zir::Type > type) private
Definition at line 1755 of file binder_types.cpp.
{
  if (!type)
    return nullptr;
  if (isStringType(type)) {
    return std::make_shared<zir::PointerType>(
        std::make_shared<zir::PrimitiveType>(zir::TypeKind::Char));
  }
  if (isPointerType(type))
    return type;
  switch (type->getKind()) {
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float64);
  case zir::TypeKind::Bool:
  case zir::TypeKind::Char:
  case zir::TypeKind::Int8:
  case zir::TypeKind::Int16:
  case zir::TypeKind::UInt8:
  case zir::TypeKind::UInt16:
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
  case zir::TypeKind::Int32:
  case zir::TypeKind::Int64:
  case zir::TypeKind::UInt32:
  case zir::TypeKind::UInt64:
  case zir::TypeKind::Int:
  case zir::TypeKind::UInt:
  case zir::TypeKind::Float64:
    return type;
  default:
    return nullptr;
  }
}
References zir::Bool, zir::Char, zir::Float, zir::Float32, zir::Float64, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, isPointerType(), sema::isStringType(), zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, and zir::UInt8.
Referenced by visit().
getPromotedType()
std::shared_ptr< zir::Type > sema::Binder::getPromotedType (std::shared_ptr< zir::Type > t1, std::shared_ptr< zir::Type > t2) private
Definition at line 1684 of file binder_types.cpp.
{
  if (t1->toString() == t2->toString())
    return t1;
  if (t1->isFloatingPoint() || t2->isFloatingPoint()) {
    if (t1->getKind() == zir::TypeKind::Float64 ||
        t2->getKind() == zir::TypeKind::Float64) {
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float64);
    }
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float);
  }
  // Integer promotion: preserve unsignedness when both operands are unsigned,
  // and choose width-aware integer kinds instead of always forcing Int64.
  if (isUnsignedIntegerType(t1) && isUnsignedIntegerType(t2)) {
    int width = std::max(typeBitWidth(t1), typeBitWidth(t2));
    if (width <= 8)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt8);
    if (width <= 16)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt16);
    if (width <= 32)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt);
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt64);
  }
  // Mixed signed/unsigned or both signed:
  // - preserve unsignedness when the unsigned operand width is >= signed width
  //   (e.g. Int + UInt -> UInt, Int16 + UInt16 -> UInt16, Int + UInt64 ->
  //   UInt64)
  // - otherwise use signed, width-aware promotion.
  if ((isUnsignedIntegerType(t1) && isSignedIntegerType(t2)) ||
      (isSignedIntegerType(t1) && isUnsignedIntegerType(t2))) {
    auto unsignedType = isUnsignedIntegerType(t1) ? t1 : t2;
    auto signedType = isUnsignedIntegerType(t1) ? t2 : t1;
    int unsignedWidth = typeBitWidth(unsignedType);
    int signedWidth = typeBitWidth(signedType);
    if (unsignedWidth >= signedWidth) {
      if (unsignedWidth <= 8)
        return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt8);
      if (unsignedWidth <= 16)
        return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt16);
      if (unsignedWidth <= 32)
        return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt);
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::UInt64);
    }
    int width = std::max(unsignedWidth, signedWidth);
    if (width <= 8)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int8);
    if (width <= 16)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int16);
    if (width <= 32)
      return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int64);
  }
  // Both signed: keep signed result, width-aware.
  int width = std::max(typeBitWidth(t1), typeBitWidth(t2));
  if (width <= 8)
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int8);
  if (width <= 16)
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int16);
  if (width <= 32)
    return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
  return std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int64);
}
References zir::Float, zir::Float64, zir::Int, zir::Int16, zir::Int64, zir::Int8, isSignedIntegerType(), isUnsignedIntegerType(), typeBitWidth(), zir::UInt, zir::UInt16, zir::UInt64, and zir::UInt8.
Referenced by buildBinaryExpression().
initializeBuiltins()
void sema::Binder::initializeBuiltins () private
Definition at line 534 of file binder.cpp.
{
  builtinScope_ = std::make_shared<SymbolTable>();
  auto declareType = [&](const std::string &name, zir::TypeKind kind) {
    builtinScope_->declare(name,
                           std::make_shared<TypeSymbol>(
                               name, std::make_shared<zir::PrimitiveType>(kind),
                               name, "", Visibility::Public));
  };
  declareType("Int", zir::TypeKind::Int);
  declareType("Int8", zir::TypeKind::Int8);
  declareType("Int16", zir::TypeKind::Int16);
  declareType("Int32", zir::TypeKind::Int32);
  declareType("Int64", zir::TypeKind::Int64);
  declareType("UInt", zir::TypeKind::UInt);
  declareType("UInt8", zir::TypeKind::UInt8);
  declareType("UInt16", zir::TypeKind::UInt16);
  declareType("UInt32", zir::TypeKind::UInt32);
  declareType("UInt64", zir::TypeKind::UInt64);
  declareType("Float", zir::TypeKind::Float);
  declareType("Float32", zir::TypeKind::Float32);
  declareType("Float64", zir::TypeKind::Float64);
  declareType("Bool", zir::TypeKind::Bool);
  declareType("Void", zir::TypeKind::Void);
  declareType("Char", zir::TypeKind::Char);
  builtinScope_->declare(
      "String",
      std::make_shared<TypeSymbol>(
          "String", std::make_shared<zir::RecordType>("String", "String"),
          "String", "", Visibility::Public));
}
References zir::Bool, builtinScope_, zir::Char, zir::Float, zir::Float32, zir::Float64, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, Public, zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, zir::UInt8, and zir::Void.
Referenced by bind().
instantiateGenericTypeSymbol()
std::shared_ptr< TypeSymbol > sema::Binder::instantiateGenericTypeSymbol (const std::shared_ptr< TypeSymbol > & baseSymbol, const TypeNode & typeNode) private
Definition at line 433 of file binder_types.cpp.
{
  if (!baseSymbol || baseSymbol->genericParameterNames.empty()) {
    return baseSymbol;
  }
  std::string cacheKey = baseSymbol->linkName + "<";
  std::shared_ptr<zir::RecordType> instantiatedType;
  const RecordDecl *recordDecl = nullptr;
  const StructDeclarationNode *structDecl = nullptr;
  const ClassDecl *classDecl = nullptr;
  if (auto recordDeclIt = recordTypeDeclarationNodes_.find(baseSymbol.get());
      recordDeclIt != recordTypeDeclarationNodes_.end()) {
    recordDecl = recordDeclIt->second;
  } else if (auto structDeclIt =
                 structTypeDeclarationNodes_.find(baseSymbol.get());
             structDeclIt != structTypeDeclarationNodes_.end()) {
    structDecl = structDeclIt->second;
  } else if (auto classDeclIt =
                 classTypeDeclarationNodes_.find(baseSymbol.get());
             classDeclIt != classTypeDeclarationNodes_.end()) {
    classDecl = classDeclIt->second;
  } else {
    error(typeNode.span, "Generic type '" + typeNode.qualifiedName() +
                             "' is not instantiable yet.");
    return nullptr;
  }
  const std::vector<std::unique_ptr<TypeNode>> *declGenericParams =
      recordDecl ? &recordDecl->genericParams_
                 : (structDecl ? &structDecl->genericParams_
                               : &classDecl->genericParams_);
  const std::vector<GenericConstraint> *declGenericConstraints =
      recordDecl ? &recordDecl->genericConstraints_
                 : (structDecl ? &structDecl->genericConstraints_
                               : &classDecl->genericConstraints_);
  if (typeNode.genericArgs.size() > baseSymbol->genericParameterNames.size()) {
    error(typeNode.span, "Generic argument count mismatch for type '" +
                             typeNode.qualifiedName() + "'.");
    return nullptr;
  }
  std::vector<std::shared_ptr<zir::Type>> genericArgs;
  genericArgs.reserve(baseSymbol->genericParameterNames.size());
  std::unordered_map<std::string, std::shared_ptr<zir::Type>> genericBindings;
  for (size_t i = 0; i < baseSymbol->genericParameterNames.size(); ++i) {
    std::shared_ptr<zir::Type> mapped;
    if (i < typeNode.genericArgs.size()) {
      mapped = mapType(*typeNode.genericArgs[i]);
      if (!mapped) {
        error(typeNode.genericArgs[i]->span,
              "Unknown generic type argument in type '" +
                  typeNode.qualifiedName() + "'.");
        return nullptr;
      }
    } else {
      if (!activeGenericBindingsStack_.empty()) {
        const auto &stackBindings = activeGenericBindingsStack_.back();
        auto stackIt = stackBindings.find(baseSymbol->genericParameterNames[i]);
        if (stackIt != stackBindings.end()) {
          mapped = stackIt->second;
        }
      }
      if (!mapped) {
        const auto &declParam = (*declGenericParams)[i];
        if (!declParam || !declParam->defaultType) {
          error(typeNode.span, "Missing generic type arguments for type '" +
                                   typeNode.qualifiedName() + "'.");
          return nullptr;
        }
        activeGenericBindingsStack_.push_back(genericBindings);
        mapped = mapType(*declParam->defaultType);
        activeGenericBindingsStack_.pop_back();
        if (!mapped) {
          error(declParam->defaultType->span,
                "Unknown default generic type argument in type '" +
                    typeNode.qualifiedName() + "'.");
          return nullptr;
        }
      }
    }
    genericArgs.push_back(mapped);
    genericBindings[baseSymbol->genericParameterNames[i]] = mapped;
  }
  std::string constraintFailure;
  if (declGenericConstraints &&
      !validateGenericConstraints(*declGenericConstraints, genericBindings,
                                  &constraintFailure)) {
    error(typeNode.span, "Generic constraints not satisfied for type '" +
                             typeNode.qualifiedName() +
                             "': " + constraintFailure);
    return nullptr;
  }
  for (size_t i = 0; i < genericArgs.size(); ++i) {
    if (i != 0) {
      cacheKey += ",";
    }
    cacheKey += genericArgs[i] ? genericArgs[i]->toString() : "<?>";
  }
  cacheKey += ">";
  auto cachedIt = genericTypeInstantiations_.find(cacheKey);
  if (cachedIt != genericTypeInstantiations_.end()) {
    return cachedIt->second;
  }
  auto moduleIdIt = typeDeclarationModuleIds_.find(baseSymbol.get());
  if (moduleIdIt == typeDeclarationModuleIds_.end()) {
    error(typeNode.span,
          "Internal error: missing module information for generic type '" +
              baseSymbol->name + "'.");
    return nullptr;
  }
  auto moduleIt = modules_.find(moduleIdIt->second);
  if (moduleIt == modules_.end() || !moduleIt->second.info) {
    error(typeNode.span,
          "Internal error: missing declaration module for generic type '" +
              baseSymbol->name + "'.");
    return nullptr;
  }
  auto baseRecordType =
      std::static_pointer_cast<zir::RecordType>(baseSymbol->type);
  auto displayName =
      renderGenericTypeName(baseRecordType->getName(), genericArgs);
  auto codegenName =
      renderGenericCodegenName(baseRecordType->getCodegenName(), genericArgs);
  if (classDecl) {
    instantiatedType =
        std::make_shared<zir::ClassType>(displayName, codegenName);
  } else {
    instantiatedType =
        std::make_shared<zir::RecordType>(displayName, codegenName);
  }
  instantiatedType->setGenericInstance(
      baseRecordType->getName(), baseRecordType->getCodegenName(), genericArgs);
  instantiatedType->hasReprC = baseRecordType->hasReprC;
  instantiatedType->isPacked = baseRecordType->isPacked;
  auto instantiatedSymbol = std::make_shared<TypeSymbol>(
      baseSymbol->name, instantiatedType, codegenName, baseSymbol->moduleName,
      baseSymbol->visibility, baseSymbol->isUnsafe, classDecl != nullptr);
  instantiatedSymbol->isGenericInstantiation = true;
  instantiatedSymbol->hasReprC = baseSymbol->hasReprC;
  instantiatedSymbol->isPacked = baseSymbol->isPacked;
  instantiatedSymbol->genericArguments = {genericBindings.begin(),
                                          genericBindings.end()};
  genericTypeInstantiations_[cacheKey] = instantiatedSymbol;
  if (classDecl) {
    auto instantiatedClassType =
        std::static_pointer_cast<zir::ClassType>(instantiatedType);
    ClassInfo classInfo;
    classInfo.typeSymbol = instantiatedSymbol;
    classInfo.classType = instantiatedClassType;
    classInfo.ownerQualifiedName = instantiatedClassType->getName();
    classInfos_[instantiatedClassType->getName()] = classInfo;
  }
  int oldUnsafeTypeContextDepth = unsafeTypeContextDepth_;
  int oldExternTypeContextDepth = externTypeContextDepth_;
  auto oldScope = currentScope_;
  auto oldModuleId = currentModuleId_;
  if (structDecl && structDecl->isUnsafe_) {
    ++unsafeTypeContextDepth_;
  }
  if (structDecl) {
    ++externTypeContextDepth_;
  }
  currentScope_ = moduleIt->second.scope;
  currentModuleId_ = moduleIt->second.info->moduleId;
  activeGenericBindingsStack_.push_back(genericBindings);
  if (classDecl && classDecl->baseType_) {
    bool hasOwnCtor = false;
    bool hasOwnDtor = false;
    for (const auto &methodDecl : classDecl->methods_) {
      hasOwnCtor = hasOwnCtor || methodDecl->name_ == "init";
      hasOwnDtor = hasOwnDtor || methodDecl->name_ == "deinit";
    }
    auto baseType = mapType(*classDecl->baseType_);
    if (baseType && baseType->getKind() == zir::TypeKind::Class) {
      auto instantiatedClassType =
          std::static_pointer_cast<zir::ClassType>(instantiatedType);
      auto baseClass = std::static_pointer_cast<zir::ClassType>(baseType);
      instantiatedClassType->setBase(baseClass);
      auto &classInfo = classInfos_[instantiatedClassType->getName()];
      auto baseIt = classInfos_.find(baseClass->getName());
      if (baseIt != classInfos_.end()) {
        if (!hasOwnCtor) {
          classInfo.constructor = baseIt->second.constructor;
        }
        if (!hasOwnDtor) {
          classInfo.destructor = baseIt->second.destructor;
        }
        classInfo.fields = baseIt->second.fields;
        classInfo.methods.insert(baseIt->second.methods.begin(),
                                 baseIt->second.methods.end());
        classInfo.nextVirtualSlot = baseIt->second.nextVirtualSlot;
      }
      for (const auto &field : baseClass->getFields()) {
        instantiatedClassType->addField(field.name, field.type,
                                        field.visibility);
      }
    } else if (baseType) {
      error(classDecl->baseType_->span,
            "Base type of class '" + classDecl->name_ + "' must be a class.");
    }
  }
  const auto &fields =
      recordDecl ? recordDecl->fields_
                 : (structDecl ? structDecl->fields_ : classDecl->fields_);
  for (const auto &field : fields) {
    auto fieldType = mapType(*field->type);
    if (!fieldType) {
      error(field->span, "Unknown type: " + field->type->qualifiedName());
      fieldType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    instantiatedType->addField(field->name, fieldType,
                               static_cast<int>(field->visibility_));
    if (classDecl) {
      auto instantiatedClassType =
          std::static_pointer_cast<zir::ClassType>(instantiatedType);
      auto &classInfo = classInfos_[instantiatedClassType->getName()];
      classInfo.fields[field->name] = std::make_shared<VariableSymbol>(
          field->name, fieldType, false, false, field->name,
          moduleIt->second.info->moduleName, field->visibility_);
    }
  }
  activeGenericBindingsStack_.pop_back();
  unsafeTypeContextDepth_ = oldUnsafeTypeContextDepth;
  externTypeContextDepth_ = oldExternTypeContextDepth;
  currentScope_ = oldScope;
  currentModuleId_ = oldModuleId;
  if (classDecl) {
    auto instantiatedClassType =
        std::static_pointer_cast<zir::ClassType>(instantiatedType);
    auto &classInfo = classInfos_[instantiatedClassType->getName()];
    auto oldScope = currentScope_;
    auto oldModuleId = currentModuleId_;
    currentScope_ = moduleIt->second.scope;
    currentModuleId_ = moduleIt->second.info->moduleId;
    for (const auto &methodDecl : classDecl->methods_) {
      if (methodDecl->isUnsafe_) {
        ++unsafeTypeContextDepth_;
      }
      std::unordered_map<std::string, std::shared_ptr<zir::Type>>
          methodGenericBindings;
      for (const auto &genericParam : methodDecl->genericParams_) {
        if (genericParam) {
          auto placeholder = std::make_shared<zir::RecordType>(
              genericParam->typeName, genericParam->typeName);
          methodGenericBindings[genericParam->typeName] = placeholder;
        }
      }
      std::vector<std::shared_ptr<VariableSymbol>> params;
      if (!methodDecl->isStatic_) {
        params.push_back(std::make_shared<VariableSymbol>(
            "self", instantiatedClassType, false, false, "self",
            moduleIt->second.info->moduleName, Visibility::Private));
      }
      activeGenericBindingsStack_.push_back(genericBindings);
      if (!methodGenericBindings.empty()) {
        activeGenericBindingsStack_.push_back(methodGenericBindings);
      }
      for (size_t i = 0; i < methodDecl->params_.size(); ++i) {
        const auto &p = methodDecl->params_[i];
        auto mappedType = mapType(*p->type);
        if (!mappedType) {
          error(p->span, "Unknown type: " + p->type->qualifiedName());
          mappedType =
              std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        params.push_back(std::make_shared<VariableSymbol>(
            p->name, mappedType, false, p->isRef, p->name,
            moduleIt->second.info->moduleName, Visibility::Private));
      }
      std::shared_ptr<zir::Type> retType;
      bool isCtor = methodDecl->name_ == "init";
      bool isDtor = methodDecl->name_ == "deinit";
      if (isDtor && (!methodDecl->params_.empty() || methodDecl->returnType_)) {
        error(methodDecl->span,
              "Destructor 'deinit' cannot have parameters or a return type.");
      }
      if (isCtor || isDtor) {
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      } else if (methodDecl->returnType_) {
        retType = mapType(*methodDecl->returnType_);
      } else {
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      if (!methodGenericBindings.empty()) {
        activeGenericBindingsStack_.pop_back();
      }
      activeGenericBindingsStack_.pop_back();
      if (!retType) {
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      if (methodDecl->isUnsafe_) {
        --unsafeTypeContextDepth_;
      }
      auto methodSymbol = std::make_shared<FunctionSymbol>(
          methodDecl->name_, std::move(params), std::move(retType), "",
          moduleIt->second.info->moduleName, methodDecl->visibility_,
          methodDecl->isUnsafe_);
      for (const auto &genericParam : methodDecl->genericParams_) {
        if (genericParam) {
          methodSymbol->genericParameterNames.push_back(genericParam->typeName);
        }
      }
      methodSymbol->isMethod = !methodDecl->isStatic_;
      methodSymbol->isStatic = methodDecl->isStatic_;
      methodSymbol->isConstructor = isCtor;
      methodSymbol->isDestructor = isDtor;
      methodSymbol->ownerTypeName = instantiatedClassType->getName();
      if (methodSymbol->isMethod && !methodSymbol->isStatic &&
          !methodSymbol->isConstructor && !methodSymbol->isDestructor) {
        methodSymbol->vtableSlot =
            findOverriddenVtableSlot(classInfo, *methodSymbol);
        if (methodSymbol->vtableSlot < 0) {
          methodSymbol->vtableSlot = classInfo.nextVirtualSlot++;
        }
      }
      methodSymbol->linkName = mangleName(
          moduleIt->second.info->linkPath.empty()
              ? moduleIt->second.info->moduleId
              : moduleIt->second.info->linkPath,
          instantiatedClassType->getCodegenName() + "$" + methodDecl->name_ +
              "$" + sanitizeTypeName(functionSignatureKey(*methodSymbol)));
      functionDeclarationNodes_[methodSymbol.get()] = methodDecl.get();
      functionDeclarationModuleIds_[methodSymbol.get()] =
          moduleIt->second.info->moduleId;
      functionGenericParamNames_[methodSymbol.get()] =
          methodSymbol->genericParameterNames;
      addClassMethodOverload(classInfo, methodSymbol);
      if (isCtor) {
        if (!classInfo.constructor) {
          classInfo.constructor = methodSymbol;
        }
      } else if (isDtor) {
        classInfo.destructor = methodSymbol;
      }
      if (!methodSymbol->genericParameterNames.empty() &&
          !methodSymbol->isGenericInstantiation) {
        continue;
      }
      auto oldScope = currentScope_;
      auto oldFunction = currentFunction_;
      auto oldModuleId = currentModuleId_;
      auto oldClassStack = currentClassStack_;
      int oldUnsafeDepth = unsafeDepth_;
      currentModuleId_ = moduleIt->second.info->moduleId;
      currentScope_ = moduleIt->second.scope;
      currentFunction_ = methodSymbol;
      currentClassStack_.push_back(instantiatedClassType->getName());
      if (methodSymbol->isUnsafe) {
        ++unsafeDepth_;
      }
      pushScope();
      for (const auto &param : methodSymbol->parameters) {
        if (!currentScope_->declare(param->name, param)) {
          error(methodDecl->span,
                "Parameter '" + param->name + "' already declared.");
        }
      }
      activeGenericBindingsStack_.push_back(genericBindings);
      auto boundBody = bindBody(methodDecl->body_.get(), false);
      activeGenericBindingsStack_.pop_back();
      popScope();
      currentScope_ = oldScope;
      currentFunction_ = oldFunction;
      currentModuleId_ = oldModuleId;
      currentClassStack_ = oldClassStack;
      unsafeDepth_ = oldUnsafeDepth;
      bool hasReturn = blockAlwaysReturns(boundBody.get());
      if (!hasReturn &&
          methodSymbol->returnType->getKind() != zir::TypeKind::Void) {
        auto kind = methodSymbol->returnType->getKind();
        if (methodSymbol->returnType->isInteger() ||
            kind == zir::TypeKind::Float || kind == zir::TypeKind::Bool) {
          std::string litVal = "0";
          if (kind == zir::TypeKind::Float)
            litVal = "0.0";
          else if (kind == zir::TypeKind::Bool)
            litVal = "false";
          auto lit =
              std::make_unique<BoundLiteral>(litVal, methodSymbol->returnType);
          boundBody->statements.push_back(
              std::make_unique<BoundReturnStatement>(std::move(lit)));
        }
        _diag.report(methodDecl->span, zap::DiagnosticLevel::Warning,
                     "Function '" + methodDecl->name_ +
                         "' has non-void return type but no return on some "
                         "paths.");
      }
      boundRoot_->functions.push_back(
          std::make_unique<BoundFunctionDeclaration>(methodSymbol,
                                                     std::move(boundBody)));
    }
    currentScope_ = oldScope;
    currentModuleId_ = oldModuleId;
    auto boundRecord = std::make_unique<BoundRecordDeclaration>();
    boundRecord->type = instantiatedClassType;
    boundRoot_->records.push_back(std::move(boundRecord));
  }
  return instantiatedSymbol;
}
References _diag, activeGenericBindingsStack_, addClassMethodOverload(), ClassDecl::baseType_, bindBody(), sema::blockAlwaysReturns(), zir::Bool, boundRoot_, zir::Class, classInfos_, sema::Binder::ClassInfo::classType, classTypeDeclarationNodes_, currentClassStack_, currentFunction_, currentModuleId_, currentScope_, error(), externTypeContextDepth_, ClassDecl::fields_, RecordDecl::fields_, StructDeclarationNode::fields_, findOverriddenVtableSlot(), zir::Float, functionDeclarationModuleIds_, functionDeclarationNodes_, functionGenericParamNames_, functionSignatureKey(), TypeNode::genericArgs, ClassDecl::genericConstraints_, RecordDecl::genericConstraints_, StructDeclarationNode::genericConstraints_, ClassDecl::genericParams_, RecordDecl::genericParams_, StructDeclarationNode::genericParams_, genericTypeInstantiations_, StructDeclarationNode::isUnsafe_, mangleName(), mapType(), ClassDecl::methods_, modules_, ClassDecl::name_, sema::Binder::ClassInfo::ownerQualifiedName, popScope(), Private, pushScope(), TypeNode::qualifiedName(), recordTypeDeclarationNodes_, sema::renderGenericCodegenName(), sema::renderGenericTypeName(), sema::sanitizeTypeName(), Node::span, structTypeDeclarationNodes_, typeDeclarationModuleIds_, sema::Binder::ClassInfo::typeSymbol, unsafeDepth_, unsafeTypeContextDepth_, validateGenericConstraints(), zir::Void, and zap::Warning.
Referenced by mapType().
isGenericTypeParameterName()
bool sema::Binder::isGenericTypeParameterName (std::string_view name) const private
Definition at line 250 of file binder_types.cpp.
{
  if (activeGenericBindingsStack_.empty()) {
    return false;
  }
  const auto &bindings = activeGenericBindingsStack_.back();
  return bindings.find(std::string(name)) != bindings.end();
}
References activeGenericBindingsStack_.
isNullType()
bool sema::Binder::isNullType (std::shared_ptr< zir::Type > type) const private
Definition at line 1602 of file binder_types.cpp.
{
  return type && type->getKind() == zir::TypeKind::NullPtr;
}
References zir::NullPtr.
Referenced by buildBinaryExpression(), canConvert(), conversionCost(), describeConversion(), visit(), and wrapInCast().
isNumeric()
bool sema::Binder::isNumeric (std::shared_ptr< zir::Type > type) const private
Definition at line 1594 of file binder_types.cpp.
{
  return type->isInteger() || type->isFloatingPoint();
}
Referenced by buildBinaryExpression(), canConvert(), visit(), and visit().
isPointerType()
bool sema::Binder::isPointerType (std::shared_ptr< zir::Type > type) const private
Definition at line 1598 of file binder_types.cpp.
{
  return type && type->getKind() == zir::TypeKind::Pointer;
}
References zir::Pointer.
Referenced by buildBinaryExpression(), canConvert(), conversionCost(), describeConversion(), getCVariadicArgumentType(), visit(), visit(), and wrapInCast().
isSignedIntegerType()
bool sema::Binder::isSignedIntegerType (std::shared_ptr< zir::Type > type) const private
Definition at line 1105 of file binder_types.cpp.
{
  if (!type) {
    return false;
  }
  switch (type->getKind()) {
  case zir::TypeKind::Int8:
  case zir::TypeKind::Int16:
  case zir::TypeKind::Int32:
  case zir::TypeKind::Int64:
  case zir::TypeKind::Int:
    return true;
  default:
    return false;
  }
}
References zir::Int, zir::Int16, zir::Int32, zir::Int64, and zir::Int8.
Referenced by conversionCost(), describeConversion(), and getPromotedType().
isSupportedBuiltInAttribute()
bool sema::Binder::isSupportedBuiltInAttribute (const std::string & name) const private
Definition at line 1243 of file binder_types.cpp.
{
  static const std::unordered_set<std::string> builtIns = {
      "error", "repr", "packed", "extern", "noMangle"};
  return builtIns.find(name) != builtIns.end();
}
Referenced by warnUnknownAttributes().
isUnsafeActive()
bool sema::Binder::isUnsafeActive () const private
Definition at line 1606 of file binder_types.cpp.
{
  return unsafeDepth_ > 0 || unsafeTypeContextDepth_ > 0;
}
References unsafeDepth_, and unsafeTypeContextDepth_.
Referenced by requireUnsafeContext(), and visit().
isUnsignedIntegerType()
bool sema::Binder::isUnsignedIntegerType (std::shared_ptr< zir::Type > type) const private
Definition at line 1122 of file binder_types.cpp.
{
  return type && type->isInteger() && type->isUnsigned();
}
Referenced by conversionCost(), describeConversion(), and getPromotedType().
lookupVisibleSymbol()
std::shared_ptr< Symbol > sema::Binder::lookupVisibleSymbol (const std::string & name) const private
Definition at line 840 of file binder.cpp.
{
  return currentScope_ ? currentScope_->lookup(name) : nullptr;
}
References currentScope_.
Referenced by resolveQualifiedSymbol().
makeSyntheticLoopName()
std::string sema::Binder::makeSyntheticLoopName (std::string_view prefix) private
Definition at line 915 of file binder.cpp.
{
  while (true) {
    std::string candidate = "__for_" + std::string(prefix) + "_" +
                            std::to_string(syntheticLoopCounter_++);
    if (!currentScope_ || !currentScope_->lookupLocal(candidate)) {
      return candidate;
    }
  }
}
References currentScope_, and syntheticLoopCounter_.
Referenced by visit().
mangleFunctionName()
std::string sema::Binder::mangleFunctionName (const std::string & modulePath, const FunctionSymbol & function) const private
Definition at line 667 of file binder.cpp.
{
  return mangleName(modulePath,
                    function.name + "$" +
                        sanitizeTypeName(functionSignatureKey(function)));
}
References functionSignatureKey(), mangleName(), sema::Symbol::name, and sema::sanitizeTypeName().
Referenced by predeclareModuleValues().
mangleName()
std::string sema::Binder::mangleName (const std::string & modulePath, const std::string & name) const private
Definition at line 568 of file binder.cpp.
{
  std::string mangled = "zap$";
  auto appendEscaped = [&](char c) {
    unsigned char uc = static_cast<unsigned char>(c);
    if (std::isalnum(uc)) {
      mangled += c;
      return;
    }
    char buf[8];
    std::snprintf(buf, sizeof(buf), "_%02X", static_cast<unsigned int>(uc));
    mangled += buf;
  };
  for (char c : modulePath) {
    appendEscaped(c);
  }
  if (!mangled.empty() && mangled.back() != '$') {
    mangled += '$';
  }
  for (char c : name) {
    appendEscaped(c);
  }
  return mangled;
}
Referenced by instantiateGenericTypeSymbol(), mangleFunctionName(), predeclareModuleAliases(), predeclareModuleTypes(), visit(), and visit().
mapType()
std::shared_ptr< zir::Type > sema::Binder::mapType (const TypeNode & typeNode) private
Definition at line 1420 of file binder_types.cpp.
{
  // Cache simple types when not in a generic instantiation context.
  // Skip cache for array types with size expressions (they evaluate AST nodes)
  // and for failable types (they may emit errors on first call).
  bool canCache = activeGenericBindingsStack_.empty() && !typeNode.isVarArgs &&
                  !typeNode.isFailable &&
                  !(typeNode.isArray && typeNode.arraySize);
  if (canCache) {
    auto it = mapTypeCache_.find(&typeNode);
    if (it != mapTypeCache_.end())
      return it->second;
  }
  auto doMap = [&]() -> std::shared_ptr<zir::Type> {
    if (typeNode.isVarArgs) {
      if (!typeNode.baseType)
        return nullptr;
      return mapType(*typeNode.baseType);
    }
    if (typeNode.isFailable) {
      if (!typeNode.baseType || !typeNode.errorType) {
        error(typeNode.span, "Invalid failable type declaration.");
        return nullptr;
      }
      auto valueType = mapType(*typeNode.baseType);
      auto errorType = mapType(*typeNode.errorType);
      if (!valueType || !errorType) {
        return nullptr;
      }
      if (!typeNode.errorType->qualifiers.empty() ||
          !typeNode.errorType->typeName.empty()) {
        std::vector<std::string> errParts = typeNode.errorType->qualifiers;
        errParts.push_back(typeNode.errorType->typeName);
        auto errSymbol = resolveQualifiedSymbol(
            errParts, typeNode.errorType->span, SymbolKind::Type);
        if (errSymbol && errSymbol->getKind() == SymbolKind::Type) {
          auto errTypeSymbol = std::static_pointer_cast<TypeSymbol>(errSymbol);
          if (!errTypeSymbol->isErrorType) {
            error(typeNode.errorType->span,
                  "Type '" + typeNode.errorType->qualifiedName() +
                      "' used as failable error type must be annotated with "
                      "@error.");
          }
        }
      }
      return makeFailableType(valueType, errorType);
    }
    if (!activeGenericBindingsStack_.empty() && typeNode.qualifiers.empty() &&
        typeNode.genericArgs.empty()) {
      const auto &bindings = activeGenericBindingsStack_.back();
      auto it = bindings.find(typeNode.typeName);
      if (it != bindings.end()) {
        auto mapped = it->second;
        if (typeNode.isWeak) {
          if (!mapped || mapped->getKind() != zir::TypeKind::Class) {
            error(typeNode.span, "'weak' can only be used with class types.");
            return nullptr;
          }
          auto weakType = std::make_shared<zir::ClassType>(
              *std::static_pointer_cast<zir::ClassType>(mapped));
          weakType->setWeak(true);
          return weakType;
        }
        return mapped;
      }
    }
    if (typeNode.isArray) {
      if (!typeNode.baseType)
        return nullptr;
      auto base = mapType(*typeNode.baseType);
      if (!typeNode.arraySize) {
        return makeVariadicViewType(base);
      }
      size_t size = 0;
      typeNode.arraySize->accept(*this);
      if (!expressionStack_.empty()) {
        auto boundSize = std::move(expressionStack_.top());
        expressionStack_.pop();
        auto evaluated = evaluateConstantInt(boundSize.get());
        if (evaluated) {
          size = static_cast<size_t>(*evaluated);
        } else {
          error(typeNode.span,
                "Array size must be a constant integer expression.");
        }
      }
      return std::make_shared<zir::ArrayType>(std::move(base), size);
    }
    if (typeNode.isPointer) {
      if (!typeNode.baseType)
        return nullptr;
      auto base = mapType(*typeNode.baseType);
      return std::make_shared<zir::PointerType>(std::move(base));
    }
    if (typeNode.isFunPtr) {
      std::vector<std::shared_ptr<zir::Type>> params;
      for (const auto &p : typeNode.funPtrParams) {
        auto mapped = mapType(*p);
        if (!mapped)
          return nullptr;
        params.push_back(std::move(mapped));
      }
      auto ret =
          typeNode.funPtrReturn
              ? mapType(*typeNode.funPtrReturn)
              : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      if (!ret)
        return nullptr;
      return std::make_shared<zir::FunctionPointerType>(std::move(params),
                                                        std::move(ret));
    }
    std::vector<std::string> parts = typeNode.qualifiers;
    parts.push_back(typeNode.typeName);
    auto symbol =
        resolveQualifiedSymbol(parts, typeNode.span, SymbolKind::Type);
    if (symbol && symbol->getKind() == SymbolKind::Type) {
      auto typeSymbol = std::static_pointer_cast<TypeSymbol>(symbol);
      if (!typeSymbol->genericParameterNames.empty()) {
        typeSymbol = instantiateGenericTypeSymbol(typeSymbol, typeNode);
        if (!typeSymbol) {
          return nullptr;
        }
      } else if (!typeNode.genericArgs.empty()) {
        error(typeNode.span,
              "Type '" + typeNode.qualifiedName() + "' is not generic.");
        return nullptr;
      }
      if (typeSymbol->isUnsafe) {
        requireUnsafeContext(typeNode.span, "unsafe struct types");
      }
      if (typeNode.isWeak) {
        if (!typeSymbol->isClass ||
            typeSymbol->type->getKind() != zir::TypeKind::Class) {
          error(typeNode.span, "'weak' can only be used with class types.");
          return nullptr;
        }
        auto weakType = std::make_shared<zir::ClassType>(
            *std::static_pointer_cast<zir::ClassType>(typeSymbol->type));
        weakType->setWeak(true);
        return weakType;
      }
      auto resolvedType = typeSymbol->type;
      if (typeNode.errorType && !typeSymbol->isErrorType) {
        error(typeNode.span,
              "Type '" + typeNode.qualifiedName() +
                  "' used as failable error type must be annotated with "
                  "@error.");
      }
      return resolvedType;
    }
    return nullptr;
  }; // end doMap lambda
  auto result = doMap();
  if (canCache)
    mapTypeCache_[&typeNode] = result;
  return result;
}
References activeGenericBindingsStack_, TypeNode::arraySize, TypeNode::baseType, zir::Class, error(), TypeNode::errorType, evaluateConstantInt(), expressionStack_, TypeNode::funPtrParams, TypeNode::funPtrReturn, TypeNode::genericArgs, instantiateGenericTypeSymbol(), TypeNode::isArray, TypeNode::isFailable, TypeNode::isFunPtr, TypeNode::isPointer, TypeNode::isVarArgs, TypeNode::isWeak, sema::makeFailableType(), sema::makeVariadicViewType(), mapType(), mapTypeCache_, TypeNode::qualifiedName(), TypeNode::qualifiers, requireUnsafeContext(), resolveQualifiedSymbol(), Node::span, sema::Type, TypeNode::typeName, and zir::Void.
Referenced by buildGenericBindings(), instantiateGenericTypeSymbol(), mapType(), mapTypeWithGenericBindings(), predeclareModuleAliases(), predeclareModuleTypes(), predeclareModuleValues(), validateGenericConstraints(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
mapTypeWithGenericBindings()
std::shared_ptr< zir::Type > sema::Binder::mapTypeWithGenericBindings (const TypeNode & typeNode, const std::unordered_map< std::string, std::shared_ptr< zir::Type > > & genericBindings) private
Definition at line 871 of file binder_types.cpp.
{
  auto mapped = mapType(typeNode);
  return substituteGenericType(std::move(mapped), genericBindings);
}
References mapType(), and substituteGenericType().
orderedGenericBindings()
std::vector< std::pair< std::string, std::shared_ptr< zir::Type > > > sema::Binder::orderedGenericBindings (const std::unordered_map< std::string, std::shared_ptr< zir::Type > > & genericBindings) const private
Definition at line 419 of file binder_types.cpp.
{
  std::vector<std::pair<std::string, std::shared_ptr<zir::Type>>> ordered;
  ordered.reserve(genericBindings.size());
  for (const auto &[name, type] : genericBindings) {
    ordered.emplace_back(name, type);
  }
  std::sort(
      ordered.begin(), ordered.end(),
      [](const auto &lhs, const auto &rhs) { return lhs.first < rhs.first; });
  return ordered;
}
Referenced by visit().
popScope()
void sema::Binder::popScope () private
Definition at line 929 of file binder.cpp.
                      {
  if (currentScope_) {
    currentScope_ = currentScope_->getParent();
  }
}
References currentScope_.
Referenced by bindBody(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), visit(), and visit().
predeclareModuleAliases()
void sema::Binder::predeclareModuleAliases (ModuleState & module) private
Definition at line 261 of file binder_decls.cpp.
{
  currentModuleId_ = module.info->moduleId;
  currentScope_ = module.scope;
  for (const auto &child : module.info->root->children) {
    if (auto aliasDecl = dynamic_cast<TypeAliasDecl *>(child.get())) {
      auto type = mapType(*aliasDecl->type_);
      if (!type) {
        error(aliasDecl->span,
              "Unknown type: " + aliasDecl->type_->qualifiedName());
        continue;
      }
      auto symbol = std::make_shared<TypeSymbol>(
          aliasDecl->name_, type,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     aliasDecl->name_),
          module.info->moduleName, aliasDecl->visibility_, false);
      if (!module.scope->declare(aliasDecl->name_, symbol)) {
        error(aliasDecl->span,
              "Type '" + aliasDecl->name_ + "' already declared.");
      }
      module.symbol->members[aliasDecl->name_] = symbol;
      if (aliasDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[aliasDecl->name_] = symbol;
      }
    }
  }
}
References currentModuleId_, currentScope_, error(), sema::Binder::ModuleState::info, sema::ModuleInfo::linkPath, mangleName(), mapType(), sema::ModuleInfo::moduleId, sema::ModuleInfo::moduleName, Public, sema::ModuleInfo::root, and sema::Binder::ModuleState::scope.
Referenced by bind().
predeclareModuleTypes()
void sema::Binder::predeclareModuleTypes (ModuleState & module) private
Definition at line 18 of file binder_decls.cpp.
{
  currentModuleId_ = module.info->moduleId;
  currentScope_ = module.scope;
  std::vector<std::pair<EnumDecl *, std::shared_ptr<TypeSymbol>>>
      pendingPayloadEnums;
  for (const auto &child : module.info->root->children) {
    if (auto recordDecl = dynamic_cast<RecordDecl *>(child.get())) {
      auto type = std::make_shared<zir::RecordType>(
          displayTypeName(module.info->moduleName, recordDecl->name_),
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     recordDecl->name_));
      auto symbol = std::make_shared<TypeSymbol>(
          recordDecl->name_, type,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     recordDecl->name_),
          module.info->moduleName, recordDecl->visibility_, false);
      validateAndApplyTypeAttributes(*recordDecl, symbol, true);
      if (symbol->hasReprC) {
        auto reprType = std::make_shared<zir::RecordType>(recordDecl->name_,
                                                          recordDecl->name_);
        reprType->hasReprC = true;
        reprType->isPacked = symbol->isPacked;
        symbol->type = reprType;
      }
      for (const auto &genericParam : recordDecl->genericParams_) {
        if (genericParam) {
          symbol->genericParameterNames.push_back(genericParam->typeName);
        }
      }
      recordTypeDeclarationNodes_[symbol.get()] = recordDecl;
      typeDeclarationModuleIds_[symbol.get()] = module.info->moduleId;
      if (!module.scope->declare(recordDecl->name_, symbol)) {
        error(recordDecl->span,
              "Type '" + recordDecl->name_ + "' already declared.");
      }
      module.symbol->members[recordDecl->name_] = symbol;
      if (recordDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[recordDecl->name_] = symbol;
      }
    } else if (auto classDecl = dynamic_cast<ClassDecl *>(child.get())) {
      auto type = std::make_shared<zir::ClassType>(
          displayTypeName(module.info->moduleName, classDecl->name_),
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     classDecl->name_));
      auto symbol = std::make_shared<TypeSymbol>(
          classDecl->name_, type,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     classDecl->name_),
          module.info->moduleName, classDecl->visibility_, false, true);
      for (const auto &genericParam : classDecl->genericParams_) {
        if (genericParam) {
          symbol->genericParameterNames.push_back(genericParam->typeName);
        }
      }
      classTypeDeclarationNodes_[symbol.get()] = classDecl;
      typeDeclarationModuleIds_[symbol.get()] = module.info->moduleId;
      validateAndApplyTypeAttributes(*classDecl, symbol, true);
      if (!module.scope->declare(classDecl->name_, symbol)) {
        error(classDecl->span,
              "Type '" + classDecl->name_ + "' already declared.");
      }
      module.symbol->members[classDecl->name_] = symbol;
      if (classDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[classDecl->name_] = symbol;
      }
      if (symbol->genericParameterNames.empty()) {
        ClassInfo info;
        info.typeSymbol = symbol;
        info.classType = type;
        info.ownerQualifiedName = type->getName();
        classInfos_[type->getName()] = info;
      }
    } else if (auto structDecl =
                   dynamic_cast<StructDeclarationNode *>(child.get())) {
      auto type = std::make_shared<zir::RecordType>(
          displayTypeName(module.info->moduleName, structDecl->name_),
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     structDecl->name_));
      auto symbol = std::make_shared<TypeSymbol>(
          structDecl->name_, type,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     structDecl->name_),
          module.info->moduleName, structDecl->visibility_,
          structDecl->isUnsafe_);
      for (const auto &genericParam : structDecl->genericParams_) {
        if (genericParam) {
          symbol->genericParameterNames.push_back(genericParam->typeName);
        }
      }
      structTypeDeclarationNodes_[symbol.get()] = structDecl;
      typeDeclarationModuleIds_[symbol.get()] = module.info->moduleId;
      validateAndApplyTypeAttributes(*structDecl, symbol, true);
      if (symbol->hasReprC) {
        auto reprType = std::make_shared<zir::RecordType>(structDecl->name_,
                                                          structDecl->name_);
        reprType->hasReprC = true;
        reprType->isPacked = symbol->isPacked;
        symbol->type = reprType;
      }
      if (!module.scope->declare(structDecl->name_, symbol)) {
        error(structDecl->span,
              "Type '" + structDecl->name_ + "' already declared.");
      }
      module.symbol->members[structDecl->name_] = symbol;
      if (structDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[structDecl->name_] = symbol;
      }
    } else if (auto enumDecl = dynamic_cast<EnumDecl *>(child.get())) {
      bool hasPayloadVariants =
          std::any_of(enumDecl->entries_.begin(), enumDecl->entries_.end(),
                      [](const EnumDecl::Entry &entry) {
                        return entry.payloadType_ != nullptr;
                      });
      if (hasPayloadVariants) {
        auto type = std::make_shared<zir::TaggedUnionType>(
            displayTypeName(module.info->moduleName, enumDecl->name_),
            std::vector<zir::TaggedUnionType::Variant>{},
            mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                     : module.info->linkPath,
                       enumDecl->name_));
        auto symbol = std::make_shared<TypeSymbol>(
            enumDecl->name_, type,
            mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                     : module.info->linkPath,
                       enumDecl->name_),
            module.info->moduleName, enumDecl->visibility_, false);
        validateAndApplyTypeAttributes(*enumDecl, symbol, true);
        if (symbol->hasReprC) {
          error(enumDecl->span,
                "attribute 'repr' cannot be applied to enum payloads");
        }
        if (!module.scope->declare(enumDecl->name_, symbol)) {
          error(enumDecl->span,
                "Type '" + enumDecl->name_ + "' already declared.");
        }
        module.symbol->members[enumDecl->name_] = symbol;
        if (enumDecl->visibility_ == Visibility::Public) {
          module.symbol->exports[enumDecl->name_] = symbol;
        }
        pendingPayloadEnums.push_back({enumDecl, symbol});
        continue;
      }
      std::vector<zir::EnumType::Variant> variants;
      variants.reserve(enumDecl->entries_.size());
      int64_t nextImplicitValue = 0;
      bool overflowed = false;
      for (const auto &entry : enumDecl->entries_) {
        int64_t resolvedValue = 0;
        if (entry.hasExplicitValue_) {
          resolvedValue = entry.value_;
          if (resolvedValue == std::numeric_limits<int64_t>::max()) {
            overflowed = true;
          } else {
            nextImplicitValue = resolvedValue + 1;
          }
        } else {
          if (overflowed) {
            error(enumDecl->span, "Enum '" + enumDecl->name_ +
                                      "' has implicit value after maximum "
                                      "explicit discriminant.");
            break;
          }
          resolvedValue = nextImplicitValue;
          if (nextImplicitValue == std::numeric_limits<int64_t>::max()) {
            overflowed = true;
          } else {
            ++nextImplicitValue;
          }
        }
        variants.push_back({entry.name_, resolvedValue});
      }
      auto type = std::make_shared<zir::EnumType>(
          displayTypeName(module.info->moduleName, enumDecl->name_),
          std::move(variants),
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     enumDecl->name_));
      auto symbol = std::make_shared<TypeSymbol>(
          enumDecl->name_, type,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     enumDecl->name_),
          module.info->moduleName, enumDecl->visibility_, false);
      validateAndApplyTypeAttributes(*enumDecl, symbol, true);
      if (symbol->hasReprC) {
        std::static_pointer_cast<zir::EnumType>(symbol->type)->hasReprC = true;
      }
      if (!module.scope->declare(enumDecl->name_, symbol)) {
        error(enumDecl->span,
              "Type '" + enumDecl->name_ + "' already declared.");
      }
      module.symbol->members[enumDecl->name_] = symbol;
      if (enumDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[enumDecl->name_] = symbol;
      }
    }
  }
  for (auto &[decl, symbol] : pendingPayloadEnums) {
    std::vector<zir::TaggedUnionType::Variant> variants;
    variants.reserve(decl->entries_.size());
    std::unordered_set<std::string> seenVariants;
    for (size_t i = 0; i < decl->entries_.size(); ++i) {
      const auto &entry = decl->entries_[i];
      if (!seenVariants.insert(entry.name_).second) {
        error(decl->span, "Duplicate enum variant '" + entry.name_ + "' in '" +
                              decl->name_ + "'.");
        continue;
      }
      if (entry.hasExplicitValue_) {
        error(decl->span,
              "Enum variants with payloads cannot use explicit values.");
      }
      std::shared_ptr<zir::Type> payloadType = nullptr;
      if (entry.payloadType_) {
        payloadType = mapType(*entry.payloadType_);
        if (!payloadType) {
          error(entry.payloadType_->span,
                "Unknown type: " + entry.payloadType_->qualifiedName());
          continue;
        }
      }
      variants.push_back({entry.name_, payloadType, static_cast<int64_t>(i)});
    }
    std::static_pointer_cast<zir::TaggedUnionType>(symbol->type)
        ->setVariants(std::move(variants));
  }
}
References classInfos_, sema::Binder::ClassInfo::classType, classTypeDeclarationNodes_, currentModuleId_, currentScope_, displayTypeName(), error(), EnumDecl::Entry::hasExplicitValue_, sema::Binder::ModuleState::info, sema::ModuleInfo::linkPath, mangleName(), mapType(), sema::ModuleInfo::moduleId, sema::ModuleInfo::moduleName, EnumDecl::Entry::name_, sema::Binder::ClassInfo::ownerQualifiedName, Public, recordTypeDeclarationNodes_, sema::ModuleInfo::root, sema::Binder::ModuleState::scope, structTypeDeclarationNodes_, typeDeclarationModuleIds_, sema::Binder::ClassInfo::typeSymbol, validateAndApplyTypeAttributes(), and EnumDecl::Entry::value_.
Referenced by bind().
predeclareModuleValues()
void sema::Binder::predeclareModuleValues (ModuleState & module) private
Definition at line 434 of file binder_decls.cpp.
{
  currentModuleId_ = module.info->moduleId;
  currentScope_ = module.scope;
  for (const auto &child : module.info->root->children) {
    if (auto funDecl = dynamic_cast<FunDecl *>(child.get())) {
      if (funDecl->isUnsafe_) {
        ++unsafeTypeContextDepth_;
      }
      std::unordered_map<std::string, std::shared_ptr<zir::Type>>
          genericBindings;
      for (const auto &genericParam : funDecl->genericParams_) {
        if (!genericParam) {
          continue;
        }
        auto placeholder = std::make_shared<zir::RecordType>(
            genericParam->typeName, genericParam->typeName);
        genericBindings[genericParam->typeName] = placeholder;
      }
      if (!genericBindings.empty()) {
        activeGenericBindingsStack_.push_back(genericBindings);
      }
      std::vector<std::shared_ptr<VariableSymbol>> params;
      for (size_t i = 0; i < funDecl->params_.size(); ++i) {
        const auto &p = funDecl->params_[i];
        if (p->isVariadic && i + 1 != funDecl->params_.size()) {
          error(p->span, "Variadic parameter must be the last parameter.");
        }
        if (p->isVariadic && p->isRef) {
          error(p->span, "Variadic parameter cannot be passed by 'ref'.");
        }
        auto mappedType = mapType(*p->type);
        if (!mappedType) {
          error(p->span, "Unknown type: " + p->type->qualifiedName());
          mappedType =
              std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        auto symbol = std::make_shared<VariableSymbol>(
            p->name, mappedType, false, p->isRef, p->name,
            module.info->moduleName, Visibility::Private);
        if (p->isVariadic) {
          symbol->is_variadic_pack = true;
          symbol->variadic_element_type = mappedType;
          symbol->type = makeVariadicViewType(mappedType);
        }
        params.push_back(std::move(symbol));
      }
      std::shared_ptr<zir::Type> retType = nullptr;
      if (funDecl->returnType_) {
        retType = mapType(*funDecl->returnType_);
      } else if (funDecl->name_ == "main" && module.info->isEntry) {
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
      } else if (!funDecl->isExtern_ && funDecl->body_ &&
                 funDecl->genericParams_.empty()) {
        retType = nullptr;
      } else {
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      if (!genericBindings.empty()) {
        activeGenericBindingsStack_.pop_back();
      }
      if (!retType && funDecl->returnType_) {
        error(funDecl->span,
              "Unknown return type in function '" + funDecl->name_ + "'.");
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      if (funDecl->isUnsafe_) {
        --unsafeTypeContextDepth_;
      }
      auto linkName = (funDecl->name_ == "main" && module.info->isEntry)
                          ? std::string("main")
                          : std::string();
      auto symbol = std::make_shared<FunctionSymbol>(
          funDecl->name_, std::move(params), std::move(retType), "",
          module.info->moduleName, funDecl->visibility_, funDecl->isUnsafe_);
      symbol->returnsRef = funDecl->returnsRef_;
      for (const auto &genericParam : funDecl->genericParams_) {
        if (genericParam) {
          symbol->genericParameterNames.push_back(genericParam->typeName);
        }
      }
      functionGenericParamNames_[symbol.get()] = symbol->genericParameterNames;
      functionDeclarationNodes_[symbol.get()] = funDecl;
      functionDeclarationModuleIds_[symbol.get()] = module.info->moduleId;
      validateAndApplyFunctionAttributes(*funDecl, symbol, false);
      if (symbol->hasNoMangle ||
          (symbol->hasExternC && symbol->externAbi == "C")) {
        symbol->linkName = symbol->name;
      } else if (linkName != "main") {
        symbol->linkName = mangleFunctionName(module.info->linkPath.empty()
                                                  ? module.info->moduleId
                                                  : module.info->linkPath,
                                              *symbol);
      } else {
        symbol->linkName = linkName;
      }
      auto existing = module.scope->lookupLocal(funDecl->name_);
      if (findFunctionBySignature(existing, *symbol)) {
        error(funDecl->span,
              "Function '" + funDecl->name_ + "' already declared.");
        continue;
      }
      auto overloads = module.scope->declareFunction(funDecl->name_, symbol);
      if (!overloads) {
        error(funDecl->span, "Function '" + funDecl->name_ +
                                 "' conflicts with an existing declaration.");
        continue;
      }
      declaredFunctionSymbols_[funDecl] = symbol;
      module.symbol->members[funDecl->name_] = overloads;
      if (funDecl->visibility_ == Visibility::Public) {
        auto exportIt = module.symbol->exports.find(funDecl->name_);
        std::shared_ptr<OverloadSetSymbol> exportSet;
        if (exportIt == module.symbol->exports.end()) {
          exportSet = std::make_shared<OverloadSetSymbol>(
              funDecl->name_, module.info->moduleName, Visibility::Public);
          module.symbol->exports[funDecl->name_] = exportSet;
        } else {
          exportSet =
              std::dynamic_pointer_cast<OverloadSetSymbol>(exportIt->second);
        }
        if (!exportSet) {
          error(funDecl->span, "Function '" + funDecl->name_ +
                                   "' conflicts with an exported declaration.");
        } else {
          exportSet->addOverload(symbol);
        }
      }
    } else if (auto classDecl = dynamic_cast<ClassDecl *>(child.get())) {
      auto classSymbol = std::dynamic_pointer_cast<TypeSymbol>(
          module.scope->lookup(classDecl->name_));
      if (!classSymbol || !classSymbol->isClass ||
          !classSymbol->genericParameterNames.empty()) {
        continue;
      }
      auto classType =
          std::static_pointer_cast<zir::ClassType>(classSymbol->type);
      auto &classInfo = classInfos_[classType->getName()];
      if (classDecl->baseType_) {
        bool hasOwnCtor = false;
        bool hasOwnDtor = false;
        for (const auto &methodDecl : classDecl->methods_) {
          hasOwnCtor = hasOwnCtor || methodDecl->name_ == "init";
          hasOwnDtor = hasOwnDtor || methodDecl->name_ == "deinit";
        }
        auto baseType = mapType(*classDecl->baseType_);
        if (baseType && baseType->getKind() == zir::TypeKind::Class) {
          auto baseClass = std::static_pointer_cast<zir::ClassType>(baseType);
          auto baseIt = classInfos_.find(baseClass->getName());
          if (baseIt != classInfos_.end()) {
            if (!hasOwnCtor) {
              classInfo.constructor = baseIt->second.constructor;
            }
            if (!hasOwnDtor) {
              classInfo.destructor = baseIt->second.destructor;
            }
            classInfo.methods.insert(baseIt->second.methods.begin(),
                                     baseIt->second.methods.end());
            classInfo.nextVirtualSlot = baseIt->second.nextVirtualSlot;
          }
        }
      }
      for (const auto &methodDecl : classDecl->methods_) {
        if (methodDecl->isUnsafe_) {
          ++unsafeTypeContextDepth_;
        }
        std::unordered_map<std::string, std::shared_ptr<zir::Type>>
            methodGenericBindings;
        for (const auto &genericParam : methodDecl->genericParams_) {
          if (genericParam) {
            auto placeholder = std::make_shared<zir::RecordType>(
                genericParam->typeName, genericParam->typeName);
            methodGenericBindings[genericParam->typeName] = placeholder;
          }
        }
        if (!methodGenericBindings.empty()) {
          activeGenericBindingsStack_.push_back(methodGenericBindings);
        }
        std::vector<std::shared_ptr<VariableSymbol>> params;
        if (!methodDecl->isStatic_) {
          params.push_back(std::make_shared<VariableSymbol>(
              "self", classType, false, false, "self", module.info->moduleName,
              Visibility::Private));
        }
        for (size_t i = 0; i < methodDecl->params_.size(); ++i) {
          const auto &p = methodDecl->params_[i];
          auto mappedType = mapType(*p->type);
          if (!mappedType) {
            error(p->span, "Unknown type: " + p->type->qualifiedName());
            mappedType =
                std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
          }
          params.push_back(std::make_shared<VariableSymbol>(
              p->name, mappedType, false, p->isRef, p->name,
              module.info->moduleName, Visibility::Private));
        }
        std::shared_ptr<zir::Type> retType;
        bool isCtor = methodDecl->name_ == "init";
        bool isDtor = methodDecl->name_ == "deinit";
        if (isDtor &&
            (!methodDecl->params_.empty() || methodDecl->returnType_)) {
          error(methodDecl->span,
                "Destructor 'deinit' cannot have parameters or a return type.");
        }
        if (isCtor) {
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        } else if (isDtor) {
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        } else if (methodDecl->returnType_) {
          retType = mapType(*methodDecl->returnType_);
        } else {
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        if (!methodGenericBindings.empty()) {
          activeGenericBindingsStack_.pop_back();
        }
        if (!retType) {
          retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        if (methodDecl->isUnsafe_) {
          --unsafeTypeContextDepth_;
        }
        auto symbol = std::make_shared<FunctionSymbol>(
            methodDecl->name_, std::move(params), std::move(retType), "",
            module.info->moduleName, methodDecl->visibility_,
            methodDecl->isUnsafe_);
        for (const auto &genericParam : methodDecl->genericParams_) {
          if (genericParam) {
            symbol->genericParameterNames.push_back(genericParam->typeName);
          }
        }
        symbol->isMethod = !methodDecl->isStatic_;
        symbol->isStatic = methodDecl->isStatic_;
        symbol->isConstructor = isCtor;
        symbol->isDestructor = isDtor;
        symbol->ownerTypeName = classType->getName();
        if (symbol->isMethod && !symbol->isStatic && !symbol->isConstructor &&
            !symbol->isDestructor) {
          symbol->vtableSlot = findOverriddenVtableSlot(classInfo, *symbol);
          if (symbol->vtableSlot < 0) {
            symbol->vtableSlot = classInfo.nextVirtualSlot++;
          }
        }
        symbol->linkName =
            mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                     : module.info->linkPath,
                       classDecl->name_ + "$" + methodDecl->name_ + "$" +
                           sanitizeTypeName(functionSignatureKey(*symbol)));
        declaredFunctionSymbols_[methodDecl.get()] = symbol;
        functionDeclarationNodes_[symbol.get()] = methodDecl.get();
        functionDeclarationModuleIds_[symbol.get()] = module.info->moduleId;
        functionGenericParamNames_[symbol.get()] =
            symbol->genericParameterNames;
        addClassMethodOverload(classInfo, symbol);
        if (isCtor) {
          if (!classInfo.constructor) {
            classInfo.constructor = symbol;
          }
        } else if (isDtor) {
          classInfo.destructor = symbol;
        }
      }
    } else if (auto extDecl = dynamic_cast<ExtDecl *>(child.get())) {
      ++externTypeContextDepth_;
      std::vector<std::shared_ptr<VariableSymbol>> params;
      for (const auto &p : extDecl->params_) {
        if (p->isVariadic) {
          error(p->span, "Variadic parameters are only supported in Zap "
                         "function declarations.");
        }
        auto mappedType = mapType(*p->type);
        if (!mappedType) {
          error(p->span, "Unknown type: " + p->type->qualifiedName());
          mappedType =
              std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
        params.push_back(std::make_shared<VariableSymbol>(
            p->name, mappedType, false, p->isRef, p->name,
            module.info->moduleName, Visibility::Private));
      }
      auto retType =
          extDecl->returnType_
              ? mapType(*extDecl->returnType_)
              : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      if (!retType) {
        error(extDecl->span, "Unknown return type in external function '" +
                                 extDecl->name_ + "'.");
        retType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      --externTypeContextDepth_;
      auto linkName = extDecl->name_;
      bool isStdIoModule = module.info->linkPath == "std/io";
      if (isStdIoModule && extDecl->name_ == "printf") {
        linkName = "zap_printf";
      } else if (isStdIoModule && extDecl->name_ == "printfln") {
        linkName = "zap_printfln";
      }
      auto symbol = std::make_shared<FunctionSymbol>(
          extDecl->name_, std::move(params), std::move(retType), linkName,
          module.info->moduleName, extDecl->visibility_, false,
          extDecl->isCVariadic_);
      validateAndApplyFunctionAttributes(*extDecl, symbol, true);
      if (symbol->hasNoMangle ||
          (symbol->hasExternC && symbol->externAbi == "C")) {
        symbol->linkName = symbol->name;
      }
      auto existing = module.scope->lookupLocal(extDecl->name_);
      if (findFunctionBySignature(existing, *symbol)) {
        error(extDecl->span,
              "External function '" + extDecl->name_ + "' already declared.");
        continue;
      }
      auto overloads = module.scope->declareFunction(extDecl->name_, symbol);
      if (!overloads) {
        error(extDecl->span, "External function '" + extDecl->name_ +
                                 "' conflicts with an existing declaration.");
        continue;
      }
      declaredFunctionSymbols_[extDecl] = symbol;
      module.symbol->members[extDecl->name_] = overloads;
      if (extDecl->visibility_ == Visibility::Public) {
        auto exportIt = module.symbol->exports.find(extDecl->name_);
        std::shared_ptr<OverloadSetSymbol> exportSet;
        if (exportIt == module.symbol->exports.end()) {
          exportSet = std::make_shared<OverloadSetSymbol>(
              extDecl->name_, module.info->moduleName, Visibility::Public);
          module.symbol->exports[extDecl->name_] = exportSet;
        } else {
          exportSet =
              std::dynamic_pointer_cast<OverloadSetSymbol>(exportIt->second);
        }
        if (!exportSet) {
          error(extDecl->span, "External function '" + extDecl->name_ +
                                   "' conflicts with an exported declaration.");
        } else {
          exportSet->addOverload(symbol);
        }
      }
    } else if (auto varDecl = dynamic_cast<VarDecl *>(child.get())) {
      if (!varDecl->isGlobal_) {
        continue;
      }
      std::shared_ptr<zir::Type> type;
      if (varDecl->type_) {
        type = mapType(*varDecl->type_);
        if (!type) {
          error(varDecl->span,
                "Unknown type: " + varDecl->type_->qualifiedName());
          type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
      } else {
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      auto linkName = varDecl->isExternal_
                          ? varDecl->name_
                          : mangleName(module.info->linkPath.empty()
                                           ? module.info->moduleId
                                           : module.info->linkPath,
                                       varDecl->name_);
      auto symbol = std::make_shared<VariableSymbol>(
          varDecl->name_, type, false, false, linkName, module.info->moduleName,
          varDecl->visibility_);
      symbol->is_external = varDecl->isExternal_;
      if (!module.scope->declare(varDecl->name_, symbol)) {
        error(varDecl->span,
              "Variable '" + varDecl->name_ + "' already declared.");
      }
      module.symbol->members[varDecl->name_] = symbol;
      if (varDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[varDecl->name_] = symbol;
      }
    } else if (auto constDecl = dynamic_cast<ConstDecl *>(child.get())) {
      std::shared_ptr<zir::Type> type;
      if (constDecl->type_) {
        type = mapType(*constDecl->type_);
        if (!type) {
          error(constDecl->span,
                "Unknown type: " + constDecl->type_->qualifiedName());
          type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
        }
      } else {
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
      auto symbol = std::make_shared<VariableSymbol>(
          constDecl->name_, type, true, false,
          mangleName(module.info->linkPath.empty() ? module.info->moduleId
                                                   : module.info->linkPath,
                     constDecl->name_),
          module.info->moduleName, constDecl->visibility_);
      if (!module.scope->declare(constDecl->name_, symbol)) {
        error(constDecl->span,
              "Identifier '" + constDecl->name_ + "' already declared.");
      }
      module.symbol->members[constDecl->name_] = symbol;
      if (constDecl->visibility_ == Visibility::Public) {
        module.symbol->exports[constDecl->name_] = symbol;
      }
    }
  }
}
References activeGenericBindingsStack_, zir::Class, classInfos_, currentModuleId_, currentScope_, declaredFunctionSymbols_, error(), findFunctionBySignature(), functionDeclarationModuleIds_, functionDeclarationNodes_, functionGenericParamNames_, sema::Binder::ModuleState::info, zir::Int, sema::ModuleInfo::isEntry, sema::ModuleInfo::linkPath, sema::makeVariadicViewType(), mangleFunctionName(), mapType(), sema::ModuleInfo::moduleId, sema::ModuleInfo::moduleName, Private, Public, sema::ModuleInfo::root, sema::Binder::ModuleState::symbol, unsafeTypeContextDepth_, validateAndApplyFunctionAttributes(), and zir::Void.
Referenced by ensureModuleValuesReady().
pushScope()
void sema::Binder::pushScope () private
Definition at line 925 of file binder.cpp.
                       {
  currentScope_ = std::make_shared<SymbolTable>(currentScope_);
}
References currentScope_.
Referenced by bindBody(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), visit(), and visit().
renderFunctionSignature()
std::string sema::Binder::renderFunctionSignature (const FunctionSymbol & function) const private
Definition at line 617 of file binder.cpp.
{
  std::string rendered = function.name;
  auto genericParamNamesIt = functionGenericParamNames_.find(&function);
  const auto *genericParamNames =
      genericParamNamesIt != functionGenericParamNames_.end()
          ? &genericParamNamesIt->second
          : &function.genericParameterNames;
  if (genericParamNames && !genericParamNames->empty()) {
    rendered += "<";
    for (size_t i = 0; i < genericParamNames->size(); ++i) {
      if (i != 0) {
        rendered += ", ";
      }
      const auto &name = (*genericParamNames)[i];
      auto argIt = function.genericArguments.find(name);
      rendered += (argIt != function.genericArguments.end() && argIt->second)
                      ? argIt->second->toString()
                      : name;
    }
    rendered += ">";
  }
  rendered += "(";
  for (size_t i = 0; i < function.parameters.size(); ++i) {
    if (i != 0) {
      rendered += ", ";
    }
    const auto &param = function.parameters[i];
    if (param->is_ref) {
      rendered += "ref ";
    }
    if (param->is_variadic_pack) {
      rendered += "...";
      rendered += param->variadic_element_type
                      ? param->variadic_element_type->toString()
                      : (param->type ? param->type->toString() : "Void");
    } else {
      rendered += param->type ? param->type->toString() : "Void";
    }
  }
  if (function.isCVariadic) {
    if (!function.parameters.empty()) {
      rendered += ", ";
    }
    rendered += "...";
  }
  rendered += ")";
  return rendered;
}
References functionGenericParamNames_, sema::FunctionSymbol::genericArguments, sema::FunctionSymbol::genericParameterNames, sema::FunctionSymbol::isCVariadic, sema::Symbol::name, and sema::FunctionSymbol::parameters.
Referenced by visit().
renderTypeForUser()
std::string sema::Binder::renderTypeForUser (const std::shared_ptr< zir::Type > & type) const private
Definition at line 761 of file binder.cpp.
{
  if (!type) {
    return "<unknown>";
  }
  switch (type->getKind()) {
  case zir::TypeKind::Void:
    return "Void";
  case zir::TypeKind::Bool:
    return "Bool";
  case zir::TypeKind::Char:
    return "Char";
  case zir::TypeKind::Int:
    return "Int";
  case zir::TypeKind::Int8:
    return "Int8";
  case zir::TypeKind::Int16:
    return "Int16";
  case zir::TypeKind::Int32:
    return "Int32";
  case zir::TypeKind::Int64:
    return "Int64";
  case zir::TypeKind::UInt:
    return "UInt";
  case zir::TypeKind::UInt8:
    return "UInt8";
  case zir::TypeKind::UInt16:
    return "UInt16";
  case zir::TypeKind::UInt32:
    return "UInt32";
  case zir::TypeKind::UInt64:
    return "UInt64";
  case zir::TypeKind::Float:
    return "Float";
  case zir::TypeKind::Float32:
    return "Float32";
  case zir::TypeKind::Float64:
    return "Float64";
  case zir::TypeKind::NullPtr:
    return "null";
  case zir::TypeKind::Pointer: {
    auto ptr = std::static_pointer_cast<zir::PointerType>(type);
    return "*" + renderTypeForUser(ptr->getBaseType());
  }
  case zir::TypeKind::Array: {
    auto arr = std::static_pointer_cast<zir::ArrayType>(type);
    if (arr->getSize() == 0) {
      return "[]" + renderTypeForUser(arr->getBaseType());
    }
    return "[" + std::to_string(arr->getSize()) + "]" +
           renderTypeForUser(arr->getBaseType());
  }
  case zir::TypeKind::Record: {
    auto rec = std::static_pointer_cast<zir::RecordType>(type);
    return rec->getName();
  }
  case zir::TypeKind::Class: {
    auto cls = std::static_pointer_cast<zir::ClassType>(type);
    return std::string(cls->isWeak() ? "weak " : "") + cls->getName();
  }
  case zir::TypeKind::Enum: {
    auto en = std::static_pointer_cast<zir::EnumType>(type);
    return en->getName();
  }
  }
  return type->toString();
}
References zir::Array, zir::Bool, zir::Char, zir::Class, zir::Enum, zir::Float, zir::Float32, zir::Float64, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, zir::NullPtr, zir::Pointer, zir::Record, renderTypeForUser(), zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, zir::UInt8, and zir::Void.
Referenced by buildBinaryExpression(), renderTypeForUser(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
requireUnsafeContext()
void sema::Binder::requireUnsafeContext (SourceSpan span, const std::string & feature) private
Definition at line 1616 of file binder_types.cpp.
{
  if (!isUnsafeActive()) {
    error(span, "Using " + feature + " is only allowed inside unsafe code.");
  }
}
References error(), and isUnsafeActive().
Referenced by mapType(), visit(), visit(), visit(), and visit().
requireUnsafeEnabled()
void sema::Binder::requireUnsafeEnabled (SourceSpan span, const std::string & feature) private
Definition at line 1610 of file binder_types.cpp.
{
  if (!allowUnsafe_) {
    error(span, "Using " + feature + " requires '--allow-unsafe'.");
  }
}
References allowUnsafe_, and error().
Referenced by visit().
resolveModuleMember()
std::shared_ptr< Symbol > sema::Binder::resolveModuleMember (const std::string & moduleName, const std::string & memberName, SourceSpan span) private
Definition at line 845 of file binder.cpp.
{
  auto moduleSym = std::dynamic_pointer_cast<ModuleSymbol>(
      currentScope_->lookup(moduleName));
  if (!moduleSym) {
    error(span, "Undefined module: " + moduleName);
    return nullptr;
  }
  auto exportedIt = moduleSym->exports.find(memberName);
  if (exportedIt != moduleSym->exports.end()) {
    return exportedIt->second;
  }
  auto memberIt = moduleSym->members.find(memberName);
  if (memberIt == moduleSym->members.end()) {
    error(span,
          "Module '" + moduleName + "' has no member '" + memberName + "'.");
    return nullptr;
  }
  error(span, "Member '" + memberName + "' of module '" + moduleName +
                  "' is private.");
  return nullptr;
}
References currentScope_, and error().
resolveQualifiedSymbol()
std::shared_ptr< Symbol > sema::Binder::resolveQualifiedSymbol (const std::vector< std::string > & parts, SourceSpan span, SymbolKind expectedKind = SymbolKind::Variable, bool allowAnyKind = false) private
Definition at line 871 of file binder.cpp.
{
  if (parts.empty()) {
    return nullptr;
  }
  auto symbol = lookupVisibleSymbol(parts.front());
  if (!symbol) {
    error(span, "Undefined identifier: " + parts.front());
    return nullptr;
  }
  for (size_t i = 1; i < parts.size(); ++i) {
    auto moduleSym = std::dynamic_pointer_cast<ModuleSymbol>(symbol);
    if (!moduleSym) {
      error(span, "'" + parts[i - 1] + "' is not a module.");
      return nullptr;
    }
    auto memberIt = moduleSym->exports.find(parts[i]);
    if (memberIt == moduleSym->exports.end()) {
      auto privateIt = moduleSym->members.find(parts[i]);
      if (privateIt != moduleSym->members.end()) {
        error(span, "Member '" + parts[i] + "' of module '" + moduleSym->name +
                        "' is private.");
      } else {
        error(span, "Module '" + moduleSym->name + "' has no member '" +
                        parts[i] + "'.");
      }
      return nullptr;
    }
    symbol = memberIt->second;
  }
  if (!allowAnyKind && symbol->getKind() != expectedKind &&
      !(expectedKind == SymbolKind::Function &&
        symbol->getKind() == SymbolKind::OverloadSet)) {
    return nullptr;
  }
  return symbol;
}
References error(), sema::Function, lookupVisibleSymbol(), and sema::OverloadSet.
Referenced by mapType(), visit(), and visit().
substituteGenericType()
std::shared_ptr< zir::Type > sema::Binder::substituteGenericType (std::shared_ptr< zir::Type > type, const std::unordered_map< std::string, std::shared_ptr< zir::Type > > & genericBindings) const private
Definition at line 258 of file binder_types.cpp.
{
  if (!type) {
    return nullptr;
  }
  if (type->getKind() == zir::TypeKind::Record) {
    auto record = std::static_pointer_cast<zir::RecordType>(type);
    auto it = genericBindings.find(record->getName());
    if (it == genericBindings.end() && !record->getName().empty() &&
        record->getName()[0] == '%') {
      it = genericBindings.find(record->getName().substr(1));
    }
    if (it != genericBindings.end()) {
      return it->second;
    }
    if (record->isGenericInstance()) {
      std::vector<std::shared_ptr<zir::Type>> substitutedArgs;
      substitutedArgs.reserve(record->getGenericArguments().size());
      for (const auto &arg : record->getGenericArguments()) {
        substitutedArgs.push_back(substituteGenericType(arg, genericBindings));
      }
      auto substituted = std::make_shared<zir::RecordType>(
          renderGenericTypeName(record->getGenericBaseName(), substitutedArgs),
          renderGenericCodegenName(record->getGenericCodegenBaseName(),
                                   substitutedArgs));
      substituted->setGenericInstance(record->getGenericBaseName(),
                                      record->getGenericCodegenBaseName(),
                                      substitutedArgs);
      for (const auto &field : record->getFields()) {
        substituted->addField(
            field.name, substituteGenericType(field.type, genericBindings),
            field.visibility);
      }
      return substituted;
    }
    if (record->getName().rfind("__zap_varargs_", 0) == 0) {
      const auto &fields = record->getFields();
      if (fields.size() >= 2 &&
          fields[0].type->getKind() == zir::TypeKind::Pointer) {
        auto dataPtr =
            std::static_pointer_cast<zir::PointerType>(fields[0].type);
        auto elemType =
            substituteGenericType(dataPtr->getBaseType(), genericBindings);
        auto substitutedView = std::make_shared<zir::RecordType>(
            "__zap_varargs_" + sanitizeTypeName(elemType->toString()),
            "__zap_varargs_" + sanitizeTypeName(elemType->toString()));
        substitutedView->addField("data",
                                  std::make_shared<zir::PointerType>(elemType));
        substitutedView->addField(
            "len", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int));
        return substitutedView;
      }
    }
    return type;
  }
  if (type->getKind() == zir::TypeKind::Class) {
    auto classType = std::static_pointer_cast<zir::ClassType>(type);
    auto it = genericBindings.find(classType->getName());
    if (it == genericBindings.end() && !classType->getName().empty() &&
        classType->getName()[0] == '%') {
      it = genericBindings.find(classType->getName().substr(1));
    }
    if (it != genericBindings.end()) {
      return it->second;
    }
    if (classType->isGenericInstance()) {
      std::vector<std::shared_ptr<zir::Type>> substitutedArgs;
      substitutedArgs.reserve(classType->getGenericArguments().size());
      for (const auto &arg : classType->getGenericArguments()) {
        substitutedArgs.push_back(substituteGenericType(arg, genericBindings));
      }
      auto substituted = std::make_shared<zir::ClassType>(
          renderGenericTypeName(classType->getGenericBaseName(),
                                substitutedArgs),
          renderGenericCodegenName(classType->getGenericCodegenBaseName(),
                                   substitutedArgs));
      substituted->setGenericInstance(classType->getGenericBaseName(),
                                      classType->getGenericCodegenBaseName(),
                                      substitutedArgs);
      substituted->setWeak(classType->isWeak());
      if (auto base = classType->getBase()) {
        auto substitutedBase = substituteGenericType(base, genericBindings);
        if (substitutedBase &&
            substitutedBase->getKind() == zir::TypeKind::Class) {
          substituted->setBase(
              std::static_pointer_cast<zir::ClassType>(substitutedBase));
        }
      }
      for (const auto &field : classType->getFields()) {
        substituted->addField(
            field.name, substituteGenericType(field.type, genericBindings),
            field.visibility);
      }
      return substituted;
    }
    return type;
  }
  if (type->getKind() == zir::TypeKind::Pointer) {
    auto ptr = std::static_pointer_cast<zir::PointerType>(type);
    auto base = substituteGenericType(ptr->getBaseType(), genericBindings);
    return std::make_shared<zir::PointerType>(base);
  }
  if (type->getKind() == zir::TypeKind::Array) {
    auto arr = std::static_pointer_cast<zir::ArrayType>(type);
    auto base = substituteGenericType(arr->getBaseType(), genericBindings);
    return std::make_shared<zir::ArrayType>(base, arr->getSize());
  }
  return type;
}
References zir::Array, zir::Class, zir::Int, zir::Pointer, zir::Record, sema::renderGenericCodegenName(), sema::renderGenericTypeName(), sema::sanitizeTypeName(), and substituteGenericType().
Referenced by ensureGenericFunctionInstantiation(), mapTypeWithGenericBindings(), substituteGenericType(), and visit().
typeBitWidth()
int sema::Binder::typeBitWidth (std::shared_ptr< zir::Type > type) const private
Definition at line 1126 of file binder_types.cpp.
{
  if (!type) {
    return 0;
  }
  switch (type->getKind()) {
  case zir::TypeKind::Bool:
    return 1;
  case zir::TypeKind::Char:
  case zir::TypeKind::Int8:
  case zir::TypeKind::UInt8:
    return 8;
  case zir::TypeKind::Int16:
  case zir::TypeKind::UInt16:
    return 16;
  case zir::TypeKind::Int32:
  case zir::TypeKind::UInt32:
  case zir::TypeKind::Int:
  case zir::TypeKind::UInt:
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
    return 32;
  case zir::TypeKind::Int64:
  case zir::TypeKind::UInt64:
  case zir::TypeKind::Float64:
    return 64;
  default:
    return 0;
  }
}
References zir::Bool, zir::Char, zir::Float, zir::Float32, zir::Float64, zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, and zir::UInt8.
Referenced by buildBinaryExpression(), conversionCost(), describeConversion(), evaluateConstantInt(), and getPromotedType().
validateAndApplyFunctionAttributes()
void sema::Binder::validateAndApplyFunctionAttributes (const TopLevel & node, const std::shared_ptr< FunctionSymbol > & symbol, bool isExternalDeclaration) private
Definition at line 1352 of file binder_types.cpp.
{
  (void)isExternalDeclaration;
  if (!symbol) {
    return;
  }
  warnUnknownAttributes(node);
  bool seenExtern = false;
  bool seenNoMangle = false;
  for (const auto &attr : node.attributes_) {
    if (attr.name == "extern") {
      if (seenExtern) {
        error(attr.span, "duplicate attribute 'extern'");
        continue;
      }
      seenExtern = true;
      if (attr.arguments.size() != 1 ||
          attr.arguments[0].kind != AttributeArgumentKind::Positional) {
        error(attr.span, "attribute 'extern' expects exactly one positional "
                         "string argument");
        continue;
      }
      auto *str = dynamic_cast<ConstString *>(attr.arguments[0].value.get());
      if (!str) {
        error(attr.span,
              "attribute 'extern' expects a string literal argument");
        continue;
      }
      if (str->value_ != "C") {
        error(attr.span,
              "invalid argument for attribute 'extern': expected \"C\"");
        continue;
      }
      symbol->hasExternC = true;
      symbol->externAbi = str->value_;
      continue;
    }
    if (attr.name == "noMangle") {
      if (seenNoMangle) {
        error(attr.span, "duplicate attribute 'noMangle'");
        continue;
      }
      if (attr.hasArguments()) {
        error(attr.span, "attribute 'noMangle' does not accept arguments");
        continue;
      }
      seenNoMangle = true;
      symbol->hasNoMangle = true;
      continue;
    }
    if (attr.name == "repr" || attr.name == "error" || attr.name == "packed") {
      error(attr.span,
            "attribute '" + attr.name + "' cannot be applied to functions");
      continue;
    }
  }
}
References TopLevel::attributes_, error(), Positional, ConstString::value_, and warnUnknownAttributes().
Referenced by predeclareModuleValues().
validateAndApplyTypeAttributes()
void sema::Binder::validateAndApplyTypeAttributes (const TopLevel & node, const std::shared_ptr< TypeSymbol > & symbol, bool allowErrorAttribute) private
Definition at line 1258 of file binder_types.cpp.
{
  if (!symbol) {
    return;
  }
  warnUnknownAttributes(node);
  bool seenError = false;
  bool seenRepr = false;
  bool seenPacked = false;
  for (const auto &attr : node.attributes_) {
    if (attr.name == "error") {
      if (!allowErrorAttribute) {
        error(attr.span, "attribute 'error' cannot be applied to this type");
        continue;
      }
      if (seenError) {
        error(attr.span, "duplicate attribute 'error'");
        continue;
      }
      if (attr.hasArguments()) {
        error(attr.span, "attribute 'error' does not accept arguments");
        continue;
      }
      seenError = true;
      symbol->isErrorType = true;
      continue;
    }
    if (attr.name == "repr") {
      if (seenRepr) {
        error(attr.span, "duplicate attribute 'repr'");
        continue;
      }
      seenRepr = true;
      if (attr.arguments.size() != 1 ||
          attr.arguments[0].kind != AttributeArgumentKind::Positional) {
        error(
            attr.span,
            "attribute 'repr' expects exactly one positional string argument");
        continue;
      }
      auto *str = dynamic_cast<ConstString *>(attr.arguments[0].value.get());
      if (!str) {
        error(attr.span, "attribute 'repr' expects a string literal argument");
        continue;
      }
      if (str->value_ != "C") {
        error(attr.span,
              "invalid argument for attribute 'repr': expected \"C\"");
        continue;
      }
      symbol->hasReprC = true;
      symbol->reprValue = str->value_;
      continue;
    }
    if (attr.name == "packed") {
      if (seenPacked) {
        error(attr.span, "duplicate attribute 'packed'");
        continue;
      }
      if (attr.hasArguments()) {
        error(attr.span, "attribute 'packed' does not accept arguments");
        continue;
      }
      auto recordType =
          std::dynamic_pointer_cast<zir::RecordType>(symbol->type);
      if (!recordType || symbol->type->getKind() != zir::TypeKind::Record) {
        error(attr.span,
              "attribute 'packed' can only be applied to record types");
        continue;
      }
      seenPacked = true;
      symbol->isPacked = true;
      recordType->isPacked = true;
      continue;
    }
    if (attr.name == "extern" || attr.name == "noMangle") {
      error(attr.span, "attribute '" + attr.name +
                           "' cannot be applied to type declarations");
      continue;
    }
  }
}
References TopLevel::attributes_, error(), Positional, zir::Record, ConstString::value_, and warnUnknownAttributes().
Referenced by predeclareModuleTypes().
validateGenericConstraints()
bool sema::Binder::validateGenericConstraints (const std::vector< GenericConstraint > & constraints, std::unordered_map< std::string, std::shared_ptr< zir::Type > > & bindings, std::string * failureReason = nullptr) private
Definition at line 378 of file binder_types.cpp.
{
  for (const auto &constraint : constraints) {
    auto boundIt = bindings.find(constraint.parameterName);
    if (boundIt == bindings.end() || !boundIt->second) {
      if (failureReason) {
        *failureReason = "missing binding for constrained type parameter '" +
                         constraint.parameterName + "'";
      }
      return false;
    }
    if (!constraint.boundType) {
      continue;
    }
    activeGenericBindingsStack_.push_back(bindings);
    auto requiredType = mapType(*constraint.boundType);
    activeGenericBindingsStack_.pop_back();
    if (!requiredType) {
      if (failureReason) {
        *failureReason =
            "unknown constraint type for '" + constraint.parameterName + "'";
      }
      return false;
    }
    if (!canConvert(boundIt->second, requiredType)) {
      if (failureReason) {
        *failureReason =
            "type parameter '" + constraint.parameterName + "' with type '" +
            boundIt->second->toString() + "' does not satisfy constraint '" +
            constraint.parameterName + ": " + requiredType->toString() + "'";
      }
      return false;
    }
  }
  return true;
}
References activeGenericBindingsStack_, canConvert(), and mapType().
Referenced by buildGenericBindings(), and instantiateGenericTypeSymbol().
visit() [1/44]
void sema::Binder::visit (ArrayLiteralNode & node) override virtual
Reimplemented from Visitor.
Definition at line 2009 of file binder_exprs.cpp.
{
  std::vector<std::unique_ptr<BoundExpression>> elements;
  std::shared_ptr<zir::Type> elementType = nullptr;
  auto expectedType = currentExpectedExpressionType();
  if (expectedType && expectedType->getKind() == zir::TypeKind::Array) {
    elementType =
        std::static_pointer_cast<zir::ArrayType>(expectedType)->getBaseType();
  }
  for (const auto &el : node.elements_) {
    auto boundEl = bindExpressionWithExpected(el.get(), elementType);
    if (boundEl) {
      if (!elementType) {
        elementType = boundEl->type;
      } else if (!canConvert(boundEl->type, elementType)) {
        error(el->span, "Array elements must have the same type. Expected '" +
                            renderTypeForUser(elementType) + "', but got '" +
                            renderTypeForUser(boundEl->type) + "'");
      }
      elements.push_back(std::move(boundEl));
    }
  }
  auto arrayType = std::make_shared<zir::ArrayType>(
      elementType ? elementType
                  : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void),
      elements.size());
  expressionStack_.push(
      std::make_unique<BoundArrayLiteral>(std::move(elements), arrayType));
}
References zir::Array, bindExpressionWithExpected(), canConvert(), currentExpectedExpressionType(), ArrayLiteralNode::elements_, error(), expressionStack_, renderTypeForUser(), visit(), and zir::Void.
visit() [2/44]
void sema::Binder::visit (AsmStmtNode & node) override virtual
Reimplemented from Visitor.
Definition at line 86 of file binder_stmts.cpp.
{
  requireUnsafeContext(node.span, "inline 'asm'");
  std::vector<BoundAsmOperand> outputs;
  for (auto &operand : node.outputs) {
    operand.expr->accept(*this);
    if (expressionStack_.empty())
      return;
    auto bound = std::move(expressionStack_.top());
    expressionStack_.pop();
    bool isLValue =
        dynamic_cast<BoundVariableExpression *>(bound.get()) ||
        dynamic_cast<BoundIndexAccess *>(bound.get()) ||
        dynamic_cast<BoundMemberAccess *>(bound.get()) ||
        (dynamic_cast<BoundUnaryExpression *>(bound.get()) &&
         static_cast<BoundUnaryExpression *>(bound.get())->op == "*");
    if (!isLValue) {
      error(node.span, "Inline 'asm' output operand must be an l-value.");
      return;
    }
    if (auto varExpr = dynamic_cast<BoundVariableExpression *>(bound.get())) {
      if (varExpr->symbol->is_const) {
        error(node.span, "Cannot assign to constant '" + varExpr->symbol->name +
                             "' through inline 'asm'.");
        return;
      }
    }
    outputs.push_back({operand.constraint, std::move(bound)});
  }
  std::vector<BoundAsmOperand> inputs;
  for (auto &operand : node.inputs) {
    operand.expr->accept(*this);
    if (expressionStack_.empty())
      return;
    auto bound = std::move(expressionStack_.top());
    expressionStack_.pop();
    inputs.push_back({operand.constraint, std::move(bound)});
  }
  statementStack_.push(std::make_unique<BoundAsmStatement>(
      node.assembly, std::move(outputs), std::move(inputs), node.clobbers));
}
References AsmStmtNode::assembly, AsmStmtNode::clobbers, error(), expressionStack_, AsmStmtNode::inputs, sema::BoundUnaryExpression::op, AsmStmtNode::outputs, requireUnsafeContext(), Node::span, and statementStack_.
visit() [3/44]
void sema::Binder::visit (AssignNode & node) override virtual
Reimplemented from Visitor.
Definition at line 708 of file binder_exprs.cpp.
{
  node.target_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto target = std::move(expressionStack_.top());
  expressionStack_.pop();
  auto *targetAsVar = dynamic_cast<BoundVariableExpression *>(target.get());
  auto *targetAsIndex = dynamic_cast<BoundIndexAccess *>(target.get());
  auto *targetAsMember = dynamic_cast<BoundMemberAccess *>(target.get());
  auto *targetAsUnary = dynamic_cast<BoundUnaryExpression *>(target.get());
  auto *targetAsCall = dynamic_cast<BoundFunctionCall *>(target.get());
  bool isLValue = targetAsVar || targetAsIndex || targetAsMember ||
                  (targetAsUnary && targetAsUnary->op == "*") ||
                  (targetAsCall && targetAsCall->symbol->returnsRef);
  if (!isLValue) {
    error(node.span, "Target of assignment must be an l-value.");
    return;
  }
  if (auto varExpr = targetAsVar) {
    if (varExpr->symbol->is_const) {
      error(node.span,
            "Cannot assign to constant '" + varExpr->symbol->name + "'.");
      return;
    }
  } else if (auto indexExpr = targetAsIndex) {
    if (isStringType(indexExpr->left->type)) {
      error(node.span, "Cannot assign through String index access.");
      return;
    }
  }
  auto expr = bindExpressionWithExpected(node.expr_.get(), target->type);
  if (!expr)
    return;
  bool isCompound = !node.op_.empty();
  if (isCompound) {
    auto targetLoad = std::make_unique<BoundCompoundTargetLoad>(target->type);
    expr =
        buildBinaryExpression(std::move(targetLoad), node.op_, std::move(expr),
                              node.target_->span, node.expr_->span);
    if (!expr)
      return;
  }
  if (!canConvert(expr->type, target->type)) {
    error(node.span, "Cannot assign expression of type '" +
                         renderTypeForUser(expr->type) + "' to type '" +
                         renderTypeForUser(target->type) + "'");
  } else {
    expr = wrapInCast(std::move(expr), target->type);
  }
  statementStack_.push(std::make_unique<BoundAssignment>(
      std::move(target), std::move(expr), isCompound));
}
References bindExpressionWithExpected(), buildBinaryExpression(), canConvert(), error(), AssignNode::expr_, expressionStack_, sema::isStringType(), AssignNode::op_, renderTypeForUser(), Node::span, statementStack_, AssignNode::target_, and wrapInCast().
visit() [4/44]
void sema::Binder::visit (BinExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 162 of file binder_exprs.cpp.
{
  std::unique_ptr<BoundExpression> left;
  std::unique_ptr<BoundExpression> right;
  bool leftIsNullLiteral =
      dynamic_cast<ConstNull *>(node.left_.get()) != nullptr;
  bool rightIsNullLiteral =
      dynamic_cast<ConstNull *>(node.right_.get()) != nullptr;
  if (leftIsNullLiteral && !rightIsNullLiteral) {
    right = bindExpressionWithExpected(node.right_.get(), nullptr);
    if (!right)
      return;
    left = bindExpressionWithExpected(node.left_.get(), right->type);
    if (!left)
      return;
  } else if (rightIsNullLiteral && !leftIsNullLiteral) {
    left = bindExpressionWithExpected(node.left_.get(), nullptr);
    if (!left)
      return;
    right = bindExpressionWithExpected(node.right_.get(), left->type);
    if (!right)
      return;
  } else {
    node.left_->accept(*this);
    if (expressionStack_.empty())
      return;
    left = std::move(expressionStack_.top());
    expressionStack_.pop();
    node.right_->accept(*this);
    if (expressionStack_.empty())
      return;
    right = std::move(expressionStack_.top());
    expressionStack_.pop();
  }
  expressionStack_.push(
      buildBinaryExpression(std::move(left), node.op_, std::move(right),
                            node.left_->span, node.right_->span));
}
References bindExpressionWithExpected(), buildBinaryExpression(), expressionStack_, BinExpr::left_, BinExpr::op_, and BinExpr::right_.
visit() [5/44]
void sema::Binder::visit (BodyNode & node) override virtual
Reimplemented from Visitor.
Definition at line 41 of file binder_stmts.cpp.
{
  currentBlock_ = std::make_unique<BoundBlock>();
  for (const auto &stmt : node.statements) {
    stmt->accept(*this);
    if (!statementStack_.empty()) {
      currentBlock_->statements.push_back(std::move(statementStack_.top()));
      statementStack_.pop();
    } else if (!expressionStack_.empty()) {
      auto expr = std::move(expressionStack_.top());
      expressionStack_.pop();
      currentBlock_->statements.push_back(
          std::make_unique<BoundExpressionStatement>(std::move(expr)));
    }
  }
  if (node.result) {
    node.result->accept(*this);
    if (!expressionStack_.empty()) {
      currentBlock_->result = std::move(expressionStack_.top());
      expressionStack_.pop();
    }
  }
}
References currentBlock_, expressionStack_, BodyNode::result, BodyNode::statements, and statementStack_.
visit() [6/44]
void sema::Binder::visit (BreakNode & node) override virtual
Reimplemented from Visitor.
Definition at line 516 of file binder_stmts.cpp.
{
  if (loopDepth_ <= 0) {
    error(node.span, "'break' can only be used inside loops.");
    return;
  }
  statementStack_.push(std::make_unique<BoundBreakStatement>());
}
References error(), loopDepth_, Node::span, and statementStack_.
visit() [7/44]
void sema::Binder::visit (CastExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 447 of file binder_exprs.cpp.
{
  node.expr_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto expr = std::move(expressionStack_.top());
  expressionStack_.pop();
  auto targetType = mapType(*node.type_);
  if (!targetType) {
    error(node.type_->span, "Unknown type: " + node.type_->qualifiedName());
    return;
  }
  bool castAllowed = false;
  auto sourceKind = expr->type->getKind();
  auto targetKind = targetType->getKind();
  bool sourceIsChar = sourceKind == zir::TypeKind::Char;
  bool targetIsChar = targetKind == zir::TypeKind::Char;
  if (isNumeric(expr->type) && isNumeric(targetType))
    castAllowed = true;
  else if ((sourceIsChar && targetType->isInteger()) ||
           (expr->type->isInteger() && targetIsChar))
    castAllowed = true;
  else if (sourceKind == zir::TypeKind::Enum && targetType->isInteger())
    castAllowed = true;
  else if ((isPointerType(expr->type) || isNullType(expr->type)) &&
           isPointerType(targetType))
    castAllowed = true;
  else if (isStringType(expr->type) && isPointerType(targetType))
    castAllowed = true;
  else if (isStringType(expr->type) && isStringType(targetType))
    castAllowed = true;
  else if (isPointerType(expr->type) && isStringType(targetType)) {
    auto ptrType = std::static_pointer_cast<zir::PointerType>(expr->type);
    auto baseKind = ptrType->getBaseType()->getKind();
    castAllowed =
        baseKind == zir::TypeKind::Void || baseKind == zir::TypeKind::Char;
  } else if (isPointerType(expr->type) && targetType->isInteger())
    castAllowed = true;
  else if (expr->type->isInteger() && isPointerType(targetType))
    castAllowed = true;
  if (!castAllowed) {
    error(node.span, "Cannot cast from '" + renderTypeForUser(expr->type) +
                         "' to '" + renderTypeForUser(targetType) + "'");
    return;
  }
  expressionStack_.push(
      std::make_unique<BoundCast>(std::move(expr), targetType));
}
References zir::Char, zir::Enum, error(), CastExpr::expr_, expressionStack_, isNullType(), isNumeric(), isPointerType(), sema::isStringType(), mapType(), renderTypeForUser(), Node::span, CastExpr::type_, and zir::Void.
visit() [8/44]
void sema::Binder::visit (ClassDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 867 of file binder_decls.cpp.
{
  auto symbol =
      std::dynamic_pointer_cast<TypeSymbol>(currentScope_->lookup(node.name_));
  if (!symbol || !symbol->isClass || !symbol->genericParameterNames.empty()) {
    return;
  }
  auto classType = std::static_pointer_cast<zir::ClassType>(symbol->type);
  auto &classInfo = classInfos_[classType->getName()];
  currentClassStack_.push_back(classType->getName());
  if (node.baseType_) {
    bool hasOwnCtor = false;
    bool hasOwnDtor = false;
    for (const auto &method : node.methods_) {
      hasOwnCtor = hasOwnCtor || method->name_ == "init";
      hasOwnDtor = hasOwnDtor || method->name_ == "deinit";
    }
    auto baseType = mapType(*node.baseType_);
    if (!baseType || baseType->getKind() != zir::TypeKind::Class) {
      error(node.baseType_->span, "Base type must be a class.");
    } else {
      auto baseClass = std::static_pointer_cast<zir::ClassType>(baseType);
      classType->setBase(baseClass);
      auto baseIt = classInfos_.find(baseClass->getName());
      if (baseIt != classInfos_.end()) {
        if (!hasOwnCtor) {
          classInfo.constructor = baseIt->second.constructor;
        }
        if (!hasOwnDtor) {
          classInfo.destructor = baseIt->second.destructor;
        }
        classInfo.fields = baseIt->second.fields;
        classInfo.methods.insert(baseIt->second.methods.begin(),
                                 baseIt->second.methods.end());
        for (const auto &field : baseClass->getFields()) {
          classType->addField(field.name, field.type, field.visibility);
        }
      }
    }
  }
  for (const auto &field : node.fields_) {
    auto fieldType = mapType(*field->type);
    if (!fieldType) {
      error(field->span, "Unknown type: " + field->type->qualifiedName());
      fieldType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    classType->addField(field->name, fieldType,
                        static_cast<int>(field->visibility_));
    classInfo.fields[field->name] = std::make_shared<VariableSymbol>(
        field->name, fieldType, false, false, field->name,
        modules_[currentModuleId_].info->moduleName, field->visibility_);
  }
  auto boundRecord = std::make_unique<BoundRecordDeclaration>();
  boundRecord->type = classType;
  boundRoot_->records.push_back(std::move(boundRecord));
  for (const auto &method : node.methods_) {
    method->accept(*this);
  }
  currentClassStack_.pop_back();
}
References ClassDecl::baseType_, boundRoot_, zir::Class, classInfos_, currentClassStack_, currentModuleId_, currentScope_, error(), ClassDecl::fields_, mapType(), ClassDecl::methods_, modules_, ClassDecl::name_, visit(), and zir::Void.
visit() [9/44]
void sema::Binder::visit (ConstBool & node) override virtual
Reimplemented from Visitor.
Definition at line 1947 of file binder_exprs.cpp.
{
  expressionStack_.push(std::make_unique<BoundLiteral>(
      node.value_ ? "true" : "false",
      std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool)));
}
References zir::Bool, expressionStack_, ConstBool::value_, and visit().
visit() [10/44]
void sema::Binder::visit (ConstChar & node) override virtual
Reimplemented from Visitor.
Definition at line 431 of file binder_exprs.cpp.
{
  expressionStack_.push(std::make_unique<BoundLiteral>(
      node.value_, std::make_shared<zir::PrimitiveType>(zir::TypeKind::Char)));
}
References zir::Char, expressionStack_, and ConstChar::value_.
visit() [11/44]
void sema::Binder::visit (ConstDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1162 of file binder_decls.cpp.
{
  auto existing = currentScope_->lookupLocal(node.name_);
  std::shared_ptr<VariableSymbol> symbol;
  if (existing) {
    symbol = std::dynamic_pointer_cast<VariableSymbol>(existing);
  }
  std::shared_ptr<zir::Type> type;
  std::unique_ptr<BoundExpression> initializer = nullptr;
  if (node.type_) {
    type = mapType(*node.type_);
    if (!type) {
      error(node.span, "Unknown type: " + node.type_->qualifiedName());
      type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    if (node.initializer_) {
      initializer = bindExpressionWithExpected(node.initializer_.get(), type);
      if (initializer) {
        if (!canConvert(initializer->type, type)) {
          error(node.initializer_->span,
                "Cannot assign expression of type '" +
                    renderTypeForUser(initializer->type) +
                    "' to constant of type '" + renderTypeForUser(type) + "'");
        } else {
          initializer = wrapInCast(std::move(initializer), type);
        }
      }
    } else {
      error(node.span, "Constant '" + node.name_ + "' must be initialized.");
    }
  } else {
    if (!node.initializer_) {
      error(node.span, "Constant '" + node.name_ + "' must be initialized.");
      type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    } else {
      initializer =
          bindExpressionWithExpected(node.initializer_.get(), nullptr);
      if (initializer && initializer->type &&
          initializer->type->getKind() != zir::TypeKind::Void) {
        type = initializer->type;
      } else {
        error(node.initializer_->span, "Cannot infer type of constant '" +
                                           node.name_ +
                                           "' from a void expression.");
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
    }
  }
  if (!symbol) {
    symbol = std::make_shared<VariableSymbol>(
        node.name_, type, true, false,
        mangleName(currentModuleLinkPath(), node.name_),
        modules_[currentModuleId_].info->moduleName, node.visibility_);
    if (!currentScope_->declare(node.name_, symbol)) {
      error(node.span, "Identifier '" + node.name_ + "' already declared.");
    }
  } else if (!node.type_ && type) {
    symbol->type = type;
  }
  if (initializer) {
    symbol->constant_value =
        std::shared_ptr<BoundExpression>(initializer->clone());
  }
  if (semanticInfo_) {
    semanticInfo_->recordSymbol(&node, symbol);
    semanticInfo_->recordType(&node, symbol->type);
  }
  auto boundDecl = std::make_unique<BoundVariableDeclaration>(
      symbol, std::move(initializer));
  if (currentBlock_) {
    statementStack_.push(std::move(boundDecl));
  } else {
    boundRoot_->globals.push_back(std::move(boundDecl));
  }
}
References bindExpressionWithExpected(), boundRoot_, canConvert(), currentBlock_, currentModuleId_, currentModuleLinkPath(), currentScope_, error(), ConstDecl::initializer_, mangleName(), mapType(), modules_, ConstDecl::name_, renderTypeForUser(), semanticInfo_, Node::span, statementStack_, ConstDecl::type_, TopLevel::visibility_, visit(), zir::Void, and wrapInCast().
visit() [12/44]
void sema::Binder::visit (ConstFloat & node) override virtual
Reimplemented from Visitor.
Definition at line 419 of file binder_exprs.cpp.
{
  expressionStack_.push(std::make_unique<BoundLiteral>(
      std::to_string(node.value_),
      std::make_shared<zir::PrimitiveType>(zir::TypeKind::Float)));
}
References expressionStack_, zir::Float, and ConstFloat::value_.
visit() [13/44]
void sema::Binder::visit (ConstId & node) override virtual
Reimplemented from Visitor.
Definition at line 640 of file binder_exprs.cpp.
{
  auto symbol = currentScope_->lookup(node.value_);
  if (!symbol) {
    error(node.span, "Undefined identifier: " + node.value_);
    return;
  }
  if (auto varSymbol = std::dynamic_pointer_cast<VariableSymbol>(symbol)) {
    if (semanticInfo_) {
      semanticInfo_->recordSymbol(&node, varSymbol);
      semanticInfo_->recordType(&node, varSymbol->type);
    }
    expressionStack_.push(std::make_unique<BoundVariableExpression>(varSymbol));
  } else if (auto typeSymbol = std::dynamic_pointer_cast<TypeSymbol>(symbol)) {
    if (semanticInfo_) {
      semanticInfo_->recordSymbol(&node, typeSymbol);
      semanticInfo_->recordType(&node, typeSymbol->type);
    }
    expressionStack_.push(std::make_unique<BoundLiteral>("", typeSymbol->type));
  } else if (auto moduleSymbol =
                 std::dynamic_pointer_cast<ModuleSymbol>(symbol)) {
    expressionStack_.push(std::make_unique<BoundModuleReference>(moduleSymbol));
  } else if (auto overloadSet =
                 std::dynamic_pointer_cast<OverloadSetSymbol>(symbol)) {
    // Function reference — resolve to a function pointer type
    auto expected = currentExpectedExpressionType();
    std::shared_ptr<FunctionSymbol> match;
    if (expected && expected->getKind() == zir::TypeKind::FunctionPointer) {
      const auto &fpType =
          static_cast<const zir::FunctionPointerType &>(*expected);
      for (const auto &overload : overloadSet->overloads) {
        if (overload->parameters.size() == fpType.getParams().size()) {
          bool ok = true;
          for (size_t i = 0; i < fpType.getParams().size(); ++i) {
            if (!canConvert(fpType.getParams()[i],
                            overload->parameters[i]->type)) {
              ok = false;
              break;
            }
          }
          if (ok) {
            match = overload;
            break;
          }
        }
      }
    }
    if (!match && !overloadSet->overloads.empty())
      match = overloadSet->overloads.front();
    if (match) {
      // Build FunctionPointerType from the matched overload's signature
      std::vector<std::shared_ptr<zir::Type>> params;
      for (const auto &p : match->parameters)
        params.push_back(p->type);
      auto fpType = std::make_shared<zir::FunctionPointerType>(
          std::move(params), match->returnType);
      expressionStack_.push(
          std::make_unique<BoundFunctionReference>(match, fpType));
      return;
    }
    error(node.span, "'" + node.value_ + "' is not a variable or type.");
  } else {
    error(node.span, "'" + node.value_ + "' is not a variable or type.");
  }
}
References canConvert(), currentExpectedExpressionType(), currentScope_, error(), expressionStack_, zir::FunctionPointer, semanticInfo_, Node::span, and ConstId::value_.
visit() [14/44]
void sema::Binder::visit (ConstInt & node) override virtual
Reimplemented from Visitor.
Definition at line 414 of file binder_exprs.cpp.
{
  expressionStack_.push(std::make_unique<BoundLiteral>(
      node.value_, std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int)));
}
References expressionStack_, zir::Int, and ConstInt::value_.
visit() [15/44]
void sema::Binder::visit (ConstNull & node) override virtual
Reimplemented from Visitor.
Definition at line 436 of file binder_exprs.cpp.
{
  auto expectedType = currentExpectedExpressionType();
  bool nullIsSafeHere =
      expectedType && expectedType->getKind() == zir::TypeKind::Class;
  if (!nullIsSafeHere) {
  }
  expressionStack_.push(std::make_unique<BoundLiteral>(
      "0", std::make_shared<zir::PrimitiveType>(zir::TypeKind::NullPtr)));
}
References zir::Class, currentExpectedExpressionType(), expressionStack_, and zir::NullPtr.
visit() [16/44]
void sema::Binder::visit (ConstString & node) override virtual
Reimplemented from Visitor.
Definition at line 425 of file binder_exprs.cpp.
{
  expressionStack_.push(std::make_unique<BoundLiteral>(
      node.value_,
      std::make_shared<zir::RecordType>("StringView", "StringView")));
}
References expressionStack_, and ConstString::value_.
visit() [17/44]
void sema::Binder::visit (ContinueNode & node) override virtual
Reimplemented from Visitor.
Definition at line 524 of file binder_stmts.cpp.
{
  if (loopDepth_ <= 0) {
    error(node.span, "'continue' can only be used inside loops.");
    return;
  }
  statementStack_.push(std::make_unique<BoundContinueStatement>());
}
References error(), loopDepth_, Node::span, and statementStack_.
visit() [18/44]
void sema::Binder::visit (EnumDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1299 of file binder_decls.cpp.
{
  auto symbol =
      std::dynamic_pointer_cast<TypeSymbol>(currentScope_->lookup(node.name_));
  if (symbol->type->getKind() == zir::TypeKind::TaggedUnion) {
    auto taggedUnionType =
        std::static_pointer_cast<zir::TaggedUnionType>(symbol->type);
    auto boundTaggedUnion = std::make_unique<BoundTaggedUnionDeclaration>();
    boundTaggedUnion->type = taggedUnionType;
    boundRoot_->taggedUnions.push_back(std::move(boundTaggedUnion));
    return;
  }
  auto enumType = std::static_pointer_cast<zir::EnumType>(symbol->type);
  auto boundEnum = std::make_unique<BoundEnumDeclaration>();
  boundEnum->type = enumType;
  boundRoot_->enums.push_back(std::move(boundEnum));
}
References boundRoot_, currentScope_, EnumDecl::name_, zir::TaggedUnion, and visit().
visit() [19/44]
void sema::Binder::visit (ExtDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1058 of file binder_decls.cpp.
{
  auto symbolIt = declaredFunctionSymbols_.find(&node);
  auto symbol =
      symbolIt == declaredFunctionSymbols_.end() ? nullptr : symbolIt->second;
  if (!symbol) {
    return;
  }
  for (const auto &existing : boundRoot_->externalFunctions) {
    if (existing->symbol->linkName == symbol->linkName) {
      return;
    }
  }
  boundRoot_->externalFunctions.push_back(
      std::make_unique<BoundExternalFunctionDeclaration>(symbol));
}
References boundRoot_, declaredFunctionSymbols_, and visit().
visit() [20/44]
void sema::Binder::visit (FailableHandleExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 577 of file binder_exprs.cpp.
{
  node.expression_->accept(*this);
  if (expressionStack_.empty()) {
    return;
  }
  auto expression = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (!isFailableType(expression->type)) {
    error(node.span, "Operator 'or <name> { ... }' requires failable "
                     "expression type, got '" +
                         renderTypeForUser(expression->type) + "'");
    return;
  }
  auto valueType = failableValueType(expression->type);
  auto errorType = failableErrorType(expression->type);
  pushScope();
  auto errorSymbol = std::make_shared<VariableSymbol>(
      node.errorName_, errorType, false, false, node.errorName_,
      modules_[currentModuleId_].info->moduleName, Visibility::Private);
  if (!currentScope_->declare(node.errorName_, errorSymbol)) {
    error(node.span, "Handler variable '" + node.errorName_ +
                         "' is already declared in this scope.");
  }
  if (semanticInfo_) {
    semanticInfo_->recordSymbol(&node, errorSymbol);
    semanticInfo_->recordType(&node, errorType);
  }
  auto handler = bindBody(node.handler_.get(), false);
  popScope();
  if (handler && !handler->result) {
    handler->result = deriveValueExpressionFromBlock(*handler);
  }
  std::shared_ptr<zir::Type> handlerResultType = valueType;
  if (handler && handler->result) {
    if (!canConvert(handler->result->type, valueType)) {
      error(node.span, "Handler result type '" +
                           renderTypeForUser(handler->result->type) +
                           "' is not compatible with '" +
                           renderTypeForUser(valueType) + "'");
      return;
    }
    handler->result = wrapInCast(std::move(handler->result), valueType);
    handlerResultType = valueType;
  } else if (valueType && valueType->getKind() != zir::TypeKind::Void &&
             (!handler || !blockAlwaysReturns(handler.get()))) {
    error(node.span, "Handler block for 'or " + node.errorName_ +
                         " { ... }' must produce a fallback value of type '" +
                         renderTypeForUser(valueType) + "'.");
    return;
  }
  expressionStack_.push(std::make_unique<BoundFailableHandleExpression>(
      std::move(expression), errorSymbol, std::move(handler), handlerResultType,
      errorType));
}
References bindBody(), sema::blockAlwaysReturns(), canConvert(), currentModuleId_, currentScope_, sema::deriveValueExpressionFromBlock(), error(), FailableHandleExpr::errorName_, FailableHandleExpr::expression_, expressionStack_, sema::failableErrorType(), sema::failableValueType(), FailableHandleExpr::handler_, sema::isFailableType(), modules_, popScope(), Private, pushScope(), renderTypeForUser(), semanticInfo_, Node::span, zir::Void, and wrapInCast().
visit() [21/44]
void sema::Binder::visit (FailNode & node) override virtual
Reimplemented from Visitor.
Definition at line 188 of file binder_stmts.cpp.
{
  if (!currentFunction_ || !isFailableType(currentFunction_->returnType)) {
    error(node.span, "'fail' can only be used inside failable functions.");
    return;
  }
  auto propagatedType = currentFunction_->returnType;
  auto expectedErrorType = failableErrorType(propagatedType);
  auto errExpr =
      bindExpressionWithExpected(node.errorValue_.get(), expectedErrorType);
  if (!errExpr) {
    return;
  }
  if (!canConvert(errExpr->type, expectedErrorType)) {
    error(node.errorValue_->span,
          "Cannot fail with error type '" + renderTypeForUser(errExpr->type) +
              "', expected '" + renderTypeForUser(expectedErrorType) + "'");
    return;
  }
  errExpr = wrapInCast(std::move(errExpr), expectedErrorType);
  statementStack_.push(std::make_unique<BoundFailStatement>(
      std::move(errExpr), propagatedType, expectedErrorType));
}
References bindExpressionWithExpected(), canConvert(), currentFunction_, error(), FailNode::errorValue_, sema::failableErrorType(), sema::isFailableType(), renderTypeForUser(), Node::span, statementStack_, and wrapInCast().
visit() [22/44]
void sema::Binder::visit (FallbackExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 541 of file binder_exprs.cpp.
{
  node.expression_->accept(*this);
  if (expressionStack_.empty()) {
    return;
  }
  auto expression = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (!isFailableType(expression->type)) {
    error(node.span, "Operator 'or' requires failable expression type, got '" +
                         renderTypeForUser(expression->type) + "'");
    return;
  }
  auto valueType = failableValueType(expression->type);
  auto errorType = failableErrorType(expression->type);
  auto fallback = bindExpressionWithExpected(node.fallback_.get(), valueType);
  if (!fallback) {
    return;
  }
  if (!canConvert(fallback->type, valueType)) {
    error(node.fallback_->span, "Fallback expression type '" +
                                    renderTypeForUser(fallback->type) +
                                    "' is not compatible with '" +
                                    renderTypeForUser(valueType) + "'");
    return;
  }
  fallback = wrapInCast(std::move(fallback), valueType);
  expressionStack_.push(std::make_unique<BoundFallbackExpression>(
      std::move(expression), std::move(fallback), valueType, errorType));
}
References bindExpressionWithExpected(), canConvert(), error(), FallbackExpr::expression_, expressionStack_, sema::failableErrorType(), sema::failableValueType(), FallbackExpr::fallback_, sema::isFailableType(), renderTypeForUser(), Node::span, and wrapInCast().
visit() [23/44]
void sema::Binder::visit (ForInNode & node) override virtual
Reimplemented from Visitor.
Definition at line 352 of file binder_stmts.cpp.
{
  const std::string moduleName =
      (modules_.count(currentModuleId_) && modules_[currentModuleId_].info)
          ? modules_[currentModuleId_].info->moduleName
          : "";
  pushScope();
  node.iterable_->accept(*this);
  if (expressionStack_.empty()) {
    popScope();
    return;
  }
  auto iterableValue = std::move(expressionStack_.top());
  expressionStack_.pop();
  auto intType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
  auto iterableName = makeSyntheticLoopName("iter");
  auto iterableSymbol = std::make_shared<VariableSymbol>(
      iterableName, iterableValue->type, false, false, iterableName, moduleName,
      Visibility::Private);
  currentScope_->declare(iterableName, iterableSymbol);
  auto indexName = makeSyntheticLoopName("idx");
  auto indexSymbol = std::make_shared<VariableSymbol>(
      indexName, intType, false, false, indexName, moduleName,
      Visibility::Private);
  currentScope_->declare(indexName, indexSymbol);
  auto initBlock = std::make_unique<BoundBlock>();
  initBlock->statements.push_back(std::make_unique<BoundVariableDeclaration>(
      iterableSymbol, std::move(iterableValue)));
  initBlock->statements.push_back(std::make_unique<BoundVariableDeclaration>(
      indexSymbol, std::make_unique<BoundLiteral>("0", intType)));
  auto makeIdExpr = [](const std::string &name) {
    return std::make_unique<ConstId>(name);
  };
  std::unique_ptr<ExpressionNode> conditionAst = nullptr;
  std::unique_ptr<ExpressionNode> elementAst = nullptr;
  auto iterableType = iterableSymbol->type;
  std::string accessName = iterableName;
  if (iterableType->getKind() == zir::TypeKind::Array) {
    auto arr = std::static_pointer_cast<zir::ArrayType>(iterableType);
    auto sliceName = makeSyntheticLoopName("slice");
    auto sliceType = makeVariadicViewType(arr->getBaseType());
    auto sliceSymbol = std::make_shared<VariableSymbol>(
        sliceName, sliceType, false, false, sliceName, moduleName,
        Visibility::Private);
    currentScope_->declare(sliceName, sliceSymbol);
    initBlock->statements.push_back(std::make_unique<BoundVariableDeclaration>(
        sliceSymbol,
        std::make_unique<BoundCast>(
            std::make_unique<BoundVariableExpression>(iterableSymbol),
            sliceType)));
    accessName = sliceName;
    conditionAst = std::make_unique<BinExpr>(
        makeIdExpr(indexName), "<",
        std::make_unique<MemberAccessNode>(makeIdExpr(accessName), "len"));
    elementAst = std::make_unique<IndexAccessNode>(makeIdExpr(accessName),
                                                   makeIdExpr(indexName));
  } else if (isVariadicViewType(iterableType)) {
    conditionAst = std::make_unique<BinExpr>(
        makeIdExpr(indexName), "<",
        std::make_unique<MemberAccessNode>(makeIdExpr(accessName), "len"));
    elementAst = std::make_unique<IndexAccessNode>(makeIdExpr(accessName),
                                                   makeIdExpr(indexName));
  } else if (iterableType->getKind() == zir::TypeKind::Class) {
    auto lenCall = std::make_unique<FunCall>();
    lenCall->callee_ =
        std::make_unique<MemberAccessNode>(makeIdExpr(accessName), "len");
    conditionAst = std::make_unique<BinExpr>(makeIdExpr(indexName), "<",
                                             std::move(lenCall));
    auto atCall = std::make_unique<FunCall>();
    atCall->callee_ =
        std::make_unique<MemberAccessNode>(makeIdExpr(accessName), "at");
    atCall->params_.push_back(
        std::make_unique<Argument>("", makeIdExpr(indexName), false, false));
    elementAst = std::move(atCall);
  } else {
    error(node.iterable_->span,
          "Type '" + renderTypeForUser(iterableType) +
              "' is not iterable in for-in. Expected array, slice, or class "
              "with 'len()' and 'at(Int)'.");
    popScope();
    return;
  }
  conditionAst->accept(*this);
  if (expressionStack_.empty()) {
    popScope();
    return;
  }
  auto condition = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (condition->type->getKind() != zir::TypeKind::Bool) {
    error(node.span, "For-in condition must be Bool, got '" +
                         renderTypeForUser(condition->type) + "'");
  }
  elementAst->accept(*this);
  if (expressionStack_.empty()) {
    popScope();
    return;
  }
  auto elementValue = std::move(expressionStack_.top());
  expressionStack_.pop();
  auto increment = std::make_unique<BoundAssignment>(
      std::make_unique<BoundVariableExpression>(indexSymbol),
      std::make_unique<BoundBinaryExpression>(
          std::make_unique<BoundVariableExpression>(indexSymbol), "+",
          std::make_unique<BoundLiteral>("1", intType), intType));
  pushScope();
  auto itemSymbol = std::make_shared<VariableSymbol>(
      node.itemName_, elementValue->type, false, false, node.itemName_,
      moduleName, Visibility::Private);
  if (!currentScope_->declare(node.itemName_, itemSymbol)) {
    error(node.span, "Variable '" + node.itemName_ + "' already declared.");
  }
  if (semanticInfo_) {
    semanticInfo_->recordSymbol(&node, itemSymbol);
    semanticInfo_->recordType(&node, itemSymbol->type);
  }
  std::shared_ptr<VariableSymbol> indexUserSymbol = nullptr;
  if (!node.indexName_.empty()) {
    indexUserSymbol = std::make_shared<VariableSymbol>(
        node.indexName_, intType, false, false, node.indexName_, moduleName,
        Visibility::Private);
    if (!currentScope_->declare(node.indexName_, indexUserSymbol)) {
      error(node.span, "Variable '" + node.indexName_ + "' already declared.");
    }
  }
  ++loopDepth_;
  auto body = bindBody(node.body_.get(), false);
  --loopDepth_;
  body->statements.insert(body->statements.begin(),
                          std::make_unique<BoundVariableDeclaration>(
                              itemSymbol, std::move(elementValue)));
  if (indexUserSymbol) {
    body->statements.insert(
        body->statements.begin(),
        std::make_unique<BoundVariableDeclaration>(
            indexUserSymbol,
            std::make_unique<BoundVariableExpression>(indexSymbol)));
  }
  popScope();
  popScope();
  statementStack_.push(std::make_unique<BoundForStatement>(
      std::move(initBlock), std::move(condition), std::move(increment),
      std::move(body)));
}
References zir::Array, bindBody(), ForInNode::body_, zir::Bool, zir::Class, currentModuleId_, currentScope_, error(), expressionStack_, ForInNode::indexName_, zir::Int, sema::isVariadicViewType(), ForInNode::itemName_, ForInNode::iterable_, loopDepth_, makeSyntheticLoopName(), sema::makeVariadicViewType(), modules_, popScope(), Private, pushScope(), renderTypeForUser(), semanticInfo_, Node::span, and statementStack_.
visit() [24/44]
void sema::Binder::visit (ForNode & node) override virtual
Reimplemented from Visitor.
Definition at line 303 of file binder_stmts.cpp.
{
  pushScope();
  node.initializer_->accept(*this);
  std::unique_ptr<BoundStatement> initializer = nullptr;
  if (!statementStack_.empty()) {
    initializer = std::move(statementStack_.top());
    statementStack_.pop();
  }
  node.condition_->accept(*this);
  if (expressionStack_.empty()) {
    popScope();
    return;
  }
  auto condition = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (condition->type->getKind() != zir::TypeKind::Bool) {
    error(node.condition_->span, "For condition must be Bool, got '" +
                                     renderTypeForUser(condition->type) + "'");
  }
  auto incrementTargetId =
      dynamic_cast<ConstId *>(node.increment_->target_.get());
  if (!incrementTargetId ||
      incrementTargetId->value_ != node.initializer_->name_) {
    error(node.increment_->target_->span,
          "For increment must assign to loop variable '" +
              node.initializer_->name_ + "'.");
  }
  node.increment_->accept(*this);
  std::unique_ptr<BoundStatement> increment = nullptr;
  if (!statementStack_.empty()) {
    increment = std::move(statementStack_.top());
    statementStack_.pop();
  }
  ++loopDepth_;
  auto body = bindBody(node.body_.get(), true);
  --loopDepth_;
  popScope();
  statementStack_.push(std::make_unique<BoundForStatement>(
      std::move(initializer), std::move(condition), std::move(increment),
      std::move(body)));
}
References bindBody(), ForNode::body_, zir::Bool, ForNode::condition_, error(), expressionStack_, ForNode::increment_, ForNode::initializer_, loopDepth_, popScope(), pushScope(), renderTypeForUser(), and statementStack_.
visit() [25/44]
void sema::Binder::visit (FunCall & node) override virtual
Reimplemented from Visitor.
Definition at line 962 of file binder_exprs.cpp.
{
  if (bindSizeOfBuiltinCall(node)) {
    return;
  }
  if (bindWeakBuiltinCall(node)) {
    return;
  }
  if (auto member = dynamic_cast<MemberAccessNode *>(node.callee_.get())) {
    member->left_->accept(*this);
    if (expressionStack_.empty()) {
      return;
    }
    auto selfExpr = std::move(expressionStack_.top());
    expressionStack_.pop();
    if (selfExpr->type->getKind() == zir::TypeKind::TaggedUnion &&
        dynamic_cast<BoundLiteral *>(selfExpr.get())) {
      auto taggedUnionType =
          std::static_pointer_cast<zir::TaggedUnionType>(selfExpr->type);
      auto variant = taggedUnionType->findVariant(member->member_);
      if (!variant) {
        error(node.span, "Enum '" + taggedUnionType->getName() +
                             "' has no variant '" + member->member_ + "'.");
        return;
      }
      if (variant->payloadType) {
        if (node.params_.size() != 1) {
          error(node.span, "Enum variant '" + member->member_ +
                               "' expects one payload argument.");
          return;
        }
        if (!node.params_[0]->name.empty() || node.params_[0]->isRef ||
            node.params_[0]->isSpread) {
          error(node.params_[0]->value->span,
                "Enum payload arguments must be positional values.");
          return;
        }
        auto payload = bindExpressionWithExpected(node.params_[0]->value.get(),
                                                  variant->payloadType);
        if (!payload) {
          return;
        }
        if (!canConvert(payload->type, variant->payloadType)) {
          error(node.params_[0]->value->span,
                "Cannot convert enum payload from '" +
                    renderTypeForUser(payload->type) + "' to '" +
                    renderTypeForUser(variant->payloadType) + "'");
          return;
        }
        payload = wrapInCast(std::move(payload), variant->payloadType);
        expressionStack_.push(std::make_unique<BoundTaggedUnionLiteral>(
            taggedUnionType, variant->name, variant->tag, std::move(payload)));
        return;
      }
      if (!node.params_.empty()) {
        error(node.span, "Enum variant '" + member->member_ +
                             "' does not take a payload argument.");
        return;
      }
      expressionStack_.push(std::make_unique<BoundTaggedUnionLiteral>(
          taggedUnionType, variant->name, variant->tag, nullptr));
      return;
    }
    if (selfExpr->type->getKind() != zir::TypeKind::Class) {
      // Not a class method call. Fall through to the normal qualified
      // function/module call resolution path below.
    } else {
      auto classType = std::static_pointer_cast<zir::ClassType>(selfExpr->type);
      if (classType->isWeak()) {
        error(node.span,
              "Weak references cannot be used to call methods directly.");
        return;
      }
      auto infoIt = classInfos_.find(classType->getName());
      if (infoIt == classInfos_.end()) {
        error(node.span, "Unknown class type: " + classType->getName());
        return;
      }
      auto methodIt = infoIt->second.methods.find(member->member_);
      if (methodIt == infoIt->second.methods.end()) {
        error(node.span, "Class '" + classType->getName() +
                             "' has no method '" + member->member_ + "'.");
        return;
      }
      auto candidates = collectOverloads(methodIt->second);
      if (candidates.empty()) {
        error(node.span, "'" + member->member_ + "' is not a method.");
        return;
      }
      std::vector<std::unique_ptr<BoundExpression>> rawArgs;
      rawArgs.reserve(node.params_.size());
      for (size_t i = 0; i < node.params_.size(); ++i) {
        auto arg =
            bindExpressionWithExpected(node.params_[i]->value.get(), nullptr);
        if (!arg) {
          return;
        }
        rawArgs.push_back(std::move(arg));
      }
      struct MethodCandidate {
        std::shared_ptr<FunctionSymbol> symbol;
        std::vector<int> cost;
      };
      const bool calledOnType =
          dynamic_cast<BoundLiteral *>(selfExpr.get()) != nullptr;
      std::vector<MethodCandidate> matches;
      bool inaccessibleMatch = false;
      bool unsafeMatch = false;
      for (auto funcSymbol : candidates) {
        if (!funcSymbol) {
          continue;
        }
        if (funcSymbol->isMethod && calledOnType) {
          continue;
        }
        bool methodAllowed =
            funcSymbol->visibility == Visibility::Public ||
            (!currentClassStack_.empty() &&
             currentClassStack_.back() == classType->getName()) ||
            (funcSymbol->visibility == Visibility::Protected &&
             !currentClassStack_.empty());
        if (!methodAllowed) {
          inaccessibleMatch = true;
          continue;
        }
        if (funcSymbol->isUnsafe && !isUnsafeActive()) {
          unsafeMatch = true;
          continue;
        }
        std::vector<std::unique_ptr<BoundExpression>> inferenceArgs;
        if (funcSymbol->isMethod) {
          inferenceArgs.push_back(selfExpr->clone());
        }
        for (const auto &rawArg : rawArgs) {
          inferenceArgs.push_back(rawArg->clone());
        }
        std::unordered_map<std::string, std::shared_ptr<zir::Type>>
            genericBindings;
        if (!funcSymbol->genericParameterNames.empty()) {
          genericBindings =
              buildGenericBindings(*funcSymbol, inferenceArgs,
                                   node.genericArgs_, node.span, nullptr);
          if (genericBindings.empty()) {
            continue;
          }
          funcSymbol = ensureGenericFunctionInstantiation(
              funcSymbol, orderedGenericBindings(genericBindings), node.span);
          if (!funcSymbol) {
            continue;
          }
        } else if (!node.genericArgs_.empty()) {
          continue;
        }
        size_t paramOffset = funcSymbol->isMethod ? 1 : 0;
        if (node.params_.size() + paramOffset !=
            funcSymbol->parameters.size()) {
          continue;
        }
        MethodCandidate match;
        match.symbol = funcSymbol;
        bool failed = false;
        for (size_t i = 0; i < rawArgs.size(); ++i) {
          auto expectedType = funcSymbol->parameters[i + paramOffset]->type;
          if (!canConvert(rawArgs[i]->type, expectedType)) {
            failed = true;
            break;
          }
          match.cost.push_back(conversionCost(rawArgs[i]->type, expectedType));
        }
        if (!failed) {
          matches.push_back(std::move(match));
        }
      }
      if (matches.empty()) {
        if (inaccessibleMatch) {
          error(node.span,
                "Method '" + member->member_ + "' is not accessible.");
        } else if (unsafeMatch) {
          requireUnsafeContext(node.span, "unsafe function calls");
        } else {
          error(node.span,
                "No matching overload for method '" + member->member_ + "'.");
        }
        return;
      }
      std::sort(matches.begin(), matches.end(),
                [](const MethodCandidate &lhs, const MethodCandidate &rhs) {
                  return lhs.cost < rhs.cost;
                });
      if (matches.size() > 1 && matches[0].cost == matches[1].cost) {
        error(node.span,
              "Ambiguous overload for method '" + member->member_ + "'.");
        return;
      }
      auto funcSymbol = matches.front().symbol;
      std::vector<std::unique_ptr<BoundExpression>> args;
      std::vector<bool> argIsRef;
      if (funcSymbol->isMethod) {
        args.push_back(std::move(selfExpr));
        argIsRef.push_back(false);
      }
      size_t paramOffset = funcSymbol->isMethod ? 1 : 0;
      for (size_t i = 0; i < node.params_.size(); ++i) {
        auto arg = rawArgs[i]->clone();
        auto expectedType = funcSymbol->parameters[i + paramOffset]->type;
        arg = wrapInCast(std::move(arg), expectedType);
        args.push_back(std::move(arg));
        argIsRef.push_back(node.params_[i]->isRef);
      }
      expressionStack_.push(std::make_unique<BoundFunctionCall>(
          funcSymbol, std::move(args), std::move(argIsRef)));
      return;
    }
  }
  std::vector<std::string> calleeParts;
  if (!node.callee_ || !extractQualifiedPath(node.callee_.get(), calleeParts)) {
    // Try indirect call through function pointer
    if (node.callee_) {
      node.callee_->accept(*this);
      if (!expressionStack_.empty()) {
        auto calleeExpr = std::move(expressionStack_.top());
        expressionStack_.pop();
        if (calleeExpr->type &&
            calleeExpr->type->getKind() == zir::TypeKind::FunctionPointer) {
          const auto &fpType =
              static_cast<const zir::FunctionPointerType &>(*calleeExpr->type);
          if (node.params_.size() != fpType.getParams().size()) {
            error(node.span, "Function pointer call argument count mismatch.");
            return;
          }
          std::vector<std::unique_ptr<BoundExpression>> args;
          for (size_t i = 0; i < node.params_.size(); ++i) {
            auto arg = bindExpressionWithExpected(node.params_[i]->value.get(),
                                                  fpType.getParams()[i]);
            if (!arg)
              return;
            args.push_back(std::move(arg));
          }
          expressionStack_.push(std::make_unique<BoundIndirectCall>(
              std::move(calleeExpr), std::move(args), fpType.getReturnType()));
          return;
        }
      }
    }
    error(node.span, "Only direct function calls are supported.");
    return;
  }
  auto symbol =
      resolveQualifiedSymbol(calleeParts, node.span, SymbolKind::Function);
  if (!symbol) {
    // Check if it's a variable holding a function pointer
    auto varSym =
        resolveQualifiedSymbol(calleeParts, node.span, SymbolKind::Variable);
    if (varSym && varSym->getKind() == SymbolKind::Variable) {
      auto varSymbol = std::static_pointer_cast<VariableSymbol>(varSym);
      if (varSymbol->type &&
          varSymbol->type->getKind() == zir::TypeKind::FunctionPointer) {
        const auto &fpType =
            static_cast<const zir::FunctionPointerType &>(*varSymbol->type);
        if (node.params_.size() != fpType.getParams().size()) {
          error(node.span, "Function pointer call argument count mismatch.");
          return;
        }
        std::vector<std::unique_ptr<BoundExpression>> args;
        for (size_t i = 0; i < node.params_.size(); ++i) {
          auto arg = bindExpressionWithExpected(node.params_[i]->value.get(),
                                                fpType.getParams()[i]);
          if (!arg)
            return;
          args.push_back(std::move(arg));
        }
        auto calleeExpr = std::make_unique<BoundVariableExpression>(varSymbol);
        expressionStack_.push(std::make_unique<BoundIndirectCall>(
            std::move(calleeExpr), std::move(args), fpType.getReturnType()));
        return;
      }
    }
    return;
  }
  auto candidates = collectOverloads(symbol);
  if (candidates.empty()) {
    error(node.span, "'" + calleeParts.back() + "' is not a function.");
    return;
  }
  bool seenSpreadArg = false;
  std::vector<std::unique_ptr<BoundExpression>> rawArgs;
  std::vector<bool> rawArgIsRef;
  std::vector<bool> rawArgIsSpread;
  std::vector<std::string> rawArgNames;
  for (size_t i = 0; i < node.params_.size(); ++i) {
    if (seenSpreadArg) {
      error(node.params_[i]->value->span,
            "Spread argument must be the last argument in a function call.");
      return;
    }
    auto arg =
        bindExpressionWithExpected(node.params_[i]->value.get(), nullptr);
    if (!arg)
      return;
    rawArgNames.push_back(node.params_[i]->name);
    rawArgIsRef.push_back(node.params_[i]->isRef);
    rawArgIsSpread.push_back(node.params_[i]->isSpread);
    if (node.params_[i]->isSpread) {
      seenSpreadArg = true;
    }
    rawArgs.push_back(std::move(arg));
  }
  struct CandidateMatch {
    std::shared_ptr<FunctionSymbol> symbol;
    std::vector<std::unique_ptr<BoundExpression>> arguments;
    std::vector<bool> argumentIsRef;
    std::unique_ptr<BoundExpression> variadicPack;
    std::vector<int> cost;
    bool usedExtraArguments = false;
    int returnCost = 0;
    std::vector<std::string> notes;
  };
  auto compareCost = [](const CandidateMatch &lhs, const CandidateMatch &rhs) {
    if (lhs.cost != rhs.cost) {
      return lhs.cost < rhs.cost;
    }
    if (lhs.returnCost != rhs.returnCost) {
      return lhs.returnCost < rhs.returnCost;
    }
    if (lhs.usedExtraArguments != rhs.usedExtraArguments) {
      return !lhs.usedExtraArguments && rhs.usedExtraArguments;
    }
    if (lhs.symbol->acceptsExtraArguments() !=
        rhs.symbol->acceptsExtraArguments()) {
      return !lhs.symbol->acceptsExtraArguments() &&
             rhs.symbol->acceptsExtraArguments();
    }
    return false;
  };
  std::vector<CandidateMatch> matches;
  std::shared_ptr<FunctionSymbol> blockedUnsafeMatch = nullptr;
  std::vector<std::string> rejectionNotes;
  auto expectedReturnType = currentExpectedExpressionType();
  for (const auto &funcSymbol : candidates) {
    if (!funcSymbol) {
      continue;
    }
    size_t fixedParamCount = funcSymbol->fixedParameterCount();
    bool hasExplicitTypeArgs = !node.genericArgs_.empty();
    if (hasExplicitTypeArgs &&
        node.genericArgs_.size() > funcSymbol->genericParameterNames.size()) {
      rejectionNotes.push_back("'" + renderFunctionSignature(*funcSymbol) +
                               "': explicit generic argument count mismatch");
      continue;
    }
    if (!hasExplicitTypeArgs && !funcSymbol->genericParameterNames.empty()) {
      // inference is allowed; no early rejection
    }
    if (!funcSymbol->acceptsExtraArguments() &&
        node.params_.size() != funcSymbol->parameters.size()) {
      rejectionNotes.push_back("'" + renderFunctionSignature(*funcSymbol) +
                               "': wrong argument count");
      continue;
    }
    if (funcSymbol->acceptsExtraArguments() &&
        node.params_.size() < fixedParamCount) {
      rejectionNotes.push_back("'" + renderFunctionSignature(*funcSymbol) +
                               "': too few arguments");
      continue;
    }
    CandidateMatch match;
    match.symbol = funcSymbol;
    match.arguments.resize(fixedParamCount);
    match.argumentIsRef.resize(fixedParamCount, false);
    std::string genericBindingFailure;
    auto genericBindings =
        buildGenericBindings(*funcSymbol, rawArgs, node.genericArgs_, node.span,
                             &genericBindingFailure);
    if (!funcSymbol->genericParameterNames.empty() && genericBindings.empty()) {
      rejectionNotes.push_back(
          "'" + renderFunctionSignature(*funcSymbol) + "': " +
          (genericBindingFailure.empty() ? "generic type binding failed"
                                         : genericBindingFailure));
      continue;
    }
    bool failed = false;
    std::string failureReason;
    auto variadicParam = funcSymbol->variadicParameter();
    std::vector<int> positionalToParameter(rawArgs.size(), -1);
    std::vector<bool> parameterAssigned(funcSymbol->parameters.size(), false);
    bool seenNamedArgument = false;
    for (size_t i = 0, positionalIndex = 0; i < rawArgs.size(); ++i) {
      const bool isSpread = rawArgIsSpread[i];
      const bool isNamed = !rawArgNames[i].empty();
      if (isSpread) {
        if (isNamed) {
          failed = true;
          failureReason = "named spread arguments are not supported";
          break;
        }
        positionalToParameter[i] = static_cast<int>(fixedParamCount);
        continue;
      }
      if (isNamed) {
        seenNamedArgument = true;
        bool found = false;
        for (size_t paramIndex = 0; paramIndex < fixedParamCount;
             ++paramIndex) {
          if (funcSymbol->parameters[paramIndex]->name != rawArgNames[i]) {
            continue;
          }
          if (parameterAssigned[paramIndex]) {
            failed = true;
            failureReason =
                "parameter '" + rawArgNames[i] + "' provided more than once";
            break;
          }
          positionalToParameter[i] = static_cast<int>(paramIndex);
          parameterAssigned[paramIndex] = true;
          found = true;
          break;
        }
        if (failed) {
          break;
        }
        if (!found) {
          failed = true;
          failureReason = "unknown named argument '" + rawArgNames[i] + "'";
          break;
        }
        continue;
      }
      if (seenNamedArgument) {
        failed = true;
        failureReason = "positional arguments cannot follow named arguments";
        break;
      }
      while (positionalIndex < fixedParamCount &&
             parameterAssigned[positionalIndex]) {
        ++positionalIndex;
      }
      if (positionalIndex < fixedParamCount) {
        positionalToParameter[i] = static_cast<int>(positionalIndex);
        parameterAssigned[positionalIndex] = true;
        ++positionalIndex;
      } else {
        positionalToParameter[i] = static_cast<int>(fixedParamCount);
      }
    }
    if (!failed) {
      for (size_t paramIndex = 0; paramIndex < fixedParamCount; ++paramIndex) {
        if (!parameterAssigned[paramIndex]) {
          failed = true;
          failureReason = "missing argument for parameter '" +
                          funcSymbol->parameters[paramIndex]->name + "'";
          break;
        }
      }
    }
    for (size_t i = 0; i < rawArgs.size(); ++i) {
      auto arg = rawArgs[i]->clone();
      bool argIsRef = rawArgIsRef[i];
      bool argIsSpread = rawArgIsSpread[i];
      int parameterIndex = positionalToParameter[i];
      if (failed) {
        break;
      }
      if (argIsSpread) {
        if (parameterIndex < static_cast<int>(fixedParamCount) || argIsRef ||
            !funcSymbol->hasVariadicParameter()) {
          failed = true;
          failureReason =
              "spread arguments can only target a Zap variadic parameter";
          break;
        }
        if (!variadicParam || !variadicParam->variadic_element_type) {
          failed = true;
          failureReason = "internal error: missing variadic parameter type";
          break;
        }
        auto expectedViewType =
            makeVariadicViewType(variadicParam->variadic_element_type);
        if (arg->type && arg->type->getKind() == zir::TypeKind::Array) {
          if (!canConvert(arg->type, expectedViewType)) {
            failed = true;
            failureReason =
                "spread argument type does not match variadic parameter";
            break;
          }
          arg = wrapInCast(std::move(arg), expectedViewType);
        } else if (!arg->type || !isVariadicViewType(arg->type) ||
                   !canConvert(arg->type, expectedViewType)) {
          failed = true;
          failureReason =
              "spread argument type does not match variadic parameter";
          break;
        }
        match.variadicPack = std::move(arg);
        match.usedExtraArguments = true;
        match.notes.push_back("spread -> variadic pack");
        continue;
      }
      if (parameterIndex >= 0 &&
          parameterIndex < static_cast<int>(fixedParamCount)) {
        auto expectedType = funcSymbol->parameters[parameterIndex]->type;
        if (!genericBindings.empty()) {
          expectedType = substituteGenericType(expectedType, genericBindings);
        }
        const auto &parameter = funcSymbol->parameters[parameterIndex];
        if (argIsRef != parameter->is_ref) {
          failed = true;
          failureReason = "argument for parameter '" + parameter->name +
                          "' has mismatched ref-ness";
          break;
        }
        if (argIsRef) {
          auto varExpr = dynamic_cast<BoundVariableExpression *>(arg.get());
          if (!varExpr || arg->type->toString() != expectedType->toString()) {
            failed = true;
            failureReason = "ref argument for parameter '" + parameter->name +
                            "' must exactly match type '" +
                            renderTypeForUser(expectedType) + "'";
            break;
          }
          match.cost.push_back(0);
          match.notes.push_back("param " + parameter->name +
                                ": exact ref match");
        } else if (!canConvert(arg->type, expectedType)) {
          failed = true;
          failureReason = "argument for parameter '" + parameter->name +
                          "' is not convertible from '" +
                          renderTypeForUser(arg->type) + "' to '" +
                          renderTypeForUser(expectedType) + "'";
          break;
        } else {
          int cost = conversionCost(arg->type, expectedType);
          if (cost >= 1000) {
            failed = true;
            failureReason = "argument for parameter '" + parameter->name +
                            "' is not convertible from '" +
                            renderTypeForUser(arg->type) + "' to '" +
                            renderTypeForUser(expectedType) + "'";
            break;
          }
          match.cost.push_back(cost);
          match.notes.push_back("param " + parameter->name + ": " +
                                describeConversion(arg->type, expectedType));
          arg = wrapInCast(std::move(arg), expectedType);
        }
        match.argumentIsRef[parameterIndex] = argIsRef;
        match.arguments[parameterIndex] = std::move(arg);
      } else if (funcSymbol->hasVariadicParameter()) {
        if (argIsRef) {
          failed = true;
          failureReason = "variadic arguments cannot be passed by ref";
          break;
        }
        auto expectedType = variadicParam->variadic_element_type;
        if (!genericBindings.empty()) {
          expectedType = substituteGenericType(expectedType, genericBindings);
        }
        if (!canConvert(arg->type, expectedType)) {
          failed = true;
          failureReason = "variadic argument is not convertible from '" +
                          renderTypeForUser(arg->type) + "' to '" +
                          renderTypeForUser(expectedType) + "'";
          break;
        }
        int cost = conversionCost(arg->type, expectedType);
        match.cost.push_back(cost);
        match.usedExtraArguments = true;
        match.notes.push_back("variadic: " +
                              describeConversion(arg->type, expectedType));
        arg = wrapInCast(std::move(arg), expectedType);
        match.argumentIsRef.push_back(false);
        match.arguments.push_back(std::move(arg));
      } else if (funcSymbol->isCVariadic) {
        if (argIsRef) {
          failed = true;
          failureReason = "C variadic arguments cannot be passed by ref";
          break;
        }
        auto promotedType = getCVariadicArgumentType(arg->type);
        if (!promotedType) {
          failed = true;
          failureReason = "type '" + renderTypeForUser(arg->type) +
                          "' is not supported in C variadic arguments";
          break;
        }
        int cost = conversionCost(arg->type, promotedType);
        match.cost.push_back(cost);
        match.usedExtraArguments = true;
        match.notes.push_back("c variadic: " +
                              describeConversion(arg->type, promotedType));
        arg = wrapInCast(std::move(arg), promotedType);
        match.argumentIsRef.push_back(false);
        match.arguments.push_back(std::move(arg));
      } else {
        failed = true;
        failureReason = "too many arguments";
        break;
      }
    }
    if (failed) {
      rejectionNotes.push_back("'" + renderFunctionSignature(*funcSymbol) +
                               "': " + failureReason);
      continue;
    }
    if (expectedReturnType) {
      if (funcSymbol->returnType->toString() ==
          expectedReturnType->toString()) {
        match.returnCost = 0;
        match.notes.push_back("return: exact match");
      } else if (canConvert(funcSymbol->returnType, expectedReturnType)) {
        match.returnCost =
            conversionCost(funcSymbol->returnType, expectedReturnType);
        match.notes.push_back(
            "return: " +
            describeConversion(funcSymbol->returnType, expectedReturnType));
      } else {
        match.returnCost = 50;
        match.notes.push_back("return: incompatible with expected " +
                              renderTypeForUser(expectedReturnType));
      }
    }
    std::shared_ptr<FunctionSymbol> resolvedSymbol = funcSymbol;
    if (!funcSymbol->genericParameterNames.empty()) {
      resolvedSymbol = ensureGenericFunctionInstantiation(
          funcSymbol, orderedGenericBindings(genericBindings), node.span);
      if (!resolvedSymbol) {
        rejectionNotes.push_back("'" + renderFunctionSignature(*funcSymbol) +
                                 "': failed to instantiate generic function");
        continue;
      }
      std::vector<std::unique_ptr<BoundExpression>> remappedArgs;
      std::vector<bool> remappedRef;
      remappedArgs.reserve(match.arguments.size());
      remappedRef.reserve(match.argumentIsRef.size());
      for (size_t i = 0; i < match.arguments.size(); ++i) {
        auto argClone =
            match.arguments[i] ? match.arguments[i]->clone() : nullptr;
        if (i < resolvedSymbol->parameters.size() && argClone) {
          auto expected = resolvedSymbol->parameters[i]->type;
          if (!resolvedSymbol->parameters[i]->is_ref) {
            argClone = wrapInCast(std::move(argClone), expected);
          }
        }
        remappedArgs.push_back(std::move(argClone));
        remappedRef.push_back(
            i < match.argumentIsRef.size() ? match.argumentIsRef[i] : false);
      }
      match.arguments = std::move(remappedArgs);
      match.argumentIsRef = std::move(remappedRef);
      match.symbol = resolvedSymbol;
    }
    if (resolvedSymbol->isUnsafe && !isUnsafeActive()) {
      blockedUnsafeMatch = resolvedSymbol;
      rejectionNotes.push_back("'" + renderFunctionSignature(*resolvedSymbol) +
                               "': requires unsafe context");
      continue;
    }
    matches.push_back(std::move(match));
  }
  if (matches.empty()) {
    if (blockedUnsafeMatch) {
      requireUnsafeContext(node.span, "unsafe function calls");
      return;
    }
    error(
        node.callee_->span,
        "No matching overload for function '" + calleeParts.back() + "'. " +
            (rejectionNotes.empty() ? std::string() : ("Candidates: " + [&]() {
              std::string details;
              for (size_t i = 0; i < rejectionNotes.size(); ++i) {
                if (i != 0) {
                  details += "; ";
                }
                details += rejectionNotes[i];
              }
              return details;
            }())));
    return;
  }
  size_t bestIndex = 0;
  for (size_t i = 1; i < matches.size(); ++i) {
    if (compareCost(matches[i], matches[bestIndex])) {
      bestIndex = i;
    }
  }
  std::vector<size_t> ambiguous = {bestIndex};
  for (size_t i = 0; i < matches.size(); ++i) {
    if (i == bestIndex) {
      continue;
    }
    if (!compareCost(matches[i], matches[bestIndex]) &&
        !compareCost(matches[bestIndex], matches[i])) {
      ambiguous.push_back(i);
    }
  }
  if (ambiguous.size() > 1) {
    std::string message =
        "Call to function '" + calleeParts.back() + "' is ambiguous between ";
    for (size_t i = 0; i < ambiguous.size(); ++i) {
      if (i != 0) {
        message += i + 1 == ambiguous.size() ? " and " : ", ";
      }
      message +=
          "'" + renderFunctionSignature(*matches[ambiguous[i]].symbol) + "'";
    }
    message += ".";
    if (expectedReturnType) {
      message +=
          " Expected result type: '" + expectedReturnType->toString() + "'.";
    }
    message += " Candidate details: ";
    for (size_t i = 0; i < ambiguous.size(); ++i) {
      if (i != 0) {
        message += "; ";
      }
      message +=
          "'" + renderFunctionSignature(*matches[ambiguous[i]].symbol) + "' [";
      for (size_t j = 0; j < matches[ambiguous[i]].notes.size(); ++j) {
        if (j != 0) {
          message += ", ";
        }
        message += matches[ambiguous[i]].notes[j];
      }
      message += "]";
    }
    error(node.callee_->span, message);
    return;
  }
  auto &best = matches[bestIndex];
  expressionStack_.push(std::make_unique<BoundFunctionCall>(
      best.symbol, std::move(best.arguments), std::move(best.argumentIsRef),
      std::move(best.variadicPack)));
}
References zir::Array, bindExpressionWithExpected(), bindSizeOfBuiltinCall(), bindWeakBuiltinCall(), buildGenericBindings(), FunCall::callee_, canConvert(), zir::Class, classInfos_, sema::collectOverloads(), conversionCost(), currentClassStack_, currentExpectedExpressionType(), describeConversion(), ensureGenericFunctionInstantiation(), error(), expressionStack_, sema::extractQualifiedPath(), sema::Function, zir::FunctionPointer, FunCall::genericArgs_, getCVariadicArgumentType(), isUnsafeActive(), sema::isVariadicViewType(), sema::makeVariadicViewType(), orderedGenericBindings(), FunCall::params_, Protected, Public, renderFunctionSignature(), renderTypeForUser(), requireUnsafeContext(), resolveQualifiedSymbol(), Node::span, substituteGenericType(), zir::TaggedUnion, sema::Variable, and wrapInCast().
visit() [26/44]
void sema::Binder::visit (FunDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 933 of file binder_decls.cpp.
{
  auto symbolIt = declaredFunctionSymbols_.find(&node);
  auto symbol =
      symbolIt == declaredFunctionSymbols_.end() ? nullptr : symbolIt->second;
  if (!symbol) {
    return;
  }
  if (!symbol->genericParameterNames.empty() &&
      !symbol->isGenericInstantiation) {
    return;
  }
  pushScope();
  auto oldFunction = currentFunction_;
  currentFunction_ = symbol;
  int oldUnsafeDepth = unsafeDepth_;
  if (node.isUnsafe_) {
    ++unsafeDepth_;
  }
  for (size_t i = 0; i < symbol->parameters.size(); ++i) {
    const auto &param = symbol->parameters[i];
    if (!currentScope_->declare(param->name, param)) {
      error(node.span, "Parameter '" + param->name + "' already declared.");
    }
    if (semanticInfo_ && i < node.params_.size() && node.params_[i]) {
      semanticInfo_->recordSymbol(node.params_[i].get(), param);
      semanticInfo_->recordType(node.params_[i].get(), param->type);
    }
  }
  auto boundBody = bindBody(node.body_.get(), false);
  popScope();
  currentFunction_ = oldFunction;
  unsafeDepth_ = oldUnsafeDepth;
  if (!symbol->returnType) {
    std::vector<std::shared_ptr<zir::Type>> returnTypes;
    std::function<void(const BoundBlock *)> collectReturns =
        [&](const BoundBlock *block) {
          if (!block)
            return;
          for (const auto &stmt : block->statements) {
            if (auto *ret =
                    dynamic_cast<const BoundReturnStatement *>(stmt.get())) {
              returnTypes.push_back(ret->expression
                                        ? ret->expression->type
                                        : std::make_shared<zir::PrimitiveType>(
                                              zir::TypeKind::Void));
            } else if (auto *ifStmt =
                           dynamic_cast<const BoundIfStatement *>(stmt.get())) {
              collectReturns(ifStmt->thenBody.get());
              collectReturns(ifStmt->elseBody.get());
            } else if (auto *whileStmt =
                           dynamic_cast<const BoundWhileStatement *>(
                               stmt.get())) {
              collectReturns(whileStmt->body.get());
            }
          }
        };
    collectReturns(boundBody.get());
    if (returnTypes.empty()) {
      symbol->returnType =
          std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    } else {
      auto inferred = returnTypes[0];
      bool conflict = false;
      for (size_t i = 1; i < returnTypes.size(); ++i) {
        if (!canConvert(returnTypes[i], inferred) &&
            !canConvert(inferred, returnTypes[i])) {
          error(node.span, "Cannot infer return type of function '" +
                               node.name_ + "': conflicting return types '" +
                               renderTypeForUser(inferred) + "' and '" +
                               renderTypeForUser(returnTypes[i]) +
                               "'. Add an explicit return type annotation.");
          conflict = true;
          break;
        }
        if (canConvert(inferred, returnTypes[i])) {
          inferred = returnTypes[i];
        }
      }
      symbol->returnType =
          conflict ? std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void)
                   : inferred;
    }
  }
  bool hasReturn = blockAlwaysReturns(boundBody.get());
  if (!hasReturn && symbol->linkName == "main" &&
      symbol->returnType->isInteger()) {
    auto intType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int);
    auto lit = std::make_unique<BoundLiteral>("0", intType);
    boundBody->statements.push_back(
        std::make_unique<BoundReturnStatement>(std::move(lit)));
    hasReturn = true;
  }
  if (!hasReturn && symbol->returnType->getKind() != zir::TypeKind::Void) {
    auto kind = symbol->returnType->getKind();
    if (symbol->returnType->isInteger() || kind == zir::TypeKind::Float ||
        kind == zir::TypeKind::Bool) {
      std::string litVal = "0";
      if (kind == zir::TypeKind::Float)
        litVal = "0.0";
      else if (kind == zir::TypeKind::Bool)
        litVal = "false";
      auto lit = std::make_unique<BoundLiteral>(litVal, symbol->returnType);
      boundBody->statements.push_back(
          std::make_unique<BoundReturnStatement>(std::move(lit)));
    }
    _diag.report(node.span, zap::DiagnosticLevel::Warning,
                 "Function '" + node.name_ +
                     "' has non-void return type but no return on some paths.");
  }
  boundRoot_->functions.push_back(
      std::make_unique<BoundFunctionDeclaration>(symbol, std::move(boundBody)));
}
References _diag, bindBody(), sema::blockAlwaysReturns(), FunDecl::body_, zir::Bool, boundRoot_, canConvert(), currentFunction_, currentScope_, declaredFunctionSymbols_, error(), zir::Float, zir::Int, FunDecl::isUnsafe_, FunDecl::name_, FunDecl::params_, popScope(), pushScope(), renderTypeForUser(), semanticInfo_, Node::span, unsafeDepth_, visit(), zir::Void, and zap::Warning.
visit() [27/44]
void sema::Binder::visit (IfNode & node) override virtual
Reimplemented from Visitor.
Definition at line 215 of file binder_stmts.cpp.
{
  node.condition_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto cond = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (cond->type->getKind() != zir::TypeKind::Bool) {
    error(node.condition_->span, "If condition must be Bool, got '" +
                                     renderTypeForUser(cond->type) + "'");
  }
  auto thenBody = bindBody(node.thenBody_.get(), true);
  std::unique_ptr<BoundBlock> elseBody = nullptr;
  if (node.elseBody_) {
    elseBody = bindBody(node.elseBody_.get(), true);
  }
  statementStack_.push(std::make_unique<BoundIfStatement>(
      std::move(cond), std::move(thenBody), std::move(elseBody)));
}
References bindBody(), zir::Bool, IfNode::condition_, IfNode::elseBody_, error(), expressionStack_, renderTypeForUser(), statementStack_, and IfNode::thenBody_.
visit() [28/44]
void sema::Binder::visit (IfTypeNode & node) override virtual
Reimplemented from Visitor.
Definition at line 239 of file binder_stmts.cpp.
{
  if (activeGenericBindingsStack_.empty()) {
    error(node.span,
          "'iftype' can only be used inside a generic instantiation.");
    return;
  }
  std::shared_ptr<zir::Type> actualType = nullptr;
  for (auto it = activeGenericBindingsStack_.rbegin();
       it != activeGenericBindingsStack_.rend(); ++it) {
    auto bindingIt = it->find(node.parameterName_);
    if (bindingIt != it->end()) {
      actualType = bindingIt->second;
      break;
    }
  }
  if (!actualType) {
    error(node.span,
          "'iftype' expects an active generic type parameter, got '" +
              node.parameterName_ + "'.");
    return;
  }
  auto matchType = mapType(*node.matchType_);
  if (!matchType) {
    error(node.matchType_->span,
          "Unknown type: " + node.matchType_->qualifiedName());
    return;
  }
  bool matched = renderTypeForUser(actualType) == renderTypeForUser(matchType);
  std::unique_ptr<BoundBlock> selectedBody = nullptr;
  if (matched) {
    selectedBody = bindBody(node.thenBody_.get(), true);
  } else if (node.elseBody_) {
    selectedBody = bindBody(node.elseBody_.get(), true);
  } else {
    selectedBody = std::make_unique<BoundBlock>();
  }
  statementStack_.push(std::move(selectedBody));
}
References activeGenericBindingsStack_, bindBody(), IfTypeNode::elseBody_, error(), mapType(), IfTypeNode::matchType_, IfTypeNode::parameterName_, renderTypeForUser(), Node::span, statementStack_, and IfTypeNode::thenBody_.
visit() [29/44]
void sema::Binder::visit (ImportNode & node) override virtual
Reimplemented from Visitor.
Definition at line 865 of file binder_decls.cpp.
{ (void)node; }
References visit().
visit() [30/44]
void sema::Binder::visit (IndexAccessNode & node) override virtual
Reimplemented from Visitor.
Definition at line 769 of file binder_exprs.cpp.
{
  node.left_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto left = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (left->type->getKind() != zir::TypeKind::Array &&
      !isVariadicViewType(left->type) && !isStringType(left->type)) {
    error(node.span, "Type '" + renderTypeForUser(left->type) +
                         "' does not support indexing.");
    return;
  }
  node.index_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto index = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (!index->type->isInteger()) {
    error(node.span, "Array index must be an integer, but got '" +
                         renderTypeForUser(index->type) + "'");
  }
  std::shared_ptr<zir::Type> elementType;
  if (left->type->getKind() == zir::TypeKind::Array) {
    auto arrayType = std::static_pointer_cast<zir::ArrayType>(left->type);
    elementType = arrayType->getBaseType();
  } else if (isVariadicViewType(left->type)) {
    auto recordType = std::static_pointer_cast<zir::RecordType>(left->type);
    const auto &fields = recordType->getFields();
    if (fields.empty() || fields[0].type->getKind() != zir::TypeKind::Pointer) {
      error(node.span, "Internal error: invalid variadic view layout.");
      return;
    }
    elementType = std::static_pointer_cast<zir::PointerType>(fields[0].type)
                      ->getBaseType();
  } else {
    elementType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Char);
  }
  expressionStack_.push(std::make_unique<BoundIndexAccess>(
      std::move(left), std::move(index), elementType));
}
References zir::Array, zir::Char, error(), expressionStack_, IndexAccessNode::index_, sema::isStringType(), sema::isVariadicViewType(), IndexAccessNode::left_, zir::Pointer, renderTypeForUser(), and Node::span.
visit() [31/44]
void sema::Binder::visit (MemberAccessNode & node) override virtual
Reimplemented from Visitor.
Definition at line 815 of file binder_exprs.cpp.
{
  node.left_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto left = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (auto moduleRef = dynamic_cast<BoundModuleReference *>(left.get())) {
    auto memberIt = moduleRef->symbol->exports.find(node.member_);
    if (memberIt == moduleRef->symbol->exports.end()) {
      auto privateIt = moduleRef->symbol->members.find(node.member_);
      if (privateIt != moduleRef->symbol->members.end()) {
        error(node.span, "Member '" + node.member_ + "' of module '" +
                             moduleRef->symbol->name + "' is private.");
      } else {
        error(node.span, "Module '" + moduleRef->symbol->name +
                             "' has no member '" + node.member_ + "'");
      }
      return;
    }
    if (auto varSymbol =
            std::dynamic_pointer_cast<VariableSymbol>(memberIt->second)) {
      expressionStack_.push(
          std::make_unique<BoundVariableExpression>(varSymbol));
      return;
    }
    if (auto typeSymbol =
            std::dynamic_pointer_cast<TypeSymbol>(memberIt->second)) {
      expressionStack_.push(
          std::make_unique<BoundLiteral>("", typeSymbol->type));
      return;
    }
    if (auto nestedModule =
            std::dynamic_pointer_cast<ModuleSymbol>(memberIt->second)) {
      expressionStack_.push(
          std::make_unique<BoundModuleReference>(nestedModule));
      return;
    }
    error(node.span, "'" + node.member_ + "' is not a value or type.");
    return;
  }
  if (left->type->getKind() == zir::TypeKind::Enum) {
    auto enumType = std::static_pointer_cast<zir::EnumType>(left->type);
    int64_t value = enumType->getVariantDiscriminant(node.member_);
    if (value != -1) {
      expressionStack_.push(
          std::make_unique<BoundLiteral>(std::to_string(value), enumType));
      return;
    }
  } else if (left->type->getKind() == zir::TypeKind::TaggedUnion) {
    auto taggedUnionType =
        std::static_pointer_cast<zir::TaggedUnionType>(left->type);
    if (node.member_ == "tag") {
      expressionStack_.push(std::make_unique<BoundMemberAccess>(
          std::move(left), node.member_,
          std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int32)));
      return;
    }
    if (taggedUnionType->findVariant(node.member_) &&
        dynamic_cast<BoundLiteral *>(left.get())) {
      expressionStack_.push(std::make_unique<BoundMemberAccess>(
          std::move(left), node.member_, taggedUnionType));
      return;
    }
  } else if (left->type->getKind() == zir::TypeKind::Record) {
    auto recordType = std::static_pointer_cast<zir::RecordType>(left->type);
    for (const auto &field : recordType->getFields()) {
      if (field.name == node.member_) {
        expressionStack_.push(std::make_unique<BoundMemberAccess>(
            std::move(left), node.member_, field.type));
        return;
      }
    }
  } else if (left->type->getKind() == zir::TypeKind::Pointer) {
    auto ptrType = std::static_pointer_cast<zir::PointerType>(left->type);
    auto baseType = ptrType->getBaseType();
    if (baseType->getKind() == zir::TypeKind::Record) {
      auto recordType = std::static_pointer_cast<zir::RecordType>(baseType);
      for (const auto &field : recordType->getFields()) {
        if (field.name == node.member_) {
          expressionStack_.push(std::make_unique<BoundMemberAccess>(
              std::move(left), node.member_, field.type));
          return;
        }
      }
    } else if (baseType->getKind() == zir::TypeKind::Class) {
      auto classType = std::static_pointer_cast<zir::ClassType>(baseType);
      if (classType->isWeak()) {
        error(node.span, "Weak references cannot be accessed directly.");
        return;
      }
      auto infoIt = classInfos_.find(classType->getName());
      if (infoIt != classInfos_.end()) {
        auto fieldIt = infoIt->second.fields.find(node.member_);
        if (fieldIt != infoIt->second.fields.end()) {
          auto fieldVis = fieldIt->second->visibility;
          bool allowed = fieldVis == Visibility::Public ||
                         (!currentClassStack_.empty() &&
                          currentClassStack_.back() == classType->getName()) ||
                         (fieldVis == Visibility::Protected &&
                          !currentClassStack_.empty());
          if (!allowed) {
            error(node.span, "Field '" + node.member_ + "' is not accessible.");
            return;
          }
          expressionStack_.push(std::make_unique<BoundMemberAccess>(
              std::move(left), node.member_, fieldIt->second->type));
          return;
        }
      }
    }
  } else if (left->type->getKind() == zir::TypeKind::Class) {
    auto classType = std::static_pointer_cast<zir::ClassType>(left->type);
    if (classType->isWeak()) {
      error(node.span, "Weak references cannot be accessed directly.");
      return;
    }
    auto infoIt = classInfos_.find(classType->getName());
    if (infoIt != classInfos_.end()) {
      auto fieldIt = infoIt->second.fields.find(node.member_);
      if (fieldIt != infoIt->second.fields.end()) {
        auto fieldVis = fieldIt->second->visibility;
        bool allowed =
            fieldVis == Visibility::Public ||
            (!currentClassStack_.empty() &&
             currentClassStack_.back() == classType->getName()) ||
            (fieldVis == Visibility::Protected && !currentClassStack_.empty());
        if (!allowed) {
          error(node.span, "Field '" + node.member_ + "' is not accessible.");
          return;
        }
        expressionStack_.push(std::make_unique<BoundMemberAccess>(
            std::move(left), node.member_, fieldIt->second->type));
        return;
      }
    }
  }
  error(node.span, "Member '" + node.member_ + "' not found in type '" +
                       renderTypeForUser(left->type) + "'");
}
References zir::Class, classInfos_, currentClassStack_, zir::Enum, error(), expressionStack_, zir::Int32, MemberAccessNode::left_, MemberAccessNode::member_, zir::Pointer, Protected, Public, zir::Record, renderTypeForUser(), Node::span, and zir::TaggedUnion.
visit() [32/44]
void sema::Binder::visit (NewExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 1831 of file binder_exprs.cpp.
{
  auto classType = mapType(*node.type_);
  if (!classType || classType->getKind() != zir::TypeKind::Class) {
    error(node.span, "'new' expects a class type.");
    return;
  }
  auto concreteType = std::static_pointer_cast<zir::ClassType>(classType);
  if (concreteType->isWeak()) {
    error(node.span, "'new' expects a strong class type, not 'weak'.");
    return;
  }
  auto infoIt = classInfos_.find(concreteType->getName());
  if (infoIt == classInfos_.end()) {
    error(node.span, "Unknown class type: " + concreteType->getName());
    return;
  }
  std::vector<std::unique_ptr<BoundExpression>> args;
  std::vector<bool> argRefs;
  std::vector<std::unique_ptr<BoundExpression>> rawArgs;
  rawArgs.reserve(node.args_.size());
  for (size_t i = 0; i < node.args_.size(); ++i) {
    auto arg = bindExpressionWithExpected(node.args_[i]->value.get(), nullptr);
    if (!arg) {
      return;
    }
    rawArgs.push_back(std::move(arg));
  }
  auto ctor = infoIt->second.constructor;
  auto ctorIt = infoIt->second.methods.find("init");
  auto ctorCandidates = ctorIt == infoIt->second.methods.end()
                            ? std::vector<std::shared_ptr<FunctionSymbol>>{}
                            : collectOverloads(ctorIt->second);
  if (ctorCandidates.empty() && ctor) {
    ctorCandidates.push_back(ctor);
  }
  struct ConstructorCandidate {
    std::shared_ptr<FunctionSymbol> symbol;
    std::vector<int> cost;
  };
  std::vector<ConstructorCandidate> matches;
  if (ctorCandidates.empty()) {
    if (!node.args_.empty()) {
      error(node.span, "Constructor for class '" + concreteType->getName() +
                           "' expects 0 arguments, got " +
                           std::to_string(node.args_.size()) + ".");
      return;
    }
  } else {
    for (const auto &candidate : ctorCandidates) {
      if (!candidate) {
        continue;
      }
      size_t ctorParamOffset = candidate->isMethod ? 1 : 0;
      if (node.args_.size() + ctorParamOffset != candidate->parameters.size()) {
        continue;
      }
      ConstructorCandidate match;
      match.symbol = candidate;
      bool failed = false;
      for (size_t i = 0; i < rawArgs.size(); ++i) {
        auto expected = candidate->parameters[i + ctorParamOffset]->type;
        if (!canConvert(rawArgs[i]->type, expected)) {
          failed = true;
          break;
        }
        match.cost.push_back(conversionCost(rawArgs[i]->type, expected));
      }
      if (!failed) {
        matches.push_back(std::move(match));
      }
    }
    if (matches.empty()) {
      error(node.span, "No matching constructor for class '" +
                           concreteType->getName() + "'.");
      return;
    }
    std::sort(
        matches.begin(), matches.end(),
        [](const ConstructorCandidate &lhs, const ConstructorCandidate &rhs) {
          return lhs.cost < rhs.cost;
        });
    if (matches.size() > 1 && matches[0].cost == matches[1].cost) {
      error(node.span, "Ambiguous constructor for class '" +
                           concreteType->getName() + "'.");
      return;
    }
    ctor = matches.front().symbol;
  }
  size_t ctorParamOffset = ctor && ctor->isMethod ? 1 : 0;
  for (size_t i = 0; i < rawArgs.size(); ++i) {
    auto arg = rawArgs[i]->clone();
    auto expected =
        ctor ? ctor->parameters[i + ctorParamOffset]->type : nullptr;
    if (expected) {
      arg = wrapInCast(std::move(arg), expected);
    }
    args.push_back(std::move(arg));
    argRefs.push_back(node.args_[i]->isRef);
  }
  expressionStack_.push(std::make_unique<BoundNewExpression>(
      concreteType, ctor, std::move(args), std::move(argRefs)));
  if (semanticInfo_) {
    semanticInfo_->recordType(&node, concreteType);
  }
}
References NewExpr::args_, bindExpressionWithExpected(), canConvert(), zir::Class, classInfos_, sema::collectOverloads(), conversionCost(), error(), expressionStack_, mapType(), semanticInfo_, Node::span, NewExpr::type_, visit(), and wrapInCast().
visit() [33/44]
void sema::Binder::visit (RecordDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1246 of file binder_decls.cpp.
{
  auto symbol =
      std::dynamic_pointer_cast<TypeSymbol>(currentScope_->lookup(node.name_));
  if (!symbol || !symbol->genericParameterNames.empty()) {
    return;
  }
  auto recordType = std::static_pointer_cast<zir::RecordType>(symbol->type);
  for (const auto &field : node.fields_) {
    auto fieldType = mapType(*field->type);
    if (!fieldType) {
      error(field->span, "Unknown type: " + field->type->qualifiedName());
      fieldType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    recordType->addField(field->name, fieldType);
  }
  auto boundRecord = std::make_unique<BoundRecordDeclaration>();
  boundRecord->type = recordType;
  boundRoot_->records.push_back(std::move(boundRecord));
}
References boundRoot_, currentScope_, error(), RecordDecl::fields_, mapType(), RecordDecl::name_, visit(), and zir::Void.
visit() [34/44]
void sema::Binder::visit (ReturnNode & node) override virtual
Reimplemented from Visitor.
Definition at line 131 of file binder_stmts.cpp.
{
  std::unique_ptr<BoundExpression> expr = nullptr;
  bool expressionHadDiagnostic = false;
  if (node.returnValue) {
    bool hadErrorBefore = hadError_;
    expr = bindExpressionWithExpected(
        node.returnValue.get(),
        currentFunction_ ? currentFunction_->returnType : nullptr);
    expressionHadDiagnostic = (hadError_ != hadErrorBefore);
    if (!expr) {
      // The return expression already produced a diagnostic.
      // Avoid cascading with a secondary "received Void" return-type error.
      statementStack_.push(std::make_unique<BoundReturnStatement>(
          nullptr, currentFunction_ && currentFunction_->returnsRef));
      return;
    }
  }
  if (currentFunction_ && currentFunction_->returnType) {
    auto expectedType = currentFunction_->returnType;
    auto actualType =
        expr ? expr->type
             : std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    if (isFailableType(expectedType) && !isFailableType(actualType)) {
      auto expectedValueType = failableValueType(expectedType);
      if (!canConvert(actualType, expectedValueType)) {
        error(node.span,
              "Function '" + currentFunction_->name +
                  "' expects return type '" + renderTypeForUser(expectedType) +
                  "', but received '" + renderTypeForUser(actualType) + "'");
      } else if (expr) {
        expr = wrapInCast(std::move(expr), expectedValueType);
        expr = makeFailableValueExpr(std::move(expr), expectedType);
      } else {
        expr = makeFailableValueExpr(makeDefaultValueExpr(expectedValueType),
                                     expectedType);
      }
    } else if (!canConvert(actualType, expectedType)) {
      if (expressionHadDiagnostic) {
        statementStack_.push(std::make_unique<BoundReturnStatement>(
            std::move(expr), currentFunction_ && currentFunction_->returnsRef));
        return;
      }
      error(node.span,
            "Function '" + currentFunction_->name + "' expects return type '" +
                renderTypeForUser(expectedType) + "', but received '" +
                renderTypeForUser(actualType) + "'");
    } else if (expr) {
      expr = wrapInCast(std::move(expr), expectedType);
    }
  }
  statementStack_.push(std::make_unique<BoundReturnStatement>(
      std::move(expr), currentFunction_ && currentFunction_->returnsRef));
}
References bindExpressionWithExpected(), canConvert(), currentFunction_, error(), sema::failableValueType(), hadError_, sema::isFailableType(), sema::makeDefaultValueExpr(), sema::makeFailableValueExpr(), renderTypeForUser(), ReturnNode::returnValue, Node::span, statementStack_, zir::Void, and wrapInCast().
visit() [35/44]
void sema::Binder::visit (RootNode & node) override virtual
Reimplemented from Visitor.
Definition at line 856 of file binder_decls.cpp.
{
  for (const auto &child : node.children) {
    if (dynamic_cast<ImportNode *>(child.get())) {
      continue;
    }
    child->accept(*this);
  }
}
References RootNode::children, and visit().
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
visit() [36/44]
void sema::Binder::visit (StructDeclarationNode & node) override virtual
Reimplemented from Visitor.
Definition at line 1268 of file binder_decls.cpp.
{
  auto symbol =
      std::dynamic_pointer_cast<TypeSymbol>(currentScope_->lookup(node.name_));
  if (!symbol || !symbol->genericParameterNames.empty()) {
    return;
  }
  auto recordType = std::static_pointer_cast<zir::RecordType>(symbol->type);
  int oldUnsafeTypeContextDepth = unsafeTypeContextDepth_;
  int oldExternTypeContextDepth = externTypeContextDepth_;
  if (node.isUnsafe_) {
    ++unsafeTypeContextDepth_;
  }
  ++externTypeContextDepth_;
  for (const auto &field : node.fields_) {
    auto fieldType = mapType(*field->type);
    if (!fieldType) {
      error(field->span, "Unknown type: " + field->type->qualifiedName());
      fieldType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    recordType->addField(field->name, fieldType);
  }
  unsafeTypeContextDepth_ = oldUnsafeTypeContextDepth;
  externTypeContextDepth_ = oldExternTypeContextDepth;
  auto boundRecord = std::make_unique<BoundRecordDeclaration>();
  boundRecord->type = recordType;
  boundRoot_->records.push_back(std::move(boundRecord));
}
References boundRoot_, currentScope_, error(), externTypeContextDepth_, StructDeclarationNode::fields_, StructDeclarationNode::isUnsafe_, mapType(), StructDeclarationNode::name_, unsafeTypeContextDepth_, visit(), and zir::Void.
visit() [37/44]
void sema::Binder::visit (StructLiteralNode & node) override virtual
Reimplemented from Visitor.
Definition at line 2041 of file binder_exprs.cpp.
{
  if (!node.type_) {
    error(node.span, "Missing struct literal type.");
    return;
  }
  auto parts = splitQualified(node.type_->qualifiedName());
  auto symbol = resolveQualifiedSymbol(parts, node.span, SymbolKind::Type);
  if (!symbol || symbol->getKind() != SymbolKind::Type) {
    error(node.span, "Unknown type: " + node.type_->qualifiedName());
    return;
  }
  auto typeSymbol = std::static_pointer_cast<TypeSymbol>(symbol);
  bool pushedInferredBindings = false;
  if (!typeSymbol->genericParameterNames.empty() &&
      node.type_->genericArgs.empty()) {
    const std::vector<std::unique_ptr<ParameterNode>> *declFields = nullptr;
    if (auto rdIt = recordTypeDeclarationNodes_.find(typeSymbol.get());
        rdIt != recordTypeDeclarationNodes_.end()) {
      declFields = &rdIt->second->fields_;
    } else if (auto sdIt = structTypeDeclarationNodes_.find(typeSymbol.get());
               sdIt != structTypeDeclarationNodes_.end()) {
      declFields = &sdIt->second->fields_;
    }
    if (declFields) {
      std::unordered_map<std::string, std::shared_ptr<zir::Type>>
          inferredBindings;
      for (const auto &fieldInit : node.fields_) {
        for (const auto &declField : *declFields) {
          if (declField->name != fieldInit.name)
            continue;
          const TypeNode &fieldTypeNode = *declField->type;
          if (!fieldTypeNode.qualifiers.empty() ||
              !fieldTypeNode.genericArgs.empty())
            break;
          const auto &paramName = fieldTypeNode.typeName;
          bool isGenericParam = false;
          for (const auto &gp : typeSymbol->genericParameterNames) {
            if (gp == paramName) {
              isGenericParam = true;
              break;
            }
          }
          if (!isGenericParam || inferredBindings.count(paramName))
            break;
          auto stackSizeBefore = expressionStack_.size();
          fieldInit.value->accept(*this);
          if (expressionStack_.size() > stackSizeBefore) {
            auto preBound = std::move(expressionStack_.top());
            expressionStack_.pop();
            if (preBound && preBound->type) {
              inferredBindings[paramName] = preBound->type;
            }
          }
          break;
        }
      }
      if (!inferredBindings.empty()) {
        activeGenericBindingsStack_.push_back(std::move(inferredBindings));
        pushedInferredBindings = true;
      }
    }
  }
  auto mappedType = mapType(*node.type_);
  if (pushedInferredBindings) {
    activeGenericBindingsStack_.pop_back();
  }
  if (!mappedType || mappedType->getKind() != zir::TypeKind::Record) {
    error(node.span, "'" + node.type_->qualifiedName() + "' is not a struct.");
    return;
  }
  if (typeSymbol->isUnsafe) {
    requireUnsafeContext(node.span, "unsafe struct literals");
  }
  auto recordType = std::static_pointer_cast<zir::RecordType>(mappedType);
  const StructDeclarationNode *structDecl = nullptr;
  if (auto sdIt = structTypeDeclarationNodes_.find(typeSymbol.get());
      sdIt != structTypeDeclarationNodes_.end()) {
    structDecl = sdIt->second;
  }
  std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>>
      boundFields;
  std::vector<std::string> missingFields;
  for (auto &fieldInit : node.fields_) {
    std::shared_ptr<zir::Type> fieldExpectedType = nullptr;
    for (const auto &f : recordType->getFields()) {
      if (f.name == fieldInit.name) {
        fieldExpectedType = f.type;
        break;
      }
    }
    std::unique_ptr<BoundExpression> boundVal;
    if (fieldExpectedType) {
      boundVal =
          bindExpressionWithExpected(fieldInit.value.get(), fieldExpectedType);
    } else {
      fieldInit.value->accept(*this);
      if (expressionStack_.empty())
        continue;
      boundVal = std::move(expressionStack_.top());
      expressionStack_.pop();
    }
    if (!boundVal)
      continue;
    bool found = false;
    for (const auto &f : recordType->getFields()) {
      if (f.name == fieldInit.name) {
        if (!canConvert(boundVal->type, f.type)) {
          error(node.span, "Cannot assign type '" +
                               renderTypeForUser(boundVal->type) +
                               "' to field '" + f.name + "' of type '" +
                               renderTypeForUser(f.type) + "'");
        } else {
          boundVal = wrapInCast(std::move(boundVal), f.type);
        }
        found = true;
        break;
      }
    }
    if (!found) {
      error(fieldInit.value ? fieldInit.value->span : node.span,
            "Field '" + fieldInit.name + "' not found in struct '" +
                node.type_->qualifiedName() + "'");
    }
    boundFields.push_back({fieldInit.name, std::move(boundVal)});
  }
  for (const auto &f : recordType->getFields()) {
    bool initialized = false;
    for (const auto &bf : boundFields) {
      if (bf.first == f.name) {
        initialized = true;
        break;
      }
    }
    if (!initialized) {
      const ParameterNode *declField = nullptr;
      if (structDecl) {
        for (const auto &candidate : structDecl->fields_) {
          if (candidate->name == f.name) {
            declField = candidate.get();
            break;
          }
        }
      }
      std::unique_ptr<BoundExpression> defaultValue;
      bool hasDeclaredDefault = declField && declField->defaultValue;
      if (hasDeclaredDefault) {
        defaultValue =
            bindExpressionWithExpected(declField->defaultValue.get(), f.type);
        if (!defaultValue) {
          defaultValue = nullptr;
        } else if (!canConvert(defaultValue->type, f.type)) {
          error(declField->defaultValue->span,
                "Cannot assign default value of type '" +
                    renderTypeForUser(defaultValue->type) + "' to field '" +
                    f.name + "' of type '" + renderTypeForUser(f.type) + "'");
          defaultValue = nullptr;
        } else {
          defaultValue = wrapInCast(std::move(defaultValue), f.type);
        }
      }
      if (!defaultValue) {
        if (!hasDeclaredDefault) {
          missingFields.push_back(f.name);
        }
        defaultValue = makeDefaultValueExpr(f.type);
      }
      boundFields.push_back({f.name, std::move(defaultValue)});
    }
  }
  if (!missingFields.empty()) {
    std::string missingList;
    for (size_t i = 0; i < missingFields.size(); ++i) {
      if (i != 0) {
        missingList += ", ";
      }
      missingList += "'" + missingFields[i] + "'";
    }
    SourceSpan warningSpan = node.span;
    if (!node.fields_.empty() && node.fields_.front().value) {
      warningSpan = node.fields_.front().value->span;
    } else if (node.type_) {
      warningSpan = node.type_->span;
    }
    _diag.report(warningSpan, zap::DiagnosticLevel::Warning,
                 "Struct literal for '" + node.type_->qualifiedName() +
                     "' is missing fields: " + missingList +
                     ". Using default values.");
  }
  expressionStack_.push(
      std::make_unique<BoundStructLiteral>(std::move(boundFields), recordType));
}
References _diag, activeGenericBindingsStack_, bindExpressionWithExpected(), canConvert(), ParameterNode::defaultValue, error(), expressionStack_, StructDeclarationNode::fields_, StructLiteralNode::fields_, TypeNode::genericArgs, sema::makeDefaultValueExpr(), mapType(), TypeNode::qualifiers, zir::Record, recordTypeDeclarationNodes_, renderTypeForUser(), requireUnsafeContext(), resolveQualifiedSymbol(), Node::span, sema::splitQualified(), structTypeDeclarationNodes_, sema::Type, StructLiteralNode::type_, TypeNode::typeName, visit(), zap::Warning, and wrapInCast().
visit() [38/44]
void sema::Binder::visit (TernaryExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 372 of file binder_exprs.cpp.
{
  node.condition_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto condition = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (condition->type->getKind() != zir::TypeKind::Bool) {
    error(node.condition_->span, "Ternary condition must be Bool, got '" +
                                     renderTypeForUser(condition->type) + "'");
  }
  node.thenExpr_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto thenExpr = std::move(expressionStack_.top());
  expressionStack_.pop();
  node.elseExpr_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto elseExpr = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (!canConvert(thenExpr->type, elseExpr->type) &&
      !canConvert(elseExpr->type, thenExpr->type)) {
    error(SourceSpan::merge(node.thenExpr_->span, node.elseExpr_->span),
          "Ternary branches must be compatible, got '" +
              renderTypeForUser(thenExpr->type) + "' and '" +
              renderTypeForUser(elseExpr->type) + "'");
  }
  auto resultType = canConvert(thenExpr->type, elseExpr->type) ? elseExpr->type
                                                               : thenExpr->type;
  thenExpr = wrapInCast(std::move(thenExpr), resultType);
  elseExpr = wrapInCast(std::move(elseExpr), resultType);
  expressionStack_.push(std::make_unique<BoundTernaryExpression>(
      std::move(condition), std::move(thenExpr), std::move(elseExpr),
      resultType));
}
References zir::Bool, canConvert(), TernaryExpr::condition_, TernaryExpr::elseExpr_, error(), expressionStack_, SourceSpan::merge(), renderTypeForUser(), TernaryExpr::thenExpr_, and wrapInCast().
visit() [39/44]
void sema::Binder::visit (TryExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 501 of file binder_exprs.cpp.
{
  node.expression_->accept(*this);
  if (expressionStack_.empty()) {
    return;
  }
  auto expression = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (!isFailableType(expression->type)) {
    error(node.span, "Operator '?' requires failable expression type, got '" +
                         renderTypeForUser(expression->type) + "'");
    return;
  }
  auto valueType = failableValueType(expression->type);
  auto errorType = failableErrorType(expression->type);
  if (!currentFunction_ || !isFailableType(currentFunction_->returnType)) {
    error(node.span, "Operator '?' can only be used inside functions returning "
                     "failable type.");
    return;
  }
  auto currentErrorType = failableErrorType(currentFunction_->returnType);
  if (!currentErrorType || !errorType ||
      currentErrorType->toString() != errorType->toString()) {
    error(node.span, "Cannot propagate error type '" +
                         renderTypeForUser(errorType) +
                         "' into function error type '" +
                         renderTypeForUser(currentErrorType) +
                         "': exact error type match is required for '?'.");
    return;
  }
  expressionStack_.push(std::make_unique<BoundTryExpression>(
      std::move(expression), valueType, currentFunction_->returnType,
      errorType));
}
References currentFunction_, error(), TryExpr::expression_, expressionStack_, sema::failableErrorType(), sema::failableValueType(), sema::isFailableType(), renderTypeForUser(), and Node::span.
visit() [40/44]
void sema::Binder::visit (TypeAliasDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1244 of file binder_decls.cpp.
{ (void)node; }
References visit().
visit() [41/44]
void sema::Binder::visit (UnaryExpr & node) override virtual
Reimplemented from Visitor.
Definition at line 1953 of file binder_exprs.cpp.
{
  node.expr_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto expr = std::move(expressionStack_.top());
  expressionStack_.pop();
  auto type = expr->type;
  if (node.op_ == "&") {
    auto *exprAsVar = dynamic_cast<BoundVariableExpression *>(expr.get());
    auto *exprAsIndex = dynamic_cast<BoundIndexAccess *>(expr.get());
    auto *exprAsMember = dynamic_cast<BoundMemberAccess *>(expr.get());
    auto *exprAsUnary = dynamic_cast<BoundUnaryExpression *>(expr.get());
    auto *exprAsCall = dynamic_cast<BoundFunctionCall *>(expr.get());
    bool isLValue = exprAsVar || exprAsIndex || exprAsMember ||
                    (exprAsUnary && exprAsUnary->op == "*") ||
                    (exprAsCall && exprAsCall->symbol->returnsRef);
    if (!isLValue) {
      error(node.span, "Cannot take the address of a non-lvalue expression.");
    }
    type = std::make_shared<zir::PointerType>(expr->type);
  } else if (node.op_ == "*") {
    requireUnsafeContext(node.span, "pointer dereference");
    if (!isPointerType(type)) {
      error(node.span, "Cannot dereference non-pointer type '" +
                           renderTypeForUser(type) + "'");
    } else {
      type = std::static_pointer_cast<zir::PointerType>(type)->getBaseType();
      if (type->getKind() == zir::TypeKind::Void) {
        error(node.span, "Cannot dereference '*Void' directly. Cast it to a "
                         "concrete pointer type first.");
      }
    }
  } else if (node.op_ == "-" || node.op_ == "+") {
    if (!isNumeric(type)) {
      error(node.span, "Operator '" + node.op_ +
                           "' cannot be applied to type '" +
                           renderTypeForUser(type) + "'");
    }
  } else if (node.op_ == "!") {
    if (type->getKind() != zir::TypeKind::Bool) {
      error(node.span, "Operator '!' cannot be applied to type '" +
                           renderTypeForUser(type) + "'");
    }
  } else if (node.op_ == "~") {
    if (!type->isInteger()) {
      error(node.span, "Operator '~' cannot be applied to type '" +
                           renderTypeForUser(type) + "'");
    }
  }
  expressionStack_.push(
      std::make_unique<BoundUnaryExpression>(node.op_, std::move(expr), type));
}
References zir::Bool, error(), UnaryExpr::expr_, expressionStack_, isNumeric(), isPointerType(), UnaryExpr::op_, renderTypeForUser(), requireUnsafeContext(), Node::span, visit(), and zir::Void.
visit() [42/44]
void sema::Binder::visit (UnsafeBlockNode & node) override virtual
Reimplemented from Visitor.
Definition at line 66 of file binder_stmts.cpp.
{
  requireUnsafeEnabled(node.span, "'unsafe' block");
  int oldUnsafeDepth = unsafeDepth_;
  ++unsafeDepth_;
  auto savedBlock = std::move(currentBlock_);
  pushScope();
  visit(static_cast<BodyNode &>(node));
  auto boundBody = std::make_unique<BoundBlock>();
  if (currentBlock_) {
    boundBody = std::move(currentBlock_);
  }
  popScope();
  currentBlock_ = std::move(savedBlock);
  unsafeDepth_ = oldUnsafeDepth;
  statementStack_.push(std::move(boundBody));
}
References currentBlock_, popScope(), pushScope(), requireUnsafeEnabled(), Node::span, statementStack_, unsafeDepth_, and visit().
visit() [43/44]
void sema::Binder::visit (VarDecl & node) override virtual
Reimplemented from Visitor.
Definition at line 1076 of file binder_decls.cpp.
{
  auto existing = currentScope_->lookupLocal(node.name_);
  std::shared_ptr<VariableSymbol> symbol;
  if (existing) {
    symbol = std::dynamic_pointer_cast<VariableSymbol>(existing);
  }
  bool isRef = node.type_ && node.type_->isReference;
  std::shared_ptr<zir::Type> type;
  std::unique_ptr<BoundExpression> initializer = nullptr;
  if (node.type_) {
    type = mapType(*node.type_);
    if (!type) {
      error(node.span, "Unknown type: " + node.type_->qualifiedName());
      type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    }
    if (node.initializer_) {
      initializer = bindExpressionWithExpected(node.initializer_.get(), type);
      if (initializer && !isRef) {
        if (!canConvert(initializer->type, type)) {
          error(node.initializer_->span,
                "Cannot assign expression of type '" +
                    renderTypeForUser(initializer->type) +
                    "' to variable of type '" + renderTypeForUser(type) + "'");
        } else {
          initializer = wrapInCast(std::move(initializer), type);
        }
      }
    } else if (isRef) {
      error(node.span,
            "Reference variable '" + node.name_ + "' must be initialized.");
    }
  } else {
    if (!node.initializer_) {
      error(node.span, "Variable '" + node.name_ +
                           "' needs a type annotation or an initializer.");
      type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
    } else {
      initializer =
          bindExpressionWithExpected(node.initializer_.get(), nullptr);
      if (initializer && initializer->type &&
          initializer->type->getKind() != zir::TypeKind::Void) {
        type = initializer->type;
      } else {
        error(node.initializer_->span, "Cannot infer type of variable '" +
                                           node.name_ +
                                           "' from a void expression.");
        type = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void);
      }
    }
  }
  if (!symbol) {
    symbol = std::make_shared<VariableSymbol>(
        node.name_, type, false, isRef,
        node.isGlobal_ ? (node.isExternal_
                              ? node.name_
                              : mangleName(currentModuleLinkPath(), node.name_))
                       : node.name_,
        modules_[currentModuleId_].info->moduleName, node.visibility_);
    symbol->is_external = node.isExternal_;
    if (!currentScope_->declare(node.name_, symbol)) {
      error(node.span, "Variable '" + node.name_ + "' already declared.");
    }
  } else if (!node.type_ && type) {
    symbol->type = type;
  }
  symbol->is_ref = isRef;
  if (semanticInfo_) {
    semanticInfo_->recordSymbol(&node, symbol);
    semanticInfo_->recordType(&node, symbol->type);
  }
  auto boundDecl = std::make_unique<BoundVariableDeclaration>(
      symbol, std::move(initializer));
  if (currentBlock_ && !node.isGlobal_) {
    statementStack_.push(std::move(boundDecl));
  } else {
    boundRoot_->globals.push_back(std::move(boundDecl));
  }
}
References bindExpressionWithExpected(), boundRoot_, canConvert(), currentBlock_, currentModuleId_, currentModuleLinkPath(), currentScope_, error(), VarDecl::initializer_, VarDecl::isExternal_, VarDecl::isGlobal_, mangleName(), mapType(), modules_, VarDecl::name_, renderTypeForUser(), semanticInfo_, Node::span, statementStack_, VarDecl::type_, TopLevel::visibility_, visit(), zir::Void, and wrapInCast().
visit() [44/44]
void sema::Binder::visit (WhileNode & node) override virtual
Reimplemented from Visitor.
Definition at line 282 of file binder_stmts.cpp.
{
  node.condition_->accept(*this);
  if (expressionStack_.empty())
    return;
  auto cond = std::move(expressionStack_.top());
  expressionStack_.pop();
  if (cond->type->getKind() != zir::TypeKind::Bool) {
    error(node.condition_->span, "While condition must be Bool, got '" +
                                     renderTypeForUser(cond->type) + "'");
  }
  ++loopDepth_;
  auto body = bindBody(node.body_.get(), true);
  --loopDepth_;
  statementStack_.push(
      std::make_unique<BoundWhileStatement>(std::move(cond), std::move(body)));
}
References bindBody(), WhileNode::body_, zir::Bool, WhileNode::condition_, error(), expressionStack_, loopDepth_, renderTypeForUser(), and statementStack_.
warnUnknownAttributes()
void sema::Binder::warnUnknownAttributes (const TopLevel & node) private
Definition at line 1249 of file binder_types.cpp.
{
  for (const auto &attr : node.attributes_) {
    if (!isSupportedBuiltInAttribute(attr.name)) {
      _diag.report(attr.span, zap::DiagnosticLevel::Warning,
                   "unknown attribute '" + attr.name + "'");
    }
  }
}
References _diag, TopLevel::attributes_, isSupportedBuiltInAttribute(), and zap::Warning.
Referenced by validateAndApplyFunctionAttributes(), and validateAndApplyTypeAttributes().
wrapInCast()
std::unique_ptr< BoundExpression > sema::Binder::wrapInCast (std::unique_ptr< BoundExpression > expr, std::shared_ptr< zir::Type > targetType) private
Definition at line 1792 of file binder_types.cpp.
{
  if (!expr || !targetType)
    return expr;
  if (expr->type->getKind() == targetType->getKind() &&
      expr->type->toString() == targetType->toString()) {
    return expr;
  }
  if (isNullType(expr->type) && isPointerType(targetType)) {
    return std::make_unique<BoundCast>(std::move(expr), targetType);
  }
  return std::make_unique<BoundCast>(std::move(expr), targetType);
}
References isNullType(), and isPointerType().
Referenced by buildBinaryExpression(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
Member Data Documentation
_diag
zap::DiagnosticEngine& sema::Binder::_diag private
Definition at line 116 of file binder.hpp.
Referenced by bind(), bind(), Binder(), ensureGenericFunctionInstantiation(), error(), instantiateGenericTypeSymbol(), visit(), visit(), and warnUnknownAttributes().
activeGenericBindingsStack_
std::vector<std::unordered_map<std::string, std::shared_ptr<zir::Type> > > sema::Binder::activeGenericBindingsStack_ private
Definition at line 172 of file binder.hpp.
Referenced by bind(), buildGenericBindings(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), isGenericTypeParameterName(), mapType(), predeclareModuleValues(), validateGenericConstraints(), visit(), and visit().
allowUnsafe_
bool sema::Binder::allowUnsafe_ = true private
Definition at line 132 of file binder.hpp.
Referenced by Binder(), and requireUnsafeEnabled().
boundRoot_
std::unique_ptr<BoundRootNode> sema::Binder::boundRoot_ private
Definition at line 120 of file binder.hpp.
Referenced by bind(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
builtinScope_
std::shared_ptr<SymbolTable> sema::Binder::builtinScope_ private
Definition at line 119 of file binder.hpp.
Referenced by bind(), and initializeBuiltins().
canConvertCache_
std::unordered_map<std::pair<const zir::Type *, const zir::Type *>, bool, PairHash> sema::Binder::canConvertCache_ mutable private
Definition at line 198 of file binder.hpp.
Referenced by canConvert().
classInfos_
std::unordered_map<std::string, ClassInfo> sema::Binder::classInfos_ private
Definition at line 184 of file binder.hpp.
Referenced by instantiateGenericTypeSymbol(), predeclareModuleTypes(), predeclareModuleValues(), visit(), visit(), visit(), and visit().
classTypeDeclarationNodes_
std::unordered_map<const TypeSymbol *, const ClassDecl *> sema::Binder::classTypeDeclarationNodes_ private
Definition at line 156 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), and predeclareModuleTypes().
currentBlock_
std::unique_ptr<BoundBlock> sema::Binder::currentBlock_ private
Definition at line 124 of file binder.hpp.
Referenced by bindBody(), visit(), visit(), visit(), and visit().
currentClassStack_
std::vector<std::string> sema::Binder::currentClassStack_ private
Definition at line 185 of file binder.hpp.
Referenced by instantiateGenericTypeSymbol(), visit(), visit(), and visit().
currentFunction_
std::shared_ptr<FunctionSymbol> sema::Binder::currentFunction_ = nullptr private
Definition at line 137 of file binder.hpp.
Referenced by bind(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), and visit().
currentModuleId_
std::string sema::Binder::currentModuleId_ private
Definition at line 138 of file binder.hpp.
Referenced by bind(), currentModuleLinkPath(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), predeclareModuleAliases(), predeclareModuleTypes(), predeclareModuleValues(), visit(), visit(), visit(), visit(), and visit().
currentScope_
std::shared_ptr<SymbolTable> sema::Binder::currentScope_ private
Definition at line 118 of file binder.hpp.
Referenced by bind(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), lookupVisibleSymbol(), makeSyntheticLoopName(), popScope(), predeclareModuleAliases(), predeclareModuleTypes(), predeclareModuleValues(), pushScope(), resolveModuleMember(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
declaredFunctionSymbols_
std::unordered_map<const Node *, std::shared_ptr<FunctionSymbol> > sema::Binder::declaredFunctionSymbols_ private
Definition at line 150 of file binder.hpp.
Referenced by bind(), predeclareModuleValues(), visit(), and visit().
expectedExpressionTypes_
std::vector<std::shared_ptr<zir::Type> > sema::Binder::expectedExpressionTypes_ private
Definition at line 125 of file binder.hpp.
Referenced by bindExpressionWithExpected(), and currentExpectedExpressionType().
expressionStack_
std::stack<std::unique_ptr<BoundExpression> > sema::Binder::expressionStack_ private
Definition at line 122 of file binder.hpp.
Referenced by bindExpressionWithExpected(), bindSizeOfBuiltinCall(), bindWeakBuiltinCall(), mapType(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
externTypeContextDepth_
int sema::Binder::externTypeContextDepth_ = 0 private
Definition at line 131 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), and visit().
functionDeclarationModuleIds_
std::unordered_map<const FunctionSymbol *, std::string> sema::Binder::functionDeclarationModuleIds_ private
Definition at line 161 of file binder.hpp.
Referenced by ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), and predeclareModuleValues().
functionDeclarationNodes_
std::unordered_map<const FunctionSymbol *, const FunDecl *> sema::Binder::functionDeclarationNodes_ private
Definition at line 159 of file binder.hpp.
Referenced by bind(), buildGenericBindings(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), and predeclareModuleValues().
functionGenericParamNames_
std::unordered_map<const FunctionSymbol *, std::vector<std::string> > sema::Binder::functionGenericParamNames_ private
Definition at line 163 of file binder.hpp.
Referenced by bind(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), predeclareModuleValues(), and renderFunctionSignature().
genericFunctionDeclarationKeys_
std::unordered_map<const FunctionSymbol *, std::string> sema::Binder::genericFunctionDeclarationKeys_ private
Definition at line 169 of file binder.hpp.
Referenced by bind().
genericFunctionInstantiations_
std::unordered_map<std::string, std::shared_ptr<FunctionSymbol> > sema::Binder::genericFunctionInstantiations_ private
Definition at line 165 of file binder.hpp.
Referenced by bind(), and ensureGenericFunctionInstantiation().
genericInstantiationEmitted_
std::unordered_map<const FunctionSymbol *, bool> sema::Binder::genericInstantiationEmitted_ private
Definition at line 170 of file binder.hpp.
Referenced by bind(), and ensureGenericFunctionInstantiation().
genericInstantiationInProgress_
std::vector<std::string> sema::Binder::genericInstantiationInProgress_ private
Definition at line 173 of file binder.hpp.
Referenced by bind(), and ensureGenericFunctionInstantiation().
genericTypeInstantiations_
std::unordered_map<std::string, std::shared_ptr<TypeSymbol> > sema::Binder::genericTypeInstantiations_ private
Definition at line 167 of file binder.hpp.
Referenced by bind(), and instantiateGenericTypeSymbol().
hadError_
bool sema::Binder::hadError_ = false private
Definition at line 318 of file binder.hpp.
Referenced by bind(), Binder(), error(), and visit().
loopDepth_
int sema::Binder::loopDepth_ = 0 private
Definition at line 127 of file binder.hpp.
Referenced by visit(), visit(), visit(), visit(), and visit().
mapTypeCache_
std::unordered_map<const TypeNode *, std::shared_ptr<zir::Type> > sema::Binder::mapTypeCache_ private
Definition at line 200 of file binder.hpp.
Referenced by mapType().
modules_
std::map<std::string, ModuleState> sema::Binder::modules_ private
Definition at line 148 of file binder.hpp.
Referenced by applyImports(), bind(), currentModuleLinkPath(), ensureGenericFunctionInstantiation(), ensureModuleValuesReady(), instantiateGenericTypeSymbol(), visit(), visit(), visit(), visit(), and visit().
recordTypeDeclarationNodes_
std::unordered_map<const TypeSymbol *, const RecordDecl *> sema::Binder::recordTypeDeclarationNodes_ private
Definition at line 152 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), predeclareModuleTypes(), and visit().
sawPrivacyError_
bool sema::Binder::sawPrivacyError_ = false private
Definition at line 319 of file binder.hpp.
Referenced by bind(), and error().
semanticInfo_
SemanticInfo* sema::Binder::semanticInfo_ = nullptr private
Definition at line 117 of file binder.hpp.
Referenced by Binder(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
statementStack_
std::stack<std::unique_ptr<BoundStatement> > sema::Binder::statementStack_ private
Definition at line 123 of file binder.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
structTypeDeclarationNodes_
std::unordered_map<const TypeSymbol *, const StructDeclarationNode *> sema::Binder::structTypeDeclarationNodes_ private
Definition at line 154 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), predeclareModuleTypes(), and visit().
syntheticLoopCounter_
size_t sema::Binder::syntheticLoopCounter_ = 0 private
Definition at line 128 of file binder.hpp.
Referenced by bind(), and makeSyntheticLoopName().
typeDeclarationModuleIds_
std::unordered_map<const TypeSymbol *, std::string> sema::Binder::typeDeclarationModuleIds_ private
Definition at line 157 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), and predeclareModuleTypes().
unsafeDepth_
int sema::Binder::unsafeDepth_ = 0 private
Definition at line 129 of file binder.hpp.
Referenced by bind(), ensureGenericFunctionInstantiation(), instantiateGenericTypeSymbol(), isUnsafeActive(), visit(), and visit().
unsafeTypeContextDepth_
int sema::Binder::unsafeTypeContextDepth_ = 0 private
Definition at line 130 of file binder.hpp.
Referenced by bind(), instantiateGenericTypeSymbol(), isUnsafeActive(), predeclareModuleValues(), and visit().
The documentation for this class was generated from the following files:
src/sema/binder.hpp
src/sema/binder.cpp
src/sema/binder_decls.cpp
src/sema/binder_exprs.cpp
src/sema/binder_stmts.cpp
src/sema/binder_types.cpp