ZAP: Visitor Struct Reference
Visitor Struct Reference
Visitor interface with empty implementations to allow selective overrides.
#include <visitor.hpp>
Public Member Functions
virtual ~Visitor () noexcept=default
virtual void visit (Node &)
virtual void visit (RootNode &)
virtual void visit (TopLevel &)
virtual void visit (FunDecl &)
virtual void visit (ExtDecl &)
virtual void visit (BodyNode &)
virtual void visit (StatementNode &)
virtual void visit (VarDecl &)
virtual void visit (ConstDecl &)
virtual void visit (ReturnNode &)
virtual void visit (IfNode &)
virtual void visit (WhileNode &)
virtual void visit (MemberAccessNode &)
virtual void visit (BreakNode &)
virtual void visit (ContinueNode &)
virtual void visit (EnumDecl &)
virtual void visit (RecordDecl &)
virtual void visit (TypeAliasDecl &)
virtual void visit (StructDeclarationNode &)
virtual void visit (StructLiteralNode &)
virtual void visit (ClassDecl &)
virtual void visit (ImportNode &)
virtual void visit (ParameterNode &)
virtual void visit (TypeNode &)
virtual void visit (IndexAccessNode &)
virtual void visit (UnsafeBlockNode &)
virtual void visit (ExpressionNode &)
virtual void visit (BinExpr &)
virtual void visit (TernaryExpr &)
virtual void visit (UnaryExpr &)
virtual void visit (CastExpr &)
virtual void visit (FunCall &)
virtual void visit (ArrayLiteralNode &)
virtual void visit (AssignNode &)
virtual void visit (NewExpr &)
virtual void visit (ConstInt &)
virtual void visit (ConstFloat &)
virtual void visit (ConstString &)
virtual void visit (ConstChar &)
virtual void visit (ConstBool &)
virtual void visit (ConstId &)
virtual void visit (ConstNull &)
Detailed Description
Visitor interface with empty implementations to allow selective overrides.
Definition at line 50 of file visitor.hpp.
Constructor & Destructor Documentation
~Visitor()
virtual Visitor::~Visitor () virtual default noexcept
Member Function Documentation
visit() [1/42]
virtual void Visitor::visit (ArrayLiteralNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 87 of file visitor.hpp.
{}
visit() [2/42]
virtual void Visitor::visit (AssignNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 88 of file visitor.hpp.
{}
visit() [3/42]
virtual void Visitor::visit (BinExpr &) inline virtual
Reimplemented in sema::Binder.
Definition at line 82 of file visitor.hpp.
{}
visit() [4/42]
virtual void Visitor::visit (BodyNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 59 of file visitor.hpp.
{}
visit() [5/42]
virtual void Visitor::visit (BreakNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 67 of file visitor.hpp.
{}
visit() [6/42]
virtual void Visitor::visit (CastExpr &) inline virtual
Reimplemented in sema::Binder.
Definition at line 85 of file visitor.hpp.
{}
visit() [7/42]
virtual void Visitor::visit (ClassDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 74 of file visitor.hpp.
{}
visit() [8/42]
virtual void Visitor::visit (ConstBool &) inline virtual
Reimplemented in sema::Binder.
Definition at line 95 of file visitor.hpp.
{}
visit() [9/42]
virtual void Visitor::visit (ConstChar &) inline virtual
Reimplemented in sema::Binder.
Definition at line 94 of file visitor.hpp.
{}
visit() [10/42]
virtual void Visitor::visit (ConstDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 62 of file visitor.hpp.
{}
visit() [11/42]
virtual void Visitor::visit (ConstFloat &) inline virtual
Reimplemented in sema::Binder.
Definition at line 92 of file visitor.hpp.
{}
visit() [12/42]
virtual void Visitor::visit (ConstId &) inline virtual
Reimplemented in sema::Binder.
Definition at line 96 of file visitor.hpp.
{}
visit() [13/42]
virtual void Visitor::visit (ConstInt &) inline virtual
Reimplemented in sema::Binder.
Definition at line 91 of file visitor.hpp.
{}
visit() [14/42]
virtual void Visitor::visit (ConstNull &) inline virtual
Reimplemented in sema::Binder.
Definition at line 97 of file visitor.hpp.
{}
visit() [15/42]
virtual void Visitor::visit (ConstString &) inline virtual
Reimplemented in sema::Binder.
Definition at line 93 of file visitor.hpp.
{}
visit() [16/42]
virtual void Visitor::visit (ContinueNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 68 of file visitor.hpp.
{}
visit() [17/42]
virtual void Visitor::visit (EnumDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 69 of file visitor.hpp.
{}
visit() [18/42]
virtual void Visitor::visit (ExpressionNode &) inline virtual
Definition at line 81 of file visitor.hpp.
{}
visit() [19/42]
virtual void Visitor::visit (ExtDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 58 of file visitor.hpp.
{}
visit() [20/42]
virtual void Visitor::visit (FunCall &) inline virtual
Reimplemented in sema::Binder.
Definition at line 86 of file visitor.hpp.
{}
visit() [21/42]
virtual void Visitor::visit (FunDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 57 of file visitor.hpp.
{}
visit() [22/42]
virtual void Visitor::visit (IfNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 64 of file visitor.hpp.
{}
visit() [23/42]
virtual void Visitor::visit (ImportNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 75 of file visitor.hpp.
{}
visit() [24/42]
virtual void Visitor::visit (IndexAccessNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 78 of file visitor.hpp.
{}
visit() [25/42]
virtual void Visitor::visit (MemberAccessNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 66 of file visitor.hpp.
{}
visit() [26/42]
virtual void Visitor::visit (NewExpr &) inline virtual
Reimplemented in sema::Binder.
Definition at line 89 of file visitor.hpp.
{}
visit() [27/42]
virtual void Visitor::visit (Node &) inline virtual
Definition at line 54 of file visitor.hpp.
{}
References visit().
Referenced by ArrayLiteralNode::accept(), AssignNode::accept(), BinExpr::accept(), BodyNode::accept(), CastExpr::accept(), ClassDecl::accept(), ConstBool::accept(), ConstChar::accept(), ConstDecl::accept(), ConstFloat::accept(), ConstId::accept(), ConstInt::accept(), ConstNull::accept(), ConstString::accept(), EnumDecl::accept(), ExtDecl::accept(), FunCall::accept(), FunDecl::accept(), IfNode::accept(), IndexAccessNode::accept(), MemberAccessNode::accept(), NewExpr::accept(), ParameterNode::accept(), RecordDecl::accept(), RootNode::accept(), StructDeclarationNode::accept(), StructLiteralNode::accept(), TernaryExpr::accept(), TypeAliasDecl::accept(), TypeNode::accept(), UnaryExpr::accept(), UnsafeBlockNode::accept(), VarDecl::accept(), WhileNode::accept(), and visit().
visit() [28/42]
virtual void Visitor::visit (ParameterNode &) inline virtual
Definition at line 76 of file visitor.hpp.
{}
visit() [29/42]
virtual void Visitor::visit (RecordDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 70 of file visitor.hpp.
{}
visit() [30/42]
virtual void Visitor::visit (ReturnNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 63 of file visitor.hpp.
{}
visit() [31/42]
virtual void Visitor::visit (RootNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 55 of file visitor.hpp.
{}
visit() [32/42]
virtual void Visitor::visit (StatementNode &) inline virtual
Definition at line 60 of file visitor.hpp.
{}
visit() [33/42]
virtual void Visitor::visit (StructDeclarationNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 72 of file visitor.hpp.
{}
visit() [34/42]
virtual void Visitor::visit (StructLiteralNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 73 of file visitor.hpp.
{}
visit() [35/42]
virtual void Visitor::visit (TernaryExpr &) inline virtual
Reimplemented in sema::Binder.
Definition at line 83 of file visitor.hpp.
{}
visit() [36/42]
virtual void Visitor::visit (TopLevel &) inline virtual
Definition at line 56 of file visitor.hpp.
{}
visit() [37/42]
virtual void Visitor::visit (TypeAliasDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 71 of file visitor.hpp.
{}
visit() [38/42]
virtual void Visitor::visit (TypeNode &) inline virtual
Definition at line 77 of file visitor.hpp.
{}
visit() [39/42]
virtual void Visitor::visit (UnaryExpr &) inline virtual
Reimplemented in sema::Binder.
Definition at line 84 of file visitor.hpp.
{}
visit() [40/42]
virtual void Visitor::visit (UnsafeBlockNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 79 of file visitor.hpp.
{}
visit() [41/42]
virtual void Visitor::visit (VarDecl &) inline virtual
Reimplemented in sema::Binder.
Definition at line 61 of file visitor.hpp.
{}
visit() [42/42]
virtual void Visitor::visit (WhileNode &) inline virtual
Reimplemented in sema::Binder.
Definition at line 65 of file visitor.hpp.
{}
The documentation for this struct was generated from the following file:
src/ast/visitor.hpp