ZAP: RootNode Class Reference
RootNode Class Reference
#include <root_node.hpp>
Public Member Functions
RootNode () noexcept=default
~RootNode () noexcept override=default
void addChild (std::unique_ptr< Node > child)
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::vector< std::unique_ptr< Node > > children
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 7 of file root_node.hpp.
Constructor & Destructor Documentation
RootNode()
RootNode::RootNode () default noexcept
Referenced by ~RootNode().
~RootNode()
RootNode::~RootNode () override default noexcept
References RootNode().
Member Function Documentation
accept()
void RootNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 22 of file root_node.hpp.
{ v.visit(*this); }
References Visitor::visit().
Referenced by sema::Binder::bind().
addChild()
void RootNode::addChild (std::unique_ptr< Node > child) inline
Definition at line 15 of file root_node.hpp.
{
    if (child) {
      children.push_back(std::move(child));
    } else {
      std::cerr << "Cannot add a null child to RootNode" << std::endl;
    }
  }
References addChild(), and children.
Referenced by addChild().
Member Data Documentation
children
std::vector<std::unique_ptr<Node> > RootNode::children
Definition at line 9 of file root_node.hpp.
Referenced by addChild(), sema::Binder::bind(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/root_node.hpp