ZAP: zap::driver Class Reference
zap::driver Class Reference
The class that drives the argument parsing. Order of the functions that should be called is by how they are defined here in the header. Meaning that first is parseArgs(int, char**), second is splitInputs(), third is verifySources(), and so on... Most functions return true on error not on success. It returns error due to easy checks like if(verifyOutput()) return 1;.
#include <driver.hpp>
Public Types
enum class output_type : uint8_t {
EXEC ,
OBJECT ,
ASM ,
TEXT_LLVM ,
LLVM ,
ZIR
}
Different output types that the driver (most likely) supports.
Public Member Functions
driver ()
void setExecutablePath (std::filesystem::path path)
bool parseArgs (int argc, char **argv)
Parses the provided args.
bool splitInputs ()
Splits inputs based on their file extension.
bool verifySources ()
Verifies that the sources provided actually exist or not.
bool verifyOutput ()
Checks if the output is valid or not.
bool compile ()
Compiles the files to the chosen output mode.
bool link ()
Links everything if the output mode requires it.
bool cleanup ()
Cleans up the files in the cleanup queue.
const std::vector< std::string > & get_inputs () const noexcept
Returns the unsplit input files vector.
const std::vector< std::filesystem::path > & get_sources () const noexcept
Returns the paths to the source files.
const std::filesystem::path & get_output () const noexcept
Returns the desired path of the output file.
bool is_implicit_output () const noexcept
Returns whether or not the output was explicit (-o) or not.
output_type get_output_type () const noexcept
Returns the chosen output type.
bool needs_linking () const noexcept
Returns whether or not the output type needs linking or not.
bool format_supported () const noexcept
Returns if the current selected format is supported by this compiler version.
bool binary_output () const noexcept
Returns whether the output is binary or text.
Static Public Member Functions
static constexpr const char * format_fileextension (output_type type) noexcept
Returns a file extension based on the file format given.
template<typename... Args>
static void reportError (Args &&...args)
template<typename... Args>
static void reportWarning (Args &&...args)
Private Member Functions
bool compileSourceFile (const std::string &source, const std::string &source_name)
Used internally by the compile() function.
Private Attributes
std::vector< std::string > inputs
A vector of input files.
std::vector< std::filesystem::path > sources
A vector of .zp files.
std::vector< std::filesystem::path > objects
A vector of .o files.
std::vector< std::filesystem::path > cleanups
A vector of files that need to be deleted.
std::filesystem::path output
Output file.
output_type out_type
Output type, default executable.
bool implicit_output
Was the output implicit or explicit.
bool inc_stdlib
Include the zap stdlib.o or not.
bool allow_unsafe = false
Allow unsafe language features.
std::filesystem::path executable_path
Path to the running executable.
Friends
bool compileLoadedModules (driver &drv, const std::filesystem::path &entryPath)
Detailed Description
The class that drives the argument parsing. Order of the functions that should be called is by how they are defined here in the header. Meaning that first is parseArgs(int, char**), second is splitInputs(), third is verifySources(), and so on... Most functions return true on error not on success. It returns error due to easy checks like if(verifyOutput()) return 1;.
Definition at line 16 of file driver.hpp.
Member Enumeration Documentation
output_type
enum class zap::driver::output_type : uint8_t strong
Different output types that the driver (most likely) supports.
See also
parseArgs(int, char**) implementation to see how it chooses the output type.
Enumerator
EXEC
Executable (default), link.
OBJECT
Object file, no linking.
ASM
Assembly.
TEXT_LLVM
Textual LLVM IR (-S -emit-llvm).
LLVM
LLVM IR (.bc).
ZIR
ZIR.
Definition at line 78 of file driver.hpp.
                         : uint8_t {
    EXEC,      ///< Executable (default), link.
    OBJECT,    ///< Object file, no linking.
    ASM,       ///< Assembly.
    TEXT_LLVM, ///< Textual LLVM IR (-S -emit-llvm).
    LLVM,      ///< LLVM IR (.bc).
    ZIR,       ///< ZIR.
  };
Constructor & Destructor Documentation
driver()
zap::driver::driver () default
References argc(), and argv().
Referenced by compileLoadedModules.
Member Function Documentation
binary_output()
bool zap::driver::binary_output () const inline noexcept
Returns whether the output is binary or text.
Returns
True if binary, false if text.
Definition at line 147 of file driver.hpp.
{
    switch (out_type) {
    case output_type::EXEC:
      [[fallthrough]];
    case output_type::OBJECT:
      [[fallthrough]];
    case output_type::LLVM:
      return true;
    case output_type::ASM:
      [[fallthrough]];
    case output_type::TEXT_LLVM:
      [[fallthrough]];
    case output_type::ZIR:
      return false;
    }
    return false;
  }
References ASM, EXEC, LLVM, OBJECT, out_type, TEXT_LLVM, and ZIR.
Referenced by compileLoadedModules, and compileSourceFile().
cleanup()
bool zap::driver::cleanup ()
Cleans up the files in the cleanup queue.
Returns
True if an error has occured. Should be called seventh after linking.
Definition at line 658 of file driver.cpp.
                     {
  bool errs = false;
  for (const std::filesystem::path &f : cleanups) {
    std::error_code ec;
    std::filesystem::remove(f, ec);
    if (ec) {
      errs = true;
      reportWarning("failed to remove: ", f, "\nreason: ", ec.message());
    }
  }
  return errs;
}
References cleanups, and reportWarning().
Referenced by main().
compile()
bool zap::driver::compile ()
Compiles the files to the chosen output mode.
Returns
True if an error has occured. Should be called fifth after checking that the output is valid.
Definition at line 621 of file driver.cpp.
                     {
  for (const std::filesystem::path &input : sources) {
    if (compileLoadedModules(*this, input))
      return true;
  }
  return false;
}
References compileLoadedModules, and sources.
Referenced by main().
compileSourceFile()
bool zap::driver::compileSourceFile (const std::string & source, const std::string & source_name) private
Used internally by the compile() function.
Returns
True if an error has occured.
Definition at line 530 of file driver.cpp.
{
  zap::DiagnosticEngine diagnostics(source, source_name);
  Lexer lex(diagnostics);
  auto tokens = lex.tokenize(source);
  zap::Parser parser(tokens, diagnostics);
  auto ast = parser.parse();
  if (diagnostics.hadErrors()) {
    diagnostics.printText(err());
    return true;
  }
  if (!ast) {
    diagnostics.printText(err());
    reportError(source_name, ": failed parsing the provided file");
    return true;
  }
  sema::Binder binder(diagnostics, allow_unsafe);
  auto boundAst = binder.bind(*ast);
  diagnostics.printText(err());
  if (!boundAst) {
    reportError(source_name, ": semantic analysis failed");
    return true;
  }
  if (binary_output()) {
    if (out_type == output_type::LLVM)
      return true; // TODO: Implement LLVM bitcode emission.
    std::filesystem::path out_path;
    if (out_type == output_type::EXEC) {
      out_path = source_name + ".o";
      cleanups.emplace_back(out_path);
    } else if (out_type == output_type::OBJECT) {
      if (implicit_output) {
        out_path = source_name + ".o";
      } else {
        out_path = output;
      }
    }
    codegen::LLVMCodeGen llvmGen;
    llvmGen.generate(*boundAst);
    if (!llvmGen.emitObjectFile(out_path.string())) {
      reportError("object file emission failed");
      return true;
    }
    objects.emplace_back(std::move(out_path));
  } else {
    std::filesystem::path out_path =
        implicit_output ? std::filesystem::path(source_name +
                                                format_fileextension(out_type))
                        : output;
    std::ofstream ofoutput(out_path, std::ios::binary);
    if (!ofoutput) {
      reportError("couldn't open the provided file: ", out_path,
                  "\nreason: ", strerror(errno));
      return true;
    }
    if (out_type == output_type::ZIR) {
      if (compileSourceZIR(*boundAst, ofoutput))
        return true;
    } else if (out_type == output_type::TEXT_LLVM) {
      codegen::LLVMCodeGen llvmGen;
      llvmGen.generate(*boundAst);
      // TODO: Avoid using LLVM types like raw_string_ostream here.
      std::string ir;
      llvm::raw_string_ostream rs(ir);
      llvmGen.printIR(rs);
      ofoutput << ir;
    } else if (out_type == output_type::ASM) {
      return true; // TODO: Implement assembly emission.
    } else {
      return true;
    }
  }
  return false;
}
References allow_unsafe, ASM, binary_output(), sema::Binder::bind(), cleanups, zap::compileSourceZIR(), codegen::LLVMCodeGen::emitObjectFile(), zap::err(), EXEC, format_fileextension(), codegen::LLVMCodeGen::generate(), zap::DiagnosticEngine::hadErrors(), implicit_output, LLVM, OBJECT, objects, out_type, output, zap::Parser::parse(), codegen::LLVMCodeGen::printIR(), zap::DiagnosticEngine::printText(), reportError(), TEXT_LLVM, Lexer::tokenize(), and ZIR.
format_fileextension()
constexpr const char * zap::driver::format_fileextension (output_type type) inline static constexpr noexcept
Returns a file extension based on the file format given.
Returns
Read-only string.
Definition at line 122 of file driver.hpp.
{
    switch (type) {
    default:
      [[fallthrough]];
    case output_type::EXEC: // This should depend on the target set, not host.
#ifdef _WIN32
      return ".exe";
#else
      return "";
#endif
    case output_type::OBJECT:
      return ".o";
    case output_type::ASM:
      return ".s";
    case output_type::TEXT_LLVM:
      return ".ll";
    case output_type::LLVM:
      return ".bc";
    case output_type::ZIR:
      return ".zir";
    }
  }
References ASM, EXEC, LLVM, OBJECT, TEXT_LLVM, and ZIR.
Referenced by compileLoadedModules, and compileSourceFile().
format_supported()
bool zap::driver::format_supported () const inline noexcept
Returns if the current selected format is supported by this compiler version.
Returns
True if supported, false if not. This should change as the compiler evolves, ideally all of the below should be true.
Definition at line 102 of file driver.hpp.
{
    switch (out_type) {
    case output_type::EXEC:
      [[fallthrough]];
    case output_type::OBJECT:
      [[fallthrough]];
    case output_type::ZIR:
      [[fallthrough]];
    case output_type::TEXT_LLVM:
      return true;
    case output_type::ASM:
      [[fallthrough]];
    case output_type::LLVM:
      return false;
    }
    return false;
  }
References ASM, EXEC, LLVM, OBJECT, out_type, TEXT_LLVM, and ZIR.
Referenced by verifyOutput().
get_inputs()
const std::vector< std::string > & zap::driver::get_inputs () const inline noexcept
Returns the unsplit input files vector.
Returns
Const reference to the input files vector.
Definition at line 59 of file driver.hpp.
{ return inputs; }
References inputs.
Referenced by splitInputs(), and verifyOutput().
get_output()
const std::filesystem::path & zap::driver::get_output () const inline noexcept
Returns the desired path of the output file.
Returns
Const reference to the output file path.
Definition at line 69 of file driver.hpp.
{ return output; }
References output.
Referenced by compileLoadedModules.
get_output_type()
output_type zap::driver::get_output_type () const inline noexcept
Returns the chosen output type.
Definition at line 88 of file driver.hpp.
{ return out_type; }
References out_type.
Referenced by compileLoadedModules, and verifyOutput().
get_sources()
const std::vector< std::filesystem::path > & zap::driver::get_sources () const inline noexcept
Returns the paths to the source files.
Returns
Const reference to the source files vector.
Definition at line 63 of file driver.hpp.
{
    return sources;
  }
References sources.
is_implicit_output()
bool zap::driver::is_implicit_output () const inline noexcept
Returns whether or not the output was explicit (-o) or not.
Returns
True if was implicit, false if explicit.
Definition at line 73 of file driver.hpp.
{ return implicit_output; }
References implicit_output.
Referenced by compileLoadedModules, and verifyOutput().
link()
bool zap::driver::link ()
Links everything if the output mode requires it.
Returns
True if an error has occured. Should be called sixth after compiling.
Definition at line 630 of file driver.cpp.
                  {
  if (!needs_linking())
    return false;
  std::string cmd = "/usr/bin/cc ";
  if (inc_stdlib) {
    cmd += std::string(ZAPC_STDLIB_PATH) + " ";
  } else {
    cmd += "-nostdlib ";
  }
  for (const auto &obj : objects) {
    cmd += obj.string() + " ";
  }
  cmd += "-lm ";
  cmd += "-o " + output.string();
  int res = std::system(cmd.c_str());
  if (res != 0) {
    reportError("linking failed with exit code: ", res);
    return true;
  }
  return false;
}
References inc_stdlib, needs_linking(), objects, output, and reportError().
Referenced by main().
needs_linking()
bool zap::driver::needs_linking () const inline noexcept
Returns whether or not the output type needs linking or not.
Returns
True if needs, false if not. This shouldn't be used along link() since it already checks it.
Definition at line 93 of file driver.hpp.
{
    return (out_type == output_type::EXEC);
  }
References EXEC, and out_type.
Referenced by link().
parseArgs()
bool zap::driver::parseArgs (int argc, char ** argv)
Parses the provided args.
Parameters
argc How many arguments.
argv Pointer to the arguments.
Returns
True if should continue compiling.
Definition at line 353 of file driver.cpp.
{
  std::vector<std::string_view> args;
  for (int i = 1; i < argc; ++i) {
    args.emplace_back(argv[i]);
  }
  bool emit_llvm = false;
  bool emit_zir = false;
  bool emit_s = false;
  bool nolink = false;
  std::string_view output_str = "a.out";
  implicit_output = true;
  inc_stdlib = true;
  allow_unsafe = false;
  for (size_t i = 0; i < args.size(); ++i) {
    auto arg = args[i];
    if (arg == "--help") {
      out()
          << "Zap Compiler [options] <file>\n"
          << "Zap Compiler\n\n"
          << "Options:\n"
          << "  --help          Display available options\n"
          << "  --version       Print version information\n"
          << "  -o <file>       Write output to <file>\n"
          << "  -nostdlib       Stops the linker from linking the zap stdlib\n"
          << "  -c              Compile and assemble but not link\n"
          << "  -S              Compile only no assembling or linking\n"
          << "  -emit-llvm      Emit LLVM IR instead of final output\n"
          << "  -emit-zir       Emit ZIR instead of final output\n"
          << "  --allow-unsafe  Enable unsafe blocks, unsafe functions, and raw pointers\n";
      return false;
    } else if (arg == "--version") {
      out() << "Zap Compiler v" << zap::ZAP_VERSION << '\n';
      return false;
    } else if (arg == "-o") {
      if (i + 1 < args.size()) {
        output_str = args[++i];
        implicit_output = false;
      } else {
        reportError("argument to '-o' is missing");
        return false;
      }
    } else if (arg.substr(0, 2) == "-o") {
      output_str = arg.substr(2);
      implicit_output = false;
    } else if (arg == "-nostdlib") {
      inc_stdlib = false;
    } else if (arg == "-c") {
      nolink = true;
    } else if (arg == "-S") {
      emit_s = true;
    } else if (arg == "-emit-llvm") {
      emit_llvm = true;
    } else if (arg == "-emit-zir") {
      emit_zir = true;
    } else if (arg == "--allow-unsafe") {
      allow_unsafe = true;
    } else if (arg.substr(0, 1) == "-") {
      reportError("unknown argument: ", arg);
      return false;
    } else {
      inputs.emplace_back(std::string(arg));
    }
  }
  if (emit_llvm && emit_zir) {
    reportError("choosing multiple emit modes isn't allowed");
    return false;
  }
  if (emit_s) {
    if (emit_llvm)
      out_type = output_type::TEXT_LLVM;
    else
      out_type = output_type::ASM;
  } else if (emit_llvm)
    out_type = output_type::LLVM;
  if (emit_zir)
    out_type = output_type::ZIR;
  if (out_type == output_type::EXEC) {
    if (nolink) {
      out_type = output_type::OBJECT;
    }
  }
  output = std::filesystem::path(output_str);
  if (!inputs.empty()) {
    return true;
  }
  reportError("no input files");
  return false;
}
References allow_unsafe, argc(), argv(), ASM, EXEC, implicit_output, inc_stdlib, inputs, LLVM, OBJECT, zap::out(), out_type, output, reportError(), TEXT_LLVM, zap::ZAP_VERSION(), and ZIR.
Referenced by main().
reportError()
template<typename... Args> void zap::driver::reportError (Args &&... args) inline static
Definition at line 165 of file driver.hpp.
{
    ((err() << "zapc: ").changeColor(Color::RED, true) << "error: ")
        .resetColor();
    (err() << ... << args);
    err() << '\n';
  }
References zap::err(), and zap::RED.
Referenced by compileLoadedModules, compileSourceFile(), zap::compileSourceZIR(), link(), zap::anonymous_namespace{driver.cpp}::loadModuleGraph(), parseArgs(), zap::anonymous_namespace{driver.cpp}::readSourceFile(), zap::anonymous_namespace{driver.cpp}::resolveImportTargets(), splitInputs(), zap::verifyFile(), and verifyOutput().
reportWarning()
template<typename... Args> void zap::driver::reportWarning (Args &&... args) inline static
Definition at line 172 of file driver.hpp.
{
    ((err() << "zapc: ").changeColor(Color::YELLOW, true) << "warning: ")
        .resetColor();
    (err() << ... << args);
    err() << '\n';
  }
References zap::err(), and zap::YELLOW.
Referenced by cleanup().
setExecutablePath()
void zap::driver::setExecutablePath (std::filesystem::path path)
Definition at line 254 of file driver.cpp.
{
  executable_path = std::move(path);
  g_executable_path = executable_path;
}
References executable_path.
Referenced by main().
splitInputs()
bool zap::driver::splitInputs ()
Splits inputs based on their file extension.
Returns
True if an error has occured. This should be called second so that verifyOutput() can work.
Definition at line 452 of file driver.cpp.
{
  for (const std::string &input : get_inputs()) {
    std::filesystem::path input_path = input;
    std::string ext = input_path.extension().string();
    std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
    if (ext == ".zp") {
      sources.emplace_back(std::move(input_path));
    } else if (ext == ".a" || ext == ".o") {
      objects.emplace_back(std::move(input_path));
    } else {
      reportError("unknown input type: ", input);
      return true;
    }
  }
  return false;
}
References get_inputs(), objects, reportError(), and sources.
Referenced by main().
verifyOutput()
bool zap::driver::verifyOutput ()
Checks if the output is valid or not.
Returns
True if invalid. This should be called fourth after checking the source/object files.
Definition at line 471 of file driver.cpp.
{
  const zap::driver::output_type &emit_type = get_output_type();
  bool per_file_emit = (emit_type != output_type::EXEC);
  if (per_file_emit && get_inputs().size() > 1 && !is_implicit_output()) {
    reportError("cannot specify -o with multiple input files");
    return true;
  }
  if (per_file_emit && !objects.empty()) {
    reportError(
        "cannot use object files or archives with the selected output mode");
    return true;
  }
  if (!format_supported()) {
    reportError("chosen file output mode is not yet supported in this version");
    return true;
  }
  return false;
}
References EXEC, format_supported(), get_inputs(), get_output_type(), is_implicit_output(), objects, and reportError().
Referenced by main().
verifySources()
bool zap::driver::verifySources ()
Verifies that the sources provided actually exist or not.
Returns
True if an error has occured. This should be called third after splitting the input files.
Definition at line 506 of file driver.cpp.
{
  for (const std::filesystem::path &input : sources) {
    if (verifyFile(input))
      return true;
  }
  for (const std::filesystem::path &input : objects) {
    if (verifyFile(input))
      return true;
  }
  return false;
}
References objects, sources, and zap::verifyFile().
Referenced by main().
Friends And Related Symbol Documentation
compileLoadedModules
bool compileLoadedModules (driver & drv, const std::filesystem::path & entryPath) friend
Definition at line 259 of file driver.cpp.
{
  std::map<std::string, std::unique_ptr<sema::ModuleInfo>> moduleMap;
  std::set<std::string> visiting;
  if (loadModuleGraph(entryPath, moduleMap, visiting)) {
    return true;
  }
  auto entryId = std::filesystem::weakly_canonical(entryPath).string();
  if (moduleMap.find(entryId) == moduleMap.end()) {
    driver::reportError("failed to load entry module: ", entryPath);
    return true;
  }
  moduleMap[entryId]->isEntry = true;
  std::string entrySource;
  if (readSourceFile(entryPath, entrySource)) {
    return true;
  }
  DiagnosticEngine diagnostics(entrySource, entryPath.string());
  std::vector<sema::ModuleInfo> modules;
  modules.reserve(moduleMap.size());
  for (auto &[_, module] : moduleMap) {
    modules.push_back(std::move(*module));
  }
  sema::Binder binder(diagnostics, drv.allow_unsafe);
  auto boundAst = binder.bind(modules);
  diagnostics.printText(err());
  if (!boundAst) {
    driver::reportError(entryPath, ": semantic analysis failed");
    return true;
  }
  if (drv.binary_output()) {
    if (drv.get_output_type() == driver::output_type::LLVM)
      return true;
    std::filesystem::path out_path;
    if (drv.get_output_type() == driver::output_type::EXEC) {
      out_path = entryPath.string() + ".o";
      drv.cleanups.emplace_back(out_path);
    } else if (drv.get_output_type() == driver::output_type::OBJECT) {
      if (drv.is_implicit_output()) {
        out_path = entryPath.string() + ".o";
      } else {
        out_path = drv.get_output();
      }
    }
    codegen::LLVMCodeGen llvmGen;
    llvmGen.generate(*boundAst);
    if (!llvmGen.emitObjectFile(out_path.string())) {
      driver::reportError("object file emission failed");
      return true;
    }
    drv.objects.emplace_back(std::move(out_path));
  } else {
    std::filesystem::path out_path =
        drv.is_implicit_output()
            ? std::filesystem::path(entryPath.string() +
                                    driver::format_fileextension(drv.get_output_type()))
            : drv.get_output();
    std::ofstream ofoutput(out_path, std::ios::binary);
    if (!ofoutput) {
      driver::reportError("couldn't open the provided file: ", out_path,
                          "\nreason: ", strerror(errno));
      return true;
    }
    if (drv.get_output_type() == driver::output_type::ZIR) {
      if (compileSourceZIR(*boundAst, ofoutput))
        return true;
    } else if (drv.get_output_type() == driver::output_type::TEXT_LLVM) {
      codegen::LLVMCodeGen llvmGen;
      llvmGen.generate(*boundAst);
      std::string ir;
      llvm::raw_string_ostream rs(ir);
      llvmGen.printIR(rs);
      ofoutput << ir;
    } else {
      return true;
    }
  }
  return false;
}
References allow_unsafe, binary_output(), sema::Binder::bind(), cleanups, zap::compileSourceZIR(), driver(), codegen::LLVMCodeGen::emitObjectFile(), zap::err(), EXEC, format_fileextension(), codegen::LLVMCodeGen::generate(), get_output(), get_output_type(), is_implicit_output(), LLVM, OBJECT, objects, codegen::LLVMCodeGen::printIR(), zap::DiagnosticEngine::printText(), reportError(), TEXT_LLVM, and ZIR.
Referenced by compile().
Member Data Documentation
allow_unsafe
bool zap::driver::allow_unsafe = false private
Allow unsafe language features.
Definition at line 193 of file driver.hpp.
Referenced by compileLoadedModules, compileSourceFile(), and parseArgs().
cleanups
std::vector<std::filesystem::path> zap::driver::cleanups private
A vector of files that need to be deleted.
Definition at line 187 of file driver.hpp.
Referenced by cleanup(), compileLoadedModules, and compileSourceFile().
executable_path
std::filesystem::path zap::driver::executable_path private
Path to the running executable.
Definition at line 194 of file driver.hpp.
Referenced by setExecutablePath().
implicit_output
bool zap::driver::implicit_output private
Was the output implicit or explicit.
Definition at line 191 of file driver.hpp.
Referenced by compileSourceFile(), is_implicit_output(), and parseArgs().
inc_stdlib
bool zap::driver::inc_stdlib private
Include the zap stdlib.o or not.
Definition at line 192 of file driver.hpp.
Referenced by link(), and parseArgs().
inputs
std::vector<std::string> zap::driver::inputs private
A vector of input files.
Definition at line 183 of file driver.hpp.
Referenced by get_inputs(), and parseArgs().
objects
std::vector<std::filesystem::path> zap::driver::objects private
A vector of .o files.
Definition at line 185 of file driver.hpp.
Referenced by compileLoadedModules, compileSourceFile(), link(), splitInputs(), verifyOutput(), and verifySources().
out_type
output_type zap::driver::out_type private
Initial value:
=
      driver::output_type::EXEC
Output type, default executable.
Definition at line 189 of file driver.hpp.
Referenced by binary_output(), compileSourceFile(), format_supported(), get_output_type(), needs_linking(), and parseArgs().
output
std::filesystem::path zap::driver::output private
Output file.
Definition at line 188 of file driver.hpp.
Referenced by compileSourceFile(), get_output(), link(), and parseArgs().
sources
std::vector<std::filesystem::path> zap::driver::sources private
A vector of .zp files.
Definition at line 184 of file driver.hpp.
Referenced by compile(), get_sources(), splitInputs(), and verifySources().
The documentation for this class was generated from the following files:
src/driver/driver.hpp
src/driver/driver.cpp