ZAP: zap::args Namespace Reference
zap::args Namespace Reference
Classes
class ArgConf
struct ArgVal
class ArgHolder
struct CmdlineArgs
Typedefs
using FilePath = std::filesystem::path
using ImportMap = std::unordered_map<std::string, std::string>
Enumerations
enum class ArgTypes : unsigned { ZAP_FLAG }
enum class ParseResult {
Success ,
Failed ,
SkipCompilation
}
enum class OutputType : uint8_t {
EXEC ,
OBJECT ,
ASM ,
TEXT_LLVM ,
LLVM ,
ZIR
}
Different output types that the driver (most likely) supports.
enum class OptLevel : uint8_t {
O0 ,
O1 ,
O2 ,
O3
}
Optimization level used by the compiler.
Functions
ParseResult parse (const std::vector< std::string_view > &cmdline, CmdlineArgs &args)
Parses command line arguments from provided vector of string views.
ParseResult parse (int argc, char **argv, CmdlineArgs &args)
Parses command line arguments from provided argc & argv.
ParseResult parse (const std::vector< std::string > &argv, CmdlineArgs &args)
Parses command line arguments from provided vector of strings.
Variables
const std::unordered_map< std::string_view, ArgConf > arg_map
Ideally use a specialized string map.
Typedef Documentation
FilePath
using zap::args::FilePath = std::filesystem::path
Definition at line 10 of file args.hpp.
ImportMap
using zap::args::ImportMap = std::unordered_map<std::string, std::string>
Definition at line 11 of file args.hpp.
Enumeration Type Documentation
ArgTypes
enum class zap::args::ArgTypes : unsigned strong
Enumerator
ZAP_FLAG
This file includes the flags for the zapc driver.
The macro itself follows a simple format: ZAP_FLAG(ID /* Name of the Enum ‍/ Flag / The flag's string ‍/ HelpMessage / The message that displays when –help is used. ‍/ Kind / Kind of the arg (Flag, Joined, etc..) *‍/)
Definition at line 26 of file argparse.cpp.
                    : unsigned {
#define ZAP_FLAG(ID, ...) ID,
#include "flags.inc"
#undef ZAP_FLAG
  ARGS_END
};
OptLevel
enum class zap::args::OptLevel : uint8_t strong
Optimization level used by the compiler.
Enumerator
O0
No optimization.
O1
Less optimizations.
O2
Standard optimization level.
O3
More optimizations.
Definition at line 24 of file args.hpp.
                    : uint8_t {
  O0, ///< No optimization.
  O1, ///< Less optimizations.
  O2, ///< Standard optimization level.
  O3, ///< More optimizations.
};
OutputType
enum class zap::args::OutputType : uint8_t strong
Different output types that the driver (most likely) supports.
Enumerator
EXEC
Executable (default), link.
OBJECT
Object file, no linking.
ASM
Assembly.
TEXT_LLVM
Textual LLVM IR (-S -emit-llvm).
LLVM
LLVM IR (.bc).
ZIR
ZIR.
Definition at line 14 of file args.hpp.
                      : uint8_t {
  EXEC,      ///< Executable (default), link.
  OBJECT,    ///< Object file, no linking.
  ASM,       ///< Assembly.
  TEXT_LLVM, ///< Textual LLVM IR (-S -emit-llvm).
  LLVM,      ///< LLVM IR (.bc).
  ZIR,       ///< ZIR.
};
ParseResult
enum class zap::args::ParseResult strong
Enumerator
Success
Failed
SkipCompilation
Definition at line 22 of file argparse.hpp.
                       {
  Success,
  Failed,
  SkipCompilation,
};
Function Documentation
parse() [1/3]
ParseResult zap::args::parse (const std::vector< std::string > & argv, CmdlineArgs & args)
Parses command line arguments from provided vector of strings.
Returns
Success on success, Failed on error, SkipCompilation if help/version was printed.
Definition at line 292 of file argparse.cpp.
{
  std::vector<std::string_view> views;
  views.reserve(argv.size());
  for (const auto &arg : argv) {
    views.emplace_back(arg);
  }
  return parse(views, args);
}
References argv(), and parse().
parse() [2/3]
ParseResult zap::args::parse (const std::vector< std::string_view > & cmdline, CmdlineArgs & args)
Parses command line arguments from provided vector of string views.
Returns
Success on success, Failed on error, SkipCompilation if help/version was printed.
This file includes the flags for the zapc driver.
The macro itself follows a simple format: ZAP_FLAG(ID /* Name of the Enum ‍/ Flag / The flag's string ‍/ HelpMessage / The message that displays when –help is used. ‍/ Kind / Kind of the arg (Flag, Joined, etc..) *‍/)
Definition at line 105 of file argparse.cpp.
{
  bool ok = true;
  std::vector<ArgVal> argsvec;
  for (size_t i = 1; i < cmdline.size(); i++) {
    std::string_view original(cmdline[i]);
    if (original[0] == '-') {
      constexpr std::string_view targetPrefix = "--target=";
      if (original.rfind(targetPrefix, 0) == 0) {
        argsvec.emplace_back(original, original.substr(targetPrefix.size()),
                             ArgTypes::Target);
        continue;
      }
      if (auto it = arg_map.find(original); it != arg_map.end()) {
        const ArgConf &conf = it->second;
        if (conf.getKind() == ArgConf::ArgKind::Flag) {
          argsvec.emplace_back(original, std::string_view(), conf.getType());
        } else {
          if (i + 1 == cmdline.size()) {
            reportError("missing value for flag '", it->first, "'");
            ok = false;
            break;
          }
          argsvec.emplace_back(original, cmdline[i + 1], conf.getType());
          i++;
        }
      } else {
        const ArgConf *maybeConf = nullptr;
        size_t offset = 0;
#define ZAP_FLAG(ID, STR, MSG, KIND, ...)                                      \
  if constexpr (ArgConf::ArgKind::KIND == ArgConf::ArgKind::Joined ||          \
                ArgConf::ArgKind::KIND == ArgConf::ArgKind::JoinedSeparate) {  \
    if (original.size() >= (sizeof(STR) - 1)) {                                \
      auto it = arg_map.find(original.substr(0, (sizeof(STR) - 1)));           \
      if (it != arg_map.end()) {                                               \
        maybeConf = &it->second;                                               \
        offset = sizeof(STR) - 1;                                              \
        goto match_found;                                                      \
      }                                                                        \
    }                                                                          \
  }
#include "flags.inc"
#undef ZAP_FLAG
        reportError("unknown flag '", original, "' encountered");
        ok = false;
      match_found:
        argsvec.emplace_back(original, original.substr(offset),
                             maybeConf->getType());
      }
    } else {
      args.inputs.emplace_back(original);
    }
  }
  if (!ok)
    return ParseResult::Failed;
  ArgHolder holder(argsvec);
  if (holder.has(ArgTypes::Help)) {
    printHelp();
    return ParseResult::SkipCompilation;
  }
  if (holder.has(ArgTypes::Version)) {
    printVersion();
    return ParseResult::SkipCompilation;
  }
  if (holder.has(ArgTypes::PrintStdlibPath)) {
    args.printStdlibPath = true;
    return ParseResult::Success;
  }
  if (holder.has(ArgTypes::PrintCorePath)) {
    args.printCorePath = true;
    return ParseResult::Success;
  }
  args.output.implicit = !holder.has(ArgTypes::Output);
  args.freestanding = holder.has(ArgTypes::Freestanding);
  args.incStdlib = !args.freestanding && !holder.has(ArgTypes::NoStdlib);
  args.incPrelude = !args.freestanding && !holder.has(ArgTypes::NoPrelude);
  bool emitS = holder.has(ArgTypes::CompileOnlyS);
  bool compileOnly = holder.has(ArgTypes::CompileOnly);
  bool emitLLVM = holder.has(ArgTypes::EmitLLVM);
  bool emitZIR = holder.has(ArgTypes::EmitZIR);
  if (holder.has(ArgTypes::OptLevel)) {
    std::string_view optL = holder.get(ArgTypes::OptLevel)->optional;
    if (optL == "0") {
      args.optLevel = OptLevel::O0;
    } else if (optL == "1") {
      args.optLevel = OptLevel::O1;
    } else if (optL == "2") {
      args.optLevel = OptLevel::O2;
    } else if (optL == "3") {
      args.optLevel = OptLevel::O3;
    } else {
      reportError("unknown optimization value '", optL, "' encountered");
      ok = false;
    }
  } else
    args.optLevel = OptLevel::O0;
  if (!ok)
    return ParseResult::Failed;
  if (holder.has(ArgTypes::Target)) {
    std::string_view target = holder.get(ArgTypes::Target)->optional;
    if (target.empty()) {
      reportError("--target requires a target triple");
      return ParseResult::Failed;
    }
    args.targetTriple = std::string(target);
  }
  for (const ArgVal *arg : holder.getAll(ArgTypes::LinkDir)) {
    std::string val = "-L";
    val += arg->optional;
    args.linkerArgs.emplace_back(std::move(val));
  }
  for (const ArgVal *arg : holder.getAll(ArgTypes::LinkLib)) {
    std::string val = "-l";
    val += arg->optional;
    args.linkerArgs.emplace_back(std::move(val));
  }
  for (const ArgVal *arg : holder.getAll(ArgTypes::ImportMap)) {
    std::string_view entry = arg->optional;
    auto eq = entry.find('=');
    if (eq == std::string_view::npos) {
      reportError("--import-map requires format alias=path, got: ", entry);
      ok = false;
      continue;
    }
    args.importMap[std::string(entry.substr(0, eq))] =
        std::string(entry.substr(eq + 1));
  }
  if (!ok)
    return ParseResult::Failed;
  if (emitZIR) {
    args.output.type = OutputType::ZIR;
  } else if (emitLLVM) {
    args.output.type = emitS ? OutputType::TEXT_LLVM : OutputType::LLVM;
  } else if (emitS) {
    args.output.type = OutputType::ASM;
  } else if (compileOnly) {
    args.output.type = OutputType::OBJECT;
  }
  if ((emitLLVM || emitZIR) && !args.output.implicit && (emitLLVM == emitZIR)) {
    reportError("cannot use -o when emitting multiple text outputs");
    return ParseResult::Failed;
  }
  args.output.path = holder.has(ArgTypes::Output)
                         ? holder.get(ArgTypes::Output)->optional
                         : "a.out";
  if (args.inputs.empty()) {
    reportError("no input files");
    return ParseResult::Failed;
  }
  return ParseResult::Success;
}
References arg_map, ASM, eq(), Failed, zap::args::ArgConf::Flag, zap::args::ArgHolder::get(), zap::args::ArgHolder::getAll(), zap::args::ArgConf::getKind(), zap::args::ArgConf::getType(), zap::args::ArgHolder::has(), LLVM, O0, O1, O2, O3, OBJECT, zap::args::ArgVal::optional, zap::printHelp(), zap::printVersion(), zap::reportError(), SkipCompilation, Success, TEXT_LLVM, and ZIR.
Referenced by parse(), parse(), zap::driver::parseArgs(), and zap::lsp::anonymous_namespace{protocol_utils.cpp}::readFlagsFromFile().
parse() [3/3]
ParseResult zap::args::parse (int argc, char ** argv, CmdlineArgs & args)
Parses command line arguments from provided argc & argv.
Returns
Success on success (no way), Failed on error, SkipCompilation if help/version was printed.
Definition at line 281 of file argparse.cpp.
{
  std::vector<std::string_view> views;
  views.reserve(argc);
  for (int i = 0; i < argc; ++i) {
    views.emplace_back(argv[i]);
  }
  return parse(views, args);
}
References argc(), argv(), and parse().
Variable Documentation
arg_map
const std::unordered_map<std::string_view, ArgConf> zap::args::arg_map
Ideally use a specialized string map.
Definition at line 50 of file argparse.cpp.
                                                          {{
#define ZAP_FLAG(ID, STR, MSG, KIND, ...)                                      \
  {STR, ArgConf(ArgConf::ArgKind::KIND, ArgTypes::ID)},
#include "flags.inc"
#undef ZAP_FLAG
}};
Referenced by parse().