ZAP: src/stdlib.c File Reference
stdlib.c File Reference
#include "runtime/arc_layout.h"
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <math.h>
#include <netdb.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
Classes
struct zap_arc_metadata_t
struct zap_arc_header_t
struct zap_arc_ptrmap_t
struct zap_string_t
struct zap_string_owner_entry_t
struct zap_string_header_t
Typedefs
typedef struct zap_arc_metadata_t zap_arc_metadata_t
typedef struct zap_arc_header_t zap_arc_header_t
typedef struct zap_string_owner_entry_t zap_string_owner_entry_t
Functions
void zap_arc_add_possible_root (void *object)
void zap_arc_remove_possible_root (void *object)
static size_t zap_arc_hash_ptr (void *p)
static int zap_arc_ptrmap_init (zap_arc_ptrmap_t *m, size_t cap)
static void zap_arc_ptrmap_clear (zap_arc_ptrmap_t *m)
static int zap_arc_ptrmap_get (const zap_arc_ptrmap_t *m, void *key, uint32_t *out_index)
static int zap_arc_ptrmap_grow (zap_arc_ptrmap_t *m)
static int zap_arc_ptrmap_put (zap_arc_ptrmap_t *m, void *key, uint32_t value)
static int zap_arc_ws_push (void ***ws, size_t *count, size_t *cap, zap_arc_ptrmap_t *map, void *object)
static int zap_arc_ensure_scratch (size_t n)
void zap_arc_cycle_collect (void)
__attribute__ ((destructor))
void printInt (long v)
void printFloat (float v)
void printFloat64 (double v)
long zap_sum_variadic (long count,...)
void printBool (_Bool v)
void printChar (char v)
void printStringPtrLen (const char *ptr, long len)
static void zap_string_register_owned_ptr (const char *ptr)
static char * zap_string_alloc_owned (size_t len)
char * string_concat_ptrlen (const char *a, long a_len, const char *b, long b_len)
static zap_string_owner_entry_t * zap_string_find_owner (const char *ptr)
static void zap_string_unregister_owned_ptr (const char *ptr)
static zap_string_header_t * zap_string_header_from_ptr (const char *ptr)
static void zap_string_retain_ptr (const char *ptr)
static void zap_string_release_ptr (const char *ptr)
void print (zap_string_t s)
static char * zap_string_to_cstr (zap_string_t s)
static zap_string_t zap_string_from_owned (char *owned)
zap_string_t zap_string_from_cstr (const char *cstr)
zap_string_t zap_string_from_ptrlen (const char *ptr, long len)
zap_string_t zap_string_retain (zap_string_t s)
void zap_string_release (zap_string_t s)
static zap_string_t zap_string_from_format (const char *format,...)
zap_string_t zap_to_string_i64 (int64_t value)
zap_string_t zap_to_string_u64 (uint64_t value)
zap_string_t zap_to_string_f64 (double value)
long zap_to_int_from_char (char value)
char zap_to_char_from_int (long value)
void __zap_process_set_args (int argc, char **argv)
void println (zap_string_t s)
long zap_printf (zap_string_t format,...)
long zap_printfln (zap_string_t format,...)
void eprintln (zap_string_t s)
void println_cstr (const char *s)
zap_string_t getLn ()
long argc ()
zap_string_t argv (long i)
long len (zap_string_t s)
char at (zap_string_t s, long i)
zap_string_t slice (zap_string_t s, long start, long length)
_Bool eq (zap_string_t a, zap_string_t b)
long exec (zap_string_t cmd)
zap_string_t cwd ()
static int zap_stat_path (zap_string_t path, struct stat *st)
static char * zap_copy_path (zap_string_t path)
static int zap_net_bind_addrinfo (const char *host, long port, int socktype, int flags, struct addrinfo **out)
_Bool exists (zap_string_t path)
_Bool isFile (zap_string_t path)
_Bool isDir (zap_string_t path)
long zap_fs_mkdir (zap_string_t path)
long zap_fs_remove (zap_string_t path)
long zap_fs_rename (zap_string_t from, zap_string_t to)
zap_string_t readFile (zap_string_t path)
long writeFile (zap_string_t path, zap_string_t content)
static zap_string_t zap_copy_string_range (const char *start, size_t len)
double zapMathSqrt (double x)
double zapMathFloor (double x)
double zapMathCeil (double x)
long netConnect (zap_string_t host, long port)
long netListen (zap_string_t host, long port)
long netAccept (long listenerFd)
long netClose (long fd)
long netSend (long fd, zap_string_t data)
zap_string_t netRecv (long fd, long maxLen)
zap_string_t netResolve (zap_string_t host)
long netLastError ()
Variables
static void ** zap_arc_roots = NULL
static size_t zap_arc_root_count = 0
static size_t zap_arc_root_capacity = 0
static int zap_arc_collecting = 0
static int zap_net_last_error = 0
static void ** zap_arc_snap = NULL
static size_t zap_arc_snap_cap = 0
static void ** zap_arc_ws = NULL
static size_t zap_arc_ws_cap = 0
static int * zap_arc_incoming = NULL
static uint8_t * zap_arc_reachable = NULL
static uint32_t * zap_arc_stack = NULL
static size_t zap_arc_scratch_cap = 0
static zap_arc_ptrmap_t zap_arc_map = {NULL, NULL, 0, 0}
static zap_string_owner_entry_t * zap_string_owners = NULL
static const uint64_t ZAP_STRING_HEADER_MAGIC = 0x5A41505354524E47ULL
static long zap_process_argc = 0
static char ** zap_process_argv = NULL
Typedef Documentation
zap_arc_header_t
typedef struct zap_arc_header_t zap_arc_header_t
zap_arc_metadata_t
typedef struct zap_arc_metadata_t zap_arc_metadata_t
zap_string_owner_entry_t
typedef struct zap_string_owner_entry_t zap_string_owner_entry_t
Function Documentation
__attribute__()
__attribute__ ((destructor))
Definition at line 403 of file stdlib.c.
{
  free(zap_arc_roots);
  free(zap_arc_snap);
  free(zap_arc_ws);
  free(zap_arc_incoming);
  free(zap_arc_reachable);
  free(zap_arc_stack);
  free(zap_arc_map.keys);
  free(zap_arc_map.vals);
  zap_arc_roots = NULL;
  zap_arc_snap = NULL;
  zap_arc_ws = NULL;
  zap_arc_incoming = NULL;
  zap_arc_reachable = NULL;
  zap_arc_stack = NULL;
  zap_arc_map.keys = NULL;
  zap_arc_map.vals = NULL;
}
References zap_arc_incoming, zap_arc_map, zap_arc_reachable, zap_arc_roots, zap_arc_snap, zap_arc_stack, and zap_arc_ws.
__zap_process_set_args()
void __zap_process_set_args (int argc, char ** argv)
Definition at line 691 of file stdlib.c.
{
  zap_process_argc = argc;
  zap_process_argv = argv;
}
References argc(), argv(), zap_process_argc, and zap_process_argv.
argc()
long argc ()
Definition at line 774 of file stdlib.c.
{ return zap_process_argc; }
References zap_process_argc.
Referenced by __zap_process_set_args(), zap::driver::driver(), main(), and zap::driver::parseArgs().
argv()
zap_string_t argv (long i)
Definition at line 776 of file stdlib.c.
{
  if (i < 0 || i >= zap_process_argc || !zap_process_argv ||
      !zap_process_argv[i]) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  const char *arg = zap_process_argv[i];
  return (zap_string_t){.ptr = arg, .len = (long)strlen(arg)};
}
References zap_process_argc, and zap_process_argv.
Referenced by __zap_process_set_args(), zap::driver::driver(), main(), and zap::driver::parseArgs().
at()
char at (zap_string_t s, long i)
Definition at line 788 of file stdlib.c.
{
  if (!s.ptr || i < 0 || i >= s.len) {
    return '\0';
  }
  return s.ptr[i];
}
References zap_string_t::len, and zap_string_t::ptr.
Referenced by codegen::LLVMCodeGen::toLLVMType().
cwd()
zap_string_t cwd ()
Definition at line 867 of file stdlib.c.
                   {
  char *dir = getcwd(NULL, 0);
  if (!dir) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  size_t dir_len = strlen(dir);
  char *owned = zap_string_alloc_owned(dir_len);
  if (!owned) {
    free(dir);
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  if (dir_len > 0) {
    memcpy(owned, dir, dir_len);
  }
  owned[dir_len] = '\0';
  free(dir);
  return (zap_string_t){.ptr = owned, .len = (long)dir_len};
}
References zap_string_alloc_owned().
eprintln()
void eprintln (zap_string_t s)
Definition at line 731 of file stdlib.c.
{
  if (!s.ptr || s.len <= 0) {
    fputc('\n', stderr);
    return;
  }
  fwrite(s.ptr, 1, (size_t)s.len, stderr);
  fputc('\n', stderr);
}
References zap_string_t::len, and zap_string_t::ptr.
eq()
_Bool eq (zap_string_t a, zap_string_t b)
Definition at line 824 of file stdlib.c.
{
  if (a.len != b.len) {
    return 0;
  }
  if (a.len == 0) {
    return 1;
  }
  if (!a.ptr || !b.ptr) {
    return 0;
  }
  return memcmp(a.ptr, b.ptr, (size_t)a.len) == 0;
}
References zap_string_t::len, and zap_string_t::ptr.
exec()
long exec (zap_string_t cmd)
Definition at line 840 of file stdlib.c.
{
  if (!cmd.ptr) {
    return -1;
  }
  char *buffer = (char *)malloc((size_t)cmd.len + 1);
  if (!buffer) {
    return -1;
  }
  memcpy(buffer, cmd.ptr, (size_t)cmd.len);
  buffer[cmd.len] = '\0';
  int result = system(buffer);
  free(buffer);
  if (result == -1) {
    return -1;
  }
  if (WIFEXITED(result)) {
    return WEXITSTATUS(result);
  }
  return result;
}
References zap_string_t::len, and zap_string_t::ptr.
exists()
_Bool exists (zap_string_t path)
Definition at line 954 of file stdlib.c.
{
  struct stat st;
  return zap_stat_path(path, &st) == 0;
}
References zap_stat_path().
getLn()
zap_string_t getLn ()
Definition at line 748 of file stdlib.c.
                     {
  char *line = NULL;
  size_t len = 0;
  size_t read = getline(&line, &len, stdin);
  if (read == -1) {
    free(line);
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  // Remove newline if present
  if (read > 0 && line[read - 1] == '\n') {
    line[--read] = '\0';
  }
  char *owned = zap_string_alloc_owned(read);
  if (!owned) {
    free(line);
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  if (read > 0) {
    memcpy(owned, line, read);
  }
  owned[read] = '\0';
  free(line);
  zap_string_t result = {.ptr = owned, .len = read};
  return result;
}
References len(), and zap_string_alloc_owned().
isDir()
_Bool isDir (zap_string_t path)
Definition at line 968 of file stdlib.c.
{
  struct stat st;
  if (zap_stat_path(path, &st) != 0) {
    return 0;
  }
  return S_ISDIR(st.st_mode);
}
References zap_stat_path().
isFile()
_Bool isFile (zap_string_t path)
Definition at line 959 of file stdlib.c.
{
  struct stat st;
  if (zap_stat_path(path, &st) != 0) {
    return 0;
  }
  return S_ISREG(st.st_mode);
}
References zap_stat_path().
len()
long len (zap_string_t s)
Definition at line 786 of file stdlib.c.
{ return s.len; }
References zap_string_t::len.
Referenced by zap::detail::decodeUtf8At(), codegen::LLVMCodeGen::emitStringReleaseIfNeeded(), codegen::LLVMCodeGen::emitStringRetainIfNeeded(), codegen::LLVMCodeGen::emitZIRInstruction(), zap::detail::expandTabsForDisplay(), getLn(), codegen::LLVMCodeGen::lowerZIRAggregateConstant(), codegen::LLVMCodeGen::lowerZIRCast(), printStringPtrLen(), SourceSpan::SourceSpan(), Lexer::tokenize(), codegen::LLVMCodeGen::visit(), zap::detail::visualColumnsForBytes(), zap_copy_string_range(), zap_string_alloc_owned(), zap_string_from_cstr(), zap_string_from_ptrlen(), and zap_string_to_cstr().
netAccept()
long netAccept (long listenerFd)
Definition at line 1223 of file stdlib.c.
{
  if (listenerFd < 0) {
    zap_net_last_error = EINVAL;
    return -1;
  }
  int fd = accept((int)listenerFd, NULL, NULL);
  if (fd < 0) {
    zap_net_last_error = errno;
    return -1;
  }
  zap_net_last_error = 0;
  return fd;
}
References zap_net_last_error.
netClose()
long netClose (long fd)
Definition at line 1239 of file stdlib.c.
                       {
  if (fd < 0) {
    zap_net_last_error = EINVAL;
    return EINVAL;
  }
  if (close((int)fd) != 0) {
    zap_net_last_error = errno;
    return errno;
  }
  zap_net_last_error = 0;
  return 0;
}
References zap_net_last_error.
netConnect()
long netConnect (zap_string_t host, long port)
Definition at line 1121 of file stdlib.c.
{
  if (!host.ptr || port <= 0 || port > 65535) {
    zap_net_last_error = EINVAL;
    return -1;
  }
  char *host_buf = zap_copy_path(host);
  if (!host_buf) {
    zap_net_last_error = ENOMEM;
    return -1;
  }
  struct addrinfo *res = NULL;
  if (zap_net_bind_addrinfo(host_buf, port, SOCK_STREAM, 0, &res) != 0) {
    free(host_buf);
    return -1;
  }
  long out_fd = -1;
  int last_err = ECONNREFUSED;
  for (struct addrinfo *it = res; it; it = it->ai_next) {
    int fd = socket(it->ai_family, it->ai_socktype, it->ai_protocol);
    if (fd < 0) {
      last_err = errno;
      continue;
    }
    if (connect(fd, it->ai_addr, it->ai_addrlen) == 0) {
      out_fd = fd;
      last_err = 0;
      break;
    }
    last_err = errno;
    close(fd);
  }
  freeaddrinfo(res);
  free(host_buf);
  zap_net_last_error = last_err;
  return out_fd;
}
References zap_string_t::ptr, zap_copy_path(), zap_net_bind_addrinfo(), and zap_net_last_error.
netLastError()
long netLastError ()
Definition at line 1366 of file stdlib.c.
{ return zap_net_last_error; }
References zap_net_last_error.
netListen()
long netListen (zap_string_t host, long port)
Definition at line 1165 of file stdlib.c.
{
  if (port <= 0 || port > 65535) {
    zap_net_last_error = EINVAL;
    return -1;
  }
  char *host_buf = NULL;
  if (host.ptr) {
    host_buf = zap_copy_path(host);
    if (!host_buf) {
      zap_net_last_error = ENOMEM;
      return -1;
    }
  }
  struct addrinfo *res = NULL;
  if (zap_net_bind_addrinfo(host_buf ? host_buf : "", port, SOCK_STREAM,
                            AI_PASSIVE, &res) != 0) {
    free(host_buf);
    return -1;
  }
  long out_fd = -1;
  int last_err = EADDRNOTAVAIL;
  for (struct addrinfo *it = res; it; it = it->ai_next) {
    int fd = socket(it->ai_family, it->ai_socktype, it->ai_protocol);
    if (fd < 0) {
      last_err = errno;
      continue;
    }
    int one = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));
    if (bind(fd, it->ai_addr, it->ai_addrlen) != 0) {
      last_err = errno;
      close(fd);
      continue;
    }
    if (listen(fd, 128) != 0) {
      last_err = errno;
      close(fd);
      continue;
    }
    out_fd = fd;
    last_err = 0;
    break;
  }
  freeaddrinfo(res);
  free(host_buf);
  zap_net_last_error = last_err;
  return out_fd;
}
References zap_string_t::ptr, zap_copy_path(), zap_net_bind_addrinfo(), and zap_net_last_error.
netRecv()
zap_string_t netRecv (long fd, long maxLen)
Definition at line 1279 of file stdlib.c.
{
  if (fd < 0 || maxLen <= 0) {
    zap_net_last_error = EINVAL;
    return (zap_string_t){.ptr = "", .len = 0};
  }
  size_t cap = (size_t)maxLen;
  char *buf = zap_string_alloc_owned(cap);
  if (!buf) {
    zap_net_last_error = ENOMEM;
    return (zap_string_t){.ptr = "", .len = 0};
  }
  ssize_t n;
  do {
    n = recv((int)fd, buf, cap, 0);
  } while (n < 0 && errno == EINTR);
  if (n < 0) {
    zap_net_last_error = errno;
    zap_string_release_ptr(buf);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  buf[n] = '\0';
  zap_net_last_error = 0;
  return (zap_string_t){.ptr = buf, .len = (long)n};
}
References zap_net_last_error, zap_string_alloc_owned(), and zap_string_release_ptr().
netResolve()
zap_string_t netResolve (zap_string_t host)
Definition at line 1307 of file stdlib.c.
{
  if (!host.ptr || host.len == 0) {
    zap_net_last_error = EINVAL;
    return (zap_string_t){.ptr = "", .len = 0};
  }
  char *host_buf = zap_copy_path(host);
  if (!host_buf) {
    zap_net_last_error = ENOMEM;
    return (zap_string_t){.ptr = "", .len = 0};
  }
  struct addrinfo hints;
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  struct addrinfo *res = NULL;
  int rc = getaddrinfo(host_buf, NULL, &hints, &res);
  free(host_buf);
  if (rc != 0) {
    if (rc == EAI_SYSTEM) {
      zap_net_last_error = errno;
    } else {
      zap_net_last_error = EINVAL;
    }
    return (zap_string_t){.ptr = "", .len = 0};
  }
  char ipbuf[INET6_ADDRSTRLEN];
  memset(ipbuf, 0, sizeof(ipbuf));
  for (struct addrinfo *it = res; it; it = it->ai_next) {
    void *addr_ptr = NULL;
    if (it->ai_family == AF_INET) {
      struct sockaddr_in *sa = (struct sockaddr_in *)it->ai_addr;
      addr_ptr = &(sa->sin_addr);
    } else if (it->ai_family == AF_INET6) {
      struct sockaddr_in6 *sa6 = (struct sockaddr_in6 *)it->ai_addr;
      addr_ptr = &(sa6->sin6_addr);
    }
    if (addr_ptr &&
        inet_ntop(it->ai_family, addr_ptr, ipbuf, sizeof(ipbuf)) != NULL) {
      break;
    }
  }
  freeaddrinfo(res);
  if (ipbuf[0] == '\0') {
    zap_net_last_error = EADDRNOTAVAIL;
    return (zap_string_t){.ptr = "", .len = 0};
  }
  zap_net_last_error = 0;
  return zap_copy_string_range(ipbuf, strlen(ipbuf));
}
References zap_string_t::len, zap_string_t::ptr, zap_copy_path(), zap_copy_string_range(), and zap_net_last_error.
netSend()
long netSend (long fd, zap_string_t data)
Definition at line 1254 of file stdlib.c.
{
  if (fd < 0 || !data.ptr) {
    zap_net_last_error = EINVAL;
    return -1;
  }
  size_t total = 0;
  size_t target = data.len > 0 ? (size_t)data.len : 0;
  while (total < target) {
    ssize_t n = send((int)fd, data.ptr + total, target - total, 0);
    if (n < 0) {
      zap_net_last_error = errno;
      return -1;
    }
    if (n == 0) {
      break;
    }
    total += (size_t)n;
  }
  zap_net_last_error = 0;
  return (long)total;
}
References zap_string_t::len, zap_string_t::ptr, and zap_net_last_error.
print()
void print (zap_string_t s)
Definition at line 580 of file stdlib.c.
{
  if (!s.ptr || s.len <= 0) {
    return;
  }
  fwrite(s.ptr, 1, (size_t)s.len, stdout);
}
References zap_string_t::len, and zap_string_t::ptr.
printBool()
void printBool (_Bool v)
Definition at line 439 of file stdlib.c.
{ printf("%s\n", v ? "true" : "false"); }
printChar()
void printChar (char v)
Definition at line 441 of file stdlib.c.
                       {
  putchar(v);
  putchar('\n');
}
printFloat()
void printFloat (float v)
Definition at line 424 of file stdlib.c.
{ printf("%f\n", v); }
printFloat64()
void printFloat64 (double v)
Definition at line 426 of file stdlib.c.
{ printf("%f\n", v); }
printInt()
void printInt (long v)
Definition at line 422 of file stdlib.c.
{ printf("%ld\n", v); }
println()
void println (zap_string_t s)
Definition at line 696 of file stdlib.c.
{ printStringPtrLen(s.ptr, s.len); }
References zap_string_t::len, printStringPtrLen(), and zap_string_t::ptr.
println_cstr()
void println_cstr (const char * s)
Definition at line 740 of file stdlib.c.
{
  if (!s) {
    printf("\n");
    return;
  }
  puts(s);
}
printStringPtrLen()
void printStringPtrLen (const char * ptr, long len)
Definition at line 446 of file stdlib.c.
{
  if (!ptr || len <= 0) {
    printf("\n");
    return;
  }
  fwrite(ptr, 1, (size_t)len, stdout);
  printf("\n");
}
References len().
Referenced by println().
readFile()
zap_string_t readFile (zap_string_t path)
Definition at line 1033 of file stdlib.c.
{
  char *buffer = zap_copy_path(path);
  if (!buffer) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  FILE *file = fopen(buffer, "rb");
  free(buffer);
  if (!file) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  if (fseek(file, 0, SEEK_END) != 0) {
    fclose(file);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  long size = ftell(file);
  if (size < 0) {
    fclose(file);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  if (fseek(file, 0, SEEK_SET) != 0) {
    fclose(file);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  char *content = zap_string_alloc_owned((size_t)size);
  if (!content) {
    fclose(file);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  size_t read = fread(content, 1, (size_t)size, file);
  fclose(file);
  if (read != (size_t)size) {
    zap_string_release_ptr(content);
    return (zap_string_t){.ptr = "", .len = 0};
  }
  content[size] = '\0';
  return (zap_string_t){.ptr = content, .len = size};
}
References zap_copy_path(), zap_string_alloc_owned(), and zap_string_release_ptr().
slice()
zap_string_t slice (zap_string_t s, long start, long length)
Definition at line 795 of file stdlib.c.
{
  if (!s.ptr || s.len <= 0 || length <= 0 || start >= s.len) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  if (start < 0) {
    start = 0;
  }
  long available = s.len - start;
  if (available < 0) {
    available = 0;
  }
  if (length > available) {
    length = available;
  }
  char *out = zap_string_alloc_owned((size_t)length);
  if (!out) {
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  if (length > 0) {
    memcpy(out, s.ptr + start, (size_t)length);
  }
  out[length] = '\0';
  return (zap_string_t){.ptr = out, .len = length};
}
References zap_string_t::len, zap_string_t::ptr, and zap_string_alloc_owned().
string_concat_ptrlen()
char * string_concat_ptrlen (const char * a, long a_len, const char * b, long b_len)
Definition at line 458 of file stdlib.c.
{
  long total = a_len + b_len;
  char *out = zap_string_alloc_owned((size_t)total);
  if (!out)
    return NULL;
  if (a_len > 0)
    memcpy(out, a, (size_t)a_len);
  if (b_len > 0)
    memcpy(out + a_len, b, (size_t)b_len);
  out[total] = '\0';
  return out;
}
References zap_string_alloc_owned().
writeFile()
long writeFile (zap_string_t path, zap_string_t content)
Definition at line 1078 of file stdlib.c.
{
  char *buffer = zap_copy_path(path);
  if (!buffer) {
    return ENOMEM;
  }
  FILE *file = fopen(buffer, "wb");
  free(buffer);
  if (!file) {
    return errno;
  }
  size_t written = fwrite(content.ptr, 1, (size_t)content.len, file);
  if (fclose(file) != 0) {
    return errno;
  }
  if (written != (size_t)content.len) {
    return EIO;
  }
  return 0;
}
References zap_string_t::len, zap_string_t::ptr, and zap_copy_path().
zap_arc_add_possible_root()
void zap_arc_add_possible_root (void * object)
Definition at line 79 of file stdlib.c.
{
  if (!object) {
    return;
  }
  zap_arc_header_t *header = (zap_arc_header_t *)object;
  if (header->gc_mark & ZAP_ARC_GC_BUFFERED) {
    return;
  }
  if (zap_arc_root_count == zap_arc_root_capacity) {
    size_t next_capacity =
        zap_arc_root_capacity == 0 ? 16 : zap_arc_root_capacity * 2;
    void **next =
        (void **)realloc(zap_arc_roots, next_capacity * sizeof(void *));
    if (!next) {
      return;
    }
    zap_arc_roots = next;
    zap_arc_root_capacity = next_capacity;
  }
  header->gc_mark |= ZAP_ARC_GC_BUFFERED;
  zap_arc_roots[zap_arc_root_count++] = object;
}
References zap_arc_header_t::gc_mark, ZAP_ARC_GC_BUFFERED, zap_arc_root_capacity, zap_arc_root_count, and zap_arc_roots.
zap_arc_cycle_collect()
void zap_arc_cycle_collect (void)
Definition at line 272 of file stdlib.c.
{
  if (zap_arc_collecting || zap_arc_root_count == 0) {
    return;
  }
  zap_arc_collecting = 1;
  if (zap_arc_root_count > zap_arc_snap_cap) {
    void **next =
        (void **)realloc(zap_arc_snap, zap_arc_root_count * sizeof(void *));
    if (!next) {
      zap_arc_collecting = 0;
      return;
    }
    zap_arc_snap = next;
    zap_arc_snap_cap = zap_arc_root_count;
  }
  void **roots = zap_arc_snap;
  size_t root_count = 0;
  for (size_t i = 0; i < zap_arc_root_count; ++i) {
    void *object = zap_arc_roots[i];
    if (!object) {
      continue;
    }
    zap_arc_header_t *header = (zap_arc_header_t *)object;
    header->gc_mark &= (uint8_t)~ZAP_ARC_GC_BUFFERED;
    roots[root_count++] = object;
  }
  zap_arc_root_count = 0;
  if (root_count == 0) {
    zap_arc_collecting = 0;
    return;
  }
  if (zap_arc_map.cap == 0 && !zap_arc_ptrmap_init(&zap_arc_map, 64)) {
    zap_arc_collecting = 0;
    return;
  }
  zap_arc_ptrmap_clear(&zap_arc_map);
  size_t ws_count = 0;
  for (size_t i = 0; i < root_count; ++i) {
    if (!zap_arc_ws_push(&zap_arc_ws, &ws_count, &zap_arc_ws_cap, &zap_arc_map,
                         roots[i])) {
      goto cleanup;
    }
  }
  for (size_t cursor = 0; cursor < ws_count; ++cursor) {
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[cursor];
    if (!header->alive || !header->metadata) {
      continue;
    }
    for (uint32_t j = 0; j < header->metadata->strong_field_count; ++j) {
      uint32_t offset = header->metadata->strong_field_offsets[j];
      void *child = *(void **)((char *)zap_arc_ws[cursor] + offset);
      if (child && !zap_arc_ws_push(&zap_arc_ws, &ws_count, &zap_arc_ws_cap,
                                    &zap_arc_map, child)) {
        goto cleanup;
      }
    }
  }
  if (!zap_arc_ensure_scratch(ws_count)) {
    goto cleanup;
  }
  int *incoming = zap_arc_incoming;
  uint8_t *reachable = zap_arc_reachable;
  uint32_t *stack = zap_arc_stack;
  memset(incoming, 0, ws_count * sizeof(int));
  memset(reachable, 0, ws_count * sizeof(uint8_t));
  for (size_t i = 0; i < ws_count; ++i) {
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[i];
    if (!header->alive || !header->metadata) {
      continue;
    }
    for (uint32_t j = 0; j < header->metadata->strong_field_count; ++j) {
      uint32_t offset = header->metadata->strong_field_offsets[j];
      void *child = *(void **)((char *)zap_arc_ws[i] + offset);
      uint32_t ci;
      if (child && zap_arc_ptrmap_get(&zap_arc_map, child, &ci)) {
        incoming[ci] += 1;
      }
    }
  }
  size_t sp = 0;
  for (size_t i = 0; i < ws_count; ++i) {
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[i];
    if (header->alive && header->strong_count > incoming[i] && !reachable[i]) {
      reachable[i] = 1;
      stack[sp++] = (uint32_t)i;
    }
  }
  while (sp) {
    uint32_t idx = stack[--sp];
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[idx];
    if (!header->alive || !header->metadata) {
      continue;
    }
    for (uint32_t j = 0; j < header->metadata->strong_field_count; ++j) {
      uint32_t offset = header->metadata->strong_field_offsets[j];
      void *child = *(void **)((char *)zap_arc_ws[idx] + offset);
      uint32_t ci;
      if (child && zap_arc_ptrmap_get(&zap_arc_map, child, &ci) &&
          !reachable[ci]) {
        reachable[ci] = 1;
        stack[sp++] = ci;
      }
    }
  }
  for (size_t i = 0; i < ws_count; ++i) {
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[i];
    if (!header->alive || reachable[i]) {
      continue;
    }
    header->gc_mark = ZAP_ARC_GC_GARBAGE;
    header->strong_count = 1;
  }
  for (size_t i = 0; i < ws_count; ++i) {
    zap_arc_header_t *header = (zap_arc_header_t *)zap_arc_ws[i];
    if (header->alive && (header->gc_mark & ZAP_ARC_GC_GARBAGE) &&
        header->release_fn) {
      header->release_fn(zap_arc_ws[i]);
    }
  }
cleanup:
  zap_arc_collecting = 0;
}
References zap_arc_header_t::alive, zap_arc_header_t::gc_mark, zap_arc_header_t::metadata, zap_arc_header_t::release_fn, zap_arc_header_t::strong_count, zap_arc_metadata_t::strong_field_count, zap_arc_metadata_t::strong_field_offsets, zap_arc_collecting, zap_arc_ensure_scratch(), ZAP_ARC_GC_BUFFERED, ZAP_ARC_GC_GARBAGE, zap_arc_incoming, zap_arc_map, zap_arc_ptrmap_clear(), zap_arc_ptrmap_get(), zap_arc_ptrmap_init(), zap_arc_reachable, zap_arc_root_count, zap_arc_roots, zap_arc_snap, zap_arc_snap_cap, zap_arc_stack, zap_arc_ws, zap_arc_ws_cap, and zap_arc_ws_push().
zap_arc_ensure_scratch()
int zap_arc_ensure_scratch (size_t n) static
Definition at line 245 of file stdlib.c.
{
  if (n <= zap_arc_scratch_cap) {
    return 1;
  }
  size_t ncap = zap_arc_scratch_cap ? zap_arc_scratch_cap : 32;
  while (ncap < n) {
    ncap *= 2;
  }
  int *ni = (int *)realloc(zap_arc_incoming, ncap * sizeof(int));
  if (ni) {
    zap_arc_incoming = ni;
  }
  uint8_t *nr = (uint8_t *)realloc(zap_arc_reachable, ncap * sizeof(uint8_t));
  if (nr) {
    zap_arc_reachable = nr;
  }
  uint32_t *ns = (uint32_t *)realloc(zap_arc_stack, ncap * sizeof(uint32_t));
  if (ns) {
    zap_arc_stack = ns;
  }
  if (!ni || !nr || !ns) {
    return 0;
  }
  zap_arc_scratch_cap = ncap;
  return 1;
}
References zap_arc_incoming, zap_arc_reachable, zap_arc_scratch_cap, and zap_arc_stack.
Referenced by zap_arc_cycle_collect().
zap_arc_hash_ptr()
size_t zap_arc_hash_ptr (void * p) static
Definition at line 128 of file stdlib.c.
{
  uintptr_t x = (uintptr_t)p;
  x ^= x >> 33;
  x *= (uintptr_t)0xff51afd7ed558ccdULL;
  x ^= x >> 33;
  return (size_t)x;
}
Referenced by zap_arc_ptrmap_get(), zap_arc_ptrmap_grow(), and zap_arc_ptrmap_put().
zap_arc_ptrmap_clear()
void zap_arc_ptrmap_clear (zap_arc_ptrmap_t * m) static
Definition at line 144 of file stdlib.c.
{
  if (m->keys) {
    memset(m->keys, 0, m->cap * sizeof(void *));
  }
  m->len = 0;
}
References zap_arc_ptrmap_t::cap, zap_arc_ptrmap_t::keys, and zap_arc_ptrmap_t::len.
Referenced by zap_arc_cycle_collect().
zap_arc_ptrmap_get()
int zap_arc_ptrmap_get (const zap_arc_ptrmap_t * m, void * key, uint32_t * out_index) static
Definition at line 151 of file stdlib.c.
{
  size_t mask = m->cap - 1;
  size_t i = zap_arc_hash_ptr(key) & mask;
  while (m->keys[i]) {
    if (m->keys[i] == key) {
      *out_index = m->vals[i];
      return 1;
    }
    i = (i + 1) & mask;
  }
  return 0;
}
References zap_arc_ptrmap_t::cap, zap_arc_ptrmap_t::keys, zap_arc_ptrmap_t::vals, and zap_arc_hash_ptr().
Referenced by zap_arc_cycle_collect(), and zap_arc_ws_push().
zap_arc_ptrmap_grow()
int zap_arc_ptrmap_grow (zap_arc_ptrmap_t * m) static
Definition at line 165 of file stdlib.c.
{
  size_t ncap = m->cap * 2;
  void **nkeys = (void **)calloc(ncap, sizeof(void *));
  uint32_t *nvals = (uint32_t *)calloc(ncap, sizeof(uint32_t));
  if (!nkeys || !nvals) {
    free(nkeys);
    free(nvals);
    return 0;
  }
  size_t nmask = ncap - 1;
  for (size_t i = 0; i < m->cap; ++i) {
    if (!m->keys[i]) {
      continue;
    }
    size_t j = zap_arc_hash_ptr(m->keys[i]) & nmask;
    while (nkeys[j]) {
      j = (j + 1) & nmask;
    }
    nkeys[j] = m->keys[i];
    nvals[j] = m->vals[i];
  }
  free(m->keys);
  free(m->vals);
  m->keys = nkeys;
  m->vals = nvals;
  m->cap = ncap;
  return 1;
}
References zap_arc_ptrmap_t::cap, zap_arc_ptrmap_t::keys, zap_arc_ptrmap_t::vals, and zap_arc_hash_ptr().
Referenced by zap_arc_ptrmap_put().
zap_arc_ptrmap_init()
int zap_arc_ptrmap_init (zap_arc_ptrmap_t * m, size_t cap) static
Definition at line 136 of file stdlib.c.
{
  m->cap = cap;
  m->len = 0;
  m->keys = (void **)calloc(cap, sizeof(void *));
  m->vals = (uint32_t *)calloc(cap, sizeof(uint32_t));
  return m->keys != NULL && m->vals != NULL;
}
References zap_arc_ptrmap_t::cap, zap_arc_ptrmap_t::keys, zap_arc_ptrmap_t::len, and zap_arc_ptrmap_t::vals.
Referenced by zap_arc_cycle_collect().
zap_arc_ptrmap_put()
int zap_arc_ptrmap_put (zap_arc_ptrmap_t * m, void * key, uint32_t value) static
Definition at line 194 of file stdlib.c.
{
  if ((m->len + 1) * 2 >= m->cap && !zap_arc_ptrmap_grow(m)) {
    return 0;
  }
  size_t mask = m->cap - 1;
  size_t i = zap_arc_hash_ptr(key) & mask;
  while (m->keys[i]) {
    if (m->keys[i] == key) {
      m->vals[i] = value;
      return 1;
    }
    i = (i + 1) & mask;
  }
  m->keys[i] = key;
  m->vals[i] = value;
  m->len++;
  return 1;
}
References zap_arc_ptrmap_t::cap, zap_arc_ptrmap_t::keys, zap_arc_ptrmap_t::len, zap_arc_ptrmap_t::vals, zap_arc_hash_ptr(), and zap_arc_ptrmap_grow().
Referenced by zap_arc_ws_push().
zap_arc_remove_possible_root()
void zap_arc_remove_possible_root (void * object)
Definition at line 104 of file stdlib.c.
{
  if (!object) {
    return;
  }
  zap_arc_header_t *header = (zap_arc_header_t *)object;
  if (!(header->gc_mark & ZAP_ARC_GC_BUFFERED)) {
    return;
  }
  header->gc_mark &= (uint8_t)~ZAP_ARC_GC_BUFFERED;
  for (size_t i = 0; i < zap_arc_root_count; ++i) {
    if (zap_arc_roots[i] == object) {
      zap_arc_roots[i] = NULL;
      break;
    }
  }
}
References zap_arc_header_t::gc_mark, ZAP_ARC_GC_BUFFERED, zap_arc_root_count, and zap_arc_roots.
zap_arc_ws_push()
int zap_arc_ws_push (void *** ws, size_t * count, size_t * cap, zap_arc_ptrmap_t * map, void * object) static
Definition at line 213 of file stdlib.c.
{
  uint32_t existing;
  if (zap_arc_ptrmap_get(map, object, &existing)) {
    return 1;
  }
  if (*count == *cap) {
    size_t ncap = *cap == 0 ? 32 : *cap * 2;
    void **next = (void **)realloc(*ws, ncap * sizeof(void *));
    if (!next) {
      return 0;
    }
    *ws = next;
    *cap = ncap;
  }
  if (!zap_arc_ptrmap_put(map, object, (uint32_t)*count)) {
    return 0;
  }
  (*ws)[(*count)++] = object;
  return 1;
}
References zap_arc_ptrmap_get(), and zap_arc_ptrmap_put().
Referenced by zap_arc_cycle_collect().
zap_copy_path()
char * zap_copy_path (zap_string_t path) static
Definition at line 904 of file stdlib.c.
{
  if (!path.ptr) {
    return NULL;
  }
  char *buffer = (char *)malloc((size_t)path.len + 1);
  if (!buffer) {
    return NULL;
  }
  memcpy(buffer, path.ptr, (size_t)path.len);
  buffer[path.len] = '\0';
  return buffer;
}
References zap_string_t::len, and zap_string_t::ptr.
Referenced by netConnect(), netListen(), netResolve(), readFile(), writeFile(), zap_fs_mkdir(), zap_fs_remove(), and zap_fs_rename().
zap_copy_string_range()
zap_string_t zap_copy_string_range (const char * start, size_t len) static
Definition at line 1102 of file stdlib.c.
{
  char *out = zap_string_alloc_owned(len);
  if (!out) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  if (len > 0) {
    memcpy(out, start, len);
  }
  out[len] = '\0';
  return (zap_string_t){.ptr = out, .len = (long)len};
}
References len(), and zap_string_alloc_owned().
Referenced by netResolve().
zap_fs_mkdir()
long zap_fs_mkdir (zap_string_t path)
Definition at line 977 of file stdlib.c.
{
  char *buffer = zap_copy_path(path);
  if (!buffer) {
    return ENOMEM;
  }
  if (mkdir(buffer, 0777) == 0) {
    free(buffer);
    return 0;
  }
  int err = errno;
  free(buffer);
  return err;
}
References zap_copy_path().
zap_fs_remove()
long zap_fs_remove (zap_string_t path)
Definition at line 993 of file stdlib.c.
{
  char *buffer = zap_copy_path(path);
  if (!buffer) {
    return ENOMEM;
  }
  if (remove(buffer) == 0) {
    free(buffer);
    return 0;
  }
  int err = errno;
  free(buffer);
  return err;
}
References zap_copy_path().
zap_fs_rename()
long zap_fs_rename (zap_string_t from, zap_string_t to)
Definition at line 1009 of file stdlib.c.
{
  char *from_buffer = zap_copy_path(from);
  if (!from_buffer) {
    return ENOMEM;
  }
  char *to_buffer = zap_copy_path(to);
  if (!to_buffer) {
    free(from_buffer);
    return ENOMEM;
  }
  if (rename(from_buffer, to_buffer) == 0) {
    free(from_buffer);
    free(to_buffer);
    return 0;
  }
  int err = errno;
  free(from_buffer);
  free(to_buffer);
  return err;
}
References zap_copy_path().
zap_net_bind_addrinfo()
int zap_net_bind_addrinfo (const char * host, long port, int socktype, int flags, struct addrinfo ** out) static
Definition at line 919 of file stdlib.c.
{
  if (!out) {
    zap_net_last_error = EINVAL;
    return -1;
  }
  char port_buf[32];
  snprintf(port_buf, sizeof(port_buf), "%ld", port);
  struct addrinfo hints;
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = socktype;
  hints.ai_flags = flags;
  const char *node = host;
  if (host && (strcmp(host, "") == 0 || strcmp(host, "*") == 0)) {
    node = NULL;
  }
  int rc = getaddrinfo(node, port_buf, &hints, out);
  if (rc != 0) {
    if (rc == EAI_SYSTEM) {
      zap_net_last_error = errno;
    } else {
      zap_net_last_error = EINVAL;
    }
    return -1;
  }
  zap_net_last_error = 0;
  return 0;
}
References zap_net_last_error.
Referenced by netConnect(), and netListen().
zap_printf()
long zap_printf (zap_string_t format, ...)
Definition at line 698 of file stdlib.c.
{
  char *fmt = zap_string_to_cstr(format);
  if (!fmt)
    return -1;
  va_list args;
  va_start(args, format);
  long written = vprintf(fmt, args);
  va_end(args);
  free(fmt);
  return written;
}
References zap_string_to_cstr().
zap_printfln()
long zap_printfln (zap_string_t format, ...)
Definition at line 712 of file stdlib.c.
{
  char *fmt = zap_string_to_cstr(format);
  if (!fmt)
    return -1;
  va_list args;
  va_start(args, format);
  long written = vprintf(fmt, args);
  va_end(args);
  free(fmt);
  if (written < 0)
    return written;
  if (printf("\n") < 0)
    return -1;
  return written + 1;
}
References zap_string_to_cstr().
zap_stat_path()
int zap_stat_path (zap_string_t path, struct stat * st) static
Definition at line 886 of file stdlib.c.
{
  if (!path.ptr) {
    return -1;
  }
  char *buffer = (char *)malloc((size_t)path.len + 1);
  if (!buffer) {
    return -1;
  }
  memcpy(buffer, path.ptr, (size_t)path.len);
  buffer[path.len] = '\0';
  int result = stat(buffer, st);
  free(buffer);
  return result;
}
References zap_string_t::len, and zap_string_t::ptr.
Referenced by exists(), isDir(), and isFile().
zap_string_alloc_owned()
char * zap_string_alloc_owned (size_t len) static
Definition at line 545 of file stdlib.c.
{
  zap_string_header_t *header =
      (zap_string_header_t *)malloc(sizeof(zap_string_header_t) + len + 1);
  if (!header) {
    return NULL;
  }
  header->magic = ZAP_STRING_HEADER_MAGIC;
  header->refs = 1;
  header->len = (int64_t)len;
  char *ptr = (char *)(header + 1);
  ptr[len] = '\0';
  zap_string_register_owned_ptr(ptr);
  return ptr;
}
References len(), zap_string_header_t::len, zap_string_header_t::magic, zap_string_header_t::refs, ZAP_STRING_HEADER_MAGIC, and zap_string_register_owned_ptr().
Referenced by cwd(), getLn(), netRecv(), readFile(), slice(), string_concat_ptrlen(), zap_copy_string_range(), zap_string_from_cstr(), and zap_string_from_ptrlen().
zap_string_find_owner()
zap_string_owner_entry_t * zap_string_find_owner (const char * ptr) static
Definition at line 491 of file stdlib.c.
{
  zap_string_owner_entry_t *entry = zap_string_owners;
  while (entry) {
    if (entry->ptr == ptr) {
      return entry;
    }
    entry = entry->next;
  }
  return NULL;
}
References zap_string_owner_entry_t::next, zap_string_owner_entry_t::ptr, and zap_string_owners.
Referenced by zap_string_from_owned(), zap_string_header_from_ptr(), and zap_string_register_owned_ptr().
zap_string_from_cstr()
zap_string_t zap_string_from_cstr (const char * cstr)
Definition at line 608 of file stdlib.c.
{
  if (!cstr) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  size_t len = strlen(cstr);
  char *out = zap_string_alloc_owned(len);
  if (!out) {
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  if (len > 0) {
    memcpy(out, cstr, len);
  }
  out[len] = '\0';
  return (zap_string_t){.ptr = out, .len = (long)len};
}
References len(), and zap_string_alloc_owned().
Referenced by zap_string_from_format().
zap_string_from_format()
zap_string_t zap_string_from_format (const char * format, ...) static
Definition at line 646 of file stdlib.c.
{
  va_list args;
  va_start(args, format);
  va_list args_copy;
  va_copy(args_copy, args);
  int needed = vsnprintf(NULL, 0, format, args_copy);
  va_end(args_copy);
  if (needed < 0) {
    va_end(args);
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  char *buffer = (char *)malloc((size_t)needed + 1);
  if (!buffer) {
    va_end(args);
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  vsnprintf(buffer, (size_t)needed + 1, format, args);
  va_end(args);
  zap_string_t result = zap_string_from_cstr(buffer);
  free(buffer);
  return result;
}
References zap_string_from_cstr().
Referenced by zap_to_string_f64(), zap_to_string_i64(), and zap_to_string_u64().
zap_string_from_owned()
zap_string_t zap_string_from_owned (char * owned) static
Definition at line 598 of file stdlib.c.
{
  if (!owned) {
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  if (!zap_string_find_owner(owned)) {
    zap_string_register_owned_ptr(owned);
  }
  return (zap_string_t){.ptr = owned, .len = (long)strlen(owned)};
}
References zap_string_find_owner(), and zap_string_register_owned_ptr().
zap_string_from_ptrlen()
zap_string_t zap_string_from_ptrlen (const char * ptr, long len)
Definition at line 624 of file stdlib.c.
{
  if (!ptr || len <= 0) {
    return (zap_string_t){.ptr = "", .len = 0};
  }
  char *out = zap_string_alloc_owned((size_t)len);
  if (!out) {
    return (zap_string_t){.ptr = NULL, .len = 0};
  }
  memcpy(out, ptr, (size_t)len);
  out[len] = '\0';
  return (zap_string_t){.ptr = out, .len = len};
}
References len(), and zap_string_alloc_owned().
zap_string_header_from_ptr()
zap_string_header_t * zap_string_header_from_ptr (const char * ptr) static
Definition at line 538 of file stdlib.c.
{
  if (!ptr || !zap_string_find_owner(ptr)) {
    return NULL;
  }
  return (zap_string_header_t *)((char *)ptr - sizeof(zap_string_header_t));
}
References zap_string_find_owner().
Referenced by zap_string_release_ptr(), and zap_string_retain_ptr().
zap_string_register_owned_ptr()
void zap_string_register_owned_ptr (const char * ptr) static
Definition at line 502 of file stdlib.c.
{
  if (!ptr) {
    return;
  }
  zap_string_owner_entry_t *existing = zap_string_find_owner(ptr);
  if (existing) {
    return;
  }
  zap_string_owner_entry_t *entry =
      (zap_string_owner_entry_t *)malloc(sizeof(zap_string_owner_entry_t));
  if (!entry) {
    return;
  }
  entry->ptr = ptr;
  entry->next = zap_string_owners;
  zap_string_owners = entry;
}
References zap_string_owner_entry_t::next, zap_string_owner_entry_t::ptr, zap_string_find_owner(), and zap_string_owners.
Referenced by zap_string_alloc_owned(), and zap_string_from_owned().
zap_string_release()
void zap_string_release (zap_string_t s)
Definition at line 644 of file stdlib.c.
{ zap_string_release_ptr(s.ptr); }
References zap_string_t::ptr, and zap_string_release_ptr().
zap_string_release_ptr()
void zap_string_release_ptr (const char * ptr) static
Definition at line 568 of file stdlib.c.
{
  zap_string_header_t *header = zap_string_header_from_ptr(ptr);
  if (!header || header->magic != ZAP_STRING_HEADER_MAGIC) {
    return;
  }
  header->refs -= 1;
  if (header->refs <= 0) {
    zap_string_unregister_owned_ptr(ptr);
    free(header);
  }
}
References zap_string_header_t::magic, zap_string_header_t::refs, zap_string_header_from_ptr(), ZAP_STRING_HEADER_MAGIC, and zap_string_unregister_owned_ptr().
Referenced by netRecv(), readFile(), and zap_string_release().
zap_string_retain()
zap_string_t zap_string_retain (zap_string_t s)
Definition at line 639 of file stdlib.c.
{
  zap_string_retain_ptr(s.ptr);
  return s;
}
References zap_string_t::ptr, and zap_string_retain_ptr().
zap_string_retain_ptr()
void zap_string_retain_ptr (const char * ptr) static
Definition at line 560 of file stdlib.c.
{
  zap_string_header_t *header = zap_string_header_from_ptr(ptr);
  if (!header || header->magic != ZAP_STRING_HEADER_MAGIC) {
    return;
  }
  header->refs += 1;
}
References zap_string_header_t::magic, zap_string_header_t::refs, zap_string_header_from_ptr(), and ZAP_STRING_HEADER_MAGIC.
Referenced by zap_string_retain().
zap_string_to_cstr()
char * zap_string_to_cstr (zap_string_t s) static
Definition at line 587 of file stdlib.c.
{
  size_t len = s.len > 0 ? (size_t)s.len : 0;
  char *out = (char *)malloc(len + 1);
  if (!out)
    return NULL;
  if (len > 0 && s.ptr)
    memcpy(out, s.ptr, len);
  out[len] = '\0';
  return out;
}
References len(), zap_string_t::len, and zap_string_t::ptr.
Referenced by zap_printf(), and zap_printfln().
zap_string_unregister_owned_ptr()
void zap_string_unregister_owned_ptr (const char * ptr) static
Definition at line 520 of file stdlib.c.
{
  zap_string_owner_entry_t *prev = NULL;
  zap_string_owner_entry_t *entry = zap_string_owners;
  while (entry) {
    if (entry->ptr == ptr) {
      if (prev) {
        prev->next = entry->next;
      } else {
        zap_string_owners = entry->next;
      }
      free(entry);
      return;
    }
    prev = entry;
    entry = entry->next;
  }
}
References zap_string_owner_entry_t::next, zap_string_owner_entry_t::ptr, and zap_string_owners.
Referenced by zap_string_release_ptr().
zap_sum_variadic()
long zap_sum_variadic (long count, ...)
Definition at line 428 of file stdlib.c.
{
  va_list args;
  va_start(args, count);
  long sum = 0;
  for (long i = 0; i < count; ++i) {
    sum += va_arg(args, long);
  }
  va_end(args);
  return sum;
}
zap_to_char_from_int()
char zap_to_char_from_int (long value)
Definition at line 686 of file stdlib.c.
{ return (char)value; }
zap_to_int_from_char()
long zap_to_int_from_char (char value)
Definition at line 684 of file stdlib.c.
{ return (unsigned char)value; }
zap_to_string_f64()
zap_string_t zap_to_string_f64 (double value)
Definition at line 680 of file stdlib.c.
{
  return zap_string_from_format("%g", value);
}
References zap_string_from_format().
zap_to_string_i64()
zap_string_t zap_to_string_i64 (int64_t value)
Definition at line 672 of file stdlib.c.
{
  return zap_string_from_format("%lld", (long long)value);
}
References zap_string_from_format().
zap_to_string_u64()
zap_string_t zap_to_string_u64 (uint64_t value)
Definition at line 676 of file stdlib.c.
{
  return zap_string_from_format("%llu", (unsigned long long)value);
}
References zap_string_from_format().
zapMathCeil()
double zapMathCeil (double x)
Definition at line 1119 of file stdlib.c.
{ return ceil(x); }
zapMathFloor()
double zapMathFloor (double x)
Definition at line 1117 of file stdlib.c.
{ return floor(x); }
zapMathSqrt()
double zapMathSqrt (double x)
Definition at line 1115 of file stdlib.c.
{ return sqrt(x); }
Variable Documentation
zap_arc_collecting
int zap_arc_collecting = 0 static
Definition at line 76 of file stdlib.c.
Referenced by zap_arc_cycle_collect().
zap_arc_incoming
int* zap_arc_incoming = NULL static
Definition at line 239 of file stdlib.c.
Referenced by __attribute__(), zap_arc_cycle_collect(), and zap_arc_ensure_scratch().
zap_arc_map
zap_arc_ptrmap_t zap_arc_map = {NULL, NULL, 0, 0} static
Definition at line 243 of file stdlib.c.
{NULL, NULL, 0, 0};
Referenced by __attribute__(), and zap_arc_cycle_collect().
zap_arc_reachable
uint8_t* zap_arc_reachable = NULL static
Definition at line 240 of file stdlib.c.
Referenced by __attribute__(), zap_arc_cycle_collect(), and zap_arc_ensure_scratch().
zap_arc_root_capacity
size_t zap_arc_root_capacity = 0 static
Definition at line 75 of file stdlib.c.
Referenced by zap_arc_add_possible_root().
zap_arc_root_count
size_t zap_arc_root_count = 0 static
Definition at line 74 of file stdlib.c.
Referenced by zap_arc_add_possible_root(), zap_arc_cycle_collect(), and zap_arc_remove_possible_root().
zap_arc_roots
void** zap_arc_roots = NULL static
Definition at line 73 of file stdlib.c.
Referenced by __attribute__(), zap_arc_add_possible_root(), zap_arc_cycle_collect(), and zap_arc_remove_possible_root().
zap_arc_scratch_cap
size_t zap_arc_scratch_cap = 0 static
Definition at line 242 of file stdlib.c.
Referenced by zap_arc_ensure_scratch().
zap_arc_snap
void** zap_arc_snap = NULL static
Definition at line 235 of file stdlib.c.
Referenced by __attribute__(), and zap_arc_cycle_collect().
zap_arc_snap_cap
size_t zap_arc_snap_cap = 0 static
Definition at line 236 of file stdlib.c.
Referenced by zap_arc_cycle_collect().
zap_arc_stack
uint32_t* zap_arc_stack = NULL static
Definition at line 241 of file stdlib.c.
Referenced by __attribute__(), zap_arc_cycle_collect(), and zap_arc_ensure_scratch().
zap_arc_ws
void** zap_arc_ws = NULL static
Definition at line 237 of file stdlib.c.
Referenced by __attribute__(), and zap_arc_cycle_collect().
zap_arc_ws_cap
size_t zap_arc_ws_cap = 0 static
Definition at line 238 of file stdlib.c.
Referenced by zap_arc_cycle_collect().
zap_net_last_error
int zap_net_last_error = 0 static
Definition at line 77 of file stdlib.c.
Referenced by netAccept(), netClose(), netConnect(), netLastError(), netListen(), netRecv(), netResolve(), netSend(), and zap_net_bind_addrinfo().
zap_process_argc
long zap_process_argc = 0 static
Definition at line 688 of file stdlib.c.
Referenced by __zap_process_set_args(), argc(), and argv().
zap_process_argv
char** zap_process_argv = NULL static
Definition at line 689 of file stdlib.c.
Referenced by __zap_process_set_args(), and argv().
ZAP_STRING_HEADER_MAGIC
const uint64_t ZAP_STRING_HEADER_MAGIC = 0x5A41505354524E47ULL static
Definition at line 483 of file stdlib.c.
Referenced by zap_string_alloc_owned(), zap_string_release_ptr(), and zap_string_retain_ptr().
zap_string_owners
zap_string_owner_entry_t* zap_string_owners = NULL static
Definition at line 482 of file stdlib.c.
Referenced by zap_string_find_owner(), zap_string_register_owned_ptr(), and zap_string_unregister_owned_ptr().