ZAP: src/token/token.hpp File Reference
token.hpp File Reference
#include <string>
Classes
struct SourceSpan
Contains in-file related information like line, column, offset, and length.
class Token
Enumerations
enum TokenType {
IMPORT = 1 ,
FUN = 2 ,
RETURN = 3 ,
IF = 4 ,
ELSE = 5 ,
WHILE = 6 ,
FOR = 7 ,
MATCH = 8 ,
VAR = 9 ,
EXTERN = 10 ,
MODULE = 11 ,
PUB = 12 ,
PRIV = 13 ,
RECORD = 14 ,
IMPL = 15 ,
STATIC = 16 ,
ENUM = 17 ,
STRUCT = 18 ,
SEMICOLON = 19 ,
COLON = 20 ,
DOUBLECOLON = 21 ,
DOT = 22 ,
COMMA = 23 ,
LPAREN = 24 ,
RPAREN = 25 ,
LBRACE = 26 ,
RBRACE = 27 ,
ARRAY = 28 ,
SQUARE_LBRACE = 29 ,
SQUARE_RBRACE = 30 ,
QUESTION = 31 ,
ARROW = 32 ,
LAMBDA = 33 ,
LESSEQUAL = 34 ,
LESS = 35 ,
GREATER = 36 ,
GREATEREQUAL = 37 ,
EQUAL = 38 ,
ASSIGN = 39 ,
PLUS = 40 ,
MINUS = 41 ,
MULTIPLY = 42 ,
REFERENCE = 43 ,
DIVIDE = 44 ,
MODULO = 45 ,
POW = 46 ,
NOT = 47 ,
AND = 48 ,
OR = 49 ,
ID = 50 ,
INTEGER = 51 ,
FLOAT = 52 ,
STRING = 53 ,
CHAR = 54 ,
BOOL = 55 ,
BREAK = 56 ,
CONTINUE = 57 ,
ELLIPSIS = 58 ,
NOTEQUAL = 59 ,
CONCAT = 60 ,
BIT_OR = 61 ,
ALIAS = 62 ,
REF = 63 ,
GLOBAL ,
CONST
}
Determines the type the token will have.
Functions
std::string tokenTypeToString (TokenType type)
Turns the provided 'TokenType' to a string.
Enumeration Type Documentation
TokenType
enum TokenType
Determines the type the token will have.
Enumerator
IMPORT
"import" keyword.
FUN
"fun" (Function) keyword.
RETURN
"return" or "ret" keyword.
IF
"if" keyword.
ELSE
"else" keyword.
WHILE
"while" keyword.
FOR
"for" keyword.
MATCH
"match" keyword.
VAR
"var" keyword.
EXTERN
"ext" (Extern) keyword.
MODULE
"module" keyword.
PUB
"pub" (Public) keyword.
PRIV
"priv" (Private) keyword.
RECORD
"record" keyword.
IMPL
"impl" keyword.
STATIC
"static" keyword.
ENUM
"enum" keyword.
STRUCT
"struct" keyword.
SEMICOLON
';' symbol.
COLON
':' symbol.
DOUBLECOLON
'::' symbol.
DOT
'.' symbol.
COMMA
',' symbol.
LPAREN
'(' symbol.
RPAREN
')' symbol.
LBRACE
'{' symbol.
RBRACE
'}' symbol.
ARRAY
???
SQUARE_LBRACE
'[' symbol.
SQUARE_RBRACE
']' symbol.
QUESTION
';' symbol.
ARROW
'->' symbol.
LAMBDA
? '=>' symbol ?
LESSEQUAL
'<=' symbol.
LESS
'<' symbol.
GREATER
'>' symbol.
GREATEREQUAL
'>=' symbol.
EQUAL
'==' symbol.
ASSIGN
'=' symbol.
PLUS
'+' symbol.
MINUS
'-' symbol.
MULTIPLY
'*' symbol.
REFERENCE
'&' symbol.
DIVIDE
'/' symbol.
MODULO
'' symbol.
POW
'^' symbol.
NOT
'!' symbol.
AND
'&&' symbol.
OR
'||' symbol.
ID
Identifier.
INTEGER
Integer.
FLOAT
Floating point.
STRING
String.
CHAR
Char.
BOOL
True or false.
BREAK
"break" keyword.
CONTINUE
"continue" keyword.
ELLIPSIS
'...' symbol.
NOTEQUAL
'!=' symbol.
CONCAT
'~' symbol.
BIT_OR
'|' symbol.
ALIAS
"alias" keyword.
REF
"ref" keyword.
GLOBAL
CONST
Definition at line 5 of file token.hpp.
               {
  IMPORT = 1, ///< "import" keyword.
  FUN = 2, ///< "fun" (Function) keyword.
  RETURN = 3, ///< "return" or "ret" keyword.
  IF = 4, ///< "if" keyword.
  ELSE = 5, ///< "else" keyword.
  WHILE = 6, ///< "while" keyword.
  FOR = 7, ///< "for" keyword.
  MATCH = 8, ///< "match" keyword.
  VAR = 9, ///< "var" keyword.
  EXTERN = 10, ///< "ext" (Extern) keyword.
  MODULE = 11, ///< "module" keyword.
  PUB = 12, ///< "pub" (Public) keyword.
  PRIV = 13, ///< "priv" (Private) keyword.
  RECORD = 14, ///< "record" keyword.
  IMPL = 15, ///< "impl" keyword.
  STATIC = 16, ///< "static" keyword.
  ENUM = 17, ///< "enum" keyword.
  STRUCT = 18, ///< "struct" keyword.
  SEMICOLON = 19, ///< ';' symbol.
  COLON = 20, ///< ':' symbol.
  DOUBLECOLON = 21, ///< '::' symbol.
  DOT = 22, ///< '.' symbol.
  COMMA = 23, ///< ',' symbol.
  LPAREN = 24, ///< '(' symbol.
  RPAREN = 25, ///< ')' symbol.
  LBRACE = 26, ///< '{' symbol.
  RBRACE = 27, ///< '}' symbol.
  ARRAY = 28, ///< ???
  SQUARE_LBRACE = 29, ///< '[' symbol.
  SQUARE_RBRACE = 30, ///< ']' symbol.
  QUESTION = 31, ///< ';' symbol.
  ARROW = 32, ///< '->' symbol.
  LAMBDA = 33, ///< ? '=>' symbol ?
  LESSEQUAL = 34, ///< '<=' symbol.
  LESS = 35, ///< '<' symbol.
  GREATER = 36, ///< '>' symbol.
  GREATEREQUAL = 37, ///< '>=' symbol.
  EQUAL = 38, ///< '==' symbol.
  ASSIGN = 39, ///< '=' symbol.
  PLUS = 40, ///< '+' symbol.
  MINUS = 41, ///< '-' symbol.
  MULTIPLY = 42, ///< '*' symbol.
  REFERENCE = 43, ///< '&' symbol.
  DIVIDE = 44, ///< '/' symbol.
  MODULO = 45, ///< '%' symbol.
  POW = 46, ///< '^' symbol.
  NOT = 47, ///< '!' symbol.
  AND = 48, ///< '&&' symbol.
  OR = 49, ///< '||' symbol.
  ID = 50, ///< Identifier.
  INTEGER = 51, ///< Integer.
  FLOAT = 52, ///< Floating point.
  STRING = 53, ///< String.
  CHAR = 54, ///< Char.
  BOOL = 55, ///< True or false.
  BREAK = 56, ///< "break" keyword.
  CONTINUE = 57, ///< "continue" keyword.
  ELLIPSIS = 58, ///< '...' symbol.
  NOTEQUAL = 59, ///< '!=' symbol.
  CONCAT = 60, ///< '~' symbol.
  BIT_OR = 61, ///< '|' symbol.
  ALIAS = 62, ///< "alias" keyword.
  REF = 63, ///< "ref" keyword.
  GLOBAL,
  CONST,
};
Function Documentation
tokenTypeToString()
std::string tokenTypeToString (TokenType type) inline
Turns the provided 'TokenType' to a string.
Parameters
type The provided type.
Returns
String version of the token type.
Definition at line 121 of file token.hpp.
{
  switch (type) {
    case TokenType::IMPORT: return "import";
    case TokenType::FUN: return "fun";
    case TokenType::RETURN: return "return";
    case TokenType::IF: return "if";
    case TokenType::ELSE: return "else";
    case TokenType::WHILE: return "while";
    case TokenType::FOR: return "for";
    case TokenType::VAR: return "var";
    case TokenType::RECORD: return "record";
    case TokenType::ENUM: return "enum";
    case TokenType::SEMICOLON: return ";";
    case TokenType::COLON: return ":";
    case TokenType::DOUBLECOLON: return "::";
    case TokenType::DOT: return ".";
    case TokenType::COMMA: return ",";
    case TokenType::LPAREN: return "(";
    case TokenType::RPAREN: return ")";
    case TokenType::LBRACE: return "{";
    case TokenType::RBRACE: return "}";
    case TokenType::SQUARE_LBRACE: return "[";
    case TokenType::SQUARE_RBRACE: return "]";
    case TokenType::QUESTION: return "?";
    case TokenType::ASSIGN: return "=";
    case TokenType::EQUAL: return "==";
    case TokenType::NOTEQUAL: return "!=";
    case TokenType::PLUS: return "+";
    case TokenType::MINUS: return "-";
    case TokenType::MULTIPLY: return "*";
    case TokenType::DIVIDE: return "/";
    case TokenType::ID: return "identifier";
    case TokenType::INTEGER: return "integer literal";
    case TokenType::FLOAT: return "float literal";
    case TokenType::STRING: return "string literal";
    case TokenType::CHAR: return "char literal";
    case TokenType::BOOL: return "boolean literal";
    case TokenType::GLOBAL: return "global";
    case TokenType::CONST: return "const";
    case TokenType::ALIAS: return "alias";
    case TokenType::REF: return "ref";
    case TokenType::CONCAT: return "~";
    default: return "unknown token";
  }
}
References ALIAS, ASSIGN, BOOL, CHAR, COLON, COMMA, CONCAT, CONST, DIVIDE, DOT, DOUBLECOLON, ELSE, ENUM, EQUAL, FLOAT, FOR, FUN, GLOBAL, ID, IF, IMPORT, INTEGER, LBRACE, LPAREN, MINUS, MULTIPLY, NOTEQUAL, PLUS, QUESTION, RBRACE, RECORD, REF, RETURN, RPAREN, SEMICOLON, SQUARE_LBRACE, SQUARE_RBRACE, STRING, tokenTypeToString(), Token::type, VAR, and WHILE.
Referenced by zap::Parser::eat(), and tokenTypeToString().