ZAP: BinExpr Class Reference
BinExpr Class Reference
#include <bin_expr.hpp>
Public Member Functions
BinExpr () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
BinExpr (std::unique_ptr< ExpressionNode > left, std::string op, std::unique_ptr< ExpressionNode > right)
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::unique_ptr< ExpressionNode > left_
std::string op_
std::unique_ptr< ExpressionNode > right_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 7 of file bin_expr.hpp.
Constructor & Destructor Documentation
BinExpr() [1/2]
BinExpr::BinExpr () const default noexcept
Referenced by BinExpr().
BinExpr() [2/2]
BinExpr::BinExpr (std::unique_ptr< ExpressionNode > left, std::string op, std::unique_ptr< ExpressionNode > right) inline
Definition at line 13 of file bin_expr.hpp.
      : left_(std::move(left)), op_(op), right_(std::move(right)) {}
References BinExpr(), ExpressionNode::ExpressionNode(), left_, op_, and right_.
Member Function Documentation
accept()
void BinExpr::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 17 of file bin_expr.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
left_
std::unique_ptr<ExpressionNode> BinExpr::left_
Definition at line 9 of file bin_expr.hpp.
Referenced by BinExpr(), and sema::Binder::visit().
op_
std::string BinExpr::op_
Definition at line 10 of file bin_expr.hpp.
Referenced by BinExpr(), and sema::Binder::visit().
right_
std::unique_ptr<ExpressionNode> BinExpr::right_
Definition at line 11 of file bin_expr.hpp.
Referenced by BinExpr(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/bin_expr.hpp