ZAP: zap::Parser Class Reference
zap::Parser Class Reference
#include <parser.hpp>
Classes
class ParseError
Public Member Functions
Parser (const std::vector< Token > &toks, DiagnosticEngine &diag)
~Parser ()
std::unique_ptr< RootNode > parse ()
Private Types
enum class SyncContext {
TopLevel ,
Block
}
Private Member Functions
const Token & peek (size_t offset=0) const
Token eat (TokenType expectedType)
bool isAtEnd () const
void synchronize (SyncContext context=SyncContext::Block)
SourceSpan pointAfter (const SourceSpan &span) const
std::vector< AttributeNode > parseAttributes ()
AttributeNode parseSingleAttribute ()
std::unique_ptr< FunDecl > parseFunDecl (bool isUnsafe=false)
std::unique_ptr< ExtDecl > parseExtDecl ()
std::unique_ptr< ImportNode > parseImportDecl ()
std::unique_ptr< BodyNode > parseBody ()
std::unique_ptr< UnsafeBlockNode > parseUnsafeBlock ()
std::unique_ptr< VarDecl > parseVarDecl ()
std::unique_ptr< ConstDecl > parseConstDecl ()
std::unique_ptr< AssignNode > parseAssign ()
std::unique_ptr< TypeNode > parseType ()
std::vector< std::unique_ptr< TypeNode > > parseGenericTypeArguments ()
std::vector< std::unique_ptr< TypeNode > > parseGenericParameterList ()
std::vector< GenericConstraint > parseWhereClauses ()
std::unique_ptr< ArrayLiteralNode > parseArrayLiteral ()
std::unique_ptr< IfNode > parseIf ()
std::unique_ptr< IfTypeNode > parseIfType ()
std::unique_ptr< WhileNode > parseWhile ()
std::unique_ptr< ForNode > parseFor ()
std::unique_ptr< ForInNode > parseForIn ()
std::unique_ptr< VarDecl > parseForInitVarDecl ()
std::unique_ptr< AssignNode > parseForIncrementAssign ()
std::unique_ptr< ReturnNode > parseReturnStmt ()
std::unique_ptr< ExpressionNode > parseExpression ()
std::unique_ptr< ExpressionNode > parseFailableExpression ()
std::unique_ptr< ExpressionNode > parseCastExpression ()
std::unique_ptr< ExpressionNode > parseTernaryExpression ()
std::unique_ptr< ExpressionNode > parseBinaryExpression (int minPrecedence)
std::unique_ptr< ExpressionNode > parseUnaryExpression ()
std::unique_ptr< ExpressionNode > parsePostfixExpression ()
std::unique_ptr< ExpressionNode > parsePrimaryExpression ()
int getPrecedence (TokenType type)
std::unique_ptr< ParameterNode > parseParameter ()
std::unique_ptr< EnumDecl > parseEnumDecl ()
std::unique_ptr< TypeAliasDecl > parseTypeAliasDecl ()
std::unique_ptr< RecordDecl > parseRecordDecl ()
std::unique_ptr< ClassDecl > parseClassDecl ()
std::unique_ptr< StructDeclarationNode > parseStructDecl (bool isUnsafe=false)
std::unique_ptr< StructLiteralNode > parseStructLiteral (const std::string &type_name)
std::unique_ptr< StructLiteralNode > parseStructLiteral (std::unique_ptr< TypeNode > type)
std::unique_ptr< BreakNode > parseBreak ()
std::unique_ptr< ContinueNode > parseContinue ()
std::unique_ptr< FailNode > parseFail ()
std::vector< std::string > parseQualifiedIdentifier ()
bool isTypeStartToken (TokenType type) const
bool isTryPostfixContext (TokenType type) const
bool isGenericCallStart () const
bool isGenericStructLiteralStart () const
std::unique_ptr< TypeNode > typeNodeFromQualifiedExpression (const ExpressionNode *expr)
Private Attributes
DiagnosticEngine & _diag
std::vector< Token > _tokens
size_t _pos
AstBuilder _builder
bool _allowStructLiteral = true
Detailed Description
Definition at line 41 of file parser.hpp.
Member Enumeration Documentation
SyncContext
enum class zap::Parser::SyncContext strong private
Enumerator
TopLevel
Block
Definition at line 65 of file parser.hpp.
{
      TopLevel,
      Block
    };
Constructor & Destructor Documentation
Parser()
zap::Parser::Parser (const std::vector< Token > & toks, DiagnosticEngine & diag)
Definition at line 25 of file parser.cpp.
    : _diag(diag), _tokens(tokens), _pos(0) {}
References _diag, _pos, and _tokens.
~Parser()
zap::Parser::~Parser ()
Definition at line 28 of file parser.cpp.
{}
Member Function Documentation
eat()
Token zap::Parser::eat (TokenType expectedType) private
Definition at line 1547 of file parser.cpp.
{
  if (isAtEnd()) {
    _diag.report(peek().span, DiagnosticLevel::Error,
                 "Expected " + tokenTypeToString(expectedType) +
                     " but reached end of file.");
    throw ParseError();
  }
  Token current = _tokens[_pos];
  if (current.type == expectedType) {
    _pos++;
    return current;
  } else {
    _diag.report(current.span, DiagnosticLevel::Error,
                 "Expected " + tokenTypeToString(expectedType) + ", but got '" +
                     current.value + "'");
    throw ParseError();
  }
}
References _diag, _pos, _tokens, zap::Error, isAtEnd(), peek(), Token::span, tokenTypeToString(), Token::type, and Token::value.
Referenced by parse(), parseArrayLiteral(), parseAssign(), parseAttributes(), parseBinaryExpression(), parseBody(), parseBreak(), parseCastExpression(), parseClassDecl(), parseConstDecl(), parseContinue(), parseEnumDecl(), parseExtDecl(), parseFail(), parseFailableExpression(), parseFor(), parseForIn(), parseForIncrementAssign(), parseForInitVarDecl(), parseFunDecl(), parseGenericParameterList(), parseGenericTypeArguments(), parseIf(), parseIfType(), parseImportDecl(), parseParameter(), parsePostfixExpression(), parsePrimaryExpression(), parseQualifiedIdentifier(), parseRecordDecl(), parseReturnStmt(), parseSingleAttribute(), parseStructDecl(), parseStructLiteral(), parseTernaryExpression(), parseType(), parseTypeAliasDecl(), parseUnaryExpression(), parseUnsafeBlock(), parseVarDecl(), parseWhereClauses(), and parseWhile().
getPrecedence()
int zap::Parser::getPrecedence (TokenType type) private
Definition at line 1505 of file parser.cpp.
{
  switch (type) {
  case TokenType::OR:
    return 2;
  case TokenType::BIT_OR:
    return 3;
  case TokenType::POW:
    return 4;
  case TokenType::AND:
    return 5;
  case TokenType::REFERENCE:
    return 6;
  case TokenType::EQUAL:
  case TokenType::NOTEQUAL:
  case TokenType::LESS:
  case TokenType::LESSEQUAL:
  case TokenType::GREATER:
  case TokenType::GREATEREQUAL:
    return 7;
  case TokenType::LSHIFT:
  case TokenType::RSHIFT:
    return 8;
  case TokenType::PLUS:
  case TokenType::MINUS:
    return 9;
  case TokenType::MULTIPLY:
  case TokenType::DIVIDE:
  case TokenType::MODULO:
    return 10;
  default:
    return -1;
  }
}
References AND, BIT_OR, DIVIDE, EQUAL, GREATER, GREATEREQUAL, LESS, LESSEQUAL, LSHIFT, MINUS, MODULO, MULTIPLY, NOTEQUAL, OR, PLUS, POW, REFERENCE, and RSHIFT.
Referenced by parseBinaryExpression().
isAtEnd()
bool zap::Parser::isAtEnd () const private
Definition at line 1653 of file parser.cpp.
{ return _pos >= _tokens.size(); }
References _pos, and _tokens.
Referenced by eat(), isGenericCallStart(), isGenericStructLiteralStart(), parse(), parseBinaryExpression(), parseBody(), parsePostfixExpression(), and synchronize().
isGenericCallStart()
bool zap::Parser::isGenericCallStart () const private
Definition at line 591 of file parser.cpp.
{
  if (peek().type != TokenType::LESS || !isTypeStartToken(peek(1).type)) {
    return false;
  }
  size_t i = 1;
  int depth = 0;
  bool sawTypeToken = false;
  while (!isAtEnd()) {
    TokenType t = peek(i).type;
    if (t == TokenType::LESS && isTypeStartToken(peek(i + 1).type)) {
      ++depth;
      sawTypeToken = true;
      ++i;
      continue;
    }
    if (t == TokenType::GREATER) {
      if (depth == 0) {
        if (!sawTypeToken) {
          return false;
        }
        return peek(i + 1).type == TokenType::LPAREN;
      }
      --depth;
      ++i;
      continue;
    }
    if (t == TokenType::COMMA || t == TokenType::DOT || t == TokenType::ID ||
        t == TokenType::MULTIPLY || t == TokenType::ELLIPSIS ||
        t == TokenType::SQUARE_LBRACE || t == TokenType::SQUARE_RBRACE ||
        t == TokenType::INTEGER || t == TokenType::WEAK) {
      sawTypeToken = true;
      ++i;
      continue;
    }
    return false;
  }
  return false;
}
References COMMA, DOT, ELLIPSIS, GREATER, ID, INTEGER, isAtEnd(), isTypeStartToken(), LESS, LPAREN, MULTIPLY, peek(), SQUARE_LBRACE, SQUARE_RBRACE, Token::type, and WEAK.
Referenced by parsePostfixExpression().
isGenericStructLiteralStart()
bool zap::Parser::isGenericStructLiteralStart () const private
Definition at line 637 of file parser.cpp.
{
  if (peek().type != TokenType::LESS || !isTypeStartToken(peek(1).type)) {
    return false;
  }
  size_t i = 1;
  int depth = 0;
  bool sawTypeToken = false;
  while (!isAtEnd()) {
    TokenType t = peek(i).type;
    if (t == TokenType::LESS && isTypeStartToken(peek(i + 1).type)) {
      ++depth;
      sawTypeToken = true;
      ++i;
      continue;
    }
    if (t == TokenType::GREATER) {
      if (depth == 0) {
        if (!sawTypeToken) {
          return false;
        }
        return peek(i + 1).type == TokenType::LBRACE;
      }
      --depth;
      ++i;
      continue;
    }
    if (t == TokenType::COMMA || t == TokenType::DOT || t == TokenType::ID ||
        t == TokenType::MULTIPLY || t == TokenType::ELLIPSIS ||
        t == TokenType::SQUARE_LBRACE || t == TokenType::SQUARE_RBRACE ||
        t == TokenType::INTEGER || t == TokenType::WEAK) {
      sawTypeToken = true;
      ++i;
      continue;
    }
    return false;
  }
  return false;
}
References COMMA, DOT, ELLIPSIS, GREATER, ID, INTEGER, isAtEnd(), isTypeStartToken(), LBRACE, LESS, MULTIPLY, peek(), SQUARE_LBRACE, SQUARE_RBRACE, Token::type, and WEAK.
Referenced by parsePostfixExpression(), and parsePrimaryExpression().
isTryPostfixContext()
bool zap::Parser::isTryPostfixContext (TokenType type) const private
Definition at line 560 of file parser.cpp.
{
  switch (type) {
  case TokenType::SEMICOLON:
  case TokenType::COMMA:
  case TokenType::RPAREN:
  case TokenType::RBRACE:
  case TokenType::SQUARE_RBRACE:
  case TokenType::PLUS:
  case TokenType::MINUS:
  case TokenType::MULTIPLY:
  case TokenType::DIVIDE:
  case TokenType::MODULO:
  case TokenType::POW:
  case TokenType::BIT_OR:
  case TokenType::AND:
  case TokenType::OR:
  case TokenType::EQUAL:
  case TokenType::NOTEQUAL:
  case TokenType::LESS:
  case TokenType::LESSEQUAL:
  case TokenType::GREATER:
  case TokenType::GREATEREQUAL:
  case TokenType::LSHIFT:
  case TokenType::RSHIFT:
  case TokenType::AS:
    return true;
  default:
    return false;
  }
}
References AND, AS, BIT_OR, COMMA, DIVIDE, EQUAL, GREATER, GREATEREQUAL, LESS, LESSEQUAL, LSHIFT, MINUS, MODULO, MULTIPLY, NOTEQUAL, OR, PLUS, POW, RBRACE, RPAREN, RSHIFT, SEMICOLON, and SQUARE_RBRACE.
Referenced by parsePostfixExpression().
isTypeStartToken()
bool zap::Parser::isTypeStartToken (TokenType type) const private
Definition at line 554 of file parser.cpp.
{
  return type == TokenType::ID || type == TokenType::MULTIPLY ||
         type == TokenType::ELLIPSIS || type == TokenType::SQUARE_LBRACE ||
         type == TokenType::WEAK || type == TokenType::FUN;
}
References ELLIPSIS, FUN, ID, MULTIPLY, SQUARE_LBRACE, and WEAK.
Referenced by isGenericCallStart(), isGenericStructLiteralStart(), parseClassDecl(), parseFunDecl(), parseRecordDecl(), parseStructDecl(), and parseType().
parse()
std::unique_ptr< RootNode > zap::Parser::parse ()
Definition at line 93 of file parser.cpp.
{
  auto root = _builder.makeRoot();
  while (!isAtEnd()) {
    try {
      auto attributes = parseAttributes();
      Visibility visibility = Visibility::Private;
      if (peek().type == TokenType::PUB || peek().type == TokenType::PRIV) {
        visibility = (eat(peek().type).type == TokenType::PUB)
                         ? Visibility::Public
                         : Visibility::Private;
      }
      auto applyMetadata = [&visibility](Node *node,
                                         std::vector<AttributeNode> attrs = {}) {
        if (auto topLevel = dynamic_cast<TopLevel *>(node)) {
          topLevel->visibility_ = visibility;
          topLevel->attributes_ = std::move(attrs);
        }
      };
      if (peek().type == TokenType::IMPORT) {
        auto importDecl = parseImportDecl();
        applyMetadata(importDecl.get(), std::move(attributes));
        root->addChild(std::move(importDecl));
      } else if (peek().type == TokenType::UNSAFE &&
                 peek(1).type == TokenType::FUN) {
        eat(TokenType::UNSAFE);
        auto decl = parseFunDecl(true);
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::FUN) {
        auto decl = parseFunDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::EXTERN) {
        if (peek(1).type == TokenType::VAR) {
          Token externToken = eat(TokenType::EXTERN);
          eat(TokenType::VAR);
          Token nameToken = eat(TokenType::ID);
          eat(TokenType::COLON);
          auto typeNode = parseType();
          Token semiToken = eat(TokenType::SEMICOLON);
          auto varDecl = _builder.makeVarDecl(nameToken.value, std::move(typeNode), nullptr);
          varDecl->isGlobal_ = true;
          varDecl->isExternal_ = true;
          _builder.setSpan(varDecl.get(), SourceSpan::merge(externToken.span, semiToken.span));
          applyMetadata(varDecl.get(), std::move(attributes));
          root->addChild(std::move(varDecl));
        } else {
          auto decl = parseExtDecl();
          applyMetadata(decl.get(), std::move(attributes));
          root->addChild(std::move(decl));
        }
      } else if (peek().type == TokenType::ENUM) {
        auto decl = parseEnumDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::ALIAS) {
        auto decl = parseTypeAliasDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::UNSAFE &&
                 peek(1).type == TokenType::STRUCT) {
        eat(TokenType::UNSAFE);
        auto decl = parseStructDecl(true);
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::STRUCT) {
        auto decl = parseStructDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::RECORD) {
        auto decl = parseRecordDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::CLASS) {
        auto decl = parseClassDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::CONST) {
        auto decl = parseConstDecl();
        applyMetadata(decl.get(), std::move(attributes));
        root->addChild(std::move(decl));
      } else if (peek().type == TokenType::GLOBAL) {
        Token globalToken = eat(TokenType::GLOBAL);
        if (peek().type == TokenType::VAR) {
          auto varDecl = parseVarDecl();
          varDecl->isGlobal_ = true;
          applyMetadata(varDecl.get(), std::move(attributes));
          _builder.setSpan(varDecl.get(),
                           SourceSpan::merge(globalToken.span, varDecl->span));
          root->addChild(std::move(varDecl));
        } else {
          _diag.report(peek().span, DiagnosticLevel::Error,
                       "Expected 'var' after 'global'");
          _pos++;
          synchronize(SyncContext::TopLevel);
        }
      } else {
        _diag.report(peek().span, DiagnosticLevel::Error,
                     "Unexpected token " + peek().value);
        _pos++;
        synchronize(SyncContext::TopLevel);
      }
    } catch (const ParseError &e) {
      synchronize(SyncContext::TopLevel);
    }
  }
  return root;
}
References _builder, _diag, _pos, ALIAS, CLASS, COLON, CONST, eat(), ENUM, zap::Error, EXTERN, FUN, GLOBAL, ID, IMPORT, isAtEnd(), SourceSpan::merge(), parseAttributes(), parseClassDecl(), parseConstDecl(), parseEnumDecl(), parseExtDecl(), parseFunDecl(), parseImportDecl(), parseRecordDecl(), parseStructDecl(), parseType(), parseTypeAliasDecl(), parseVarDecl(), peek(), PRIV, Private, PUB, Public, RECORD, SEMICOLON, Token::span, STRUCT, synchronize(), TopLevel, Token::type, UNSAFE, Token::value, and VAR.
Referenced by zap::driver::compileSourceFile(), anonymous_namespace{lsp-main.cpp}::Workspace::loadModuleGraph(), and zap::anonymous_namespace{driver.cpp}::loadModuleGraph().
parseArrayLiteral()
std::unique_ptr< ArrayLiteralNode > zap::Parser::parseArrayLiteral () private
Definition at line 823 of file parser.cpp.
{
  Token lbrace = eat(TokenType::LBRACE);
  std::vector<std::unique_ptr<ExpressionNode>> elements;
  if (peek().type != TokenType::RBRACE) {
    do {
      elements.push_back(parseExpression());
    } while (peek().type == TokenType::COMMA &&
             eat(TokenType::COMMA).type == TokenType::COMMA);
  }
  Token rbrace = eat(TokenType::RBRACE);
  auto node = _builder.makeArrayLiteral(std::move(elements));
  _builder.setSpan(node.get(), SourceSpan::merge(lbrace.span, rbrace.span));
  return node;
}
References _builder, COMMA, eat(), LBRACE, SourceSpan::merge(), parseExpression(), peek(), RBRACE, and Token::span.
Referenced by parsePrimaryExpression().
parseAssign()
std::unique_ptr< AssignNode > zap::Parser::parseAssign () private
Definition at line 494 of file parser.cpp.
{
  auto target = parseExpression();
  eat(TokenType::ASSIGN);
  auto expr = parseExpression();
  Token semicolonToken = eat(TokenType::SEMICOLON);
  SourceSpan startSpan = target->span;
  auto node = _builder.makeAssign(std::move(target), std::move(expr));
  _builder.setSpan(node.get(),
                   SourceSpan::merge(startSpan, semicolonToken.span));
  return node;
}
References _builder, ASSIGN, eat(), SourceSpan::merge(), parseExpression(), SEMICOLON, and Token::span.
parseAttributes()
std::vector< AttributeNode > zap::Parser::parseAttributes () private
Definition at line 30 of file parser.cpp.
{
  std::vector<AttributeNode> attributes;
  while (peek().type == TokenType::AT) {
    Token atToken = eat(TokenType::AT);
    if (peek().type == TokenType::LBRACE) {
      eat(TokenType::LBRACE);
      if (peek().type != TokenType::RBRACE) {
        do {
          attributes.push_back(parseSingleAttribute());
        } while (peek().type == TokenType::COMMA &&
                 eat(TokenType::COMMA).type == TokenType::COMMA);
      }
      eat(TokenType::RBRACE);
    } else {
      auto attr = parseSingleAttribute();
      attr.span = SourceSpan::merge(atToken.span, attr.span);
      attributes.push_back(std::move(attr));
    }
  }
  return attributes;
}
References AT, COMMA, eat(), LBRACE, SourceSpan::merge(), parseSingleAttribute(), peek(), RBRACE, and Token::span.
Referenced by parse().
parseBinaryExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseBinaryExpression (int minPrecedence) private
Definition at line 1210 of file parser.cpp.
{
  auto left = parseUnaryExpression();
  while (true) {
    if (isAtEnd())
      break;
    Token opToken = peek();
    if (opToken.type == TokenType::OR && opToken.value == "or") {
      break;
    }
    int precedence = getPrecedence(opToken.type);
    if (precedence < minPrecedence) {
      break;
    }
    eat(opToken.type);
    int nextMinPrecedence = precedence + 1;
    auto right = parseBinaryExpression(nextMinPrecedence);
    SourceSpan leftSpan = left->span;
    SourceSpan rightSpan = right->span;
    left =
        _builder.makeBinExpr(std::move(left), opToken.value, std::move(right));
    _builder.setSpan(static_cast<BinExpr *>(left.get()),
                     SourceSpan::merge(leftSpan, rightSpan));
  }
  return left;
}
References _builder, eat(), getPrecedence(), isAtEnd(), SourceSpan::merge(), OR, parseBinaryExpression(), parseUnaryExpression(), peek(), Token::type, and Token::value.
Referenced by parseBinaryExpression(), and parseTernaryExpression().
parseBody()
std::unique_ptr< BodyNode > zap::Parser::parseBody () private
Definition at line 341 of file parser.cpp.
{
  auto body = _builder.makeBody();
  while (!isAtEnd() && peek().type != TokenType::RBRACE) {
    try {
      if (peek().type == TokenType::VAR) {
        body->addStatement(parseVarDecl());
      } else if (peek().type == TokenType::CONST) {
        body->addStatement(parseConstDecl());
      } else if (peek().type == TokenType::RETURN) {
        body->addStatement(parseReturnStmt());
      } else if (peek().type == TokenType::FAIL) {
        body->addStatement(parseFail());
      } else if (peek().type == TokenType::IF) {
        auto ifNode = parseIf();
        if (peek().type == TokenType::SEMICOLON) {
          eat(TokenType::SEMICOLON);
        }
        body->addStatement(std::move(ifNode));
      } else if (peek().type == TokenType::IFTYPE) {
        auto ifTypeNode = parseIfType();
        if (peek().type == TokenType::SEMICOLON) {
          eat(TokenType::SEMICOLON);
        }
        body->addStatement(std::move(ifTypeNode));
      } else if (peek().type == TokenType::WHILE) {
        auto whileNode = parseWhile();
        if (peek().type == TokenType::SEMICOLON) {
          eat(TokenType::SEMICOLON);
        }
        body->addStatement(std::move(whileNode));
      } else if (peek().type == TokenType::FOR) {
        bool isForIn = false;
        if (peek(1).type == TokenType::ID && peek(2).type == TokenType::ID &&
            peek(2).value == "in") {
          isForIn = true;
        } else if (peek(1).type == TokenType::LPAREN &&
                   peek(2).type == TokenType::ID &&
                   peek(3).type == TokenType::ID && peek(3).value == "in") {
          isForIn = true;
        }
        if (isForIn) {
          auto forInNode = parseForIn();
          if (peek().type == TokenType::SEMICOLON) {
            eat(TokenType::SEMICOLON);
          }
          body->addStatement(std::move(forInNode));
        } else {
          auto forNode = parseFor();
          if (peek().type == TokenType::SEMICOLON) {
            eat(TokenType::SEMICOLON);
          }
          body->addStatement(std::move(forNode));
        }
      } else if (peek().type == TokenType::BREAK) {
        body->addStatement(parseBreak());
      } else if (peek().type == TokenType::CONTINUE) {
        body->addStatement(parseContinue());
      } else if (peek().type == TokenType::UNSAFE) {
        body->addStatement(parseUnsafeBlock());
      } else {
        auto expr = parseExpression();
        if (peek().type == TokenType::ASSIGN) {
          eat(TokenType::ASSIGN);
          auto value = parseExpression();
          Token semi = eat(TokenType::SEMICOLON);
          auto assign = _builder.makeAssign(std::move(expr), std::move(value));
          _builder.setSpan(assign.get(),
                           SourceSpan::merge(assign->target_->span, semi.span));
          body->addStatement(std::move(assign));
        } else if (peek().type == TokenType::SEMICOLON) {
          eat(TokenType::SEMICOLON);
          body->addStatement(std::move(expr));
        } else {
          if (peek().type == TokenType::RBRACE) {
            body->setResult(std::move(expr));
          } else {
            _diag.report(pointAfter(expr->span), DiagnosticLevel::Error,
                         "Expected ';' after expression.");
            body->addStatement(std::move(expr));
          }
        }
      }
    } catch (const ParseError &e) {
      synchronize();
    }
  }
  return body;
}
References _builder, _diag, ASSIGN, BREAK, CONST, CONTINUE, eat(), zap::Error, FAIL, FOR, ID, IF, IFTYPE, isAtEnd(), LPAREN, SourceSpan::merge(), parseBreak(), parseConstDecl(), parseContinue(), parseExpression(), parseFail(), parseFor(), parseForIn(), parseIf(), parseIfType(), parseReturnStmt(), parseUnsafeBlock(), parseVarDecl(), parseWhile(), peek(), pointAfter(), RBRACE, RETURN, SEMICOLON, Token::span, synchronize(), UNSAFE, VAR, and WHILE.
Referenced by parseFailableExpression(), parseFor(), parseForIn(), parseFunDecl(), parseIf(), parseIfType(), parseUnsafeBlock(), and parseWhile().
parseBreak()
std::unique_ptr< BreakNode > zap::Parser::parseBreak () private
Definition at line 1078 of file parser.cpp.
{
  Token breakKeyword = eat(TokenType::BREAK);
  Token semicolonToken = eat(TokenType::SEMICOLON);
  auto node = _builder.makeBreak();
  _builder.setSpan(node.get(),
                   SourceSpan::merge(breakKeyword.span, semicolonToken.span));
  return node;
}
References _builder, BREAK, eat(), SourceSpan::merge(), SEMICOLON, and Token::span.
Referenced by parseBody().
parseCastExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseCastExpression () private
Definition at line 1174 of file parser.cpp.
{
  auto expr = parseTernaryExpression();
  while (peek().type == TokenType::AS) {
    eat(TokenType::AS);
    auto type = parseType();
    SourceSpan startSpan = expr->span;
    SourceSpan endSpan = type->span;
    auto castExpr = _builder.makeCastExpr(std::move(expr), std::move(type));
    _builder.setSpan(castExpr.get(), SourceSpan::merge(startSpan, endSpan));
    expr = std::move(castExpr);
  }
  return expr;
}
References _builder, AS, eat(), SourceSpan::merge(), parseTernaryExpression(), parseType(), and peek().
Referenced by parseFailableExpression().
parseClassDecl()
std::unique_ptr< ClassDecl > zap::Parser::parseClassDecl () private
Definition at line 1794 of file parser.cpp.
{
  Token classKeyword = eat(TokenType::CLASS);
  Token classNameToken = eat(TokenType::ID);
  auto classDecl = _builder.makeClassDecl(classNameToken.value);
  if (peek().type == TokenType::LESS && isTypeStartToken(peek(1).type)) {
    classDecl->genericParams_ = parseGenericParameterList();
  }
  if (peek().type == TokenType::COLON) {
    eat(TokenType::COLON);
    classDecl->baseType_ = parseType();
  }
  classDecl->genericConstraints_ = parseWhereClauses();
  eat(TokenType::LBRACE);
  while (peek().type != TokenType::RBRACE) {
    Visibility memberVisibility = Visibility::Private;
    if (peek().type == TokenType::PUB || peek().type == TokenType::PRIV ||
        peek().type == TokenType::PROT) {
      Token visToken = eat(peek().type);
      if (visToken.type == TokenType::PUB) {
        memberVisibility = Visibility::Public;
      } else if (visToken.type == TokenType::PROT) {
        memberVisibility = Visibility::Protected;
      }
    }
    if (peek().type == TokenType::FUN || peek().type == TokenType::STATIC ||
        peek().type == TokenType::UNSAFE) {
      auto method = parseFunDecl();
      method->visibility_ = memberVisibility;
      classDecl->methods_.push_back(std::move(method));
    } else {
      auto field = parseParameter();
      field->visibility_ = memberVisibility;
      classDecl->fields_.push_back(std::move(field));
      if (peek().type == TokenType::COMMA ||
          peek().type == TokenType::SEMICOLON) {
        eat(peek().type);
      }
    }
  }
  Token rbraceToken = eat(TokenType::RBRACE);
  _builder.setSpan(classDecl.get(),
                   SourceSpan::merge(classKeyword.span, rbraceToken.span));
  return classDecl;
}
References _builder, CLASS, COLON, COMMA, eat(), FUN, ID, isTypeStartToken(), LBRACE, LESS, SourceSpan::merge(), parseFunDecl(), parseGenericParameterList(), parseParameter(), parseType(), parseWhereClauses(), peek(), PRIV, Private, PROT, Protected, PUB, Public, RBRACE, SEMICOLON, Token::span, STATIC, Token::type, UNSAFE, and Token::value.
Referenced by parse().
parseConstDecl()
std::unique_ptr< ConstDecl > zap::Parser::parseConstDecl () private
Definition at line 475 of file parser.cpp.
{
  Token constKeyword = eat(TokenType::CONST);
  Token constNameToken = eat(TokenType::ID);
  eat(TokenType::COLON);
  auto typeNode = parseType();
  eat(TokenType::ASSIGN);
  auto expr = parseExpression();
  Token semicolonToken = eat(TokenType::SEMICOLON);
  auto constDecl = _builder.makeConstDecl(constNameToken.value,
                                          std::move(typeNode), std::move(expr));
  _builder.setSpan(constDecl.get(),
                   SourceSpan::merge(constKeyword.span, semicolonToken.span));
  return constDecl;
}
References _builder, ASSIGN, COLON, CONST, eat(), ID, SourceSpan::merge(), parseExpression(), parseType(), SEMICOLON, Token::span, and Token::value.
Referenced by parse(), and parseBody().
parseContinue()
std::unique_ptr< ContinueNode > zap::Parser::parseContinue () private
Definition at line 1087 of file parser.cpp.
{
  Token continueKeyword = eat(TokenType::CONTINUE);
  Token semicolonToken = eat(TokenType::SEMICOLON);
  auto node = _builder.makeContinue();
  _builder.setSpan(
      node.get(), SourceSpan::merge(continueKeyword.span, semicolonToken.span));
  return node;
}
References _builder, CONTINUE, eat(), SourceSpan::merge(), SEMICOLON, and Token::span.
Referenced by parseBody().
parseEnumDecl()
std::unique_ptr< EnumDecl > zap::Parser::parseEnumDecl () private
Definition at line 1655 of file parser.cpp.
{
  Token enumKeyword = eat(TokenType::ENUM);
  Token enumNameToken = eat(TokenType::ID);
  std::vector<EnumDecl::Entry> entries;
  eat(TokenType::LBRACE);
  while (peek().type != TokenType::RBRACE) {
    Token entryToken = eat(TokenType::ID);
    if (peek().type == TokenType::ASSIGN) {
      Token assignToken = eat(TokenType::ASSIGN);
      bool isNegative = false;
      if (peek().type == TokenType::MINUS) {
        eat(TokenType::MINUS);
        isNegative = true;
      }
      Token valueToken = eat(TokenType::INTEGER);
      int base = 10;
      std::string parseValue = valueToken.value;
      if (valueToken.value.size() > 2 && valueToken.value[0] == '0') {
        if (valueToken.value[1] == 'x' || valueToken.value[1] == 'X') {
          base = 16;
        } else if (valueToken.value[1] == 'b' || valueToken.value[1] == 'B') {
          base = 2;
          parseValue = valueToken.value.substr(2);
        } else if (valueToken.value[1] == 'o' || valueToken.value[1] == 'O') {
          base = 8;
          parseValue = valueToken.value.substr(2);
        }
      }
      try {
        uint64_t unsignedValue = std::stoull(parseValue, nullptr, base);
        int64_t signedValue = 0;
        if (isNegative) {
          const uint64_t minAbs =
              static_cast<uint64_t>(std::numeric_limits<int64_t>::max()) + 1ULL;
          if (unsignedValue > minAbs) {
            _diag.report(valueToken.span, DiagnosticLevel::Error,
                         "Enum value out of range for signed 64-bit integer: -" +
                             valueToken.value);
            throw ParseError();
          }
          if (unsignedValue == minAbs) {
            signedValue = std::numeric_limits<int64_t>::min();
          } else {
            signedValue = -static_cast<int64_t>(unsignedValue);
          }
        } else {
          if (unsignedValue >
              static_cast<uint64_t>(std::numeric_limits<int64_t>::max())) {
            _diag.report(valueToken.span, DiagnosticLevel::Error,
                         "Enum value out of range for signed 64-bit integer: " +
                             valueToken.value);
            throw ParseError();
          }
          signedValue = static_cast<int64_t>(unsignedValue);
        }
        entries.emplace_back(entryToken.value, signedValue);
      } catch (const ParseError &) {
        throw;
      } catch (const std::exception &) {
        _diag.report(
            SourceSpan::merge(assignToken.span, valueToken.span),
            DiagnosticLevel::Error,
            "Invalid enum value, expected integer literal after '='.");
        throw ParseError();
      }
    } else {
      entries.emplace_back(entryToken.value);
    }
    if (peek().type != TokenType::COMMA) {
      break;
    }
    eat(TokenType::COMMA);
  }
  Token rbraceToken = eat(TokenType::RBRACE);
  auto enumDecl =
      _builder.makeEnumDecl(enumNameToken.value, std::move(entries));
  _builder.setSpan(enumDecl.get(),
                   SourceSpan::merge(enumKeyword.span, rbraceToken.span));
  return enumDecl;
}
References _builder, _diag, ASSIGN, COMMA, eat(), ENUM, zap::Error, ID, INTEGER, LBRACE, SourceSpan::merge(), MINUS, peek(), RBRACE, Token::span, and Token::value.
Referenced by parse().
parseExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseExpression () private
Definition at line 1107 of file parser.cpp.
{
  return parseFailableExpression();
}
References parseFailableExpression().
Referenced by parseArrayLiteral(), parseAssign(), parseBody(), parseConstDecl(), parseFail(), parseFor(), parseForIn(), parseForIncrementAssign(), parseForInitVarDecl(), parseIf(), parsePostfixExpression(), parsePrimaryExpression(), parseReturnStmt(), parseSingleAttribute(), parseStructLiteral(), parseType(), parseVarDecl(), and parseWhile().
parseExtDecl()
std::unique_ptr< ExtDecl > zap::Parser::parseExtDecl () private
Definition at line 299 of file parser.cpp.
{
  Token externKeyword = eat(TokenType::EXTERN);
  Token funKeyword = eat(TokenType::FUN);
  Token funNameToken = eat(TokenType::ID);
  auto extDecl = std::make_unique<ExtDecl>();
  extDecl->name_ = funNameToken.value;
  eat(TokenType::LPAREN);
  if (peek().type != TokenType::RPAREN) {
    do {
      if (peek().type == TokenType::ELLIPSIS) {
        eat(TokenType::ELLIPSIS);
        extDecl->isCVariadic_ = true;
        break;
      }
      extDecl->params_.push_back(parseParameter());
    } while (peek().type == TokenType::COMMA &&
             eat(TokenType::COMMA).type == TokenType::COMMA);
  }
  eat(TokenType::RPAREN);
  if (peek().type != TokenType::SEMICOLON) {
    extDecl->returnType_ = parseType();
  } else {
    extDecl->returnType_ = _builder.makeType("Void");
    const auto &nextToken = peek();
    _builder.setSpan(extDecl->returnType_.get(),
                     SourceSpan(nextToken.span.line, nextToken.span.column,
                                nextToken.span.offset, 0));
  }
  Token semiToken = eat(TokenType::SEMICOLON);
  _builder.setSpan(extDecl.get(),
                   SourceSpan::merge(funNameToken.span, semiToken.span));
  return extDecl;
}
References _builder, COMMA, eat(), ELLIPSIS, EXTERN, FUN, ID, LPAREN, SourceSpan::merge(), parseParameter(), parseType(), peek(), RPAREN, SEMICOLON, Token::span, and Token::value.
Referenced by parse().
parseFail()
std::unique_ptr< FailNode > zap::Parser::parseFail () private
Definition at line 1096 of file parser.cpp.
{
  Token failKeyword = eat(TokenType::FAIL);
  auto errorValue = parseExpression();
  Token semicolonToken = eat(TokenType::SEMICOLON);
  auto node = _builder.makeFail(std::move(errorValue));
  _builder.setSpan(node.get(),
                   SourceSpan::merge(failKeyword.span, semicolonToken.span));
  return node;
}
References _builder, eat(), FAIL, SourceSpan::merge(), parseExpression(), SEMICOLON, and Token::span.
Referenced by parseBody().
parseFailableExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseFailableExpression () private
Definition at line 1111 of file parser.cpp.
{
  auto expr = parseCastExpression();
  while (peek().type == TokenType::OR && peek().value == "or") {
    eat(TokenType::OR);
    SourceSpan startSpan = expr->span;
    if (peek().type == TokenType::ID && peek().value == "err" &&
        peek(1).type == TokenType::LBRACE) {
      Token errToken = eat(TokenType::ID);
      eat(TokenType::LBRACE);
      auto handler = parseBody();
      Token rbraceToken = eat(TokenType::RBRACE);
      auto handled = _builder.makeFailableHandleExpr(
          std::move(expr), errToken.value, std::move(handler));
      _builder.setSpan(handled.get(),
                       SourceSpan::merge(startSpan, rbraceToken.span));
      expr = std::move(handled);
      continue;
    }
    bool oldAllowStructLiteral = _allowStructLiteral;
    _allowStructLiteral = true;
    std::unique_ptr<ExpressionNode> fallback;
    if (peek().type == TokenType::ID && peek(1).type == TokenType::LBRACE) {
      Token typeToken = eat(TokenType::ID);
      auto typeNode = _builder.makeType(typeToken.value);
      _builder.setSpan(typeNode.get(), typeToken.span);
      fallback = parseStructLiteral(std::move(typeNode));
    } else {
      fallback = parseCastExpression();
    }
    _allowStructLiteral = oldAllowStructLiteral;
    SourceSpan endSpan = fallback->span;
    auto fallbackExpr =
        _builder.makeFallbackExpr(std::move(expr), std::move(fallback));
    _builder.setSpan(fallbackExpr.get(),
                     SourceSpan::merge(startSpan, endSpan));
    expr = std::move(fallbackExpr);
  }
  return expr;
}
References _allowStructLiteral, _builder, eat(), ID, LBRACE, SourceSpan::merge(), OR, parseBody(), parseCastExpression(), parseStructLiteral(), peek(), RBRACE, Token::span, and Token::value.
Referenced by parseExpression().
parseFor()
std::unique_ptr< ForNode > zap::Parser::parseFor () private
Definition at line 988 of file parser.cpp.
{
  Token forKeyword = eat(TokenType::FOR);
  bool hasParen = false;
  if (peek().type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    hasParen = true;
  }
  if (peek().type != TokenType::VAR) {
    _diag.report(peek().span, DiagnosticLevel::Error,
                 "For initializer must be a variable declaration.");
    throw ParseError();
  }
  auto initializer = parseForInitVarDecl();
  eat(TokenType::SEMICOLON);
  bool oldAllow = _allowStructLiteral;
  _allowStructLiteral = false;
  auto condition = parseExpression();
  _allowStructLiteral = oldAllow;
  eat(TokenType::SEMICOLON);
  auto increment = parseForIncrementAssign();
  if (hasParen) {
    eat(TokenType::RPAREN);
  }
  eat(TokenType::LBRACE);
  auto body = parseBody();
  Token rbraceToken = eat(TokenType::RBRACE);
  auto forNode = _builder.makeFor(std::move(initializer), std::move(condition),
                                  std::move(increment), std::move(body));
  _builder.setSpan(forNode.get(),
                   SourceSpan::merge(forKeyword.span, rbraceToken.span));
  return forNode;
}
References _allowStructLiteral, _builder, _diag, eat(), zap::Error, FOR, LBRACE, LPAREN, SourceSpan::merge(), parseBody(), parseExpression(), parseForIncrementAssign(), parseForInitVarDecl(), peek(), RBRACE, RPAREN, SEMICOLON, Token::span, and VAR.
Referenced by parseBody().
parseForIn()
std::unique_ptr< ForInNode > zap::Parser::parseForIn () private
Definition at line 1027 of file parser.cpp.
{
  Token forKeyword = eat(TokenType::FOR);
  bool hasParen = false;
  if (peek().type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    hasParen = true;
  }
  Token itemToken = eat(TokenType::ID);
  if (peek().type != TokenType::ID || peek().value != "in") {
    _diag.report(peek().span, DiagnosticLevel::Error,
                 "Expected 'in' in for-in loop.");
    throw ParseError();
  }
  eat(TokenType::ID); // "in"
  bool oldAllow = _allowStructLiteral;
  _allowStructLiteral = false;
  auto iterable = parseExpression();
  _allowStructLiteral = oldAllow;
  if (hasParen) {
    eat(TokenType::RPAREN);
  }
  eat(TokenType::LBRACE);
  auto body = parseBody();
  Token rbraceToken = eat(TokenType::RBRACE);
  auto forInNode =
      _builder.makeForIn(itemToken.value, std::move(iterable), std::move(body));
  _builder.setSpan(forInNode.get(),
                   SourceSpan::merge(forKeyword.span, rbraceToken.span));
  return forInNode;
}
References _allowStructLiteral, _builder, _diag, eat(), zap::Error, FOR, ID, LBRACE, LPAREN, SourceSpan::merge(), parseBody(), parseExpression(), peek(), RBRACE, RPAREN, Token::span, and Token::value.
Referenced by parseBody().
parseForIncrementAssign()
std::unique_ptr< AssignNode > zap::Parser::parseForIncrementAssign () private
Definition at line 978 of file parser.cpp.
{
  auto target = parseExpression();
  eat(TokenType::ASSIGN);
  auto expr = parseExpression();
  auto assign = _builder.makeAssign(std::move(target), std::move(expr));
  _builder.setSpan(assign.get(),
                   SourceSpan::merge(assign->target_->span, assign->expr_->span));
  return assign;
}
References _builder, ASSIGN, eat(), SourceSpan::merge(), and parseExpression().
Referenced by parseFor().
parseForInitVarDecl()
std::unique_ptr< VarDecl > zap::Parser::parseForInitVarDecl () private
Definition at line 957 of file parser.cpp.
{
  Token varKeyword = eat(TokenType::VAR);
  Token varNameToken = eat(TokenType::ID);
  eat(TokenType::COLON);
  auto typeNode = parseType();
  std::unique_ptr<ExpressionNode> initializer = nullptr;
  SourceSpan endSpan = typeNode ? typeNode->span : varNameToken.span;
  if (peek().type == TokenType::ASSIGN) {
    eat(TokenType::ASSIGN);
    initializer = parseExpression();
    endSpan = initializer->span;
  }
  auto varDecl = _builder.makeVarDecl(varNameToken.value, std::move(typeNode),
                                      std::move(initializer));
  _builder.setSpan(varDecl.get(), SourceSpan::merge(varKeyword.span, endSpan));
  return varDecl;
}
References _builder, ASSIGN, COLON, eat(), ID, SourceSpan::merge(), parseExpression(), parseType(), peek(), Token::span, Token::value, and VAR.
Referenced by parseFor().
parseFunDecl()
std::unique_ptr< FunDecl > zap::Parser::parseFunDecl (bool isUnsafe = false) private
Definition at line 241 of file parser.cpp.
{
  bool isStatic = false;
  while (peek().type == TokenType::STATIC ||
         peek().type == TokenType::UNSAFE) {
    if (peek().type == TokenType::STATIC) {
      eat(TokenType::STATIC);
      isStatic = true;
    } else {
      eat(TokenType::UNSAFE);
      isUnsafe = true;
    }
  }
  Token funKeyword = eat(TokenType::FUN);
  Token funNameToken = eat(TokenType::ID);
  auto funDecl = _builder.makeFunDecl(funNameToken.value);
  funDecl->isUnsafe_ = isUnsafe;
  funDecl->isStatic_ = isStatic;
  if (peek().type == TokenType::LESS && isTypeStartToken(peek(1).type)) {
    funDecl->genericParams_ = parseGenericParameterList();
  }
  eat(TokenType::LPAREN);
  if (peek().type != TokenType::RPAREN) {
    do {
      funDecl->params_.push_back(parseParameter());
    } while (peek().type == TokenType::COMMA &&
             eat(TokenType::COMMA).type == TokenType::COMMA);
  }
  eat(TokenType::RPAREN);
  if (peek().type == TokenType::REF) {
    eat(TokenType::REF);
    funDecl->returnsRef_ = true;
  }
  if (peek().type != TokenType::LBRACE) {
    funDecl->returnType_ = parseType();
  } else {
    funDecl->returnType_.reset();
  }
  funDecl->genericConstraints_ = parseWhereClauses();
  eat(TokenType::LBRACE);
  funDecl->body_ = parseBody();
  Token rbraceToken = eat(TokenType::RBRACE);
  _builder.setSpan(funDecl.get(),
                   SourceSpan::merge(funNameToken.span, rbraceToken.span));
  return funDecl;
}
References _builder, COMMA, eat(), FUN, ID, isTypeStartToken(), LBRACE, LESS, LPAREN, SourceSpan::merge(), parseBody(), parseGenericParameterList(), parseParameter(), parseType(), parseWhereClauses(), peek(), RBRACE, REF, RPAREN, Token::span, STATIC, UNSAFE, and Token::value.
Referenced by parse(), and parseClassDecl().
parseGenericParameterList()
std::vector< std::unique_ptr< TypeNode > > zap::Parser::parseGenericParameterList () private
Definition at line 520 of file parser.cpp.
{
  std::vector<std::unique_ptr<TypeNode>> params;
  eat(TokenType::LESS);
  if (peek().type != TokenType::GREATER) {
    do {
      auto param = parseType();
      if (peek().type == TokenType::ASSIGN) {
        eat(TokenType::ASSIGN);
        param->defaultType = parseType();
        _builder.setSpan(
            param.get(),
            SourceSpan::merge(param->span, param->defaultType->span));
      }
      params.push_back(std::move(param));
    } while (peek().type == TokenType::COMMA &&
             eat(TokenType::COMMA).type == TokenType::COMMA);
  }
  eat(TokenType::GREATER);
  return params;
}
References _builder, ASSIGN, COMMA, eat(), GREATER, LESS, SourceSpan::merge(), parseType(), and peek().
Referenced by parseClassDecl(), parseFunDecl(), parseRecordDecl(), and parseStructDecl().
parseGenericTypeArguments()
std::vector< std::unique_ptr< TypeNode > > zap::Parser::parseGenericTypeArguments () private
Definition at line 507 of file parser.cpp.
{
  std::vector<std::unique_ptr<TypeNode>> args;
  eat(TokenType::LESS);
  if (peek().type != TokenType::GREATER) {
    do {
      args.push_back(parseType());
    } while (peek().type == TokenType::COMMA &&
             eat(TokenType::COMMA).type == TokenType::COMMA);
  }
  eat(TokenType::GREATER);
  return args;
}
References COMMA, eat(), GREATER, LESS, parseType(), and peek().
Referenced by parsePostfixExpression(), parsePrimaryExpression(), and parseType().
parseIf()
std::unique_ptr< IfNode > zap::Parser::parseIf () private
Definition at line 838 of file parser.cpp.
{
  Token ifKeyword = eat(TokenType::IF);
  bool hasParen = false;
  if (peek().type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    hasParen = true;
  }
  bool oldAllow = _allowStructLiteral;
  if (!hasParen) {
    _allowStructLiteral = false;
  }
  auto condition = parseExpression();
  _allowStructLiteral = oldAllow;
  if (hasParen) {
    eat(TokenType::RPAREN);
  }
  eat(TokenType::LBRACE);
  auto thenBody = parseBody();
  eat(TokenType::RBRACE);
  std::unique_ptr<BodyNode> elseBody = nullptr;
  SourceSpan endSpan = _tokens[_pos - 1].span;
  if (peek().type == TokenType::ELSE) {
    eat(TokenType::ELSE);
    if (peek().type == TokenType::IF) {
      auto nestedIf = parseIf();
      elseBody = _builder.makeBody();
      SourceSpan nestedSpan = nestedIf->span;
      elseBody->addStatement(std::move(nestedIf));
      _builder.setSpan(elseBody.get(), nestedSpan);
      endSpan = nestedSpan;
    } else {
      eat(TokenType::LBRACE);
      elseBody = parseBody();
      Token rbrace = eat(TokenType::RBRACE);
      endSpan = rbrace.span;
    }
  }
  auto ifNode = _builder.makeIf(std::move(condition), std::move(thenBody),
                                std::move(elseBody));
  _builder.setSpan(ifNode.get(), SourceSpan::merge(ifKeyword.span, endSpan));
  return ifNode;
}
References _allowStructLiteral, _builder, _pos, _tokens, eat(), ELSE, IF, LBRACE, LPAREN, SourceSpan::merge(), parseBody(), parseExpression(), parseIf(), peek(), RBRACE, RPAREN, and Token::span.
Referenced by parseBody(), and parseIf().
parseIfType()
std::unique_ptr< IfTypeNode > zap::Parser::parseIfType () private
Definition at line 889 of file parser.cpp.
{
  Token iftypeKeyword = eat(TokenType::IFTYPE);
  Token paramToken = eat(TokenType::ID);
  eat(TokenType::EQUAL);
  auto matchType = parseType();
  eat(TokenType::LBRACE);
  auto thenBody = parseBody();
  eat(TokenType::RBRACE);
  std::unique_ptr<BodyNode> elseBody = nullptr;
  SourceSpan endSpan = _tokens[_pos - 1].span;
  if (peek().type == TokenType::ELSE) {
    eat(TokenType::ELSE);
    if (peek().type == TokenType::IFTYPE) {
      auto nestedIfType = parseIfType();
      elseBody = _builder.makeBody();
      SourceSpan nestedSpan = nestedIfType->span;
      elseBody->addStatement(std::move(nestedIfType));
      _builder.setSpan(elseBody.get(), nestedSpan);
      endSpan = nestedSpan;
    } else {
      eat(TokenType::LBRACE);
      elseBody = parseBody();
      Token rbrace = eat(TokenType::RBRACE);
      endSpan = rbrace.span;
    }
  }
  auto ifTypeNode = _builder.makeIfType(paramToken.value, std::move(matchType),
                                        std::move(thenBody),
                                        std::move(elseBody));
  _builder.setSpan(ifTypeNode.get(),
                   SourceSpan::merge(iftypeKeyword.span, endSpan));
  return ifTypeNode;
}
References _builder, _pos, _tokens, eat(), ELSE, EQUAL, ID, IFTYPE, LBRACE, SourceSpan::merge(), parseBody(), parseIfType(), parseType(), peek(), RBRACE, Token::span, and Token::value.
Referenced by parseBody(), and parseIfType().
parseImportDecl()
std::unique_ptr< ImportNode > zap::Parser::parseImportDecl () private
Definition at line 205 of file parser.cpp.
{
  Token importKeyword = eat(TokenType::IMPORT);
  Token pathToken = eat(TokenType::STRING);
  std::string moduleAlias;
  std::vector<ImportBinding> bindings;
  if (peek().type == TokenType::AS) {
    eat(TokenType::AS);
    moduleAlias = eat(TokenType::ID).value;
  }
  if (peek().type == TokenType::LBRACE) {
    eat(TokenType::LBRACE);
    if (peek().type != TokenType::RBRACE) {
      do {
        Token sourceToken = eat(TokenType::ID);
        std::string localName = sourceToken.value;
        if (peek().type == TokenType::AS) {
          eat(TokenType::AS);
          localName = eat(TokenType::ID).value;
        }
        bindings.push_back({sourceToken.value, localName});
      } while (peek().type == TokenType::COMMA &&
               eat(TokenType::COMMA).type == TokenType::COMMA);
    }
    eat(TokenType::RBRACE);
  }
  Token semiToken = eat(TokenType::SEMICOLON);
  auto importDecl = _builder.makeImport(pathToken.value, std::move(moduleAlias),
                                        std::move(bindings));
  _builder.setSpan(importDecl.get(),
                   SourceSpan::merge(importKeyword.span, semiToken.span));
  return importDecl;
}
References _builder, AS, COMMA, eat(), ID, IMPORT, LBRACE, SourceSpan::merge(), peek(), RBRACE, SEMICOLON, Token::span, STRING, and Token::value.
Referenced by parse().
parseParameter()
std::unique_ptr< ParameterNode > zap::Parser::parseParameter () private
Definition at line 430 of file parser.cpp.
{
  bool isRef = false;
  if (peek().type == TokenType::REF) {
    eat(TokenType::REF);
    isRef = true;
  }
  Token paramNameToken = eat(TokenType::ID);
  eat(TokenType::COLON);
  auto typeNode = parseType();
  bool isVariadic = typeNode && typeNode->isVarArgs;
  auto paramNode = _builder.makeParam(paramNameToken.value, std::move(typeNode),
                                      isRef, isVariadic);
  _builder.setSpan(paramNode.get(), SourceSpan::merge(paramNameToken.span,
                                                      paramNode->type->span));
  return paramNode;
}
References _builder, COLON, eat(), ID, SourceSpan::merge(), parseType(), peek(), REF, Token::span, and Token::value.
Referenced by parseClassDecl(), parseExtDecl(), parseFunDecl(), parseRecordDecl(), and parseStructDecl().
parsePostfixExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parsePostfixExpression () private
Definition at line 1257 of file parser.cpp.
{
  auto left = parsePrimaryExpression();
  while (true) {
    if (isAtEnd())
      break;
    Token opToken = peek();
    if (opToken.type == TokenType::DOT) {
      eat(TokenType::DOT);
      Token memberToken = eat(TokenType::ID);
      SourceSpan leftSpan = left->span;
      left = std::move(
          _builder.makeMemberAccess(std::move(left), memberToken.value));
      _builder.setSpan(left.get(),
                       SourceSpan::merge(leftSpan, memberToken.span));
    } else if (opToken.type == TokenType::SQUARE_LBRACE) {
      eat(TokenType::SQUARE_LBRACE);
      auto index = parseExpression();
      Token rbracket = eat(TokenType::SQUARE_RBRACE);
      SourceSpan leftSpan = left->span;
      left = _builder.makeIndexAccess(std::move(left), std::move(index));
      _builder.setSpan(left.get(), SourceSpan::merge(leftSpan, rbracket.span));
    } else if (_allowStructLiteral && opToken.type == TokenType::LESS &&
               isGenericStructLiteralStart()) {
      auto typeNode = typeNodeFromQualifiedExpression(left.get());
      if (!typeNode) {
        break;
      }
      typeNode->genericArgs = parseGenericTypeArguments();
      auto structLiteral = parseStructLiteral(std::move(typeNode));
      left = std::move(structLiteral);
    } else if (opToken.type == TokenType::LESS && isGenericCallStart()) {
      auto genericCall = _builder.makeFunCall(std::move(left));
      SourceSpan leftSpan = genericCall->callee_->span;
      genericCall->genericArgs_ = parseGenericTypeArguments();
      eat(TokenType::LPAREN);
      if (peek().type != TokenType::RPAREN) {
        do {
          std::string argName = "";
          bool argIsRef = false;
          bool argIsSpread = false;
          if (peek().type == TokenType::ID &&
              peek(1).type == TokenType::ASSIGN) {
            argName = eat(TokenType::ID).value;
            eat(TokenType::ASSIGN);
          }
          if (peek().type == TokenType::ELLIPSIS) {
            eat(TokenType::ELLIPSIS);
            argIsSpread = true;
          }
          if (peek().type == TokenType::REF) {
            eat(TokenType::REF);
            argIsRef = true;
          }
          auto argValue = parseExpression();
          genericCall->params_.push_back(std::make_unique<Argument>(
              argName, std::move(argValue), argIsRef, argIsSpread));
        } while (peek().type == TokenType::COMMA &&
                 eat(TokenType::COMMA).type == TokenType::COMMA);
      }
      Token rparenToken = eat(TokenType::RPAREN);
      _builder.setSpan(genericCall.get(),
                       SourceSpan::merge(leftSpan, rparenToken.span));
      left = std::move(genericCall);
    } else if (opToken.type == TokenType::LPAREN) {
      SourceSpan leftSpan = left->span;
      auto funCall = _builder.makeFunCall(std::move(left));
      eat(TokenType::LPAREN);
      if (peek().type != TokenType::RPAREN) {
        do {
          std::string argName = "";
          bool argIsRef = false;
          bool argIsSpread = false;
          if (peek().type == TokenType::ID &&
              peek(1).type == TokenType::ASSIGN) {
            argName = eat(TokenType::ID).value;
            eat(TokenType::ASSIGN);
          }
          if (peek().type == TokenType::ELLIPSIS) {
            eat(TokenType::ELLIPSIS);
            argIsSpread = true;
          }
          if (peek().type == TokenType::REF) {
            eat(TokenType::REF);
            argIsRef = true;
          }
          auto argValue = parseExpression();
          funCall->params_.push_back(std::make_unique<Argument>(
              argName, std::move(argValue), argIsRef, argIsSpread));
        } while (peek().type == TokenType::COMMA &&
                 eat(TokenType::COMMA).type == TokenType::COMMA);
      }
      Token rparenToken = eat(TokenType::RPAREN);
      _builder.setSpan(funCall.get(),
                       SourceSpan::merge(leftSpan, rparenToken.span));
      left = std::move(funCall);
    } else if (opToken.type == TokenType::QUESTION &&
               isTryPostfixContext(peek(1).type)) {
      eat(TokenType::QUESTION);
      SourceSpan leftSpan = left->span;
      auto tryExpr = _builder.makeTryExpr(std::move(left));
      _builder.setSpan(tryExpr.get(), SourceSpan::merge(leftSpan, opToken.span));
      left = std::move(tryExpr);
    } else if (_allowStructLiteral && opToken.type == TokenType::LBRACE) {
      auto qualifiedTypeName = qualifiedNameFromExpression(left.get());
      if (qualifiedTypeName.empty()) {
        break;
      }
      auto structLiteral = parseStructLiteral(qualifiedTypeName);
      left = std::move(structLiteral);
    } else {
      break;
    }
  }
  return left;
}
References _allowStructLiteral, _builder, ASSIGN, COMMA, DOT, eat(), ELLIPSIS, ID, isAtEnd(), isGenericCallStart(), isGenericStructLiteralStart(), isTryPostfixContext(), LBRACE, LESS, LPAREN, SourceSpan::merge(), parseExpression(), parseGenericTypeArguments(), parsePrimaryExpression(), parseStructLiteral(), peek(), QUESTION, REF, RPAREN, Token::span, SQUARE_LBRACE, SQUARE_RBRACE, Token::type, typeNodeFromQualifiedExpression(), and Token::value.
Referenced by parseUnaryExpression().
parsePrimaryExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parsePrimaryExpression () private
Definition at line 1380 of file parser.cpp.
{
  Token current = peek();
  if (current.type == TokenType::NEW) {
    Token newToken = eat(TokenType::NEW);
    auto type = parseType();
    auto newExpr = _builder.makeNewExpr(std::move(type));
    eat(TokenType::LPAREN);
    if (peek().type != TokenType::RPAREN) {
      do {
        std::string argName = "";
        bool argIsRef = false;
        bool argIsSpread = false;
        if (peek().type == TokenType::ID && peek(1).type == TokenType::ASSIGN) {
          argName = eat(TokenType::ID).value;
          eat(TokenType::ASSIGN);
        }
        if (peek().type == TokenType::ELLIPSIS) {
          eat(TokenType::ELLIPSIS);
          argIsSpread = true;
        }
        if (peek().type == TokenType::REF) {
          eat(TokenType::REF);
          argIsRef = true;
        }
        auto argValue = parseExpression();
        newExpr->args_.push_back(std::make_unique<Argument>(
            argName, std::move(argValue), argIsRef, argIsSpread));
      } while (peek().type == TokenType::COMMA &&
               eat(TokenType::COMMA).type == TokenType::COMMA);
    }
    Token rparenToken = eat(TokenType::RPAREN);
    _builder.setSpan(newExpr.get(),
                     SourceSpan::merge(newToken.span, rparenToken.span));
    return newExpr;
  } else if (current.type == TokenType::INTEGER) {
    eat(TokenType::INTEGER);
    try {
      int base = 10;
      std::string parseValue = current.value;
      if (current.value.size() > 2 && current.value[0] == '0') {
        if (current.value[1] == 'x' || current.value[1] == 'X') {
          base = 16;
        } else if (current.value[1] == 'b' || current.value[1] == 'B') {
          base = 2;
          parseValue = current.value.substr(2);
        } else if (current.value[1] == 'o' || current.value[1] == 'O') {
          base = 8;
          parseValue = current.value.substr(2);
        }
      }
      (void)std::stoull(parseValue, nullptr, base);
    } catch (const std::exception &) {
      _diag.report(current.span, DiagnosticLevel::Error,
                   "Invalid integer literal: " + current.value);
      throw ParseError();
    }
    auto constInt = _builder.makeConstInt(current.value);
    _builder.setSpan(constInt.get(), current.span);
    return constInt;
  } else if (current.type == TokenType::FLOAT) {
    eat(TokenType::FLOAT);
    auto constFloat = _builder.makeConstFloat(std::stod(current.value));
    _builder.setSpan(constFloat.get(), current.span);
    return constFloat;
  } else if (current.type == TokenType::STRING) {
    eat(TokenType::STRING);
    auto constStr = _builder.makeConstString(current.value);
    _builder.setSpan(constStr.get(), current.span);
    return constStr;
  } else if (current.type == TokenType::CHAR) {
    eat(TokenType::CHAR);
    auto constChar = _builder.makeConstChar(current.value);
    _builder.setSpan(constChar.get(), current.span);
    return constChar;
  } else if (current.type == TokenType::BOOL) {
    eat(TokenType::BOOL);
    auto constBool = _builder.makeConstBool(current.value == "true");
    _builder.setSpan(constBool.get(), current.span);
    return constBool;
  } else if (current.type == TokenType::NULL_LITERAL) {
    eat(TokenType::NULL_LITERAL);
    auto constNull = _builder.makeConstNull();
    _builder.setSpan(constNull.get(), current.span);
    return constNull;
  } else if (current.type == TokenType::ID) {
    Token idToken = eat(TokenType::ID);
    if (_allowStructLiteral && peek().type == TokenType::LESS &&
        isGenericStructLiteralStart()) {
      auto typeNode = _builder.makeType(idToken.value);
      typeNode->genericArgs = parseGenericTypeArguments();
      return parseStructLiteral(std::move(typeNode));
    } else if (_allowStructLiteral && peek().type == TokenType::LBRACE) {
      auto typeNode = _builder.makeType(idToken.value);
      _builder.setSpan(typeNode.get(), idToken.span);
      return parseStructLiteral(std::move(typeNode));
    } else {
      auto constId = _builder.makeConstId(idToken.value);
      _builder.setSpan(constId.get(), idToken.span);
      return constId;
    }
  } else if (current.type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    bool oldAllow = _allowStructLiteral;
    _allowStructLiteral = true;
    auto expr = parseExpression();
    _allowStructLiteral = oldAllow;
    Token rparenToken = eat(TokenType::RPAREN);
    _builder.setSpan(static_cast<ExpressionNode *>(expr.get()),
                     SourceSpan::merge(current.span, rparenToken.span));
    return expr;
  } else if (current.type == TokenType::LBRACE) {
    if (!_allowStructLiteral) {
      _diag.report(current.span, DiagnosticLevel::Error,
                   "Struct literal not allowed in this context");
      throw ParseError();
    }
    return parseArrayLiteral();
  }
  _diag.report(current.span, DiagnosticLevel::Error,
               "Expected primary expression, got " + current.value);
  throw ParseError();
}
References _allowStructLiteral, _builder, _diag, ASSIGN, BOOL, CHAR, COMMA, eat(), ELLIPSIS, zap::Error, FLOAT, ID, INTEGER, isGenericStructLiteralStart(), LBRACE, LESS, LPAREN, SourceSpan::merge(), NEW, NULL_LITERAL, parseArrayLiteral(), parseExpression(), parseGenericTypeArguments(), parseStructLiteral(), parseType(), peek(), REF, RPAREN, Token::span, STRING, Token::type, and Token::value.
Referenced by parsePostfixExpression().
parseQualifiedIdentifier()
std::vector< std::string > zap::Parser::parseQualifiedIdentifier () private
Definition at line 1643 of file parser.cpp.
{
  std::vector<std::string> parts;
  parts.push_back(eat(TokenType::ID).value);
  while (peek().type == TokenType::DOT) {
    eat(TokenType::DOT);
    parts.push_back(eat(TokenType::ID).value);
  }
  return parts;
}
References DOT, eat(), ID, and peek().
Referenced by parseType().
parseRecordDecl()
std::unique_ptr< RecordDecl > zap::Parser::parseRecordDecl () private
Definition at line 1763 of file parser.cpp.
{
  Token recordKeyword = eat(TokenType::RECORD);
  Token recordNameToken = eat(TokenType::ID);
  std::vector<std::unique_ptr<TypeNode>> genericParams;
  if (peek().type == TokenType::LESS && isTypeStartToken(peek(1).type)) {
    genericParams = parseGenericParameterList();
  }
  auto genericConstraints = parseWhereClauses();
  std::vector<std::unique_ptr<ParameterNode>> fields;
  eat(TokenType::LBRACE);
  while (peek().type != TokenType::RBRACE) {
    fields.push_back(parseParameter());
    if (peek().type == TokenType::COMMA ||
        peek().type == TokenType::SEMICOLON) {
      eat(peek().type);
    }
  }
  Token rbraceToken = eat(TokenType::RBRACE);
  auto recordDecl =
      _builder.makeRecordDecl(recordNameToken.value, std::move(genericParams),
                              std::move(fields));
  recordDecl->genericConstraints_ = std::move(genericConstraints);
  _builder.setSpan(recordDecl.get(),
                   SourceSpan::merge(recordKeyword.span, rbraceToken.span));
  return recordDecl;
}
References _builder, COMMA, eat(), ID, isTypeStartToken(), LBRACE, LESS, SourceSpan::merge(), parseGenericParameterList(), parseParameter(), parseWhereClauses(), peek(), RBRACE, RECORD, SEMICOLON, Token::span, and Token::value.
Referenced by parse().
parseReturnStmt()
std::unique_ptr< ReturnNode > zap::Parser::parseReturnStmt () private
Definition at line 1063 of file parser.cpp.
{
  Token returnKeyword = eat(TokenType::RETURN);
  std::unique_ptr<ExpressionNode> expr = nullptr;
  if (peek().type != TokenType::SEMICOLON) {
    expr = parseExpression();
  }
  Token semicolonToken = eat(TokenType::SEMICOLON);
  auto returnNode = _builder.makeReturn(std::move(expr));
  _builder.setSpan(returnNode.get(),
                   SourceSpan::merge(returnKeyword.span, semicolonToken.span));
  return returnNode;
}
References _builder, eat(), SourceSpan::merge(), parseExpression(), peek(), RETURN, SEMICOLON, and Token::span.
Referenced by parseBody().
parseSingleAttribute()
AttributeNode zap::Parser::parseSingleAttribute () private
Definition at line 57 of file parser.cpp.
{
  Token nameToken = eat(TokenType::ID);
  AttributeNode attr;
  attr.name = nameToken.value;
  attr.span = nameToken.span;
  if (peek().type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    if (peek().type != TokenType::RPAREN) {
      do {
        AttributeArgument arg;
        if (peek().type == TokenType::ID && peek(1).type == TokenType::COLON) {
          Token argName = eat(TokenType::ID);
          eat(TokenType::COLON);
          arg.kind = AttributeArgumentKind::Named;
          arg.name = argName.value;
          arg.value = parseExpression();
        } else {
          arg.kind = AttributeArgumentKind::Positional;
          arg.value = parseExpression();
        }
        attr.arguments.push_back(std::move(arg));
      } while (peek().type == TokenType::COMMA &&
               eat(TokenType::COMMA).type == TokenType::COMMA);
    }
    Token rparen = eat(TokenType::RPAREN);
    attr.span = SourceSpan::merge(nameToken.span, rparen.span);
  }
  return attr;
}
References AttributeNode::arguments, COLON, COMMA, eat(), ID, AttributeArgument::kind, LPAREN, SourceSpan::merge(), AttributeArgument::name, AttributeNode::name, Named, parseExpression(), peek(), Positional, RPAREN, AttributeNode::span, Token::span, AttributeArgument::value, and Token::value.
Referenced by parseAttributes().
parseStructDecl()
std::unique_ptr< StructDeclarationNode > zap::Parser::parseStructDecl (bool isUnsafe = false) private
Definition at line 1844 of file parser.cpp.
{
  Token structKeyword = eat(TokenType::STRUCT);
  Token structNameToken = eat(TokenType::ID);
  std::vector<std::unique_ptr<TypeNode>> genericParams;
  if (peek().type == TokenType::LESS && isTypeStartToken(peek(1).type)) {
    genericParams = parseGenericParameterList();
  }
  auto genericConstraints = parseWhereClauses();
  std::vector<std::unique_ptr<ParameterNode>> fields;
  eat(TokenType::LBRACE);
  if (peek().type != TokenType::RBRACE) {
    do {
      fields.push_back(parseParameter());
      if (peek().type == TokenType::COMMA ||
          peek().type == TokenType::SEMICOLON) {
        eat(peek().type);
      } else {
        break;
      }
    } while (peek().type != TokenType::RBRACE);
  }
  eat(TokenType::RBRACE);
  auto decl = std::make_unique<StructDeclarationNode>(
      structNameToken.value, std::move(genericParams), std::move(fields),
      isUnsafe);
  decl->genericConstraints_ = std::move(genericConstraints);
  return decl;
}
References COMMA, eat(), ID, isTypeStartToken(), LBRACE, LESS, parseGenericParameterList(), parseParameter(), parseWhereClauses(), peek(), RBRACE, SEMICOLON, STRUCT, and Token::value.
Referenced by parse().
parseStructLiteral() [1/2]
std::unique_ptr< StructLiteralNode > zap::Parser::parseStructLiteral (const std::string & type_name) private
Definition at line 1878 of file parser.cpp.
{
  auto typeNode = _builder.makeType("");
  size_t start = 0;
  while (true) {
    size_t dot = type_name.find('.', start);
    auto part = type_name.substr(start, dot == std::string::npos
                                            ? std::string::npos
                                            : dot - start);
    if (dot == std::string::npos) {
      typeNode->typeName = part;
      break;
    }
    typeNode->qualifiers.push_back(part);
    start = dot + 1;
  }
  return parseStructLiteral(std::move(typeNode));
}
References _builder, and parseStructLiteral().
Referenced by parseFailableExpression(), parsePostfixExpression(), parsePrimaryExpression(), and parseStructLiteral().
parseStructLiteral() [2/2]
std::unique_ptr< StructLiteralNode > zap::Parser::parseStructLiteral (std::unique_ptr< TypeNode > type) private
Definition at line 1897 of file parser.cpp.
{
  eat(TokenType::LBRACE);
  std::vector<StructFieldInit> fields;
  if (peek().type != TokenType::RBRACE) {
    do {
      Token fieldName = eat(TokenType::ID);
      eat(TokenType::COLON);
      auto value = parseExpression();
      fields.emplace_back(fieldName.value, std::move(value));
      if (peek().type == TokenType::COMMA ||
          peek().type == TokenType::SEMICOLON) {
        eat(peek().type);
      } else {
        break;
      }
    } while (peek().type != TokenType::RBRACE);
  }
  eat(TokenType::RBRACE);
  return std::make_unique<StructLiteralNode>(std::move(type), std::move(fields));
}
References COLON, COMMA, eat(), ID, LBRACE, parseExpression(), peek(), RBRACE, SEMICOLON, and Token::value.
parseTernaryExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseTernaryExpression () private
Definition at line 1190 of file parser.cpp.
{
  auto condition = parseBinaryExpression(0);
  if (peek().type != TokenType::QUESTION)
    return condition;
  eat(TokenType::QUESTION);
  auto thenExpr = parseTernaryExpression();
  eat(TokenType::COLON);
  auto elseExpr = parseTernaryExpression();
  SourceSpan conditionSpan = condition->span;
  SourceSpan elseSpan = elseExpr->span;
  auto ternary = _builder.makeTernaryExpr(
      std::move(condition), std::move(thenExpr), std::move(elseExpr));
  _builder.setSpan(ternary.get(), SourceSpan::merge(conditionSpan, elseSpan));
  return ternary;
}
References _builder, COLON, eat(), SourceSpan::merge(), parseBinaryExpression(), parseTernaryExpression(), peek(), and QUESTION.
Referenced by parseCastExpression(), and parseTernaryExpression().
parseType()
std::unique_ptr< TypeNode > zap::Parser::parseType () private
Definition at line 707 of file parser.cpp.
{
  if (peek().type == TokenType::WEAK) {
    Token weakToken = eat(TokenType::WEAK);
    auto innerType = parseType();
    if (innerType) {
      innerType->isWeak = true;
      _builder.setSpan(innerType.get(),
                       SourceSpan::merge(weakToken.span, innerType->span));
    }
    return innerType;
  }
  if (peek().type == TokenType::ELLIPSIS) {
    Token ellipsisToken = eat(TokenType::ELLIPSIS);
    auto baseType = parseType();
    auto variadicType = _builder.makeType("");
    variadicType->isVarArgs = true;
    variadicType->baseType = std::move(baseType);
    _builder.setSpan(
        variadicType.get(),
        SourceSpan::merge(ellipsisToken.span, variadicType->baseType->span));
    return variadicType;
  }
  if (peek().type == TokenType::MULTIPLY) {
    Token starToken = eat(TokenType::MULTIPLY);
    if (peek().type == TokenType::FUN) {
      eat(TokenType::FUN);
      eat(TokenType::LPAREN);
      auto funPtrType = _builder.makeType("");
      funPtrType->isFunPtr = true;
      if (peek().type != TokenType::RPAREN) {
        do {
          funPtrType->funPtrParams.push_back(parseType());
        } while (peek().type == TokenType::COMMA &&
                 eat(TokenType::COMMA).type == TokenType::COMMA);
      }
      Token rparenToken = eat(TokenType::RPAREN);
      if (peek().type != TokenType::SEMICOLON && peek().type != TokenType::COMMA &&
          peek().type != TokenType::RPAREN && peek().type != TokenType::ASSIGN &&
          peek().type != TokenType::RBRACE && peek().type != TokenType::SQUARE_RBRACE) {
        funPtrType->funPtrReturn = parseType();
      } else {
        funPtrType->funPtrReturn = _builder.makeType("Void");
      }
      _builder.setSpan(funPtrType.get(),
                       SourceSpan::merge(starToken.span, funPtrType->funPtrReturn->span));
      return funPtrType;
    }
    auto baseType = parseType();
    auto pointerType = _builder.makeType("");
    pointerType->isPointer = true;
    pointerType->baseType = std::move(baseType);
    _builder.setSpan(
        pointerType.get(),
        SourceSpan::merge(starToken.span, pointerType->baseType->span));
    return pointerType;
  }
  if (peek().type == TokenType::SQUARE_LBRACE &&
      (peek(1).type == TokenType::SQUARE_RBRACE ||
       peek(1).type == TokenType::INTEGER || peek(1).type == TokenType::ID ||
       peek(1).type == TokenType::SQUARE_LBRACE)) {
    Token lbracket = eat(TokenType::SQUARE_LBRACE);
    std::unique_ptr<ExpressionNode> size = nullptr;
    if (peek().type != TokenType::SQUARE_RBRACE) {
      size = parseExpression();
    }
    Token rbracket = eat(TokenType::SQUARE_RBRACE);
    auto baseType = parseType();
    auto arrayType = _builder.makeType("");
    arrayType->isArray = true;
    arrayType->arraySize = std::move(size);
    arrayType->baseType = std::move(baseType);
    _builder.setSpan(
        arrayType.get(),
        SourceSpan::merge(lbracket.span, arrayType->baseType->span));
    return arrayType;
  }
  Token startToken = peek();
  auto identifiers = parseQualifiedIdentifier();
  auto typeNode = _builder.makeType(identifiers.back());
  identifiers.pop_back();
  typeNode->qualifiers = std::move(identifiers);
  if (peek().type == TokenType::LESS && isTypeStartToken(peek(1).type)) {
    typeNode->genericArgs = parseGenericTypeArguments();
  }
  if (peek().type == TokenType::NOT) {
    eat(TokenType::NOT);
    auto errorType = parseType();
    auto failableType = _builder.makeType("");
    failableType->isFailable = true;
    failableType->baseType = std::move(typeNode);
    failableType->errorType = std::move(errorType);
    _builder.setSpan(
        failableType.get(),
        SourceSpan::merge(startToken.span, failableType->errorType->span));
    return failableType;
  }
  _builder.setSpan(typeNode.get(),
                   SourceSpan::merge(startToken.span, _tokens[_pos - 1].span));
  return typeNode;
}
References _builder, _pos, _tokens, ASSIGN, COMMA, eat(), ELLIPSIS, FUN, ID, INTEGER, isTypeStartToken(), LESS, LPAREN, SourceSpan::merge(), MULTIPLY, NOT, parseExpression(), parseGenericTypeArguments(), parseQualifiedIdentifier(), parseType(), peek(), RBRACE, RPAREN, SEMICOLON, Token::span, SQUARE_LBRACE, SQUARE_RBRACE, and WEAK.
Referenced by parse(), parseCastExpression(), parseClassDecl(), parseConstDecl(), parseExtDecl(), parseForInitVarDecl(), parseFunDecl(), parseGenericParameterList(), parseGenericTypeArguments(), parseIfType(), parseParameter(), parsePrimaryExpression(), parseType(), parseTypeAliasDecl(), parseVarDecl(), and parseWhereClauses().
parseTypeAliasDecl()
std::unique_ptr< TypeAliasDecl > zap::Parser::parseTypeAliasDecl () private
Definition at line 1750 of file parser.cpp.
{
  Token aliasToken = eat(TokenType::ALIAS);
  Token nameToken = eat(TokenType::ID);
  eat(TokenType::ASSIGN);
  auto type = parseType();
  Token semiToken = eat(TokenType::SEMICOLON);
  auto aliasDecl = _builder.makeTypeAliasDecl(nameToken.value, std::move(type));
  _builder.setSpan(aliasDecl.get(),
                   SourceSpan::merge(aliasToken.span, semiToken.span));
  return aliasDecl;
}
References _builder, ALIAS, ASSIGN, eat(), ID, SourceSpan::merge(), parseType(), SEMICOLON, Token::span, and Token::value.
Referenced by parse().
parseUnaryExpression()
std::unique_ptr< ExpressionNode > zap::Parser::parseUnaryExpression () private
Definition at line 1243 of file parser.cpp.
{
  if (peek().type == TokenType::NOT || peek().type == TokenType::MINUS ||
      peek().type == TokenType::PLUS || peek().type == TokenType::MULTIPLY ||
      peek().type == TokenType::REFERENCE || peek().type == TokenType::CONCAT) {
    Token opToken = eat(peek().type);
    auto expr = parseUnaryExpression();
    SourceSpan endSpan = expr->span;
    auto node = _builder.makeUnaryExpr(opToken.value, std::move(expr));
    _builder.setSpan(node.get(), SourceSpan::merge(opToken.span, endSpan));
    return node;
  }
  return parsePostfixExpression();
}
References _builder, CONCAT, eat(), SourceSpan::merge(), MINUS, MULTIPLY, NOT, parsePostfixExpression(), parseUnaryExpression(), peek(), PLUS, REFERENCE, Token::span, and Token::value.
Referenced by parseBinaryExpression(), and parseUnaryExpression().
parseUnsafeBlock()
std::unique_ptr< UnsafeBlockNode > zap::Parser::parseUnsafeBlock () private
Definition at line 1160 of file parser.cpp.
{
  Token unsafeKeyword = eat(TokenType::UNSAFE);
  eat(TokenType::LBRACE);
  auto body = parseBody();
  Token rbraceToken = eat(TokenType::RBRACE);
  auto unsafeBlock = _builder.makeUnsafeBlock();
  unsafeBlock->statements = std::move(body->statements);
  unsafeBlock->result = std::move(body->result);
  _builder.setSpan(unsafeBlock.get(),
                   SourceSpan::merge(unsafeKeyword.span, rbraceToken.span));
  return unsafeBlock;
}
References _builder, eat(), LBRACE, SourceSpan::merge(), parseBody(), RBRACE, Token::span, and UNSAFE.
Referenced by parseBody().
parseVarDecl()
std::unique_ptr< VarDecl > zap::Parser::parseVarDecl () private
Definition at line 447 of file parser.cpp.
{
  Token varKeyword = eat(TokenType::VAR);
  Token varNameToken = eat(TokenType::ID);
  eat(TokenType::COLON);
  auto typeNode = parseType();
  if (peek().type == TokenType::ASSIGN) {
    eat(TokenType::ASSIGN);
    auto expr = parseExpression();
    Token semicolonToken = eat(TokenType::SEMICOLON);
    auto varDecl = _builder.makeVarDecl(varNameToken.value, std::move(typeNode),
                                        std::move(expr));
    _builder.setSpan(varDecl.get(),
                     SourceSpan::merge(varKeyword.span, semicolonToken.span));
    return varDecl;
  } else {
    Token semicolonToken = eat(TokenType::SEMICOLON);
    auto varDecl =
        _builder.makeVarDecl(varNameToken.value, std::move(typeNode), nullptr);
    _builder.setSpan(varDecl.get(),
                     SourceSpan::merge(varKeyword.span, semicolonToken.span));
    return varDecl;
  }
}
References _builder, ASSIGN, COLON, eat(), ID, SourceSpan::merge(), parseExpression(), parseType(), peek(), SEMICOLON, Token::span, Token::value, and VAR.
Referenced by parse(), and parseBody().
parseWhereClauses()
std::vector< GenericConstraint > zap::Parser::parseWhereClauses () private
Definition at line 541 of file parser.cpp.
{
  std::vector<GenericConstraint> constraints;
  while (peek().type == TokenType::WHERE) {
    eat(TokenType::WHERE);
    Token paramToken = eat(TokenType::ID);
    eat(TokenType::COLON);
    auto boundType = parseType();
    constraints.push_back(
        {paramToken.value, std::move(boundType)});
  }
  return constraints;
}
References COLON, eat(), ID, parseType(), peek(), Token::value, and WHERE.
Referenced by parseClassDecl(), parseFunDecl(), parseRecordDecl(), and parseStructDecl().
parseWhile()
std::unique_ptr< WhileNode > zap::Parser::parseWhile () private
Definition at line 927 of file parser.cpp.
{
  Token whileKeyword = eat(TokenType::WHILE);
  bool hasParen = false;
  if (peek().type == TokenType::LPAREN) {
    eat(TokenType::LPAREN);
    hasParen = true;
  }
  bool oldAllow = _allowStructLiteral;
  if (!hasParen) {
    _allowStructLiteral = false;
  }
  auto condition = parseExpression();
  _allowStructLiteral = oldAllow;
  if (hasParen) {
    eat(TokenType::RPAREN);
  }
  eat(TokenType::LBRACE);
  auto body = parseBody();
  Token rbraceToken = eat(TokenType::RBRACE);
  auto whileNode = _builder.makeWhile(std::move(condition), std::move(body));
  _builder.setSpan(whileNode.get(),
                   SourceSpan::merge(whileKeyword.span, rbraceToken.span));
  return whileNode;
}
References _allowStructLiteral, _builder, eat(), LBRACE, LPAREN, SourceSpan::merge(), parseBody(), parseExpression(), peek(), RBRACE, RPAREN, Token::span, and WHILE.
Referenced by parseBody().
peek()
const Token & zap::Parser::peek (size_t offset = 0) const private
Definition at line 1539 of file parser.cpp.
{
  if (_pos + offset >= _tokens.size()) {
    static const Token dummy(TokenType::SEMICOLON, "", SourceSpan(0, 0, 0, 0));
    return dummy;
  }
  return _tokens[_pos + offset];
}
References _pos, _tokens, and SEMICOLON.
Referenced by eat(), isGenericCallStart(), isGenericStructLiteralStart(), parse(), parseArrayLiteral(), parseAttributes(), parseBinaryExpression(), parseBody(), parseCastExpression(), parseClassDecl(), parseEnumDecl(), parseExtDecl(), parseFailableExpression(), parseFor(), parseForIn(), parseForInitVarDecl(), parseFunDecl(), parseGenericParameterList(), parseGenericTypeArguments(), parseIf(), parseIfType(), parseImportDecl(), parseParameter(), parsePostfixExpression(), parsePrimaryExpression(), parseQualifiedIdentifier(), parseRecordDecl(), parseReturnStmt(), parseSingleAttribute(), parseStructDecl(), parseStructLiteral(), parseTernaryExpression(), parseType(), parseUnaryExpression(), parseVarDecl(), parseWhereClauses(), parseWhile(), and synchronize().
pointAfter()
SourceSpan zap::Parser::pointAfter (const SourceSpan & span) const private
Definition at line 1566 of file parser.cpp.
{
  size_t length = std::max<size_t>(span.length, 1);
  return SourceSpan(span.line, span.column + length, span.offset + span.length,
                    1);
}
References SourceSpan::column, SourceSpan::length, SourceSpan::line, and SourceSpan::offset.
Referenced by parseBody().
synchronize()
void zap::Parser::synchronize (SyncContext context = SyncContext::Block) private
Definition at line 1572 of file parser.cpp.
{
  size_t lastPos = _pos;
  size_t stalledIterations = 0;
  const size_t kMaxStalledIterations = 8;
  const size_t kMaxScanTokens = 4096;
  size_t scannedTokens = 0;
  while (!isAtEnd()) {
    if (_pos == lastPos) {
      ++stalledIterations;
    } else {
      stalledIterations = 0;
      lastPos = _pos;
    }
    if (stalledIterations > kMaxStalledIterations ||
        scannedTokens > kMaxScanTokens) {
      if (!isAtEnd()) {
        ++_pos; // force progress to avoid anti-recovery infinite cascade
      }
      return;
    }
    ++scannedTokens;
    switch (peek().type) {
    case TokenType::SEMICOLON:
      _pos++;
      return;
    case TokenType::RBRACE:
      return;
    case TokenType::FUN:
    case TokenType::IMPORT:
    case TokenType::ENUM:
    case TokenType::STRUCT:
    case TokenType::RECORD:
    case TokenType::CLASS:
    case TokenType::ALIAS:
    case TokenType::EXTERN:
    case TokenType::GLOBAL:
    case TokenType::CONST:
    case TokenType::PUB:
    case TokenType::PRIV:
    case TokenType::PROT:
    case TokenType::AT:
      if (context == SyncContext::TopLevel) {
        return;
      }
      _pos++;
      break;
    case TokenType::VAR:
    case TokenType::IF:
    case TokenType::WHILE:
    case TokenType::FOR:
    case TokenType::RETURN:
    case TokenType::UNSAFE:
      if (context == SyncContext::TopLevel) {
        _pos++;
        break;
      }
      return;
    default:
      _pos++;
      break;
    }
  }
}
References _pos, ALIAS, AT, CLASS, CONST, ENUM, EXTERN, FOR, FUN, GLOBAL, IF, IMPORT, isAtEnd(), peek(), PRIV, PROT, PUB, RBRACE, RECORD, RETURN, SEMICOLON, STRUCT, TopLevel, UNSAFE, VAR, and WHILE.
Referenced by parse(), and parseBody().
typeNodeFromQualifiedExpression()
std::unique_ptr< TypeNode > zap::Parser::typeNodeFromQualifiedExpression (const ExpressionNode * expr) private
Definition at line 684 of file parser.cpp.
{
  auto qualified = qualifiedNameFromExpression(expr);
  if (qualified.empty()) {
    return nullptr;
  }
  auto typeNode = _builder.makeType("");
  size_t start = 0;
  while (true) {
    size_t dot = qualified.find('.', start);
    auto part = qualified.substr(start, dot == std::string::npos
                                            ? std::string::npos
                                            : dot - start);
    if (dot == std::string::npos) {
      typeNode->typeName = part;
      break;
    }
    typeNode->qualifiers.push_back(part);
    start = dot + 1;
  }
  return typeNode;
}
References _builder.
Referenced by parsePostfixExpression().
Member Data Documentation
_allowStructLiteral
bool zap::Parser::_allowStructLiteral = true private
Definition at line 59 of file parser.hpp.
Referenced by parseFailableExpression(), parseFor(), parseForIn(), parseIf(), parsePostfixExpression(), parsePrimaryExpression(), and parseWhile().
_builder
AstBuilder zap::Parser::_builder private
Definition at line 58 of file parser.hpp.
Referenced by parse(), parseArrayLiteral(), parseAssign(), parseBinaryExpression(), parseBody(), parseBreak(), parseCastExpression(), parseClassDecl(), parseConstDecl(), parseContinue(), parseEnumDecl(), parseExtDecl(), parseFail(), parseFailableExpression(), parseFor(), parseForIn(), parseForIncrementAssign(), parseForInitVarDecl(), parseFunDecl(), parseGenericParameterList(), parseIf(), parseIfType(), parseImportDecl(), parseParameter(), parsePostfixExpression(), parsePrimaryExpression(), parseRecordDecl(), parseReturnStmt(), parseStructLiteral(), parseTernaryExpression(), parseType(), parseTypeAliasDecl(), parseUnaryExpression(), parseUnsafeBlock(), parseVarDecl(), parseWhile(), and typeNodeFromQualifiedExpression().
_diag
DiagnosticEngine& zap::Parser::_diag private
Definition at line 55 of file parser.hpp.
Referenced by eat(), parse(), parseBody(), parseEnumDecl(), parseFor(), parseForIn(), parsePrimaryExpression(), and Parser().
_pos
size_t zap::Parser::_pos private
Definition at line 57 of file parser.hpp.
Referenced by eat(), isAtEnd(), parse(), parseIf(), parseIfType(), Parser(), parseType(), peek(), and synchronize().
_tokens
std::vector<Token> zap::Parser::_tokens private
Definition at line 56 of file parser.hpp.
Referenced by eat(), isAtEnd(), parseIf(), parseIfType(), Parser(), parseType(), and peek().
The documentation for this class was generated from the following files:
src/parser/parser.hpp
src/parser/parser.cpp