ZAP: ConstFloat Class Reference
ConstFloat Class Reference
#include <const_float.hpp>
Public Member Functions
ConstFloat () noexcept=default
ConstFloat (double value) noexcept
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
double value_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 4 of file const_float.hpp.
Constructor & Destructor Documentation
ConstFloat() [1/2]
ConstFloat::ConstFloat () default noexcept
Referenced by ConstFloat().
ConstFloat() [2/2]
ConstFloat::ConstFloat (double value) inline noexcept
Definition at line 8 of file const_float.hpp.
: value_(value) {}
References ConstFloat(), and value_.
Member Function Documentation
accept()
void ConstFloat::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 10 of file const_float.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
value_
double ConstFloat::value_
Definition at line 6 of file const_float.hpp.
Referenced by ConstFloat(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/const/const_float.hpp