ZAP: sema::BoundExpression Class Reference
sema::BoundExpression Class Reference
#include <bound_nodes.hpp>
Public Member Functions
BoundExpression (std::shared_ptr< zir::Type > t)
Public Member Functions inherited from sema::BoundNode
virtual ~BoundNode ()=default
virtual void accept (BoundVisitor &v)=0
Public Attributes
std::shared_ptr< zir::Type > type
Detailed Description
Definition at line 74 of file bound_nodes.hpp.
Constructor & Destructor Documentation
BoundExpression()
sema::BoundExpression::BoundExpression (std::shared_ptr< zir::Type > t) inline explicit
Definition at line 78 of file bound_nodes.hpp.
: type(std::move(t)) {}
References type.
Referenced by sema::BoundArrayLiteral::BoundArrayLiteral(), sema::BoundBinaryExpression::BoundBinaryExpression(), sema::BoundCast::BoundCast(), sema::BoundFunctionCall::BoundFunctionCall(), sema::BoundIfExpression::BoundIfExpression(), sema::BoundIndexAccess::BoundIndexAccess(), sema::BoundLiteral::BoundLiteral(), sema::BoundMemberAccess::BoundMemberAccess(), sema::BoundStructLiteral::BoundStructLiteral(), sema::BoundUnaryExpression::BoundUnaryExpression(), and sema::BoundVariableExpression::BoundVariableExpression().
Member Data Documentation
type
std::shared_ptr<zir::Type> sema::BoundExpression::type
Definition at line 77 of file bound_nodes.hpp.
Referenced by BoundExpression(), sema::BoundVariableExpression::BoundVariableExpression(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), zir::BoundIRGenerator::visit(), and zir::BoundIRGenerator::visit().
The documentation for this class was generated from the following file:
src/sema/bound_nodes.hpp