ZAP: ExpressionNode Class Reference
ExpressionNode Class Reference
#include <expr_node.hpp>
Public Member Functions
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Additional Inherited Members
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 5 of file expr_node.hpp.
Constructor & Destructor Documentation
~ExpressionNode()
virtual ExpressionNode::~ExpressionNode () virtual default noexcept
ExpressionNode()
ExpressionNode::ExpressionNode () default noexcept
References ExpressionNode().
Referenced by ArrayLiteralNode::ArrayLiteralNode(), BinExpr::BinExpr(), ExpressionNode(), and UnaryExpr::UnaryExpr().
Member Function Documentation
accept()
void ExpressionNode::accept (Visitor & v) inline override virtual
Implements Node.
Reimplemented in FunCall, IndexAccessNode, MemberAccessNode, StructLiteralNode, TernaryExpr, and UnaryExpr.
Definition at line 10 of file expr_node.hpp.
{ v.visit(*this); }
References accept().
Referenced by accept().
The documentation for this class was generated from the following file:
src/ast/expr_node.hpp