ZAP: codegen::anonymous_namespace{llvm_codegen_zir.cpp} Namespace Reference
codegen::anonymous_namespace{llvm_codegen_zir.cpp} Namespace Reference
Functions
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isStringLLVMStructType (llvm::Type *ty)
Function Documentation
isStringLLVMStructType()
bool codegen::anonymous_namespace{llvm_codegen_zir.cpp}::isStringLLVMStructType (llvm::Type * ty)
Definition at line 18 of file llvm_codegen_zir.cpp.
{
  auto *st = llvm::dyn_cast_or_null<llvm::StructType>(ty);
  if (!st || !st->hasName()) {
    return false;
  }
  return zap::text::isStringRecordName(st->getName().str());
}
References isStringLLVMStructType(), and zap::text::isStringRecordName().
Referenced by isStringLLVMStructType().
isStringType()
bool codegen::anonymous_namespace{llvm_codegen_zir.cpp}::isStringType (const std::shared_ptr< zir::Type > & type)
Definition at line 14 of file llvm_codegen_zir.cpp.
{
  return zap::text::isStringType(type);
}
References isStringType(), and zap::text::isStringType().
Referenced by isStringType().