ZAP: anonymous_namespace{lsp-main.cpp} Namespace Reference
anonymous_namespace{lsp-main.cpp} Namespace Reference
Classes
struct DocumentState
struct LspFlags
struct AnalysisResult
struct ProjectState
struct LspSymbol
struct LspSignature
struct CallContext
struct HoverInfo
class Workspace
Typedefs
using JsonObject = zap::lsp::JsonObject
Functions
const JsonObject * getField (const JsonObject &object, std::string_view key)
const JsonObject * getPath (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< std::string > getStringField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< int64_t > getIntegerField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::string stripSourceExtension (const std::filesystem::path &path)
std::filesystem::path stdlibRootPath ()
std::string computeLogicalModulePath (const std::filesystem::path &canonicalPath)
std::optional< std::filesystem::path > uriToPath (std::string_view uri)
bool readSourceFile (const std::filesystem::path &path, std::string &content)
LspFlags readFlagsFromFile (const std::filesystem::path &path)
LspFlags findAndReadFlags (std::filesystem::path startPath)
bool resolveImportTargets (const std::filesystem::path &modulePath, const ImportNode &importNode, std::vector< std::filesystem::path > &targets)
std::string effectiveImportAlias (const sema::ResolvedImport &import, const sema::ModuleInfo &target)
size_t offsetFromPosition (const std::string &text, int64_t line, int64_t character)
bool containsOffset (const SourceSpan &span, size_t offset)
bool isIdentifierChar (char ch)
std::string pathToUri (const std::filesystem::path &path)
std::optional< std::string > identifierAt (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > memberAccessBeforeCursor (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > qualifiedIdentifierAtOffset (const std::string &source, size_t offset)
std::optional< LspSymbol > makeSymbol (const std::string &uri, const std::string &name, const SourceSpan &span, int64_t kind, Visibility visibility=Visibility::Private)
std::string renderType (const TypeNode *type)
std::string renderParameter (const ParameterNode *param)
std::optional< LspSignature > signatureForNode (const Node *node)
std::vector< LspSignature > findTopLevelSignatures (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
std::optional< std::string > topLevelNameForNode (const Node *node)
const ClassDecl * findClassDecl (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
const sema::ModuleInfo * findImportedModuleByAlias (const ProjectState &project, const sema::ModuleInfo &module, std::string_view alias)
std::pair< std::string, std::string > splitQualifiedName (std::string_view qualifiedName)
const ClassDecl * resolveClassByTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName, bool publicOnly=false)
bool isClassTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName)
std::optional< std::string > resolveClassTypeNameFromTypeNode (const ProjectState &project, const sema::ModuleInfo &module, const TypeNode *type)
const ClassDecl * enclosingClassAtOffset (const RootNode &root, size_t offset)
std::optional< std::string > lookupTypeInBody (const ProjectState &project, const sema::ModuleInfo &module, const BodyNode *body, size_t offset, std::string_view name)
std::optional< std::string > lookupTypeInNode (const ProjectState &project, const sema::ModuleInfo &module, const Node *node, size_t offset, std::string_view name)
std::optional< std::string > resolveVariableClassType (const ProjectState &project, const sema::ModuleInfo &module, size_t offset, std::string_view name)
const ParameterNode * findClassField (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
const FunDecl * findClassMethod (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::optional< HoverInfo > hoverForClassMember (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::optional< CallContext > callContextAtOffset (const std::string &source, size_t offset)
std::optional< CallContext > callContextNearOffset (const std::string &source, size_t offset)
std::vector< LspSignature > resolveSignatures (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset, int64_t &activeParameter)
std::optional< HoverInfo > hoverForNode (const Node *node)
std::optional< HoverInfo > findTopLevelHover (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
JsonObject makeHover (const HoverInfo &hover)
std::optional< HoverInfo > resolveHover (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset)
JsonObject makeSignatureHelp (const std::vector< LspSignature > &signatures, int64_t activeSignature, int64_t activeParameter)
JsonObject makeRange (const zap::DiagnosticRange &range)
std::optional< LspSymbol > topLevelSymbolForNode (const Node *node, const std::string &uri)
std::vector< LspSymbol > collectTopLevelSymbols (const sema::ModuleInfo &module, const std::string &uri, bool publicOnly=false)
void collectLocalsInBody (const BodyNode *body, size_t offset, const std::string &uri, std::vector< LspSymbol > &symbols)
void collectLocalsFromNode (const Node *node, size_t offset, const std::string &uri, std::vector< LspSymbol > &symbols)
std::vector< LspSymbol > collectLocalSymbols (const RootNode &root, size_t offset, const std::string &uri)
JsonObject makeLocation (const std::string &uri, const SourceSpan &span)
JsonObject makeCompletionItem (const LspSymbol &symbol, const std::string &detail="")
JsonObject makeResponse (const JsonObject *id, JsonObject result)
JsonObject makeNotification (std::string method, JsonObject params)
std::vector< LspSymbol > collectImportedSymbols (const ProjectState &project, const sema::ModuleInfo &module)
std::vector< LspSymbol > collectCompletionSymbols (const std::string &uri, const ProjectState &project, size_t offset)
std::optional< LspSymbol > resolveDefinition (const Workspace &workspace, const std::string &uri, const ProjectState &project, size_t offset)
int64_t toLspSeverity (zap::DiagnosticLevel level)
JsonObject makeDiagnostic (const zap::Diagnostic &diagnostic)
JsonObject makePublishDiagnostics (std::string uri, const std::vector< zap::Diagnostic > &diagnostics)
void publishAnalysis (Server &server, const AnalysisResult &result)
Typedef Documentation
JsonObject
using anonymous_namespace{lsp-main.cpp}::JsonObject = zap::lsp::JsonObject
Definition at line 23 of file lsp-main.cpp.
Function Documentation
callContextAtOffset()
std::optional< CallContext > anonymous_namespace{lsp-main.cpp}::callContextAtOffset (const std::string & source, size_t offset)
Definition at line 936 of file lsp-main.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = std::min(offset, source.size());
  int nestedParens = 0;
  int nestedBrackets = 0;
  int nestedBraces = 0;
  int64_t activeParameter = 0;
  bool foundOpenParen = false;
  size_t openParen = 0;
  while (pos > 0) {
    --pos;
    char ch = source[pos];
    if (ch == ')') {
      ++nestedParens;
    } else if (ch == '(') {
      if (nestedParens == 0 && nestedBrackets == 0 && nestedBraces == 0) {
        openParen = pos;
        foundOpenParen = true;
        break;
      }
      if (nestedParens > 0) {
        --nestedParens;
      }
    } else if (ch == ']') {
      ++nestedBrackets;
    } else if (ch == '[') {
      if (nestedBrackets > 0) {
        --nestedBrackets;
      }
    } else if (ch == '}') {
      ++nestedBraces;
    } else if (ch == '{') {
      if (nestedBraces > 0) {
        --nestedBraces;
      }
    } else if (ch == ',' && nestedParens == 0 && nestedBrackets == 0 &&
               nestedBraces == 0) {
      ++activeParameter;
    }
  }
  if (!foundOpenParen) {
    return std::nullopt;
  }
  size_t end = openParen;
  while (end > 0 && std::isspace(static_cast<unsigned char>(source[end - 1]))) {
    --end;
  }
  size_t start = end;
  while (start > 0) {
    char ch = source[start - 1];
    if (isIdentifierChar(ch) || ch == '.' ||
        std::isspace(static_cast<unsigned char>(ch))) {
      --start;
      continue;
    }
    break;
  }
  std::string callee = source.substr(start, end - start);
  callee.erase(
      std::remove_if(callee.begin(), callee.end(),
                     [](unsigned char ch) { return std::isspace(ch); }),
      callee.end());
  if (callee.empty()) {
    return std::nullopt;
  }
  return CallContext{std::move(callee), activeParameter};
}
References isIdentifierChar().
Referenced by callContextNearOffset().
callContextNearOffset()
std::optional< CallContext > anonymous_namespace{lsp-main.cpp}::callContextNearOffset (const std::string & source, size_t offset)
Definition at line 1013 of file lsp-main.cpp.
{
  if (auto call = callContextAtOffset(source, offset)) {
    return call;
  }
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = std::min(offset, source.size() - 1);
  if (isIdentifierChar(source[pos])) {
    size_t end = pos + 1;
    while (end < source.size() && isIdentifierChar(source[end])) {
      ++end;
    }
    while (end < source.size() &&
           std::isspace(static_cast<unsigned char>(source[end]))) {
      ++end;
    }
    if (end < source.size() && source[end] == '(') {
      return callContextAtOffset(source, end + 1);
    }
  }
  if (pos < source.size() && source[pos] == '(') {
    return callContextAtOffset(source, pos + 1);
  }
  return std::nullopt;
}
References callContextAtOffset(), and isIdentifierChar().
Referenced by resolveSignatures().
collectCompletionSymbols()
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectCompletionSymbols (const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 1795 of file lsp-main.cpp.
{
  std::vector<LspSymbol> symbols;
  auto path = uriToPath(uri);
  if (!path) {
    return symbols;
  }
  auto docIt =
      project.moduleMap.find(std::filesystem::weakly_canonical(*path).string());
  if (docIt == project.moduleMap.end()) {
    return symbols;
  }
  const sema::ModuleInfo &module = *docIt->second;
  auto topLevel = collectTopLevelSymbols(module, uri);
  symbols.insert(symbols.end(), topLevel.begin(), topLevel.end());
  auto imported = collectImportedSymbols(project, module);
  symbols.insert(symbols.end(), imported.begin(), imported.end());
  auto locals = collectLocalSymbols(*module.root, offset, uri);
  symbols.insert(symbols.end(), locals.begin(), locals.end());
  static constexpr std::pair<const char *, int64_t> builtinTypes[] = {
      {"Int", 22},     {"Int8", 22},   {"Int16", 22}, {"Int32", 22},
      {"Int64", 22},   {"UInt", 22},   {"UInt8", 22}, {"UInt16", 22},
      {"UInt32", 22},  {"UInt64", 22}, {"Float", 22}, {"Float32", 22},
      {"Float64", 22}, {"Bool", 22},   {"Void", 22},  {"Char", 22},
      {"String", 22}};
  for (const auto &[name, kind] : builtinTypes) {
    symbols.push_back(
        *makeSymbol(uri, name, SourceSpan(), kind, Visibility::Public));
  }
  return symbols;
}
References collectImportedSymbols(), collectLocalSymbols(), collectTopLevelSymbols(), makeSymbol(), anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap, Public, sema::ModuleInfo::root, and uriToPath().
Referenced by main().
collectImportedSymbols()
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectImportedSymbols (const ProjectState & project, const sema::ModuleInfo & module)
Definition at line 1755 of file lsp-main.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &import : module.imports) {
    for (const auto &targetId : import.targetModuleIds) {
      auto moduleIt = project.moduleMap.find(targetId);
      if (moduleIt == project.moduleMap.end()) {
        continue;
      }
      const auto &target = *moduleIt->second;
      auto alias = effectiveImportAlias(import, target);
      auto targetUriIt = project.uriByModuleId.find(targetId);
      std::string targetUri = targetUriIt == project.uriByModuleId.end()
                                  ? pathToUri(targetId)
                                  : targetUriIt->second;
      symbols.push_back(*makeSymbol(project.uriByModuleId.at(module.moduleId),
                                    alias, import.span, 9, Visibility::Public));
      auto exported = collectTopLevelSymbols(target, targetUri, true);
      if (import.bindings.empty()) {
        continue;
      }
      for (const auto &binding : import.bindings) {
        auto exportIt = std::find_if(exported.begin(), exported.end(),
                                     [&](const LspSymbol &symbol) {
                                       return symbol.name == binding.sourceName;
                                     });
        if (exportIt == exported.end()) {
          continue;
        }
        LspSymbol local = *exportIt;
        local.name = binding.localName;
        symbols.push_back(std::move(local));
      }
    }
  }
  return symbols;
}
References collectTopLevelSymbols(), effectiveImportAlias(), sema::ModuleInfo::imports, makeSymbol(), sema::ModuleInfo::moduleId, anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap, anonymous_namespace{lsp-main.cpp}::LspSymbol::name, pathToUri(), Public, and anonymous_namespace{lsp-main.cpp}::ProjectState::uriByModuleId.
Referenced by collectCompletionSymbols(), and resolveDefinition().
collectLocalsFromNode()
void anonymous_namespace{lsp-main.cpp}::collectLocalsFromNode (const Node * node, size_t offset, const std::string & uri, std::vector< LspSymbol > & symbols)
Definition at line 1379 of file lsp-main.cpp.
{
  if (!node) {
    return;
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    if (!containsOffset(var->span, offset) && var->span.offset > offset) {
      return;
    }
    if (var->span.offset <= offset) {
      symbols.push_back(*makeSymbol(uri, var->name_, var->span, 6));
    }
    return;
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    if (!containsOffset(cnst->span, offset) && cnst->span.offset > offset) {
      return;
    }
    if (cnst->span.offset <= offset) {
      symbols.push_back(*makeSymbol(uri, cnst->name_, cnst->span, 21));
    }
    return;
  }
  if (auto body = dynamic_cast<const BodyNode *>(node)) {
    collectLocalsInBody(body, offset, uri, symbols);
    return;
  }
  if (auto ifNode = dynamic_cast<const IfNode *>(node)) {
    if (!containsOffset(ifNode->span, offset)) {
      return;
    }
    if (ifNode->thenBody_ &&
        (!ifNode->thenBody_->statements.empty() || ifNode->thenBody_->result) &&
        (ifNode->thenBody_->statements.empty() ||
         offset >= ifNode->thenBody_->statements.front()->span.offset)) {
      collectLocalsInBody(ifNode->thenBody_.get(), offset, uri, symbols);
    } else if (ifNode->elseBody_) {
      collectLocalsInBody(ifNode->elseBody_.get(), offset, uri, symbols);
    }
    return;
  }
  if (auto whileNode = dynamic_cast<const WhileNode *>(node)) {
    if (containsOffset(whileNode->span, offset) && whileNode->body_) {
      collectLocalsInBody(whileNode->body_.get(), offset, uri, symbols);
    }
    return;
  }
}
References collectLocalsInBody(), containsOffset(), and makeSymbol().
Referenced by collectLocalsInBody().
collectLocalsInBody()
void anonymous_namespace{lsp-main.cpp}::collectLocalsInBody (const BodyNode * body, size_t offset, const std::string & uri, std::vector< LspSymbol > & symbols)
Definition at line 1430 of file lsp-main.cpp.
{
  for (const auto &statement : body->statements) {
    if (!statement || statement->span.offset > offset) {
      break;
    }
    if (auto var = dynamic_cast<const VarDecl *>(statement.get())) {
      symbols.push_back(*makeSymbol(uri, var->name_, var->span, 6));
    } else if (auto cnst = dynamic_cast<const ConstDecl *>(statement.get())) {
      symbols.push_back(*makeSymbol(uri, cnst->name_, cnst->span, 21));
    }
    collectLocalsFromNode(statement.get(), offset, uri, symbols);
  }
}
References collectLocalsFromNode(), makeSymbol(), and BodyNode::statements.
Referenced by collectLocalsFromNode(), and collectLocalSymbols().
collectLocalSymbols()
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectLocalSymbols (const RootNode & root, size_t offset, const std::string & uri)
Definition at line 1446 of file lsp-main.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &child : root.children) {
    auto fun = dynamic_cast<const FunDecl *>(child.get());
    if (!fun || !fun->body_ || !containsOffset(fun->span, offset)) {
      continue;
    }
    for (const auto &param : fun->params_) {
      if (param) {
        symbols.push_back(*makeSymbol(uri, param->name, param->span, 6));
      }
    }
    collectLocalsInBody(fun->body_.get(), offset, uri, symbols);
    break;
  }
  return symbols;
}
References RootNode::children, collectLocalsInBody(), containsOffset(), and makeSymbol().
Referenced by collectCompletionSymbols(), and resolveDefinition().
collectTopLevelSymbols()
std::vector< LspSymbol > anonymous_namespace{lsp-main.cpp}::collectTopLevelSymbols (const sema::ModuleInfo & module, const std::string & uri, bool publicOnly = false)
Definition at line 1358 of file lsp-main.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &child : module.root->children) {
    auto symbol = topLevelSymbolForNode(child.get(), uri);
    if (!symbol) {
      continue;
    }
    if (publicOnly && symbol->visibility != Visibility::Public) {
      continue;
    }
    symbols.push_back(*symbol);
  }
  return symbols;
}
References Public, sema::ModuleInfo::root, and topLevelSymbolForNode().
Referenced by collectCompletionSymbols(), collectImportedSymbols(), main(), and resolveDefinition().
computeLogicalModulePath()
std::string anonymous_namespace{lsp-main.cpp}::computeLogicalModulePath (const std::filesystem::path & canonicalPath)
Definition at line 102 of file lsp-main.cpp.
{
  auto stdRoot = std::filesystem::weakly_canonical(stdlibRootPath());
  auto cwdRoot =
      std::filesystem::weakly_canonical(std::filesystem::current_path());
  auto buildRelative = [&](const std::filesystem::path &root,
                           const std::string &prefix =
                               "") -> std::optional<std::string> {
    auto rootText = root.generic_string();
    auto pathText = canonicalPath.generic_string();
    if (pathText == rootText || pathText.rfind(rootText + "/", 0) != 0) {
      return std::nullopt;
    }
    auto rel = std::filesystem::relative(canonicalPath, root);
    auto stripped = stripSourceExtension(rel);
    if (prefix.empty()) {
      return stripped;
    }
    return prefix + "/" + stripped;
  };
  if (auto logical = buildRelative(stdRoot, "std")) {
    return *logical;
  }
  if (auto logical = buildRelative(cwdRoot)) {
    return *logical;
  }
  return stripSourceExtension(canonicalPath.filename());
}
References zap::lsp::prefix, stdlibRootPath(), and stripSourceExtension().
containsOffset()
bool anonymous_namespace{lsp-main.cpp}::containsOffset (const SourceSpan & span, size_t offset)
Definition at line 317 of file lsp-main.cpp.
{
  return offset >= span.offset && offset <= span.offset + span.length;
}
References SourceSpan::length, and SourceSpan::offset.
Referenced by collectLocalsFromNode(), collectLocalSymbols(), enclosingClassAtOffset(), lookupTypeInNode(), and resolveVariableClassType().
effectiveImportAlias()
std::string anonymous_namespace{lsp-main.cpp}::effectiveImportAlias (const sema::ResolvedImport & import, const sema::ModuleInfo & target)
Definition at line 1317 of file lsp-main.cpp.
{
  return import.moduleAlias.empty() ? target.moduleName : import.moduleAlias;
}
References sema::ModuleInfo::moduleName.
Referenced by collectImportedSymbols(), findImportedModuleByAlias(), main(), resolveDefinition(), resolveHover(), and resolveSignatures().
enclosingClassAtOffset()
const ClassDecl * anonymous_namespace{lsp-main.cpp}::enclosingClassAtOffset (const RootNode & root, size_t offset)
Definition at line 712 of file lsp-main.cpp.
{
  for (const auto &child : root.children) {
    auto cls = dynamic_cast<const ClassDecl *>(child.get());
    if (!cls || !containsOffset(cls->span, offset)) {
      continue;
    }
    return cls;
  }
  return nullptr;
}
References RootNode::children, and containsOffset().
Referenced by resolveVariableClassType().
findAndReadFlags()
LspFlags anonymous_namespace{lsp-main.cpp}::findAndReadFlags (std::filesystem::path startPath)
Definition at line 210 of file lsp-main.cpp.
{
  if (std::filesystem::is_regular_file(startPath)) {
    startPath = startPath.parent_path();
  }
  while (true) {
    auto flagsPath = startPath / "zap_flags.txt";
    if (std::filesystem::exists(flagsPath)) {
      return readFlagsFromFile(flagsPath);
    }
    if (startPath == startPath.parent_path()) {
      break;
    }
    startPath = startPath.parent_path();
  }
  return {};
}
References readFlagsFromFile().
Referenced by anonymous_namespace{lsp-main.cpp}::Workspace::analyze().
findClassDecl()
const ClassDecl * anonymous_namespace{lsp-main.cpp}::findClassDecl (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 629 of file lsp-main.cpp.
{
  for (const auto &child : module.root->children) {
    auto cls = dynamic_cast<const ClassDecl *>(child.get());
    auto topLevel = dynamic_cast<const TopLevel *>(child.get());
    if (!cls || cls->name_ != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    return cls;
  }
  return nullptr;
}
References Public, and sema::ModuleInfo::root.
Referenced by resolveClassByTypeName().
findClassField()
const ParameterNode * anonymous_namespace{lsp-main.cpp}::findClassField (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 868 of file lsp-main.cpp.
{
  if (!cls) {
    return nullptr;
  }
  for (const auto &field : cls->fields_) {
    if (!field || field->name != member) {
      continue;
    }
    if (publicOnly && field->visibility_ != Visibility::Public) {
      continue;
    }
    return field.get();
  }
  if (cls->baseType_) {
    if (auto base = resolveClassByTypeName(
            project, module, cls->baseType_->qualifiedName(), publicOnly)) {
      return findClassField(base, project, module, member, publicOnly);
    }
  }
  return nullptr;
}
References ClassDecl::baseType_, ClassDecl::fields_, findClassField(), Public, and resolveClassByTypeName().
Referenced by findClassField(), hoverForClassMember(), and resolveDefinition().
findClassMethod()
const FunDecl * anonymous_namespace{lsp-main.cpp}::findClassMethod (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 894 of file lsp-main.cpp.
{
  if (!cls) {
    return nullptr;
  }
  for (const auto &method : cls->methods_) {
    if (!method || method->name_ != member) {
      continue;
    }
    if (publicOnly && method->visibility_ != Visibility::Public) {
      continue;
    }
    return method.get();
  }
  if (cls->baseType_) {
    if (auto base = resolveClassByTypeName(
            project, module, cls->baseType_->qualifiedName(), publicOnly)) {
      return findClassMethod(base, project, module, member, publicOnly);
    }
  }
  return nullptr;
}
References ClassDecl::baseType_, findClassMethod(), ClassDecl::methods_, Public, and resolveClassByTypeName().
Referenced by findClassMethod(), hoverForClassMember(), and resolveDefinition().
findImportedModuleByAlias()
const sema::ModuleInfo * anonymous_namespace{lsp-main.cpp}::findImportedModuleByAlias (const ProjectState & project, const sema::ModuleInfo & module, std::string_view alias)
Definition at line 647 of file lsp-main.cpp.
{
  for (const auto &import : module.imports) {
    for (const auto &targetId : import.targetModuleIds) {
      auto targetIt = project.moduleMap.find(targetId);
      if (targetIt == project.moduleMap.end()) {
        continue;
      }
      if (effectiveImportAlias(import, *targetIt->second) == alias) {
        return targetIt->second.get();
      }
    }
  }
  return nullptr;
}
References effectiveImportAlias(), sema::ModuleInfo::imports, and anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap.
Referenced by resolveClassByTypeName().
findTopLevelHover()
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::findTopLevelHover (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 1160 of file lsp-main.cpp.
{
  for (const auto &child : module.root->children) {
    const TopLevel *topLevel = dynamic_cast<const TopLevel *>(child.get());
    auto childName = topLevelNameForNode(child.get());
    if (!childName || *childName != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    if (auto hover = hoverForNode(child.get())) {
      return hover;
    }
  }
  return std::nullopt;
}
References hoverForNode(), Public, sema::ModuleInfo::root, topLevelNameForNode(), and TopLevel::visibility_.
Referenced by resolveHover().
findTopLevelSignatures()
std::vector< LspSignature > anonymous_namespace{lsp-main.cpp}::findTopLevelSignatures (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 562 of file lsp-main.cpp.
{
  std::vector<LspSignature> signatures;
  for (const auto &child : module.root->children) {
    const TopLevel *topLevel = dynamic_cast<const TopLevel *>(child.get());
    std::optional<std::string> childName;
    if (auto fun = dynamic_cast<const FunDecl *>(child.get())) {
      childName = fun->name_;
    } else if (auto ext = dynamic_cast<const ExtDecl *>(child.get())) {
      childName = ext->name_;
    }
    if (!childName || *childName != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    if (auto signature = signatureForNode(child.get())) {
      signatures.push_back(*signature);
    }
  }
  return signatures;
}
References Public, sema::ModuleInfo::root, signatureForNode(), and TopLevel::visibility_.
Referenced by resolveSignatures().
getField()
const JsonObject * anonymous_namespace{lsp-main.cpp}::getField (const JsonObject & object, std::string_view key)
Definition at line 32 of file lsp-main.cpp.
{
  if (!object.isObject()) {
    return nullptr;
  }
  auto it = object.getAsObject().find(std::string(key));
  return it == object.getAsObject().end() ? nullptr : &it->second;
}
References zap::lsp::JsonObject::getAsObject().
Referenced by getPath(), and main().
getIntegerField()
std::optional< int64_t > anonymous_namespace{lsp-main.cpp}::getIntegerField (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 63 of file lsp-main.cpp.
{
  const JsonObject *value = getPath(object, path);
  if (!value || !value->isInteger()) {
    return std::nullopt;
  }
  return value->getAsInteger();
}
References zap::lsp::JsonObject::getAsInteger(), getPath(), and zap::lsp::JsonObject::isInteger().
Referenced by main().
getPath()
const JsonObject * anonymous_namespace{lsp-main.cpp}::getPath (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 40 of file lsp-main.cpp.
{
  const JsonObject *current = &object;
  for (std::string_view key : path) {
    current = getField(*current, key);
    if (!current) {
      return nullptr;
    }
  }
  return current;
}
References getField().
Referenced by getIntegerField(), getStringField(), and main().
getStringField()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::getStringField (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 53 of file lsp-main.cpp.
{
  const JsonObject *value = getPath(object, path);
  if (!value || !value->isString()) {
    return std::nullopt;
  }
  return value->getAsString();
}
References zap::lsp::JsonObject::getAsString(), getPath(), and zap::lsp::JsonObject::isString().
Referenced by main().
hoverForClassMember()
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::hoverForClassMember (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 920 of file lsp-main.cpp.
{
  if (auto method = findClassMethod(cls, project, module, member, publicOnly)) {
    if (auto signature = signatureForNode(method)) {
      return HoverInfo{"zap", signature->label};
    }
  }
  if (auto field = findClassField(cls, project, module, member, publicOnly)) {
    return HoverInfo{"zap", field->name + ": " + renderType(field->type.get())};
  }
  return std::nullopt;
}
References findClassField(), findClassMethod(), renderType(), and signatureForNode().
Referenced by resolveHover().
hoverForNode()
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::hoverForNode (const Node * node)
Definition at line 1118 of file lsp-main.cpp.
{
  if (dynamic_cast<const FunDecl *>(node)) {
    if (auto signature = signatureForNode(node)) {
      return HoverInfo{"zap", signature->label};
    }
  }
  if (dynamic_cast<const ExtDecl *>(node)) {
    if (auto signature = signatureForNode(node)) {
      return HoverInfo{"zap", "ext fun " + signature->label};
    }
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return HoverInfo{"zap",
                     "var " + var->name_ + ": " + renderType(var->type_.get())};
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return HoverInfo{"zap", "const " + cnst->name_ + ": " +
                                renderType(cnst->type_.get())};
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    return HoverInfo{"zap", "record " + record->name_};
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    return HoverInfo{"zap", "struct " + strukt->name_};
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    std::string hover = "class " + cls->name_;
    if (cls->baseType_) {
      hover += " : " + renderType(cls->baseType_.get());
    }
    return HoverInfo{"zap", hover};
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return HoverInfo{"zap", "enum " + enm->name_};
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return HoverInfo{"zap", "alias " + alias->name_ + " = " +
                                renderType(alias->type_.get())};
  }
  return std::nullopt;
}
References renderType(), and signatureForNode().
Referenced by findTopLevelHover().
identifierAt()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::identifierAt (const std::string & source, size_t offset)
Definition at line 344 of file lsp-main.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = offset < source.size() ? offset : source.size() - 1;
  if (!isIdentifierChar(source[pos])) {
    if (pos == 0 || !isIdentifierChar(source[pos - 1])) {
      return std::nullopt;
    }
    --pos;
  }
  size_t start = pos;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  size_t end = pos + 1;
  while (end < source.size() && isIdentifierChar(source[end])) {
    ++end;
  }
  return source.substr(start, end - start);
}
References isIdentifierChar().
Referenced by resolveDefinition(), and resolveHover().
isClassTypeName()
bool anonymous_namespace{lsp-main.cpp}::isClassTypeName (const ProjectState & project, const sema::ModuleInfo & module, std::string_view typeName)
Definition at line 692 of file lsp-main.cpp.
{
  return resolveClassByTypeName(project, module, typeName) != nullptr;
}
References resolveClassByTypeName().
Referenced by resolveClassTypeNameFromTypeNode().
isIdentifierChar()
bool anonymous_namespace{lsp-main.cpp}::isIdentifierChar (char ch)
Definition at line 321 of file lsp-main.cpp.
{
  return std::isalnum(static_cast<unsigned char>(ch)) || ch == '_';
}
Referenced by callContextAtOffset(), callContextNearOffset(), identifierAt(), memberAccessBeforeCursor(), and qualifiedIdentifierAtOffset().
lookupTypeInBody()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::lookupTypeInBody (const ProjectState & project, const sema::ModuleInfo & module, const BodyNode * body, size_t offset, std::string_view name)
Definition at line 779 of file lsp-main.cpp.
{
  if (!body) {
    return std::nullopt;
  }
  for (const auto &statement : body->statements) {
    if (!statement || statement->span.offset > offset) {
      break;
    }
    if (auto found =
            lookupTypeInNode(project, module, statement.get(), offset, name)) {
      return found;
    }
  }
  if (body->result && body->result->span.offset <= offset) {
    if (auto found = lookupTypeInNode(project, module, body->result.get(),
                                      offset, name)) {
      return found;
    }
  }
  return std::nullopt;
}
References lookupTypeInNode(), BodyNode::result, and BodyNode::statements.
Referenced by lookupTypeInNode(), and resolveVariableClassType().
lookupTypeInNode()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::lookupTypeInNode (const ProjectState & project, const sema::ModuleInfo & module, const Node * node, size_t offset, std::string_view name)
Definition at line 728 of file lsp-main.cpp.
{
  if (!node) {
    return std::nullopt;
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    if (var->name_ == name && var->span.offset <= offset) {
      return resolveClassTypeNameFromTypeNode(project, module,
                                              var->type_.get());
    }
    return std::nullopt;
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    if (cnst->name_ == name && cnst->span.offset <= offset) {
      return resolveClassTypeNameFromTypeNode(project, module,
                                              cnst->type_.get());
    }
    return std::nullopt;
  }
  if (auto body = dynamic_cast<const BodyNode *>(node)) {
    return lookupTypeInBody(project, module, body, offset, name);
  }
  if (auto ifNode = dynamic_cast<const IfNode *>(node)) {
    if (!containsOffset(ifNode->span, offset)) {
      return std::nullopt;
    }
    if (ifNode->thenBody_) {
      if (auto found = lookupTypeInBody(
              project, module, ifNode->thenBody_.get(), offset, name)) {
        return found;
      }
    }
    if (ifNode->elseBody_) {
      if (auto found = lookupTypeInBody(
              project, module, ifNode->elseBody_.get(), offset, name)) {
        return found;
      }
    }
    return std::nullopt;
  }
  if (auto whileNode = dynamic_cast<const WhileNode *>(node)) {
    if (containsOffset(whileNode->span, offset) && whileNode->body_) {
      return lookupTypeInBody(project, module, whileNode->body_.get(), offset,
                              name);
    }
  }
  return std::nullopt;
}
References containsOffset(), lookupTypeInBody(), and resolveClassTypeNameFromTypeNode().
Referenced by lookupTypeInBody().
makeCompletionItem()
JsonObject anonymous_namespace{lsp-main.cpp}::makeCompletionItem (const LspSymbol & symbol, const std::string & detail = "")
Definition at line 1476 of file lsp-main.cpp.
{
  JsonObject::Object item;
  item.emplace("label", JsonObject(symbol.name));
  item.emplace("kind", JsonObject(symbol.completionKind));
  if (!detail.empty()) {
    item.emplace("detail", JsonObject(detail));
  }
  return JsonObject(std::move(item));
}
References anonymous_namespace{lsp-main.cpp}::LspSymbol::completionKind, and anonymous_namespace{lsp-main.cpp}::LspSymbol::name.
Referenced by main().
makeDiagnostic()
JsonObject anonymous_namespace{lsp-main.cpp}::makeDiagnostic (const zap::Diagnostic & diagnostic)
Definition at line 1945 of file lsp-main.cpp.
{
  JsonObject::Object object;
  object.emplace("range", makeRange(diagnostic.range));
  object.emplace("severity", JsonObject(toLspSeverity(diagnostic.level)));
  object.emplace("source", JsonObject("zap-lsp"));
  object.emplace("message", JsonObject(diagnostic.message));
  return JsonObject(std::move(object));
}
References zap::Diagnostic::level, makeRange(), zap::Diagnostic::message, zap::Diagnostic::range, and toLspSeverity().
Referenced by makePublishDiagnostics().
makeHover()
JsonObject anonymous_namespace{lsp-main.cpp}::makeHover (const HoverInfo & hover)
Definition at line 1180 of file lsp-main.cpp.
{
  JsonObject::Object contents;
  contents.emplace("kind", JsonObject("markdown"));
  contents.emplace("value", JsonObject("```" + hover.language + "\n" +
                                       hover.value + "\n```"));
  JsonObject::Object result;
  result.emplace("contents", JsonObject(std::move(contents)));
  return JsonObject(std::move(result));
}
References anonymous_namespace{lsp-main.cpp}::HoverInfo::language, and anonymous_namespace{lsp-main.cpp}::HoverInfo::value.
Referenced by main().
makeLocation()
JsonObject anonymous_namespace{lsp-main.cpp}::makeLocation (const std::string & uri, const SourceSpan & span)
Definition at line 1465 of file lsp-main.cpp.
{
  zap::DiagnosticRange range{{span.line, span.column, span.offset},
                             {span.line,
                              span.column + std::max<size_t>(span.length, 1),
                              span.offset + span.length}};
  JsonObject::Object object;
  object.emplace("uri", JsonObject(uri));
  object.emplace("range", makeRange(range));
  return JsonObject(std::move(object));
}
References SourceSpan::column, SourceSpan::length, SourceSpan::line, makeRange(), and SourceSpan::offset.
Referenced by main().
makeNotification()
JsonObject anonymous_namespace{lsp-main.cpp}::makeNotification (std::string method, JsonObject params)
Definition at line 1726 of file lsp-main.cpp.
{
  JsonObject::Object object;
  object.emplace("jsonrpc", JsonObject("2.0"));
  object.emplace("method", JsonObject(std::move(method)));
  object.emplace("params", std::move(params));
  return JsonObject(std::move(object));
}
Referenced by makePublishDiagnostics().
makePublishDiagnostics()
JsonObject anonymous_namespace{lsp-main.cpp}::makePublishDiagnostics (std::string uri, const std::vector< zap::Diagnostic > & diagnostics)
Definition at line 1955 of file lsp-main.cpp.
{
  JsonObject::List items;
  items.reserve(diagnostics.size());
  for (const auto &diagnostic : diagnostics) {
    items.push_back(makeDiagnostic(diagnostic));
  }
  JsonObject::Object params;
  params.emplace("uri", JsonObject(std::move(uri)));
  params.emplace("diagnostics", JsonObject(std::move(items)));
  return makeNotification("textDocument/publishDiagnostics",
                          JsonObject(std::move(params)));
}
References makeDiagnostic(), and makeNotification().
Referenced by main(), and publishAnalysis().
makeRange()
JsonObject anonymous_namespace{lsp-main.cpp}::makeRange (const zap::DiagnosticRange & range)
Definition at line 1734 of file lsp-main.cpp.
{
  JsonObject::Object start;
  start.emplace("line", JsonObject(static_cast<int64_t>(
                            range.start.line > 0 ? range.start.line - 1 : 0)));
  start.emplace("character",
                JsonObject(static_cast<int64_t>(
                    range.start.column > 0 ? range.start.column - 1 : 0)));
  JsonObject::Object end;
  end.emplace("line", JsonObject(static_cast<int64_t>(
                          range.end.line > 0 ? range.end.line - 1 : 0)));
  end.emplace("character",
              JsonObject(static_cast<int64_t>(
                  range.end.column > 0 ? range.end.column - 1 : 0)));
  JsonObject::Object object;
  object.emplace("start", JsonObject(std::move(start)));
  object.emplace("end", JsonObject(std::move(end)));
  return JsonObject(std::move(object));
}
References zap::DiagnosticPosition::column, zap::DiagnosticRange::end, zap::DiagnosticPosition::line, and zap::DiagnosticRange::start.
Referenced by makeDiagnostic(), and makeLocation().
makeResponse()
JsonObject anonymous_namespace{lsp-main.cpp}::makeResponse (const JsonObject * id, JsonObject result)
Definition at line 1718 of file lsp-main.cpp.
{
  JsonObject::Object object;
  object.emplace("jsonrpc", JsonObject("2.0"));
  object.emplace("id", id ? *id : JsonObject(nullptr));
  object.emplace("result", std::move(result));
  return JsonObject(std::move(object));
}
Referenced by main().
makeSignatureHelp()
JsonObject anonymous_namespace{lsp-main.cpp}::makeSignatureHelp (const std::vector< LspSignature > & signatures, int64_t activeSignature, int64_t activeParameter)
Definition at line 1274 of file lsp-main.cpp.
{
  JsonObject::List signatureItems;
  signatureItems.reserve(signatures.size());
  for (const auto &signature : signatures) {
    JsonObject::List parameters;
    parameters.reserve(signature.parameters.size());
    for (const auto &param : signature.parameters) {
      JsonObject::Object parameter;
      parameter.emplace("label", JsonObject(param));
      parameters.push_back(JsonObject(std::move(parameter)));
    }
    JsonObject::Object sig;
    sig.emplace("label", JsonObject(signature.label));
    sig.emplace("parameters", JsonObject(std::move(parameters)));
    signatureItems.push_back(JsonObject(std::move(sig)));
  }
  int64_t clampedSignature =
      signatures.empty()
          ? 0
          : std::max<int64_t>(0, std::min<int64_t>(activeSignature,
                                                   static_cast<int64_t>(
                                                       signatures.size() - 1)));
  int64_t clampedParameter = 0;
  if (!signatures.empty()) {
    clampedParameter = std::max<int64_t>(
        0, std::min<int64_t>(
               activeParameter,
               static_cast<int64_t>(
                   signatures[clampedSignature].parameters.empty()
                       ? 0
                       : signatures[clampedSignature].parameters.size() - 1)));
  }
  JsonObject::Object result;
  result.emplace("signatures", JsonObject(std::move(signatureItems)));
  result.emplace("activeSignature", JsonObject(clampedSignature));
  result.emplace("activeParameter", JsonObject(clampedParameter));
  return JsonObject(std::move(result));
}
Referenced by main().
makeSymbol()
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::makeSymbol (const std::string & uri, const std::string & name, const SourceSpan & span, int64_t kind, Visibility visibility = Visibility::Private)
Definition at line 495 of file lsp-main.cpp.
{
  return LspSymbol{name, uri, span, kind, visibility};
}
References Private.
Referenced by collectCompletionSymbols(), collectImportedSymbols(), collectLocalsFromNode(), collectLocalsInBody(), collectLocalSymbols(), main(), resolveDefinition(), and topLevelSymbolForNode().
memberAccessBeforeCursor()
std::optional< std::pair< std::string, std::string > > anonymous_namespace{lsp-main.cpp}::memberAccessBeforeCursor (const std::string & source, size_t offset)
Definition at line 369 of file lsp-main.cpp.
{
  if (offset == 0 || offset > source.size()) {
    return std::nullopt;
  }
  size_t pos = offset;
  while (pos > 0 && std::isspace(static_cast<unsigned char>(source[pos - 1]))) {
    --pos;
  }
  if (pos == 0 || source[pos - 1] != '.') {
    return std::nullopt;
  }
  size_t end = pos - 1;
  size_t start = end;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  if (start == end) {
    return std::nullopt;
  }
  std::string base = source.substr(start, end - start);
  size_t left = start;
  while (left > 1) {
    size_t dot = left;
    while (dot > 0 &&
           std::isspace(static_cast<unsigned char>(source[dot - 1]))) {
      --dot;
    }
    if (dot == 0 || source[dot - 1] != '.') {
      break;
    }
    size_t nameEnd = dot - 1;
    size_t nameStart = nameEnd;
    while (nameStart > 0 && isIdentifierChar(source[nameStart - 1])) {
      --nameStart;
    }
    if (nameStart == nameEnd) {
      break;
    }
    base = source.substr(nameStart, end - nameStart);
    left = nameStart;
  }
  size_t split = base.find('.');
  if (split == std::string::npos) {
    return std::make_pair(base, std::string());
  }
  return std::make_pair(base.substr(0, split), base.substr(split + 1));
}
References isIdentifierChar().
Referenced by main().
offsetFromPosition()
size_t anonymous_namespace{lsp-main.cpp}::offsetFromPosition (const std::string & text, int64_t line, int64_t character)
Definition at line 298 of file lsp-main.cpp.
{
  size_t offset = 0;
  int64_t currentLine = 0;
  while (offset < text.size() && currentLine < line) {
    if (text[offset++] == '\n') {
      ++currentLine;
    }
  }
  int64_t currentChar = 0;
  while (offset < text.size() && currentChar < character &&
         text[offset] != '\n') {
    ++offset;
    ++currentChar;
  }
  return offset;
}
Referenced by main().
pathToUri()
std::string anonymous_namespace{lsp-main.cpp}::pathToUri (const std::filesystem::path & path)
Definition at line 325 of file lsp-main.cpp.
{
  std::string uri = "file://";
  std::string text = path.generic_string();
  for (unsigned char ch : text) {
    bool unreserved = (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') ||
                      (ch >= '0' && ch <= '9') || ch == '/' || ch == '-' ||
                      ch == '_' || ch == '.' || ch == '~';
    if (unreserved) {
      uri.push_back(static_cast<char>(ch));
    } else {
      static constexpr char hex[] = "0123456789ABCDEF";
      uri.push_back('%');
      uri.push_back(hex[(ch >> 4) & 0x0F]);
      uri.push_back(hex[ch & 0x0F]);
    }
  }
  return uri;
}
Referenced by collectImportedSymbols(), anonymous_namespace{lsp-main.cpp}::Workspace::loadProject(), main(), and resolveDefinition().
publishAnalysis()
void anonymous_namespace{lsp-main.cpp}::publishAnalysis (Server & server, const AnalysisResult & result)
Definition at line 1970 of file lsp-main.cpp.
{
  for (const auto &[uri, diagnostics] : result.diagnosticsByUri) {
    server.sendMessage(makePublishDiagnostics(uri, diagnostics));
  }
}
References anonymous_namespace{lsp-main.cpp}::AnalysisResult::diagnosticsByUri, makePublishDiagnostics(), and zap::lsp::Server::sendMessage().
Referenced by main().
qualifiedIdentifierAtOffset()
std::optional< std::pair< std::string, std::string > > anonymous_namespace{lsp-main.cpp}::qualifiedIdentifierAtOffset (const std::string & source, size_t offset)
Definition at line 421 of file lsp-main.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = offset < source.size() ? offset : source.size() - 1;
  if (!isIdentifierChar(source[pos])) {
    if (pos == 0 || !isIdentifierChar(source[pos - 1])) {
      return std::nullopt;
    }
    --pos;
  }
  size_t start = pos;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  size_t end = pos + 1;
  while (end < source.size() && isIdentifierChar(source[end])) {
    ++end;
  }
  while (start > 1) {
    size_t dot = start;
    while (dot > 0 &&
           std::isspace(static_cast<unsigned char>(source[dot - 1]))) {
      --dot;
    }
    if (dot == 0 || source[dot - 1] != '.') {
      break;
    }
    size_t nameEnd = dot - 1;
    size_t nameStart = nameEnd;
    while (nameStart > 0 && isIdentifierChar(source[nameStart - 1])) {
      --nameStart;
    }
    if (nameStart == nameEnd) {
      break;
    }
    start = nameStart;
  }
  while (end < source.size()) {
    size_t dot = end;
    while (dot < source.size() &&
           std::isspace(static_cast<unsigned char>(source[dot]))) {
      ++dot;
    }
    if (dot >= source.size() || source[dot] != '.') {
      break;
    }
    size_t nameStart = dot + 1;
    while (nameStart < source.size() &&
           std::isspace(static_cast<unsigned char>(source[nameStart]))) {
      ++nameStart;
    }
    size_t nameEnd = nameStart;
    while (nameEnd < source.size() && isIdentifierChar(source[nameEnd])) {
      ++nameEnd;
    }
    if (nameEnd == nameStart) {
      break;
    }
    end = nameEnd;
  }
  std::string text = source.substr(start, end - start);
  size_t split = text.find('.');
  if (split == std::string::npos) {
    return std::make_pair(text, std::string());
  }
  return std::make_pair(text.substr(0, split), text.substr(split + 1));
}
References isIdentifierChar().
Referenced by resolveDefinition(), and resolveHover().
readFlagsFromFile()
LspFlags anonymous_namespace{lsp-main.cpp}::readFlagsFromFile (const std::filesystem::path & path)
Definition at line 194 of file lsp-main.cpp.
{
  LspFlags flags;
  std::ifstream file(path);
  if (!file) {
    return flags;
  }
  std::string line;
  while (std::getline(file, line)) {
    if (line == "--allow-unsafe") {
      flags.allowUnsafe = true;
    }
  }
  return flags;
}
References anonymous_namespace{lsp-main.cpp}::LspFlags::allowUnsafe.
Referenced by findAndReadFlags().
readSourceFile()
bool anonymous_namespace{lsp-main.cpp}::readSourceFile (const std::filesystem::path & path, std::string & content)
Definition at line 175 of file lsp-main.cpp.
{
  std::ifstream file(path, std::ios::binary | std::ios::ate);
  if (!file) {
    return false;
  }
  auto size = file.tellg();
  content.assign(static_cast<size_t>(std::max<std::streamsize>(size, 0)), '\0');
  if (size > 0) {
    file.seekg(0);
    file.read(content.data(), size);
  }
  return true;
}
Referenced by anonymous_namespace{lsp-main.cpp}::Workspace::sourceForPath().
renderParameter()
std::string anonymous_namespace{lsp-main.cpp}::renderParameter (const ParameterNode * param)
Definition at line 517 of file lsp-main.cpp.
{
  if (!param) {
    return "";
  }
  return std::string(param->isRef ? "ref " : "") + param->name + ": " +
         renderType(param->type.get());
}
References ParameterNode::isRef, ParameterNode::name, renderType(), and ParameterNode::type.
Referenced by signatureForNode().
renderType()
std::string anonymous_namespace{lsp-main.cpp}::renderType (const TypeNode * type)
Definition at line 501 of file lsp-main.cpp.
{
  if (!type) {
    return "Void";
  }
  if (type->isVarArgs && type->baseType) {
    return "..." + renderType(type->baseType.get());
  }
  if (type->isPointer && type->baseType) {
    return "*" + renderType(type->baseType.get());
  }
  if (type->isArray && type->baseType) {
    return "[" + renderType(type->baseType.get()) + "]";
  }
  return type->qualifiedName();
}
References TypeNode::baseType, TypeNode::isArray, TypeNode::isPointer, TypeNode::isVarArgs, TypeNode::qualifiedName(), and renderType().
Referenced by hoverForClassMember(), hoverForNode(), renderParameter(), renderType(), resolveClassTypeNameFromTypeNode(), and signatureForNode().
resolveClassByTypeName()
const ClassDecl * anonymous_namespace{lsp-main.cpp}::resolveClassByTypeName (const ProjectState & project, const sema::ModuleInfo & module, std::string_view typeName, bool publicOnly = false)
Definition at line 674 of file lsp-main.cpp.
{
  auto [qualifier, localName] = splitQualifiedName(typeName);
  if (localName.empty()) {
    return nullptr;
  }
  if (qualifier.empty()) {
    return findClassDecl(module, localName, publicOnly);
  }
  auto importedModule = findImportedModuleByAlias(project, module, qualifier);
  if (!importedModule) {
    return nullptr;
  }
  return findClassDecl(*importedModule, localName, publicOnly);
}
References findClassDecl(), findImportedModuleByAlias(), and splitQualifiedName().
Referenced by findClassField(), findClassMethod(), isClassTypeName(), main(), resolveDefinition(), and resolveHover().
resolveClassTypeNameFromTypeNode()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::resolveClassTypeNameFromTypeNode (const ProjectState & project, const sema::ModuleInfo & module, const TypeNode * type)
Definition at line 699 of file lsp-main.cpp.
{
  if (!type) {
    return std::nullopt;
  }
  std::string qualified = renderType(type);
  if (!isClassTypeName(project, module, qualified)) {
    return std::nullopt;
  }
  return qualified;
}
References isClassTypeName(), and renderType().
Referenced by lookupTypeInNode(), and resolveVariableClassType().
resolveDefinition()
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::resolveDefinition (const Workspace & workspace, const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 1833 of file lsp-main.cpp.
{
  const DocumentState *document = workspace.document(uri);
  if (!document) {
    return std::nullopt;
  }
  auto path = uriToPath(uri);
  if (!path) {
    return std::nullopt;
  }
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return std::nullopt;
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  if (auto qualified = qualifiedIdentifierAtOffset(document->text, offset)) {
    const auto &[base, rest] = *qualified;
    if (!rest.empty()) {
      std::string memberName = rest;
      size_t dot = memberName.rfind('.');
      if (dot != std::string::npos) {
        memberName = memberName.substr(dot + 1);
      }
      for (const auto &import : module.imports) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt == project.moduleMap.end()) {
            continue;
          }
          if (effectiveImportAlias(import, *targetIt->second) != base) {
            continue;
          }
          auto targetUriIt = project.uriByModuleId.find(targetId);
          std::string targetUri = targetUriIt == project.uriByModuleId.end()
                                      ? pathToUri(targetId)
                                      : targetUriIt->second;
          auto exported =
              collectTopLevelSymbols(*targetIt->second, targetUri, true);
          auto exportIt = std::find_if(exported.begin(), exported.end(),
                                       [&](const LspSymbol &symbol) {
                                         return symbol.name == memberName;
                                       });
          if (exportIt != exported.end()) {
            return *exportIt;
          }
        }
      }
      if (base.find('.') == std::string::npos) {
        if (auto classType =
                resolveVariableClassType(project, module, offset, base)) {
          if (auto cls = resolveClassByTypeName(project, module, *classType)) {
            if (auto field = findClassField(cls, project, module, memberName)) {
              return *makeSymbol(uri, field->name, field->span, 8,
                                 field->visibility_);
            }
            if (auto method =
                    findClassMethod(cls, project, module, memberName)) {
              return *makeSymbol(uri, method->name_, method->span, 2,
                                 method->visibility_);
            }
          }
        }
      }
    }
  }
  auto name = identifierAt(document->text, offset);
  if (!name) {
    return std::nullopt;
  }
  auto locals = collectLocalSymbols(*module.root, offset, uri);
  for (auto it = locals.rbegin(); it != locals.rend(); ++it) {
    if (it->name == *name) {
      return *it;
    }
  }
  auto imported = collectImportedSymbols(project, module);
  for (const auto &symbol : imported) {
    if (symbol.name == *name) {
      return symbol;
    }
  }
  auto topLevel = collectTopLevelSymbols(module, uri);
  for (const auto &symbol : topLevel) {
    if (symbol.name == *name) {
      return symbol;
    }
  }
  return std::nullopt;
}
References collectImportedSymbols(), collectLocalSymbols(), collectTopLevelSymbols(), anonymous_namespace{lsp-main.cpp}::Workspace::document(), effectiveImportAlias(), findClassField(), findClassMethod(), identifierAt(), sema::ModuleInfo::imports, makeSymbol(), anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap, pathToUri(), qualifiedIdentifierAtOffset(), resolveClassByTypeName(), resolveVariableClassType(), sema::ModuleInfo::root, anonymous_namespace{lsp-main.cpp}::DocumentState::text, anonymous_namespace{lsp-main.cpp}::ProjectState::uriByModuleId, and uriToPath().
Referenced by main().
resolveHover()
std::optional< HoverInfo > anonymous_namespace{lsp-main.cpp}::resolveHover (const std::string & source, const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 1191 of file lsp-main.cpp.
{
  auto path = uriToPath(uri);
  if (!path) {
    return std::nullopt;
  }
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return std::nullopt;
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  if (auto qualified = qualifiedIdentifierAtOffset(source, offset)) {
    const auto &[base, rest] = *qualified;
    if (!rest.empty()) {
      std::string memberName = rest;
      size_t dot = memberName.rfind('.');
      if (dot != std::string::npos) {
        memberName = memberName.substr(dot + 1);
      }
      for (const auto &import : module.imports) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt == project.moduleMap.end()) {
            continue;
          }
          if (effectiveImportAlias(import, *targetIt->second) != base) {
            continue;
          }
          if (auto hover =
                  findTopLevelHover(*targetIt->second, memberName, true)) {
            return hover;
          }
        }
      }
      if (base.find('.') == std::string::npos) {
        if (auto classType =
                resolveVariableClassType(project, module, offset, base)) {
          if (auto cls = resolveClassByTypeName(project, module, *classType)) {
            if (auto hover =
                    hoverForClassMember(cls, project, module, memberName)) {
              return hover;
            }
          }
        }
      }
    }
  }
  auto name = identifierAt(source, offset);
  if (!name) {
    return std::nullopt;
  }
  if (auto hover = findTopLevelHover(module, *name)) {
    return hover;
  }
  for (const auto &import : module.imports) {
    for (const auto &binding : import.bindings) {
      if (binding.localName != *name) {
        continue;
      }
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt == project.moduleMap.end()) {
          continue;
        }
        if (auto hover = findTopLevelHover(*targetIt->second,
                                           binding.sourceName, true)) {
          return hover;
        }
      }
    }
  }
  return std::nullopt;
}
References effectiveImportAlias(), findTopLevelHover(), hoverForClassMember(), identifierAt(), sema::ModuleInfo::imports, anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap, qualifiedIdentifierAtOffset(), resolveClassByTypeName(), resolveVariableClassType(), and uriToPath().
Referenced by main().
resolveImportTargets()
bool anonymous_namespace{lsp-main.cpp}::resolveImportTargets (const std::filesystem::path & modulePath, const ImportNode & importNode, std::vector< std::filesystem::path > & targets)
Definition at line 228 of file lsp-main.cpp.
{
  std::filesystem::path resolvedPath;
  if (importNode.path.rfind("std/", 0) == 0) {
    resolvedPath =
        stdlibRootPath() / importNode.path.substr(std::string("std/").size());
  } else {
    resolvedPath = modulePath.parent_path() / importNode.path;
  }
  resolvedPath = resolvedPath.lexically_normal();
  auto tryFile = [&](const std::filesystem::path &path) -> bool {
    if (std::filesystem::exists(path) &&
        std::filesystem::is_regular_file(path)) {
      targets.push_back(std::filesystem::weakly_canonical(path));
      return true;
    }
    return false;
  };
  if (tryFile(resolvedPath)) {
    return true;
  }
  if (resolvedPath.extension() != ".zp" &&
      tryFile(resolvedPath.string() + ".zp")) {
    return true;
  }
  if (std::filesystem::exists(resolvedPath) &&
      std::filesystem::is_directory(resolvedPath)) {
    for (const auto &entry :
         std::filesystem::directory_iterator(resolvedPath)) {
      if (entry.is_regular_file() && entry.path().extension() == ".zp") {
        targets.push_back(std::filesystem::weakly_canonical(entry.path()));
      }
    }
    return !targets.empty();
  }
  return false;
}
References ImportNode::path, and stdlibRootPath().
Referenced by anonymous_namespace{lsp-main.cpp}::Workspace::loadModuleGraph().
resolveSignatures()
std::vector< LspSignature > anonymous_namespace{lsp-main.cpp}::resolveSignatures (const std::string & source, const std::string & uri, const ProjectState & project, size_t offset, int64_t & activeParameter)
Definition at line 1045 of file lsp-main.cpp.
{
  auto path = uriToPath(uri);
  if (!path) {
    return {};
  }
  auto call = callContextNearOffset(source, offset);
  if (!call) {
    return {};
  }
  activeParameter = call->activeParameter;
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return {};
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  auto dot = call->callee.find('.');
  if (dot != std::string::npos) {
    std::string base = call->callee.substr(0, dot);
    std::string member = call->callee.substr(dot + 1);
    for (const auto &import : module.imports) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt == project.moduleMap.end()) {
          continue;
        }
        if (effectiveImportAlias(import, *targetIt->second) != base) {
          continue;
        }
        auto signatures =
            findTopLevelSignatures(*targetIt->second, member, true);
        if (!signatures.empty()) {
          return signatures;
        }
      }
    }
    return {};
  }
  auto localSignatures = findTopLevelSignatures(module, call->callee);
  if (!localSignatures.empty()) {
    return localSignatures;
  }
  for (const auto &import : module.imports) {
    for (const auto &binding : import.bindings) {
      if (binding.localName != call->callee) {
        continue;
      }
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt == project.moduleMap.end()) {
          continue;
        }
        auto signatures =
            findTopLevelSignatures(*targetIt->second, binding.sourceName, true);
        if (!signatures.empty()) {
          return signatures;
        }
      }
    }
  }
  return {};
}
References callContextNearOffset(), effectiveImportAlias(), findTopLevelSignatures(), sema::ModuleInfo::imports, anonymous_namespace{lsp-main.cpp}::ProjectState::moduleMap, and uriToPath().
Referenced by main().
resolveVariableClassType()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::resolveVariableClassType (const ProjectState & project, const sema::ModuleInfo & module, size_t offset, std::string_view name)
Definition at line 805 of file lsp-main.cpp.
{
  if (name == "self") {
    if (auto cls = enclosingClassAtOffset(*module.root, offset)) {
      return cls->name_;
    }
  }
  for (const auto &child : module.root->children) {
    if (auto var = dynamic_cast<const VarDecl *>(child.get())) {
      if (var->name_ == name) {
        return resolveClassTypeNameFromTypeNode(project, module,
                                                var->type_.get());
      }
    }
    if (auto cnst = dynamic_cast<const ConstDecl *>(child.get())) {
      if (cnst->name_ == name) {
        return resolveClassTypeNameFromTypeNode(project, module,
                                                cnst->type_.get());
      }
    }
    if (auto fun = dynamic_cast<const FunDecl *>(child.get())) {
      if (!containsOffset(fun->span, offset)) {
        continue;
      }
      for (const auto &param : fun->params_) {
        if (param && param->name == name) {
          return resolveClassTypeNameFromTypeNode(project, module,
                                                  param->type.get());
        }
      }
      return lookupTypeInBody(project, module, fun->body_.get(), offset, name);
    }
    if (auto cls = dynamic_cast<const ClassDecl *>(child.get())) {
      if (!containsOffset(cls->span, offset)) {
        continue;
      }
      for (const auto &field : cls->fields_) {
        if (field && field->name == name) {
          return resolveClassTypeNameFromTypeNode(project, module,
                                                  field->type.get());
        }
      }
      for (const auto &method : cls->methods_) {
        if (!method || !containsOffset(method->span, offset)) {
          continue;
        }
        for (const auto &param : method->params_) {
          if (param && param->name == name) {
            return resolveClassTypeNameFromTypeNode(project, module,
                                                    param->type.get());
          }
        }
        return lookupTypeInBody(project, module, method->body_.get(), offset,
                                name);
      }
    }
  }
  return std::nullopt;
}
References containsOffset(), enclosingClassAtOffset(), lookupTypeInBody(), resolveClassTypeNameFromTypeNode(), and sema::ModuleInfo::root.
Referenced by main(), resolveDefinition(), and resolveHover().
signatureForNode()
std::optional< LspSignature > anonymous_namespace{lsp-main.cpp}::signatureForNode (const Node * node)
Definition at line 525 of file lsp-main.cpp.
{
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    std::vector<std::string> params;
    for (const auto &param : fun->params_) {
      params.push_back(renderParameter(param.get()));
    }
    std::string label = fun->name_ + "(";
    for (size_t i = 0; i < params.size(); ++i) {
      if (i != 0) {
        label += ", ";
      }
      label += params[i];
    }
    label += ") " + renderType(fun->returnType_.get());
    return LspSignature{std::move(label), std::move(params)};
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    std::vector<std::string> params;
    for (const auto &param : ext->params_) {
      params.push_back(renderParameter(param.get()));
    }
    if (ext->isCVariadic_) {
      params.push_back("...");
    }
    std::string label = ext->name_ + "(";
    for (size_t i = 0; i < params.size(); ++i) {
      if (i != 0) {
        label += ", ";
      }
      label += params[i];
    }
    label += ") " + renderType(ext->returnType_.get());
    return LspSignature{std::move(label), std::move(params)};
  }
  return std::nullopt;
}
References renderParameter(), and renderType().
Referenced by findTopLevelSignatures(), hoverForClassMember(), hoverForNode(), and main().
splitQualifiedName()
std::pair< std::string, std::string > anonymous_namespace{lsp-main.cpp}::splitQualifiedName (std::string_view qualifiedName)
Definition at line 665 of file lsp-main.cpp.
{
  size_t dot = qualifiedName.rfind('.');
  if (dot == std::string_view::npos) {
    return {std::string(), std::string(qualifiedName)};
  }
  return {std::string(qualifiedName.substr(0, dot)),
          std::string(qualifiedName.substr(dot + 1))};
}
Referenced by resolveClassByTypeName().
stdlibRootPath()
std::filesystem::path anonymous_namespace{lsp-main.cpp}::stdlibRootPath ()
Definition at line 80 of file lsp-main.cpp.
{
  if (const char *configured = std::getenv("ZAPC_STDLIB_DIR")) {
    if (*configured != '\0') {
      return std::filesystem::path(configured);
    }
  }
  std::error_code ec;
  auto exePath = std::filesystem::read_symlink("/proc/self/exe", ec);
  if (!ec && !exePath.empty()) {
    auto siblingStd =
        std::filesystem::weakly_canonical(exePath).parent_path() / "std";
    if (std::filesystem::exists(siblingStd) &&
        std::filesystem::is_directory(siblingStd)) {
      return siblingStd;
    }
  }
  return std::filesystem::path(ZAPC_STDLIB_DIR);
}
Referenced by computeLogicalModulePath(), and resolveImportTargets().
stripSourceExtension()
std::string anonymous_namespace{lsp-main.cpp}::stripSourceExtension (const std::filesystem::path & path)
Definition at line 72 of file lsp-main.cpp.
{
  auto normalized = path.generic_string();
  if (path.extension() == ".zp" && normalized.size() >= 4) {
    normalized.resize(normalized.size() - 3);
  }
  return normalized;
}
Referenced by computeLogicalModulePath().
toLspSeverity()
int64_t anonymous_namespace{lsp-main.cpp}::toLspSeverity (zap::DiagnosticLevel level)
Definition at line 1933 of file lsp-main.cpp.
{
  switch (level) {
  case zap::DiagnosticLevel::Error:
    return 1;
  case zap::DiagnosticLevel::Warning:
    return 2;
  case zap::DiagnosticLevel::Note:
    return 3;
  }
  return 1;
}
References zap::Error, zap::Note, and zap::Warning.
Referenced by makeDiagnostic().
topLevelNameForNode()
std::optional< std::string > anonymous_namespace{lsp-main.cpp}::topLevelNameForNode (const Node * node)
Definition at line 598 of file lsp-main.cpp.
{
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    return fun->name_;
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    return ext->name_;
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return var->name_;
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return cnst->name_;
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    return record->name_;
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    return strukt->name_;
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    return cls->name_;
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return enm->name_;
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return alias->name_;
  }
  return std::nullopt;
}
Referenced by findTopLevelHover().
topLevelSymbolForNode()
std::optional< LspSymbol > anonymous_namespace{lsp-main.cpp}::topLevelSymbolForNode (const Node * node, const std::string & uri)
Definition at line 1324 of file lsp-main.cpp.
{
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    return makeSymbol(uri, fun->name_, fun->span, 3, fun->visibility_);
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    return makeSymbol(uri, ext->name_, ext->span, 3, ext->visibility_);
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return makeSymbol(uri, var->name_, var->span, 6, var->visibility_);
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return makeSymbol(uri, cnst->name_, cnst->span, 21, cnst->visibility_);
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    return makeSymbol(uri, record->name_, record->span, 22,
                      record->visibility_);
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    return makeSymbol(uri, strukt->name_, strukt->span, 22,
                      strukt->visibility_);
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    return makeSymbol(uri, cls->name_, cls->span, 5, cls->visibility_);
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return makeSymbol(uri, enm->name_, enm->span, 13, enm->visibility_);
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return makeSymbol(uri, alias->name_, alias->span, 22, alias->visibility_);
  }
  return std::nullopt;
}
References makeSymbol().
Referenced by collectTopLevelSymbols().
uriToPath()
std::optional< std::filesystem::path > anonymous_namespace{lsp-main.cpp}::uriToPath (std::string_view uri)
Definition at line 133 of file lsp-main.cpp.
{
  constexpr std::string_view prefix = "file://";
  if (uri.rfind(prefix, 0) != 0) {
    return std::nullopt;
  }
  std::string decoded;
  decoded.reserve(uri.size() - prefix.size());
  for (size_t i = prefix.size(); i < uri.size(); ++i) {
    char ch = uri[i];
    if (ch == '%' && i + 2 < uri.size()) {
      auto hex = [](char value) -> int {
        if (value >= '0' && value <= '9')
          return value - '0';
        if (value >= 'a' && value <= 'f')
          return 10 + value - 'a';
        if (value >= 'A' && value <= 'F')
          return 10 + value - 'A';
        return -1;
      };
      int hi = hex(uri[i + 1]);
      int lo = hex(uri[i + 2]);
      if (hi >= 0 && lo >= 0) {
        decoded.push_back(static_cast<char>((hi << 4) | lo));
        i += 2;
        continue;
      }
    }
    decoded.push_back(ch);
  }
#ifdef _WIN32
  if (decoded.size() >= 3 && decoded[0] == '/' &&
      std::isalpha(static_cast<unsigned char>(decoded[1])) &&
      decoded[2] == ':') {
    decoded.erase(decoded.begin());
  }
#endif
  return std::filesystem::path(decoded).lexically_normal();
}
References zap::lsp::prefix.
Referenced by collectCompletionSymbols(), main(), resolveDefinition(), resolveHover(), and resolveSignatures().