ZAP: zap::anonymous_namespace{parser.cpp} Namespace Reference
zap::anonymous_namespace{parser.cpp} Namespace Reference
Functions
std::string compoundAssignOp (TokenType type)
void qualifiedNameFromExpressionImpl (const ExpressionNode *expr, std::string &out)
std::string qualifiedNameFromExpression (const ExpressionNode *expr)
Function Documentation
compoundAssignOp()
std::string zap::anonymous_namespace{parser.cpp}::compoundAssignOp (TokenType type)
Definition at line 11 of file parser.cpp.
{
  switch (type) {
  case TokenType::PLUS_ASSIGN:
    return "+";
  case TokenType::MINUS_ASSIGN:
    return "-";
  case TokenType::STAR_ASSIGN:
    return "*";
  case TokenType::SLASH_ASSIGN:
    return "/";
  case TokenType::PERCENT_ASSIGN:
    return "%";
  case TokenType::AMP_ASSIGN:
    return "&";
  case TokenType::PIPE_ASSIGN:
    return "|";
  case TokenType::CARET_ASSIGN:
    return "^";
  case TokenType::LSHIFT_ASSIGN:
    return "<<";
  case TokenType::RSHIFT_ASSIGN:
    return ">>";
  default:
    return "";
  }
}
References AMP_ASSIGN, CARET_ASSIGN, compoundAssignOp(), LSHIFT_ASSIGN, MINUS_ASSIGN, PERCENT_ASSIGN, PIPE_ASSIGN, PLUS_ASSIGN, RSHIFT_ASSIGN, SLASH_ASSIGN, and STAR_ASSIGN.
Referenced by compoundAssignOp().
qualifiedNameFromExpression()
std::string zap::anonymous_namespace{parser.cpp}::qualifiedNameFromExpression (const ExpressionNode * expr)
Definition at line 53 of file parser.cpp.
{
  std::string result;
  result.reserve(32);
  qualifiedNameFromExpressionImpl(expr, result);
  return result;
}
References qualifiedNameFromExpression(), and qualifiedNameFromExpressionImpl().
Referenced by qualifiedNameFromExpression().
qualifiedNameFromExpressionImpl()
void zap::anonymous_namespace{parser.cpp}::qualifiedNameFromExpressionImpl (const ExpressionNode * expr, std::string & out)
Definition at line 38 of file parser.cpp.
{
  if (auto id = dynamic_cast<const ConstId *>(expr)) {
    out += id->value_;
    return;
  }
  if (auto member = dynamic_cast<const MemberAccessNode *>(expr)) {
    qualifiedNameFromExpressionImpl(member->left_.get(), out);
    if (out.empty())
      return;
    out += '.';
    out += member->member_;
  }
}
References zap::out(), and qualifiedNameFromExpressionImpl().
Referenced by qualifiedNameFromExpression(), and qualifiedNameFromExpressionImpl().