ZAP: TypeNode Class Reference
TypeNode Class Reference
#include <type_node.hpp>
Public Member Functions
TypeNode () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
TypeNode (const std::string &typeName_)
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string typeName
bool isReference = false
bool isPointer = false
bool isArray = false
bool isVarArgs = false
std::unique_ptr< ExpressionNode > arraySize
std::unique_ptr< TypeNode > baseType
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file type_node.hpp.
Constructor & Destructor Documentation
TypeNode() [1/2]
TypeNode::TypeNode () const default noexcept
Referenced by TypeNode().
TypeNode() [2/2]
TypeNode::TypeNode (const std::string & typeName_) inline explicit
Definition at line 19 of file type_node.hpp.
: typeName(typeName_) {}
References typeName, and TypeNode().
Member Function Documentation
accept()
void TypeNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 21 of file type_node.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
arraySize
std::unique_ptr<ExpressionNode> TypeNode::arraySize
Definition at line 15 of file type_node.hpp.
Referenced by sema::Binder::mapType().
baseType
std::unique_ptr<TypeNode> TypeNode::baseType
Definition at line 16 of file type_node.hpp.
Referenced by sema::Binder::mapType().
isArray
bool TypeNode::isArray = false
Definition at line 13 of file type_node.hpp.
Referenced by sema::Binder::mapType().
isPointer
bool TypeNode::isPointer = false
Definition at line 12 of file type_node.hpp.
Referenced by sema::Binder::mapType().
isReference
bool TypeNode::isReference = false
Definition at line 11 of file type_node.hpp.
isVarArgs
bool TypeNode::isVarArgs = false
Definition at line 14 of file type_node.hpp.
typeName
std::string TypeNode::typeName
Definition at line 10 of file type_node.hpp.
Referenced by sema::Binder::mapType(), and TypeNode().
The documentation for this class was generated from the following file:
src/ast/type_node.hpp