ZAP: zir::anonymous_namespace{failable_type.cpp} Namespace Reference
zir::anonymous_namespace{failable_type.cpp} Namespace Reference
Functions
std::string sanitizeFailableTypeName (const std::string &value)
std::shared_ptr< RecordType > asFailableRecord (const std::shared_ptr< Type > &type)
Function Documentation
asFailableRecord()
std::shared_ptr< RecordType > zir::anonymous_namespace{failable_type.cpp}::asFailableRecord (const std::shared_ptr< Type > & type)
Definition at line 21 of file failable_type.cpp.
{
  if (!type || type->getKind() != TypeKind::Record) {
    return nullptr;
  }
  auto record = std::static_pointer_cast<RecordType>(type);
  if (record->getName().rfind(kFailableTypePrefix, 0) != 0) {
    return nullptr;
  }
  const auto &fields = record->getFields();
  if (fields.size() != 3 || fields[FailableTypeLayout::OkField].name != "ok" ||
      fields[FailableTypeLayout::ValueField].name != "value" ||
      fields[FailableTypeLayout::ErrorField].name != "error") {
    return nullptr;
  }
  return record;
}
References asFailableRecord(), zir::FailableTypeLayout::ErrorField, zir::kFailableTypePrefix, zir::FailableTypeLayout::OkField, zir::Record, and zir::FailableTypeLayout::ValueField.
Referenced by asFailableRecord().
sanitizeFailableTypeName()
std::string zir::anonymous_namespace{failable_type.cpp}::sanitizeFailableTypeName (const std::string & value)
Definition at line 7 of file failable_type.cpp.
{
  std::string out;
  out.reserve(value.size());
  for (char ch : value) {
    if (std::isalnum(static_cast<unsigned char>(ch))) {
      out.push_back(ch);
    } else {
      out.push_back('_');
    }
  }
  return out;
}
References sanitizeFailableTypeName().
Referenced by sanitizeFailableTypeName().