ZAP: codegen::anonymous_namespace{llvm_codegen.cpp} Namespace Reference
codegen::anonymous_namespace{llvm_codegen.cpp} Namespace Reference
Functions
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isStringRecordName (const std::string &full)
std::string lowerGccAsmTemplateToLLVM (const std::string &assembly)
std::string lowerX86GccConstraintToLLVM (const std::string &constraint)
std::string lowerAsmConstraintToLLVM (const std::string &constraint, const llvm::Triple &triple)
void initializeLLVMTargets ()
std::string normalizeTargetTriple (std::string targetTriple)
llvm::CodeGenOptLevel toCodeGenOptLevel (int optimizationLevel)
Function Documentation
initializeLLVMTargets()
void codegen::anonymous_namespace{llvm_codegen.cpp}::initializeLLVMTargets ()
Definition at line 113 of file llvm_codegen.cpp.
{
  static const bool initialized = [] {
    llvm::InitializeAllTargetInfos();
    llvm::InitializeAllTargets();
    llvm::InitializeAllTargetMCs();
    llvm::InitializeAllAsmPrinters();
    llvm::InitializeAllAsmParsers();
    return true;
  }();
  (void)initialized;
}
References initializeLLVMTargets().
Referenced by initializeLLVMTargets().
isStringRecordName()
bool codegen::anonymous_namespace{llvm_codegen.cpp}::isStringRecordName (const std::string & full)
Definition at line 31 of file llvm_codegen.cpp.
{
  return zap::text::isStringRecordName(full);
}
References isStringRecordName(), and zap::text::isStringRecordName().
Referenced by isStringRecordName().
isStringType()
bool codegen::anonymous_namespace{llvm_codegen.cpp}::isStringType (const std::shared_ptr< zir::Type > & type)
Definition at line 27 of file llvm_codegen.cpp.
{
  return zap::text::isStringType(type);
}
References isStringType(), and zap::text::isStringType().
Referenced by isStringType().
lowerAsmConstraintToLLVM()
std::string codegen::anonymous_namespace{llvm_codegen.cpp}::lowerAsmConstraintToLLVM (const std::string & constraint, const llvm::Triple & triple)
Definition at line 106 of file llvm_codegen.cpp.
{
  if (triple.isX86())
    return lowerX86GccConstraintToLLVM(constraint);
  return constraint;
}
References lowerAsmConstraintToLLVM(), and lowerX86GccConstraintToLLVM().
Referenced by lowerAsmConstraintToLLVM().
lowerGccAsmTemplateToLLVM()
std::string codegen::anonymous_namespace{llvm_codegen.cpp}::lowerGccAsmTemplateToLLVM (const std::string & assembly)
Definition at line 35 of file llvm_codegen.cpp.
{
  std::string lowered;
  lowered.reserve(assembly.size());
  for (size_t i = 0; i < assembly.size(); ++i) {
    if (assembly[i] != '%' || i + 1 == assembly.size()) {
      lowered.push_back(assembly[i]);
      continue;
    }
    char next = assembly[i + 1];
    if (std::isdigit(static_cast<unsigned char>(next))) {
      lowered.push_back('$');
      while (i + 1 < assembly.size() &&
             std::isdigit(static_cast<unsigned char>(assembly[i + 1]))) {
        lowered.push_back(assembly[++i]);
      }
    } else if (next == '%') {
      lowered.push_back('%');
      ++i;
    } else {
      lowered.push_back(assembly[i]);
    }
  }
  return lowered;
}
References lowerGccAsmTemplateToLLVM().
Referenced by lowerGccAsmTemplateToLLVM().
lowerX86GccConstraintToLLVM()
std::string codegen::anonymous_namespace{llvm_codegen.cpp}::lowerX86GccConstraintToLLVM (const std::string & constraint)
Definition at line 63 of file llvm_codegen.cpp.
{
  std::string lowered;
  lowered.reserve(constraint.size() + 8);
  for (size_t i = 0; i < constraint.size(); ++i) {
    if (constraint[i] == '{') {
      while (i < constraint.size()) {
        lowered.push_back(constraint[i]);
        if (constraint[i] == '}')
          break;
        ++i;
      }
      continue;
    }
    switch (constraint[i]) {
    case 'a':
      lowered += "{ax}";
      break;
    case 'b':
      lowered += "{bx}";
      break;
    case 'c':
      lowered += "{cx}";
      break;
    case 'd':
      lowered += "{dx}";
      break;
    case 'S':
      lowered += "{si}";
      break;
    case 'D':
      lowered += "{di}";
      break;
    default:
      lowered.push_back(constraint[i]);
      break;
    }
  }
  return lowered;
}
References lowerX86GccConstraintToLLVM().
Referenced by lowerAsmConstraintToLLVM(), and lowerX86GccConstraintToLLVM().
normalizeTargetTriple()
std::string codegen::anonymous_namespace{llvm_codegen.cpp}::normalizeTargetTriple (std::string targetTriple)
Definition at line 125 of file llvm_codegen.cpp.
{
  if (targetTriple.empty()) {
    return llvm::sys::getDefaultTargetTriple();
  }
  return llvm::Triple::normalize(targetTriple);
}
References normalizeTargetTriple().
Referenced by normalizeTargetTriple().
toCodeGenOptLevel()
llvm::CodeGenOptLevel codegen::anonymous_namespace{llvm_codegen.cpp}::toCodeGenOptLevel (int optimizationLevel)
Definition at line 132 of file llvm_codegen.cpp.
{
  if (optimizationLevel < 0) {
    optimizationLevel = 0;
  } else if (optimizationLevel > 3) {
    optimizationLevel = 3;
  }
  if (optimizationLevel == 1) {
    return llvm::CodeGenOptLevel::Less;
  }
  if (optimizationLevel == 2) {
    return llvm::CodeGenOptLevel::Default;
  }
  if (optimizationLevel == 3) {
    return llvm::CodeGenOptLevel::Aggressive;
  }
  return llvm::CodeGenOptLevel::None;
}
References toCodeGenOptLevel().
Referenced by toCodeGenOptLevel().