ZAP: zir::BoundIRGenerator Class Reference
zir::BoundIRGenerator Class Reference
#include <ir_generator.hpp>
Public Member Functions
std::unique_ptr< Module > generate (sema::BoundRootNode &root)
void visit (sema::BoundRootNode &node) override
void visit (sema::BoundFunctionDeclaration &node) override
void visit (sema::BoundExternalFunctionDeclaration &node) override
void visit (sema::BoundBlock &node) override
void visit (sema::BoundVariableDeclaration &node) override
void visit (sema::BoundReturnStatement &node) override
void visit (sema::BoundAssignment &node) override
void visit (sema::BoundExpressionStatement &node) override
void visit (sema::BoundLiteral &node) override
void visit (sema::BoundVariableExpression &node) override
void visit (sema::BoundCompoundTargetLoad &node) override
void visit (sema::BoundBinaryExpression &node) override
void visit (sema::BoundTernaryExpression &node) override
void visit (sema::BoundUnaryExpression &node) override
void visit (sema::BoundFunctionCall &node) override
void visit (sema::BoundIndirectCall &node) override
void visit (sema::BoundFunctionReference &node) override
void visit (sema::BoundArrayLiteral &node) override
void visit (sema::BoundIndexAccess &node) override
void visit (sema::BoundRecordDeclaration &node) override
void visit (sema::BoundEnumDeclaration &node) override
void visit (sema::BoundTaggedUnionDeclaration &node) override
void visit (sema::BoundMemberAccess &node) override
void visit (sema::BoundStructLiteral &node) override
void visit (sema::BoundTaggedUnionLiteral &node) override
void visit (sema::BoundModuleReference &node) override
void visit (sema::BoundIfStatement &node) override
void visit (sema::BoundWhileStatement &node) override
void visit (sema::BoundForStatement &node) override
void visit (sema::BoundBreakStatement &node) override
void visit (sema::BoundContinueStatement &node) override
void visit (sema::BoundAsmStatement &node) override
void visit (sema::BoundCast &node) override
void visit (sema::BoundNewExpression &node) override
void visit (sema::BoundWeakLockExpression &node) override
void visit (sema::BoundWeakAliveExpression &node) override
void visit (sema::BoundTryExpression &node) override
void visit (sema::BoundFallbackExpression &node) override
void visit (sema::BoundFailableHandleExpression &node) override
void visit (sema::BoundFailStatement &node) override
Public Member Functions inherited from sema::BoundVisitor
virtual ~BoundVisitor ()=default
Private Member Functions
std::shared_ptr< Value > createRegister (std::shared_ptr< Type > type)
std::string createBlockLabel (const std::string &prefix)
std::shared_ptr< Value > lowerConstantExpression (const sema::BoundExpression &expression)
std::shared_ptr< Value > lowerConstantExpression (const sema::BoundExpression &expression, std::set< const sema::VariableSymbol * > &resolvingConstants)
std::shared_ptr< Value > emitFailableFieldLoad (const std::shared_ptr< Value > &value, int fieldIndex, const std::shared_ptr< Type > &fieldType)
std::shared_ptr< Value > emitFailableOk (const std::shared_ptr< Value > &value)
std::shared_ptr< Value > emitFailableValue (const std::shared_ptr< Value > &value)
std::shared_ptr< Value > emitFailableError (const std::shared_ptr< Value > &value)
Private Attributes
std::unique_ptr< Module > module_
Function * currentFunction_ = nullptr
BasicBlock * currentBlock_ = nullptr
std::map< std::shared_ptr< sema::Symbol >, std::shared_ptr< Value > > symbolMap_
std::map< std::shared_ptr< sema::Symbol >, std::shared_ptr< Value > > globalSymbolMap_
std::stack< std::shared_ptr< Value > > valueStack_
int nextRegisterId_ = 0
int nextBlockId_ = 0
std::vector< std::pair< std::string, std::string > > loopLabelStack_
std::shared_ptr< Value > lastResultValue_ = nullptr
bool evaluateAsAddress_ = false
std::shared_ptr< Value > compoundTargetAddr_ = nullptr
Detailed Description
Definition at line 13 of file ir_generator.hpp.
Member Function Documentation
createBlockLabel()
std::string zir::BoundIRGenerator::createBlockLabel (const std::string & prefix) private
Definition at line 761 of file ir_generator.cpp.
{
  return prefix + "." + std::to_string(nextBlockId_++);
}
References nextBlockId_.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
createRegister()
std::shared_ptr< Value > zir::BoundIRGenerator::createRegister (std::shared_ptr< Type > type) private
Definition at line 757 of file ir_generator.cpp.
{
  return std::make_shared<Register>(std::to_string(nextRegisterId_++), type);
}
References nextRegisterId_.
Referenced by emitFailableFieldLoad(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
emitFailableError()
std::shared_ptr< Value > zir::BoundIRGenerator::emitFailableError (const std::shared_ptr< Value > & value) private
Definition at line 155 of file ir_generator.cpp.
{
  auto layout = getFailableTypeLayout(value->getType());
  return emitFailableFieldLoad(value, FailableTypeLayout::ErrorField,
                               layout ? layout->errorType : nullptr);
}
References emitFailableFieldLoad(), zir::FailableTypeLayout::ErrorField, and zir::getFailableTypeLayout().
Referenced by visit(), and visit().
emitFailableFieldLoad()
std::shared_ptr< Value > zir::BoundIRGenerator::emitFailableFieldLoad (const std::shared_ptr< Value > & value, int fieldIndex, const std::shared_ptr< Type > & fieldType) private
Definition at line 127 of file ir_generator.cpp.
{
  if (fieldType && fieldType->getKind() == TypeKind::Void) {
    return std::make_shared<Constant>("0", fieldType);
  }
  auto fieldAddr = createRegister(std::make_shared<PointerType>(fieldType));
  currentBlock_->addInstruction(
      std::make_unique<GetElementPtrInst>(fieldAddr, value, fieldIndex));
  auto loaded = createRegister(fieldType);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(loaded, fieldAddr));
  return loaded;
}
References createRegister(), currentBlock_, and zir::Void.
Referenced by emitFailableError(), emitFailableOk(), and emitFailableValue().
emitFailableOk()
std::shared_ptr< Value > zir::BoundIRGenerator::emitFailableOk (const std::shared_ptr< Value > & value) private
Definition at line 142 of file ir_generator.cpp.
{
  return emitFailableFieldLoad(value, FailableTypeLayout::OkField,
                               std::make_shared<PrimitiveType>(TypeKind::Bool));
}
References zir::Bool, emitFailableFieldLoad(), and zir::FailableTypeLayout::OkField.
Referenced by visit(), visit(), and visit().
emitFailableValue()
std::shared_ptr< Value > zir::BoundIRGenerator::emitFailableValue (const std::shared_ptr< Value > & value) private
Definition at line 148 of file ir_generator.cpp.
{
  auto layout = getFailableTypeLayout(value->getType());
  return emitFailableFieldLoad(value, FailableTypeLayout::ValueField,
                               layout ? layout->valueType : nullptr);
}
References emitFailableFieldLoad(), zir::getFailableTypeLayout(), and zir::FailableTypeLayout::ValueField.
Referenced by visit(), visit(), and visit().
generate()
std::unique_ptr< Module > zir::BoundIRGenerator::generate (sema::BoundRootNode & root)
Definition at line 161 of file ir_generator.cpp.
{
  module_ = std::make_unique<Module>("zap_module");
  globalSymbolMap_.clear();
  root.accept(*this);
  return std::move(module_);
}
References sema::BoundRootNode::accept(), globalSymbolMap_, and module_.
Referenced by zap::generateZIRModule().
lowerConstantExpression() [1/2]
std::shared_ptr< Value > zir::BoundIRGenerator::lowerConstantExpression (const sema::BoundExpression & expression) private
Definition at line 42 of file ir_generator.cpp.
{
  std::set<const sema::VariableSymbol *> resolvingConstants;
  return lowerConstantExpression(expression, resolvingConstants);
}
References lowerConstantExpression().
Referenced by lowerConstantExpression(), lowerConstantExpression(), and visit().
lowerConstantExpression() [2/2]
std::shared_ptr< Value > zir::BoundIRGenerator::lowerConstantExpression (const sema::BoundExpression & expression, std::set< const sema::VariableSymbol * > & resolvingConstants) private
Definition at line 48 of file ir_generator.cpp.
{
  if (auto unary =
          dynamic_cast<const sema::BoundUnaryExpression *>(&expression)) {
    if (unary->op != "&") {
      return nullptr;
    }
    if (auto variable = dynamic_cast<const sema::BoundVariableExpression *>(
            unary->expr.get())) {
      return std::make_shared<GlobalAddress>(variable->symbol->linkName,
                                             unary->type);
    }
    if (auto index =
            dynamic_cast<const sema::BoundIndexAccess *>(unary->expr.get())) {
      auto variable = dynamic_cast<const sema::BoundVariableExpression *>(
          index->left.get());
      auto indexValue =
          lowerConstantExpression(*index->index, resolvingConstants);
      auto constantIndex = std::dynamic_pointer_cast<Constant>(indexValue);
      if (!variable || !constantIndex) {
        return nullptr;
      }
      try {
        return std::make_shared<GlobalAddress>(
            variable->symbol->linkName, unary->type,
            static_cast<size_t>(std::stoull(constantIndex->getLiteral())));
      } catch (const std::exception &) {
        return nullptr;
      }
    }
    return nullptr;
  }
  if (auto literal = dynamic_cast<const sema::BoundLiteral *>(&expression)) {
    return std::make_shared<Constant>(literal->value, literal->type);
  }
  if (auto variable =
          dynamic_cast<const sema::BoundVariableExpression *>(&expression)) {
    auto symbol = variable->symbol;
    if (symbol && symbol->is_const && symbol->constant_value) {
      if (!resolvingConstants.insert(symbol.get()).second) {
        return nullptr;
      }
      auto value =
          lowerConstantExpression(*symbol->constant_value, resolvingConstants);
      resolvingConstants.erase(symbol.get());
      return value;
    }
    return nullptr;
  }
  if (auto array = dynamic_cast<const sema::BoundArrayLiteral *>(&expression)) {
    std::vector<std::shared_ptr<Value>> elements;
    elements.reserve(array->elements.size());
    for (const auto &element : array->elements) {
      auto value = lowerConstantExpression(*element, resolvingConstants);
      if (!value) {
        return nullptr;
      }
      elements.push_back(std::move(value));
    }
    return std::make_shared<ArrayConstant>(array->type, std::move(elements));
  }
  if (auto cast = dynamic_cast<const sema::BoundCast *>(&expression)) {
    auto value = lowerConstantExpression(*cast->expression, resolvingConstants);
    if (auto constant = std::dynamic_pointer_cast<Constant>(value)) {
      return std::make_shared<Constant>(constant->getLiteral(), cast->type);
    }
    return value;
  }
  return nullptr;
}
References lowerConstantExpression().
visit() [1/40]
void zir::BoundIRGenerator::visit (sema::BoundArrayLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 901 of file ir_generator.cpp.
{
  auto arrayType = std::static_pointer_cast<zir::ArrayType>(node.type);
  auto allocaReg = createRegister(std::make_shared<PointerType>(arrayType));
  currentBlock_->addInstruction(
      std::make_unique<AllocaInst>(allocaReg, arrayType));
  for (size_t i = 0; i < node.elements.size(); ++i) {
    node.elements[i]->accept(*this);
    auto value = std::move(valueStack_.top());
    valueStack_.pop();
    auto elementAddr =
        createRegister(std::make_shared<PointerType>(arrayType->getBaseType()));
    currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
        elementAddr, allocaReg, static_cast<int>(i)));
    currentBlock_->addInstruction(
        std::make_unique<StoreInst>(value, elementAddr));
  }
  auto result = createRegister(arrayType);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(result, allocaReg));
  valueStack_.push(result);
}
References createRegister(), currentBlock_, sema::BoundArrayLiteral::elements, sema::BoundExpression::type, and valueStack_.
visit() [2/40]
void zir::BoundIRGenerator::visit (sema::BoundAsmStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1579 of file ir_generator.cpp.
{
  std::vector<AsmOperand> outputs;
  for (auto &operand : node.outputs) {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ = true;
    operand.expr->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    auto addr = valueStack_.top();
    valueStack_.pop();
    outputs.push_back({operand.constraint, addr, operand.expr->type});
  }
  std::vector<AsmOperand> inputs;
  for (auto &operand : node.inputs) {
    operand.expr->accept(*this);
    auto value = valueStack_.top();
    valueStack_.pop();
    inputs.push_back({operand.constraint, value, operand.expr->type});
  }
  currentBlock_->addInstruction(std::make_unique<InlineAsmInst>(
      node.assembly, std::move(outputs), std::move(inputs), node.clobbers));
}
References sema::BoundAsmStatement::assembly, sema::BoundAsmStatement::clobbers, currentBlock_, evaluateAsAddress_, sema::BoundAsmStatement::inputs, sema::BoundAsmStatement::outputs, and valueStack_.
visit() [3/40]
void zir::BoundIRGenerator::visit (sema::BoundAssignment & node) override virtual
Implements sema::BoundVisitor.
Definition at line 432 of file ir_generator.cpp.
{
  bool oldEvaluateAsAddress = evaluateAsAddress_;
  evaluateAsAddress_ = true;
  node.target->accept(*this);
  evaluateAsAddress_ = oldEvaluateAsAddress;
  auto target = valueStack_.top();
  valueStack_.pop();
  auto oldCompoundTargetAddr = compoundTargetAddr_;
  if (node.isCompound)
    compoundTargetAddr_ = target;
  node.expression->accept(*this);
  auto val = valueStack_.top();
  valueStack_.pop();
  compoundTargetAddr_ = oldCompoundTargetAddr;
  currentBlock_->addInstruction(std::make_unique<StoreInst>(val, target));
}
References compoundTargetAddr_, currentBlock_, evaluateAsAddress_, sema::BoundAssignment::expression, sema::BoundAssignment::isCompound, sema::BoundAssignment::target, and valueStack_.
visit() [4/40]
void zir::BoundIRGenerator::visit (sema::BoundBinaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 507 of file ir_generator.cpp.
{
  if (node.op == "&&") {
    auto rhsLabel = createBlockLabel("and.rhs");
    auto mergeLabel = createBlockLabel("and.merge");
    node.left->accept(*this);
    auto leftVal = valueStack_.top();
    valueStack_.pop();
    std::string leftBlockLabel = currentBlock_->label;
    currentBlock_->addInstruction(
        std::make_unique<CondBranchInst>(leftVal, rhsLabel, mergeLabel));
    auto rhsBlock = std::make_unique<BasicBlock>(rhsLabel);
    auto *rhsBlockPtr = rhsBlock.get();
    currentFunction_->addBlock(std::move(rhsBlock));
    currentBlock_ = rhsBlockPtr;
    node.right->accept(*this);
    auto rightVal = valueStack_.top();
    valueStack_.pop();
    std::string actualRhsBlockLabel = currentBlock_->label;
    currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
    auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
    auto *mergeBlockPtr = mergeBlock.get();
    currentFunction_->addBlock(std::move(mergeBlock));
    currentBlock_ = mergeBlockPtr;
    auto res = createRegister(node.type);
    std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
    incoming.push_back(
        {leftBlockLabel, std::make_shared<Constant>("false", node.type)});
    incoming.push_back({actualRhsBlockLabel, rightVal});
    currentBlock_->addInstruction(std::make_unique<PhiInst>(res, incoming));
    valueStack_.push(res);
    return;
  }
  if (node.op == "||") {
    auto rhsLabel = createBlockLabel("or.rhs");
    auto mergeLabel = createBlockLabel("or.merge");
    node.left->accept(*this);
    auto leftVal = valueStack_.top();
    valueStack_.pop();
    std::string leftBlockLabel = currentBlock_->label;
    currentBlock_->addInstruction(
        std::make_unique<CondBranchInst>(leftVal, mergeLabel, rhsLabel));
    auto rhsBlock = std::make_unique<BasicBlock>(rhsLabel);
    auto *rhsBlockPtr = rhsBlock.get();
    currentFunction_->addBlock(std::move(rhsBlock));
    currentBlock_ = rhsBlockPtr;
    node.right->accept(*this);
    auto rightVal = valueStack_.top();
    valueStack_.pop();
    std::string actualRhsBlockLabel = currentBlock_->label;
    currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
    auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
    auto *mergeBlockPtr = mergeBlock.get();
    currentFunction_->addBlock(std::move(mergeBlock));
    currentBlock_ = mergeBlockPtr;
    auto res = createRegister(node.type);
    std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
    incoming.push_back(
        {leftBlockLabel, std::make_shared<Constant>("true", node.type)});
    incoming.push_back({actualRhsBlockLabel, rightVal});
    currentBlock_->addInstruction(std::make_unique<PhiInst>(res, incoming));
    valueStack_.push(res);
    return;
  }
  node.left->accept(*this);
  auto left = valueStack_.top();
  valueStack_.pop();
  node.right->accept(*this);
  auto right = valueStack_.top();
  valueStack_.pop();
  auto reg = createRegister(node.type);
  bool isUnsigned = node.left->type->isUnsigned();
  if (node.op == "==" || node.op == "!=" || node.op == "<" ||
      (node.op == ">") || (node.op == "<=") || (node.op == ">=")) {
    std::string pred;
    if (node.op == "==")
      pred = "eq";
    else if (node.op == "!=")
      pred = "ne";
    else if (node.op == "<")
      pred = isUnsigned ? "ult" : "slt";
    else if (node.op == ">")
      pred = isUnsigned ? "ugt" : "sgt";
    else if (node.op == "<=")
      pred = isUnsigned ? "ule" : "sle";
    else if (node.op == ">=")
      pred = isUnsigned ? "uge" : "sge";
    currentBlock_->addInstruction(
        std::make_unique<CmpInst>(pred, reg, left, right));
  } else {
    OpCode op;
    if (node.op == "+")
      op = OpCode::Add;
    else if (node.op == "-")
      op = OpCode::Sub;
    else if (node.op == "*")
      op = OpCode::Mul;
    else if (node.op == "/")
      op = isUnsigned ? OpCode::UDiv : OpCode::SDiv;
    else if (node.op == "%")
      op = isUnsigned ? OpCode::URem : OpCode::SRem;
    else if (node.op == "<<")
      op = OpCode::Shl;
    else if (node.op == ">>")
      op = isUnsigned ? OpCode::LShr : OpCode::AShr;
    else if (node.op == "&")
      op = OpCode::BitAnd;
    else if (node.op == "|")
      op = OpCode::BitOr;
    else if (node.op == "^")
      op = OpCode::BitXor;
    else
      op = OpCode::Add;
    currentBlock_->addInstruction(
        std::make_unique<BinaryInst>(op, reg, left, right));
  }
  valueStack_.push(reg);
}
References zir::Add, zir::AShr, zir::BitAnd, zir::BitOr, zir::BitXor, createBlockLabel(), createRegister(), currentBlock_, currentFunction_, sema::BoundBinaryExpression::left, zir::LShr, zir::Mul, sema::BoundBinaryExpression::op, sema::BoundBinaryExpression::right, zir::SDiv, zir::Shl, zir::SRem, zir::Sub, sema::BoundExpression::type, zir::UDiv, zir::URem, and valueStack_.
visit() [5/40]
void zir::BoundIRGenerator::visit (sema::BoundBlock & node) override virtual
Implements sema::BoundVisitor.
Definition at line 264 of file ir_generator.cpp.
{
  std::vector<std::shared_ptr<sema::VariableSymbol>> blockClassLocals;
  for (const auto &stmt : node.statements) {
    stmt->accept(*this);
    if (currentFunction_) {
      if (auto *varDecl =
              dynamic_cast<sema::BoundVariableDeclaration *>(stmt.get())) {
        if (varDecl->symbol->type &&
            varDecl->symbol->type->getKind() == TypeKind::Class) {
          blockClassLocals.push_back(varDecl->symbol);
        }
      }
    }
  }
  if (node.result) {
    node.result->accept(*this);
  }
  if (currentFunction_ && currentBlock_ &&
      (currentBlock_->instructions.empty() ||
       (currentBlock_->instructions.back()->getOpCode() != OpCode::Ret &&
        currentBlock_->instructions.back()->getOpCode() != OpCode::Br &&
        currentBlock_->instructions.back()->getOpCode() != OpCode::CondBr))) {
    for (auto it = blockClassLocals.rbegin(); it != blockClassLocals.rend();
         ++it) {
      auto symbolIt = symbolMap_.find(*it);
      if (symbolIt == symbolMap_.end()) {
        continue;
      }
      currentBlock_->addInstruction(std::make_unique<StoreInst>(
          std::make_shared<Constant>("null", (*it)->type), symbolIt->second));
    }
  }
}
References zir::Br, zir::Class, zir::CondBr, currentBlock_, currentFunction_, sema::BoundBlock::result, zir::Ret, sema::BoundBlock::statements, and symbolMap_.
visit() [6/40]
void zir::BoundIRGenerator::visit (sema::BoundBreakStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1603 of file ir_generator.cpp.
{
  if (loopLabelStack_.empty()) {
    // Should have been diagnosed earlier in binder, but guard anyway
    return;
  }
  auto endLabel = loopLabelStack_.back().second;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(endLabel));
}
References currentBlock_, and loopLabelStack_.
visit() [7/40]
void zir::BoundIRGenerator::visit (sema::BoundCast & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1742 of file ir_generator.cpp.
{
  auto isArrayViewType = [](const std::shared_ptr<Type> &type) {
    return type && type->getKind() == TypeKind::Record &&
           std::static_pointer_cast<RecordType>(type)->getName().rfind(
               "__zap_varargs_", 0) == 0;
  };
  if (node.expression->type &&
      node.expression->type->getKind() == TypeKind::Array &&
      isArrayViewType(node.type)) {
    auto arrayType = std::static_pointer_cast<ArrayType>(node.expression->type);
    auto viewType = std::static_pointer_cast<RecordType>(node.type);
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ = true;
    node.expression->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    auto arrayAddr = valueStack_.top();
    valueStack_.pop();
    auto data =
        createRegister(std::make_shared<PointerType>(arrayType->getBaseType()));
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(data, arrayAddr, 0));
    auto viewAddr = createRegister(std::make_shared<PointerType>(node.type));
    currentBlock_->addInstruction(
        std::make_unique<AllocaInst>(viewAddr, node.type));
    auto dataFieldAddr = createRegister(
        std::make_shared<PointerType>(viewType->getFields()[0].type));
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(dataFieldAddr, viewAddr, 0));
    currentBlock_->addInstruction(
        std::make_unique<StoreInst>(data, dataFieldAddr));
    auto lenType = viewType->getFields()[1].type;
    auto lenFieldAddr = createRegister(std::make_shared<PointerType>(lenType));
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(lenFieldAddr, viewAddr, 1));
    currentBlock_->addInstruction(std::make_unique<StoreInst>(
        std::make_shared<Constant>(std::to_string(arrayType->getSize()),
                                   lenType),
        lenFieldAddr));
    auto result = createRegister(node.type);
    currentBlock_->addInstruction(std::make_unique<LoadInst>(result, viewAddr));
    valueStack_.push(result);
    return;
  }
  node.expression->accept(*this);
  auto src = valueStack_.top();
  valueStack_.pop();
  // Global initializers are lowered as constants only. Fold casted constants
  // immediately to the target type so LLVM sees a correctly-typed initializer.
  if (!currentFunction_ || !currentBlock_) {
    if (auto c = std::dynamic_pointer_cast<Constant>(src)) {
      auto folded = c->getLiteral();
      auto srcTy = c->getType();
      auto dstTy = node.type;
      if (srcTy && dstTy && srcTy->isInteger() && dstTy->isInteger()) {
        try {
          if (dstTy->isUnsigned()) {
            auto v = static_cast<uint64_t>(std::stoull(folded, nullptr, 0));
            folded = std::to_string(v);
          } else {
            auto v = static_cast<int64_t>(std::stoll(folded, nullptr, 0));
            folded = std::to_string(v);
          }
        } catch (...) {
          // Keep original literal when parsing fails.
        }
      } else if (srcTy && dstTy && srcTy->isFloatingPoint() &&
                 dstTy->isFloatingPoint()) {
        try {
          auto v = std::stod(folded);
          folded = std::to_string(v);
        } catch (...) {
          // Keep original literal when parsing fails.
        }
      } else if (srcTy && dstTy && srcTy->isInteger() &&
                 dstTy->isFloatingPoint()) {
        try {
          if (srcTy->isUnsigned()) {
            auto v = static_cast<double>(std::stoull(folded, nullptr, 0));
            folded = std::to_string(v);
          } else {
            auto v = static_cast<double>(std::stoll(folded, nullptr, 0));
            folded = std::to_string(v);
          }
        } catch (...) {
          // Keep original literal when parsing fails.
        }
      } else if (srcTy && dstTy && srcTy->isFloatingPoint() &&
                 dstTy->isInteger()) {
        try {
          double v = std::stod(folded);
          if (dstTy->isUnsigned()) {
            auto out = static_cast<uint64_t>(v);
            folded = std::to_string(out);
          } else {
            auto out = static_cast<int64_t>(v);
            folded = std::to_string(out);
          }
        } catch (...) {
          // Keep original literal when parsing fails.
        }
      }
      valueStack_.push(std::make_shared<Constant>(folded, node.type));
      return;
    }
    valueStack_.push(src);
    return;
  }
  auto res = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<CastInst>(res, src, node.type));
  valueStack_.push(res);
}
References zir::Array, createRegister(), currentBlock_, currentFunction_, evaluateAsAddress_, sema::BoundCast::expression, zir::Record, sema::BoundExpression::type, and valueStack_.
visit() [8/40]
void zir::BoundIRGenerator::visit (sema::BoundCompoundTargetLoad & node) override virtual
Implements sema::BoundVisitor.
Definition at line 452 of file ir_generator.cpp.
{
  auto reg = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<LoadInst>(reg, compoundTargetAddr_));
  valueStack_.push(reg);
}
References compoundTargetAddr_, createRegister(), currentBlock_, sema::BoundExpression::type, and valueStack_.
visit() [9/40]
void zir::BoundIRGenerator::visit (sema::BoundContinueStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1612 of file ir_generator.cpp.
{
  if (loopLabelStack_.empty()) {
    return;
  }
  auto condLabel = loopLabelStack_.back().first;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(condLabel));
}
References currentBlock_, and loopLabelStack_.
visit() [10/40]
void zir::BoundIRGenerator::visit (sema::BoundEnumDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 929 of file ir_generator.cpp.
{
  module_->addType(node.type);
}
References module_, and sema::BoundEnumDeclaration::type.
visit() [11/40]
void zir::BoundIRGenerator::visit (sema::BoundExpressionStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 459 of file ir_generator.cpp.
{
  node.expression->accept(*this);
  if (!valueStack_.empty())
    valueStack_.pop();
}
References sema::BoundExpressionStatement::expression, and valueStack_.
visit() [12/40]
void zir::BoundIRGenerator::visit (sema::BoundExternalFunctionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 243 of file ir_generator.cpp.
{
  auto symbol = node.symbol;
  auto func = std::make_unique<Function>(
      symbol->linkName, symbol->returnType, symbol->ownerTypeName,
      symbol->isDestructor, symbol->vtableSlot, symbol->isCVariadic);
  func->returnsRef = symbol->returnsRef;
  for (const auto &paramSymbol : symbol->parameters) {
    auto argType = paramSymbol->is_ref
                       ? std::static_pointer_cast<Type>(
                             std::make_shared<PointerType>(paramSymbol->type))
                       : paramSymbol->type;
    auto arg = std::make_shared<Argument>(
        paramSymbol->name, argType, paramSymbol->is_ref,
        paramSymbol->is_variadic_pack, paramSymbol->variadic_element_type);
    func->arguments.push_back(arg);
  }
  module_->addExternalFunction(std::move(func));
}
References module_, and sema::BoundExternalFunctionDeclaration::symbol.
visit() [13/40]
void zir::BoundIRGenerator::visit (sema::BoundFailableHandleExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1334 of file ir_generator.cpp.
{
  node.expression->accept(*this);
  if (valueStack_.empty()) {
    return;
  }
  auto failableValue = valueStack_.top();
  valueStack_.pop();
  auto okValue = emitFailableOk(failableValue);
  auto successLabel = createBlockLabel("orerr.ok");
  auto handlerLabel = createBlockLabel("orerr.handler");
  auto mergeLabel = createBlockLabel("orerr.merge");
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(okValue, successLabel, handlerLabel));
  auto successBlock = std::make_unique<BasicBlock>(successLabel);
  auto *successBlockPtr = successBlock.get();
  currentFunction_->addBlock(std::move(successBlock));
  currentBlock_ = successBlockPtr;
  auto successValue = emitFailableValue(failableValue);
  std::string successFrom = currentBlock_->label;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto handlerBlock = std::make_unique<BasicBlock>(handlerLabel);
  auto *handlerBlockPtr = handlerBlock.get();
  currentFunction_->addBlock(std::move(handlerBlock));
  currentBlock_ = handlerBlockPtr;
  auto errValue = emitFailableError(failableValue);
  if (node.errorSymbol) {
    auto errAlloca =
        createRegister(std::make_shared<PointerType>(node.errorSymbol->type));
    currentBlock_->addInstruction(
        std::make_unique<AllocaInst>(errAlloca, node.errorSymbol->type));
    currentBlock_->addInstruction(
        std::make_unique<StoreInst>(errValue, errAlloca));
    symbolMap_[node.errorSymbol] = errAlloca;
  }
  if (node.handler) {
    node.handler->accept(*this);
  }
  bool resultIsVoid = node.type && node.type->getKind() == TypeKind::Void;
  std::shared_ptr<Value> handlerValue = nullptr;
  if (node.handler && node.handler->result) {
    handlerValue = valueStack_.top();
    valueStack_.pop();
  } else {
    handlerValue = std::make_shared<Constant>("0", node.type);
  }
  bool handlerReachesMerge =
      currentBlock_->instructions.empty() ||
      currentBlock_->instructions.back()->getOpCode() != OpCode::Ret;
  std::string handlerFrom = currentBlock_->label;
  if (handlerReachesMerge) {
    currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  }
  auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
  auto *mergeBlockPtr = mergeBlock.get();
  currentFunction_->addBlock(std::move(mergeBlock));
  currentBlock_ = mergeBlockPtr;
  if (!handlerReachesMerge) {
    valueStack_.push(resultIsVoid ? std::make_shared<Constant>("0", node.type)
                                  : successValue);
    return;
  }
  if (resultIsVoid) {
    valueStack_.push(std::make_shared<Constant>("0", node.type));
    return;
  }
  auto result = createRegister(node.type);
  std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
  incoming.push_back({successFrom, successValue});
  incoming.push_back({handlerFrom, handlerValue});
  currentBlock_->addInstruction(std::make_unique<PhiInst>(result, incoming));
  valueStack_.push(result);
}
References createBlockLabel(), createRegister(), currentBlock_, currentFunction_, emitFailableError(), emitFailableOk(), emitFailableValue(), sema::BoundFailableHandleExpression::errorSymbol, sema::BoundFailableHandleExpression::expression, sema::BoundFailableHandleExpression::handler, zir::Ret, symbolMap_, sema::BoundExpression::type, valueStack_, and zir::Void.
visit() [14/40]
void zir::BoundIRGenerator::visit (sema::BoundFailStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 376 of file ir_generator.cpp.
{
  if (!currentFunction_) {
    return;
  }
  std::shared_ptr<Value> errValue = nullptr;
  if (node.errorExpression) {
    node.errorExpression->accept(*this);
    errValue = valueStack_.top();
    valueStack_.pop();
  }
  auto failableType = node.propagatedType;
  auto failableLayout = getFailableTypeLayout(failableType);
  auto valueType = failableLayout ? failableLayout->valueType : nullptr;
  auto errorType = failableLayout ? failableLayout->errorType : nullptr;
  auto allocaReg = createRegister(std::make_shared<PointerType>(failableType));
  currentBlock_->addInstruction(
      std::make_unique<AllocaInst>(allocaReg, failableType));
  auto okAddr = createRegister(std::make_shared<PointerType>(
      std::make_shared<PrimitiveType>(TypeKind::Bool)));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      okAddr, allocaReg, FailableTypeLayout::OkField));
  currentBlock_->addInstruction(std::make_unique<StoreInst>(
      std::make_shared<Constant>(
          "false", std::make_shared<PrimitiveType>(TypeKind::Bool)),
      okAddr));
  auto valueAddr = createRegister(std::make_shared<PointerType>(valueType));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      valueAddr, allocaReg, FailableTypeLayout::ValueField));
  if (valueType && valueType->getKind() != TypeKind::Void) {
    // The value field is unused on the error path; zero it without ARC.
    currentBlock_->addInstruction(std::make_unique<StoreInst>(
        std::make_shared<Constant>("0", valueType), valueAddr,
        /*bypassArc=*/true));
  }
  auto errAddr = createRegister(std::make_shared<PointerType>(errorType));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      errAddr, allocaReg, FailableTypeLayout::ErrorField));
  if (errValue) {
    currentBlock_->addInstruction(
        std::make_unique<StoreInst>(errValue, errAddr));
  } else {
    currentBlock_->addInstruction(std::make_unique<StoreInst>(
        std::make_shared<Constant>("0", errorType), errAddr));
  }
  auto loaded = createRegister(failableType);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(loaded, allocaReg));
  currentBlock_->addInstruction(std::make_unique<ReturnInst>(loaded));
}
References zir::Bool, createRegister(), currentBlock_, currentFunction_, sema::BoundFailStatement::errorExpression, zir::FailableTypeLayout::ErrorField, zir::getFailableTypeLayout(), zir::FailableTypeLayout::OkField, sema::BoundFailStatement::propagatedType, zir::FailableTypeLayout::ValueField, valueStack_, and zir::Void.
visit() [15/40]
void zir::BoundIRGenerator::visit (sema::BoundFallbackExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1280 of file ir_generator.cpp.
{
  node.expression->accept(*this);
  if (valueStack_.empty()) {
    return;
  }
  auto failableValue = valueStack_.top();
  valueStack_.pop();
  auto okValue = emitFailableOk(failableValue);
  auto successLabel = createBlockLabel("or.ok");
  auto fallbackLabel = createBlockLabel("or.fallback");
  auto mergeLabel = createBlockLabel("or.merge");
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(okValue, successLabel, fallbackLabel));
  auto successBlock = std::make_unique<BasicBlock>(successLabel);
  auto *successBlockPtr = successBlock.get();
  currentFunction_->addBlock(std::move(successBlock));
  currentBlock_ = successBlockPtr;
  auto successValue = emitFailableValue(failableValue);
  std::string successFrom = currentBlock_->label;
  bool resultIsVoid = node.type && node.type->getKind() == TypeKind::Void;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto fallbackBlock = std::make_unique<BasicBlock>(fallbackLabel);
  auto *fallbackBlockPtr = fallbackBlock.get();
  currentFunction_->addBlock(std::move(fallbackBlock));
  currentBlock_ = fallbackBlockPtr;
  node.fallback->accept(*this);
  auto fallbackValue = valueStack_.top();
  valueStack_.pop();
  std::string fallbackFrom = currentBlock_->label;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
  auto *mergeBlockPtr = mergeBlock.get();
  currentFunction_->addBlock(std::move(mergeBlock));
  currentBlock_ = mergeBlockPtr;
  if (resultIsVoid) {
    valueStack_.push(std::make_shared<Constant>("0", node.type));
    return;
  }
  auto result = createRegister(node.type);
  std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
  incoming.push_back({successFrom, successValue});
  incoming.push_back({fallbackFrom, fallbackValue});
  currentBlock_->addInstruction(std::make_unique<PhiInst>(result, incoming));
  valueStack_.push(result);
}
References createBlockLabel(), createRegister(), currentBlock_, currentFunction_, emitFailableOk(), emitFailableValue(), sema::BoundFallbackExpression::expression, sema::BoundFallbackExpression::fallback, sema::BoundExpression::type, valueStack_, and zir::Void.
visit() [16/40]
void zir::BoundIRGenerator::visit (sema::BoundForStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1515 of file ir_generator.cpp.
{
  if (node.initializer) {
    if (auto *initBlock =
            dynamic_cast<sema::BoundBlock *>(node.initializer.get())) {
      for (const auto &stmt : initBlock->statements) {
        if (stmt) {
          stmt->accept(*this);
        }
      }
    } else {
      node.initializer->accept(*this);
    }
  }
  auto condLabel = createBlockLabel("for.cond");
  auto bodyLabel = createBlockLabel("for.body");
  auto stepLabel = createBlockLabel("for.step");
  auto endLabel = createBlockLabel("for.end");
  currentBlock_->addInstruction(std::make_unique<BranchInst>(condLabel));
  auto condBlock = std::make_unique<BasicBlock>(condLabel);
  auto *condBlockPtr = condBlock.get();
  currentFunction_->addBlock(std::move(condBlock));
  currentBlock_ = condBlockPtr;
  node.condition->accept(*this);
  auto cond = valueStack_.top();
  valueStack_.pop();
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(cond, bodyLabel, endLabel));
  auto bodyBlock = std::make_unique<BasicBlock>(bodyLabel);
  auto *bodyBlockPtr = bodyBlock.get();
  currentFunction_->addBlock(std::move(bodyBlock));
  currentBlock_ = bodyBlockPtr;
  loopLabelStack_.push_back({stepLabel, endLabel});
  if (node.body) {
    node.body->accept(*this);
  }
  loopLabelStack_.pop_back();
  if (currentBlock_->instructions.empty() ||
      currentBlock_->instructions.back()->getOpCode() != OpCode::Ret) {
    currentBlock_->addInstruction(std::make_unique<BranchInst>(stepLabel));
  }
  auto stepBlock = std::make_unique<BasicBlock>(stepLabel);
  auto *stepBlockPtr = stepBlock.get();
  currentFunction_->addBlock(std::move(stepBlock));
  currentBlock_ = stepBlockPtr;
  if (node.increment) {
    node.increment->accept(*this);
  }
  if (currentBlock_->instructions.empty() ||
      currentBlock_->instructions.back()->getOpCode() != OpCode::Ret) {
    currentBlock_->addInstruction(std::make_unique<BranchInst>(condLabel));
  }
  auto endBlock = std::make_unique<BasicBlock>(endLabel);
  auto *endBlockPtr = endBlock.get();
  currentFunction_->addBlock(std::move(endBlock));
  currentBlock_ = endBlockPtr;
}
References sema::BoundForStatement::body, sema::BoundForStatement::condition, createBlockLabel(), currentBlock_, currentFunction_, sema::BoundForStatement::increment, sema::BoundForStatement::initializer, loopLabelStack_, zir::Ret, and valueStack_.
visit() [17/40]
void zir::BoundIRGenerator::visit (sema::BoundFunctionCall & node) override virtual
Implements sema::BoundVisitor.
Definition at line 692 of file ir_generator.cpp.
{
  std::vector<std::shared_ptr<Value>> args;
  for (size_t i = 0; i < node.arguments.size(); ++i) {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ =
        (i < node.argumentIsRef.size() && node.argumentIsRef[i]);
    node.arguments[i]->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    args.push_back(valueStack_.top());
    valueStack_.pop();
  }
  std::shared_ptr<Value> variadicPack = nullptr;
  if (node.variadicPack) {
    node.variadicPack->accept(*this);
    variadicPack = valueStack_.top();
    valueStack_.pop();
  }
  // ref-returning functions return a pointer in LLVM IR
  auto resultType = node.symbol->returnsRef
                        ? std::static_pointer_cast<zir::Type>(
                              std::make_shared<PointerType>(node.type))
                        : node.type;
  auto reg = createRegister(resultType);
  currentBlock_->addInstruction(std::make_unique<CallInst>(
      reg, node.symbol->linkName, args, node.argumentIsRef, variadicPack,
      node.symbol->returnsRef));
  // If ref-returning function is used as value (not address), load it
  if (node.symbol->returnsRef && !evaluateAsAddress_) {
    auto loadReg = createRegister(node.type);
    currentBlock_->addInstruction(std::make_unique<LoadInst>(loadReg, reg));
    valueStack_.push(loadReg);
  } else {
    valueStack_.push(reg);
  }
}
References sema::BoundFunctionCall::argumentIsRef, sema::BoundFunctionCall::arguments, createRegister(), currentBlock_, evaluateAsAddress_, sema::BoundFunctionCall::symbol, sema::BoundExpression::type, valueStack_, and sema::BoundFunctionCall::variadicPack.
visit() [18/40]
void zir::BoundIRGenerator::visit (sema::BoundFunctionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 189 of file ir_generator.cpp.
{
  auto symbol = node.symbol;
  auto func = std::make_unique<Function>(
      symbol->linkName, symbol->returnType, symbol->ownerTypeName,
      symbol->isDestructor, symbol->vtableSlot, symbol->isCVariadic);
  func->returnsRef = symbol->returnsRef;
  currentFunction_ = func.get();
  auto entryBlock = std::make_unique<BasicBlock>("entry");
  currentBlock_ = entryBlock.get();
  currentFunction_->addBlock(std::move(entryBlock));
  for (const auto &paramSymbol : symbol->parameters) {
    auto argType = paramSymbol->is_ref
                       ? std::static_pointer_cast<Type>(
                             std::make_shared<PointerType>(paramSymbol->type))
                       : paramSymbol->type;
    auto arg = std::make_shared<Argument>(
        paramSymbol->name, argType, paramSymbol->is_ref,
        paramSymbol->is_variadic_pack, paramSymbol->variadic_element_type);
    currentFunction_->arguments.push_back(arg);
    auto spillType = paramSymbol->is_ref
                         ? std::make_shared<PointerType>(paramSymbol->type)
                         : paramSymbol->type;
    auto allocaReg = createRegister(std::make_shared<PointerType>(spillType));
    currentBlock_->addInstruction(
        std::make_unique<AllocaInst>(allocaReg, spillType));
    currentBlock_->addInstruction(std::make_unique<StoreInst>(arg, allocaReg));
    symbolMap_[paramSymbol] = allocaReg;
  }
  if (node.body) {
    node.body->accept(*this);
  }
  if (currentBlock_ &&
      (currentBlock_->instructions.empty() ||
       currentBlock_->instructions.back()->getOpCode() != OpCode::Ret)) {
    if (symbol->returnType->getKind() == TypeKind::Void) {
      currentBlock_->addInstruction(std::make_unique<ReturnInst>());
    } else {
      auto dummy = std::make_shared<Constant>("0", symbol->returnType);
      currentBlock_->addInstruction(std::make_unique<ReturnInst>(dummy));
    }
  }
  module_->addFunction(std::move(func));
  currentFunction_ = nullptr;
  currentBlock_ = nullptr;
  symbolMap_.clear();
}
References sema::BoundFunctionDeclaration::body, createRegister(), currentBlock_, currentFunction_, module_, zir::Ret, sema::BoundFunctionDeclaration::symbol, symbolMap_, and zir::Void.
visit() [19/40]
void zir::BoundIRGenerator::visit (sema::BoundFunctionReference & node) override virtual
Implements sema::BoundVisitor.
Definition at line 731 of file ir_generator.cpp.
{
  // Represent as a Global value pointing to the function
  auto fnGlobal = std::make_shared<Global>(
      node.symbol->linkName, node.symbol->linkName, node.type, nullptr, true);
  valueStack_.push(fnGlobal);
}
References sema::BoundFunctionReference::symbol, sema::BoundExpression::type, and valueStack_.
visit() [20/40]
void zir::BoundIRGenerator::visit (sema::BoundIfStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1425 of file ir_generator.cpp.
{
  auto trueLabel = createBlockLabel("if.then");
  auto falseLabel = node.elseBody ? createBlockLabel("if.else") : "";
  auto mergeLabel = createBlockLabel("if.merge");
  node.condition->accept(*this);
  auto cond = valueStack_.top();
  valueStack_.pop();
  if (node.elseBody) {
    currentBlock_->addInstruction(
        std::make_unique<CondBranchInst>(cond, trueLabel, falseLabel));
  } else {
    currentBlock_->addInstruction(
        std::make_unique<CondBranchInst>(cond, trueLabel, mergeLabel));
  }
  auto thenBlock = std::make_unique<BasicBlock>(trueLabel);
  auto *thenBlockPtr = thenBlock.get();
  currentFunction_->addBlock(std::move(thenBlock));
  currentBlock_ = thenBlockPtr;
  if (node.thenBody)
    node.thenBody->accept(*this);
  std::string actualThenLabel = currentBlock_->label;
  if (currentBlock_->instructions.empty() ||
      currentBlock_->instructions.back()->getOpCode() != OpCode::Ret) {
    currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  }
  std::string actualElseLabel = "";
  if (node.elseBody) {
    auto elseBlock = std::make_unique<BasicBlock>(falseLabel);
    auto *elseBlockPtr = elseBlock.get();
    currentFunction_->addBlock(std::move(elseBlock));
    currentBlock_ = elseBlockPtr;
    node.elseBody->accept(*this);
    actualElseLabel = currentBlock_->label;
    if (currentBlock_->instructions.empty() ||
        currentBlock_->instructions.back()->getOpCode() != OpCode::Ret) {
      currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
    }
  }
  auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
  auto *mergeBlockPtr = mergeBlock.get();
  currentFunction_->addBlock(std::move(mergeBlock));
  currentBlock_ = mergeBlockPtr;
}
References sema::BoundIfStatement::condition, createBlockLabel(), currentBlock_, currentFunction_, sema::BoundIfStatement::elseBody, zir::Ret, sema::BoundIfStatement::thenBody, and valueStack_.
visit() [21/40]
void zir::BoundIRGenerator::visit (sema::BoundIndexAccess & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1640 of file ir_generator.cpp.
{
  if (node.left->type->getKind() == zir::TypeKind::Record) {
    auto recordType =
        std::static_pointer_cast<zir::RecordType>(node.left->type);
    if (zap::text::isStringRecordName(recordType->getName())) {
      if (evaluateAsAddress_) {
        throw std::runtime_error("String index access is not assignable.");
      }
      node.left->accept(*this);
      auto stringValue = valueStack_.top();
      valueStack_.pop();
      node.index->accept(*this);
      auto indexValue = valueStack_.top();
      valueStack_.pop();
      auto result = createRegister(node.type);
      currentBlock_->addInstruction(std::make_unique<CallInst>(
          result, "at",
          std::vector<std::shared_ptr<Value>>{stringValue, indexValue}));
      valueStack_.push(result);
      return;
    }
    if (recordType->getName().rfind("__zap_varargs_", 0) == 0) {
      bool oldEvaluateAsAddress = evaluateAsAddress_;
      evaluateAsAddress_ = true;
      node.left->accept(*this);
      evaluateAsAddress_ = oldEvaluateAsAddress;
      auto sliceAddr = valueStack_.top();
      valueStack_.pop();
      bool oldIndexEvaluateAsAddress = evaluateAsAddress_;
      evaluateAsAddress_ = false;
      node.index->accept(*this);
      evaluateAsAddress_ = oldIndexEvaluateAsAddress;
      auto indexValue = valueStack_.top();
      valueStack_.pop();
      auto elemType = std::static_pointer_cast<zir::PointerType>(
                          recordType->getFields()[0].type)
                          ->getBaseType();
      auto dataAddr = createRegister(recordType->getFields()[0].type);
      currentBlock_->addInstruction(
          std::make_unique<GetElementPtrInst>(dataAddr, sliceAddr, 0));
      auto dataPtr = createRegister(recordType->getFields()[0].type);
      currentBlock_->addInstruction(
          std::make_unique<LoadInst>(dataPtr, dataAddr));
      auto elemAddr = createRegister(std::make_shared<PointerType>(elemType));
      currentBlock_->addInstruction(std::make_unique<BinaryInst>(
          OpCode::Add, elemAddr, dataPtr, indexValue));
      if (evaluateAsAddress_) {
        valueStack_.push(elemAddr);
      } else {
        auto res = createRegister(node.type);
        currentBlock_->addInstruction(
            std::make_unique<LoadInst>(res, elemAddr));
        valueStack_.push(res);
      }
      return;
    }
  }
  bool oldEvaluateAsAddress = evaluateAsAddress_;
  evaluateAsAddress_ = true;
  node.left->accept(*this);
  auto left = valueStack_.top();
  valueStack_.pop();
  evaluateAsAddress_ = false;
  node.index->accept(*this);
  auto indexVal = valueStack_.top();
  valueStack_.pop();
  evaluateAsAddress_ = oldEvaluateAsAddress;
  auto ptr = createRegister(std::make_shared<PointerType>(node.type));
  if (auto *c = dynamic_cast<Constant *>(indexVal.get())) {
    int idx = 0;
    try {
      idx = std::stoi(c->getName());
    } catch (...) {
    }
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(ptr, left, idx));
  } else {
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(ptr, left, indexVal));
  }
  if (evaluateAsAddress_) {
    valueStack_.push(ptr);
  } else {
    auto res = createRegister(node.type);
    currentBlock_->addInstruction(std::make_unique<LoadInst>(res, ptr));
    valueStack_.push(res);
  }
}
References zir::Add, createRegister(), currentBlock_, evaluateAsAddress_, sema::BoundIndexAccess::index, zap::text::isStringRecordName(), sema::BoundIndexAccess::left, zir::Record, sema::BoundExpression::type, and valueStack_.
visit() [22/40]
void zir::BoundIRGenerator::visit (sema::BoundIndirectCall & node) override virtual
Implements sema::BoundVisitor.
Definition at line 738 of file ir_generator.cpp.
{
  node.callee->accept(*this);
  auto calleeVal = valueStack_.top();
  valueStack_.pop();
  std::vector<std::shared_ptr<Value>> args;
  for (auto &arg : node.arguments) {
    arg->accept(*this);
    args.push_back(valueStack_.top());
    valueStack_.pop();
  }
  auto reg = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<CallInst>(reg, calleeVal, std::move(args)));
  valueStack_.push(reg);
}
References sema::BoundIndirectCall::arguments, sema::BoundIndirectCall::callee, createRegister(), currentBlock_, sema::BoundExpression::type, and valueStack_.
visit() [23/40]
void zir::BoundIRGenerator::visit (sema::BoundLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 465 of file ir_generator.cpp.
{
  valueStack_.push(std::make_shared<Constant>(node.value, node.type));
}
References sema::BoundExpression::type, sema::BoundLiteral::value, and valueStack_.
visit() [24/40]
void zir::BoundIRGenerator::visit (sema::BoundMemberAccess & node) override virtual
Implements sema::BoundVisitor.
Definition at line 937 of file ir_generator.cpp.
{
  if (node.left->type->getKind() == zir::TypeKind::Enum) {
    node.left->accept(*this);
    auto left = std::move(valueStack_.top());
    valueStack_.pop();
    auto enumType = std::static_pointer_cast<zir::EnumType>(left->getType());
    int64_t value = enumType->getVariantDiscriminant(node.member);
    if (value != -1) {
      valueStack_.push(std::make_shared<Constant>(
          std::to_string(value),
          std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int)));
      return;
    }
  }
  if (node.left->type->getKind() == zir::TypeKind::TaggedUnion &&
      node.member == "tag") {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ = true;
    node.left->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    auto left = std::move(valueStack_.top());
    valueStack_.pop();
    auto fieldAddr = createRegister(std::make_shared<PointerType>(
        std::make_shared<PrimitiveType>(TypeKind::Int32)));
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(fieldAddr, left, 0));
    if (evaluateAsAddress_) {
      valueStack_.push(fieldAddr);
    } else {
      auto result = createRegister(node.type);
      currentBlock_->addInstruction(
          std::make_unique<LoadInst>(result, fieldAddr));
      valueStack_.push(result);
    }
    return;
  }
  bool oldEvaluateAsAddress = evaluateAsAddress_;
  evaluateAsAddress_ = !(node.left->type->getKind() == zir::TypeKind::Class ||
                         node.left->type->getKind() == zir::TypeKind::Pointer);
  node.left->accept(*this);
  evaluateAsAddress_ = oldEvaluateAsAddress;
  auto left = std::move(valueStack_.top());
  valueStack_.pop();
  if (node.left->type->getKind() == zir::TypeKind::Class) {
    auto classType = std::static_pointer_cast<zir::ClassType>(node.left->type);
    int fieldIndex = -1;
    const auto &fields = classType->getFields();
    for (size_t i = 0; i < fields.size(); ++i) {
      if (fields[i].name == node.member) {
        fieldIndex = static_cast<int>(i);
        break;
      }
    }
    if (fieldIndex != -1) {
      auto fieldAddr = createRegister(
          std::make_shared<PointerType>(fields[fieldIndex].type));
      currentBlock_->addInstruction(
          std::make_unique<GetElementPtrInst>(fieldAddr, left, fieldIndex));
      if (evaluateAsAddress_) {
        valueStack_.push(fieldAddr);
      } else {
        auto result = createRegister(fields[fieldIndex].type);
        currentBlock_->addInstruction(
            std::make_unique<LoadInst>(result, fieldAddr));
        valueStack_.push(result);
      }
      return;
    }
  } else if (left->getType()->getKind() == zir::TypeKind::Pointer) {
    auto baseType = std::static_pointer_cast<zir::PointerType>(left->getType())
                        ->getBaseType();
    if (baseType->getKind() == zir::TypeKind::Class) {
      auto classType = std::static_pointer_cast<zir::ClassType>(baseType);
      int fieldIndex = -1;
      const auto &fields = classType->getFields();
      for (size_t i = 0; i < fields.size(); ++i) {
        if (fields[i].name == node.member) {
          fieldIndex = static_cast<int>(i);
          break;
        }
      }
      if (fieldIndex != -1) {
        auto fieldAddr = createRegister(
            std::make_shared<PointerType>(fields[fieldIndex].type));
        currentBlock_->addInstruction(
            std::make_unique<GetElementPtrInst>(fieldAddr, left, fieldIndex));
        if (evaluateAsAddress_) {
          valueStack_.push(fieldAddr);
        } else {
          auto result = createRegister(fields[fieldIndex].type);
          currentBlock_->addInstruction(
              std::make_unique<LoadInst>(result, fieldAddr));
          valueStack_.push(result);
        }
        return;
      }
    } else if (baseType->getKind() == zir::TypeKind::Record) {
      auto recordType = std::static_pointer_cast<zir::RecordType>(baseType);
      int fieldIndex = -1;
      const auto &fields = recordType->getFields();
      for (size_t i = 0; i < fields.size(); ++i) {
        if (fields[i].name == node.member) {
          fieldIndex = static_cast<int>(i);
          break;
        }
      }
      if (fieldIndex != -1) {
        auto fieldAddr = createRegister(
            std::make_shared<PointerType>(fields[fieldIndex].type));
        currentBlock_->addInstruction(
            std::make_unique<GetElementPtrInst>(fieldAddr, left, fieldIndex));
        if (evaluateAsAddress_) {
          valueStack_.push(fieldAddr);
        } else {
          auto result = createRegister(fields[fieldIndex].type);
          currentBlock_->addInstruction(
              std::make_unique<LoadInst>(result, fieldAddr));
          valueStack_.push(result);
        }
        return;
      }
    }
  } else if (left->getType()->getKind() == zir::TypeKind::Record) {
    auto recordType =
        std::static_pointer_cast<zir::RecordType>(left->getType());
    int fieldIndex = -1;
    const auto &fields = recordType->getFields();
    for (size_t i = 0; i < fields.size(); ++i) {
      if (fields[i].name == node.member) {
        fieldIndex = static_cast<int>(i);
        break;
      }
    }
    if (fieldIndex != -1) {
      auto fieldAddr = createRegister(
          std::make_shared<PointerType>(fields[fieldIndex].type));
      currentBlock_->addInstruction(
          std::make_unique<GetElementPtrInst>(fieldAddr, left, fieldIndex));
      if (evaluateAsAddress_) {
        valueStack_.push(fieldAddr);
      } else {
        auto result = createRegister(fields[fieldIndex].type);
        currentBlock_->addInstruction(
            std::make_unique<LoadInst>(result, fieldAddr));
        valueStack_.push(result);
      }
      return;
    }
  }
  throw std::runtime_error("IR member access failed: member '" + node.member +
                           "' not found in type '" +
                           renderTypeForUser(left->getType()) + "'");
}
References zir::Class, createRegister(), currentBlock_, zir::Enum, evaluateAsAddress_, zir::Int, zir::Int32, sema::BoundMemberAccess::left, sema::BoundMemberAccess::member, zir::Pointer, zir::Record, zir::TaggedUnion, sema::BoundExpression::type, and valueStack_.
visit() [25/40]
void zir::BoundIRGenerator::visit (sema::BoundModuleReference & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1420 of file ir_generator.cpp.
{
  (void)node;
  throw std::runtime_error("module reference reached ZIR generation");
}
visit() [26/40]
void zir::BoundIRGenerator::visit (sema::BoundNewExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1869 of file ir_generator.cpp.
{
  auto result = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<AllocInst>(result, node.classType));
  if (node.constructor) {
    std::vector<std::shared_ptr<Value>> args;
    args.push_back(result);
    for (size_t i = 0; i < node.arguments.size(); ++i) {
      bool oldEvaluateAsAddress = evaluateAsAddress_;
      if (i < node.argumentIsRef.size() && node.argumentIsRef[i]) {
        evaluateAsAddress_ = true;
      }
      node.arguments[i]->accept(*this);
      evaluateAsAddress_ = oldEvaluateAsAddress;
      args.push_back(valueStack_.top());
      valueStack_.pop();
    }
    currentBlock_->addInstruction(
        std::make_unique<CallInst>(nullptr, node.constructor->linkName, args));
  }
  valueStack_.push(result);
}
References sema::BoundNewExpression::argumentIsRef, sema::BoundNewExpression::arguments, sema::BoundNewExpression::classType, sema::BoundNewExpression::constructor, createRegister(), currentBlock_, evaluateAsAddress_, sema::BoundExpression::type, and valueStack_.
visit() [27/40]
void zir::BoundIRGenerator::visit (sema::BoundRecordDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 925 of file ir_generator.cpp.
{
  module_->addType(node.type);
}
References module_, and sema::BoundRecordDeclaration::type.
visit() [28/40]
void zir::BoundIRGenerator::visit (sema::BoundReturnStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 361 of file ir_generator.cpp.
{
  std::shared_ptr<Value> val = nullptr;
  if (node.expression) {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    if (node.returnsRef) {
      evaluateAsAddress_ = true;
    }
    node.expression->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    val = valueStack_.top();
    valueStack_.pop();
  }
  currentBlock_->addInstruction(std::make_unique<ReturnInst>(val));
}
References currentBlock_, evaluateAsAddress_, sema::BoundReturnStatement::expression, sema::BoundReturnStatement::returnsRef, and valueStack_.
visit() [29/40]
void zir::BoundIRGenerator::visit (sema::BoundRootNode & node) override virtual
Implements sema::BoundVisitor.
Definition at line 168 of file ir_generator.cpp.
{
  for (const auto &record : node.records) {
    record->accept(*this);
  }
  for (const auto &en : node.enums) {
    en->accept(*this);
  }
  for (const auto &taggedUnion : node.taggedUnions) {
    taggedUnion->accept(*this);
  }
  for (const auto &global : node.globals) {
    global->accept(*this);
  }
  for (const auto &extFunc : node.externalFunctions) {
    extFunc->accept(*this);
  }
  for (const auto &func : node.functions) {
    func->accept(*this);
  }
}
References sema::BoundRootNode::enums, sema::BoundRootNode::externalFunctions, sema::BoundRootNode::functions, sema::BoundRootNode::globals, sema::BoundRootNode::records, and sema::BoundRootNode::taggedUnions.
visit() [30/40]
void zir::BoundIRGenerator::visit (sema::BoundStructLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1101 of file ir_generator.cpp.
{
  auto recordType = std::static_pointer_cast<zir::RecordType>(node.type);
  // Global initializers are lowered as constants only.
  if (!currentFunction_ || !currentBlock_) {
    std::vector<AggregateConstant::FieldValue> aggregateFields;
    aggregateFields.reserve(node.fields.size());
    for (const auto &fieldInit : node.fields) {
      fieldInit.second->accept(*this);
      auto val = std::move(valueStack_.top());
      valueStack_.pop();
      aggregateFields.push_back({fieldInit.first, val});
    }
    valueStack_.push(std::make_shared<AggregateConstant>(
        node.type, std::move(aggregateFields)));
    return;
  }
  auto allocaReg = createRegister(std::make_shared<PointerType>(recordType));
  currentBlock_->addInstruction(
      std::make_unique<AllocaInst>(allocaReg, recordType));
  for (const auto &fieldInit : node.fields) {
    // Find field index
    int fieldIndex = -1;
    const auto &fields = recordType->getFields();
    for (size_t i = 0; i < fields.size(); ++i) {
      if (fields[i].name == fieldInit.first) {
        fieldIndex = static_cast<int>(i);
        break;
      }
    }
    fieldInit.second->accept(*this);
    auto val = std::move(valueStack_.top());
    valueStack_.pop();
    if (fields[fieldIndex].type &&
        fields[fieldIndex].type->getKind() != TypeKind::Void) {
      auto fieldAddr = createRegister(
          std::make_shared<PointerType>(fields[fieldIndex].type));
      currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
          fieldAddr, allocaReg, fieldIndex));
      currentBlock_->addInstruction(std::make_unique<StoreInst>(
          val, fieldAddr, /*bypassArc=*/false, /*initStore=*/true));
    }
  }
  auto result = createRegister(recordType);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(result, allocaReg));
  valueStack_.push(result);
}
References createRegister(), currentBlock_, currentFunction_, sema::BoundStructLiteral::fields, sema::BoundExpression::type, valueStack_, and zir::Void.
visit() [31/40]
void zir::BoundIRGenerator::visit (sema::BoundTaggedUnionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 933 of file ir_generator.cpp.
{
  module_->addType(node.type);
}
References module_, and sema::BoundTaggedUnionDeclaration::type.
visit() [32/40]
void zir::BoundIRGenerator::visit (sema::BoundTaggedUnionLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1156 of file ir_generator.cpp.
{
  auto taggedUnionType = std::static_pointer_cast<TaggedUnionType>(node.type);
  auto allocaReg =
      createRegister(std::make_shared<PointerType>(taggedUnionType));
  currentBlock_->addInstruction(
      std::make_unique<AllocaInst>(allocaReg, taggedUnionType));
  auto tagType = std::make_shared<PrimitiveType>(TypeKind::Int32);
  auto tagAddr = createRegister(std::make_shared<PointerType>(tagType));
  currentBlock_->addInstruction(
      std::make_unique<GetElementPtrInst>(tagAddr, allocaReg, 0));
  auto tagValue = std::make_shared<Constant>(std::to_string(node.tag), tagType);
  currentBlock_->addInstruction(std::make_unique<StoreInst>(
      tagValue, tagAddr, /*bypassArc=*/true, /*initStore=*/true));
  if (node.payload) {
    node.payload->accept(*this);
    auto payload = std::move(valueStack_.top());
    valueStack_.pop();
    auto payloadAddr =
        createRegister(std::make_shared<PointerType>(node.payload->type));
    currentBlock_->addInstruction(
        std::make_unique<GetElementPtrInst>(payloadAddr, allocaReg, 1));
    currentBlock_->addInstruction(std::make_unique<StoreInst>(
        payload, payloadAddr, /*bypassArc=*/false, /*initStore=*/true));
  }
  auto result = createRegister(taggedUnionType);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(result, allocaReg));
  valueStack_.push(result);
}
References createRegister(), currentBlock_, zir::Int32, sema::BoundTaggedUnionLiteral::payload, sema::BoundTaggedUnionLiteral::tag, sema::BoundExpression::type, and valueStack_.
visit() [33/40]
void zir::BoundIRGenerator::visit (sema::BoundTernaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 645 of file ir_generator.cpp.
{
  auto thenLabel = createBlockLabel("ternary.then");
  auto elseLabel = createBlockLabel("ternary.else");
  auto mergeLabel = createBlockLabel("ternary.merge");
  node.condition->accept(*this);
  auto condVal = valueStack_.top();
  valueStack_.pop();
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(condVal, thenLabel, elseLabel));
  auto thenBlock = std::make_unique<BasicBlock>(thenLabel);
  auto *thenBlockPtr = thenBlock.get();
  currentFunction_->addBlock(std::move(thenBlock));
  currentBlock_ = thenBlockPtr;
  node.thenExpr->accept(*this);
  auto thenVal = valueStack_.top();
  valueStack_.pop();
  std::string actualThenLabel = currentBlock_->label;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto elseBlock = std::make_unique<BasicBlock>(elseLabel);
  auto *elseBlockPtr = elseBlock.get();
  currentFunction_->addBlock(std::move(elseBlock));
  currentBlock_ = elseBlockPtr;
  node.elseExpr->accept(*this);
  auto elseVal = valueStack_.top();
  valueStack_.pop();
  std::string actualElseLabel = currentBlock_->label;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
  auto *mergeBlockPtr = mergeBlock.get();
  currentFunction_->addBlock(std::move(mergeBlock));
  currentBlock_ = mergeBlockPtr;
  auto res = createRegister(node.type);
  std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
  incoming.push_back({actualThenLabel, thenVal});
  incoming.push_back({actualElseLabel, elseVal});
  currentBlock_->addInstruction(std::make_unique<PhiInst>(res, incoming));
  valueStack_.push(res);
}
References sema::BoundTernaryExpression::condition, createBlockLabel(), createRegister(), currentBlock_, currentFunction_, sema::BoundTernaryExpression::elseExpr, sema::BoundTernaryExpression::thenExpr, sema::BoundExpression::type, and valueStack_.
visit() [34/40]
void zir::BoundIRGenerator::visit (sema::BoundTryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1188 of file ir_generator.cpp.
{
  node.expression->accept(*this);
  if (valueStack_.empty()) {
    return;
  }
  auto failableValue = valueStack_.top();
  valueStack_.pop();
  auto okValue = emitFailableOk(failableValue);
  auto successLabel = createBlockLabel("try.ok");
  auto failLabel = createBlockLabel("try.fail");
  auto mergeLabel = createBlockLabel("try.merge");
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(okValue, successLabel, failLabel));
  auto successBlock = std::make_unique<BasicBlock>(successLabel);
  auto *successBlockPtr = successBlock.get();
  currentFunction_->addBlock(std::move(successBlock));
  currentBlock_ = successBlockPtr;
  auto successValue = emitFailableValue(failableValue);
  std::string successFrom = currentBlock_->label;
  bool resultIsVoid = node.type && node.type->getKind() == TypeKind::Void;
  currentBlock_->addInstruction(std::make_unique<BranchInst>(mergeLabel));
  auto failBlock = std::make_unique<BasicBlock>(failLabel);
  auto *failBlockPtr = failBlock.get();
  currentFunction_->addBlock(std::move(failBlock));
  currentBlock_ = failBlockPtr;
  auto failErr = emitFailableError(failableValue);
  auto propagatedType = node.propagatedType;
  auto propagatedLayout = getFailableTypeLayout(propagatedType);
  auto propagatedValueType =
      propagatedLayout ? propagatedLayout->valueType : nullptr;
  auto propagatedErrorType =
      propagatedLayout ? propagatedLayout->errorType : nullptr;
  auto propagatedAlloca =
      createRegister(std::make_shared<PointerType>(propagatedType));
  currentBlock_->addInstruction(
      std::make_unique<AllocaInst>(propagatedAlloca, propagatedType));
  auto okAddr = createRegister(std::make_shared<PointerType>(
      std::make_shared<PrimitiveType>(TypeKind::Bool)));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      okAddr, propagatedAlloca, FailableTypeLayout::OkField));
  currentBlock_->addInstruction(std::make_unique<StoreInst>(
      std::make_shared<Constant>(
          "false", std::make_shared<PrimitiveType>(TypeKind::Bool)),
      okAddr));
  auto valueAddr =
      createRegister(std::make_shared<PointerType>(propagatedValueType));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      valueAddr, propagatedAlloca, FailableTypeLayout::ValueField));
  if (propagatedValueType && propagatedValueType->getKind() != TypeKind::Void) {
    currentBlock_->addInstruction(std::make_unique<StoreInst>(
        std::make_shared<Constant>("0", propagatedValueType), valueAddr));
  }
  auto errAddr =
      createRegister(std::make_shared<PointerType>(propagatedErrorType));
  currentBlock_->addInstruction(std::make_unique<GetElementPtrInst>(
      errAddr, propagatedAlloca, FailableTypeLayout::ErrorField));
  currentBlock_->addInstruction(std::make_unique<StoreInst>(failErr, errAddr));
  auto propagatedValue = createRegister(propagatedType);
  currentBlock_->addInstruction(
      std::make_unique<LoadInst>(propagatedValue, propagatedAlloca));
  currentBlock_->addInstruction(std::make_unique<ReturnInst>(propagatedValue));
  auto mergeBlock = std::make_unique<BasicBlock>(mergeLabel);
  auto *mergeBlockPtr = mergeBlock.get();
  currentFunction_->addBlock(std::move(mergeBlock));
  currentBlock_ = mergeBlockPtr;
  if (resultIsVoid) {
    valueStack_.push(std::make_shared<Constant>("0", node.type));
    return;
  }
  auto result = createRegister(node.type);
  std::vector<std::pair<std::string, std::shared_ptr<Value>>> incoming;
  incoming.push_back({successFrom, successValue});
  currentBlock_->addInstruction(std::make_unique<PhiInst>(result, incoming));
  valueStack_.push(result);
}
References zir::Bool, createBlockLabel(), createRegister(), currentBlock_, currentFunction_, emitFailableError(), emitFailableOk(), emitFailableValue(), zir::FailableTypeLayout::ErrorField, sema::BoundTryExpression::expression, zir::getFailableTypeLayout(), zir::FailableTypeLayout::OkField, sema::BoundTryExpression::propagatedType, sema::BoundExpression::type, zir::FailableTypeLayout::ValueField, valueStack_, and zir::Void.
visit() [35/40]
void zir::BoundIRGenerator::visit (sema::BoundUnaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 765 of file ir_generator.cpp.
{
  if (node.op == "&") {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ = true;
    node.expr->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    return;
  }
  if (node.op == "*") {
    bool oldEvaluateAsAddress = evaluateAsAddress_;
    evaluateAsAddress_ = false;
    node.expr->accept(*this);
    evaluateAsAddress_ = oldEvaluateAsAddress;
    auto ptr = valueStack_.top();
    valueStack_.pop();
    if (evaluateAsAddress_) {
      valueStack_.push(ptr);
      return;
    }
    auto reg = createRegister(node.type);
    currentBlock_->addInstruction(std::make_unique<LoadInst>(reg, ptr));
    valueStack_.push(reg);
    return;
  }
  node.expr->accept(*this);
  auto expr = valueStack_.top();
  valueStack_.pop();
  // Global initializers are lowered as constants only. Fold unary operators on
  // constants instead of emitting runtime IR outside functions.
  if (!currentFunction_ || !currentBlock_) {
    if (auto c = std::dynamic_pointer_cast<Constant>(expr)) {
      const auto &lit = c->getLiteral();
      if (node.op == "+") {
        valueStack_.push(c);
        return;
      }
      if (node.op == "-") {
        if (!lit.empty() && lit != "true" && lit != "false" && lit != "null" &&
            lit[0] != '\'' && lit[0] != '\\') {
          try {
            if (c->getType() && c->getType()->isFloatingPoint()) {
              auto v = std::stod(lit);
              valueStack_.push(
                  std::make_shared<Constant>(std::to_string(-v), node.type));
              return;
            }
            if (c->getType() && c->getType()->isInteger()) {
              if (c->getType()->isUnsigned()) {
                auto v = std::stoull(lit);
                auto out = static_cast<int64_t>(-(static_cast<int64_t>(v)));
                valueStack_.push(
                    std::make_shared<Constant>(std::to_string(out), node.type));
              } else {
                auto v = std::stoll(lit);
                valueStack_.push(
                    std::make_shared<Constant>(std::to_string(-v), node.type));
              }
              return;
            }
          } catch (...) {
          }
        }
      }
      if (node.op == "!") {
        if (lit == "true") {
          valueStack_.push(std::make_shared<Constant>("false", node.type));
          return;
        }
        if (lit == "false") {
          valueStack_.push(std::make_shared<Constant>("true", node.type));
          return;
        }
      }
      if (node.op == "~") {
        if (!lit.empty() && lit != "true" && lit != "false" && lit != "null" &&
            lit[0] != '\'' && lit[0] != '\\') {
          try {
            auto v = std::stoll(lit);
            valueStack_.push(
                std::make_shared<Constant>(std::to_string(~v), node.type));
            return;
          } catch (...) {
          }
        }
      }
    }
    valueStack_.push(expr);
    return;
  }
  if (node.op == "+") {
    valueStack_.push(expr);
    return;
  }
  if (node.op == "-") {
    auto zero = std::make_shared<Constant>("0", node.type);
    auto reg = createRegister(node.type);
    currentBlock_->addInstruction(
        std::make_unique<BinaryInst>(OpCode::Sub, reg, zero, expr));
    valueStack_.push(reg);
    return;
  }
  if (node.op == "!") {
    auto zero = std::make_shared<Constant>(
        "false", std::make_shared<PrimitiveType>(TypeKind::Bool));
    auto reg = createRegister(node.type);
    currentBlock_->addInstruction(
        std::make_unique<CmpInst>("eq", reg, expr, zero));
    valueStack_.push(reg);
    return;
  }
  if (node.op == "~") {
    auto allOnes = std::make_shared<Constant>("-1", node.type);
    auto reg = createRegister(node.type);
    currentBlock_->addInstruction(
        std::make_unique<BinaryInst>(OpCode::BitXor, reg, expr, allOnes));
    valueStack_.push(reg);
    return;
  }
  valueStack_.push(expr);
}
References zir::BitXor, zir::Bool, createRegister(), currentBlock_, currentFunction_, evaluateAsAddress_, sema::BoundUnaryExpression::expr, sema::BoundUnaryExpression::op, zir::Sub, sema::BoundExpression::type, and valueStack_.
visit() [36/40]
void zir::BoundIRGenerator::visit (sema::BoundVariableDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 299 of file ir_generator.cpp.
{
  auto type = node.symbol->type;
  if (!currentFunction_) {
    if (node.symbol->is_external) {
      auto global = std::make_shared<Global>(
          node.symbol->name, node.symbol->linkName, type, nullptr, false);
      module_->addExternalGlobal(global);
      globalSymbolMap_[node.symbol] = global;
      return;
    }
    std::shared_ptr<Value> initializer = nullptr;
    if (node.initializer) {
      initializer = lowerConstantExpression(*node.initializer);
      if (!initializer) {
        node.initializer->accept(*this);
        if (!valueStack_.empty()) {
          initializer = valueStack_.top();
          valueStack_.pop();
        }
      }
    }
    auto global =
        std::make_shared<Global>(node.symbol->name, node.symbol->linkName, type,
                                 initializer, node.symbol->is_const);
    module_->addGlobal(global);
    globalSymbolMap_[node.symbol] = global;
    return;
  }
  if (node.symbol->is_ref) {
    // Ref var: alloca a pointer slot, store the address of the initializer
    auto ptrType = std::make_shared<PointerType>(type);
    auto refReg = createRegister(std::make_shared<PointerType>(ptrType));
    currentBlock_->addInstruction(
        std::make_unique<AllocaInst>(refReg, ptrType));
    symbolMap_[node.symbol] = refReg;
    if (node.initializer) {
      bool old = evaluateAsAddress_;
      evaluateAsAddress_ = true;
      node.initializer->accept(*this);
      evaluateAsAddress_ = old;
      auto addr = valueStack_.top();
      valueStack_.pop();
      currentBlock_->addInstruction(std::make_unique<StoreInst>(addr, refReg));
    }
    return;
  }
  auto reg = createRegister(std::make_shared<PointerType>(type));
  currentBlock_->addInstruction(std::make_unique<AllocaInst>(reg, type));
  symbolMap_[node.symbol] = reg;
  if (node.initializer) {
    node.initializer->accept(*this);
    auto val = valueStack_.top();
    valueStack_.pop();
    currentBlock_->addInstruction(std::make_unique<StoreInst>(val, reg));
  }
}
References createRegister(), currentBlock_, currentFunction_, evaluateAsAddress_, globalSymbolMap_, sema::BoundVariableDeclaration::initializer, lowerConstantExpression(), module_, sema::BoundVariableDeclaration::symbol, symbolMap_, and valueStack_.
visit() [37/40]
void zir::BoundIRGenerator::visit (sema::BoundVariableExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 469 of file ir_generator.cpp.
{
  std::shared_ptr<Value> addr = nullptr;
  auto localIt = symbolMap_.find(node.symbol);
  if (localIt != symbolMap_.end()) {
    addr = localIt->second;
  } else {
    auto globalIt = globalSymbolMap_.find(node.symbol);
    if (globalIt != globalSymbolMap_.end()) {
      addr = globalIt->second;
    }
  }
  if (!addr) {
    std::cerr << "Error: Symbol " << node.symbol->name
              << " not found in IR symbol map\n";
    return;
  }
  if (node.symbol->is_ref) {
    auto ptrReg =
        createRegister(std::make_shared<PointerType>(node.symbol->type));
    currentBlock_->addInstruction(std::make_unique<LoadInst>(ptrReg, addr));
    if (evaluateAsAddress_) {
      valueStack_.push(ptrReg);
      return;
    }
    auto valueReg = createRegister(node.type);
    currentBlock_->addInstruction(std::make_unique<LoadInst>(valueReg, ptrReg));
    valueStack_.push(valueReg);
    return;
  }
  if (evaluateAsAddress_) {
    valueStack_.push(addr);
    return;
  }
  auto reg = createRegister(node.type);
  currentBlock_->addInstruction(std::make_unique<LoadInst>(reg, addr));
  valueStack_.push(reg);
}
References createRegister(), currentBlock_, evaluateAsAddress_, globalSymbolMap_, sema::BoundVariableExpression::symbol, symbolMap_, sema::BoundExpression::type, and valueStack_.
visit() [38/40]
void zir::BoundIRGenerator::visit (sema::BoundWeakAliveExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1630 of file ir_generator.cpp.
{
  node.weakExpression->accept(*this);
  auto weakValue = valueStack_.top();
  valueStack_.pop();
  auto result = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<WeakAliveInst>(result, weakValue));
  valueStack_.push(result);
}
References createRegister(), currentBlock_, sema::BoundExpression::type, valueStack_, and sema::BoundWeakAliveExpression::weakExpression.
visit() [39/40]
void zir::BoundIRGenerator::visit (sema::BoundWeakLockExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1620 of file ir_generator.cpp.
{
  node.weakExpression->accept(*this);
  auto weakValue = valueStack_.top();
  valueStack_.pop();
  auto result = createRegister(node.type);
  currentBlock_->addInstruction(
      std::make_unique<WeakLockInst>(result, weakValue));
  valueStack_.push(result);
}
References createRegister(), currentBlock_, sema::BoundExpression::type, valueStack_, and sema::BoundWeakLockExpression::weakExpression.
visit() [40/40]
void zir::BoundIRGenerator::visit (sema::BoundWhileStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1479 of file ir_generator.cpp.
{
  auto condLabel = createBlockLabel("while.cond");
  auto bodyLabel = createBlockLabel("while.body");
  auto endLabel = createBlockLabel("while.end");
  currentBlock_->addInstruction(std::make_unique<BranchInst>(condLabel));
  auto condBlock = std::make_unique<BasicBlock>(condLabel);
  auto *condBlockPtr = condBlock.get();
  currentFunction_->addBlock(std::move(condBlock));
  currentBlock_ = condBlockPtr;
  node.condition->accept(*this);
  auto cond = valueStack_.top();
  valueStack_.pop();
  currentBlock_->addInstruction(
      std::make_unique<CondBranchInst>(cond, bodyLabel, endLabel));
  auto bodyBlock = std::make_unique<BasicBlock>(bodyLabel);
  auto *bodyBlockPtr = bodyBlock.get();
  currentFunction_->addBlock(std::move(bodyBlock));
  currentBlock_ = bodyBlockPtr;
  loopLabelStack_.push_back({condLabel, endLabel});
  node.body->accept(*this);
  loopLabelStack_.pop_back();
  if (currentBlock_->instructions.empty() ||
      currentBlock_->instructions.back()->getOpCode() != OpCode::Ret) {
    currentBlock_->addInstruction(std::make_unique<BranchInst>(condLabel));
  }
  auto endBlock = std::make_unique<BasicBlock>(endLabel);
  auto *endBlockPtr = endBlock.get();
  currentFunction_->addBlock(std::move(endBlock));
  currentBlock_ = endBlockPtr;
}
References sema::BoundWhileStatement::body, sema::BoundWhileStatement::condition, createBlockLabel(), currentBlock_, currentFunction_, loopLabelStack_, zir::Ret, and valueStack_.
Member Data Documentation
compoundTargetAddr_
std::shared_ptr<Value> zir::BoundIRGenerator::compoundTargetAddr_ = nullptr private
Definition at line 75 of file ir_generator.hpp.
Referenced by visit(), and visit().
currentBlock_
BasicBlock* zir::BoundIRGenerator::currentBlock_ = nullptr private
Definition at line 61 of file ir_generator.hpp.
Referenced by emitFailableFieldLoad(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
currentFunction_
Function* zir::BoundIRGenerator::currentFunction_ = nullptr private
Definition at line 60 of file ir_generator.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
evaluateAsAddress_
bool zir::BoundIRGenerator::evaluateAsAddress_ = false private
Definition at line 74 of file ir_generator.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
globalSymbolMap_
std::map<std::shared_ptr<sema::Symbol>, std::shared_ptr<Value> > zir::BoundIRGenerator::globalSymbolMap_ private
Definition at line 65 of file ir_generator.hpp.
Referenced by generate(), visit(), and visit().
lastResultValue_
std::shared_ptr<Value> zir::BoundIRGenerator::lastResultValue_ = nullptr private
Definition at line 73 of file ir_generator.hpp.
loopLabelStack_
std::vector<std::pair<std::string, std::string> > zir::BoundIRGenerator::loopLabelStack_ private
Definition at line 71 of file ir_generator.hpp.
Referenced by visit(), visit(), visit(), and visit().
module_
std::unique_ptr<Module> zir::BoundIRGenerator::module_ private
Definition at line 59 of file ir_generator.hpp.
Referenced by generate(), visit(), visit(), visit(), visit(), visit(), and visit().
nextBlockId_
int zir::BoundIRGenerator::nextBlockId_ = 0 private
Definition at line 69 of file ir_generator.hpp.
Referenced by createBlockLabel().
nextRegisterId_
int zir::BoundIRGenerator::nextRegisterId_ = 0 private
Definition at line 68 of file ir_generator.hpp.
Referenced by createRegister().
symbolMap_
std::map<std::shared_ptr<sema::Symbol>, std::shared_ptr<Value> > zir::BoundIRGenerator::symbolMap_ private
Definition at line 63 of file ir_generator.hpp.
Referenced by visit(), visit(), visit(), visit(), and visit().
valueStack_
std::stack<std::shared_ptr<Value> > zir::BoundIRGenerator::valueStack_ private
Definition at line 66 of file ir_generator.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
The documentation for this class was generated from the following files:
src/ir/ir_generator.hpp
src/ir/ir_generator.cpp