ZAP: zap::text Namespace Reference
zap::text Namespace Reference
Enumerations
enum class StringKind {
NotString ,
String ,
StringView
}
Functions
std::string baseTypeName (const std::string &full)
StringKind classifyRecordName (const std::string &full)
bool isStringRecordName (const std::string &full)
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isStringViewType (const std::shared_ptr< zir::Type > &type)
Enumeration Type Documentation
StringKind
enum class zap::text::StringKind strong
Enumerator
NotString
String
StringView
Definition at line 9 of file string_type_utils.hpp.
                      {
  NotString,
  String,
  StringView,
};
Function Documentation
baseTypeName()
std::string zap::text::baseTypeName (const std::string & full) inline
Definition at line 15 of file string_type_utils.hpp.
{
  auto dot = full.find_last_of('.');
  return dot == std::string::npos ? full : full.substr(dot + 1);
}
Referenced by classifyRecordName().
classifyRecordName()
StringKind zap::text::classifyRecordName (const std::string & full) inline
Definition at line 20 of file string_type_utils.hpp.
{
  const auto base = baseTypeName(full);
  if (base == "String") {
    return StringKind::String;
  }
  if (base == "StringView") {
    return StringKind::StringView;
  }
  return StringKind::NotString;
}
References baseTypeName(), NotString, String, and StringView.
Referenced by isStringRecordName(), and isStringViewType().
isStringRecordName()
bool zap::text::isStringRecordName (const std::string & full) inline
Definition at line 31 of file string_type_utils.hpp.
{
  return classifyRecordName(full) != StringKind::NotString;
}
References classifyRecordName(), and NotString.
Referenced by codegen::anonymous_namespace{llvm_codegen_zir.cpp}::isStringLLVMStructType(), codegen::anonymous_namespace{llvm_codegen.cpp}::isStringRecordName(), codegen::anonymous_namespace{llvm_codegen_constants.cpp}::isStringRecordName(), codegen::anonymous_namespace{llvm_codegen_expr.cpp}::isStringRecordName(), isStringType(), sema::anonymous_namespace{binder_exprs.cpp}::layoutOfRecord(), and zir::BoundIRGenerator::visit().
isStringType()
bool zap::text::isStringType (const std::shared_ptr< zir::Type > & type) inline
Definition at line 35 of file string_type_utils.hpp.
{
  if (!type) {
    return false;
  }
  if (type->getKind() == zir::TypeKind::Record) {
    return isStringRecordName(
        static_cast<zir::RecordType *>(type.get())->getName());
  }
  if (type->getKind() == zir::TypeKind::Class) {
    return isStringRecordName(
        static_cast<zir::ClassType *>(type.get())->getName());
  }
  return false;
}
References zir::Class, zir::RecordType::getName(), isStringRecordName(), and zir::Record.
Referenced by codegen::LLVMCodeGen::isOwnedStringType(), codegen::anonymous_namespace{llvm_codegen.cpp}::isStringType(), codegen::anonymous_namespace{llvm_codegen_constants.cpp}::isStringType(), codegen::anonymous_namespace{llvm_codegen_expr.cpp}::isStringType(), codegen::anonymous_namespace{llvm_codegen_zir.cpp}::isStringType(), and sema::isStringType().
isStringViewType()
bool zap::text::isStringViewType (const std::shared_ptr< zir::Type > & type) inline
Definition at line 53 of file string_type_utils.hpp.
{
  if (!type || type->getKind() != zir::TypeKind::Record) {
    return false;
  }
  return classifyRecordName(
             static_cast<zir::RecordType *>(type.get())->getName()) ==
         StringKind::StringView;
}
References classifyRecordName(), zir::RecordType::getName(), zir::Record, and StringView.
Referenced by sema::Binder::conversionCost(), and codegen::LLVMCodeGen::isOwnedStringType().