ZAP: ReturnNode Class Reference
ReturnNode Class Reference
#include <return_node.hpp>
Public Member Functions
ReturnNode () noexcept=default
ReturnNode (std::unique_ptr< ExpressionNode > value)
~ReturnNode () noexcept override=default
void accept (Visitor &v) override
Public Member Functions inherited from StatementNode
virtual ~StatementNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::unique_ptr< ExpressionNode > returnValue
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 9 of file return_node.hpp.
Constructor & Destructor Documentation
ReturnNode() [1/2]
ReturnNode::ReturnNode () default noexcept
Referenced by ReturnNode().
ReturnNode() [2/2]
ReturnNode::ReturnNode (std::unique_ptr< ExpressionNode > value) inline
Definition at line 14 of file return_node.hpp.
      : returnValue(std::move(value)) {}
References ReturnNode(), and returnValue.
~ReturnNode()
ReturnNode::~ReturnNode () override default noexcept
Member Function Documentation
accept()
void ReturnNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 19 of file return_node.hpp.
{ v.visit(*this); }
References accept().
Referenced by accept().
Member Data Documentation
returnValue
std::unique_ptr<ExpressionNode> ReturnNode::returnValue
Definition at line 11 of file return_node.hpp.
Referenced by ReturnNode(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/return_node.hpp