ZAP: sema::BoundBlock Class Reference
sema::BoundBlock Class Reference
#include <bound_nodes.hpp>
Public Member Functions
void accept (BoundVisitor &v) override
std::unique_ptr< BoundStatement > cloneStatement () const override
std::unique_ptr< BoundBlock > cloneBlock () const
Public Member Functions inherited from sema::BoundNode
virtual ~BoundNode ()=default
Public Attributes
std::vector< std::unique_ptr< BoundStatement > > statements
std::unique_ptr< BoundExpression > result
Detailed Description
Definition at line 103 of file bound_nodes.hpp.
Member Function Documentation
accept()
void sema::BoundBlock::accept (BoundVisitor & v) inline override virtual
Implements sema::BoundNode.
Definition at line 108 of file bound_nodes.hpp.
{ v.visit(*this); }
References sema::BoundVisitor::visit().
cloneBlock()
std::unique_ptr< BoundBlock > sema::BoundBlock::cloneBlock () const inline
Definition at line 115 of file bound_nodes.hpp.
{
      auto res = cloneStatement();
      return std::unique_ptr<BoundBlock>(static_cast<BoundBlock *>(res.release()));
    }
References cloneStatement().
cloneStatement()
std::unique_ptr< BoundStatement > sema::BoundBlock::cloneStatement () const inline override virtual
Implements sema::BoundStatement.
Definition at line 109 of file bound_nodes.hpp.
{
      auto cloned = std::make_unique<BoundBlock>();
      for (const auto &stmt : statements) cloned->statements.push_back(stmt->cloneStatement());
      if (result) cloned->result = result->clone();
      return cloned;
    }
References result, and statements.
Referenced by cloneBlock().
Member Data Documentation
result
std::unique_ptr<BoundExpression> sema::BoundBlock::result
Definition at line 107 of file bound_nodes.hpp.
Referenced by cloneStatement(), codegen::LLVMCodeGen::visit(), and zir::BoundIRGenerator::visit().
statements
std::vector<std::unique_ptr<BoundStatement> > sema::BoundBlock::statements
Definition at line 106 of file bound_nodes.hpp.
Referenced by cloneStatement(), codegen::LLVMCodeGen::visit(), and zir::BoundIRGenerator::visit().
The documentation for this class was generated from the following file:
src/sema/bound_nodes.hpp