ZAP: zap::lsp Namespace Reference
zap::lsp Namespace Reference
Namespaces
namespace anonymous_namespace{lsp.cpp}
namespace anonymous_namespace{protocol_utils.cpp}
namespace anonymous_namespace{symbol_index.cpp}
Classes
struct StructLiteralCompletionContext
struct LspSymbol
class JsonObject
class JsonParser
class JsonRPC
class Server
struct VisibleSymbolInfo
class Workspace
struct DocumentState
struct AnalysisResult
struct ProjectState
struct LspSignature
struct CallContext
struct HoverInfo
Functions
bool matchesPrefix (std::string_view name, std::string_view prefix)
std::optional< size_t > enclosingBraceBeforeOffset (const std::string &source, size_t offset)
std::optional< std::string > typeNameBeforeBrace (const std::string &source, size_t brace)
std::optional< StructLiteralCompletionContext > structLiteralCompletionAtCursor (const std::string &source, size_t offset)
std::vector< const ParameterNode * > findRecordLikeFields (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
std::vector< const ParameterNode * > resolveRecordLikeFieldsInModule (const ProjectState &project, const sema::ModuleInfo &module, std::string_view name, bool publicOnly, std::set< std::string > &visited)
std::vector< const ParameterNode * > resolveRecordLikeFieldsByTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName, bool publicOnly=false)
std::vector< LspSymbol > collectCompletionSymbols (const std::string &uri, const ProjectState &project, size_t offset)
JsonObject::List makeCompletionItems (const std::string &uri, const std::string &source, const ProjectState &project, size_t offset)
std::optional< LspSymbol > makeSymbol (const std::string &uri, const std::string &name, const SourceSpan &span, int64_t kind, Visibility visibility)
std::optional< LspSignature > signatureForNode (const Node *node)
std::string effectiveImportAlias (const sema::ResolvedImport &import, const sema::ModuleInfo &target)
const sema::ModuleInfo * findImportedModuleByAlias (const ProjectState &project, const sema::ModuleInfo &module, std::string_view alias)
std::pair< std::string, std::string > splitQualifiedName (std::string_view qualifiedName)
std::string stripGenericArguments (std::string_view typeName)
const ClassDecl * resolveClassByTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName, bool publicOnly)
std::optional< std::string > resolveVariableClassType (const ProjectState &project, const sema::ModuleInfo &module, size_t offset, std::string_view name)
std::shared_ptr< zir::RecordType > resolveVariableRecordType (const ProjectState &project, const sema::ModuleInfo &module, size_t offset, std::string_view name)
std::vector< LspSymbol > collectTopLevelSymbols (const sema::ModuleInfo &module, const std::string &uri, bool publicOnly)
std::vector< LspSymbol > collectExportedSymbolsRecursive (const ProjectState &project, const sema::ModuleInfo &module, std::set< std::string > &visited)
std::vector< LspSymbol > collectImportedSymbols (const ProjectState &project, const sema::ModuleInfo &module)
std::string renderType (const TypeNode *type)
std::string renderParameter (const ParameterNode *param)
std::vector< LspSignature > findTopLevelSignatures (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
std::optional< std::string > topLevelNameForNode (const Node *node)
const ClassDecl * findClassDecl (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
const ClassDecl * resolveClassInModule (const ProjectState &project, const sema::ModuleInfo &module, std::string_view name, bool publicOnly, std::set< std::string > &visited)
bool isClassTypeName (const ProjectState &project, const sema::ModuleInfo &module, std::string_view typeName)
std::optional< std::string > resolveClassTypeNameFromTypeNode (const ProjectState &project, const sema::ModuleInfo &module, const TypeNode *type)
std::optional< std::string > resolveClassTypeNameFromSemanticType (const ProjectState &project, const sema::ModuleInfo &module, const std::shared_ptr< zir::Type > &type)
const ClassDecl * enclosingClassAtOffset (const RootNode &root, size_t offset)
const ParameterNode * findClassField (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
const FunDecl * findClassMethod (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::vector< LspSignature > findConstructorSignatures (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module)
std::optional< HoverInfo > hoverForClassMember (const ClassDecl *cls, const ProjectState &project, const sema::ModuleInfo &module, std::string_view member, bool publicOnly=false)
std::optional< CallContext > callContextAtOffset (const std::string &source, size_t offset)
std::optional< CallContext > callContextNearOffset (const std::string &source, size_t offset)
std::vector< LspSignature > resolveSignaturesInModuleRecursive (const ProjectState &project, const sema::ModuleInfo &module, std::string_view name, bool publicOnly, std::set< std::string > &visited)
std::vector< LspSignature > resolveSignatures (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset, int64_t &activeParameter)
std::optional< HoverInfo > hoverForNode (const Node *node)
std::optional< HoverInfo > findTopLevelHover (const sema::ModuleInfo &module, std::string_view name, bool publicOnly=false)
std::optional< HoverInfo > resolveHoverInModuleRecursive (const ProjectState &project, const sema::ModuleInfo &module, std::string_view name, bool publicOnly, std::set< std::string > &visited)
std::optional< HoverInfo > resolveHover (const std::string &source, const std::string &uri, const ProjectState &project, size_t offset)
std::optional< LspSymbol > topLevelSymbolForNode (const Node *node, const std::string &uri)
std::optional< LspSymbol > resolveDefinition (const Workspace &workspace, const std::string &uri, const ProjectState &project, size_t offset)
int64_t chooseActiveSignature (const std::vector< LspSignature > &signatures, int64_t activeParameter)
JsonObject makeResponse (const JsonObject *id, JsonObject result)
JsonObject makeNotification (std::string method, JsonObject params)
JsonObject makeRange (const zap::DiagnosticRange &range)
JsonObject makeLocation (const std::string &uri, const SourceSpan &span)
JsonObject makeCompletionItem (const LspSymbol &symbol, const std::string &detail)
JsonObject makeHover (const HoverInfo &hover)
JsonObject makeSignatureHelp (const std::vector< LspSignature > &signatures, int64_t activeSignature, int64_t activeParameter)
int64_t toLspSeverity (zap::DiagnosticLevel level)
JsonObject makeDiagnostic (const zap::Diagnostic &diagnostic)
JsonObject makePublishDiagnostics (std::string uri, const std::vector< zap::Diagnostic > &diagnostics)
void publishAnalysis (Server &server, const AnalysisResult &result)
const JsonObject * getField (const JsonObject &object, std::string_view key)
const JsonObject * getPath (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< std::string > getStringField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< int64_t > getIntegerField (const JsonObject &object, std::initializer_list< std::string_view > path)
std::optional< std::filesystem::path > uriToPath (std::string_view uri)
std::string pathToUri (const std::filesystem::path &path)
bool readSourceFile (const std::filesystem::path &path, std::string &content)
zap::args::CmdlineArgs findAndReadFlags (std::filesystem::path startPath)
size_t offsetFromPosition (const std::string &text, int64_t line, int64_t character)
bool containsOffset (const SourceSpan &span, size_t offset)
bool isIdentifierChar (char ch)
std::optional< std::string > identifierAt (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > memberAccessBeforeCursor (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > memberAccessAtCursor (const std::string &source, size_t offset)
std::optional< std::pair< std::string, std::string > > qualifiedIdentifierAtOffset (const std::string &source, size_t offset)
std::vector< LspSymbol > collectLocalSymbols (const RootNode &root, size_t offset, const std::string &uri)
VisibleSymbolInfo findVisibleSymbolInfo (const RootNode &root, size_t offset, std::string_view name)
const TypeNode * findVisibleTypeNode (const RootNode &root, size_t offset, std::string_view name)
Variables
constexpr std::string_view prefix = "Content-Length: "
constexpr size_t kMaxLspMessageBytes = 8 * 1024 * 1024
Function Documentation
callContextAtOffset()
std::optional< CallContext > zap::lsp::callContextAtOffset (const std::string & source, size_t offset)
Definition at line 524 of file language_features.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = std::min(offset, source.size());
  int nestedParens = 0;
  int nestedBrackets = 0;
  int nestedBraces = 0;
  int64_t activeParameter = 0;
  bool foundOpenParen = false;
  size_t openParen = 0;
  while (pos > 0) {
    --pos;
    char ch = source[pos];
    if (ch == ')') {
      ++nestedParens;
    } else if (ch == '(') {
      if (nestedParens == 0 && nestedBrackets == 0 && nestedBraces == 0) {
        openParen = pos;
        foundOpenParen = true;
        break;
      }
      if (nestedParens > 0) {
        --nestedParens;
      }
    } else if (ch == ']') {
      ++nestedBrackets;
    } else if (ch == '[') {
      if (nestedBrackets > 0) {
        --nestedBrackets;
      }
    } else if (ch == '}') {
      ++nestedBraces;
    } else if (ch == '{') {
      if (nestedBraces > 0) {
        --nestedBraces;
      }
    } else if (ch == ',' && nestedParens == 0 && nestedBrackets == 0 &&
               nestedBraces == 0) {
      ++activeParameter;
    }
  }
  if (!foundOpenParen) {
    return std::nullopt;
  }
  size_t end = openParen;
  while (end > 0 && std::isspace(static_cast<unsigned char>(source[end - 1]))) {
    --end;
  }
  size_t start = end;
  while (start > 0) {
    char ch = source[start - 1];
    if (isIdentifierChar(ch) || ch == '.' || ch == '<' || ch == '>' ||
        ch == ',' || std::isspace(static_cast<unsigned char>(ch))) {
      --start;
      continue;
    }
    break;
  }
  std::string callee = source.substr(start, end - start);
  bool isConstructor = false;
  size_t newKeyword = callee.rfind("new");
  if (newKeyword != std::string::npos &&
      (newKeyword == 0 || !isIdentifierChar(callee[newKeyword - 1])) &&
      newKeyword + 3 < callee.size() &&
      std::isspace(static_cast<unsigned char>(callee[newKeyword + 3]))) {
    callee = callee.substr(newKeyword + 3);
    isConstructor = true;
  }
  callee.erase(
      std::remove_if(callee.begin(), callee.end(),
                     [](unsigned char ch) { return std::isspace(ch); }),
      callee.end());
  if (callee.empty()) {
    return std::nullopt;
  }
  return CallContext{std::move(callee), activeParameter, isConstructor};
}
References isIdentifierChar().
Referenced by callContextNearOffset().
callContextNearOffset()
std::optional< CallContext > zap::lsp::callContextNearOffset (const std::string & source, size_t offset)
Definition at line 610 of file language_features.cpp.
{
  if (auto call = callContextAtOffset(source, offset)) {
    return call;
  }
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = std::min(offset, source.size() - 1);
  if (isIdentifierChar(source[pos])) {
    size_t end = pos + 1;
    while (end < source.size() && isIdentifierChar(source[end])) {
      ++end;
    }
    while (end < source.size() &&
           std::isspace(static_cast<unsigned char>(source[end]))) {
      ++end;
    }
    if (end < source.size() && source[end] == '(') {
      return callContextAtOffset(source, end + 1);
    }
  }
  if (pos < source.size() && source[pos] == '(') {
    return callContextAtOffset(source, pos + 1);
  }
  return std::nullopt;
}
References callContextAtOffset(), and isIdentifierChar().
Referenced by resolveSignatures().
chooseActiveSignature()
int64_t zap::lsp::chooseActiveSignature (const std::vector< LspSignature > & signatures, int64_t activeParameter)
Definition at line 1253 of file language_features.cpp.
{
  int64_t activeSignature = 0;
  for (size_t i = 0; i < signatures.size(); ++i) {
    if (activeParameter < static_cast<int64_t>(std::max<size_t>(
                              size_t(1), signatures[i].parameters.size()))) {
      activeSignature = static_cast<int64_t>(i);
      break;
    }
  }
  return activeSignature;
}
Referenced by main().
collectCompletionSymbols()
std::vector< LspSymbol > zap::lsp::collectCompletionSymbols (const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 307 of file completion.cpp.
{
  std::vector<LspSymbol> symbols;
  auto path = uriToPath(uri);
  if (!path) {
    return symbols;
  }
  auto docIt =
      project.moduleMap.find(std::filesystem::weakly_canonical(*path).string());
  if (docIt == project.moduleMap.end()) {
    return symbols;
  }
  const sema::ModuleInfo &module = *docIt->second;
  auto topLevel = collectTopLevelSymbols(module, uri, false);
  symbols.insert(symbols.end(), topLevel.begin(), topLevel.end());
  auto imported = collectImportedSymbols(project, module);
  symbols.insert(symbols.end(), imported.begin(), imported.end());
  auto locals = collectLocalSymbols(*module.root, offset, uri);
  symbols.insert(symbols.end(), locals.begin(), locals.end());
  static constexpr std::pair<const char *, int64_t> builtinTypes[] = {
      {"Int", 22},     {"Int8", 22},   {"Int16", 22}, {"Int32", 22},
      {"Int64", 22},   {"UInt", 22},   {"UInt8", 22}, {"UInt16", 22},
      {"UInt32", 22},  {"UInt64", 22}, {"Float", 22}, {"Float32", 22},
      {"Float64", 22}, {"Bool", 22},   {"Void", 22},  {"Char", 22},
      {"String", 22}};
  for (const auto &[name, kind] : builtinTypes) {
    symbols.push_back(
        *makeSymbol(uri, name, SourceSpan(), kind, Visibility::Public));
  }
  return symbols;
}
References collectImportedSymbols(), collectLocalSymbols(), collectTopLevelSymbols(), makeSymbol(), zap::lsp::ProjectState::moduleMap, Public, sema::ModuleInfo::root, and uriToPath().
Referenced by makeCompletionItems().
collectExportedSymbolsRecursive()
std::vector< LspSymbol > zap::lsp::collectExportedSymbolsRecursive (const ProjectState & project, const sema::ModuleInfo & module, std::set< std::string > & visited)
Definition at line 1051 of file language_features.cpp.
{
  std::string moduleId = module.moduleId;
  if (visited.count(moduleId)) {
    return {};
  }
  visited.insert(moduleId);
  auto targetUriIt = project.uriByModuleId.find(moduleId);
  std::string targetUri = targetUriIt == project.uriByModuleId.end()
                              ? pathToUri(moduleId)
                              : targetUriIt->second;
  std::vector<LspSymbol> symbols =
      collectTopLevelSymbols(module, targetUri, true);
  for (const auto &import : module.imports) {
    if (import.visibility != Visibility::Public) {
      continue;
    }
    for (const auto &targetId : import.targetModuleIds) {
      auto targetIt = project.moduleMap.find(targetId);
      if (targetIt == project.moduleMap.end()) {
        continue;
      }
      auto subExports =
          collectExportedSymbolsRecursive(project, *targetIt->second, visited);
      if (import.bindings.empty()) {
        for (const auto &sym : subExports) {
          symbols.push_back(sym);
        }
      } else {
        for (const auto &binding : import.bindings) {
          auto exportIt =
              std::find_if(subExports.begin(), subExports.end(),
                           [&](const LspSymbol &symbol) {
                             return symbol.name == binding.sourceName;
                           });
          if (exportIt != subExports.end()) {
            LspSymbol local = *exportIt;
            local.name = binding.localName;
            symbols.push_back(std::move(local));
          }
        }
      }
    }
  }
  return symbols;
}
References collectExportedSymbolsRecursive(), collectTopLevelSymbols(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, zap::lsp::LspSymbol::name, pathToUri(), Public, and zap::lsp::ProjectState::uriByModuleId.
Referenced by collectExportedSymbolsRecursive(), collectImportedSymbols(), makeCompletionItems(), and resolveDefinition().
collectImportedSymbols()
std::vector< LspSymbol > zap::lsp::collectImportedSymbols (const ProjectState & project, const sema::ModuleInfo & module)
Definition at line 1103 of file language_features.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &import : module.imports) {
    for (const auto &targetId : import.targetModuleIds) {
      auto moduleIt = project.moduleMap.find(targetId);
      if (moduleIt == project.moduleMap.end()) {
        continue;
      }
      const auto &target = *moduleIt->second;
      auto alias = effectiveImportAlias(import, target);
      auto targetUriIt = project.uriByModuleId.find(targetId);
      std::string targetUri = targetUriIt == project.uriByModuleId.end()
                                  ? pathToUri(targetId)
                                  : targetUriIt->second;
      symbols.push_back(*makeSymbol(project.uriByModuleId.at(module.moduleId),
                                    alias, import.span, 9, Visibility::Public));
      std::set<std::string> visited;
      auto exported = collectExportedSymbolsRecursive(project, target, visited);
      bool isImplicitPreludeImport =
          import.rawPath == "std/prelude" && import.moduleAlias.empty();
      if (isImplicitPreludeImport) {
        for (const auto &sym : exported) {
          symbols.push_back(sym);
        }
      }
      if (import.bindings.empty()) {
        continue;
      }
      for (const auto &binding : import.bindings) {
        auto exportIt = std::find_if(exported.begin(), exported.end(),
                                     [&](const LspSymbol &symbol) {
                                       return symbol.name == binding.sourceName;
                                     });
        if (exportIt == exported.end()) {
          continue;
        }
        LspSymbol local = *exportIt;
        local.name = binding.localName;
        symbols.push_back(std::move(local));
      }
    }
  }
  return symbols;
}
References collectExportedSymbolsRecursive(), effectiveImportAlias(), sema::ModuleInfo::imports, makeSymbol(), sema::ModuleInfo::moduleId, zap::lsp::ProjectState::moduleMap, zap::lsp::LspSymbol::name, pathToUri(), Public, and zap::lsp::ProjectState::uriByModuleId.
Referenced by collectCompletionSymbols(), and resolveDefinition().
collectLocalSymbols()
std::vector< LspSymbol > zap::lsp::collectLocalSymbols (const RootNode & root, size_t offset, const std::string & uri)
Definition at line 402 of file symbol_index.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &child : root.children) {
    if (!child || !containsOffset(child->span, offset)) {
      continue;
    }
    if (auto fun = dynamic_cast<const FunDecl *>(child.get())) {
      collectFunctionLocals(fun, offset, uri, symbols);
      break;
    }
    if (auto cls = dynamic_cast<const ClassDecl *>(child.get())) {
      for (const auto &field : cls->fields_) {
        if (field && field->span.offset <= offset) {
          addSymbol(symbols, uri, field->name, field->span, 8,
                    field->visibility_);
        }
      }
      for (const auto &method : cls->methods_) {
        collectFunctionLocals(method.get(), offset, uri, symbols);
      }
      break;
    }
  }
  return symbols;
}
References RootNode::children, and containsOffset().
Referenced by collectCompletionSymbols(), and resolveDefinition().
collectTopLevelSymbols()
std::vector< LspSymbol > zap::lsp::collectTopLevelSymbols (const sema::ModuleInfo & module, const std::string & uri, bool publicOnly = false)
Definition at line 1033 of file language_features.cpp.
{
  std::vector<LspSymbol> symbols;
  for (const auto &child : module.root->children) {
    auto symbol = topLevelSymbolForNode(child.get(), uri);
    if (!symbol) {
      continue;
    }
    if (publicOnly && symbol->visibility != Visibility::Public) {
      continue;
    }
    symbols.push_back(*symbol);
  }
  return symbols;
}
References Public, sema::ModuleInfo::root, and topLevelSymbolForNode().
Referenced by collectCompletionSymbols(), collectExportedSymbolsRecursive(), and resolveDefinition().
containsOffset()
bool zap::lsp::containsOffset (const SourceSpan & span, size_t offset)
Definition at line 197 of file protocol_utils.cpp.
{
  return offset >= span.offset && offset <= span.offset + span.length;
}
References SourceSpan::length, and SourceSpan::offset.
Referenced by zap::lsp::anonymous_namespace{symbol_index.cpp}::collectFromExpression(), zap::lsp::anonymous_namespace{symbol_index.cpp}::collectFromStatement(), zap::lsp::anonymous_namespace{symbol_index.cpp}::collectFunctionLocals(), collectLocalSymbols(), enclosingClassAtOffset(), zap::lsp::anonymous_namespace{symbol_index.cpp}::findInfoInExpression(), zap::lsp::anonymous_namespace{symbol_index.cpp}::findInfoInStatement(), and findVisibleSymbolInfo().
effectiveImportAlias()
std::string zap::lsp::effectiveImportAlias (const sema::ResolvedImport & import, const sema::ModuleInfo & target)
Definition at line 994 of file language_features.cpp.
{
  return import.moduleAlias.empty() ? target.moduleName : import.moduleAlias;
}
References sema::ModuleInfo::moduleName.
Referenced by collectImportedSymbols(), findImportedModuleByAlias(), makeCompletionItems(), resolveDefinition(), resolveHover(), and resolveSignatures().
enclosingBraceBeforeOffset()
std::optional< size_t > zap::lsp::enclosingBraceBeforeOffset (const std::string & source, size_t offset)
Definition at line 27 of file completion.cpp.
{
  size_t pos = std::min(offset, source.size());
  int nestedBraces = 0;
  while (pos > 0) {
    --pos;
    char ch = source[pos];
    if (ch == '}') {
      ++nestedBraces;
      continue;
    }
    if (ch == '{') {
      if (nestedBraces == 0) {
        return pos;
      }
      --nestedBraces;
    }
  }
  return std::nullopt;
}
Referenced by structLiteralCompletionAtCursor().
enclosingClassAtOffset()
const ClassDecl * zap::lsp::enclosingClassAtOffset (const RootNode & root, size_t offset)
Definition at line 380 of file language_features.cpp.
{
  for (const auto &child : root.children) {
    auto cls = dynamic_cast<const ClassDecl *>(child.get());
    if (!cls || !containsOffset(cls->span, offset)) {
      continue;
    }
    return cls;
  }
  return nullptr;
}
References RootNode::children, and containsOffset().
Referenced by resolveVariableClassType().
findAndReadFlags()
zap::args::CmdlineArgs zap::lsp::findAndReadFlags (std::filesystem::path startPath)
Definition at line 160 of file protocol_utils.cpp.
{
  if (std::filesystem::is_regular_file(startPath)) {
    startPath = startPath.parent_path();
  }
  while (true) {
    auto flagsPath = startPath / "zap_flags.txt";
    if (std::filesystem::exists(flagsPath)) {
      return readFlagsFromFile(flagsPath);
    }
    if (startPath == startPath.parent_path()) {
      break;
    }
    startPath = startPath.parent_path();
  }
  return {};
}
Referenced by zap::lsp::Workspace::analyze(), and zap::lsp::Workspace::loadProject().
findClassDecl()
const ClassDecl * zap::lsp::findClassDecl (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 204 of file language_features.cpp.
{
  for (const auto &child : module.root->children) {
    auto cls = dynamic_cast<const ClassDecl *>(child.get());
    auto topLevel = dynamic_cast<const TopLevel *>(child.get());
    if (!cls || cls->name_ != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    return cls;
  }
  return nullptr;
}
References Public, and sema::ModuleInfo::root.
Referenced by resolveClassInModule().
findClassField()
const ParameterNode * zap::lsp::findClassField (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 427 of file language_features.cpp.
{
  if (!cls) {
    return nullptr;
  }
  for (const auto &field : cls->fields_) {
    if (!field || field->name != member) {
      continue;
    }
    if (publicOnly && field->visibility_ != Visibility::Public) {
      continue;
    }
    return field.get();
  }
  if (cls->baseType_) {
    if (auto base = resolveClassByTypeName(
            project, module, cls->baseType_->qualifiedName(), publicOnly)) {
      return findClassField(base, project, module, member, publicOnly);
    }
  }
  return nullptr;
}
References ClassDecl::baseType_, ClassDecl::fields_, findClassField(), Public, and resolveClassByTypeName().
Referenced by findClassField(), hoverForClassMember(), and resolveDefinition().
findClassMethod()
const FunDecl * zap::lsp::findClassMethod (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 453 of file language_features.cpp.
{
  if (!cls) {
    return nullptr;
  }
  for (const auto &method : cls->methods_) {
    if (!method || method->name_ != member) {
      continue;
    }
    if (publicOnly && method->visibility_ != Visibility::Public) {
      continue;
    }
    return method.get();
  }
  if (cls->baseType_) {
    if (auto base = resolveClassByTypeName(
            project, module, cls->baseType_->qualifiedName(), publicOnly)) {
      return findClassMethod(base, project, module, member, publicOnly);
    }
  }
  return nullptr;
}
References ClassDecl::baseType_, findClassMethod(), ClassDecl::methods_, Public, and resolveClassByTypeName().
Referenced by findClassMethod(), hoverForClassMember(), and resolveDefinition().
findConstructorSignatures()
std::vector< LspSignature > zap::lsp::findConstructorSignatures (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module)
Definition at line 480 of file language_features.cpp.
{
  if (!cls) {
    return {};
  }
  std::vector<LspSignature> signatures;
  for (const auto &method : cls->methods_) {
    if (!method || method->name_ != "init") {
      continue;
    }
    if (auto signature = signatureForNode(method.get())) {
      signatures.push_back(*signature);
    }
  }
  if (!signatures.empty()) {
    return signatures;
  }
  if (cls->baseType_) {
    if (auto base = resolveClassByTypeName(project, module,
                                           cls->baseType_->qualifiedName())) {
      return findConstructorSignatures(base, project, module);
    }
  }
  return {};
}
References ClassDecl::baseType_, findConstructorSignatures(), ClassDecl::methods_, resolveClassByTypeName(), and signatureForNode().
Referenced by findConstructorSignatures(), and resolveSignatures().
findImportedModuleByAlias()
const sema::ModuleInfo * zap::lsp::findImportedModuleByAlias (const ProjectState & project, const sema::ModuleInfo & module, std::string_view alias)
Definition at line 222 of file language_features.cpp.
{
  for (const auto &import : module.imports) {
    for (const auto &targetId : import.targetModuleIds) {
      auto targetIt = project.moduleMap.find(targetId);
      if (targetIt == project.moduleMap.end()) {
        continue;
      }
      if (effectiveImportAlias(import, *targetIt->second) == alias) {
        return targetIt->second.get();
      }
    }
  }
  return nullptr;
}
References effectiveImportAlias(), sema::ModuleInfo::imports, and zap::lsp::ProjectState::moduleMap.
Referenced by resolveClassByTypeName(), and resolveRecordLikeFieldsByTypeName().
findRecordLikeFields()
std::vector< const ParameterNode * > zap::lsp::findRecordLikeFields (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 203 of file completion.cpp.
{
  for (const auto &child : module.root->children) {
    auto topLevel = dynamic_cast<const TopLevel *>(child.get());
    if (auto record = dynamic_cast<const RecordDecl *>(child.get())) {
      if (record->name_ != name ||
          (publicOnly &&
           (!topLevel || topLevel->visibility_ != Visibility::Public))) {
        continue;
      }
      std::vector<const ParameterNode *> fields;
      for (const auto &field : record->fields_) {
        fields.push_back(field.get());
      }
      return fields;
    }
    if (auto strukt =
            dynamic_cast<const StructDeclarationNode *>(child.get())) {
      if (strukt->name_ != name ||
          (publicOnly &&
           (!topLevel || topLevel->visibility_ != Visibility::Public))) {
        continue;
      }
      std::vector<const ParameterNode *> fields;
      for (const auto &field : strukt->fields_) {
        fields.push_back(field.get());
      }
      return fields;
    }
  }
  return {};
}
References Public, and sema::ModuleInfo::root.
Referenced by resolveRecordLikeFieldsInModule().
findTopLevelHover()
std::optional< HoverInfo > zap::lsp::findTopLevelHover (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 865 of file language_features.cpp.
{
  for (const auto &child : module.root->children) {
    const TopLevel *topLevel = dynamic_cast<const TopLevel *>(child.get());
    auto childName = topLevelNameForNode(child.get());
    if (!childName || *childName != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    if (auto hover = hoverForNode(child.get())) {
      return hover;
    }
  }
  return std::nullopt;
}
References hoverForNode(), Public, sema::ModuleInfo::root, topLevelNameForNode(), and TopLevel::visibility_.
Referenced by resolveHover(), and resolveHoverInModuleRecursive().
findTopLevelSignatures()
std::vector< LspSignature > zap::lsp::findTopLevelSignatures (const sema::ModuleInfo & module, std::string_view name, bool publicOnly = false)
Definition at line 147 of file language_features.cpp.
{
  std::vector<LspSignature> signatures;
  for (const auto &child : module.root->children) {
    const TopLevel *topLevel = dynamic_cast<const TopLevel *>(child.get());
    std::optional<std::string> childName;
    if (auto fun = dynamic_cast<const FunDecl *>(child.get())) {
      childName = fun->name_;
    } else if (auto ext = dynamic_cast<const ExtDecl *>(child.get())) {
      childName = ext->name_;
    }
    if (!childName || *childName != name) {
      continue;
    }
    if (publicOnly &&
        (!topLevel || topLevel->visibility_ != Visibility::Public)) {
      continue;
    }
    if (auto signature = signatureForNode(child.get())) {
      signatures.push_back(*signature);
    }
  }
  return signatures;
}
References Public, sema::ModuleInfo::root, signatureForNode(), and TopLevel::visibility_.
Referenced by resolveSignatures(), and resolveSignaturesInModuleRecursive().
findVisibleSymbolInfo()
VisibleSymbolInfo zap::lsp::findVisibleSymbolInfo (const RootNode & root, size_t offset, std::string_view name)
Definition at line 429 of file symbol_index.cpp.
{
  for (const auto &child : root.children) {
    if (!child) {
      continue;
    }
    if (auto var = dynamic_cast<const VarDecl *>(child.get())) {
      if (var->name_ == name && var->span.offset <= offset) {
        return {var, var->type_.get()};
      }
      continue;
    }
    if (auto cnst = dynamic_cast<const ConstDecl *>(child.get())) {
      if (cnst->name_ == name && cnst->span.offset <= offset) {
        return {cnst, cnst->type_.get()};
      }
      continue;
    }
    if (!containsOffset(child->span, offset)) {
      continue;
    }
    if (auto fun = dynamic_cast<const FunDecl *>(child.get())) {
      for (const auto &param : fun->params_) {
        if (param && param->name == name && param->span.offset <= offset) {
          return {param.get(), param->type.get()};
        }
      }
      return findInfoInBody(fun->body_.get(), offset, name);
    }
    if (auto cls = dynamic_cast<const ClassDecl *>(child.get())) {
      for (const auto &field : cls->fields_) {
        if (field && field->name == name && field->span.offset <= offset) {
          return {field.get(), field->type.get()};
        }
      }
      for (const auto &method : cls->methods_) {
        if (!method || !containsOffset(method->span, offset)) {
          continue;
        }
        for (const auto &param : method->params_) {
          if (param && param->name == name && param->span.offset <= offset) {
            return {param.get(), param->type.get()};
          }
        }
        return findInfoInBody(method->body_.get(), offset, name);
      }
    }
  }
  return {};
}
References RootNode::children, and containsOffset().
Referenced by findVisibleTypeNode(), resolveVariableClassType(), and resolveVariableRecordType().
findVisibleTypeNode()
const TypeNode * zap::lsp::findVisibleTypeNode (const RootNode & root, size_t offset, std::string_view name)
Definition at line 480 of file symbol_index.cpp.
{
  return findVisibleSymbolInfo(root, offset, name).typeNode;
}
References findVisibleSymbolInfo(), and zap::lsp::VisibleSymbolInfo::typeNode.
getField()
const JsonObject * zap::lsp::getField (const JsonObject & object, std::string_view key)
Definition at line 10 of file protocol_utils.cpp.
{
  if (!object.isObject()) {
    return nullptr;
  }
  auto it = object.getAsObject().find(std::string(key));
  return it == object.getAsObject().end() ? nullptr : &it->second;
}
References zap::lsp::JsonObject::getAsObject().
Referenced by getPath(), and main().
getIntegerField()
std::optional< int64_t > zap::lsp::getIntegerField (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 41 of file protocol_utils.cpp.
{
  const JsonObject *value = getPath(object, path);
  if (!value || !value->isInteger()) {
    return std::nullopt;
  }
  return value->getAsInteger();
}
References zap::lsp::JsonObject::getAsInteger(), getPath(), and zap::lsp::JsonObject::isInteger().
Referenced by main().
getPath()
const JsonObject * zap::lsp::getPath (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 18 of file protocol_utils.cpp.
{
  const JsonObject *current = &object;
  for (std::string_view key : path) {
    current = getField(*current, key);
    if (!current) {
      return nullptr;
    }
  }
  return current;
}
References getField().
Referenced by getIntegerField(), getStringField(), and main().
getStringField()
std::optional< std::string > zap::lsp::getStringField (const JsonObject & object, std::initializer_list< std::string_view > path)
Definition at line 31 of file protocol_utils.cpp.
{
  const JsonObject *value = getPath(object, path);
  if (!value || !value->isString()) {
    return std::nullopt;
  }
  return value->getAsString();
}
References zap::lsp::JsonObject::getAsString(), getPath(), and zap::lsp::JsonObject::isString().
Referenced by main().
hoverForClassMember()
std::optional< HoverInfo > zap::lsp::hoverForClassMember (const ClassDecl * cls, const ProjectState & project, const sema::ModuleInfo & module, std::string_view member, bool publicOnly = false)
Definition at line 508 of file language_features.cpp.
{
  if (auto method = findClassMethod(cls, project, module, member, publicOnly)) {
    if (auto signature = signatureForNode(method)) {
      return HoverInfo{"zap", signature->label};
    }
  }
  if (auto field = findClassField(cls, project, module, member, publicOnly)) {
    return HoverInfo{"zap", field->name + ": " + renderType(field->type.get())};
  }
  return std::nullopt;
}
References findClassField(), findClassMethod(), renderType(), and signatureForNode().
Referenced by resolveHover().
hoverForNode()
std::optional< HoverInfo > zap::lsp::hoverForNode (const Node * node)
Definition at line 747 of file language_features.cpp.
{
  if (dynamic_cast<const FunDecl *>(node)) {
    if (auto signature = signatureForNode(node)) {
      return HoverInfo{"zap", signature->label};
    }
  }
  if (dynamic_cast<const ExtDecl *>(node)) {
    if (auto signature = signatureForNode(node)) {
      return HoverInfo{"zap", "ext fun " + signature->label};
    }
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return HoverInfo{"zap",
                     "var " + var->name_ + ": " + renderType(var->type_.get())};
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return HoverInfo{"zap", "const " + cnst->name_ + ": " +
                                renderType(cnst->type_.get())};
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    std::string hover = "record " + record->name_;
    if (!record->genericParams_.empty()) {
      hover += "<";
      for (size_t i = 0; i < record->genericParams_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += record->genericParams_[i]
                     ? record->genericParams_[i]->qualifiedName()
                     : std::string("?");
      }
      hover += ">";
    }
    if (!record->genericConstraints_.empty()) {
      hover += " where ";
      for (size_t i = 0; i < record->genericConstraints_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += record->genericConstraints_[i].parameterName + ": ";
        hover +=
            record->genericConstraints_[i].boundType
                ? renderType(record->genericConstraints_[i].boundType.get())
                : std::string("?");
      }
    }
    return HoverInfo{"zap", hover};
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    std::string hover = "struct " + strukt->name_;
    if (!strukt->genericParams_.empty()) {
      hover += "<";
      for (size_t i = 0; i < strukt->genericParams_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += strukt->genericParams_[i]
                     ? strukt->genericParams_[i]->qualifiedName()
                     : std::string("?");
      }
      hover += ">";
    }
    if (!strukt->genericConstraints_.empty()) {
      hover += " where ";
      for (size_t i = 0; i < strukt->genericConstraints_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += strukt->genericConstraints_[i].parameterName + ": ";
        hover +=
            strukt->genericConstraints_[i].boundType
                ? renderType(strukt->genericConstraints_[i].boundType.get())
                : std::string("?");
      }
    }
    return HoverInfo{"zap", hover};
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    std::string hover = "class " + cls->name_;
    if (!cls->genericParams_.empty()) {
      hover += "<";
      for (size_t i = 0; i < cls->genericParams_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += cls->genericParams_[i]
                     ? cls->genericParams_[i]->qualifiedName()
                     : std::string("?");
      }
      hover += ">";
    }
    if (cls->baseType_) {
      hover += " : " + renderType(cls->baseType_.get());
    }
    if (!cls->genericConstraints_.empty()) {
      hover += " where ";
      for (size_t i = 0; i < cls->genericConstraints_.size(); ++i) {
        if (i != 0) {
          hover += ", ";
        }
        hover += cls->genericConstraints_[i].parameterName + ": ";
        hover += cls->genericConstraints_[i].boundType
                     ? renderType(cls->genericConstraints_[i].boundType.get())
                     : std::string("?");
      }
    }
    return HoverInfo{"zap", hover};
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return HoverInfo{"zap", "enum " + enm->name_};
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return HoverInfo{"zap", "alias " + alias->name_ + " = " +
                                renderType(alias->type_.get())};
  }
  return std::nullopt;
}
References renderType(), and signatureForNode().
Referenced by findTopLevelHover().
identifierAt()
std::optional< std::string > zap::lsp::identifierAt (const std::string & source, size_t offset)
Definition at line 205 of file protocol_utils.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = offset < source.size() ? offset : source.size() - 1;
  if (!isIdentifierChar(source[pos])) {
    if (pos == 0 || !isIdentifierChar(source[pos - 1])) {
      return std::nullopt;
    }
    --pos;
  }
  size_t start = pos;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  size_t end = pos + 1;
  while (end < source.size() && isIdentifierChar(source[end])) {
    ++end;
  }
  return source.substr(start, end - start);
}
References isIdentifierChar().
Referenced by resolveDefinition(), and resolveHover().
isClassTypeName()
bool zap::lsp::isClassTypeName (const ProjectState & project, const sema::ModuleInfo & module, std::string_view typeName)
Definition at line 328 of file language_features.cpp.
{
  return resolveClassByTypeName(project, module, typeName) != nullptr;
}
References resolveClassByTypeName().
Referenced by resolveClassTypeNameFromSemanticType(), and resolveClassTypeNameFromTypeNode().
isIdentifierChar()
bool zap::lsp::isIdentifierChar (char ch)
Definition at line 201 of file protocol_utils.cpp.
{
  return std::isalnum(static_cast<unsigned char>(ch)) || ch == '_';
}
Referenced by callContextAtOffset(), callContextNearOffset(), identifierAt(), memberAccessAtCursor(), memberAccessBeforeCursor(), qualifiedIdentifierAtOffset(), structLiteralCompletionAtCursor(), and typeNameBeforeBrace().
makeCompletionItem()
JsonObject zap::lsp::makeCompletionItem (const LspSymbol & symbol, const std::string & detail)
Definition at line 55 of file protocol_messages.cpp.
{
  JsonObject::Object item;
  item.emplace("label", JsonObject(symbol.name));
  item.emplace("kind", JsonObject(symbol.completionKind));
  if (!detail.empty()) {
    item.emplace("detail", JsonObject(detail));
  }
  return JsonObject(std::move(item));
}
References zap::lsp::LspSymbol::completionKind, and zap::lsp::LspSymbol::name.
Referenced by makeCompletionItems().
makeCompletionItems()
JsonObject::List zap::lsp::makeCompletionItems (const std::string & uri, const std::string & source, const ProjectState & project, size_t offset)
Definition at line 345 of file completion.cpp.
{
  JsonObject::List items;
  std::string moduleId;
  auto path = uriToPath(uri);
  if (path) {
    moduleId = std::filesystem::weakly_canonical(*path).string();
  }
  auto moduleIt = project.moduleMap.find(moduleId);
  if (auto literal = structLiteralCompletionAtCursor(source, offset);
      literal && moduleIt != project.moduleMap.end()) {
    auto fields = resolveRecordLikeFieldsByTypeName(project, *moduleIt->second,
                                                    literal->typeName);
    if (!fields.empty()) {
      std::set<std::string> seenFields;
      for (const auto *field : fields) {
        if (!field || !matchesPrefix(field->name, literal->fieldPrefix) ||
            literal->initializedFields.count(field->name) ||
            !seenFields.insert(field->name).second) {
          continue;
        }
        items.push_back(makeCompletionItem(
            *makeSymbol(uri, field->name, field->span, 8, field->visibility_),
            "field"));
      }
      return items;
    }
  }
  if (auto member = memberAccessAtCursor(source, offset)) {
    const auto &[base, memberPrefix] = *member;
    if (moduleIt == project.moduleMap.end()) {
      return items;
    }
    std::set<std::string> seenImportedMembers;
    for (const auto &import : moduleIt->second->imports) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt == project.moduleMap.end()) {
          continue;
        }
        if (effectiveImportAlias(import, *targetIt->second) != base) {
          continue;
        }
        std::set<std::string> visited;
        for (const auto &symbol : collectExportedSymbolsRecursive(
                 project, *targetIt->second, visited)) {
          if (!matchesPrefix(symbol.name, memberPrefix)) {
            continue;
          }
          if (!seenImportedMembers.insert(symbol.name).second) {
            continue;
          }
          items.push_back(makeCompletionItem(symbol, "imported member"));
        }
      }
    }
    if (base.find('.') == std::string::npos) {
      if (auto classType = resolveVariableClassType(project, *moduleIt->second,
                                                    offset, base)) {
        if (auto cls = resolveClassByTypeName(project, *moduleIt->second,
                                              *classType, false)) {
          std::set<std::string> seenMembers;
          const ClassDecl *current = cls;
          while (current) {
            for (const auto &field : current->fields_) {
              if (!field || !matchesPrefix(field->name, memberPrefix) ||
                  !seenMembers.insert(field->name).second) {
                continue;
              }
              items.push_back(
                  makeCompletionItem(*makeSymbol(uri, field->name, field->span,
                                                 8, field->visibility_),
                                     "field"));
            }
            for (const auto &method : current->methods_) {
              if (!method || !matchesPrefix(method->name_, memberPrefix) ||
                  !seenMembers.insert(method->name_).second) {
                continue;
              }
              auto detail = method->name_;
              if (auto signature = signatureForNode(method.get())) {
                detail = signature->label;
              }
              items.push_back(makeCompletionItem(
                  *makeSymbol(uri, method->name_, method->span, 2,
                              method->visibility_),
                  detail));
            }
            if (!current->baseType_) {
              break;
            }
            current = resolveClassByTypeName(
                project, *moduleIt->second, current->baseType_->qualifiedName(),
                false);
          }
        }
      }
    }
    if (auto recordType = resolveVariableRecordType(project, *moduleIt->second,
                                                    offset, base)) {
      std::set<std::string> seenFields;
      for (const auto &field : recordType->getFields()) {
        if (!matchesPrefix(field.name, memberPrefix) ||
            !seenFields.insert(field.name).second) {
          continue;
        }
        items.push_back(makeCompletionItem(
            *makeSymbol(uri, field.name, SourceSpan(), 8, Visibility::Private),
            "field"));
      }
    }
    return items;
  }
  std::vector<LspSymbol> symbols =
      collectCompletionSymbols(uri, project, offset);
  std::set<std::string> seen;
  static constexpr const char *keywords[] = {
      "fun",   "return", "if",    "else",  "iftype", "while",  "var",
      "const", "import", "pub",   "priv",  "prot",   "struct", "record",
      "class", "enum",   "alias", "ext",   "global", "break",  "continue",
      "ref",   "as",     "new",   "self",  "where",  "unsafe", "weak",
      "fail",  "or",     "for",   "match", "module", "impl",   "static"};
  for (const char *keyword : keywords) {
    if (seen.insert(keyword).second) {
      items.push_back(makeCompletionItem(
          *makeSymbol(uri, keyword, SourceSpan(), 14, Visibility::Private),
          "keyword"));
    }
  }
  for (const auto &symbol : symbols) {
    if (seen.insert(symbol.name).second) {
      items.push_back(makeCompletionItem(symbol));
    }
  }
  return items;
}
References ClassDecl::baseType_, collectCompletionSymbols(), collectExportedSymbolsRecursive(), effectiveImportAlias(), ClassDecl::fields_, makeCompletionItem(), makeSymbol(), matchesPrefix(), memberAccessAtCursor(), ClassDecl::methods_, zap::lsp::ProjectState::moduleMap, Private, resolveClassByTypeName(), resolveRecordLikeFieldsByTypeName(), resolveVariableClassType(), resolveVariableRecordType(), signatureForNode(), structLiteralCompletionAtCursor(), and uriToPath().
Referenced by main().
makeDiagnostic()
JsonObject zap::lsp::makeDiagnostic (const zap::Diagnostic & diagnostic)
Definition at line 132 of file protocol_messages.cpp.
{
  JsonObject::Object object;
  object.emplace("range", makeRange(diagnostic.range));
  object.emplace("severity", JsonObject(toLspSeverity(diagnostic.level)));
  object.emplace("source", JsonObject("zap-lsp"));
  object.emplace("message", JsonObject(diagnostic.message));
  if (!diagnostic.code.empty()) {
    object.emplace("code", JsonObject(diagnostic.code));
  }
  return JsonObject(std::move(object));
}
References zap::Diagnostic::code, zap::Diagnostic::level, makeRange(), zap::Diagnostic::message, zap::Diagnostic::range, and toLspSeverity().
Referenced by makePublishDiagnostics().
makeHover()
JsonObject zap::lsp::makeHover (const HoverInfo & hover)
Definition at line 66 of file protocol_messages.cpp.
{
  JsonObject::Object contents;
  contents.emplace("kind", JsonObject("markdown"));
  contents.emplace("value", JsonObject("```" + hover.language + "\n" +
                                       hover.value + "\n```"));
  JsonObject::Object result;
  result.emplace("contents", JsonObject(std::move(contents)));
  return JsonObject(std::move(result));
}
References zap::lsp::HoverInfo::language, and zap::lsp::HoverInfo::value.
Referenced by main().
makeLocation()
JsonObject zap::lsp::makeLocation (const std::string & uri, const SourceSpan & span)
Definition at line 44 of file protocol_messages.cpp.
{
  zap::DiagnosticRange range{{span.line, span.column, span.offset},
                             {span.line,
                              span.column + std::max<size_t>(span.length, 1),
                              span.offset + span.length}};
  JsonObject::Object object;
  object.emplace("uri", JsonObject(uri));
  object.emplace("range", makeRange(range));
  return JsonObject(std::move(object));
}
References SourceSpan::column, SourceSpan::length, SourceSpan::line, makeRange(), and SourceSpan::offset.
Referenced by main().
makeNotification()
JsonObject zap::lsp::makeNotification (std::string method, JsonObject params)
Definition at line 15 of file protocol_messages.cpp.
{
  JsonObject::Object object;
  object.emplace("jsonrpc", JsonObject("2.0"));
  object.emplace("method", JsonObject(std::move(method)));
  object.emplace("params", std::move(params));
  return JsonObject(std::move(object));
}
Referenced by makePublishDiagnostics().
makePublishDiagnostics()
JsonObject zap::lsp::makePublishDiagnostics (std::string uri, const std::vector< zap::Diagnostic > & diagnostics)
Definition at line 145 of file protocol_messages.cpp.
{
  JsonObject::List items;
  items.reserve(diagnostics.size());
  for (const auto &diagnostic : diagnostics) {
    items.push_back(makeDiagnostic(diagnostic));
  }
  JsonObject::Object params;
  params.emplace("uri", JsonObject(std::move(uri)));
  params.emplace("diagnostics", JsonObject(std::move(items)));
  return makeNotification("textDocument/publishDiagnostics",
                          JsonObject(std::move(params)));
}
References makeDiagnostic(), and makeNotification().
Referenced by main(), and publishAnalysis().
makeRange()
JsonObject zap::lsp::makeRange (const zap::DiagnosticRange & range)
Definition at line 23 of file protocol_messages.cpp.
{
  JsonObject::Object start;
  start.emplace("line", JsonObject(static_cast<int64_t>(
                            range.start.line > 0 ? range.start.line - 1 : 0)));
  start.emplace("character",
                JsonObject(static_cast<int64_t>(
                    range.start.column > 0 ? range.start.column - 1 : 0)));
  JsonObject::Object end;
  end.emplace("line", JsonObject(static_cast<int64_t>(
                          range.end.line > 0 ? range.end.line - 1 : 0)));
  end.emplace("character",
              JsonObject(static_cast<int64_t>(
                  range.end.column > 0 ? range.end.column - 1 : 0)));
  JsonObject::Object object;
  object.emplace("start", JsonObject(std::move(start)));
  object.emplace("end", JsonObject(std::move(end)));
  return JsonObject(std::move(object));
}
References zap::DiagnosticPosition::column, zap::DiagnosticRange::end, zap::DiagnosticPosition::line, and zap::DiagnosticRange::start.
Referenced by makeDiagnostic(), and makeLocation().
makeResponse()
JsonObject zap::lsp::makeResponse (const JsonObject * id, JsonObject result)
Definition at line 7 of file protocol_messages.cpp.
{
  JsonObject::Object object;
  object.emplace("jsonrpc", JsonObject("2.0"));
  object.emplace("id", id ? *id : JsonObject(nullptr));
  object.emplace("result", std::move(result));
  return JsonObject(std::move(object));
}
Referenced by main().
makeSignatureHelp()
JsonObject zap::lsp::makeSignatureHelp (const std::vector< LspSignature > & signatures, int64_t activeSignature, int64_t activeParameter)
Definition at line 77 of file protocol_messages.cpp.
{
  JsonObject::List signatureItems;
  signatureItems.reserve(signatures.size());
  for (const auto &signature : signatures) {
    JsonObject::List parameters;
    parameters.reserve(signature.parameters.size());
    for (const auto &param : signature.parameters) {
      JsonObject::Object parameter;
      parameter.emplace("label", JsonObject(param));
      parameters.push_back(JsonObject(std::move(parameter)));
    }
    JsonObject::Object sig;
    sig.emplace("label", JsonObject(signature.label));
    sig.emplace("parameters", JsonObject(std::move(parameters)));
    signatureItems.push_back(JsonObject(std::move(sig)));
  }
  int64_t clampedSignature =
      signatures.empty()
          ? 0
          : std::max<int64_t>(0, std::min<int64_t>(activeSignature,
                                                   static_cast<int64_t>(
                                                       signatures.size() - 1)));
  int64_t clampedParameter = 0;
  if (!signatures.empty()) {
    clampedParameter = std::max<int64_t>(
        0, std::min<int64_t>(
               activeParameter,
               static_cast<int64_t>(
                   signatures[clampedSignature].parameters.empty()
                       ? 0
                       : signatures[clampedSignature].parameters.size() - 1)));
  }
  JsonObject::Object result;
  result.emplace("signatures", JsonObject(std::move(signatureItems)));
  result.emplace("activeSignature", JsonObject(clampedSignature));
  result.emplace("activeParameter", JsonObject(clampedParameter));
  return JsonObject(std::move(result));
}
Referenced by main().
makeSymbol()
std::optional< LspSymbol > zap::lsp::makeSymbol (const std::string & uri, const std::string & name, const SourceSpan & span, int64_t kind, Visibility visibility = Visibility::Private)
Definition at line 24 of file language_features.cpp.
{
  return LspSymbol{name, uri, span, kind, visibility};
}
References Private.
Referenced by collectCompletionSymbols(), collectImportedSymbols(), makeCompletionItems(), resolveDefinition(), and topLevelSymbolForNode().
matchesPrefix()
bool zap::lsp::matchesPrefix (std::string_view name, std::string_view prefix)
Definition at line 17 of file completion.cpp.
{
  return prefix.empty() || name.rfind(prefix, 0) == 0;
}
References prefix.
Referenced by makeCompletionItems().
memberAccessAtCursor()
std::optional< std::pair< std::string, std::string > > zap::lsp::memberAccessAtCursor (const std::string & source, size_t offset)
Definition at line 282 of file protocol_utils.cpp.
{
  if (offset == 0 || offset > source.size()) {
    return std::nullopt;
  }
  size_t pos = offset;
  while (pos > 0 && std::isspace(static_cast<unsigned char>(source[pos - 1]))) {
    --pos;
  }
  std::string memberPrefix;
  if (pos > 0 && isIdentifierChar(source[pos - 1])) {
    size_t prefixEnd = pos;
    size_t prefixStart = prefixEnd;
    while (prefixStart > 0 && isIdentifierChar(source[prefixStart - 1])) {
      --prefixStart;
    }
    memberPrefix = source.substr(prefixStart, prefixEnd - prefixStart);
    pos = prefixStart;
  }
  if (pos == 0 || source[pos - 1] != '.') {
    return std::nullopt;
  }
  size_t end = pos - 1;
  size_t start = end;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  if (start == end) {
    return std::nullopt;
  }
  std::string base = source.substr(start, end - start);
  size_t left = start;
  while (left > 1) {
    size_t dot = left;
    while (dot > 0 &&
           std::isspace(static_cast<unsigned char>(source[dot - 1]))) {
      --dot;
    }
    if (dot == 0 || source[dot - 1] != '.') {
      break;
    }
    size_t nameEnd = dot - 1;
    size_t nameStart = nameEnd;
    while (nameStart > 0 && isIdentifierChar(source[nameStart - 1])) {
      --nameStart;
    }
    if (nameStart == nameEnd) {
      break;
    }
    base = source.substr(nameStart, end - nameStart);
    left = nameStart;
  }
  size_t split = base.find('.');
  if (split != std::string::npos) {
    base = base.substr(0, split);
  }
  return std::make_pair(base, memberPrefix);
}
References isIdentifierChar().
Referenced by makeCompletionItems().
memberAccessBeforeCursor()
std::optional< std::pair< std::string, std::string > > zap::lsp::memberAccessBeforeCursor (const std::string & source, size_t offset)
Definition at line 230 of file protocol_utils.cpp.
{
  if (offset == 0 || offset > source.size()) {
    return std::nullopt;
  }
  size_t pos = offset;
  while (pos > 0 && std::isspace(static_cast<unsigned char>(source[pos - 1]))) {
    --pos;
  }
  if (pos == 0 || source[pos - 1] != '.') {
    return std::nullopt;
  }
  size_t end = pos - 1;
  size_t start = end;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  if (start == end) {
    return std::nullopt;
  }
  std::string base = source.substr(start, end - start);
  size_t left = start;
  while (left > 1) {
    size_t dot = left;
    while (dot > 0 &&
           std::isspace(static_cast<unsigned char>(source[dot - 1]))) {
      --dot;
    }
    if (dot == 0 || source[dot - 1] != '.') {
      break;
    }
    size_t nameEnd = dot - 1;
    size_t nameStart = nameEnd;
    while (nameStart > 0 && isIdentifierChar(source[nameStart - 1])) {
      --nameStart;
    }
    if (nameStart == nameEnd) {
      break;
    }
    base = source.substr(nameStart, end - nameStart);
    left = nameStart;
  }
  size_t split = base.find('.');
  if (split == std::string::npos) {
    return std::make_pair(base, std::string());
  }
  return std::make_pair(base.substr(0, split), base.substr(split + 1));
}
References isIdentifierChar().
offsetFromPosition()
size_t zap::lsp::offsetFromPosition (const std::string & text, int64_t line, int64_t character)
Definition at line 178 of file protocol_utils.cpp.
{
  size_t offset = 0;
  int64_t currentLine = 0;
  while (offset < text.size() && currentLine < line) {
    if (text[offset++] == '\n') {
      ++currentLine;
    }
  }
  int64_t currentChar = 0;
  while (offset < text.size() && currentChar < character &&
         text[offset] != '\n') {
    ++offset;
    ++currentChar;
  }
  return offset;
}
Referenced by main().
pathToUri()
std::string zap::lsp::pathToUri (const std::filesystem::path & path)
Definition at line 95 of file protocol_utils.cpp.
{
  std::string uri = "file://";
  std::string text = path.generic_string();
  for (unsigned char ch : text) {
    bool unreserved = (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') ||
                      (ch >= '0' && ch <= '9') || ch == '/' || ch == '-' ||
                      ch == '_' || ch == '.' || ch == '~';
    if (unreserved) {
      uri.push_back(static_cast<char>(ch));
    } else {
      static constexpr char hex[] = "0123456789ABCDEF";
      uri.push_back('%');
      uri.push_back(hex[(ch >> 4) & 0x0F]);
      uri.push_back(hex[ch & 0x0F]);
    }
  }
  return uri;
}
Referenced by collectExportedSymbolsRecursive(), collectImportedSymbols(), zap::lsp::Workspace::loadProject(), and resolveDefinition().
publishAnalysis()
void zap::lsp::publishAnalysis (Server & server, const AnalysisResult & result)
Definition at line 160 of file protocol_messages.cpp.
{
  for (const auto &[uri, diagnostics] : result.diagnosticsByUri) {
    server.sendMessage(makePublishDiagnostics(uri, diagnostics));
  }
}
References zap::lsp::AnalysisResult::diagnosticsByUri, makePublishDiagnostics(), and zap::lsp::Server::sendMessage().
Referenced by main().
qualifiedIdentifierAtOffset()
std::optional< std::pair< std::string, std::string > > zap::lsp::qualifiedIdentifierAtOffset (const std::string & source, size_t offset)
Definition at line 347 of file protocol_utils.cpp.
{
  if (source.empty()) {
    return std::nullopt;
  }
  size_t pos = offset < source.size() ? offset : source.size() - 1;
  if (!isIdentifierChar(source[pos])) {
    if (pos == 0 || !isIdentifierChar(source[pos - 1])) {
      return std::nullopt;
    }
    --pos;
  }
  size_t start = pos;
  while (start > 0 && isIdentifierChar(source[start - 1])) {
    --start;
  }
  size_t end = pos + 1;
  while (end < source.size() && isIdentifierChar(source[end])) {
    ++end;
  }
  while (start > 1) {
    size_t dot = start;
    while (dot > 0 &&
           std::isspace(static_cast<unsigned char>(source[dot - 1]))) {
      --dot;
    }
    if (dot == 0 || source[dot - 1] != '.') {
      break;
    }
    size_t nameEnd = dot - 1;
    size_t nameStart = nameEnd;
    while (nameStart > 0 && isIdentifierChar(source[nameStart - 1])) {
      --nameStart;
    }
    if (nameStart == nameEnd) {
      break;
    }
    start = nameStart;
  }
  while (end < source.size()) {
    size_t dot = end;
    while (dot < source.size() &&
           std::isspace(static_cast<unsigned char>(source[dot]))) {
      ++dot;
    }
    if (dot >= source.size() || source[dot] != '.') {
      break;
    }
    size_t nameStart = dot + 1;
    while (nameStart < source.size() &&
           std::isspace(static_cast<unsigned char>(source[nameStart]))) {
      ++nameStart;
    }
    size_t nameEnd = nameStart;
    while (nameEnd < source.size() && isIdentifierChar(source[nameEnd])) {
      ++nameEnd;
    }
    if (nameEnd == nameStart) {
      break;
    }
    end = nameEnd;
  }
  std::string text = source.substr(start, end - start);
  size_t split = text.find('.');
  if (split == std::string::npos) {
    return std::make_pair(text, std::string());
  }
  return std::make_pair(text.substr(0, split), text.substr(split + 1));
}
References isIdentifierChar().
Referenced by resolveDefinition(), and resolveHover().
readSourceFile()
bool zap::lsp::readSourceFile (const std::filesystem::path & path, std::string & content)
Definition at line 114 of file protocol_utils.cpp.
{
  std::ifstream file(path, std::ios::binary | std::ios::ate);
  if (!file) {
    return false;
  }
  auto size = file.tellg();
  content.assign(static_cast<size_t>(std::max<std::streamsize>(size, 0)), '\0');
  if (size > 0) {
    file.seekg(0);
    file.read(content.data(), size);
  }
  return true;
}
Referenced by zap::lsp::Workspace::sourceForPath().
renderParameter()
std::string zap::lsp::renderParameter (const ParameterNode * param)
Definition at line 63 of file language_features.cpp.
{
  if (!param) {
    return "";
  }
  std::string prefix = param->isRef ? "ref " : "";
  if (param->isVariadic) {
    return prefix + param->name + ": ..." + renderType(param->type.get());
  }
  return prefix + param->name + ": " + renderType(param->type.get());
}
References ParameterNode::isRef, ParameterNode::isVariadic, ParameterNode::name, prefix, renderType(), and ParameterNode::type.
Referenced by signatureForNode().
renderType()
std::string zap::lsp::renderType (const TypeNode * type)
Definition at line 30 of file language_features.cpp.
{
  if (!type) {
    return "Void";
  }
  if (type->isVarArgs && type->baseType) {
    return "..." + renderType(type->baseType.get());
  }
  if (type->isPointer && type->baseType) {
    return "*" + renderType(type->baseType.get());
  }
  if (type->isArray && type->baseType) {
    std::string size = type->arraySize ? "?" : "?";
    return "[" + size + "]" + renderType(type->baseType.get());
  }
  std::string qualified = type->qualifiedName();
  if (!type->genericArgs.empty()) {
    qualified += "<";
    for (size_t i = 0; i < type->genericArgs.size(); ++i) {
      if (i != 0) {
        qualified += ", ";
      }
      qualified += renderType(type->genericArgs[i].get());
    }
    qualified += ">";
  }
  if (type->isWeak) {
    return "weak " + qualified;
  }
  return qualified;
}
References TypeNode::arraySize, TypeNode::baseType, TypeNode::genericArgs, TypeNode::isArray, TypeNode::isPointer, TypeNode::isVarArgs, TypeNode::isWeak, TypeNode::qualifiedName(), and renderType().
Referenced by hoverForClassMember(), hoverForNode(), renderParameter(), renderType(), resolveClassTypeNameFromTypeNode(), and signatureForNode().
resolveClassByTypeName()
const ClassDecl * zap::lsp::resolveClassByTypeName (const ProjectState & project, const sema::ModuleInfo & module, std::string_view typeName, bool publicOnly = false)
Definition at line 305 of file language_features.cpp.
{
  std::string normalizedTypeName = stripGenericArguments(typeName);
  auto [qualifier, localName] = splitQualifiedName(normalizedTypeName);
  if (localName.empty()) {
    return nullptr;
  }
  if (qualifier.empty()) {
    std::set<std::string> visited;
    return resolveClassInModule(project, module, localName, publicOnly,
                                visited);
  }
  auto importedModule = findImportedModuleByAlias(project, module, qualifier);
  if (!importedModule) {
    return nullptr;
  }
  std::set<std::string> visited;
  return resolveClassInModule(project, *importedModule, localName, publicOnly,
                              visited);
}
References findImportedModuleByAlias(), resolveClassInModule(), splitQualifiedName(), and stripGenericArguments().
Referenced by findClassField(), findClassMethod(), findConstructorSignatures(), isClassTypeName(), makeCompletionItems(), resolveDefinition(), resolveHover(), and resolveSignatures().
resolveClassInModule()
const ClassDecl * zap::lsp::resolveClassInModule (const ProjectState & project, const sema::ModuleInfo & module, std::string_view name, bool publicOnly, std::set< std::string > & visited)
Definition at line 239 of file language_features.cpp.
{
  std::string moduleId = module.moduleId;
  if (visited.count(moduleId)) {
    return nullptr;
  }
  visited.insert(moduleId);
  if (auto cls = findClassDecl(module, name, publicOnly)) {
    return cls;
  }
  for (const auto &import : module.imports) {
    bool isImplicitPreludeImport =
        import.rawPath == "std/prelude" && import.moduleAlias.empty();
    if (isImplicitPreludeImport) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt != project.moduleMap.end()) {
          if (auto cls = resolveClassInModule(project, *targetIt->second, name,
                                              true, visited)) {
            return cls;
          }
        }
      }
    }
    for (const auto &binding : import.bindings) {
      if (binding.localName == name) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt != project.moduleMap.end()) {
            if (auto cls =
                    resolveClassInModule(project, *targetIt->second,
                                         binding.sourceName, true, visited)) {
              return cls;
            }
          }
        }
      }
    }
  }
  return nullptr;
}
References findClassDecl(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, and resolveClassInModule().
Referenced by resolveClassByTypeName(), and resolveClassInModule().
resolveClassTypeNameFromSemanticType()
std::optional< std::string > zap::lsp::resolveClassTypeNameFromSemanticType (const ProjectState & project, const sema::ModuleInfo & module, const std::shared_ptr< zir::Type > & type)
Definition at line 349 of file language_features.cpp.
{
  if (!type || type->getKind() != zir::TypeKind::Class) {
    return std::nullopt;
  }
  auto classType = std::static_pointer_cast<zir::ClassType>(type);
  std::string name = classType->getName();
  if (isClassTypeName(project, module, name)) {
    return stripGenericArguments(name);
  }
  if (classType->isGenericInstance()) {
    const std::string &baseName = classType->getGenericBaseName();
    if (isClassTypeName(project, module, baseName)) {
      return stripGenericArguments(baseName);
    }
    auto [__, baseLocalName] = splitQualifiedName(baseName);
    if (!baseLocalName.empty() &&
        isClassTypeName(project, module, baseLocalName)) {
      return stripGenericArguments(baseLocalName);
    }
  }
  auto [_, localName] = splitQualifiedName(name);
  std::string normalizedLocalName = stripGenericArguments(localName);
  if (!normalizedLocalName.empty() &&
      isClassTypeName(project, module, normalizedLocalName)) {
    return normalizedLocalName;
  }
  return std::nullopt;
}
References zir::Class, isClassTypeName(), splitQualifiedName(), and stripGenericArguments().
Referenced by resolveVariableClassType().
resolveClassTypeNameFromTypeNode()
std::optional< std::string > zap::lsp::resolveClassTypeNameFromTypeNode (const ProjectState & project, const sema::ModuleInfo & module, const TypeNode * type)
Definition at line 335 of file language_features.cpp.
{
  if (!type) {
    return std::nullopt;
  }
  std::string qualified = renderType(type);
  if (!isClassTypeName(project, module, qualified)) {
    return std::nullopt;
  }
  return qualified;
}
References isClassTypeName(), and renderType().
Referenced by resolveVariableClassType().
resolveDefinition()
std::optional< LspSymbol > zap::lsp::resolveDefinition (const Workspace & workspace, const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 1152 of file language_features.cpp.
{
  const DocumentState *document = workspace.document(uri);
  if (!document) {
    return std::nullopt;
  }
  auto path = uriToPath(uri);
  if (!path) {
    return std::nullopt;
  }
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return std::nullopt;
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  if (auto qualified = qualifiedIdentifierAtOffset(document->text, offset)) {
    const auto &[base, rest] = *qualified;
    if (!rest.empty()) {
      std::string memberName = rest;
      size_t dot = memberName.rfind('.');
      if (dot != std::string::npos) {
        memberName = memberName.substr(dot + 1);
      }
      for (const auto &import : module.imports) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt == project.moduleMap.end()) {
            continue;
          }
          if (effectiveImportAlias(import, *targetIt->second) != base) {
            continue;
          }
          auto targetUriIt = project.uriByModuleId.find(targetId);
          std::string targetUri = targetUriIt == project.uriByModuleId.end()
                                      ? pathToUri(targetId)
                                      : targetUriIt->second;
          std::set<std::string> visited;
          auto exported = collectExportedSymbolsRecursive(
              project, *targetIt->second, visited);
          auto exportIt = std::find_if(exported.begin(), exported.end(),
                                       [&](const LspSymbol &symbol) {
                                         return symbol.name == memberName;
                                       });
          if (exportIt != exported.end()) {
            return *exportIt;
          }
        }
      }
      if (base.find('.') == std::string::npos) {
        if (auto classType =
                resolveVariableClassType(project, module, offset, base)) {
          if (auto cls = resolveClassByTypeName(project, module, *classType)) {
            if (auto field = findClassField(cls, project, module, memberName)) {
              return *makeSymbol(uri, field->name, field->span, 8,
                                 field->visibility_);
            }
            if (auto method =
                    findClassMethod(cls, project, module, memberName)) {
              return *makeSymbol(uri, method->name_, method->span, 2,
                                 method->visibility_);
            }
          }
        }
      }
    }
  }
  auto name = identifierAt(document->text, offset);
  if (!name) {
    return std::nullopt;
  }
  auto locals = collectLocalSymbols(*module.root, offset, uri);
  for (auto it = locals.rbegin(); it != locals.rend(); ++it) {
    if (it->name == *name) {
      return *it;
    }
  }
  auto imported = collectImportedSymbols(project, module);
  for (const auto &symbol : imported) {
    if (symbol.name == *name) {
      return symbol;
    }
  }
  auto topLevel = collectTopLevelSymbols(module, uri);
  for (const auto &symbol : topLevel) {
    if (symbol.name == *name) {
      return symbol;
    }
  }
  return std::nullopt;
}
References collectExportedSymbolsRecursive(), collectImportedSymbols(), collectLocalSymbols(), collectTopLevelSymbols(), zap::lsp::Workspace::document(), effectiveImportAlias(), findClassField(), findClassMethod(), identifierAt(), sema::ModuleInfo::imports, makeSymbol(), zap::lsp::ProjectState::moduleMap, pathToUri(), qualifiedIdentifierAtOffset(), resolveClassByTypeName(), resolveVariableClassType(), sema::ModuleInfo::root, zap::lsp::DocumentState::text, zap::lsp::ProjectState::uriByModuleId, and uriToPath().
Referenced by main().
resolveHover()
std::optional< HoverInfo > zap::lsp::resolveHover (const std::string & source, const std::string & uri, const ProjectState & project, size_t offset)
Definition at line 932 of file language_features.cpp.
{
  auto path = uriToPath(uri);
  if (!path) {
    return std::nullopt;
  }
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return std::nullopt;
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  if (auto qualified = qualifiedIdentifierAtOffset(source, offset)) {
    const auto &[base, rest] = *qualified;
    if (!rest.empty()) {
      std::string memberName = rest;
      size_t dot = memberName.rfind('.');
      if (dot != std::string::npos) {
        memberName = memberName.substr(dot + 1);
      }
      for (const auto &import : module.imports) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt == project.moduleMap.end()) {
            continue;
          }
          if (effectiveImportAlias(import, *targetIt->second) != base) {
            continue;
          }
          if (auto hover =
                  findTopLevelHover(*targetIt->second, memberName, true)) {
            return hover;
          }
        }
      }
      if (base.find('.') == std::string::npos) {
        if (auto classType =
                resolveVariableClassType(project, module, offset, base)) {
          if (auto cls = resolveClassByTypeName(project, module, *classType)) {
            if (auto hover =
                    hoverForClassMember(cls, project, module, memberName)) {
              return hover;
            }
          }
        }
      }
    }
  }
  auto name = identifierAt(source, offset);
  if (!name) {
    return std::nullopt;
  }
  std::set<std::string> visited;
  return resolveHoverInModuleRecursive(project, module, *name, false, visited);
}
References effectiveImportAlias(), findTopLevelHover(), hoverForClassMember(), identifierAt(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, qualifiedIdentifierAtOffset(), resolveClassByTypeName(), resolveHoverInModuleRecursive(), resolveVariableClassType(), and uriToPath().
Referenced by main().
resolveHoverInModuleRecursive()
std::optional< HoverInfo > zap::lsp::resolveHoverInModuleRecursive (const ProjectState & project, const sema::ModuleInfo & module, std::string_view name, bool publicOnly, std::set< std::string > & visited)
Definition at line 885 of file language_features.cpp.
{
  std::string moduleId = module.moduleId;
  if (visited.count(moduleId)) {
    return std::nullopt;
  }
  visited.insert(moduleId);
  if (auto hover = findTopLevelHover(module, name, publicOnly)) {
    return hover;
  }
  for (const auto &import : module.imports) {
    bool isImplicitPreludeImport =
        import.rawPath == "std/prelude" && import.moduleAlias.empty();
    if (isImplicitPreludeImport) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt != project.moduleMap.end()) {
          if (auto hover = resolveHoverInModuleRecursive(
                  project, *targetIt->second, name, true, visited)) {
            return hover;
          }
        }
      }
    }
    for (const auto &binding : import.bindings) {
      if (binding.localName == name) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt != project.moduleMap.end()) {
            if (auto hover = resolveHoverInModuleRecursive(
                    project, *targetIt->second, binding.sourceName, true,
                    visited)) {
              return hover;
            }
          }
        }
      }
    }
  }
  return std::nullopt;
}
References findTopLevelHover(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, and resolveHoverInModuleRecursive().
Referenced by resolveHover(), and resolveHoverInModuleRecursive().
resolveRecordLikeFieldsByTypeName()
std::vector< const ParameterNode * > zap::lsp::resolveRecordLikeFieldsByTypeName (const ProjectState & project, const sema::ModuleInfo & module, std::string_view typeName, bool publicOnly = false)
Definition at line 285 of file completion.cpp.
{
  std::string normalizedTypeName = stripGenericArguments(typeName);
  auto [qualifier, localName] = splitQualifiedName(normalizedTypeName);
  if (localName.empty()) {
    return {};
  }
  if (qualifier.empty()) {
    std::set<std::string> visited;
    return resolveRecordLikeFieldsInModule(project, module, localName,
                                           publicOnly, visited);
  }
  auto importedModule = findImportedModuleByAlias(project, module, qualifier);
  if (!importedModule) {
    return {};
  }
  std::set<std::string> visited;
  return resolveRecordLikeFieldsInModule(project, *importedModule, localName,
                                         publicOnly, visited);
}
References findImportedModuleByAlias(), resolveRecordLikeFieldsInModule(), splitQualifiedName(), and stripGenericArguments().
Referenced by makeCompletionItems().
resolveRecordLikeFieldsInModule()
std::vector< const ParameterNode * > zap::lsp::resolveRecordLikeFieldsInModule (const ProjectState & project, const sema::ModuleInfo & module, std::string_view name, bool publicOnly, std::set< std::string > & visited)
Definition at line 236 of file completion.cpp.
{
  std::string moduleId = module.moduleId;
  if (visited.count(moduleId)) {
    return {};
  }
  visited.insert(moduleId);
  auto fields = findRecordLikeFields(module, name, publicOnly);
  if (!fields.empty()) {
    return fields;
  }
  for (const auto &import : module.imports) {
    bool isImplicitPreludeImport =
        import.rawPath == "std/prelude" && import.moduleAlias.empty();
    if (isImplicitPreludeImport) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt != project.moduleMap.end()) {
          auto importedFields = resolveRecordLikeFieldsInModule(
              project, *targetIt->second, name, true, visited);
          if (!importedFields.empty()) {
            return importedFields;
          }
        }
      }
    }
    for (const auto &binding : import.bindings) {
      if (binding.localName == name) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt != project.moduleMap.end()) {
            auto importedFields = resolveRecordLikeFieldsInModule(
                project, *targetIt->second, binding.sourceName, true, visited);
            if (!importedFields.empty()) {
              return importedFields;
            }
          }
        }
      }
    }
  }
  return {};
}
References findRecordLikeFields(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, and resolveRecordLikeFieldsInModule().
Referenced by resolveRecordLikeFieldsByTypeName(), and resolveRecordLikeFieldsInModule().
resolveSignatures()
std::vector< LspSignature > zap::lsp::resolveSignatures (const std::string & source, const std::string & uri, const ProjectState & project, size_t offset, int64_t & activeParameter)
Definition at line 691 of file language_features.cpp.
{
  auto path = uriToPath(uri);
  if (!path) {
    return {};
  }
  auto call = callContextNearOffset(source, offset);
  if (!call) {
    return {};
  }
  activeParameter = call->activeParameter;
  std::string moduleId = std::filesystem::weakly_canonical(*path).string();
  auto moduleIt = project.moduleMap.find(moduleId);
  if (moduleIt == project.moduleMap.end()) {
    return {};
  }
  const sema::ModuleInfo &module = *moduleIt->second;
  if (call->isConstructor) {
    auto cls = resolveClassByTypeName(project, module, call->callee);
    return findConstructorSignatures(cls, project, module);
  }
  auto dot = call->callee.find('.');
  if (dot != std::string::npos) {
    std::string base = call->callee.substr(0, dot);
    std::string member = call->callee.substr(dot + 1);
    for (const auto &import : module.imports) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt == project.moduleMap.end()) {
          continue;
        }
        if (effectiveImportAlias(import, *targetIt->second) != base) {
          continue;
        }
        auto signatures =
            findTopLevelSignatures(*targetIt->second, member, true);
        if (!signatures.empty()) {
          return signatures;
        }
      }
    }
    return {};
  }
  std::set<std::string> visited;
  return resolveSignaturesInModuleRecursive(project, module, call->callee,
                                            false, visited);
}
References callContextNearOffset(), effectiveImportAlias(), findConstructorSignatures(), findTopLevelSignatures(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, resolveClassByTypeName(), resolveSignaturesInModuleRecursive(), and uriToPath().
Referenced by main().
resolveSignaturesInModuleRecursive()
std::vector< LspSignature > zap::lsp::resolveSignaturesInModuleRecursive (const ProjectState & project, const sema::ModuleInfo & module, std::string_view name, bool publicOnly, std::set< std::string > & visited)
Definition at line 642 of file language_features.cpp.
{
  std::string moduleId = module.moduleId;
  if (visited.count(moduleId)) {
    return {};
  }
  visited.insert(moduleId);
  auto localSignatures = findTopLevelSignatures(module, name, publicOnly);
  if (!localSignatures.empty()) {
    return localSignatures;
  }
  for (const auto &import : module.imports) {
    bool isImplicitPreludeImport =
        import.rawPath == "std/prelude" && import.moduleAlias.empty();
    if (isImplicitPreludeImport) {
      for (const auto &targetId : import.targetModuleIds) {
        auto targetIt = project.moduleMap.find(targetId);
        if (targetIt != project.moduleMap.end()) {
          auto signatures = resolveSignaturesInModuleRecursive(
              project, *targetIt->second, name, true, visited);
          if (!signatures.empty()) {
            return signatures;
          }
        }
      }
    }
    for (const auto &binding : import.bindings) {
      if (binding.localName == name) {
        for (const auto &targetId : import.targetModuleIds) {
          auto targetIt = project.moduleMap.find(targetId);
          if (targetIt != project.moduleMap.end()) {
            auto signatures = resolveSignaturesInModuleRecursive(
                project, *targetIt->second, binding.sourceName, true, visited);
            if (!signatures.empty()) {
              return signatures;
            }
          }
        }
      }
    }
  }
  return {};
}
References findTopLevelSignatures(), sema::ModuleInfo::imports, zap::lsp::ProjectState::moduleMap, and resolveSignaturesInModuleRecursive().
Referenced by resolveSignatures(), and resolveSignaturesInModuleRecursive().
resolveVariableClassType()
std::optional< std::string > zap::lsp::resolveVariableClassType (const ProjectState & project, const sema::ModuleInfo & module, size_t offset, std::string_view name)
Definition at line 392 of file language_features.cpp.
{
  if (name == "self") {
    if (auto cls = enclosingClassAtOffset(*module.root, offset)) {
      return cls->name_;
    }
  }
  auto visible = findVisibleSymbolInfo(*module.root, offset, name);
  if (visible.node) {
    if (auto type = resolveClassTypeNameFromSemanticType(
            project, module, project.semanticInfo.typeFor(visible.node))) {
      return type;
    }
  }
  if (visible.typeNode) {
    return resolveClassTypeNameFromTypeNode(project, module, visible.typeNode);
  }
  return std::nullopt;
}
References enclosingClassAtOffset(), findVisibleSymbolInfo(), resolveClassTypeNameFromSemanticType(), resolveClassTypeNameFromTypeNode(), sema::ModuleInfo::root, zap::lsp::ProjectState::semanticInfo, and sema::SemanticInfo::typeFor().
Referenced by makeCompletionItems(), resolveDefinition(), and resolveHover().
resolveVariableRecordType()
std::shared_ptr< zir::RecordType > zap::lsp::resolveVariableRecordType (const ProjectState & project, const sema::ModuleInfo & module, size_t offset, std::string_view name)
Definition at line 414 of file language_features.cpp.
{
  auto visible = findVisibleSymbolInfo(*module.root, offset, name);
  if (visible.node) {
    auto type = project.semanticInfo.typeFor(visible.node);
    if (type && type->getKind() == zir::TypeKind::Record) {
      return std::static_pointer_cast<zir::RecordType>(type);
    }
  }
  return nullptr;
}
References findVisibleSymbolInfo(), zir::Record, sema::ModuleInfo::root, zap::lsp::ProjectState::semanticInfo, and sema::SemanticInfo::typeFor().
Referenced by makeCompletionItems().
signatureForNode()
std::optional< LspSignature > zap::lsp::signatureForNode (const Node * node)
Definition at line 74 of file language_features.cpp.
{
  auto renderGenericParams =
      [](const std::vector<std::unique_ptr<TypeNode>> &genericParams) {
        if (genericParams.empty()) {
          return std::string();
        }
        std::string out = "<";
        for (size_t i = 0; i < genericParams.size(); ++i) {
          if (i != 0) {
            out += ", ";
          }
          out += genericParams[i] ? genericParams[i]->qualifiedName() : "?";
        }
        out += ">";
        return out;
      };
  auto renderConstraints =
      [](const std::vector<GenericConstraint> &constraints) {
        if (constraints.empty()) {
          return std::string();
        }
        std::string out = " where ";
        for (size_t i = 0; i < constraints.size(); ++i) {
          if (i != 0) {
            out += ", ";
          }
          out += constraints[i].parameterName + ": ";
          out += constraints[i].boundType
                     ? renderType(constraints[i].boundType.get())
                     : std::string("?");
        }
        return out;
      };
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    std::vector<std::string> params;
    for (const auto &param : fun->params_) {
      params.push_back(renderParameter(param.get()));
    }
    std::string label =
        fun->name_ + renderGenericParams(fun->genericParams_) + "(";
    for (size_t i = 0; i < params.size(); ++i) {
      if (i != 0) {
        label += ", ";
      }
      label += params[i];
    }
    label += ") " + renderType(fun->returnType_.get());
    label += renderConstraints(fun->genericConstraints_);
    return LspSignature{std::move(label), std::move(params)};
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    std::vector<std::string> params;
    for (const auto &param : ext->params_) {
      params.push_back(renderParameter(param.get()));
    }
    if (ext->isCVariadic_) {
      params.push_back("...");
    }
    std::string label = ext->name_ + "(";
    for (size_t i = 0; i < params.size(); ++i) {
      if (i != 0) {
        label += ", ";
      }
      label += params[i];
    }
    label += ") " + renderType(ext->returnType_.get());
    return LspSignature{std::move(label), std::move(params)};
  }
  return std::nullopt;
}
References zap::out(), renderParameter(), and renderType().
Referenced by findConstructorSignatures(), findTopLevelSignatures(), hoverForClassMember(), hoverForNode(), and makeCompletionItems().
splitQualifiedName()
std::pair< std::string, std::string > zap::lsp::splitQualifiedName (std::string_view qualifiedName)
Definition at line 288 of file language_features.cpp.
{
  size_t dot = qualifiedName.rfind('.');
  if (dot == std::string_view::npos) {
    return {std::string(), std::string(qualifiedName)};
  }
  return {std::string(qualifiedName.substr(0, dot)),
          std::string(qualifiedName.substr(dot + 1))};
}
Referenced by resolveClassByTypeName(), resolveClassTypeNameFromSemanticType(), and resolveRecordLikeFieldsByTypeName().
stripGenericArguments()
std::string zap::lsp::stripGenericArguments (std::string_view typeName)
Definition at line 297 of file language_features.cpp.
{
  size_t genericStart = typeName.find('<');
  if (genericStart == std::string_view::npos) {
    return std::string(typeName);
  }
  return std::string(typeName.substr(0, genericStart));
}
Referenced by resolveClassByTypeName(), resolveClassTypeNameFromSemanticType(), and resolveRecordLikeFieldsByTypeName().
structLiteralCompletionAtCursor()
std::optional< StructLiteralCompletionContext > zap::lsp::structLiteralCompletionAtCursor (const std::string & source, size_t offset)
Definition at line 90 of file completion.cpp.
{
  auto brace = enclosingBraceBeforeOffset(source, offset);
  if (!brace) {
    return std::nullopt;
  }
  auto typeName = typeNameBeforeBrace(source, *brace);
  if (!typeName) {
    return std::nullopt;
  }
  size_t cursor = std::min(offset, source.size());
  size_t fieldStart = *brace + 1;
  int nestedParens = 0;
  int nestedBrackets = 0;
  int nestedBraces = 0;
  StructLiteralCompletionContext context{*typeName, "", {}};
  for (size_t i = *brace + 1; i < cursor; ++i) {
    char ch = source[i];
    if (ch == '(') {
      ++nestedParens;
      continue;
    }
    if (ch == ')' && nestedParens > 0) {
      --nestedParens;
      continue;
    }
    if (ch == '[') {
      ++nestedBrackets;
      continue;
    }
    if (ch == ']' && nestedBrackets > 0) {
      --nestedBrackets;
      continue;
    }
    if (ch == '{') {
      ++nestedBraces;
      continue;
    }
    if (ch == '}' && nestedBraces > 0) {
      --nestedBraces;
      continue;
    }
    bool atTopLevel =
        nestedParens == 0 && nestedBrackets == 0 && nestedBraces == 0;
    if (!atTopLevel) {
      continue;
    }
    if (ch == ',') {
      fieldStart = i + 1;
      continue;
    }
    if (std::isalpha(static_cast<unsigned char>(ch)) || ch == '_') {
      size_t nameStart = i;
      size_t nameEnd = i + 1;
      while (nameEnd < cursor && isIdentifierChar(source[nameEnd])) {
        ++nameEnd;
      }
      size_t afterName = nameEnd;
      while (afterName < cursor &&
             std::isspace(static_cast<unsigned char>(source[afterName]))) {
        ++afterName;
      }
      if (afterName < cursor && source[afterName] == ':') {
        context.initializedFields.insert(
            source.substr(nameStart, nameEnd - nameStart));
      }
      i = nameEnd - 1;
    }
  }
  nestedParens = 0;
  nestedBrackets = 0;
  nestedBraces = 0;
  for (size_t i = fieldStart; i < cursor; ++i) {
    char ch = source[i];
    if (ch == '(') {
      ++nestedParens;
    } else if (ch == ')' && nestedParens > 0) {
      --nestedParens;
    } else if (ch == '[') {
      ++nestedBrackets;
    } else if (ch == ']' && nestedBrackets > 0) {
      --nestedBrackets;
    } else if (ch == '{') {
      ++nestedBraces;
    } else if (ch == '}' && nestedBraces > 0) {
      --nestedBraces;
    } else if (ch == ':' && nestedParens == 0 && nestedBrackets == 0 &&
               nestedBraces == 0) {
      return std::nullopt;
    }
  }
  size_t end = cursor;
  while (end > fieldStart &&
         std::isspace(static_cast<unsigned char>(source[end - 1]))) {
    --end;
  }
  size_t start = end;
  while (start > fieldStart && isIdentifierChar(source[start - 1])) {
    --start;
  }
  if (start < end) {
    context.fieldPrefix = source.substr(start, end - start);
  }
  return context;
}
References enclosingBraceBeforeOffset(), zap::lsp::StructLiteralCompletionContext::fieldPrefix, zap::lsp::StructLiteralCompletionContext::initializedFields, isIdentifierChar(), and typeNameBeforeBrace().
Referenced by makeCompletionItems().
toLspSeverity()
int64_t zap::lsp::toLspSeverity (zap::DiagnosticLevel level)
Definition at line 120 of file protocol_messages.cpp.
{
  switch (level) {
  case zap::DiagnosticLevel::Error:
    return 1;
  case zap::DiagnosticLevel::Warning:
    return 2;
  case zap::DiagnosticLevel::Note:
    return 3;
  }
  return 1;
}
References zap::Error, zap::Note, and zap::Warning.
Referenced by makeDiagnostic().
topLevelNameForNode()
std::optional< std::string > zap::lsp::topLevelNameForNode (const Node * node)
Definition at line 173 of file language_features.cpp.
{
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    return fun->name_;
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    return ext->name_;
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return var->name_;
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return cnst->name_;
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    return record->name_;
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    return strukt->name_;
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    return cls->name_;
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return enm->name_;
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return alias->name_;
  }
  return std::nullopt;
}
Referenced by findTopLevelHover().
topLevelSymbolForNode()
std::optional< LspSymbol > zap::lsp::topLevelSymbolForNode (const Node * node, const std::string & uri)
Definition at line 999 of file language_features.cpp.
{
  if (auto fun = dynamic_cast<const FunDecl *>(node)) {
    return makeSymbol(uri, fun->name_, fun->span, 3, fun->visibility_);
  }
  if (auto ext = dynamic_cast<const ExtDecl *>(node)) {
    return makeSymbol(uri, ext->name_, ext->span, 3, ext->visibility_);
  }
  if (auto var = dynamic_cast<const VarDecl *>(node)) {
    return makeSymbol(uri, var->name_, var->span, 6, var->visibility_);
  }
  if (auto cnst = dynamic_cast<const ConstDecl *>(node)) {
    return makeSymbol(uri, cnst->name_, cnst->span, 21, cnst->visibility_);
  }
  if (auto record = dynamic_cast<const RecordDecl *>(node)) {
    return makeSymbol(uri, record->name_, record->span, 22,
                      record->visibility_);
  }
  if (auto strukt = dynamic_cast<const StructDeclarationNode *>(node)) {
    return makeSymbol(uri, strukt->name_, strukt->span, 22,
                      strukt->visibility_);
  }
  if (auto cls = dynamic_cast<const ClassDecl *>(node)) {
    return makeSymbol(uri, cls->name_, cls->span, 5, cls->visibility_);
  }
  if (auto enm = dynamic_cast<const EnumDecl *>(node)) {
    return makeSymbol(uri, enm->name_, enm->span, 13, enm->visibility_);
  }
  if (auto alias = dynamic_cast<const TypeAliasDecl *>(node)) {
    return makeSymbol(uri, alias->name_, alias->span, 22, alias->visibility_);
  }
  return std::nullopt;
}
References makeSymbol().
Referenced by collectTopLevelSymbols().
typeNameBeforeBrace()
std::optional< std::string > zap::lsp::typeNameBeforeBrace (const std::string & source, size_t brace)
Definition at line 48 of file completion.cpp.
{
  size_t end = brace;
  while (end > 0 && std::isspace(static_cast<unsigned char>(source[end - 1]))) {
    --end;
  }
  size_t start = end;
  int angleDepth = 0;
  while (start > 0) {
    char ch = source[start - 1];
    if (ch == '>') {
      ++angleDepth;
      --start;
      continue;
    }
    if (ch == '<') {
      if (angleDepth == 0) {
        break;
      }
      --angleDepth;
      --start;
      continue;
    }
    if (angleDepth > 0) {
      --start;
      continue;
    }
    if (isIdentifierChar(ch) || ch == '.') {
      --start;
      continue;
    }
    break;
  }
  if (start == end) {
    return std::nullopt;
  }
  return source.substr(start, end - start);
}
References isIdentifierChar().
Referenced by structLiteralCompletionAtCursor().
uriToPath()
std::optional< std::filesystem::path > zap::lsp::uriToPath (std::string_view uri)
Definition at line 50 of file protocol_utils.cpp.
{
  constexpr std::string_view prefix = "file://";
  if (uri.rfind(prefix, 0) != 0) {
    return std::nullopt;
  }
  std::string decoded;
  decoded.reserve(uri.size() - prefix.size());
  for (size_t i = prefix.size(); i < uri.size(); ++i) {
    char ch = uri[i];
    if (ch == '%' && i + 2 < uri.size()) {
      auto hex = [](char value) -> int {
        if (value >= '0' && value <= '9') {
          return value - '0';
        }
        if (value >= 'a' && value <= 'f') {
          return 10 + value - 'a';
        }
        if (value >= 'A' && value <= 'F') {
          return 10 + value - 'A';
        }
        return -1;
      };
      int hi = hex(uri[i + 1]);
      int lo = hex(uri[i + 2]);
      if (hi >= 0 && lo >= 0) {
        decoded.push_back(static_cast<char>((hi << 4) | lo));
        i += 2;
        continue;
      }
    }
    decoded.push_back(ch);
  }
#ifdef _WIN32
  if (decoded.size() >= 3 && decoded[0] == '/' &&
      std::isalpha(static_cast<unsigned char>(decoded[1])) &&
      decoded[2] == ':') {
    decoded.erase(decoded.begin());
  }
#endif
  return std::filesystem::path(decoded).lexically_normal();
}
References prefix.
Referenced by collectCompletionSymbols(), main(), makeCompletionItems(), resolveDefinition(), resolveHover(), and resolveSignatures().
Variable Documentation
kMaxLspMessageBytes
size_t zap::lsp::kMaxLspMessageBytes = 8 * 1024 * 1024 constexpr
Definition at line 426 of file lsp.cpp.
Referenced by zap::lsp::Server::processMessage().
prefix
std::string_view zap::lsp::prefix = "Content-Length: " constexpr
Definition at line 425 of file lsp.cpp.
Referenced by matchesPrefix(), zap::lsp::Server::processMessage(), renderParameter(), zap::lsp::Server::sendMessageRaw(), and uriToPath().