ZAP: zap::lsp::anonymous_namespace{lsp.cpp} Namespace Reference
zap::lsp::anonymous_namespace{lsp.cpp} Namespace Reference
Functions
JsonObject parseJson (const char *&it, const char *end)
void jsonSkipWhitespace (const char *&it, const char *end)
bool appendUtf8 (std::string &out, unsigned codepoint)
bool parseHex4 (const char *&it, const char *end, unsigned &codepoint)
JsonObject parseJsonString (const char *&it, const char *end)
JsonObject parseJsonNumber (const char *&it, const char *end)
JsonObject parseKeyword (const char *&it, const char *end)
JsonObject parseJsonList (const char *&it, const char *end)
JsonObject parseJsonObject (const char *&it, const char *end)
void appendEscapedJsonString (std::string &out, std::string_view value)
void stringifyJson (std::string &out, const JsonObject &json)
Function Documentation
appendEscapedJsonString()
void zap::lsp::anonymous_namespace{lsp.cpp}::appendEscapedJsonString (std::string & out, std::string_view value)
Definition at line 256 of file lsp.cpp.
{
  out.push_back('"');
  for (unsigned char ch : value) {
    switch (ch) {
    case '\\':
      out += "\\\\";
      break;
    case '"':
      out += "\\\"";
      break;
    case '\b':
      out += "\\b";
      break;
    case '\f':
      out += "\\f";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\r':
      out += "\\r";
      break;
    case '\t':
      out += "\\t";
      break;
    default:
      if (ch < 0x20) {
        static constexpr char hex[] = "0123456789abcdef";
        out += "\\u00";
        out.push_back(hex[(ch >> 4) & 0x0F]);
        out.push_back(hex[ch & 0x0F]);
      } else {
        out.push_back(static_cast<char>(ch));
      }
      break;
    }
  }
  out.push_back('"');
}
References appendEscapedJsonString(), and zap::out().
Referenced by appendEscapedJsonString(), and stringifyJson().
appendUtf8()
bool zap::lsp::anonymous_namespace{lsp.cpp}::appendUtf8 (std::string & out, unsigned codepoint)
Definition at line 20 of file lsp.cpp.
{
  if (codepoint <= 0x7F) {
    out.push_back(static_cast<char>(codepoint));
    return true;
  }
  if (codepoint <= 0x7FF) {
    out.push_back(static_cast<char>(0xC0 | (codepoint >> 6)));
    out.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    return true;
  }
  if (codepoint <= 0xFFFF) {
    out.push_back(static_cast<char>(0xE0 | (codepoint >> 12)));
    out.push_back(static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    return true;
  }
  if (codepoint <= 0x10FFFF) {
    out.push_back(static_cast<char>(0xF0 | (codepoint >> 18)));
    out.push_back(static_cast<char>(0x80 | ((codepoint >> 12) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (codepoint & 0x3F)));
    return true;
  }
  return false;
}
References appendUtf8(), and zap::out().
Referenced by appendUtf8(), and parseJsonString().
jsonSkipWhitespace()
void zap::lsp::anonymous_namespace{lsp.cpp}::jsonSkipWhitespace (const char *& it, const char * end)
Definition at line 14 of file lsp.cpp.
{
  while (it != end && std::isspace(static_cast<unsigned char>(*it))) {
    ++it;
  }
}
References jsonSkipWhitespace().
Referenced by jsonSkipWhitespace(), parseJson(), parseJsonList(), and parseJsonObject().
parseHex4()
bool zap::lsp::anonymous_namespace{lsp.cpp}::parseHex4 (const char *& it, const char * end, unsigned & codepoint)
Definition at line 46 of file lsp.cpp.
{
  codepoint = 0;
  for (int i = 0; i < 4; ++i) {
    if (it == end) {
      return false;
    }
    codepoint <<= 4;
    char ch = *it++;
    if (ch >= '0' && ch <= '9') {
      codepoint |= static_cast<unsigned>(ch - '0');
    } else if (ch >= 'a' && ch <= 'f') {
      codepoint |= static_cast<unsigned>(10 + ch - 'a');
    } else if (ch >= 'A' && ch <= 'F') {
      codepoint |= static_cast<unsigned>(10 + ch - 'A');
    } else {
      return false;
    }
  }
  return true;
}
References parseHex4().
Referenced by parseHex4(), and parseJsonString().
parseJson()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseJson (const char *& it, const char * end)
Definition at line 231 of file lsp.cpp.
{
  jsonSkipWhitespace(it, end);
  if (it == end) {
    return JsonObject(nullptr);
  }
  switch (*it) {
  case '{':
    return parseJsonObject(++it, end);
  case '[':
    return parseJsonList(++it, end);
  case '"':
    return parseJsonString(++it, end);
  case 't':
  case 'f':
  case 'n':
    return parseKeyword(it, end);
  default:
    if (*it == '-' || std::isdigit(static_cast<unsigned char>(*it))) {
      return parseJsonNumber(it, end);
    }
    return JsonObject(nullptr);
  }
}
References jsonSkipWhitespace(), parseJson(), parseJsonList(), parseJsonNumber(), parseJsonObject(), parseJsonString(), and parseKeyword().
Referenced by parseJson(), parseJsonList(), and parseJsonObject().
parseJsonList()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonList (const char *& it, const char * end)
Definition at line 159 of file lsp.cpp.
{
  JsonObject::List list;
  jsonSkipWhitespace(it, end);
  if (it != end && *it == ']') {
    ++it;
    return JsonObject(std::move(list));
  }
  while (it != end) {
    list.push_back(parseJson(it, end));
    if (list.back().isNull() && (it == end || *(it - 1) != 'l')) {
      return JsonObject(nullptr);
    }
    jsonSkipWhitespace(it, end);
    if (it == end) {
      return JsonObject(nullptr);
    }
    if (*it == ']') {
      ++it;
      return JsonObject(std::move(list));
    }
    if (*it != ',') {
      return JsonObject(nullptr);
    }
    ++it;
    jsonSkipWhitespace(it, end);
  }
  return JsonObject(nullptr);
}
References jsonSkipWhitespace(), parseJson(), and parseJsonList().
Referenced by parseJson(), and parseJsonList().
parseJsonNumber()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonNumber (const char *& it, const char * end)
Definition at line 118 of file lsp.cpp.
{
  const char *start = it;
  if (it != end && *it == '-') {
    ++it;
  }
  if (it == end || !std::isdigit(static_cast<unsigned char>(*it))) {
    return JsonObject(nullptr);
  }
  while (it != end && std::isdigit(static_cast<unsigned char>(*it))) {
    ++it;
  }
  if (it != end && (*it == '.' || *it == 'e' || *it == 'E')) {
    return JsonObject(nullptr);
  }
  JsonObject::Integer integer = 0;
  auto result = std::from_chars(start, it, integer);
  if (result.ec != std::errc()) {
    return JsonObject(nullptr);
  }
  return JsonObject(integer);
}
References parseJsonNumber().
Referenced by parseJson(), and parseJsonNumber().
parseJsonObject()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonObject (const char *& it, const char * end)
Definition at line 190 of file lsp.cpp.
{
  JsonObject::Object object;
  jsonSkipWhitespace(it, end);
  if (it != end && *it == '}') {
    ++it;
    return JsonObject(std::move(object));
  }
  while (it != end) {
    if (*it != '"') {
      return JsonObject(nullptr);
    }
    JsonObject key = parseJsonString(++it, end);
    if (!key.isString()) {
      return JsonObject(nullptr);
    }
    jsonSkipWhitespace(it, end);
    if (it == end || *it != ':') {
      return JsonObject(nullptr);
    }
    ++it;
    JsonObject value = parseJson(it, end);
    object.emplace(key.getAsString(), std::move(value));
    jsonSkipWhitespace(it, end);
    if (it == end) {
      return JsonObject(nullptr);
    }
    if (*it == '}') {
      ++it;
      return JsonObject(std::move(object));
    }
    if (*it != ',') {
      return JsonObject(nullptr);
    }
    ++it;
    jsonSkipWhitespace(it, end);
  }
  return JsonObject(nullptr);
}
References zap::lsp::JsonObject::getAsString(), zap::lsp::JsonObject::isString(), jsonSkipWhitespace(), parseJson(), parseJsonObject(), and parseJsonString().
Referenced by parseJson(), and parseJsonObject().
parseJsonString()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonString (const char *& it, const char * end)
Definition at line 67 of file lsp.cpp.
{
  std::string result;
  while (it != end) {
    char ch = *it++;
    if (ch == '"') {
      return JsonObject(std::move(result));
    }
    if (ch != '\\') {
      result.push_back(ch);
      continue;
    }
    if (it == end) {
      return JsonObject(nullptr);
    }
    char escaped = *it++;
    switch (escaped) {
    case '"':
    case '\\':
    case '/':
      result.push_back(escaped);
      break;
    case 'b':
      result.push_back('\b');
      break;
    case 'f':
      result.push_back('\f');
      break;
    case 'n':
      result.push_back('\n');
      break;
    case 'r':
      result.push_back('\r');
      break;
    case 't':
      result.push_back('\t');
      break;
    case 'u': {
      unsigned codepoint = 0;
      if (!parseHex4(it, end, codepoint) || !appendUtf8(result, codepoint)) {
        return JsonObject(nullptr);
      }
      break;
    }
    default:
      return JsonObject(nullptr);
    }
  }
  return JsonObject(nullptr);
}
References appendUtf8(), parseHex4(), and parseJsonString().
Referenced by parseJson(), parseJsonObject(), and parseJsonString().
parseKeyword()
JsonObject zap::lsp::anonymous_namespace{lsp.cpp}::parseKeyword (const char *& it, const char * end)
Definition at line 141 of file lsp.cpp.
{
  const char *start = it;
  while (it != end && std::isalpha(static_cast<unsigned char>(*it))) {
    ++it;
  }
  std::string_view keyword(start, static_cast<size_t>(it - start));
  if (keyword == "true") {
    return JsonObject(true);
  }
  if (keyword == "false") {
    return JsonObject(false);
  }
  if (keyword == "null") {
    return JsonObject(nullptr);
  }
  return JsonObject(nullptr);
}
References parseKeyword().
Referenced by parseJson(), and parseKeyword().
stringifyJson()
void zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson (std::string & out, const JsonObject & json)
Definition at line 296 of file lsp.cpp.
{
  switch (json.getType()) {
  case JsonObject::ObjectType::OBJECT_T: {
    out.push_back('{');
    bool first = true;
    for (const auto &entry : json.getAsObject()) {
      if (!first) {
        out.push_back(',');
      }
      first = false;
      appendEscapedJsonString(out, entry.first);
      out.push_back(':');
      stringifyJson(out, entry.second);
    }
    out.push_back('}');
    break;
  }
  case JsonObject::ObjectType::LIST_T: {
    out.push_back('[');
    bool first = true;
    for (const auto &entry : json.getAsList()) {
      if (!first) {
        out.push_back(',');
      }
      first = false;
      stringifyJson(out, entry);
    }
    out.push_back(']');
    break;
  }
  case JsonObject::ObjectType::INTEGER_T:
    out += std::to_string(json.getAsInteger());
    break;
  case JsonObject::ObjectType::STRING_T:
    appendEscapedJsonString(out, json.getAsString());
    break;
  case JsonObject::ObjectType::BOOLEAN_T:
    out += json.getAsBoolean() ? "true" : "false";
    break;
  case JsonObject::ObjectType::NULL_T:
    out += "null";
    break;
  }
}
References appendEscapedJsonString(), zap::lsp::JsonObject::BOOLEAN_T, zap::lsp::JsonObject::getAsBoolean(), zap::lsp::JsonObject::getAsInteger(), zap::lsp::JsonObject::getAsList(), zap::lsp::JsonObject::getAsObject(), zap::lsp::JsonObject::getAsString(), zap::lsp::JsonObject::getType(), zap::lsp::JsonObject::INTEGER_T, zap::lsp::JsonObject::LIST_T, zap::lsp::JsonObject::NULL_T, zap::lsp::JsonObject::OBJECT_T, zap::out(), zap::lsp::JsonObject::STRING_T, and stringifyJson().
Referenced by stringifyJson().