ZAP: sema::anonymous_namespace{binder.cpp} Namespace Reference
sema::anonymous_namespace{binder.cpp} Namespace Reference
Functions
std::string sanitizeTypeName (const std::string &value)
bool isStringType (const std::shared_ptr< zir::Type > &type)
bool isFailableType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::Type > failableValueType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::Type > failableErrorType (const std::shared_ptr< zir::Type > &type)
std::shared_ptr< zir::RecordType > makeFailableType (const std::shared_ptr< zir::Type > &valueType, const std::shared_ptr< zir::Type > &errorType)
std::string renderGenericTypeName (const std::string &baseName, const std::vector< std::shared_ptr< zir::Type > > &arguments)
std::string renderGenericCodegenName (const std::string &baseName, const std::vector< std::shared_ptr< zir::Type > > &arguments)
std::shared_ptr< zir::RecordType > makeVariadicViewType (const std::shared_ptr< zir::Type > &elementType)
bool isVariadicViewType (const std::shared_ptr< zir::Type > &type)
std::unique_ptr< BoundExpression > makeDefaultValueExpr (const std::shared_ptr< zir::Type > &type)
std::unique_ptr< BoundExpression > makeFailableValueExpr (std::unique_ptr< BoundExpression > valueExpr, const std::shared_ptr< zir::Type > &failableType)
std::unique_ptr< BoundExpression > makeFailableErrorExpr (std::unique_ptr< BoundExpression > errorExpr, const std::shared_ptr< zir::Type > &failableType)
std::vector< std::string > splitQualified (const std::string &value)
bool extractQualifiedPath (const ExpressionNode *expr, std::vector< std::string > &parts)
std::vector< std::shared_ptr< FunctionSymbol > > collectOverloads (const std::shared_ptr< Symbol > &symbol)
bool sameFunctionSignature (const FunctionSymbol &lhs, const FunctionSymbol &rhs)
Variables
constexpr const char * kFailablePrefix = "__zap_failable_"
Function Documentation
collectOverloads()
std::vector< std::shared_ptr< FunctionSymbol > > sema::anonymous_namespace{binder.cpp}::collectOverloads (const std::shared_ptr< Symbol > & symbol)
Definition at line 234 of file binder.cpp.
{
  if (!symbol) {
    return {};
  }
  if (auto function = std::dynamic_pointer_cast<FunctionSymbol>(symbol)) {
    return {function};
  }
  if (auto set = std::dynamic_pointer_cast<OverloadSetSymbol>(symbol)) {
    return set->overloads;
  }
  return {};
}
References collectOverloads().
Referenced by collectOverloads().
extractQualifiedPath()
bool sema::anonymous_namespace{binder.cpp}::extractQualifiedPath (const ExpressionNode * expr, std::vector< std::string > & parts)
Definition at line 215 of file binder.cpp.
{
  if (auto id = dynamic_cast<const ConstId *>(expr)) {
    parts.push_back(id->value_);
    return true;
  }
  if (auto member = dynamic_cast<const MemberAccessNode *>(expr)) {
    if (!extractQualifiedPath(member->left_.get(), parts)) {
      return false;
    }
    parts.push_back(member->member_);
    return true;
  }
  return false;
}
References extractQualifiedPath().
Referenced by extractQualifiedPath().
failableErrorType()
std::shared_ptr< zir::Type > sema::anonymous_namespace{binder.cpp}::failableErrorType (const std::shared_ptr< zir::Type > & type)
Definition at line 52 of file binder.cpp.
{
  if (!isFailableType(type)) {
    return nullptr;
  }
  auto record = std::static_pointer_cast<zir::RecordType>(type);
  return record->getFields()[2].type;
}
References failableErrorType(), and isFailableType().
Referenced by failableErrorType(), makeDefaultValueExpr(), and makeFailableValueExpr().
failableValueType()
std::shared_ptr< zir::Type > sema::anonymous_namespace{binder.cpp}::failableValueType (const std::shared_ptr< zir::Type > & type)
Definition at line 43 of file binder.cpp.
{
  if (!isFailableType(type)) {
    return nullptr;
  }
  auto record = std::static_pointer_cast<zir::RecordType>(type);
  return record->getFields()[1].type;
}
References failableValueType(), and isFailableType().
Referenced by failableValueType(), makeDefaultValueExpr(), makeFailableErrorExpr(), and makeFailableValueExpr().
isFailableType()
bool sema::anonymous_namespace{binder.cpp}::isFailableType (const std::shared_ptr< zir::Type > & type)
Definition at line 26 of file binder.cpp.
{
  if (!type || type->getKind() != zir::TypeKind::Record) {
    return false;
  }
  auto record = std::static_pointer_cast<zir::RecordType>(type);
  const auto &name = record->getName();
  if (name.rfind(kFailablePrefix, 0) != 0) {
    return false;
  }
  const auto &fields = record->getFields();
  return fields.size() == 3 && fields[0].name == "ok" &&
         fields[1].name == "value" && fields[2].name == "error";
}
References isFailableType(), kFailablePrefix, and zir::Record.
Referenced by failableErrorType(), failableValueType(), isFailableType(), and makeDefaultValueExpr().
isStringType()
bool sema::anonymous_namespace{binder.cpp}::isStringType (const std::shared_ptr< zir::Type > & type)
Definition at line 19 of file binder.cpp.
{
  return type &&
         (type->getKind() == zir::TypeKind::Record ||
          type->getKind() == zir::TypeKind::Class) &&
         static_cast<zir::RecordType *>(type.get())->getName() == "String";
}
References zir::Class, zir::RecordType::getName(), isStringType(), and zir::Record.
Referenced by isStringType().
isVariadicViewType()
bool sema::anonymous_namespace{binder.cpp}::isVariadicViewType (const std::shared_ptr< zir::Type > & type)
Definition at line 127 of file binder.cpp.
{
  return type && type->getKind() == zir::TypeKind::Record &&
         static_cast<zir::RecordType *>(type.get())
                 ->getName()
                 .rfind("__zap_varargs_", 0) == 0;
}
References zir::RecordType::getName(), isVariadicViewType(), and zir::Record.
Referenced by isVariadicViewType().
makeDefaultValueExpr()
std::unique_ptr< BoundExpression > sema::anonymous_namespace{binder.cpp}::makeDefaultValueExpr (const std::shared_ptr< zir::Type > & type)
Definition at line 135 of file binder.cpp.
{
  if (!type) {
    return std::make_unique<BoundLiteral>(
        "0", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Void));
  }
  switch (type->getKind()) {
  case zir::TypeKind::Bool:
    return std::make_unique<BoundLiteral>(
        "false", std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool));
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
  case zir::TypeKind::Float64:
    return std::make_unique<BoundLiteral>("0.0", type);
  case zir::TypeKind::Pointer:
  case zir::TypeKind::NullPtr:
  case zir::TypeKind::Class:
    return std::make_unique<BoundLiteral>(
        "0", std::make_shared<zir::PrimitiveType>(zir::TypeKind::NullPtr));
  case zir::TypeKind::Record:
    if (isFailableType(type)) {
      auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
      auto valueType = failableValueType(type);
      auto errorType = failableErrorType(type);
      std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>>
          fields;
      fields.push_back(
          {"ok", std::make_unique<BoundLiteral>("false", okType)});
      fields.push_back({"value", makeDefaultValueExpr(valueType)});
      fields.push_back({"error", makeDefaultValueExpr(errorType)});
      return std::make_unique<BoundStructLiteral>(std::move(fields), type);
    }
    return std::make_unique<BoundLiteral>("0", type);
  default:
    if (type->isInteger() || type->getKind() == zir::TypeKind::Enum) {
      return std::make_unique<BoundLiteral>("0", type);
    }
    return std::make_unique<BoundLiteral>("0", type);
  }
}
References zir::Bool, zir::Class, zir::Enum, failableErrorType(), failableValueType(), zir::Float, zir::Float32, zir::Float64, isFailableType(), makeDefaultValueExpr(), zir::NullPtr, zir::Pointer, zir::Record, and zir::Void.
Referenced by makeDefaultValueExpr(), makeFailableErrorExpr(), and makeFailableValueExpr().
makeFailableErrorExpr()
std::unique_ptr< BoundExpression > sema::anonymous_namespace{binder.cpp}::makeFailableErrorExpr (std::unique_ptr< BoundExpression > errorExpr, const std::shared_ptr< zir::Type > & failableType)
Definition at line 191 of file binder.cpp.
{
  auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  auto valueType = failableValueType(failableType);
  std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>> fields;
  fields.push_back({"ok", std::make_unique<BoundLiteral>("false", okType)});
  fields.push_back({"value", makeDefaultValueExpr(valueType)});
  fields.push_back({"error", std::move(errorExpr)});
  return std::make_unique<BoundStructLiteral>(std::move(fields), failableType);
}
References zir::Bool, failableValueType(), makeDefaultValueExpr(), and makeFailableErrorExpr().
Referenced by makeFailableErrorExpr().
makeFailableType()
std::shared_ptr< zir::RecordType > sema::anonymous_namespace{binder.cpp}::makeFailableType (const std::shared_ptr< zir::Type > & valueType, const std::shared_ptr< zir::Type > & errorType)
Definition at line 61 of file binder.cpp.
{
  auto suffix = sanitizeTypeName((valueType ? valueType->toString() : "<?>") +
                                 std::string("$") +
                                 (errorType ? errorType->toString() : "<?>"));
  auto typeName = std::string(kFailablePrefix) + suffix;
  auto type = std::make_shared<zir::RecordType>(typeName, typeName);
  type->addField("ok",
                 std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool));
  type->addField("value", valueType);
  type->addField("error", errorType);
  return type;
}
References zir::Bool, kFailablePrefix, makeFailableType(), and sanitizeTypeName().
Referenced by makeFailableType().
makeFailableValueExpr()
std::unique_ptr< BoundExpression > sema::anonymous_namespace{binder.cpp}::makeFailableValueExpr (std::unique_ptr< BoundExpression > valueExpr, const std::shared_ptr< zir::Type > & failableType)
Definition at line 177 of file binder.cpp.
{
  auto okType = std::make_shared<zir::PrimitiveType>(zir::TypeKind::Bool);
  auto valueType = failableValueType(failableType);
  auto errorType = failableErrorType(failableType);
  std::vector<std::pair<std::string, std::unique_ptr<BoundExpression>>> fields;
  fields.push_back({"ok", std::make_unique<BoundLiteral>("true", okType)});
  fields.push_back({"value", std::move(valueExpr)});
  fields.push_back({"error", makeDefaultValueExpr(errorType)});
  return std::make_unique<BoundStructLiteral>(std::move(fields), failableType);
}
References zir::Bool, failableErrorType(), failableValueType(), makeDefaultValueExpr(), and makeFailableValueExpr().
Referenced by makeFailableValueExpr().
makeVariadicViewType()
std::shared_ptr< zir::RecordType > sema::anonymous_namespace{binder.cpp}::makeVariadicViewType (const std::shared_ptr< zir::Type > & elementType)
Definition at line 117 of file binder.cpp.
{
  auto suffix = sanitizeTypeName(elementType->toString());
  auto type = std::make_shared<zir::RecordType>("__zap_varargs_" + suffix,
                                                "__zap_varargs_" + suffix);
  type->addField("data", std::make_shared<zir::PointerType>(elementType));
  type->addField("len",
                 std::make_shared<zir::PrimitiveType>(zir::TypeKind::Int));
  return type;
}
References zir::Int, makeVariadicViewType(), and sanitizeTypeName().
Referenced by makeVariadicViewType().
renderGenericCodegenName()
std::string sema::anonymous_namespace{binder.cpp}::renderGenericCodegenName (const std::string & baseName, const std::vector< std::shared_ptr< zir::Type > > & arguments)
Definition at line 102 of file binder.cpp.
{
  std::string suffix;
  for (size_t i = 0; i < arguments.size(); ++i) {
    if (i != 0) {
      suffix += "$";
    }
    suffix += sanitizeTypeName(arguments[i] ? arguments[i]->toString()
                                            : std::string("<?>"));
  }
  return baseName + "$g$" + suffix;
}
References renderGenericCodegenName(), and sanitizeTypeName().
Referenced by renderGenericCodegenName().
renderGenericTypeName()
std::string sema::anonymous_namespace{binder.cpp}::renderGenericTypeName (const std::string & baseName, const std::vector< std::shared_ptr< zir::Type > > & arguments)
Definition at line 88 of file binder.cpp.
{
  std::string name = baseName + "<";
  for (size_t i = 0; i < arguments.size(); ++i) {
    if (i != 0) {
      name += ", ";
    }
    name += arguments[i] ? arguments[i]->toString() : "<?>";
  }
  name += ">";
  return name;
}
References renderGenericTypeName().
Referenced by renderGenericTypeName().
sameFunctionSignature()
bool sema::anonymous_namespace{binder.cpp}::sameFunctionSignature (const FunctionSymbol & lhs, const FunctionSymbol & rhs)
Definition at line 247 of file binder.cpp.
{
  if (lhs.parameters.size() != rhs.parameters.size() ||
      lhs.isCVariadic != rhs.isCVariadic) {
    return false;
  }
  for (size_t i = 0; i < lhs.parameters.size(); ++i) {
    const auto &left = lhs.parameters[i];
    const auto &right = rhs.parameters[i];
    if (left->is_ref != right->is_ref ||
        left->is_variadic_pack != right->is_variadic_pack) {
      return false;
    }
    if (!left->type || !right->type ||
        left->type->toString() != right->type->toString()) {
      return false;
    }
  }
  return true;
}
References sema::FunctionSymbol::isCVariadic, sema::FunctionSymbol::parameters, and sameFunctionSignature().
Referenced by sameFunctionSignature().
sanitizeTypeName()
std::string sema::anonymous_namespace{binder.cpp}::sanitizeTypeName (const std::string & value)
Definition at line 75 of file binder.cpp.
{
  std::string out;
  out.reserve(value.size());
  for (char ch : value) {
    if (std::isalnum(static_cast<unsigned char>(ch))) {
      out.push_back(ch);
    } else {
      out.push_back('_');
    }
  }
  return out;
}
References sanitizeTypeName().
Referenced by makeFailableType(), makeVariadicViewType(), renderGenericCodegenName(), and sanitizeTypeName().
splitQualified()
std::vector< std::string > sema::anonymous_namespace{binder.cpp}::splitQualified (const std::string & value)
Definition at line 203 of file binder.cpp.
{
  std::vector<std::string> parts;
  std::stringstream ss(value);
  std::string item;
  while (std::getline(ss, item, '.')) {
    if (!item.empty()) {
      parts.push_back(item);
    }
  }
  return parts;
}
References splitQualified().
Referenced by splitQualified().
Variable Documentation
kFailablePrefix
const char* sema::anonymous_namespace{binder.cpp}::kFailablePrefix = "__zap_failable_" constexpr
Definition at line 17 of file binder.cpp.
Referenced by isFailableType(), and makeFailableType().