ZAP: zir::RecordType Class Reference
zir::RecordType Class Reference
#include <type.hpp>
Classes
struct Field
Public Member Functions
RecordType (std::string n, std::string codegen="")
TypeKind getKind () const override
std::string toString () const override
bool isReferenceType () const override
void addField (std::string n, std::shared_ptr< Type > t)
const std::vector< Field > & getFields () const
const std::string & getName () const
const std::string & getCodegenName () const
Public Member Functions inherited from zir::Type
virtual ~Type ()=default
virtual bool isPointerLike () const
virtual bool isInteger () const
virtual bool isUnsigned () const
virtual bool isFloatingPoint () const
Private Attributes
std::string name
std::string codegenName
std::vector< Field > fields
Detailed Description
Definition at line 121 of file type.hpp.
Constructor & Destructor Documentation
RecordType()
zir::RecordType::RecordType (std::string n, std::string codegen = "") inline
Definition at line 132 of file type.hpp.
      : name(std::move(n)),
        codegenName(codegen.empty() ? name : std::move(codegen)) {}
References codegenName, and name.
Member Function Documentation
addField()
void zir::RecordType::addField (std::string n, std::shared_ptr< Type > t) inline
Definition at line 139 of file type.hpp.
{
    fields.push_back({std::move(n), std::move(t)});
  }
References fields.
getCodegenName()
const std::string & zir::RecordType::getCodegenName () const inline
Definition at line 145 of file type.hpp.
{ return codegenName; }
References codegenName.
getFields()
const std::vector< Field > & zir::RecordType::getFields () const inline
Definition at line 143 of file type.hpp.
{ return fields; }
References fields.
getKind()
TypeKind zir::RecordType::getKind () const inline override virtual
Implements zir::Type.
Definition at line 135 of file type.hpp.
{ return TypeKind::Record; }
References zir::Record.
getName()
const std::string & zir::RecordType::getName () const inline
Definition at line 144 of file type.hpp.
{ return name; }
References name.
Referenced by codegen::anonymous_namespace{llvm_codegen.cpp}::isStringType(), sema::anonymous_namespace{binder.cpp}::isStringType(), codegen::anonymous_namespace{llvm_codegen.cpp}::isVariadicViewType(), and sema::anonymous_namespace{binder.cpp}::isVariadicViewType().
isReferenceType()
bool zir::RecordType::isReferenceType () const inline override virtual
Reimplemented from zir::Type.
Definition at line 137 of file type.hpp.
{ return true; }
toString()
std::string zir::RecordType::toString () const inline override virtual
Implements zir::Type.
Definition at line 136 of file type.hpp.
{ return "%" + name; }
References name.
Member Data Documentation
codegenName
std::string zir::RecordType::codegenName private
Definition at line 128 of file type.hpp.
Referenced by getCodegenName(), and RecordType().
fields
std::vector<Field> zir::RecordType::fields private
Definition at line 129 of file type.hpp.
Referenced by addField(), and getFields().
name
std::string zir::RecordType::name private
Definition at line 127 of file type.hpp.
Referenced by getName(), RecordType(), and toString().
The documentation for this class was generated from the following file:
src/ir/type.hpp