ZAP: zap::lsp::JsonParser Class Reference
zap::lsp::JsonParser Class Reference
#include <lsp.hpp>
Static Public Member Functions
static JsonObject parse (std::string_view)
Parses the provided json.
static void toString (std::string &dest, JsonObject &j)
Detailed Description
Definition at line 111 of file lsp.hpp.
Member Function Documentation
parse()
JsonObject zap::lsp::JsonParser::parse (std::string_view sv) static
Parses the provided json.
Returns
Json object.
Definition at line 261 of file lsp.cpp.
{
  const char* it = sv.begin();
  return parseJson(it, sv.end());
}
References zap::lsp::parseJson().
toString()
void zap::lsp::JsonParser::toString (std::string & dest, JsonObject & j) static
Definition at line 227 of file lsp.cpp.
{
  switch(j.getType()){
    case JsonObject::ObjectType::OBJECT_T:
      strJsonObject(dest, j.getAsObject());
      break;
    case JsonObject::ObjectType::LIST_T:
      strJsonList(dest, j.getAsList());
      break;
    case JsonObject::ObjectType::INTEGER_T:
      strJsonInteger(dest, j.getAsInteger());
      break;
    case JsonObject::ObjectType::STRING_T:
      strJsonStr(dest, j.getAsString());
      break;
    case JsonObject::ObjectType::BOOLEAN_T:
      strJsonBool(dest, j.getAsBoolean());
      break;
    case JsonObject::ObjectType::NULL_T:
      strJsonNull(dest);
      break;
    default:
      return;
  }
}
References zap::lsp::JsonObject::BOOLEAN_T, zap::lsp::JsonObject::getAsBoolean(), zap::lsp::JsonObject::getAsInteger(), zap::lsp::JsonObject::getAsList(), zap::lsp::JsonObject::getAsObject(), zap::lsp::JsonObject::getAsString(), zap::lsp::JsonObject::getType(), zap::lsp::JsonObject::INTEGER_T, zap::lsp::JsonObject::LIST_T, zap::lsp::JsonObject::NULL_T, zap::lsp::JsonObject::OBJECT_T, zap::lsp::JsonObject::STRING_T, zap::lsp::strJsonBool(), zap::lsp::strJsonInteger(), zap::lsp::strJsonList(), zap::lsp::strJsonNull(), zap::lsp::strJsonObject(), and zap::lsp::strJsonStr().
Referenced by zap::lsp::JsonRPC::getStr(), zap::lsp::Server::sendMessage(), zap::lsp::strJsonList(), and zap::lsp::strJsonObject().
The documentation for this class was generated from the following files:
src/lsp/lsp.hpp
src/lsp/lsp.cpp