ZAP: zap Namespace Reference
zap Namespace Reference
Namespaces
namespace args
namespace anonymous_namespace{driver.cpp}
namespace frontend
namespace lsp
namespace anonymous_namespace{parser.cpp}
namespace detail
namespace text
Classes
class driver
Orchestrates and controls the entire compilation process. Order of the functions that should be called is by how they are defined here in the header. Meaning that first is parseArgs(int, char**), second is splitInputs(), third is verifySources(), and so on... Most functions return true on error not on success. It returns error due to easy checks like if(verifyOutput()) return 1;.
class _version_base
Base class for the version.
class Parser
struct DiagnosticPosition
struct DiagnosticRange
struct Diagnostic
class DiagnosticTextFormatter
class DiagnosticEngine
struct HandleColors
class StdoutStream
class StderrStream
class Stream
A base stream class.
class SFStream
Standard FILE* stream.
Typedefs
using version = _version_base<uint16_t>
Can be changed to any integer or float type.
Enumerations
enum class DiagnosticLevel {
Note ,
Warning ,
Error
}
enum class ColorOverride : uint8_t {
AUTO ,
ALWAYS ,
NEVER
}
Allows to override if colors are allowed or not.
enum class Color {
BLACK = 30 ,
RED ,
GREEN ,
YELLOW ,
BLUE ,
MAGENTA ,
CYAN ,
WHITE ,
BRIGHT_BLACK = 90 ,
BRIGHT_RED ,
BRIGHT_GREEN ,
BRIGHT_YELLOW ,
BRIGHT_BLUE ,
BRIGHT_MAGENTA ,
BRIGHT_CYAN ,
BRIGHT_WHITE
}
Functions
void printHelp ()
void printVersion ()
template<typename... TArgs>
void reportError (TArgs &&...args)
constexpr version ZAP_VERSION (0, 2, 1)
Zap's version, displayed when –version is used.
bool compileSourceZIR (sema::BoundRootNode &node, std::ostream &ofoutput)
bool compileSourceLLVMFromZIR (sema::BoundRootNode &node, std::ostream &ofoutput, const std::string &targetTriple, bool freestanding)
std::unique_ptr< zir::Module > generateZIRModule (sema::BoundRootNode &node)
bool compileObjectFromZIR (sema::BoundRootNode &node, const std::string &output_path, int optimization_level, const std::string &targetTriple, bool freestanding)
bool compileAssemblyFromZIR (sema::BoundRootNode &node, const std::string &output_path, int optimization_level, const std::string &targetTriple, bool freestanding)
bool compileLoadedModules (driver &drv, const std::filesystem::path &entryPath)
bool verifyFile (const std::filesystem::path &input)
Stream & err ()
Stream & out ()
Variables
constexpr const char * ZAP_NAME = ZAP_NAME_MACRO
Name that displays when –help is used.
ColorOverride color_override = ColorOverride::AUTO
static HandleColors standard_stream_colors
Typedef Documentation
version
using zap::version = _version_base<uint16_t>
Can be changed to any integer or float type.
Definition at line 34 of file version.hpp.
Enumeration Type Documentation
Color
enum class zap::Color strong
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
BRIGHT_BLACK
BRIGHT_RED
BRIGHT_GREEN
BRIGHT_YELLOW
BRIGHT_BLUE
BRIGHT_MAGENTA
BRIGHT_CYAN
BRIGHT_WHITE
Definition at line 17 of file stream.hpp.
                 {
  BLACK = 30,
  RED,
  GREEN,
  YELLOW,
  BLUE,
  MAGENTA,
  CYAN,
  WHITE,
  BRIGHT_BLACK = 90,
  BRIGHT_RED,
  BRIGHT_GREEN,
  BRIGHT_YELLOW,
  BRIGHT_BLUE,
  BRIGHT_MAGENTA,
  BRIGHT_CYAN,
  BRIGHT_WHITE
};
ColorOverride
enum class zap::ColorOverride : uint8_t strong
Allows to override if colors are allowed or not.
Enumerator
AUTO
ALWAYS
NEVER
Definition at line 14 of file stream.hpp.
: uint8_t { AUTO, ALWAYS, NEVER };
DiagnosticLevel
enum class zap::DiagnosticLevel strong
Enumerator
Note
Warning
Error
Definition at line 14 of file diagnostics.hpp.
{ Note, Warning, Error };
Function Documentation
compileAssemblyFromZIR()
bool zap::compileAssemblyFromZIR (sema::BoundRootNode & node, const std::string & output_path, int optimization_level, const std::string & targetTriple, bool freestanding)
Definition at line 436 of file driver.cpp.
{
  try {
    auto mod = generateZIRModule(node);
    if (!mod) {
      driver::reportError("failed to generate ZIR");
      return true;
    }
    codegen::LLVMCodeGen llvmGen(targetTriple, freestanding);
    llvmGen.generate(*mod);
    if (!llvmGen.emitAssemblyFile(output_path, optimization_level)) {
      driver::reportError("assembly file emission failed");
      return true;
    }
  } catch (const std::exception &ex) {
    driver::reportError("Assembly generation failed: ", ex.what());
    return true;
  }
  return false;
}
References codegen::LLVMCodeGen::emitAssemblyFile(), codegen::LLVMCodeGen::generate(), generateZIRModule(), and zap::driver::reportError().
Referenced by zap::driver::compileLoadedModules, and zap::driver::compileSourceFile().
compileLoadedModules()
bool zap::compileLoadedModules (driver & drv, const std::filesystem::path & entryPath)
Definition at line 198 of file driver.cpp.
{
  std::map<std::string, std::unique_ptr<sema::ModuleInfo>> moduleMap;
  std::set<std::string> visiting;
  if (loadModuleGraph(entryPath, moduleMap, visiting,
                      drv.cmdArgs.incStdlib && drv.cmdArgs.incPrelude,
                      drv.cmdArgs.importMap)) {
    return true;
  }
  auto entryId = std::filesystem::weakly_canonical(entryPath).string();
  if (moduleMap.find(entryId) == moduleMap.end()) {
    driver::reportError("failed to load entry module: ", entryPath);
    return true;
  }
  moduleMap[entryId]->isEntry = true;
  std::string entrySource;
  if (readSourceFile(entryPath, entrySource)) {
    return true;
  }
  DiagnosticEngine diagnostics(entrySource, entryPath.string());
  std::vector<sema::ModuleInfo> modules;
  modules.reserve(moduleMap.size());
  for (auto &[_, module] : moduleMap) {
    diagnostics.registerSource(module->sourceName, module->sourceText);
    modules.push_back(std::move(*module));
  }
  sema::Binder binder(diagnostics, true);
  auto boundAst = binder.bind(modules);
  diagnostics.printText(err());
  if (!boundAst) {
    driver::reportError(entryPath, ": semantic analysis failed");
    return true;
  }
  if (drv.binary_output()) {
    std::filesystem::path out_path;
    if (drv.get_output_type() == args::OutputType::EXEC) {
      out_path = entryPath.string() + ".o";
      drv.cleanups.emplace_back(out_path);
    } else if (drv.get_output_type() == args::OutputType::OBJECT) {
      if (drv.is_implicit_output()) {
        out_path = entryPath.string() + ".o";
      } else {
        out_path = drv.get_output();
      }
    }
    if (compileObjectFromZIR(*boundAst, out_path.string(),
                             static_cast<int>(drv.cmdArgs.optLevel),
                             drv.cmdArgs.targetTriple,
                             drv.cmdArgs.freestanding)) {
      return true;
    }
    drv.cmdArgs.objects.emplace_back(std::move(out_path));
  } else if (drv.get_output_type() == args::OutputType::ASM) {
    std::filesystem::path out_path =
        drv.is_implicit_output() ? entryPath : drv.get_output();
    out_path.replace_extension(
        driver::format_fileextension(args::OutputType::ASM));
    if (compileAssemblyFromZIR(*boundAst, out_path.string(),
                               static_cast<int>(drv.cmdArgs.optLevel),
                               drv.cmdArgs.targetTriple,
                               drv.cmdArgs.freestanding)) {
      return true;
    }
  } else if (drv.emits_text_output()) {
    std::filesystem::path out_path =
        drv.is_implicit_output() ? entryPath : drv.get_output();
    if (emitRequestedTextOutputs(drv, *boundAst, out_path)) {
      return true;
    }
  } else {
    return true;
  }
  return false;
}
compileObjectFromZIR()
bool zap::compileObjectFromZIR (sema::BoundRootNode & node, const std::string & output_path, int optimization_level, const std::string & targetTriple, bool freestanding)
Definition at line 412 of file driver.cpp.
{
  try {
    auto mod = generateZIRModule(node);
    if (!mod) {
      driver::reportError("failed to generate ZIR");
      return true;
    }
    codegen::LLVMCodeGen llvmGen(targetTriple, freestanding);
    llvmGen.generate(*mod);
    if (!llvmGen.emitObjectFile(output_path, optimization_level)) {
      driver::reportError("object file emission failed");
      return true;
    }
  } catch (const std::exception &ex) {
    driver::reportError("Object generation failed: ", ex.what());
    return true;
  }
  return false;
}
References codegen::LLVMCodeGen::emitObjectFile(), codegen::LLVMCodeGen::generate(), generateZIRModule(), and zap::driver::reportError().
Referenced by zap::driver::compileLoadedModules, and zap::driver::compileSourceFile().
compileSourceLLVMFromZIR()
bool zap::compileSourceLLVMFromZIR (sema::BoundRootNode & node, std::ostream & ofoutput, const std::string & targetTriple, bool freestanding)
Definition at line 389 of file driver.cpp.
{
  try {
    auto mod = generateZIRModule(node);
    if (!mod) {
      driver::reportError("failed to generate ZIR");
      return true;
    }
    codegen::LLVMCodeGen llvmGen(targetTriple, freestanding);
    llvmGen.generate(*mod);
    std::string ir;
    llvm::raw_string_ostream rs(ir);
    llvmGen.printIR(rs);
    ofoutput << ir;
  } catch (const std::exception &ex) {
    driver::reportError("LLVM text generation failed: ", ex.what());
    return true;
  }
  return false;
}
References codegen::LLVMCodeGen::generate(), generateZIRModule(), codegen::LLVMCodeGen::printIR(), and zap::driver::reportError().
Referenced by zap::anonymous_namespace{driver.cpp}::emitRequestedTextOutputs().
compileSourceZIR()
bool zap::compileSourceZIR (sema::BoundRootNode & node, std::ostream & ofoutput)
Definition at line 373 of file driver.cpp.
{
  try {
    auto mod = generateZIRModule(node);
    if (mod) {
      ofoutput << mod->toString();
    } else {
      driver::reportError("failed to generate ZIR");
      return true;
    }
  } catch (const std::exception &ex) {
    driver::reportError("ZIR generation failed: ", ex.what());
    return true;
  }
  return false;
}
References generateZIRModule(), and zap::driver::reportError().
Referenced by zap::anonymous_namespace{driver.cpp}::emitRequestedTextOutputs().
err()
Stream & zap::err ()
Definition at line 105 of file stream.cpp.
              {
  static StderrStream stderrStream(stderr, false);
  return stderrStream;
}
Referenced by zap::driver::compileLoadedModules, zap::driver::compileSourceFile(), zap::anonymous_namespace{driver.cpp}::loadModuleGraph(), main(), zap::anonymous_namespace{driver.cpp}::readSourceFile(), reportError(), and zap::driver::reportWarning().
generateZIRModule()
std::unique_ptr< zir::Module > zap::generateZIRModule (sema::BoundRootNode & node)
Definition at line 368 of file driver.cpp.
{
  zir::BoundIRGenerator irGen;
  return irGen.generate(node);
}
References zir::BoundIRGenerator::generate().
Referenced by compileAssemblyFromZIR(), compileObjectFromZIR(), compileSourceLLVMFromZIR(), and compileSourceZIR().
out()
Stream & zap::out ()
Definition at line 110 of file stream.cpp.
              {
  static StdoutStream stdoutStream(stdout, false);
  return stdoutStream;
}
Referenced by zap::lsp::anonymous_namespace{lsp.cpp}::appendEscapedJsonString(), zap::lsp::anonymous_namespace{lsp.cpp}::appendUtf8(), zap::detail::expandTabsForDisplay(), zap::driver::parseArgs(), printHelp(), printVersion(), zap::anonymous_namespace{parser.cpp}::qualifiedNameFromExpressionImpl(), zap::frontend::setImportError(), zap::lsp::signatureForNode(), and zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson().
printHelp()
void zap::printHelp ()
This file includes the flags for the zapc driver.
The macro itself follows a simple format: ZAP_FLAG(ID /* Name of the Enum ‍/ Flag / The flag's string ‍/ HelpMessage / The message that displays when –help is used. ‍/ Kind / Kind of the arg (Flag, Joined, etc..) *‍/)
Definition at line 8 of file argparse.cpp.
                 {
  out() << "Usage: zapc [options] <file>\n"
           "Options:\n";
#define ZAP_FLAG(ID, STR, MSG, ...)                                            \
  out() << "  " STR;                                                           \
  if constexpr ((2 + (sizeof(STR) - 1)) >= 18) {                               \
    (out() << '\n').indent(18) << MSG "\n";                                    \
  } else {                                                                     \
    out().indent(18 - ((sizeof(STR) - 1) + 2)) << MSG "\n";                    \
  }
#include "flags.inc"
#undef ZAP_FLAG
}
References out().
Referenced by zap::args::parse().
printVersion()
void zap::printVersion ()
Definition at line 22 of file argparse.cpp.
{ out() << "Zap Compiler v" << ZAP_VERSION << '\n'; }
References out(), and ZAP_VERSION().
Referenced by zap::args::parse().
reportError()
template<typename... TArgs> void zap::reportError (TArgs &&... args)
Definition at line 11 of file argparse.hpp.
{
  ((err() << "zapc: ").changeColor(Color::RED, true) << "error: ").resetColor();
  (err() << ... << args);
  err() << '\n';
}
References err(), and RED.
Referenced by zap::args::parse(), and zap::driver::reportError().
verifyFile()
bool zap::verifyFile (const std::filesystem::path & input)
Definition at line 345 of file driver.cpp.
{
  if (!std::filesystem::exists(input)) {
    driver::reportError("provided file doesn't exist: ", input);
    return true;
  } else if (!std::filesystem::is_regular_file(input)) {
    driver::reportError("provided file isn't a regular file: ", input);
    return true;
  }
  return false;
}
References zap::driver::reportError().
Referenced by zap::driver::verifySources().
ZAP_VERSION()
version zap::ZAP_VERSION (0 , 2 , 1) constexpr
Zap's version, displayed when –version is used.
Referenced by printVersion().
Variable Documentation
color_override
ColorOverride zap::color_override = ColorOverride::AUTO
Definition at line 12 of file stream.cpp.
Referenced by zap::HandleColors::HandleColors().
standard_stream_colors
HandleColors zap::standard_stream_colors static
Definition at line 81 of file stream.cpp.
Referenced by zap::StderrStream::hasColors(), zap::StdoutStream::hasColors(), zap::StderrStream::onTTY(), and zap::StdoutStream::onTTY().
ZAP_NAME
const char* zap::ZAP_NAME = ZAP_NAME_MACRO constexpr
Name that displays when –help is used.
Definition at line 12 of file compiler.hpp.