ZAP: codegen::LLVMCodeGen Class Reference
codegen::LLVMCodeGen Class Reference
#include <llvm_codegen.hpp>
Public Member Functions
LLVMCodeGen (std::string targetTriple={}, bool freestanding=false)
~LLVMCodeGen ()
void generate (sema::BoundRootNode &root)
void generate (const zir::Module &module)
void printIR (llvm::raw_ostream &) const
bool emitObjectFile (const std::string &path, int optimization_level=0)
bool emitAssemblyFile (const std::string &path, int optimization_level=0)
void visit (sema::BoundRootNode &node) override
void visit (sema::BoundFunctionDeclaration &node) override
void visit (sema::BoundExternalFunctionDeclaration &node) override
void visit (sema::BoundBlock &node) override
void visit (sema::BoundVariableDeclaration &node) override
void visit (sema::BoundReturnStatement &node) override
void visit (sema::BoundAssignment &node) override
void visit (sema::BoundExpressionStatement &node) override
void visit (sema::BoundLiteral &node) override
void visit (sema::BoundVariableExpression &node) override
void visit (sema::BoundCompoundTargetLoad &node) override
void visit (sema::BoundBinaryExpression &node) override
void visit (sema::BoundTernaryExpression &node) override
void visit (sema::BoundUnaryExpression &node) override
void visit (sema::BoundFunctionCall &node) override
void visit (sema::BoundIndirectCall &node) override
void visit (sema::BoundFunctionReference &node) override
void visit (sema::BoundArrayLiteral &node) override
void visit (sema::BoundIndexAccess &node) override
void visit (sema::BoundRecordDeclaration &node) override
void visit (sema::BoundEnumDeclaration &node) override
void visit (sema::BoundTaggedUnionDeclaration &node) override
void visit (sema::BoundMemberAccess &node) override
void visit (sema::BoundStructLiteral &node) override
void visit (sema::BoundTaggedUnionLiteral &node) override
void visit (sema::BoundModuleReference &node) override
void visit (sema::BoundIfStatement &node) override
void visit (sema::BoundWhileStatement &node) override
void visit (sema::BoundForStatement &node) override
void visit (sema::BoundBreakStatement &node) override
void visit (sema::BoundContinueStatement &node) override
void visit (sema::BoundAsmStatement &node) override
void visit (sema::BoundCast &node) override
void visit (sema::BoundNewExpression &node) override
void visit (sema::BoundWeakLockExpression &node) override
void visit (sema::BoundWeakAliveExpression &node) override
void visit (sema::BoundTryExpression &node) override
void visit (sema::BoundFallbackExpression &node) override
void visit (sema::BoundFailableHandleExpression &node) override
void visit (sema::BoundFailStatement &node) override
Public Member Functions inherited from sema::BoundVisitor
virtual ~BoundVisitor ()=default
Private Member Functions
llvm::Constant * getOrCreateGlobalString (const std::string &str, std::string &globalName)
llvm::Type * toLLVMType (const zir::Type &ty)
llvm::Type * toLLVMAggregateFieldType (const std::shared_ptr< zir::Type > &type)
llvm::FunctionType * buildFunctionType (const sema::FunctionSymbol &sym, bool injectMainProcessArgs=false)
llvm::FunctionType * buildFunctionType (const zir::Function &fn)
void initializeModule ()
void declareZIRFunction (const zir::Function &fn, bool isExternal)
void emitZIRFunction (const zir::Function &fn)
void emitZIRInstruction (const zir::Instruction &inst)
void buildInlineAsmCall (const std::string &assembly, const std::vector< std::string > &outConstraints, const std::vector< llvm::Value * > &outAddrs, const std::vector< llvm::Type * > &outValueTypes, const std::vector< std::string > &inConstraints, const std::vector< llvm::Value * > &inValues, const std::vector< std::string > &clobbers)
llvm::Value * lowerZIRValue (const std::shared_ptr< zir::Value > &value)
llvm::Value * lowerZIRRValue (const std::shared_ptr< zir::Value > &value)
llvm::Constant * lowerZIRConstant (const zir::Constant &constant)
llvm::Constant * lowerZIRAggregateConstant (const zir::AggregateConstant &constant)
llvm::Constant * lowerZIRArrayConstant (const zir::ArrayConstant &constant)
llvm::Value * lowerZIRCast (llvm::Value *src, const std::shared_ptr< zir::Type > &sourceType, const std::shared_ptr< zir::Type > &targetType)
llvm::Value * emitStringConcat (llvm::Value *lhs, llvm::Value *rhs, const std::shared_ptr< zir::Type > &lhsType, const std::shared_ptr< zir::Type > &rhsType, const std::shared_ptr< zir::Type > &resultType)
llvm::AllocaInst * createEntryAlloca (llvm::Function *fn, const std::string &name, llvm::Type *ty)
bool isClassType (const std::shared_ptr< zir::Type > &type) const
bool isWeakClassType (const std::shared_ptr< zir::Type > &type) const
bool isOwnedStringType (const std::shared_ptr< zir::Type > &type) const
bool expressionProducesOwnedClass (const sema::BoundExpression *expr) const
bool expressionProducesOwnedString (const sema::BoundExpression *expr) const
void emitRetainIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
void emitReleaseIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
llvm::Value * emitStringRetainIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
void emitStringReleaseIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
void emitRetainWeakIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
void emitReleaseWeakIfNeeded (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
llvm::Value * emitWeakAlive (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
llvm::Value * emitWeakLock (llvm::Value *value, const std::shared_ptr< zir::Type > &type)
void emitStoreWithArc (llvm::Value *addr, llvm::Value *value, const std::shared_ptr< zir::Type > &type, bool valueIsOwned, bool skipReleaseOld=false)
void emitStoreWithStringArc (llvm::Value *addr, llvm::Value *value, const std::shared_ptr< zir::Type > &type, bool valueIsOwned, bool skipReleaseOld=false)
void emitScopeReleases ()
void ensureArcSupport (sema::BoundRootNode &root)
void ensureClassArcSupport (const std::shared_ptr< zir::ClassType > &classType)
void computeCyclicClasses (const zir::Module &module)
llvm::StructType * getOrCreateClassStruct (const zir::ClassType &ct)
void finalizeClassStruct (const zir::ClassType &ct)
Private Attributes
llvm::LLVMContext ctx_
llvm::IRBuilder builder_
std::unique_ptr< llvm::Module > module_
std::string targetTriple_
bool freestanding_ = false
llvm::Function * currentFn_ = nullptr
llvm::Value * lastValue_ = nullptr
bool evaluateAsAddr_ = false
llvm::Value * compoundTargetAddr_ = nullptr
std::map< std::string, llvm::Value * > localValues_
std::map< std::string, llvm::GlobalVariable * > globalValues_
std::map< std::string, llvm::Function * > functionMap_
std::map< std::string, const zir::Function * > zirFunctionMap_
std::map< std::string, llvm::StructType * > structCache_
std::map< std::string, std::map< int, llvm::Function * > > classVirtualMethodFns_
std::map< std::string, llvm::GlobalVariable * > classVTables_
std::map< std::string, llvm::Function * > classRetainFns_
std::map< std::string, llvm::Function * > classReleaseFns_
std::map< std::string, llvm::Function * > classDestroyFns_
std::map< std::string, llvm::Function * > classDestructorFns_
std::map< std::string, llvm::GlobalVariable * > classMetadataGlobals_
std::unordered_set< std::string > cyclicClasses_
std::vector< std::vector< std::pair< std::shared_ptr< zir::Type >, llvm::Value * > > > scopeClassLocals_
std::vector< std::vector< std::pair< std::shared_ptr< zir::Type >, llvm::Value * > > > scopeStringLocals_
std::unique_ptr< ClassArcEmitter > arcEmitter_
std::unordered_map< const zir::Value *, llvm::Value * > zirValueMap_
std::unordered_set< const zir::Value * > refReturnValues_
std::unordered_map< std::string, llvm::BasicBlock * > zirBlockMap_
std::unordered_map< std::string, llvm::BasicBlock * > zirBlockExitMap_
std::unordered_set< const zir::Value * > zirOwnedClassValues_
std::unordered_set< const zir::Value * > zirOwnedStringValues_
std::unordered_set< const zir::Value * > zirClassParamAllocas_
std::unordered_set< const zir::Value * > zirPendingClassParamInitAllocas_
std::vector< std::pair< std::shared_ptr< zir::Type >, llvm::Value * > > zirFunctionClassLocals_
std::vector< std::pair< std::shared_ptr< zir::Type >, llvm::Value * > > zirFunctionStringLocals_
const zir::Function * currentZIRFunction_ = nullptr
size_t zirParamSpillIndex_ = 0
int nextStringId_ = 0
std::vector< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > > loopBBStack_
Friends
class ClassArcEmitter
Detailed Description
Definition at line 18 of file llvm_codegen.hpp.
Constructor & Destructor Documentation
LLVMCodeGen()
codegen::LLVMCodeGen::LLVMCodeGen (std::string targetTriple = {}, bool freestanding = false) explicit
Definition at line 152 of file llvm_codegen.cpp.
    : builder_(ctx_),
      targetTriple_(normalizeTargetTriple(std::move(targetTriple))),
      freestanding_(freestanding), evaluateAsAddr_(false),
      arcEmitter_(std::make_unique<ClassArcEmitter>(*this)), nextStringId_(0) {
  initializeLLVMTargets();
}
References arcEmitter_, builder_, ClassArcEmitter, ctx_, evaluateAsAddr_, freestanding_, nextStringId_, and targetTriple_.
~LLVMCodeGen()
codegen::LLVMCodeGen::~LLVMCodeGen () default
Member Function Documentation
buildFunctionType() [1/2]
llvm::FunctionType * codegen::LLVMCodeGen::buildFunctionType (const sema::FunctionSymbol & sym, bool injectMainProcessArgs = false) private
Definition at line 517 of file llvm_codegen.cpp.
{
  std::vector<llvm::Type *> paramTypes;
  if (injectMainProcessArgs) {
    paramTypes.push_back(llvm::Type::getInt32Ty(ctx_));
    paramTypes.push_back(llvm::PointerType::getUnqual(
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_))));
  }
  for (const auto &param : sym.parameters) {
    if (param->is_variadic_pack) {
      paramTypes.push_back(llvm::Type::getInt32Ty(ctx_));
      paramTypes.push_back(llvm::PointerType::getUnqual(
          toLLVMType(*param->variadic_element_type)));
      continue;
    }
    auto *ty = toLLVMType(*param->type);
    if (param->is_ref)
      ty = llvm::PointerType::getUnqual(ty);
    paramTypes.push_back(ty);
  }
  llvm::Type *retTy = toLLVMType(*sym.returnType);
  if (sym.returnsRef)
    retTy = llvm::PointerType::getUnqual(retTy);
  return llvm::FunctionType::get(retTy, paramTypes, sym.isCVariadic);
}
References ctx_, sema::FunctionSymbol::isCVariadic, sema::FunctionSymbol::parameters, sema::FunctionSymbol::returnsRef, sema::FunctionSymbol::returnType, and toLLVMType().
Referenced by declareZIRFunction(), and visit().
buildFunctionType() [2/2]
llvm::FunctionType * codegen::LLVMCodeGen::buildFunctionType (const zir::Function & fn) private
Definition at line 544 of file llvm_codegen.cpp.
{
  std::vector<llvm::Type *> paramTypes;
  if (!freestanding_ && fn.name == "main") {
    paramTypes.push_back(llvm::Type::getInt32Ty(ctx_));
    paramTypes.push_back(llvm::PointerType::getUnqual(
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_))));
  }
  for (const auto &param : fn.getArguments()) {
    if (param->isVariadicPack()) {
      paramTypes.push_back(llvm::Type::getInt32Ty(ctx_));
      paramTypes.push_back(llvm::PointerType::getUnqual(
          toLLVMType(*param->getVariadicElementType())));
      continue;
    }
    paramTypes.push_back(toLLVMType(*param->getType()));
  }
  llvm::Type *retTy = toLLVMType(*fn.getReturnType());
  if (fn.returnsRef)
    retTy = llvm::PointerType::getUnqual(retTy);
  return llvm::FunctionType::get(retTy, paramTypes, fn.isCVariadic);
}
References ctx_, freestanding_, zir::Function::getArguments(), zir::Function::getReturnType(), zir::Function::isCVariadic, zir::Function::name, zir::Function::returnsRef, and toLLVMType().
buildInlineAsmCall()
void codegen::LLVMCodeGen::buildInlineAsmCall (const std::string & assembly, const std::vector< std::string > & outConstraints, const std::vector< llvm::Value * > & outAddrs, const std::vector< llvm::Type * > & outValueTypes, const std::vector< std::string > & inConstraints, const std::vector< llvm::Value * > & inValues, const std::vector< std::string > & clobbers) private
Definition at line 629 of file llvm_codegen.cpp.
{
  llvm::Triple triple(module_->getTargetTriple());
  std::vector<std::string> parts;
  for (const auto &c : outConstraints)
    parts.push_back(lowerAsmConstraintToLLVM(c, triple));
  for (const auto &c : inConstraints)
    parts.push_back(lowerAsmConstraintToLLVM(c, triple));
  for (const auto &c : clobbers)
    parts.push_back("~{" + c + "}");
  std::string constraints;
  for (size_t i = 0; i < parts.size(); ++i) {
    if (i > 0)
      constraints += ",";
    constraints += parts[i];
  }
  llvm::Type *retTy;
  if (outValueTypes.empty()) {
    retTy = llvm::Type::getVoidTy(ctx_);
  } else if (outValueTypes.size() == 1) {
    retTy = outValueTypes[0];
  } else {
    retTy = llvm::StructType::get(ctx_, outValueTypes);
  }
  std::vector<llvm::Type *> paramTypes;
  for (auto *v : inValues)
    paramTypes.push_back(v->getType());
  auto *fnTy = llvm::FunctionType::get(retTy, paramTypes, /*isVarArg=*/false);
  auto *inlineAsm =
      llvm::InlineAsm::get(fnTy, lowerGccAsmTemplateToLLVM(assembly),
                           constraints, /*hasSideEffects=*/true);
  auto *call = builder_.CreateCall(inlineAsm, inValues);
  if (outValueTypes.size() == 1) {
    builder_.CreateStore(call, outAddrs[0]);
  } else if (outValueTypes.size() > 1) {
    for (unsigned i = 0; i < outValueTypes.size(); ++i) {
      auto *field = builder_.CreateExtractValue(call, {i});
      builder_.CreateStore(field, outAddrs[i]);
    }
  }
}
References builder_, ctx_, and module_.
Referenced by emitZIRInstruction(), and visit().
computeCyclicClasses()
void codegen::LLVMCodeGen::computeCyclicClasses (const zir::Module & module) private
Definition at line 222 of file llvm_codegen.cpp.
{
  cyclicClasses_.clear();
  std::unordered_map<std::string, std::shared_ptr<zir::ClassType>> classes;
  for (const auto &type : module.getTypes()) {
    if (type->getKind() == zir::TypeKind::Class) {
      auto cls = std::static_pointer_cast<zir::ClassType>(type);
      classes[cls->getName()] = cls;
    }
  }
  std::unordered_map<std::string, std::vector<std::string>> subtypesOf;
  for (const auto &[name, cls] : classes) {
    for (auto cur = cls; cur; cur = cur->getBase()) {
      subtypesOf[cur->getName()].push_back(name);
    }
  }
  std::unordered_map<std::string, std::unordered_set<std::string>> edges;
  for (const auto &[name, cls] : classes) {
    auto &out = edges[name];
    for (auto cur = cls; cur; cur = cur->getBase()) {
      for (const auto &field : cur->getFields()) {
        if (!field.type || field.type->getKind() != zir::TypeKind::Class) {
          continue;
        }
        auto fieldClass = std::static_pointer_cast<zir::ClassType>(field.type);
        if (fieldClass->isWeak()) {
          continue;
        }
        auto it = subtypesOf.find(fieldClass->getName());
        if (it == subtypesOf.end()) {
          continue;
        }
        for (const auto &sub : it->second) {
          out.insert(sub);
        }
      }
    }
  }
  for (const auto &[start, _] : classes) {
    std::vector<std::string> stack = {start};
    std::unordered_set<std::string> seen;
    bool cyclic = false;
    while (!stack.empty()) {
      std::string node = std::move(stack.back());
      stack.pop_back();
      auto it = edges.find(node);
      if (it == edges.end()) {
        continue;
      }
      for (const auto &next : it->second) {
        if (next == start) {
          cyclic = true;
          break;
        }
        if (seen.insert(next).second) {
          stack.push_back(next);
        }
      }
      if (cyclic) {
        break;
      }
    }
    if (cyclic) {
      cyclicClasses_.insert(start);
    }
  }
}
References zir::Class, cyclicClasses_, and zir::Module::getTypes().
Referenced by generate().
createEntryAlloca()
llvm::AllocaInst * codegen::LLVMCodeGen::createEntryAlloca (llvm::Function * fn, const std::string & name, llvm::Type * ty) private
Definition at line 566 of file llvm_codegen.cpp.
{
  llvm::IRBuilder<> entry(&fn->getEntryBlock(), fn->getEntryBlock().begin());
  return entry.CreateAlloca(ty, nullptr, name);
}
Referenced by emitStringConcat(), emitZIRInstruction(), visit(), visit(), visit(), visit(), and visit().
declareZIRFunction()
void codegen::LLVMCodeGen::declareZIRFunction (const zir::Function & fn, bool isExternal) private
Definition at line 133 of file llvm_codegen_zir.cpp.
{
  auto *ft = buildFunctionType(fn);
  auto linkage = llvm::Function::ExternalLinkage;
  auto *llvmFn = llvm::Function::Create(ft, linkage, fn.name, *module_);
  auto argIt = llvmFn->arg_begin();
  for (const auto &arg : fn.getArguments()) {
    if (arg->isVariadicPack()) {
      argIt->setName(arg->getRawName() + ".count");
      ++argIt;
      argIt->setName(arg->getRawName() + ".data");
      ++argIt;
      continue;
    }
    argIt->setName(arg->getRawName());
    ++argIt;
  }
  functionMap_[fn.name] = llvmFn;
  (void)isExternal;
}
References buildFunctionType(), functionMap_, zir::Function::getArguments(), module_, and zir::Function::name.
Referenced by emitZIRInstruction(), generate(), lowerZIRValue(), and visit().
emitAssemblyFile()
bool codegen::LLVMCodeGen::emitAssemblyFile (const std::string & path, int optimization_level = 0)
Definition at line 343 of file llvm_codegen.cpp.
{
  llvm::Triple triple(targetTriple_);
  module_->setTargetTriple(triple);
  std::string error;
  const auto *target = llvm::TargetRegistry::lookupTarget(triple, error);
  if (!target) {
    llvm::errs() << "Target lookup failed: " << error << "\n";
    return false;
  }
  llvm::TargetOptions opts;
  std::unique_ptr<llvm::TargetMachine> tm(target->createTargetMachine(
      triple, "generic", "", opts, llvm::Reloc::PIC_, std::nullopt,
      toCodeGenOptLevel(optimization_level)));
  if (!tm) {
    llvm::errs() << "Failed to create target machine for: " << targetTriple_
                 << "\n";
    return false;
  }
  module_->setDataLayout(tm->createDataLayout());
  std::error_code ec;
  llvm::raw_fd_ostream dest(path, ec, llvm::sys::fs::OF_None);
  if (ec) {
    llvm::errs() << "Cannot open output file: " << ec.message() << "\n";
    return false;
  }
  llvm::legacy::PassManager pm;
  if (tm->addPassesToEmitFile(pm, dest, nullptr,
                              llvm::CodeGenFileType::AssemblyFile)) {
    llvm::errs() << "TargetMachine cannot emit assembly file\n";
    return false;
  }
  bool is_broken = llvm::verifyModule(*module_, &llvm::errs());
  if (!is_broken) {
    pm.run(*module_);
  }
  dest.flush();
  return !is_broken;
}
References module_, and targetTriple_.
Referenced by zap::compileAssemblyFromZIR().
emitObjectFile()
bool codegen::LLVMCodeGen::emitObjectFile (const std::string & path, int optimization_level = 0)
Definition at line 298 of file llvm_codegen.cpp.
{
  llvm::Triple triple(targetTriple_);
  module_->setTargetTriple(triple);
  std::string error;
  const auto *target = llvm::TargetRegistry::lookupTarget(triple, error);
  if (!target) {
    llvm::errs() << "Target lookup failed: " << error << "\n";
    return false;
  }
  llvm::TargetOptions opts;
  std::unique_ptr<llvm::TargetMachine> tm(target->createTargetMachine(
      triple, "generic", "", opts, llvm::Reloc::PIC_, std::nullopt,
      toCodeGenOptLevel(optimization_level)));
  if (!tm) {
    llvm::errs() << "Failed to create target machine for: " << targetTriple_
                 << "\n";
    return false;
  }
  module_->setDataLayout(tm->createDataLayout());
  std::error_code ec;
  llvm::raw_fd_ostream dest(path, ec, llvm::sys::fs::OF_None);
  if (ec) {
    llvm::errs() << "Cannot open output file: " << ec.message() << "\n";
    return false;
  }
  llvm::legacy::PassManager pm;
  if (tm->addPassesToEmitFile(pm, dest, nullptr,
                              llvm::CodeGenFileType::ObjectFile)) {
    llvm::errs() << "TargetMachine cannot emit object file\n";
    return false;
  }
  // TODO: Improve handling of verifying the module.
  bool is_broken = llvm::verifyModule(*module_, &llvm::errs());
  if (!is_broken)
    pm.run(*module_);
  dest.flush();
  return !is_broken;
}
References module_, and targetTriple_.
Referenced by zap::compileObjectFromZIR().
emitReleaseIfNeeded()
void codegen::LLVMCodeGen::emitReleaseIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 49 of file llvm_codegen_arc.cpp.
{
  if (isOwnedStringType(type)) {
    emitStringReleaseIfNeeded(value, type);
    return;
  }
  arcEmitter_->emitReleaseIfNeeded(value, type);
}
References arcEmitter_, emitStringReleaseIfNeeded(), and isOwnedStringType().
Referenced by emitZIRInstruction(), visit(), visit(), visit(), and visit().
emitReleaseWeakIfNeeded()
void codegen::LLVMCodeGen::emitReleaseWeakIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 109 of file llvm_codegen_arc.cpp.
{
  arcEmitter_->emitReleaseWeakIfNeeded(value, type);
}
References arcEmitter_.
Referenced by emitZIRInstruction(), visit(), and visit().
emitRetainIfNeeded()
void codegen::LLVMCodeGen::emitRetainIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 40 of file llvm_codegen_arc.cpp.
{
  if (isOwnedStringType(type)) {
    (void)emitStringRetainIfNeeded(value, type);
    return;
  }
  arcEmitter_->emitRetainIfNeeded(value, type);
}
References arcEmitter_, emitStringRetainIfNeeded(), and isOwnedStringType().
Referenced by emitZIRInstruction(), visit(), visit(), and visit().
emitRetainWeakIfNeeded()
void codegen::LLVMCodeGen::emitRetainWeakIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 104 of file llvm_codegen_arc.cpp.
{
  arcEmitter_->emitRetainWeakIfNeeded(value, type);
}
References arcEmitter_.
emitScopeReleases()
void codegen::LLVMCodeGen::emitScopeReleases () private
Definition at line 150 of file llvm_codegen_arc.cpp.
{
  arcEmitter_->emitScopeReleases();
  if (scopeStringLocals_.empty()) {
    return;
  }
  auto &locals = scopeStringLocals_.back();
  for (auto it = locals.rbegin(); it != locals.rend(); ++it) {
    auto *value = builder_.CreateLoad(toLLVMType(*it->first), it->second,
                                      "str.scope.release");
    emitStringReleaseIfNeeded(value, it->first);
  }
}
References arcEmitter_, builder_, emitStringReleaseIfNeeded(), scopeStringLocals_, and toLLVMType().
Referenced by visit().
emitStoreWithArc()
void codegen::LLVMCodeGen::emitStoreWithArc (llvm::Value * addr, llvm::Value * value, const std::shared_ptr< zir::Type > & type, bool valueIsOwned, bool skipReleaseOld = false) private
Definition at line 125 of file llvm_codegen_arc.cpp.
{
  if (isOwnedStringType(type)) {
    emitStoreWithStringArc(addr, value, type, valueIsOwned, skipReleaseOld);
    return;
  }
  arcEmitter_->emitStoreWithArc(addr, value, type, valueIsOwned,
                                skipReleaseOld);
}
References arcEmitter_, emitStoreWithStringArc(), and isOwnedStringType().
Referenced by emitZIRInstruction(), visit(), visit(), and visit().
emitStoreWithStringArc()
void codegen::LLVMCodeGen::emitStoreWithStringArc (llvm::Value * addr, llvm::Value * value, const std::shared_ptr< zir::Type > & type, bool valueIsOwned, bool skipReleaseOld = false) private
Definition at line 136 of file llvm_codegen_arc.cpp.
{
  if (!skipReleaseOld) {
    auto *oldValue = builder_.CreateLoad(toLLVMType(*type), addr, "str.old");
    emitStringReleaseIfNeeded(oldValue, type);
  }
  auto *storedValue =
      valueIsOwned ? value : emitStringRetainIfNeeded(value, type);
  builder_.CreateStore(storedValue, addr);
}
References builder_, emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), and toLLVMType().
Referenced by emitStoreWithArc(), emitZIRInstruction(), visit(), and visit().
emitStringConcat()
llvm::Value * codegen::LLVMCodeGen::emitStringConcat (llvm::Value * lhs, llvm::Value * rhs, const std::shared_ptr< zir::Type > & lhsType, const std::shared_ptr< zir::Type > & rhsType, const std::shared_ptr< zir::Type > & resultType) private
Definition at line 574 of file llvm_codegen.cpp.
{
  auto *i8Ty = llvm::Type::getInt8Ty(ctx_);
  auto *i64Ty = llvm::Type::getInt64Ty(ctx_);
  llvm::Value *lhsPtr = nullptr;
  llvm::Value *lhsLen = nullptr;
  llvm::Value *rhsPtr = nullptr;
  llvm::Value *rhsLen = nullptr;
  if (isStringType(lhsType)) {
    lhsPtr = builder_.CreateExtractValue(lhs, {0});
    lhsLen = builder_.CreateExtractValue(lhs, {1});
  } else if (lhsType && lhsType->getKind() == zir::TypeKind::Char) {
    auto *buf = createEntryAlloca(currentFn_, "zir_char_buf_l", i8Ty);
    builder_.CreateStore(lhs, buf);
    lhsPtr = buf;
    lhsLen = llvm::ConstantInt::get(i64Ty, 1);
  }
  if (isStringType(rhsType)) {
    rhsPtr = builder_.CreateExtractValue(rhs, {0});
    rhsLen = builder_.CreateExtractValue(rhs, {1});
  } else if (rhsType && rhsType->getKind() == zir::TypeKind::Char) {
    auto *buf = createEntryAlloca(currentFn_, "zir_char_buf_r", i8Ty);
    builder_.CreateStore(rhs, buf);
    rhsPtr = buf;
    rhsLen = llvm::ConstantInt::get(i64Ty, 1);
  }
  auto concatIt = functionMap_.find("string_concat_ptrlen");
  if (concatIt == functionMap_.end()) {
    std::vector<llvm::Type *> params = {
        llvm::PointerType::getUnqual(i8Ty), i64Ty,
        llvm::PointerType::getUnqual(i8Ty), i64Ty};
    auto *ft = llvm::FunctionType::get(llvm::PointerType::getUnqual(i8Ty),
                                       params, false);
    auto *fn = llvm::Function::Create(ft, llvm::Function::ExternalLinkage,
                                      "string_concat_ptrlen", *module_);
    concatIt = functionMap_.emplace("string_concat_ptrlen", fn).first;
  }
  auto *concatFn = concatIt->second;
  auto *call = builder_.CreateCall(concatFn, {lhsPtr, lhsLen, rhsPtr, rhsLen});
  auto *sumLen = builder_.CreateAdd(lhsLen, rhsLen);
  auto *structTy = static_cast<llvm::StructType *>(toLLVMType(*resultType));
  llvm::Value *res = llvm::UndefValue::get(structTy);
  res = builder_.CreateInsertValue(res, call, {0});
  res = builder_.CreateInsertValue(res, sumLen, {1});
  return res;
}
References builder_, zir::Char, createEntryAlloca(), ctx_, currentFn_, functionMap_, module_, and toLLVMType().
Referenced by emitZIRInstruction(), and visit().
emitStringReleaseIfNeeded()
void codegen::LLVMCodeGen::emitStringReleaseIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 81 of file llvm_codegen_arc.cpp.
{
  if (!isOwnedStringType(type)) {
    return;
  }
  auto *stringTy = toLLVMType(*type);
  if (value->getType() != stringTy && isStringLikeStruct(value->getType()) &&
      isStringLikeStruct(stringTy)) {
    auto *ptr = builder_.CreateExtractValue(value, {0}, "str.cvt.ptr");
    auto *len = builder_.CreateExtractValue(value, {1}, "str.cvt.len");
    llvm::Value *converted = llvm::UndefValue::get(stringTy);
    converted =
        builder_.CreateInsertValue(converted, ptr, {0}, "str.cvt.ptr.i");
    converted =
        builder_.CreateInsertValue(converted, len, {1}, "str.cvt.len.i");
    value = converted;
  }
  auto *fnTy =
      llvm::FunctionType::get(llvm::Type::getVoidTy(ctx_), {stringTy}, false);
  auto callee = module_->getOrInsertFunction("zap_string_release", fnTy);
  builder_.CreateCall(fnTy, callee.getCallee(), {value});
}
References builder_, ctx_, isOwnedStringType(), len(), module_, and toLLVMType().
Referenced by emitReleaseIfNeeded(), emitScopeReleases(), emitStoreWithStringArc(), emitZIRInstruction(), visit(), and visit().
emitStringRetainIfNeeded()
llvm::Value * codegen::LLVMCodeGen::emitStringRetainIfNeeded (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 59 of file llvm_codegen_arc.cpp.
{
  if (!isOwnedStringType(type)) {
    return value;
  }
  auto *stringTy = toLLVMType(*type);
  if (value->getType() != stringTy && isStringLikeStruct(value->getType()) &&
      isStringLikeStruct(stringTy)) {
    auto *ptr = builder_.CreateExtractValue(value, {0}, "str.cvt.ptr");
    auto *len = builder_.CreateExtractValue(value, {1}, "str.cvt.len");
    llvm::Value *converted = llvm::UndefValue::get(stringTy);
    converted =
        builder_.CreateInsertValue(converted, ptr, {0}, "str.cvt.ptr.i");
    converted =
        builder_.CreateInsertValue(converted, len, {1}, "str.cvt.len.i");
    value = converted;
  }
  auto *fnTy = llvm::FunctionType::get(stringTy, {stringTy}, false);
  auto callee = module_->getOrInsertFunction("zap_string_retain", fnTy);
  return builder_.CreateCall(fnTy, callee.getCallee(), {value}, "str.retain");
}
References builder_, isOwnedStringType(), len(), module_, and toLLVMType().
Referenced by emitRetainIfNeeded(), emitStoreWithStringArc(), emitZIRInstruction(), and visit().
emitWeakAlive()
llvm::Value * codegen::LLVMCodeGen::emitWeakAlive (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 115 of file llvm_codegen_arc.cpp.
{
  return arcEmitter_->emitWeakAlive(value, type);
}
References arcEmitter_.
Referenced by emitZIRInstruction(), and visit().
emitWeakLock()
llvm::Value * codegen::LLVMCodeGen::emitWeakLock (llvm::Value * value, const std::shared_ptr< zir::Type > & type) private
Definition at line 120 of file llvm_codegen_arc.cpp.
{
  return arcEmitter_->emitWeakLock(value, type);
}
References arcEmitter_.
Referenced by emitZIRInstruction(), and visit().
emitZIRFunction()
void codegen::LLVMCodeGen::emitZIRFunction (const zir::Function & fn) private
Definition at line 1241 of file llvm_codegen_zir.cpp.
{
  currentZIRFunction_ = &fn;
  currentFn_ = functionMap_.at(fn.name);
  zirBlockMap_.clear();
  zirValueMap_.clear();
  zirOwnedClassValues_.clear();
  zirOwnedStringValues_.clear();
  zirClassParamAllocas_.clear();
  zirPendingClassParamInitAllocas_.clear();
  zirFunctionClassLocals_.clear();
  zirFunctionStringLocals_.clear();
  zirParamSpillIndex_ = 0;
  zirBlockExitMap_.clear();
  auto llvmArgIt = currentFn_->arg_begin();
  if (!freestanding_ && fn.name == "main") {
    auto *i32Ty = llvm::Type::getInt32Ty(ctx_);
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *argvTy = llvm::PointerType::getUnqual(i8PtrTy);
    llvmArgIt->setName("argc");
    llvm::Value *argcValue = &*llvmArgIt++;
    llvmArgIt->setName("argv");
    llvm::Value *argvValue = &*llvmArgIt++;
    auto setArgsIt = functionMap_.find("__zap_process_set_args");
    if (setArgsIt == functionMap_.end()) {
      auto *ft = llvm::FunctionType::get(llvm::Type::getVoidTy(ctx_),
                                         {i32Ty, argvTy}, false);
      auto *setArgsFn =
          llvm::Function::Create(ft, llvm::Function::ExternalLinkage,
                                 "__zap_process_set_args", *module_);
      setArgsIt =
          functionMap_.emplace("__zap_process_set_args", setArgsFn).first;
    }
    builder_.SetInsertPoint(
        llvm::BasicBlock::Create(ctx_, "entry", currentFn_));
    builder_.CreateCall(
        setArgsIt->second,
        {builder_.CreateIntCast(argcValue, i32Ty, true), argvValue});
    builder_.CreateBr(llvm::BasicBlock::Create(
        ctx_, fn.getBlocks().front()->label, currentFn_));
    zirBlockMap_[fn.getBlocks().front()->label] = &currentFn_->back();
  }
  std::vector<llvm::Value *> physicalArgs;
  for (; llvmArgIt != currentFn_->arg_end(); ++llvmArgIt) {
    physicalArgs.push_back(&*llvmArgIt);
  }
  for (size_t i = 0; i < fn.getBlocks().size(); ++i) {
    const auto &block = fn.getBlocks()[i];
    if (!freestanding_ && fn.name == "main" && i == 0 &&
        zirBlockMap_.count(block->label) != 0) {
      continue;
    }
    zirBlockMap_[block->label] =
        llvm::BasicBlock::Create(ctx_, block->label, currentFn_);
  }
  auto *argInsertBlock = zirBlockMap_.at(fn.getBlocks().front()->label);
  builder_.SetInsertPoint(argInsertBlock, argInsertBlock->begin());
  size_t physicalArgIndex = 0;
  for (const auto &arg : fn.getArguments()) {
    if (arg->isVariadicPack()) {
      auto *sliceTy =
          static_cast<llvm::StructType *>(toLLVMType(*arg->getType()));
      llvm::Value *sliceValue = llvm::PoisonValue::get(sliceTy);
      llvm::Value *countValue = physicalArgs.at(physicalArgIndex++);
      llvm::Value *dataValue = physicalArgs.at(physicalArgIndex++);
      sliceValue = builder_.CreateInsertValue(sliceValue, dataValue, {0},
                                              arg->getRawName() + ".data");
      if (countValue->getType() != sliceTy->getElementType(1)) {
        countValue = builder_.CreateIntCast(
            countValue, sliceTy->getElementType(1),
            /*isSigned=*/true, arg->getRawName() + ".len.cast");
      }
      sliceValue = builder_.CreateInsertValue(sliceValue, countValue, {1},
                                              arg->getRawName() + ".len");
      zirValueMap_[arg.get()] = sliceValue;
      continue;
    }
    zirValueMap_[arg.get()] = physicalArgs.at(physicalArgIndex++);
  }
  for (const auto &block : fn.getBlocks()) {
    builder_.SetInsertPoint(zirBlockMap_.at(block->label));
    for (const auto &inst : block->getInstructions()) {
      emitZIRInstruction(*inst);
      if (builder_.GetInsertBlock()->getTerminator()) {
        break;
      }
    }
    auto *endBlock = builder_.GetInsertBlock();
    if (endBlock && endBlock->getTerminator()) {
      zirBlockExitMap_[block->label] = endBlock;
    } else {
      zirBlockExitMap_[block->label] = zirBlockMap_.at(block->label);
    }
  }
  currentFn_ = nullptr;
  currentZIRFunction_ = nullptr;
  zirBlockMap_.clear();
  zirValueMap_.clear();
  zirOwnedClassValues_.clear();
  zirOwnedStringValues_.clear();
  zirBlockExitMap_.clear();
  zirClassParamAllocas_.clear();
  zirPendingClassParamInitAllocas_.clear();
  zirFunctionClassLocals_.clear();
  zirFunctionStringLocals_.clear();
}
References builder_, ctx_, currentFn_, currentZIRFunction_, emitZIRInstruction(), freestanding_, functionMap_, zir::Function::getArguments(), zir::Function::getBlocks(), module_, zir::Function::name, toLLVMType(), zirBlockExitMap_, zirBlockMap_, zirClassParamAllocas_, zirFunctionClassLocals_, zirFunctionStringLocals_, zirOwnedClassValues_, zirOwnedStringValues_, zirParamSpillIndex_, zirPendingClassParamInitAllocas_, and zirValueMap_.
Referenced by generate().
emitZIRInstruction()
void codegen::LLVMCodeGen::emitZIRInstruction (const zir::Instruction & inst) private
Definition at line 296 of file llvm_codegen_zir.cpp.
{
  using namespace zir;
  switch (inst.getOpCode()) {
  case OpCode::Alloca: {
    const auto &allocaInst = static_cast<const AllocaInst &>(inst);
    bool isParamSpill =
        currentZIRFunction_ &&
        zirParamSpillIndex_ < currentZIRFunction_->getArguments().size();
    bool isBorrowedSelf = false;
    if (isParamSpill) {
      isBorrowedSelf = !currentZIRFunction_->ownerTypeName.empty() &&
                       currentZIRFunction_->getArguments()[zirParamSpillIndex_]
                               ->getRawName() == "self";
    }
    auto *alloca = createEntryAlloca(
        currentFn_,
        static_cast<const Register &>(*allocaInst.getResult()).getRawName(),
        toLLVMType(*allocaInst.getAllocatedType()));
    zirValueMap_[allocaInst.getResult().get()] = alloca;
    if (isClassType(allocaInst.getAllocatedType())) {
      builder_.CreateStore(llvm::Constant::getNullValue(
                               toLLVMType(*allocaInst.getAllocatedType())),
                           alloca);
      if (isParamSpill) {
        zirClassParamAllocas_.insert(allocaInst.getResult().get());
        zirPendingClassParamInitAllocas_.insert(allocaInst.getResult().get());
      }
      if (!isBorrowedSelf) {
        zirFunctionClassLocals_.push_back(
            {allocaInst.getAllocatedType(), alloca});
      }
    } else if (isOwnedStringType(allocaInst.getAllocatedType())) {
      builder_.CreateStore(llvm::Constant::getNullValue(
                               toLLVMType(*allocaInst.getAllocatedType())),
                           alloca);
      zirFunctionStringLocals_.push_back(
          {allocaInst.getAllocatedType(), alloca});
    }
    if (isParamSpill) {
      ++zirParamSpillIndex_;
    }
    return;
  }
  case OpCode::Load: {
    const auto &loadInst = static_cast<const LoadInst &>(inst);
    auto *src = lowerZIRValue(loadInst.getSource());
    auto *value = builder_.CreateLoad(
        toLLVMType(*loadInst.getResult()->getType()), src,
        static_cast<const Register &>(*loadInst.getResult()).getRawName());
    zirValueMap_[loadInst.getResult().get()] = value;
    return;
  }
  case OpCode::Store: {
    const auto &storeInst = static_cast<const StoreInst &>(inst);
    auto *dst = lowerZIRValue(storeInst.getDestination());
    auto *src = lowerZIRRValue(storeInst.getSource());
    auto dstType = storeInst.getDestination()->getType();
    auto ptrType = std::dynamic_pointer_cast<zir::PointerType>(dstType);
    auto valueType = ptrType ? ptrType->getBaseType() : nullptr;
    bool skipReleaseOld = storeInst.initStore();
    if (storeInst.bypassArc()) {
      builder_.CreateStore(src, dst);
    } else if (valueType && isClassType(valueType)) {
      if (zirPendingClassParamInitAllocas_.count(
              storeInst.getDestination().get()) > 0) {
        builder_.CreateStore(src, dst);
        zirPendingClassParamInitAllocas_.erase(
            storeInst.getDestination().get());
      } else {
        bool valueIsOwned =
            zirOwnedClassValues_.count(storeInst.getSource().get()) > 0;
        emitStoreWithArc(dst, src, valueType, valueIsOwned, skipReleaseOld);
        if (valueIsOwned) {
          zirOwnedClassValues_.erase(storeInst.getSource().get());
        }
      }
    } else if (valueType && isOwnedStringType(valueType)) {
      bool valueIsOwned =
          zirOwnedStringValues_.count(storeInst.getSource().get()) > 0;
      emitStoreWithStringArc(dst, src, valueType, valueIsOwned, skipReleaseOld);
      if (valueIsOwned) {
        zirOwnedStringValues_.erase(storeInst.getSource().get());
      }
    } else {
      builder_.CreateStore(src, dst);
    }
    return;
  }
  case OpCode::Add:
  case OpCode::Sub:
  case OpCode::Mul:
  case OpCode::SDiv:
  case OpCode::UDiv:
  case OpCode::SRem:
  case OpCode::URem:
  case OpCode::Shl:
  case OpCode::LShr:
  case OpCode::AShr:
  case OpCode::BitAnd:
  case OpCode::BitOr:
  case OpCode::BitXor: {
    const auto &binaryInst = static_cast<const BinaryInst &>(inst);
    auto *lhs = lowerZIRRValue(binaryInst.getLhs());
    auto *rhs = lowerZIRRValue(binaryInst.getRhs());
    llvm::Value *result = nullptr;
    bool lhsIsPointer =
        binaryInst.getLhs()->getType()->getKind() == zir::TypeKind::Pointer;
    bool rhsIsPointer =
        binaryInst.getRhs()->getType()->getKind() == zir::TypeKind::Pointer;
    switch (inst.getOpCode()) {
    case OpCode::Add:
      if (isStringType(binaryInst.getLhs()->getType()) ||
          isStringType(binaryInst.getRhs()->getType()) ||
          binaryInst.getLhs()->getType()->getKind() == zir::TypeKind::Char ||
          binaryInst.getRhs()->getType()->getKind() == zir::TypeKind::Char) {
        result = emitStringConcat(lhs, rhs, binaryInst.getLhs()->getType(),
                                  binaryInst.getRhs()->getType(),
                                  binaryInst.getResult()->getType());
        if (isOwnedStringType(binaryInst.getResult()->getType())) {
          zirOwnedStringValues_.insert(binaryInst.getResult().get());
        }
      } else if (lhsIsPointer || rhsIsPointer) {
        llvm::Value *pointerValue = lhsIsPointer ? lhs : rhs;
        llvm::Value *offsetValue = lhsIsPointer ? rhs : lhs;
        auto pointerType = std::static_pointer_cast<zir::PointerType>(
            lhsIsPointer ? binaryInst.getLhs()->getType()
                         : binaryInst.getRhs()->getType());
        auto *elemTy = toLLVMType(*pointerType->getBaseType());
        auto *indexTy = llvm::Type::getInt64Ty(ctx_);
        auto *index =
            builder_.CreateIntCast(offsetValue, indexTy, /*isSigned=*/true);
        result = builder_.CreateInBoundsGEP(elemTy, pointerValue, index);
      } else if (lhs->getType()->isFloatingPointTy()) {
        result = builder_.CreateFAdd(lhs, rhs);
      } else {
        result = builder_.CreateAdd(lhs, rhs);
      }
      break;
    case OpCode::Sub:
      if (lhsIsPointer && rhsIsPointer) {
        auto pointerType = std::static_pointer_cast<zir::PointerType>(
            binaryInst.getLhs()->getType());
        auto *elemTy = toLLVMType(*pointerType->getBaseType());
        auto *i64Ty = llvm::Type::getInt64Ty(ctx_);
        auto *lhsInt = builder_.CreatePtrToInt(lhs, i64Ty);
        auto *rhsInt = builder_.CreatePtrToInt(rhs, i64Ty);
        auto *bytes = builder_.CreateSub(lhsInt, rhsInt);
        llvm::Value *elemSize = llvm::ConstantExpr::getSizeOf(elemTy);
        if (elemSize->getType() != i64Ty) {
          elemSize = builder_.CreateIntCast(elemSize, i64Ty, false);
        }
        result = builder_.CreateSDiv(bytes, elemSize);
      } else if (lhsIsPointer) {
        auto pointerType = std::static_pointer_cast<zir::PointerType>(
            binaryInst.getLhs()->getType());
        auto *elemTy = toLLVMType(*pointerType->getBaseType());
        auto *indexTy = llvm::Type::getInt64Ty(ctx_);
        auto *index = builder_.CreateIntCast(rhs, indexTy, /*isSigned=*/true);
        index = builder_.CreateNeg(index);
        result = builder_.CreateInBoundsGEP(elemTy, lhs, index);
      } else if (lhs->getType()->isFloatingPointTy()) {
        result = builder_.CreateFSub(lhs, rhs);
      } else {
        result = builder_.CreateSub(lhs, rhs);
      }
      break;
    case OpCode::Mul:
      result = lhs->getType()->isFloatingPointTy()
                   ? builder_.CreateFMul(lhs, rhs)
                   : builder_.CreateMul(lhs, rhs);
      break;
    case OpCode::SDiv:
      result = lhs->getType()->isFloatingPointTy()
                   ? builder_.CreateFDiv(lhs, rhs)
                   : builder_.CreateSDiv(lhs, rhs);
      break;
    case OpCode::UDiv:
      result = lhs->getType()->isFloatingPointTy()
                   ? builder_.CreateFDiv(lhs, rhs)
                   : builder_.CreateUDiv(lhs, rhs);
      break;
    case OpCode::SRem:
      result = lhs->getType()->isFloatingPointTy()
                   ? builder_.CreateFRem(lhs, rhs)
                   : builder_.CreateSRem(lhs, rhs);
      break;
    case OpCode::URem:
      result = lhs->getType()->isFloatingPointTy()
                   ? builder_.CreateFRem(lhs, rhs)
                   : builder_.CreateURem(lhs, rhs);
      break;
    case OpCode::Shl:
      result = builder_.CreateShl(lhs, rhs);
      break;
    case OpCode::LShr:
      result = builder_.CreateLShr(lhs, rhs);
      break;
    case OpCode::AShr:
      result = builder_.CreateAShr(lhs, rhs);
      break;
    case OpCode::BitAnd:
      result = builder_.CreateAnd(lhs, rhs);
      break;
    case OpCode::BitOr:
      result = builder_.CreateOr(lhs, rhs);
      break;
    case OpCode::BitXor:
      result = builder_.CreateXor(lhs, rhs);
      break;
    default:
      break;
    }
    zirValueMap_[binaryInst.getResult().get()] = result;
    return;
  }
  case OpCode::Cmp: {
    const auto &cmpInst = static_cast<const CmpInst &>(inst);
    auto *lhs = lowerZIRRValue(cmpInst.getLhs());
    auto *rhs = lowerZIRRValue(cmpInst.getRhs());
    llvm::Value *result = nullptr;
    const auto &pred = cmpInst.getPredicate();
    auto *lhsTy = lhs->getType();
    auto *rhsTy = rhs->getType();
    if (lhsTy != rhsTy) {
      if (lhsTy->isIntegerTy() && rhsTy->isIntegerTy()) {
        unsigned lhsBits = lhsTy->getIntegerBitWidth();
        unsigned rhsBits = rhsTy->getIntegerBitWidth();
        if (lhsBits < rhsBits) {
          bool lhsUnsigned = cmpInst.getLhs() && cmpInst.getLhs()->getType()
                                 ? cmpInst.getLhs()->getType()->isUnsigned()
                                 : false;
          lhs = lhsUnsigned ? builder_.CreateZExt(lhs, rhsTy)
                            : builder_.CreateSExt(lhs, rhsTy);
          lhsTy = lhs->getType();
        } else if (rhsBits < lhsBits) {
          bool rhsUnsigned = cmpInst.getRhs() && cmpInst.getRhs()->getType()
                                 ? cmpInst.getRhs()->getType()->isUnsigned()
                                 : false;
          rhs = rhsUnsigned ? builder_.CreateZExt(rhs, lhsTy)
                            : builder_.CreateSExt(rhs, lhsTy);
          rhsTy = rhs->getType();
        }
      } else if (lhsTy->isFloatingPointTy() && rhsTy->isFloatingPointTy()) {
        unsigned lhsBits = lhsTy->getPrimitiveSizeInBits();
        unsigned rhsBits = rhsTy->getPrimitiveSizeInBits();
        if (lhsBits < rhsBits) {
          lhs = builder_.CreateFPExt(lhs, rhsTy);
          lhsTy = lhs->getType();
        } else if (rhsBits < lhsBits) {
          rhs = builder_.CreateFPExt(rhs, lhsTy);
          rhsTy = rhs->getType();
        }
      } else if (lhsTy->isIntegerTy() && rhsTy->isFloatingPointTy()) {
        bool lhsUnsigned = cmpInst.getLhs() && cmpInst.getLhs()->getType()
                               ? cmpInst.getLhs()->getType()->isUnsigned()
                               : false;
        lhs = lhsUnsigned ? builder_.CreateUIToFP(lhs, rhsTy)
                          : builder_.CreateSIToFP(lhs, rhsTy);
        lhsTy = lhs->getType();
      } else if (lhsTy->isFloatingPointTy() && rhsTy->isIntegerTy()) {
        bool rhsUnsigned = cmpInst.getRhs() && cmpInst.getRhs()->getType()
                               ? cmpInst.getRhs()->getType()->isUnsigned()
                               : false;
        rhs = rhsUnsigned ? builder_.CreateUIToFP(rhs, lhsTy)
                          : builder_.CreateSIToFP(rhs, lhsTy);
        rhsTy = rhs->getType();
      }
    }
    if (lhsTy != rhsTy) {
      throw std::runtime_error(
          "ZIR cmp operand type mismatch after coercion: " +
          cmpInst.getLhs()->getTypeName() + " vs " +
          cmpInst.getRhs()->getTypeName());
    }
    if (isStringLLVMStructType(lhsTy) && isStringLLVMStructType(rhsTy) &&
        (pred == "eq" || pred == "ne")) {
      auto *boolTy = llvm::Type::getInt1Ty(ctx_);
      auto *strTy = lhsTy;
      auto *eqFnTy = llvm::FunctionType::get(boolTy, {strTy, strTy}, false);
      auto eqCallee = module_->getOrInsertFunction("eq", eqFnTy);
      auto *isEq = builder_.CreateCall(eqFnTy, eqCallee.getCallee(), {lhs, rhs},
                                       "str.eq");
      zirValueMap_[cmpInst.getResult().get()] =
          pred == "eq" ? isEq : builder_.CreateNot(isEq, "str.ne");
      return;
    }
    if (lhsTy->isFloatingPointTy()) {
      if (pred == "eq")
        result = builder_.CreateFCmpOEQ(lhs, rhs);
      else if (pred == "ne")
        result = builder_.CreateFCmpONE(lhs, rhs);
      else if (pred == "slt" || pred == "ult")
        result = builder_.CreateFCmpOLT(lhs, rhs);
      else if (pred == "sle" || pred == "ule")
        result = builder_.CreateFCmpOLE(lhs, rhs);
      else if (pred == "sgt" || pred == "ugt")
        result = builder_.CreateFCmpOGT(lhs, rhs);
      else if (pred == "sge" || pred == "uge")
        result = builder_.CreateFCmpOGE(lhs, rhs);
    } else if (lhsTy->isIntOrIntVectorTy() || lhsTy->isPtrOrPtrVectorTy()) {
      if (pred == "eq")
        result = builder_.CreateICmpEQ(lhs, rhs);
      else if (pred == "ne")
        result = builder_.CreateICmpNE(lhs, rhs);
      else if (pred == "slt")
        result = builder_.CreateICmpSLT(lhs, rhs);
      else if (pred == "sle")
        result = builder_.CreateICmpSLE(lhs, rhs);
      else if (pred == "sgt")
        result = builder_.CreateICmpSGT(lhs, rhs);
      else if (pred == "sge")
        result = builder_.CreateICmpSGE(lhs, rhs);
      else if (pred == "ult")
        result = builder_.CreateICmpULT(lhs, rhs);
      else if (pred == "ule")
        result = builder_.CreateICmpULE(lhs, rhs);
      else if (pred == "ugt")
        result = builder_.CreateICmpUGT(lhs, rhs);
      else if (pred == "uge")
        result = builder_.CreateICmpUGE(lhs, rhs);
    }
    if (!result) {
      throw std::runtime_error("unsupported ZIR cmp predicate/type: " + pred +
                               " on " + cmpInst.getLhs()->getTypeName());
    }
    zirValueMap_[cmpInst.getResult().get()] = result;
    return;
  }
  case OpCode::Br: {
    const auto &branchInst = static_cast<const BranchInst &>(inst);
    builder_.CreateBr(zirBlockMap_.at(branchInst.getTarget()));
    return;
  }
  case OpCode::CondBr: {
    const auto &branchInst = static_cast<const CondBranchInst &>(inst);
    builder_.CreateCondBr(lowerZIRRValue(branchInst.getCondition()),
                          zirBlockMap_.at(branchInst.getTrueLabel()),
                          zirBlockMap_.at(branchInst.getFalseLabel()));
    return;
  }
  case OpCode::Ret: {
    const auto &returnInst = static_cast<const ReturnInst &>(inst);
    if (returnInst.getValue()) {
      auto *retValue = lowerZIRRValue(returnInst.getValue());
      auto retType = returnInst.getValue()->getType();
      if (isClassType(retType) &&
          zirOwnedClassValues_.count(returnInst.getValue().get()) == 0) {
        emitRetainIfNeeded(retValue, retType);
      } else if (isOwnedStringType(retType) &&
                 zirOwnedStringValues_.count(returnInst.getValue().get()) ==
                     0) {
        retValue = emitStringRetainIfNeeded(retValue, retType);
      }
      for (auto it = zirFunctionClassLocals_.rbegin();
           it != zirFunctionClassLocals_.rend(); ++it) {
        auto *value = builder_.CreateLoad(toLLVMType(*it->first), it->second,
                                          "zir.arc.ret.release");
        if (isWeakClassType(it->first)) {
          emitReleaseWeakIfNeeded(value, it->first);
        } else {
          emitReleaseIfNeeded(value, it->first);
        }
      }
      for (auto it = zirFunctionStringLocals_.rbegin();
           it != zirFunctionStringLocals_.rend(); ++it) {
        auto *value = builder_.CreateLoad(toLLVMType(*it->first), it->second,
                                          "zir.str.ret.release");
        emitStringReleaseIfNeeded(value, it->first);
      }
      builder_.CreateRet(retValue);
    } else {
      for (auto it = zirFunctionClassLocals_.rbegin();
           it != zirFunctionClassLocals_.rend(); ++it) {
        auto *value = builder_.CreateLoad(toLLVMType(*it->first), it->second,
                                          "zir.arc.ret.release");
        if (isWeakClassType(it->first)) {
          emitReleaseWeakIfNeeded(value, it->first);
        } else {
          emitReleaseIfNeeded(value, it->first);
        }
      }
      for (auto it = zirFunctionStringLocals_.rbegin();
           it != zirFunctionStringLocals_.rend(); ++it) {
        auto *value = builder_.CreateLoad(toLLVMType(*it->first), it->second,
                                          "zir.str.ret.release");
        emitStringReleaseIfNeeded(value, it->first);
      }
      builder_.CreateRetVoid();
    }
    return;
  }
  case OpCode::Call: {
    const auto &callInst = static_cast<const CallInst &>(inst);
    std::vector<llvm::Value *> args;
    if (callInst.isIndirect()) {
      auto *calleePtr = lowerZIRRValue(callInst.getCalleeValue());
      const auto &fpType = static_cast<const zir::FunctionPointerType &>(
          *callInst.getCalleeValue()->getType());
      std::vector<llvm::Type *> paramTypes;
      for (const auto &p : fpType.getParams())
        paramTypes.push_back(toLLVMType(*p));
      auto *fnTy = llvm::FunctionType::get(toLLVMType(*fpType.getReturnType()),
                                           paramTypes, false);
      for (const auto &arg : callInst.getArguments())
        args.push_back(lowerZIRRValue(arg));
      auto *call = builder_.CreateCall(fnTy, calleePtr, args);
      if (callInst.getResult()) {
        zirValueMap_[callInst.getResult().get()] = call;
        if (callInst.returnsRef()) {
          refReturnValues_.insert(callInst.getResult().get());
        }
      }
      return;
    }
    auto calleeIt = functionMap_.find(callInst.getFunctionName());
    if (calleeIt == functionMap_.end()) {
      auto zirDeclIt = zirFunctionMap_.find(callInst.getFunctionName());
      if (zirDeclIt != zirFunctionMap_.end()) {
        declareZIRFunction(*zirDeclIt->second, true);
        calleeIt = functionMap_.find(callInst.getFunctionName());
      }
    }
    if (calleeIt == functionMap_.end()) {
      auto *existing = module_->getFunction(callInst.getFunctionName());
      if (!existing) {
        std::vector<llvm::Type *> inferredParamTypes;
        inferredParamTypes.reserve(callInst.getArguments().size());
        for (size_t i = 0; i < callInst.getArguments().size(); ++i) {
          bool isRef = i < callInst.getArgumentIsRef().size() &&
                       callInst.getArgumentIsRef()[i];
          auto *argTy =
              isRef ? lowerZIRValue(callInst.getArguments()[i])->getType()
                    : lowerZIRRValue(callInst.getArguments()[i])->getType();
          inferredParamTypes.push_back(argTy);
        }
        llvm::Type *retTy = llvm::Type::getVoidTy(ctx_);
        if (callInst.getResult()) {
          retTy = toLLVMType(*callInst.getResult()->getType());
        }
        auto *fnTy = llvm::FunctionType::get(retTy, inferredParamTypes, false);
        existing = llvm::Function::Create(fnTy, llvm::Function::ExternalLinkage,
                                          callInst.getFunctionName(), *module_);
      }
      functionMap_[callInst.getFunctionName()] = existing;
      calleeIt = functionMap_.find(callInst.getFunctionName());
    }
    if (calleeIt == functionMap_.end()) {
      throw std::runtime_error("missing callee in LLVM function map: " +
                               callInst.getFunctionName());
    }
    auto *callee = calleeIt->second;
    auto *calleeTy = callee->getFunctionType();
    auto zirIt = zirFunctionMap_.find(callInst.getFunctionName());
    size_t fixedParamCount = callInst.getArguments().size();
    bool hasVariadicParameter = false;
    std::shared_ptr<zir::Type> variadicElementType = nullptr;
    bool isCVariadic = calleeTy->isVarArg();
    if (zirIt != zirFunctionMap_.end()) {
      fixedParamCount = 0;
      for (const auto &param : zirIt->second->getArguments()) {
        if (param->isVariadicPack()) {
          hasVariadicParameter = true;
          variadicElementType = param->getVariadicElementType();
          break;
        }
        ++fixedParamCount;
      }
      isCVariadic = zirIt->second->isCVariadic;
    }
    for (size_t i = 0; i < callInst.getArguments().size(); ++i) {
      bool isRef = i < callInst.getArgumentIsRef().size() &&
                   callInst.getArgumentIsRef()[i];
      auto *arg = isRef ? lowerZIRValue(callInst.getArguments()[i])
                        : lowerZIRRValue(callInst.getArguments()[i]);
      std::shared_ptr<zir::Type> calleeParamType = nullptr;
      if (zirIt != zirFunctionMap_.end() && i < fixedParamCount &&
          i < zirIt->second->getArguments().size()) {
        calleeParamType = zirIt->second->getArguments()[i]->getType();
      }
      llvm::Type *paramTy = nullptr;
      if (i < fixedParamCount &&
          static_cast<unsigned>(i) < calleeTy->getNumParams()) {
        paramTy = calleeTy->getParamType(static_cast<unsigned>(i));
      }
      if (paramTy && arg->getType() != paramTy) {
        if (isStringLLVMStructType(arg->getType()) &&
            isStringLLVMStructType(paramTy)) {
          auto *ptr = builder_.CreateExtractValue(arg, {0}, "zir.call.str.ptr");
          auto *len = builder_.CreateExtractValue(arg, {1}, "zir.call.str.len");
          llvm::Value *converted = llvm::UndefValue::get(paramTy);
          converted = builder_.CreateInsertValue(converted, ptr, {0},
                                                 "zir.call.str.ptr.i");
          converted = builder_.CreateInsertValue(converted, len, {1},
                                                 "zir.call.str.len.i");
          arg = converted;
        }
        auto *argPtrTy = llvm::dyn_cast<llvm::PointerType>(arg->getType());
        if (argPtrTy && !paramTy->isPointerTy()) {
          arg = builder_.CreateLoad(paramTy, arg, "zir.call.arg");
        }
      } else if (isCVariadic && i >= fixedParamCount) {
        // C varargs default argument promotions:
        // - integer types narrower than int -> int
        // - float -> double
        // (already-typed varargs keep their value category)
        auto *argTy = arg->getType();
        if (argTy->isIntegerTy()) {
          unsigned bits = argTy->getIntegerBitWidth();
          if (bits < 32) {
            auto argType = callInst.getArguments()[i]
                               ? callInst.getArguments()[i]->getType()
                               : nullptr;
            bool isUnsignedArg =
                argType && (argType->isUnsigned() ||
                            argType->getKind() == zir::TypeKind::Bool ||
                            argType->getKind() == zir::TypeKind::Char);
            auto *i32Ty = llvm::Type::getInt32Ty(ctx_);
            arg = isUnsignedArg
                      ? builder_.CreateZExt(arg, i32Ty, "cvararg.zext")
                      : builder_.CreateSExt(arg, i32Ty, "cvararg.sext");
          }
        } else if (argTy->isFloatTy()) {
          auto *f64Ty = llvm::Type::getDoubleTy(ctx_);
          arg = builder_.CreateFPExt(arg, f64Ty, "cvararg.fpext");
        }
      }
      bool isBorrowedSelfArg =
          zirIt != zirFunctionMap_.end() && i == 0 &&
          !zirIt->second->ownerTypeName.empty() &&
          i < zirIt->second->getArguments().size() &&
          zirIt->second->getArguments()[i]->getRawName() == "self";
      if (!isRef && i < fixedParamCount && !isBorrowedSelfArg &&
          !(calleeParamType && isWeakClassType(calleeParamType)) &&
          isClassType(callInst.getArguments()[i]->getType()) &&
          zirOwnedClassValues_.count(callInst.getArguments()[i].get()) == 0) {
        emitRetainIfNeeded(arg, callInst.getArguments()[i]->getType());
      }
      args.push_back(arg);
    }
    if (hasVariadicParameter) {
      auto *elemTy = toLLVMType(*variadicElementType);
      auto *elemPtrTy = llvm::PointerType::getUnqual(elemTy);
      size_t explicitVariadicCount =
          callInst.getArguments().size() - fixedParamCount;
      llvm::Value *forwardedCount =
          llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0);
      llvm::Value *forwardedData = llvm::ConstantPointerNull::get(elemPtrTy);
      if (callInst.getVariadicPack()) {
        auto *packValue = lowerZIRRValue(callInst.getVariadicPack());
        forwardedData =
            builder_.CreateExtractValue(packValue, {0}, "varargs.forward.data");
        forwardedCount =
            builder_.CreateExtractValue(packValue, {1}, "varargs.forward.len");
        if (forwardedCount->getType() != llvm::Type::getInt32Ty(ctx_)) {
          forwardedCount = builder_.CreateIntCast(
              forwardedCount, llvm::Type::getInt32Ty(ctx_), /*isSigned=*/true);
        }
      }
      llvm::Value *explicitCount =
          llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                                 static_cast<uint64_t>(explicitVariadicCount));
      if (explicitVariadicCount == 0 && !callInst.getVariadicPack()) {
        args.push_back(explicitCount);
        args.push_back(llvm::ConstantPointerNull::get(elemPtrTy));
      } else if (explicitVariadicCount == 0) {
        args.push_back(forwardedCount);
        args.push_back(forwardedData);
      } else {
        llvm::Value *totalCount = explicitCount;
        if (callInst.getVariadicPack()) {
          totalCount = builder_.CreateAdd(explicitCount, forwardedCount,
                                          "varargs.total");
        }
        auto *buffer = builder_.CreateAlloca(elemTy, totalCount, "varargs.buf");
        for (size_t i = 0; i < explicitVariadicCount; ++i) {
          auto *dst = builder_.CreateInBoundsGEP(
              elemTy, buffer,
              llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                                     static_cast<uint64_t>(i)));
          builder_.CreateStore(args[fixedParamCount + i], dst);
        }
        if (callInst.getVariadicPack()) {
          auto *copyCondBB =
              llvm::BasicBlock::Create(ctx_, "varargs.copy.cond", currentFn_);
          auto *copyBodyBB =
              llvm::BasicBlock::Create(ctx_, "varargs.copy.body", currentFn_);
          auto *copyDoneBB =
              llvm::BasicBlock::Create(ctx_, "varargs.copy.done", currentFn_);
          auto *copyPreheaderBB = builder_.GetInsertBlock();
          builder_.CreateBr(copyCondBB);
          builder_.SetInsertPoint(copyCondBB);
          auto *indexPhi =
              builder_.CreatePHI(llvm::Type::getInt32Ty(ctx_), 2, "varargs.i");
          indexPhi->addIncoming(
              llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0),
              copyPreheaderBB);
          auto *cond =
              builder_.CreateICmpULT(indexPhi, forwardedCount, "varargs.cond");
          builder_.CreateCondBr(cond, copyBodyBB, copyDoneBB);
          builder_.SetInsertPoint(copyBodyBB);
          auto *src = builder_.CreateInBoundsGEP(elemTy, forwardedData,
                                                 indexPhi, "varargs.src");
          auto *srcVal = builder_.CreateLoad(elemTy, src, "varargs.load");
          auto *dstIndex = builder_.CreateAdd(indexPhi, explicitCount);
          auto *dst = builder_.CreateInBoundsGEP(elemTy, buffer, dstIndex,
                                                 "varargs.dst");
          builder_.CreateStore(srcVal, dst);
          auto *next = builder_.CreateAdd(
              indexPhi,
              llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 1));
          builder_.CreateBr(copyCondBB);
          indexPhi->addIncoming(next, copyBodyBB);
          builder_.SetInsertPoint(copyDoneBB);
        }
        args.erase(args.begin() + static_cast<std::ptrdiff_t>(fixedParamCount),
                   args.end());
        args.push_back(totalCount);
        args.push_back(buffer);
      }
    } else if (isCVariadic) {
      // Extra arguments are passed through unchanged after the fixed params.
    }
    llvm::Value *call = nullptr;
    if (zirIt != zirFunctionMap_.end() && zirIt->second->vtableSlot >= 0 &&
        !args.empty()) {
      auto receiverType = callInst.getArguments().front()->getType();
      std::shared_ptr<zir::ClassType> classType = nullptr;
      if (receiverType->getKind() == zir::TypeKind::Class) {
        classType = std::static_pointer_cast<zir::ClassType>(receiverType);
      } else if (receiverType->getKind() == zir::TypeKind::Pointer) {
        auto baseType = std::static_pointer_cast<zir::PointerType>(receiverType)
                            ->getBaseType();
        if (baseType->getKind() == zir::TypeKind::Class) {
          classType = std::static_pointer_cast<zir::ClassType>(baseType);
        }
      }
      if (classType) {
        auto *objectTy = structCache_.at(classType->getCodegenName() + ".obj");
        auto *selfPtr = builder_.CreateBitCast(
            args[0], llvm::PointerType::getUnqual(objectTy), "zir.method.self");
        auto *vtableAddr = builder_.CreateStructGEP(
            objectTy, selfPtr, kClassVTableIndex, "zir.method.vtable.addr");
        auto *i8PtrTy =
            llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
        auto *vtablePtrTy = llvm::PointerType::getUnqual(i8PtrTy);
        auto *vtablePtr =
            builder_.CreateLoad(vtablePtrTy, vtableAddr, "zir.method.vtable");
        auto *slotAddr = builder_.CreateInBoundsGEP(
            i8PtrTy, vtablePtr,
            llvm::ConstantInt::get(
                llvm::Type::getInt32Ty(ctx_),
                static_cast<uint64_t>(zirIt->second->vtableSlot)));
        auto *fnRaw =
            builder_.CreateLoad(i8PtrTy, slotAddr, "zir.method.fn.raw");
        auto *fnPtr = builder_.CreateBitCast(
            fnRaw, llvm::PointerType::getUnqual(calleeTy), "zir.method.fn");
        call = builder_.CreateCall(calleeTy, fnPtr, args);
      }
    }
    if (!call) {
      call = builder_.CreateCall(callee, args);
    }
    if (callInst.getResult()) {
      zirValueMap_[callInst.getResult().get()] = call;
      if (callInst.returnsRef()) {
        refReturnValues_.insert(callInst.getResult().get());
      }
      if (isClassType(callInst.getResult()->getType())) {
        zirOwnedClassValues_.insert(callInst.getResult().get());
      } else if (isOwnedStringType(callInst.getResult()->getType())) {
        zirOwnedStringValues_.insert(callInst.getResult().get());
      }
    }
    return;
  }
  case OpCode::GetElementPtr: {
    const auto &gepInst = static_cast<const GetElementPtrInst &>(inst);
    auto *ptr = lowerZIRValue(gepInst.getPointer());
    auto operandType = gepInst.getPointer()->getType();
    auto pointerType = std::dynamic_pointer_cast<zir::PointerType>(operandType);
    auto baseType = pointerType ? pointerType->getBaseType() : operandType;
    llvm::Value *gep = nullptr;
    if (baseType->getKind() == zir::TypeKind::Record) {
      auto recordType = std::static_pointer_cast<zir::RecordType>(baseType);
      auto *structTy = llvm::cast<llvm::StructType>(toLLVMType(*recordType));
      llvm::Value *structPtr = ptr;
      if (!pointerType) {
        auto *tmp = createEntryAlloca(
            currentFn_,
            static_cast<const Register &>(*gepInst.getResult()).getRawName() +
                ".addr",
            structTy);
        builder_.CreateStore(ptr, tmp);
        structPtr = tmp;
      }
      gep = builder_.CreateStructGEP(
          structTy, structPtr, static_cast<unsigned>(gepInst.getIndex()),
          static_cast<const Register &>(*gepInst.getResult()).getRawName());
    } else if (baseType->getKind() == zir::TypeKind::TaggedUnion) {
      auto taggedUnionType =
          std::static_pointer_cast<zir::TaggedUnionType>(baseType);
      auto *structTy =
          llvm::cast<llvm::StructType>(toLLVMType(*taggedUnionType));
      llvm::Value *structPtr = ptr;
      if (!pointerType) {
        auto *tmp = createEntryAlloca(
            currentFn_,
            static_cast<const Register &>(*gepInst.getResult()).getRawName() +
                ".addr",
            structTy);
        builder_.CreateStore(ptr, tmp);
        structPtr = tmp;
      }
      gep = builder_.CreateStructGEP(
          structTy, structPtr, static_cast<unsigned>(gepInst.getIndex()),
          static_cast<const Register &>(*gepInst.getResult()).getRawName());
    } else if (baseType->getKind() == zir::TypeKind::Class) {
      auto classType = std::static_pointer_cast<zir::ClassType>(baseType);
      auto *objectTy = structCache_.at(classType->getCodegenName() + ".obj");
      llvm::Value *objectPtr = ptr;
      gep = builder_.CreateStructGEP(
          objectTy, objectPtr,
          static_cast<unsigned>(gepInst.getIndex() + kClassFieldStartIndex),
          static_cast<const Register &>(*gepInst.getResult()).getRawName());
    } else {
      llvm::Value *basePtr = ptr;
      llvm::Value *index =
          gepInst.getIndexValue()
              ? lowerZIRRValue(gepInst.getIndexValue())
              : llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                                       gepInst.getIndex());
      if (baseType->getKind() == zir::TypeKind::Array) {
        auto *arrayTy = toLLVMType(*baseType);
        if (!pointerType) {
          auto *tmp = createEntryAlloca(
              currentFn_,
              static_cast<const Register &>(*gepInst.getResult()).getRawName() +
                  ".array.addr",
              arrayTy);
          builder_.CreateStore(ptr, tmp);
          basePtr = tmp;
        }
        auto *i32Ty = llvm::Type::getInt32Ty(ctx_);
        llvm::Value *indices[] = {llvm::ConstantInt::get(i32Ty, 0), index};
        gep = builder_.CreateInBoundsGEP(
            arrayTy, basePtr, indices,
            static_cast<const Register &>(*gepInst.getResult()).getRawName());
      } else {
        if (!pointerType) {
          throw std::runtime_error("ZIR getelementptr expects pointer operand");
        }
        auto *elemTy = toLLVMType(*baseType);
        gep = builder_.CreateInBoundsGEP(
            elemTy, ptr, index,
            static_cast<const Register &>(*gepInst.getResult()).getRawName());
      }
    }
    zirValueMap_[gepInst.getResult().get()] = gep;
    return;
  }
  case OpCode::Phi: {
    const auto &phiInst = static_cast<const PhiInst &>(inst);
    auto *phi = builder_.CreatePHI(
        toLLVMType(*phiInst.getResult()->getType()),
        phiInst.getIncoming().size(),
        static_cast<const Register &>(*phiInst.getResult()).getRawName());
    bool phiOwnsClassValue = isClassType(phiInst.getResult()->getType());
    for (const auto &incoming : phiInst.getIncoming()) {
      auto blockIt = zirBlockExitMap_.find(incoming.first);
      auto *incomingBlock = blockIt != zirBlockExitMap_.end()
                                ? blockIt->second
                                : zirBlockMap_.at(incoming.first);
      phi->addIncoming(lowerZIRValue(incoming.second), incomingBlock);
      if (phiOwnsClassValue &&
          zirOwnedClassValues_.count(incoming.second.get()) == 0) {
        phiOwnsClassValue = false;
      }
    }
    zirValueMap_[phiInst.getResult().get()] = phi;
    if (phiOwnsClassValue) {
      zirOwnedClassValues_.insert(phiInst.getResult().get());
    }
    return;
  }
  case OpCode::Cast: {
    const auto &castInst = static_cast<const CastInst &>(inst);
    auto *result =
        lowerZIRCast(lowerZIRRValue(castInst.getSource()),
                     castInst.getSource()->getType(), castInst.getTargetType());
    zirValueMap_[castInst.getResult().get()] = result;
    if (isClassType(castInst.getTargetType()) &&
        zirOwnedClassValues_.count(castInst.getSource().get()) > 0) {
      zirOwnedClassValues_.insert(castInst.getResult().get());
      zirOwnedClassValues_.erase(castInst.getSource().get());
    }
    return;
  }
  case OpCode::WeakLock: {
    const auto &weakLockInst = static_cast<const WeakLockInst &>(inst);
    auto *result = emitWeakLock(lowerZIRRValue(weakLockInst.getWeakValue()),
                                weakLockInst.getWeakValue()->getType());
    zirValueMap_[weakLockInst.getResult().get()] = result;
    if (isClassType(weakLockInst.getResult()->getType())) {
      zirOwnedClassValues_.insert(weakLockInst.getResult().get());
    }
    return;
  }
  case OpCode::WeakAlive: {
    const auto &weakAliveInst = static_cast<const WeakAliveInst &>(inst);
    auto *result = emitWeakAlive(lowerZIRRValue(weakAliveInst.getWeakValue()),
                                 weakAliveInst.getWeakValue()->getType());
    zirValueMap_[weakAliveInst.getResult().get()] = result;
    return;
  }
  case OpCode::Alloc: {
    const auto &allocInst = static_cast<const AllocInst &>(inst);
    auto allocType = allocInst.getAllocatedType();
    if (allocType->getKind() != zir::TypeKind::Class) {
      throw std::runtime_error("ZIR alloc currently supports only class types");
    }
    auto classType = std::static_pointer_cast<zir::ClassType>(allocType);
    auto *ptrTy = llvm::cast<llvm::PointerType>(toLLVMType(*classType));
    auto *objectTy = structCache_.at(classType->getCodegenName() + ".obj");
    auto *sizeOfObj = llvm::ConstantExpr::getSizeOf(objectTy);
    auto *sizeTy = llvm::Type::getInt64Ty(ctx_);
    llvm::Value *sizeValue = sizeOfObj;
    if (sizeValue->getType() != sizeTy) {
      sizeValue = builder_.CreateIntCast(sizeValue, sizeTy, /*isSigned=*/false);
    }
    auto mallocIt = functionMap_.find("malloc");
    if (mallocIt == functionMap_.end()) {
      auto *mallocTy = llvm::FunctionType::get(
          llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)), {sizeTy},
          false);
      auto *mallocFn = llvm::Function::Create(
          mallocTy, llvm::Function::ExternalLinkage, "malloc", *module_);
      mallocIt = functionMap_.emplace("malloc", mallocFn).first;
    }
    auto *rawPtr =
        builder_.CreateCall(mallocIt->second, {sizeValue}, "class.alloc");
    auto *typedPtr = builder_.CreateBitCast(rawPtr, ptrTy, "class.obj");
    auto *refCountAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 0, "refcount.addr");
    builder_.CreateStore(
        llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_), 1), refCountAddr);
    auto *weakCountAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 1, "weakcount.addr");
    builder_.CreateStore(
        llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_), 0), weakCountAddr);
    auto *aliveAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 2, "alive.addr");
    builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt8Ty(ctx_), 1),
                         aliveAddr);
    auto *gcMarkAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 3, "gcmark.addr");
    builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt8Ty(ctx_), 0),
                         gcMarkAddr);
    auto *releaseFnAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 4, "release.fn.addr");
    auto *releaseFnPtr = builder_.CreateBitCast(
        classReleaseFns_.at(classType->getName()),
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
    builder_.CreateStore(releaseFnPtr, releaseFnAddr);
    auto *destroyFnAddr =
        builder_.CreateStructGEP(objectTy, typedPtr, 5, "destroy.fn.addr");
    auto *destroyFnPtr = builder_.CreateBitCast(
        classDestroyFns_.at(classType->getName()),
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
    builder_.CreateStore(destroyFnPtr, destroyFnAddr);
    auto *metadataAddr = builder_.CreateStructGEP(
        objectTy, typedPtr, kClassMetadataIndex, "metadata.addr");
    auto *metadataPtr = builder_.CreateBitCast(
        classMetadataGlobals_.at(classType->getName()),
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
    builder_.CreateStore(metadataPtr, metadataAddr);
    auto *vtableAddr = builder_.CreateStructGEP(
        objectTy, typedPtr, kClassVTableIndex, "vtable.addr");
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *vtablePtrTy = llvm::PointerType::getUnqual(i8PtrTy);
    auto *vtableGlobal = classVTables_.at(classType->getName());
    auto *zero = llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0);
    llvm::Constant *vtableIndices[] = {zero, zero};
    auto *vtablePtr = llvm::ConstantExpr::getInBoundsGetElementPtr(
        vtableGlobal->getValueType(), vtableGlobal, vtableIndices);
    builder_.CreateStore(llvm::ConstantExpr::getBitCast(vtablePtr, vtablePtrTy),
                         vtableAddr);
    for (size_t i = 0; i < classType->getFields().size(); ++i) {
      auto *fieldAddr = builder_.CreateStructGEP(
          objectTy, typedPtr, static_cast<unsigned>(i + kClassFieldStartIndex));
      builder_.CreateStore(llvm::Constant::getNullValue(
                               toLLVMType(*classType->getFields()[i].type)),
                           fieldAddr);
    }
    zirValueMap_[allocInst.getResult().get()] = typedPtr;
    zirOwnedClassValues_.insert(allocInst.getResult().get());
    return;
  }
  case OpCode::InlineAsm: {
    const auto &asmInst = static_cast<const InlineAsmInst &>(inst);
    std::vector<std::string> outConstraints, inConstraints;
    std::vector<llvm::Value *> outAddrs, inValues;
    std::vector<llvm::Type *> outValueTypes;
    for (const auto &out : asmInst.getOutputs()) {
      outConstraints.push_back(out.constraint);
      outAddrs.push_back(lowerZIRValue(out.value));
      outValueTypes.push_back(toLLVMType(*out.valueType));
    }
    for (const auto &in : asmInst.getInputs()) {
      inConstraints.push_back(in.constraint);
      inValues.push_back(lowerZIRRValue(in.value));
    }
    buildInlineAsmCall(asmInst.getAssembly(), outConstraints, outAddrs,
                       outValueTypes, inConstraints, inValues,
                       asmInst.getClobbers());
    return;
  }
  case OpCode::Retain:
  case OpCode::Release:
    throw std::runtime_error("ZIR opcode not lowered yet in LLVM backend");
  }
}
References zir::Add, zir::Alloc, zir::Alloca, zir::Array, zir::AShr, zir::BitAnd, zir::BitOr, zir::BitXor, zir::Bool, zir::Br, builder_, buildInlineAsmCall(), zir::Call, zir::Cast, zir::Char, zir::Class, classDestroyFns_, classMetadataGlobals_, classReleaseFns_, classVTables_, zir::Cmp, zir::CondBr, createEntryAlloca(), ctx_, currentFn_, currentZIRFunction_, declareZIRFunction(), emitReleaseIfNeeded(), emitReleaseWeakIfNeeded(), emitRetainIfNeeded(), emitStoreWithArc(), emitStoreWithStringArc(), emitStringConcat(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), emitWeakAlive(), emitWeakLock(), functionMap_, zir::AllocInst::getAllocatedType(), zir::GetElementPtr, zir::Instruction::getOpCode(), zir::Register::getRawName(), zir::InlineAsm, isClassType(), isOwnedStringType(), isWeakClassType(), codegen::kClassFieldStartIndex, codegen::kClassMetadataIndex, codegen::kClassVTableIndex, len(), zir::Load, lowerZIRCast(), lowerZIRRValue(), lowerZIRValue(), zir::LShr, module_, zir::Mul, zir::Phi, zir::Pointer, zir::Record, refReturnValues_, zir::Release, zir::Ret, zir::Retain, zir::SDiv, zir::Shl, zir::SRem, zir::Store, structCache_, zir::Sub, zir::TaggedUnion, toLLVMType(), zir::UDiv, zir::URem, zir::WeakAlive, zir::WeakLock, zirBlockExitMap_, zirBlockMap_, zirClassParamAllocas_, zirFunctionClassLocals_, zirFunctionMap_, zirFunctionStringLocals_, zirOwnedClassValues_, zirOwnedStringValues_, zirParamSpillIndex_, zirPendingClassParamInitAllocas_, and zirValueMap_.
Referenced by emitZIRFunction().
ensureArcSupport()
void codegen::LLVMCodeGen::ensureArcSupport (sema::BoundRootNode & root) private
Definition at line 168 of file llvm_codegen_arc.cpp.
{
  arcEmitter_->ensureArcSupport(root);
}
References arcEmitter_.
Referenced by generate().
ensureClassArcSupport()
void codegen::LLVMCodeGen::ensureClassArcSupport (const std::shared_ptr< zir::ClassType > & classType) private
Definition at line 163 of file llvm_codegen_arc.cpp.
{
  arcEmitter_->ensureClassArcSupport(classType);
}
References arcEmitter_.
Referenced by generate(), and visit().
expressionProducesOwnedClass()
bool codegen::LLVMCodeGen::expressionProducesOwnedClass (const sema::BoundExpression * expr) const private
Definition at line 27 of file llvm_codegen_arc.cpp.
{
  return arcEmitter_->expressionProducesOwnedClass(expr);
}
References arcEmitter_.
Referenced by visit(), visit(), visit(), visit(), visit(), and visit().
expressionProducesOwnedString()
bool codegen::LLVMCodeGen::expressionProducesOwnedString (const sema::BoundExpression * expr) const private
Definition at line 32 of file llvm_codegen_arc.cpp.
{
  if (!expr || !isOwnedStringType(expr->type)) {
    return false;
  }
  return dynamic_cast<const sema::BoundLiteral *>(expr) == nullptr;
}
References isOwnedStringType(), and sema::BoundExpression::type.
Referenced by visit(), and visit().
finalizeClassStruct()
void codegen::LLVMCodeGen::finalizeClassStruct (const zir::ClassType & ct) private
Definition at line 201 of file llvm_codegen.cpp.
{
  auto *objectTy = getOrCreateClassStruct(ct);
  if (!objectTy->isOpaque()) {
    return;
  }
  auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
  std::vector<llvm::Type *> fieldTypes = {
      llvm::Type::getInt64Ty(ctx_),
      llvm::Type::getInt64Ty(ctx_),
      llvm::Type::getInt8Ty(ctx_),
      llvm::Type::getInt8Ty(ctx_),
      i8PtrTy,
      i8PtrTy,
      i8PtrTy,
      llvm::PointerType::getUnqual(i8PtrTy)};
  for (const auto &f : ct.getFields()) {
    fieldTypes.push_back(toLLVMAggregateFieldType(f.type));
  }
  objectTy->setBody(fieldTypes);
}
References ctx_, zir::RecordType::getFields(), getOrCreateClassStruct(), and toLLVMAggregateFieldType().
Referenced by generate().
generate() [1/2]
void codegen::LLVMCodeGen::generate (const zir::Module & module)
Definition at line 27 of file llvm_codegen_zir.cpp.
{
  initializeModule();
  functionMap_.clear();
  zirFunctionMap_.clear();
  globalValues_.clear();
  zirValueMap_.clear();
  zirBlockMap_.clear();
  for (const auto &type : module.getTypes()) {
    if (type->getKind() == zir::TypeKind::Record ||
        type->getKind() == zir::TypeKind::TaggedUnion ||
        type->getKind() == zir::TypeKind::Class) {
      toLLVMType(*type);
    }
  }
  for (const auto &global : module.getExternalGlobals()) {
    auto *gv = new llvm::GlobalVariable(
        *module_, toLLVMType(*global->getValueType()), false,
        llvm::GlobalVariable::ExternalLinkage, nullptr, global->getLinkName());
    globalValues_[global->getLinkName()] = gv;
  }
  for (const auto &global : module.getGlobals()) {
    auto *valueTy = toLLVMType(*global->getValueType());
    auto *gv = new llvm::GlobalVariable(*module_, valueTy, global->isConstant(),
                                        llvm::GlobalVariable::ExternalLinkage,
                                        llvm::Constant::getNullValue(valueTy),
                                        global->getLinkName());
    globalValues_[global->getLinkName()] = gv;
  }
  for (const auto &global : module.getGlobals()) {
    llvm::Constant *initializer = nullptr;
    if (global->getInitializer()) {
      if (global->getInitializer()->getKind() == zir::ValueKind::Constant) {
        initializer = lowerZIRConstant(
            static_cast<const zir::Constant &>(*global->getInitializer()));
      } else if (global->getInitializer()->getKind() ==
                 zir::ValueKind::AggregateConstant) {
        initializer = lowerZIRAggregateConstant(
            static_cast<const zir::AggregateConstant &>(
                *global->getInitializer()));
      } else if (global->getInitializer()->getKind() ==
                 zir::ValueKind::ArrayConstant) {
        initializer = lowerZIRArrayConstant(
            static_cast<const zir::ArrayConstant &>(*global->getInitializer()));
      } else if (global->getInitializer()->getKind() ==
                 zir::ValueKind::GlobalAddress) {
        const auto &address =
            static_cast<const zir::GlobalAddress &>(*global->getInitializer());
        auto target = globalValues_.find(address.getLinkName());
        if (target != globalValues_.end()) {
          initializer = target->second;
          if (address.getArrayIndex()) {
            auto *zero =
                llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_), 0);
            auto *index = llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_),
                                                 *address.getArrayIndex());
            llvm::Constant *indices[] = {zero, index};
            initializer = llvm::ConstantExpr::getInBoundsGetElementPtr(
                target->second->getValueType(), target->second, indices);
          }
        }
      }
    }
    if (!initializer) {
      initializer =
          llvm::Constant::getNullValue(toLLVMType(*global->getValueType()));
    }
    globalValues_.at(global->getLinkName())->setInitializer(initializer);
  }
  for (const auto &func : module.getExternalFunctions()) {
    zirFunctionMap_[func->name] = func.get();
    declareZIRFunction(*func, true);
  }
  for (const auto &func : module.getFunctions()) {
    zirFunctionMap_[func->name] = func.get();
    declareZIRFunction(*func, false);
    auto *llvmFn = functionMap_.at(func->name);
    if (func->isDestructor && !func->ownerTypeName.empty()) {
      classDestructorFns_[func->ownerTypeName] = llvmFn;
    }
    if (func->vtableSlot >= 0 && !func->ownerTypeName.empty()) {
      classVirtualMethodFns_[func->ownerTypeName][func->vtableSlot] = llvmFn;
    }
  }
  for (const auto &type : module.getTypes()) {
    if (type->getKind() == zir::TypeKind::Class) {
      finalizeClassStruct(static_cast<const zir::ClassType &>(*type));
    }
  }
  computeCyclicClasses(module);
  for (const auto &type : module.getTypes()) {
    if (type->getKind() == zir::TypeKind::Class) {
      ensureClassArcSupport(std::static_pointer_cast<zir::ClassType>(type));
    }
  }
  for (const auto &func : module.getFunctions()) {
    emitZIRFunction(*func);
  }
}
References zir::AggregateConstant, zir::ArrayConstant, zir::Class, classDestructorFns_, classVirtualMethodFns_, computeCyclicClasses(), zir::Constant, ctx_, declareZIRFunction(), emitZIRFunction(), ensureClassArcSupport(), finalizeClassStruct(), functionMap_, zir::Module::getExternalFunctions(), zir::Module::getExternalGlobals(), zir::Module::getFunctions(), zir::Module::getGlobals(), zir::Module::getTypes(), zir::GlobalAddress, globalValues_, initializeModule(), lowerZIRAggregateConstant(), lowerZIRArrayConstant(), lowerZIRConstant(), module_, zir::Record, zir::TaggedUnion, toLLVMType(), zirBlockMap_, zirFunctionMap_, and zirValueMap_.
generate() [2/2]
void codegen::LLVMCodeGen::generate (sema::BoundRootNode & root)
Definition at line 183 of file llvm_codegen.cpp.
{
  initializeModule();
  ensureArcSupport(root);
  root.accept(*this);
}
References sema::BoundRootNode::accept(), ensureArcSupport(), and initializeModule().
Referenced by zap::compileAssemblyFromZIR(), zap::compileObjectFromZIR(), and zap::compileSourceLLVMFromZIR().
getOrCreateClassStruct()
llvm::StructType * codegen::LLVMCodeGen::getOrCreateClassStruct (const zir::ClassType & ct) private
Definition at line 190 of file llvm_codegen.cpp.
{
  std::string objectName = ct.getCodegenName() + ".obj";
  auto it = structCache_.find(objectName);
  if (it != structCache_.end()) {
    return it->second;
  }
  auto *objectTy = llvm::StructType::create(ctx_, objectName);
  structCache_[objectName] = objectTy;
  return objectTy;
}
References ctx_, zir::RecordType::getCodegenName(), and structCache_.
Referenced by finalizeClassStruct(), and toLLVMType().
getOrCreateGlobalString()
llvm::Constant * codegen::LLVMCodeGen::getOrCreateGlobalString (const std::string & str, std::string & globalName) private
Definition at line 34 of file llvm_codegen_constants.cpp.
{
  globalName = ".str." + std::to_string(nextStringId_++);
  auto *arrayTy = llvm::ArrayType::get(llvm::Type::getInt8Ty(ctx_),
                                       static_cast<unsigned>(str.size() + 1));
  auto *constArray = llvm::ConstantDataArray::getString(ctx_, str, true);
  auto *gv = new llvm::GlobalVariable(*module_, arrayTy, /*isConstant=*/true,
                                      llvm::GlobalValue::PrivateLinkage,
                                      constArray, globalName);
  auto *zero32 = llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0);
  llvm::Constant *indices[] = {zero32, zero32};
  auto *gep =
      llvm::ConstantExpr::getInBoundsGetElementPtr(arrayTy, gv, indices);
  auto *ptrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
  return llvm::ConstantExpr::getBitCast(gep, ptrTy);
}
References ctx_, module_, and nextStringId_.
Referenced by lowerZIRConstant(), and visit().
initializeModule()
void codegen::LLVMCodeGen::initializeModule () private
Definition at line 162 of file llvm_codegen.cpp.
{
  module_ = std::make_unique<llvm::Module>("zap_module", ctx_);
  llvm::Triple triple(targetTriple_);
  module_->setTargetTriple(triple);
  std::string error;
  const auto *target = llvm::TargetRegistry::lookupTarget(triple, error);
  if (!target) {
    throw std::runtime_error("target lookup failed for '" + targetTriple_ +
                             "': " + error);
  }
  llvm::TargetOptions opts;
  std::unique_ptr<llvm::TargetMachine> tm(target->createTargetMachine(
      triple, "generic", "", opts, llvm::Reloc::PIC_));
  if (!tm) {
    throw std::runtime_error("failed to create target machine for '" +
                             targetTriple_ + "'");
  }
  module_->setDataLayout(tm->createDataLayout());
}
References ctx_, module_, and targetTriple_.
Referenced by generate(), and generate().
isClassType()
bool codegen::LLVMCodeGen::isClassType (const std::shared_ptr< zir::Type > & type) const private
Definition at line 13 of file llvm_codegen_arc.cpp.
{
  return arcEmitter_->isClassType(type);
}
References arcEmitter_.
Referenced by emitZIRInstruction(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
isOwnedStringType()
bool codegen::LLVMCodeGen::isOwnedStringType (const std::shared_ptr< zir::Type > & type) const private
Definition at line 22 of file llvm_codegen_arc.cpp.
{
  return zap::text::isStringType(type) && !zap::text::isStringViewType(type);
}
References zap::text::isStringType(), and zap::text::isStringViewType().
Referenced by emitReleaseIfNeeded(), emitRetainIfNeeded(), emitStoreWithArc(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), emitZIRInstruction(), expressionProducesOwnedString(), visit(), visit(), and visit().
isWeakClassType()
bool codegen::LLVMCodeGen::isWeakClassType (const std::shared_ptr< zir::Type > & type) const private
Definition at line 17 of file llvm_codegen_arc.cpp.
{
  return arcEmitter_->isWeakClassType(type);
}
References arcEmitter_.
Referenced by emitZIRInstruction(), visit(), visit(), and visit().
lowerZIRAggregateConstant()
llvm::Constant * codegen::LLVMCodeGen::lowerZIRAggregateConstant (const zir::AggregateConstant & constant) private
Definition at line 141 of file llvm_codegen_constants.cpp.
{
  auto *ty = toLLVMType(*constant.getType());
  auto *structTy = llvm::dyn_cast<llvm::StructType>(ty);
  if (!structTy) {
    return llvm::Constant::getNullValue(ty);
  }
  const auto *recordTy =
      static_cast<const zir::RecordType *>(constant.getType().get());
  const auto &recordFields = recordTy->getFields();
  std::vector<llvm::Constant *> elems(recordFields.size(), nullptr);
  for (const auto &fieldInit : constant.getFields()) {
    int fieldIndex = -1;
    for (size_t i = 0; i < recordFields.size(); ++i) {
      if (recordFields[i].name == fieldInit.name) {
        fieldIndex = static_cast<int>(i);
        break;
      }
    }
    if (fieldIndex < 0 || fieldInit.value == nullptr) {
      continue;
    }
    llvm::Constant *fieldConst = nullptr;
    if (fieldInit.value->getKind() == zir::ValueKind::Constant) {
      fieldConst = lowerZIRConstant(
          static_cast<const zir::Constant &>(*fieldInit.value));
    } else if (fieldInit.value->getKind() ==
               zir::ValueKind::AggregateConstant) {
      fieldConst = lowerZIRAggregateConstant(
          static_cast<const zir::AggregateConstant &>(*fieldInit.value));
    }
    if (fieldConst) {
      auto *expectedFieldTy = toLLVMAggregateFieldType(
          recordFields[static_cast<size_t>(fieldIndex)].type);
      if (fieldConst->getType() != expectedFieldTy) {
        auto sourceFieldType = fieldInit.value->getType();
        auto targetFieldType =
            recordFields[static_cast<size_t>(fieldIndex)].type;
        if (isStringType(sourceFieldType) && isStringType(targetFieldType)) {
          if (auto *srcStruct =
                  llvm::dyn_cast<llvm::ConstantStruct>(fieldConst)) {
            auto *ptr = srcStruct->getAggregateElement((unsigned)0);
            auto *len = srcStruct->getAggregateElement((unsigned)1);
            auto *dstStructTy =
                llvm::dyn_cast<llvm::StructType>(expectedFieldTy);
            if (ptr && len && dstStructTy) {
              fieldConst = llvm::ConstantStruct::get(dstStructTy, {ptr, len});
            }
          }
        } else if (fieldConst->getType()->isIntegerTy() &&
                   expectedFieldTy->isIntegerTy()) {
          unsigned srcBits = fieldConst->getType()->getIntegerBitWidth();
          unsigned dstBits = expectedFieldTy->getIntegerBitWidth();
          if (dstBits < srcBits) {
            fieldConst = llvm::dyn_cast<llvm::Constant>(
                llvm::ConstantExpr::getTrunc(fieldConst, expectedFieldTy));
          } else if (dstBits > srcBits) {
            auto targetFieldType =
                recordFields[static_cast<size_t>(fieldIndex)].type;
            if (targetFieldType->isUnsigned()) {
              fieldConst =
                  llvm::dyn_cast<llvm::Constant>(llvm::ConstantExpr::getCast(
                      llvm::Instruction::ZExt, fieldConst, expectedFieldTy));
            } else {
              fieldConst =
                  llvm::dyn_cast<llvm::Constant>(llvm::ConstantExpr::getCast(
                      llvm::Instruction::SExt, fieldConst, expectedFieldTy));
            }
          }
        } else {
          fieldConst = llvm::dyn_cast<llvm::Constant>(
              llvm::ConstantExpr::getBitCast(fieldConst, expectedFieldTy));
        }
      }
      elems[static_cast<size_t>(fieldIndex)] = fieldConst;
    }
  }
  for (size_t i = 0; i < elems.size(); ++i) {
    if (!elems[i]) {
      elems[i] = llvm::Constant::getNullValue(
          toLLVMAggregateFieldType(recordFields[i].type));
    }
  }
  return llvm::ConstantStruct::get(structTy, elems);
}
References zir::AggregateConstant, zir::Constant, zir::AggregateConstant::getFields(), zir::RecordType::getFields(), zir::AggregateConstant::getType(), len(), lowerZIRAggregateConstant(), lowerZIRConstant(), toLLVMAggregateFieldType(), and toLLVMType().
Referenced by generate(), lowerZIRAggregateConstant(), lowerZIRArrayConstant(), and lowerZIRValue().
lowerZIRArrayConstant()
llvm::Constant * codegen::LLVMCodeGen::lowerZIRArrayConstant (const zir::ArrayConstant & constant) private
Definition at line 236 of file llvm_codegen_constants.cpp.
{
  auto *ty = toLLVMType(*constant.getType());
  auto *arrayTy = llvm::dyn_cast<llvm::ArrayType>(ty);
  if (!arrayTy) {
    return llvm::Constant::getNullValue(ty);
  }
  std::vector<llvm::Constant *> elems;
  elems.reserve(arrayTy->getNumElements());
  for (const auto &element : constant.getElements()) {
    llvm::Constant *elementConst = nullptr;
    if (element->getKind() == zir::ValueKind::Constant) {
      elementConst =
          lowerZIRConstant(static_cast<const zir::Constant &>(*element));
    } else if (element->getKind() == zir::ValueKind::AggregateConstant) {
      elementConst = lowerZIRAggregateConstant(
          static_cast<const zir::AggregateConstant &>(*element));
    } else if (element->getKind() == zir::ValueKind::ArrayConstant) {
      elementConst = lowerZIRArrayConstant(
          static_cast<const zir::ArrayConstant &>(*element));
    }
    if (elementConst) {
      auto *expectedTy = arrayTy->getElementType();
      if (elementConst->getType() != expectedTy) {
        if (elementConst->getType()->isIntegerTy() &&
            expectedTy->isIntegerTy()) {
          auto srcBits = elementConst->getType()->getIntegerBitWidth();
          auto dstBits = expectedTy->getIntegerBitWidth();
          if (dstBits < srcBits) {
            elementConst = llvm::cast<llvm::Constant>(
                llvm::ConstantExpr::getTrunc(elementConst, expectedTy));
          } else if (dstBits > srcBits) {
            elementConst =
                llvm::cast<llvm::Constant>(llvm::ConstantExpr::getCast(
                    llvm::Instruction::SExt, elementConst, expectedTy));
          }
        } else {
          elementConst = llvm::cast<llvm::Constant>(
              llvm::ConstantExpr::getBitCast(elementConst, expectedTy));
        }
      }
    }
    elems.push_back(
        elementConst ? elementConst
                     : llvm::Constant::getNullValue(arrayTy->getElementType()));
  }
  while (elems.size() < arrayTy->getNumElements()) {
    elems.push_back(llvm::Constant::getNullValue(arrayTy->getElementType()));
  }
  return llvm::ConstantArray::get(arrayTy, elems);
}
References zir::AggregateConstant, zir::ArrayConstant, zir::Constant, zir::ArrayConstant::getElements(), zir::ArrayConstant::getType(), lowerZIRAggregateConstant(), lowerZIRArrayConstant(), lowerZIRConstant(), and toLLVMType().
Referenced by generate(), lowerZIRArrayConstant(), and lowerZIRValue().
lowerZIRCast()
llvm::Value * codegen::LLVMCodeGen::lowerZIRCast (llvm::Value * src, const std::shared_ptr< zir::Type > & sourceType, const std::shared_ptr< zir::Type > & targetType) private
Definition at line 216 of file llvm_codegen_zir.cpp.
{
  auto *srcTy = src->getType();
  auto *destTy = toLLVMType(*targetType);
  if (isStringType(sourceType) && isStringType(targetType)) {
    if (srcTy == destTy) {
      return src;
    }
    auto *ptr = builder_.CreateExtractValue(src, {0}, "zir.cast.str.ptr");
    auto *len = builder_.CreateExtractValue(src, {1}, "zir.cast.str.len");
    llvm::Value *result = llvm::UndefValue::get(destTy);
    result = builder_.CreateInsertValue(result, ptr, {0}, "zir.cast.str.ptr.i");
    result = builder_.CreateInsertValue(result, len, {1}, "zir.cast.str.len.i");
    return result;
  }
  if (isStringType(sourceType) && destTy->isPointerTy()) {
    auto *ptr = builder_.CreateExtractValue(src, {0}, "zir.cast.str.ptr");
    return ptr->getType() == destTy ? ptr : builder_.CreateBitCast(ptr, destTy);
  }
  if (srcTy->isPointerTy() && isStringType(targetType)) {
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *cstrPtr =
        srcTy == i8PtrTy ? src : builder_.CreateBitCast(src, i8PtrTy);
    std::vector<llvm::Type *> fromCStrParams = {i8PtrTy};
    auto *fromCStrTy = llvm::FunctionType::get(destTy, fromCStrParams, false);
    auto fromCStrCallee =
        module_->getOrInsertFunction("zap_string_from_cstr", fromCStrTy);
    return builder_.CreateCall(fromCStrTy, fromCStrCallee.getCallee(),
                               {cstrPtr}, "zir.cast.cstr.to.string");
  }
  if (srcTy == destTy) {
    return src;
  }
  if (srcTy->isPointerTy() && destTy->isPointerTy()) {
    return builder_.CreateBitCast(src, destTy);
  }
  if (srcTy->isPointerTy() && destTy->isIntegerTy()) {
    return builder_.CreatePtrToInt(src, destTy);
  }
  if (srcTy->isIntegerTy() && destTy->isPointerTy()) {
    return builder_.CreateIntToPtr(src, destTy);
  }
  if (srcTy->isIntegerTy() && destTy->isIntegerTy()) {
    unsigned srcBits = srcTy->getIntegerBitWidth();
    unsigned destBits = destTy->getIntegerBitWidth();
    if (destBits > srcBits) {
      bool shouldZeroExtend = sourceType->isUnsigned() ||
                              sourceType->getKind() == zir::TypeKind::Bool ||
                              sourceType->getKind() == zir::TypeKind::Char;
      return shouldZeroExtend ? builder_.CreateZExt(src, destTy)
                              : builder_.CreateSExt(src, destTy);
    }
    if (destBits < srcBits) {
      return builder_.CreateTrunc(src, destTy);
    }
    return src;
  }
  if (srcTy->isIntegerTy() && destTy->isFloatingPointTy()) {
    return sourceType->isUnsigned() ? builder_.CreateUIToFP(src, destTy)
                                    : builder_.CreateSIToFP(src, destTy);
  }
  if (srcTy->isFloatingPointTy() && destTy->isIntegerTy()) {
    return targetType->isUnsigned() ? builder_.CreateFPToUI(src, destTy)
                                    : builder_.CreateFPToSI(src, destTy);
  }
  if (srcTy->isFloatingPointTy() && destTy->isFloatingPointTy()) {
    if (srcTy->getPrimitiveSizeInBits() < destTy->getPrimitiveSizeInBits()) {
      return builder_.CreateFPExt(src, destTy);
    }
    if (srcTy->getPrimitiveSizeInBits() > destTy->getPrimitiveSizeInBits()) {
      return builder_.CreateFPTrunc(src, destTy);
    }
    return src;
  }
  return builder_.CreateBitCast(src, destTy);
}
References zir::Bool, builder_, zir::Char, ctx_, len(), module_, and toLLVMType().
Referenced by emitZIRInstruction().
lowerZIRConstant()
llvm::Constant * codegen::LLVMCodeGen::lowerZIRConstant (const zir::Constant & constant) private
Definition at line 54 of file llvm_codegen_constants.cpp.
{
  if (constant.getType()->getKind() == zir::TypeKind::Record) {
    const auto &rt = static_cast<const zir::RecordType &>(*constant.getType());
    if (isStringRecordName(rt.getName())) {
      std::string gname;
      auto *ptrConst = getOrCreateGlobalString(constant.getLiteral(), gname);
      auto *lenConst = llvm::ConstantInt::get(
          llvm::Type::getInt64Ty(ctx_),
          static_cast<uint64_t>(constant.getLiteral().size()));
      auto *structTy =
          static_cast<llvm::StructType *>(toLLVMType(*constant.getType()));
      return llvm::ConstantStruct::get(structTy, {ptrConst, lenConst});
    }
  }
  auto *ty = toLLVMType(*constant.getType());
  const auto &literal = constant.getLiteral();
  if (ty->isIntegerTy(1)) {
    return llvm::ConstantInt::get(ty, literal == "true" ? 1 : 0);
  }
  if (ty->isIntegerTy(8) &&
      constant.getType()->getKind() == zir::TypeKind::Char) {
    if (literal == "null") {
      return llvm::ConstantInt::get(ty, 0, false);
    }
    int64_t code = 0;
    if (!literal.empty()) {
      if (literal.size() >= 2 && literal[0] == '\\') {
        switch (literal[1]) {
        case 'n':
          code = '\n';
          break;
        case 't':
          code = '\t';
          break;
        case 'r':
          code = '\r';
          break;
        case '\\':
          code = '\\';
          break;
        case '\'':
          code = '\'';
          break;
        case '0':
          code = '\0';
          break;
        default:
          code = static_cast<unsigned char>(literal[1]);
          break;
        }
      } else {
        code = static_cast<unsigned char>(literal[0]);
      }
    }
    return llvm::ConstantInt::get(ty, code, false);
  }
  if (ty->isIntegerTy()) {
    if (literal == "null") {
      return llvm::ConstantInt::get(ty, 0, false);
    }
    uint64_t unsignedValue = parseIntegerLiteral(literal);
    if (constant.getType()->isUnsigned()) {
      return llvm::ConstantInt::get(ty, unsignedValue, false);
    }
    return llvm::ConstantInt::get(ty, unsignedValue, true);
  }
  if (ty->isFloatTy()) {
    return llvm::ConstantFP::get(ty, std::stof(literal));
  }
  if (ty->isDoubleTy()) {
    return llvm::ConstantFP::get(ty, std::stod(literal));
  }
  if (ty->isPointerTy()) {
    if (literal == "null") {
      return llvm::ConstantPointerNull::get(llvm::cast<llvm::PointerType>(ty));
    }
    auto *address =
        llvm::ConstantInt::get(module_->getDataLayout().getIntPtrType(ctx_),
                               parseIntegerLiteral(literal), false);
    return llvm::ConstantExpr::getIntToPtr(address, ty);
  }
  return llvm::Constant::getNullValue(ty);
}
References zir::Char, ctx_, zir::Constant::getLiteral(), getOrCreateGlobalString(), zir::Constant::getType(), module_, zir::Record, and toLLVMType().
Referenced by generate(), lowerZIRAggregateConstant(), lowerZIRArrayConstant(), and lowerZIRValue().
lowerZIRRValue()
llvm::Value * codegen::LLVMCodeGen::lowerZIRRValue (const std::shared_ptr< zir::Value > & value) private
Definition at line 192 of file llvm_codegen_zir.cpp.
{
  auto *raw = lowerZIRValue(value);
  if (!value) {
    return raw;
  }
  auto *expectedTy = toLLVMType(*value->getType());
  if (raw->getType() == expectedTy) {
    return raw;
  }
  auto *ptrTy = llvm::dyn_cast<llvm::PointerType>(raw->getType());
  if (!ptrTy) {
    return raw;
  }
  if (value->getType()->getKind() == zir::TypeKind::Pointer ||
      value->getType()->getKind() == zir::TypeKind::Class ||
      value->getType()->getKind() == zir::TypeKind::NullPtr) {
    return raw;
  }
  return builder_.CreateLoad(expectedTy, raw, "zir.rvalue");
}
References builder_, zir::Class, lowerZIRValue(), zir::NullPtr, zir::Pointer, and toLLVMType().
Referenced by emitZIRInstruction().
lowerZIRValue()
llvm::Value * codegen::LLVMCodeGen::lowerZIRValue (const std::shared_ptr< zir::Value > & value) private
Definition at line 154 of file llvm_codegen_zir.cpp.
{
  if (!value) {
    return nullptr;
  }
  if (value->getKind() == zir::ValueKind::Constant) {
    return lowerZIRConstant(static_cast<const zir::Constant &>(*value));
  }
  if (value->getKind() == zir::ValueKind::AggregateConstant) {
    return lowerZIRAggregateConstant(
        static_cast<const zir::AggregateConstant &>(*value));
  }
  if (value->getKind() == zir::ValueKind::ArrayConstant) {
    return lowerZIRArrayConstant(
        static_cast<const zir::ArrayConstant &>(*value));
  }
  if (value->getKind() == zir::ValueKind::Global) {
    const auto &g = static_cast<const zir::Global &>(*value);
    if (g.getValueType()->getKind() == zir::TypeKind::FunctionPointer) {
      auto it = functionMap_.find(g.getLinkName());
      if (it != functionMap_.end())
        return it->second;
      auto zirIt = zirFunctionMap_.find(g.getLinkName());
      if (zirIt != zirFunctionMap_.end()) {
        declareZIRFunction(*zirIt->second, false);
        return functionMap_.at(g.getLinkName());
      }
    }
    return globalValues_.at(g.getLinkName());
  }
  auto it = zirValueMap_.find(value.get());
  if (it == zirValueMap_.end()) {
    throw std::runtime_error("unmapped ZIR value: " + value->getName());
  }
  return it->second;
}
References zir::AggregateConstant, zir::ArrayConstant, zir::Constant, declareZIRFunction(), functionMap_, zir::FunctionPointer, zir::Global, globalValues_, lowerZIRAggregateConstant(), lowerZIRArrayConstant(), lowerZIRConstant(), zirFunctionMap_, and zirValueMap_.
Referenced by emitZIRInstruction(), and lowerZIRRValue().
printIR()
void codegen::LLVMCodeGen::printIR (llvm::raw_ostream & os) const
Definition at line 293 of file llvm_codegen.cpp.
{
  if (module_)
    module_->print(os, nullptr);
}
References module_.
Referenced by zap::compileSourceLLVMFromZIR().
toLLVMAggregateFieldType()
llvm::Type * codegen::LLVMCodeGen::toLLVMAggregateFieldType (const std::shared_ptr< zir::Type > & type) private
Definition at line 509 of file llvm_codegen.cpp.
{
  if (type && type->getKind() == zir::TypeKind::Void) {
    return llvm::Type::getInt8Ty(ctx_);
  }
  return type ? toLLVMType(*type) : llvm::Type::getInt8Ty(ctx_);
}
References ctx_, toLLVMType(), and zir::Void.
Referenced by finalizeClassStruct(), lowerZIRAggregateConstant(), and toLLVMType().
toLLVMType()
llvm::Type * codegen::LLVMCodeGen::toLLVMType (const zir::Type & ty) private
Definition at line 387 of file llvm_codegen.cpp.
{
  switch (ty.getKind()) {
  case zir::TypeKind::Void:
    return llvm::Type::getVoidTy(ctx_);
  case zir::TypeKind::Bool:
    return llvm::Type::getInt1Ty(ctx_);
  case zir::TypeKind::Char:
    return llvm::Type::getInt8Ty(ctx_);
  case zir::TypeKind::Int8:
  case zir::TypeKind::UInt8:
    return llvm::Type::getInt8Ty(ctx_);
  case zir::TypeKind::Int16:
  case zir::TypeKind::UInt16:
    return llvm::Type::getInt16Ty(ctx_);
  case zir::TypeKind::Int32:
  case zir::TypeKind::UInt32:
    return llvm::Type::getInt32Ty(ctx_);
  case zir::TypeKind::Int:
  case zir::TypeKind::UInt:
  case zir::TypeKind::Int64:
  case zir::TypeKind::UInt64:
    return llvm::Type::getInt64Ty(ctx_);
  case zir::TypeKind::Float:
  case zir::TypeKind::Float32:
    return llvm::Type::getFloatTy(ctx_);
  case zir::TypeKind::Float64:
    return llvm::Type::getDoubleTy(ctx_);
  case zir::TypeKind::Pointer: {
    const auto &pt = static_cast<const zir::PointerType &>(ty);
    auto *baseTy = toLLVMType(*pt.getBaseType());
    if (baseTy->isVoidTy()) {
      baseTy = llvm::Type::getInt8Ty(ctx_);
    }
    return llvm::PointerType::getUnqual(baseTy);
  }
  case zir::TypeKind::NullPtr:
    return llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
  case zir::TypeKind::Enum:
    if (static_cast<const zir::EnumType &>(ty).hasReprC)
      return llvm::Type::getInt32Ty(ctx_);
    return llvm::Type::getInt64Ty(ctx_);
  case zir::TypeKind::TaggedUnion: {
    const auto &tu = static_cast<const zir::TaggedUnionType &>(ty);
    auto it = structCache_.find(tu.getCodegenName());
    if (it != structCache_.end())
      return it->second;
    auto *structTy = llvm::StructType::create(ctx_, tu.getCodegenName());
    structCache_[tu.getCodegenName()] = structTy;
    llvm::Type *payloadStorageTy = llvm::Type::getInt8Ty(ctx_);
    uint64_t payloadStorageSize = 0;
    uint64_t payloadStorageAlign = 0;
    for (const auto &variant : tu.getVariants()) {
      if (!variant.payloadType)
        continue;
      auto *candidateTy = toLLVMType(*variant.payloadType);
      auto candidateSize =
          module_->getDataLayout().getTypeAllocSize(candidateTy);
      auto candidateAlign =
          module_->getDataLayout().getABITypeAlign(candidateTy).value();
      if (candidateSize > payloadStorageSize ||
          (candidateSize == payloadStorageSize &&
           candidateAlign > payloadStorageAlign)) {
        payloadStorageTy = candidateTy;
        payloadStorageSize = candidateSize;
        payloadStorageAlign = candidateAlign;
      }
    }
    structTy->setBody({llvm::Type::getInt32Ty(ctx_), payloadStorageTy});
    return structTy;
  }
  case zir::TypeKind::Record: {
    const auto &rt = static_cast<const zir::RecordType &>(ty);
    auto it = structCache_.find(rt.getCodegenName());
    if (it != structCache_.end())
      return it->second;
    if (isStringRecordName(rt.getName())) {
      auto *structTy = llvm::StructType::create(ctx_, rt.getCodegenName());
      structCache_[rt.getCodegenName()] = structTy;
      std::vector<llvm::Type *> fieldTypes;
      fieldTypes.push_back(
          llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
      fieldTypes.push_back(llvm::Type::getInt64Ty(ctx_));
      structTy->setBody(fieldTypes, rt.isPacked);
      return structTy;
    }
    auto *structTy = llvm::StructType::create(ctx_, rt.getCodegenName());
    structCache_[rt.getCodegenName()] = structTy;
    std::vector<llvm::Type *> fieldTypes;
    for (const auto &f : rt.getFields())
      fieldTypes.push_back(toLLVMAggregateFieldType(f.type));
    structTy->setBody(fieldTypes, rt.isPacked);
    return structTy;
  }
  case zir::TypeKind::Class: {
    const auto &ct = static_cast<const zir::ClassType &>(ty);
    return llvm::PointerType::getUnqual(getOrCreateClassStruct(ct));
  }
  case zir::TypeKind::Array: {
    const auto &at = static_cast<const zir::ArrayType &>(ty);
    return llvm::ArrayType::get(toLLVMType(*at.getBaseType()), at.getSize());
  }
  case zir::TypeKind::FunctionPointer: {
    const auto &ft = static_cast<const zir::FunctionPointerType &>(ty);
    std::vector<llvm::Type *> paramTypes;
    for (const auto &p : ft.getParams())
      paramTypes.push_back(toLLVMType(*p));
    auto *fnTy = llvm::FunctionType::get(toLLVMType(*ft.getReturnType()),
                                         paramTypes, false);
    return llvm::PointerType::getUnqual(fnTy);
  }
  default:
    break;
  }
  throw std::runtime_error("Unknown ZIR type: " + ty.toString());
}
References zir::Array, at(), zir::Bool, zir::Char, zir::Class, ctx_, zir::Enum, zir::Float, zir::Float32, zir::Float64, zir::FunctionPointer, zir::Type::getKind(), getOrCreateClassStruct(), zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, module_, zir::NullPtr, zir::Pointer, zir::Record, structCache_, zir::TaggedUnion, toLLVMAggregateFieldType(), toLLVMType(), zir::Type::toString(), zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, zir::UInt8, and zir::Void.
Referenced by buildFunctionType(), buildFunctionType(), emitScopeReleases(), emitStoreWithStringArc(), emitStringConcat(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), emitZIRFunction(), emitZIRInstruction(), generate(), lowerZIRAggregateConstant(), lowerZIRArrayConstant(), lowerZIRCast(), lowerZIRConstant(), lowerZIRRValue(), toLLVMAggregateFieldType(), toLLVMType(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
visit() [1/40]
void codegen::LLVMCodeGen::visit (sema::BoundArrayLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 686 of file llvm_codegen_expr.cpp.
{
  auto *arrayTy = static_cast<llvm::ArrayType *>(toLLVMType(*node.type));
  auto *elemTy = arrayTy->getElementType();
  (void)elemTy;
  std::vector<llvm::Constant *> constants;
  bool allConstants = true;
  for (const auto &expr : node.elements) {
    expr->accept(*this);
    if (auto *c = llvm::dyn_cast<llvm::Constant>(lastValue_)) {
      constants.push_back(c);
    } else {
      allConstants = false;
      break;
    }
  }
  if (allConstants) {
    lastValue_ = llvm::ConstantArray::get(arrayTy, constants);
  } else {
    // If not all elements are constants, allocate on stack and store
    auto *alloca = createEntryAlloca(currentFn_, "array_lit", arrayTy);
    for (size_t i = 0; i < node.elements.size(); ++i) {
      node.elements[i]->accept(*this);
      auto *ptr = builder_.CreateConstGEP2_32(arrayTy, alloca, 0, (unsigned)i);
      builder_.CreateStore(lastValue_, ptr);
    }
    lastValue_ = builder_.CreateLoad(arrayTy, alloca);
  }
}
References builder_, createEntryAlloca(), currentFn_, sema::BoundArrayLiteral::elements, lastValue_, toLLVMType(), and sema::BoundExpression::type.
visit() [2/40]
void codegen::LLVMCodeGen::visit (sema::BoundAsmStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1257 of file llvm_codegen.cpp.
{
  std::vector<std::string> outConstraints, inConstraints;
  std::vector<llvm::Value *> outAddrs, inValues;
  std::vector<llvm::Type *> outValueTypes;
  for (auto &out : node.outputs) {
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = true;
    out.expr->accept(*this);
    evaluateAsAddr_ = old;
    outConstraints.push_back(out.constraint);
    outAddrs.push_back(lastValue_);
    outValueTypes.push_back(toLLVMType(*out.expr->type));
  }
  for (auto &in : node.inputs) {
    in.expr->accept(*this);
    inConstraints.push_back(in.constraint);
    inValues.push_back(lastValue_);
  }
  buildInlineAsmCall(node.assembly, outConstraints, outAddrs, outValueTypes,
                     inConstraints, inValues, node.clobbers);
}
References sema::BoundAsmStatement::assembly, buildInlineAsmCall(), sema::BoundAsmStatement::clobbers, evaluateAsAddr_, sema::BoundAsmStatement::inputs, lastValue_, sema::BoundAsmStatement::outputs, and toLLVMType().
visit() [3/40]
void codegen::LLVMCodeGen::visit (sema::BoundAssignment & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1050 of file llvm_codegen.cpp.
{
  bool old = evaluateAsAddr_;
  llvm::Value *alloca = nullptr;
  llvm::Value *oldCompoundTargetAddr = compoundTargetAddr_;
  if (node.isCompound) {
    evaluateAsAddr_ = true;
    node.target->accept(*this);
    alloca = lastValue_;
    evaluateAsAddr_ = old;
    compoundTargetAddr_ = alloca;
  }
  node.expression->accept(*this);
  llvm::Value *val = lastValue_;
  compoundTargetAddr_ = oldCompoundTargetAddr;
  if (!node.isCompound) {
    evaluateAsAddr_ = true;
    node.target->accept(*this);
    alloca = lastValue_;
    evaluateAsAddr_ = old;
  }
  if (isClassType(node.target->type)) {
    emitStoreWithArc(alloca, val, node.target->type,
                     expressionProducesOwnedClass(node.expression.get()));
  } else {
    builder_.CreateStore(val, alloca);
  }
}
References builder_, compoundTargetAddr_, emitStoreWithArc(), evaluateAsAddr_, sema::BoundAssignment::expression, expressionProducesOwnedClass(), isClassType(), sema::BoundAssignment::isCompound, lastValue_, and sema::BoundAssignment::target.
visit() [4/40]
void codegen::LLVMCodeGen::visit (sema::BoundBinaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 263 of file llvm_codegen_expr.cpp.
{
  if (node.op == "&&") {
    auto *rhsBB = llvm::BasicBlock::Create(ctx_, "and.rhs", currentFn_);
    auto *mergeBB = llvm::BasicBlock::Create(ctx_, "and.merge", currentFn_);
    node.left->accept(*this);
    auto *lhs = lastValue_;
    auto *leftBB = builder_.GetInsertBlock();
    builder_.CreateCondBr(lhs, rhsBB, mergeBB);
    builder_.SetInsertPoint(rhsBB);
    node.right->accept(*this);
    auto *rhs = lastValue_;
    auto *actualRhsBB = builder_.GetInsertBlock();
    builder_.CreateBr(mergeBB);
    builder_.SetInsertPoint(mergeBB);
    auto *phi = builder_.CreatePHI(llvm::Type::getInt1Ty(ctx_), 2, "and.res");
    phi->addIncoming(llvm::ConstantInt::get(llvm::Type::getInt1Ty(ctx_), 0),
                     leftBB);
    phi->addIncoming(rhs, actualRhsBB);
    lastValue_ = phi;
    return;
  }
  if (node.op == "||") {
    auto *rhsBB = llvm::BasicBlock::Create(ctx_, "or.rhs", currentFn_);
    auto *mergeBB = llvm::BasicBlock::Create(ctx_, "or.merge", currentFn_);
    node.left->accept(*this);
    auto *lhs = lastValue_;
    auto *leftBB = builder_.GetInsertBlock();
    builder_.CreateCondBr(lhs, mergeBB, rhsBB);
    builder_.SetInsertPoint(rhsBB);
    node.right->accept(*this);
    auto *rhs = lastValue_;
    auto *actualRhsBB = builder_.GetInsertBlock();
    builder_.CreateBr(mergeBB);
    builder_.SetInsertPoint(mergeBB);
    auto *phi = builder_.CreatePHI(llvm::Type::getInt1Ty(ctx_), 2, "or.res");
    phi->addIncoming(llvm::ConstantInt::get(llvm::Type::getInt1Ty(ctx_), 1),
                     leftBB);
    phi->addIncoming(rhs, actualRhsBB);
    lastValue_ = phi;
    return;
  }
  node.left->accept(*this);
  auto *lhs = lastValue_;
  node.right->accept(*this);
  auto *rhs = lastValue_;
  bool isPointer =
      lhs->getType()->isPointerTy() || rhs->getType()->isPointerTy();
  bool isFP = lhs->getType()->isFloatingPointTy();
  bool isUnsigned = node.left->type->isUnsigned();
  if (isPointer && (node.op == "+" || node.op == "-")) {
    llvm::Value *pointerValue = lhs->getType()->isPointerTy() ? lhs : rhs;
    llvm::Value *offsetValue = lhs->getType()->isPointerTy() ? rhs : lhs;
    auto ptrType = std::static_pointer_cast<zir::PointerType>(
        lhs->getType()->isPointerTy() ? node.left->type : node.right->type);
    auto *elemTy = toLLVMType(*ptrType->getBaseType());
    if (lhs->getType()->isPointerTy() && rhs->getType()->isPointerTy()) {
      auto *i64Ty = llvm::Type::getInt64Ty(ctx_);
      auto *lhsInt = builder_.CreatePtrToInt(lhs, i64Ty);
      auto *rhsInt = builder_.CreatePtrToInt(rhs, i64Ty);
      auto *bytes = builder_.CreateSub(lhsInt, rhsInt);
      llvm::Value *elemSize64 = llvm::ConstantExpr::getSizeOf(elemTy);
      if (elemSize64->getType() != i64Ty) {
        elemSize64 =
            builder_.CreateIntCast(elemSize64, i64Ty, /*isSigned=*/false);
      }
      lastValue_ = builder_.CreateSDiv(bytes, elemSize64);
      return;
    }
    auto *indexTy = llvm::Type::getInt64Ty(ctx_);
    auto *index =
        builder_.CreateIntCast(offsetValue, indexTy, /*isSigned=*/true);
    if (node.op == "-") {
      index = builder_.CreateNeg(index);
    }
    lastValue_ = builder_.CreateInBoundsGEP(elemTy, pointerValue, index);
    return;
  }
  if (node.op == "-")
    lastValue_ =
        isFP ? builder_.CreateFSub(lhs, rhs) : builder_.CreateSub(lhs, rhs);
  else if (node.op == "*")
    lastValue_ =
        isFP ? builder_.CreateFMul(lhs, rhs) : builder_.CreateMul(lhs, rhs);
  else if (node.op == "/")
    lastValue_ = isFP ? builder_.CreateFDiv(lhs, rhs)
                      : (isUnsigned ? builder_.CreateUDiv(lhs, rhs)
                                    : builder_.CreateSDiv(lhs, rhs));
  else if (node.op == "%")
    lastValue_ = isFP ? builder_.CreateFRem(lhs, rhs)
                      : (isUnsigned ? builder_.CreateURem(lhs, rhs)
                                    : builder_.CreateSRem(lhs, rhs));
  else if (node.op == "<<")
    lastValue_ = builder_.CreateShl(lhs, rhs);
  else if (node.op == ">>")
    lastValue_ = isUnsigned ? builder_.CreateLShr(lhs, rhs)
                            : builder_.CreateAShr(lhs, rhs);
  else if (node.op == "&")
    lastValue_ = builder_.CreateAnd(lhs, rhs);
  else if (node.op == "|")
    lastValue_ = builder_.CreateOr(lhs, rhs);
  else if (node.op == "^")
    lastValue_ = builder_.CreateXor(lhs, rhs);
  else if ((node.op == "==" || node.op == "!=") &&
           isStringType(node.left->type) && isStringType(node.right->type)) {
    auto *boolTy = llvm::Type::getInt1Ty(ctx_);
    auto *strTy = lhs->getType();
    auto *eqFnTy = llvm::FunctionType::get(boolTy, {strTy, strTy}, false);
    auto eqCallee = module_->getOrInsertFunction("eq", eqFnTy);
    auto *isEq =
        builder_.CreateCall(eqFnTy, eqCallee.getCallee(), {lhs, rhs}, "str.eq");
    lastValue_ = node.op == "==" ? isEq : builder_.CreateNot(isEq, "str.ne");
  } else if (node.op == "==")
    lastValue_ = isFP ? builder_.CreateFCmpOEQ(lhs, rhs)
                      : builder_.CreateICmpEQ(lhs, rhs);
  else if (node.op == "!=")
    lastValue_ = isFP ? builder_.CreateFCmpONE(lhs, rhs)
                      : builder_.CreateICmpNE(lhs, rhs);
  else if (node.op == "<")
    lastValue_ = isFP ? builder_.CreateFCmpOLT(lhs, rhs)
                      : (isUnsigned ? builder_.CreateICmpULT(lhs, rhs)
                                    : builder_.CreateICmpSLT(lhs, rhs));
  else if (node.op == "<=")
    lastValue_ = isFP ? builder_.CreateFCmpOLE(lhs, rhs)
                      : (isUnsigned ? builder_.CreateICmpULE(lhs, rhs)
                                    : builder_.CreateICmpSLE(lhs, rhs));
  else if (node.op == ">")
    lastValue_ = isFP ? builder_.CreateFCmpOGT(lhs, rhs)
                      : (isUnsigned ? builder_.CreateICmpUGT(lhs, rhs)
                                    : builder_.CreateICmpSGT(lhs, rhs));
  else if (node.op == ">=")
    lastValue_ = isFP ? builder_.CreateFCmpOGE(lhs, rhs)
                      : (isUnsigned ? builder_.CreateICmpUGE(lhs, rhs)
                                    : builder_.CreateICmpSGE(lhs, rhs));
  else if (node.op == "+") {
    if (isStringType(node.left->type) || isStringType(node.right->type) ||
        node.left->type->getKind() == zir::TypeKind::Char ||
        node.right->type->getKind() == zir::TypeKind::Char) {
      lastValue_ = emitStringConcat(lhs, rhs, node.left->type, node.right->type,
                                    node.type);
    } else {
      lastValue_ =
          isFP ? builder_.CreateFAdd(lhs, rhs) : builder_.CreateAdd(lhs, rhs);
    }
  }
}
References builder_, zir::Char, ctx_, currentFn_, emitStringConcat(), lastValue_, sema::BoundBinaryExpression::left, module_, sema::BoundBinaryExpression::op, sema::BoundBinaryExpression::right, toLLVMType(), and sema::BoundExpression::type.
visit() [5/40]
void codegen::LLVMCodeGen::visit (sema::BoundBlock & node) override virtual
Implements sema::BoundVisitor.
Definition at line 911 of file llvm_codegen.cpp.
{
  scopeClassLocals_.push_back({});
  scopeStringLocals_.push_back({});
  for (const auto &stmt : node.statements) {
    if (builder_.GetInsertBlock()->getTerminator()) {
      break;
    }
    stmt->accept(*this);
  }
  if (node.result && !builder_.GetInsertBlock()->getTerminator()) {
    node.result->accept(*this);
    if (isClassType(node.result->type) &&
        !expressionProducesOwnedClass(node.result.get())) {
      emitRetainIfNeeded(lastValue_, node.result->type);
    }
  }
  if (!builder_.GetInsertBlock()->getTerminator()) {
    emitScopeReleases();
  }
  scopeClassLocals_.pop_back();
  scopeStringLocals_.pop_back();
}
References builder_, emitRetainIfNeeded(), emitScopeReleases(), expressionProducesOwnedClass(), isClassType(), lastValue_, sema::BoundBlock::result, scopeClassLocals_, scopeStringLocals_, and sema::BoundBlock::statements.
visit() [6/40]
void codegen::LLVMCodeGen::visit (sema::BoundBreakStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1247 of file llvm_codegen.cpp.
{
  if (loopBBStack_.empty())
    return; // binder should have diagnosed
  auto endBB = loopBBStack_.back().second;
  builder_.CreateBr(endBB);
  // Create a new continuation block so subsequent instructions have a place
  auto *contBB = llvm::BasicBlock::Create(ctx_, "after.break", currentFn_);
  builder_.SetInsertPoint(contBB);
}
References builder_, ctx_, currentFn_, and loopBBStack_.
visit() [7/40]
void codegen::LLVMCodeGen::visit (sema::BoundCast & node) override virtual
Implements sema::BoundVisitor.
Definition at line 46 of file llvm_codegen_expr.cpp.
{
  node.expression->accept(*this);
  auto *src = lastValue_;
  auto *srcTy = src->getType();
  auto *destTy = toLLVMType(*node.type);
  if (isStringType(node.expression->type) && isStringType(node.type)) {
    if (srcTy == destTy) {
      lastValue_ = src;
      return;
    }
    auto *ptr = builder_.CreateExtractValue(src, {0}, "str.cast.ptr");
    auto *len = builder_.CreateExtractValue(src, {1}, "str.cast.len");
    llvm::Value *result = llvm::UndefValue::get(destTy);
    result = builder_.CreateInsertValue(result, ptr, {0}, "str.cast.ptr.i");
    result = builder_.CreateInsertValue(result, len, {1}, "str.cast.len.i");
    lastValue_ = result;
    return;
  }
  if (isStringType(node.expression->type) && destTy->isPointerTy()) {
    auto *ptr = builder_.CreateExtractValue(src, {0}, "str.ptr");
    if (ptr->getType() == destTy) {
      lastValue_ = ptr;
    } else {
      lastValue_ = builder_.CreateBitCast(ptr, destTy);
    }
    return;
  }
  if (srcTy->isPointerTy() && isStringType(node.type)) {
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *cstrPtr =
        srcTy == i8PtrTy ? src : builder_.CreateBitCast(src, i8PtrTy);
    std::vector<llvm::Type *> fromCStrParams = {i8PtrTy};
    auto *fromCStrTy = llvm::FunctionType::get(destTy, fromCStrParams, false);
    auto fromCStrCallee =
        module_->getOrInsertFunction("zap_string_from_cstr", fromCStrTy);
    lastValue_ = builder_.CreateCall(fromCStrTy, fromCStrCallee.getCallee(),
                                     {cstrPtr}, "str.from.cstr");
    return;
  }
  if (srcTy == destTy) {
    lastValue_ = src;
    return;
  }
  auto *srcConst = llvm::dyn_cast<llvm::Constant>(src);
  if (srcTy->isPointerTy() && destTy->isPointerTy()) {
    lastValue_ = srcConst ? llvm::ConstantExpr::getBitCast(srcConst, destTy)
                          : builder_.CreateBitCast(src, destTy);
  } else if (srcTy->isPointerTy() && destTy->isIntegerTy()) {
    lastValue_ = srcConst ? llvm::ConstantExpr::getPtrToInt(srcConst, destTy)
                          : builder_.CreatePtrToInt(src, destTy);
  } else if (srcTy->isIntegerTy() && destTy->isPointerTy()) {
    lastValue_ = srcConst ? llvm::ConstantExpr::getIntToPtr(srcConst, destTy)
                          : builder_.CreateIntToPtr(src, destTy);
  } else if (srcTy->isIntegerTy() && destTy->isIntegerTy()) {
    unsigned srcBits = srcTy->getIntegerBitWidth();
    unsigned destBits = destTy->getIntegerBitWidth();
    if (destBits > srcBits) {
      if (node.expression->type->isUnsigned() ||
          node.expression->type->getKind() == zir::TypeKind::Char) {
        lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                    llvm::Instruction::ZExt, srcConst, destTy)
                              : builder_.CreateZExt(src, destTy);
      } else {
        lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                    llvm::Instruction::SExt, srcConst, destTy)
                              : builder_.CreateSExt(src, destTy);
      }
    } else if (destBits < srcBits) {
      lastValue_ = srcConst ? llvm::ConstantExpr::getTrunc(srcConst, destTy)
                            : builder_.CreateTrunc(src, destTy);
    } else {
      lastValue_ = src;
    }
  } else if (srcTy->isIntegerTy() && destTy->isFloatingPointTy()) {
    if (node.expression->type->isUnsigned()) {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::UIToFP, srcConst, destTy)
                            : builder_.CreateUIToFP(src, destTy);
    } else {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::SIToFP, srcConst, destTy)
                            : builder_.CreateSIToFP(src, destTy);
    }
  } else if (srcTy->isFloatingPointTy() && destTy->isIntegerTy()) {
    if (node.type->isUnsigned()) {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::FPToUI, srcConst, destTy)
                            : builder_.CreateFPToUI(src, destTy);
    } else {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::FPToSI, srcConst, destTy)
                            : builder_.CreateFPToSI(src, destTy);
    }
  } else if (srcTy->isFloatingPointTy() && destTy->isFloatingPointTy()) {
    if (srcTy->getPrimitiveSizeInBits() < destTy->getPrimitiveSizeInBits()) {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::FPExt, srcConst, destTy)
                            : builder_.CreateFPExt(src, destTy);
    } else if (srcTy->getPrimitiveSizeInBits() >
               destTy->getPrimitiveSizeInBits()) {
      lastValue_ = srcConst ? llvm::ConstantExpr::getCast(
                                  llvm::Instruction::FPTrunc, srcConst, destTy)
                            : builder_.CreateFPTrunc(src, destTy);
    } else {
      lastValue_ = src;
    }
  } else {
    lastValue_ = srcConst ? llvm::ConstantExpr::getBitCast(srcConst, destTy)
                          : builder_.CreateBitCast(src, destTy);
  }
}
References builder_, zir::Char, ctx_, sema::BoundCast::expression, lastValue_, len(), module_, toLLVMType(), and sema::BoundExpression::type.
visit() [8/40]
void codegen::LLVMCodeGen::visit (sema::BoundCompoundTargetLoad & node) override virtual
Implements sema::BoundVisitor.
Definition at line 165 of file llvm_codegen_expr.cpp.
{
  lastValue_ = builder_.CreateLoad(toLLVMType(*node.type), compoundTargetAddr_);
}
References builder_, compoundTargetAddr_, lastValue_, toLLVMType(), and sema::BoundExpression::type.
visit() [9/40]
void codegen::LLVMCodeGen::visit (sema::BoundContinueStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1281 of file llvm_codegen.cpp.
{
  if (loopBBStack_.empty())
    return;
  auto condBB = loopBBStack_.back().first;
  builder_.CreateBr(condBB);
  auto *contBB = llvm::BasicBlock::Create(ctx_, "after.continue", currentFn_);
  builder_.SetInsertPoint(contBB);
}
References builder_, ctx_, currentFn_, and loopBBStack_.
visit() [10/40]
void codegen::LLVMCodeGen::visit (sema::BoundEnumDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1092 of file llvm_codegen.cpp.
{
  // Enums are typically handled at the type level in ZIR/sema.
  // We don't need to generate code for the declaration itself
  // unless we want to generate debug info or constant values.
  (void)node;
}
visit() [11/40]
void codegen::LLVMCodeGen::visit (sema::BoundExpressionStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1080 of file llvm_codegen.cpp.
{
  node.expression->accept(*this);
  if (isClassType(node.expression->type) &&
      expressionProducesOwnedClass(node.expression.get())) {
    emitReleaseIfNeeded(lastValue_, node.expression->type);
  }
}
References emitReleaseIfNeeded(), sema::BoundExpressionStatement::expression, expressionProducesOwnedClass(), isClassType(), and lastValue_.
visit() [12/40]
void codegen::LLVMCodeGen::visit (sema::BoundExternalFunctionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 902 of file llvm_codegen.cpp.
{
  (void)node;
}
visit() [13/40]
void codegen::LLVMCodeGen::visit (sema::BoundFailableHandleExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1141 of file llvm_codegen_expr.cpp.
{
  (void)node;
  throw std::runtime_error("BoundFailableHandleExpression should be lowered to "
                           "ZIR before LLVMCodeGen.");
}
visit() [14/40]
void codegen::LLVMCodeGen::visit (sema::BoundFailStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1103 of file llvm_codegen.cpp.
{
  (void)node;
  throw std::runtime_error(
      "BoundFailStatement should be lowered to ZIR before LLVMCodeGen.");
}
visit() [15/40]
void codegen::LLVMCodeGen::visit (sema::BoundFallbackExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1135 of file llvm_codegen_expr.cpp.
{
  (void)node;
  throw std::runtime_error(
      "BoundFallbackExpression should be lowered to ZIR before LLVMCodeGen.");
}
visit() [16/40]
void codegen::LLVMCodeGen::visit (sema::BoundForStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1192 of file llvm_codegen.cpp.
{
  if (!currentFn_)
    throw std::runtime_error("currentFn_ is null in visit(BoundForStatement)");
  if (node.initializer) {
    if (auto *initBlock =
            dynamic_cast<sema::BoundBlock *>(node.initializer.get())) {
      for (const auto &stmt : initBlock->statements) {
        if (stmt) {
          stmt->accept(*this);
        }
      }
    } else {
      node.initializer->accept(*this);
    }
  }
  auto *condBB = llvm::BasicBlock::Create(ctx_, "for.cond", currentFn_);
  auto *bodyBB = llvm::BasicBlock::Create(ctx_, "for.body", currentFn_);
  auto *stepBB = llvm::BasicBlock::Create(ctx_, "for.step", currentFn_);
  auto *endBB = llvm::BasicBlock::Create(ctx_, "for.end", currentFn_);
  builder_.CreateBr(condBB);
  builder_.SetInsertPoint(condBB);
  if (!node.condition)
    throw std::runtime_error("condition is null in BoundForStatement");
  node.condition->accept(*this);
  auto *cond = lastValue_;
  if (!cond)
    throw std::runtime_error(
        "lastValue_ is null after condition in BoundForStatement");
  builder_.CreateCondBr(cond, bodyBB, endBB);
  builder_.SetInsertPoint(bodyBB);
  loopBBStack_.push_back({stepBB, endBB});
  if (node.body) {
    node.body->accept(*this);
  }
  loopBBStack_.pop_back();
  if (!builder_.GetInsertBlock()->getTerminator()) {
    builder_.CreateBr(stepBB);
  }
  builder_.SetInsertPoint(stepBB);
  if (node.increment) {
    node.increment->accept(*this);
  }
  if (!builder_.GetInsertBlock()->getTerminator()) {
    builder_.CreateBr(condBB);
  }
  builder_.SetInsertPoint(endBB);
}
References sema::BoundForStatement::body, builder_, sema::BoundForStatement::condition, ctx_, currentFn_, sema::BoundForStatement::increment, sema::BoundForStatement::initializer, lastValue_, and loopBBStack_.
visit() [17/40]
void codegen::LLVMCodeGen::visit (sema::BoundFunctionCall & node) override virtual
Implements sema::BoundVisitor.
Definition at line 486 of file llvm_codegen_expr.cpp.
{
  auto *callee = functionMap_.at(node.symbol->linkName);
  std::vector<llvm::Value *> args;
  size_t fixedParamCount = node.symbol->fixedParameterCount();
  for (size_t i = 0; i < node.arguments.size(); ++i) {
    bool isRef = false;
    if (i < fixedParamCount && i < node.argumentIsRef.size())
      isRef = node.argumentIsRef[i];
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = isRef; // false for value args, true for ref args
    node.arguments[i]->accept(*this);
    if (!isRef && i < fixedParamCount) {
      const auto &param = node.symbol->parameters[i];
      bool isBorrowedSelf =
          node.symbol->isMethod && !node.symbol->isStatic && i == 0;
      if (!isBorrowedSelf && isClassType(param->type) &&
          !isWeakClassType(param->type) &&
          !expressionProducesOwnedClass(node.arguments[i].get())) {
        emitRetainIfNeeded(lastValue_, param->type);
      }
    }
    args.push_back(lastValue_);
    evaluateAsAddr_ = old;
  }
  if (node.symbol->hasVariadicParameter()) {
    auto variadicParam = node.symbol->variadicParameter();
    auto *elemTy = toLLVMType(*variadicParam->variadic_element_type);
    auto *elemPtrTy = llvm::PointerType::getUnqual(elemTy);
    size_t explicitVariadicCount = node.arguments.size() - fixedParamCount;
    llvm::Value *forwardedCount =
        llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0);
    llvm::Value *forwardedData = llvm::ConstantPointerNull::get(elemPtrTy);
    if (node.variadicPack) {
      node.variadicPack->accept(*this);
      forwardedData =
          builder_.CreateExtractValue(lastValue_, {0}, "varargs.forward.data");
      forwardedCount =
          builder_.CreateExtractValue(lastValue_, {1}, "varargs.forward.len");
      if (forwardedCount->getType() != llvm::Type::getInt32Ty(ctx_)) {
        forwardedCount = builder_.CreateIntCast(
            forwardedCount, llvm::Type::getInt32Ty(ctx_), /*isSigned=*/true);
      }
    }
    llvm::Value *explicitCount =
        llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                               static_cast<uint64_t>(explicitVariadicCount));
    if (explicitVariadicCount == 0 && !node.variadicPack) {
      args.push_back(explicitCount);
      args.push_back(llvm::ConstantPointerNull::get(elemPtrTy));
    } else if (explicitVariadicCount == 0) {
      args.push_back(forwardedCount);
      args.push_back(forwardedData);
    } else {
      llvm::Value *totalCount = explicitCount;
      if (node.variadicPack) {
        totalCount =
            builder_.CreateAdd(explicitCount, forwardedCount, "varargs.total");
      }
      auto *buffer = builder_.CreateAlloca(elemTy, totalCount, "varargs.buf");
      for (size_t i = 0; i < explicitVariadicCount; ++i) {
        auto *dst = builder_.CreateInBoundsGEP(
            elemTy, buffer,
            llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                                   static_cast<uint64_t>(i)));
        builder_.CreateStore(args[fixedParamCount + i], dst);
      }
      if (node.variadicPack) {
        auto *copyCondBB =
            llvm::BasicBlock::Create(ctx_, "varargs.copy.cond", currentFn_);
        auto *copyBodyBB =
            llvm::BasicBlock::Create(ctx_, "varargs.copy.body", currentFn_);
        auto *copyDoneBB =
            llvm::BasicBlock::Create(ctx_, "varargs.copy.done", currentFn_);
        auto *copyPreheaderBB = builder_.GetInsertBlock();
        builder_.CreateBr(copyCondBB);
        builder_.SetInsertPoint(copyCondBB);
        auto *indexPhi =
            builder_.CreatePHI(llvm::Type::getInt32Ty(ctx_), 2, "varargs.i");
        indexPhi->addIncoming(
            llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0),
            copyPreheaderBB);
        auto *hasMore = builder_.CreateICmpSLT(indexPhi, forwardedCount);
        builder_.CreateCondBr(hasMore, copyBodyBB, copyDoneBB);
        builder_.SetInsertPoint(copyBodyBB);
        auto *src = builder_.CreateInBoundsGEP(elemTy, forwardedData, indexPhi);
        auto *dstIndex = builder_.CreateAdd(explicitCount, indexPhi);
        auto *dst = builder_.CreateInBoundsGEP(elemTy, buffer, dstIndex);
        auto *loaded = builder_.CreateLoad(elemTy, src);
        builder_.CreateStore(loaded, dst);
        auto *nextIndex = builder_.CreateAdd(
            indexPhi, llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 1));
        builder_.CreateBr(copyCondBB);
        indexPhi->addIncoming(nextIndex, copyBodyBB);
        builder_.SetInsertPoint(copyDoneBB);
      }
      args.resize(fixedParamCount);
      args.push_back(totalCount);
      args.push_back(buffer);
    }
  }
  if (node.symbol->vtableSlot >= 0 && !args.empty()) {
    auto classType =
        std::static_pointer_cast<zir::ClassType>(node.arguments[0]->type);
    auto *objectTy = structCache_.at(classType->getCodegenName() + ".obj");
    auto *selfPtr = builder_.CreateBitCast(
        args[0], llvm::PointerType::getUnqual(objectTy), "method.self");
    auto *vtableAddr = builder_.CreateStructGEP(
        objectTy, selfPtr, kClassVTableIndex, "method.vtable.addr");
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *vtablePtrTy = llvm::PointerType::getUnqual(i8PtrTy);
    auto *vtablePtr =
        builder_.CreateLoad(vtablePtrTy, vtableAddr, "method.vtable");
    auto *slotAddr = builder_.CreateInBoundsGEP(
        i8PtrTy, vtablePtr,
        llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_),
                               static_cast<uint64_t>(node.symbol->vtableSlot)));
    auto *fnRaw = builder_.CreateLoad(i8PtrTy, slotAddr, "method.fn.raw");
    auto *fnPtr = builder_.CreateBitCast(
        fnRaw, llvm::PointerType::getUnqual(callee->getFunctionType()),
        "method.fn");
    lastValue_ = builder_.CreateCall(callee->getFunctionType(), fnPtr, args);
    if (node.symbol->returnsRef && !evaluateAsAddr_) {
      lastValue_ = builder_.CreateLoad(toLLVMType(*node.symbol->returnType),
                                       lastValue_, "ref.load");
    }
    return;
  }
  lastValue_ = builder_.CreateCall(callee, args);
  if (node.symbol->returnsRef && !evaluateAsAddr_) {
    lastValue_ = builder_.CreateLoad(toLLVMType(*node.symbol->returnType),
                                     lastValue_, "ref.load");
  }
  for (size_t i = 0; i < node.arguments.size() && i < fixedParamCount; ++i) {
    if (i < node.argumentIsRef.size() && node.argumentIsRef[i]) {
      continue;
    }
    const auto &param = node.symbol->parameters[i];
    if (isWeakClassType(param->type) &&
        expressionProducesOwnedClass(node.arguments[i].get())) {
      auto strongType = std::make_shared<zir::ClassType>(
          *std::static_pointer_cast<zir::ClassType>(param->type));
      strongType->setWeak(false);
      emitReleaseIfNeeded(args[i], strongType);
    }
  }
}
References sema::BoundFunctionCall::argumentIsRef, sema::BoundFunctionCall::arguments, builder_, ctx_, currentFn_, emitReleaseIfNeeded(), emitRetainIfNeeded(), evaluateAsAddr_, expressionProducesOwnedClass(), functionMap_, isClassType(), isWeakClassType(), codegen::kClassVTableIndex, lastValue_, structCache_, sema::BoundFunctionCall::symbol, toLLVMType(), and sema::BoundFunctionCall::variadicPack.
visit() [18/40]
void codegen::LLVMCodeGen::visit (sema::BoundFunctionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 755 of file llvm_codegen.cpp.
{
  auto *fn = functionMap_.at(node.symbol->linkName);
  currentFn_ = fn;
  localValues_.clear();
  scopeClassLocals_.clear();
  scopeStringLocals_.clear();
  scopeClassLocals_.push_back({});
  scopeStringLocals_.push_back({});
  auto *entry = llvm::BasicBlock::Create(ctx_, "entry", fn);
  builder_.SetInsertPoint(entry);
  auto argIt = fn->arg_begin();
  if (!freestanding_ && node.symbol->linkName == "main") {
    auto *i32Ty = llvm::Type::getInt32Ty(ctx_);
    auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
    auto *argvTy = llvm::PointerType::getUnqual(i8PtrTy);
    argIt->setName("argc");
    llvm::Value *argcValue = &*argIt++;
    argIt->setName("argv");
    llvm::Value *argvValue = &*argIt++;
    auto setArgsIt2 = functionMap_.find("__zap_process_set_args");
    if (setArgsIt2 == functionMap_.end()) {
      auto *ft = llvm::FunctionType::get(llvm::Type::getVoidTy(ctx_),
                                         {i32Ty, argvTy}, false);
      auto *setArgsFn =
          llvm::Function::Create(ft, llvm::Function::ExternalLinkage,
                                 "__zap_process_set_args", *module_);
      setArgsIt2 =
          functionMap_.emplace("__zap_process_set_args", setArgsFn).first;
    }
    builder_.CreateCall(
        setArgsIt2->second,
        {builder_.CreateIntCast(argcValue, i32Ty, true), argvValue});
  }
  // Spill each argument to a stack slot so we can reassign params later.
  size_t idx = 0;
  for (; argIt != fn->arg_end(); ++argIt) {
    const auto &param = node.symbol->parameters[idx++];
    if (param->is_variadic_pack) {
      auto &countArg = *argIt;
      ++argIt;
      auto &dataArg = *argIt;
      auto *sliceTy = static_cast<llvm::StructType *>(toLLVMType(*param->type));
      auto *sliceAlloca = createEntryAlloca(fn, param->name, sliceTy);
      llvm::Value *sliceValue = llvm::PoisonValue::get(sliceTy);
      sliceValue = builder_.CreateInsertValue(sliceValue, &dataArg, {0},
                                              param->name + ".data");
      llvm::Value *countValue = &countArg;
      if (countValue->getType() != sliceTy->getElementType(1)) {
        countValue = builder_.CreateIntCast(
            countValue, sliceTy->getElementType(1),
            /*isSigned=*/true, param->name + ".len.cast");
      }
      sliceValue = builder_.CreateInsertValue(sliceValue, countValue, {1},
                                              param->name + ".len");
      builder_.CreateStore(sliceValue, sliceAlloca);
      localValues_[param->name] = sliceAlloca;
      continue;
    }
    auto &arg = *argIt;
    auto *alloca = createEntryAlloca(fn, param->name, arg.getType());
    localValues_[param->name] = alloca;
    if (isClassType(param->type) && !param->is_ref) {
      bool isBorrowedSelf =
          node.symbol->isMethod && !node.symbol->isStatic && idx == 1;
      builder_.CreateStore(llvm::Constant::getNullValue(arg.getType()), alloca);
      if (isWeakClassType(param->type)) {
        emitStoreWithArc(alloca, &arg, param->type, /*valueIsOwned=*/false);
        scopeClassLocals_.back().push_back({param->type, alloca});
      } else if (!isBorrowedSelf) {
        builder_.CreateStore(&arg, alloca);
        scopeClassLocals_.back().push_back({param->type, alloca});
      } else {
        builder_.CreateStore(&arg, alloca);
      }
    } else {
      if (isOwnedStringType(param->type)) {
        builder_.CreateStore(llvm::Constant::getNullValue(arg.getType()),
                             alloca);
        emitStoreWithStringArc(alloca, &arg, param->type,
                               /*valueIsOwned=*/false);
        scopeStringLocals_.back().push_back({param->type, alloca});
        continue;
      }
      builder_.CreateStore(&arg, alloca);
    }
  }
  node.body->accept(*this);
  if (!builder_.GetInsertBlock()->getTerminator()) {
    if (node.body->result) {
      for (auto it = scopeClassLocals_.rbegin(); it != scopeClassLocals_.rend();
           ++it) {
        for (auto local = it->rbegin(); local != it->rend(); ++local) {
          auto *value = builder_.CreateLoad(
              toLLVMType(*local->first), local->second, "arc.fn.ret.release");
          if (isWeakClassType(local->first))
            emitReleaseWeakIfNeeded(value, local->first);
          else
            emitReleaseIfNeeded(value, local->first);
        }
      }
      for (auto it = scopeStringLocals_.rbegin();
           it != scopeStringLocals_.rend(); ++it) {
        for (auto local = it->rbegin(); local != it->rend(); ++local) {
          auto *value = builder_.CreateLoad(
              toLLVMType(*local->first), local->second, "str.fn.ret.release");
          emitStringReleaseIfNeeded(value, local->first);
        }
      }
      builder_.CreateRet(lastValue_);
    } else if (fn->getReturnType()->isVoidTy()) {
      for (auto it = scopeClassLocals_.rbegin(); it != scopeClassLocals_.rend();
           ++it) {
        for (auto local = it->rbegin(); local != it->rend(); ++local) {
          auto *value = builder_.CreateLoad(
              toLLVMType(*local->first), local->second, "arc.fn.ret.release");
          if (isWeakClassType(local->first))
            emitReleaseWeakIfNeeded(value, local->first);
          else
            emitReleaseIfNeeded(value, local->first);
        }
      }
      for (auto it = scopeStringLocals_.rbegin();
           it != scopeStringLocals_.rend(); ++it) {
        for (auto local = it->rbegin(); local != it->rend(); ++local) {
          auto *value = builder_.CreateLoad(
              toLLVMType(*local->first), local->second, "str.fn.ret.release");
          emitStringReleaseIfNeeded(value, local->first);
        }
      }
      builder_.CreateRetVoid();
    }
  }
  currentFn_ = nullptr;
  scopeClassLocals_.clear();
  scopeStringLocals_.clear();
}
References sema::BoundFunctionDeclaration::body, builder_, createEntryAlloca(), ctx_, currentFn_, emitReleaseIfNeeded(), emitReleaseWeakIfNeeded(), emitStoreWithArc(), emitStoreWithStringArc(), emitStringReleaseIfNeeded(), freestanding_, functionMap_, isClassType(), isOwnedStringType(), isWeakClassType(), lastValue_, localValues_, module_, scopeClassLocals_, scopeStringLocals_, sema::BoundFunctionDeclaration::symbol, and toLLVMType().
visit() [19/40]
void codegen::LLVMCodeGen::visit (sema::BoundFunctionReference & node) override virtual
Implements sema::BoundVisitor.
Definition at line 649 of file llvm_codegen_expr.cpp.
{
  auto it = functionMap_.find(node.symbol->linkName);
  if (it == functionMap_.end()) {
    // Declare it if not yet seen
    auto zirIt = zirFunctionMap_.find(node.symbol->linkName);
    if (zirIt != zirFunctionMap_.end()) {
      declareZIRFunction(*zirIt->second, false);
      it = functionMap_.find(node.symbol->linkName);
    }
  }
  if (it == functionMap_.end())
    throw std::runtime_error("Unknown function reference: " +
                             node.symbol->linkName);
  lastValue_ = it->second;
}
References declareZIRFunction(), functionMap_, lastValue_, sema::BoundFunctionReference::symbol, and zirFunctionMap_.
visit() [20/40]
void codegen::LLVMCodeGen::visit (sema::BoundIfStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1109 of file llvm_codegen.cpp.
{
  if (!currentFn_)
    throw std::runtime_error("currentFn_ is null in visit(BoundIfStatement)");
  auto *thenBB = llvm::BasicBlock::Create(ctx_, "if.then", currentFn_);
  auto *elseBB = node.elseBody
                     ? llvm::BasicBlock::Create(ctx_, "if.else", currentFn_)
                     : nullptr;
  auto *mergeBB = llvm::BasicBlock::Create(ctx_, "if.merge", currentFn_);
  if (!node.condition)
    throw std::runtime_error("condition is null in BoundIfStatement");
  node.condition->accept(*this);
  auto *cond = lastValue_;
  if (!cond)
    throw std::runtime_error(
        "lastValue_ is null after condition in BoundIfStatement");
  if (elseBB) {
    builder_.CreateCondBr(cond, thenBB, elseBB);
  } else {
    builder_.CreateCondBr(cond, thenBB, mergeBB);
  }
  builder_.SetInsertPoint(thenBB);
  if (node.thenBody) {
    lastValue_ = nullptr;
    node.thenBody->accept(*this);
  }
  if (!builder_.GetInsertBlock()->getTerminator()) {
    builder_.CreateBr(mergeBB);
  }
  thenBB = builder_.GetInsertBlock();
  if (elseBB) {
    builder_.SetInsertPoint(elseBB);
    if (node.elseBody) {
      lastValue_ = nullptr;
      node.elseBody->accept(*this);
    }
    if (!builder_.GetInsertBlock()->getTerminator()) {
      builder_.CreateBr(mergeBB);
    }
    elseBB = builder_.GetInsertBlock();
  }
  builder_.SetInsertPoint(mergeBB);
  lastValue_ = nullptr;
}
References builder_, sema::BoundIfStatement::condition, ctx_, currentFn_, sema::BoundIfStatement::elseBody, lastValue_, and sema::BoundIfStatement::thenBody.
visit() [21/40]
void codegen::LLVMCodeGen::visit (sema::BoundIndexAccess & node) override virtual
Implements sema::BoundVisitor.
Definition at line 718 of file llvm_codegen_expr.cpp.
{
  llvm::Value *leftAddr = nullptr;
  llvm::Value *leftValue = nullptr;
  bool old = evaluateAsAddr_;
  if (isStringType(node.left->type)) {
    evaluateAsAddr_ = false;
    node.left->accept(*this);
    leftValue = lastValue_;
  } else {
    evaluateAsAddr_ = true;
    node.left->accept(*this);
    leftAddr = lastValue_;
  }
  evaluateAsAddr_ = false;
  node.index->accept(*this);
  llvm::Value *indexVal = lastValue_;
  evaluateAsAddr_ = old;
  llvm::Value *elemAddr = nullptr;
  if (node.left->type->getKind() == zir::TypeKind::Array) {
    auto *leftTy = toLLVMType(*node.left->type);
    auto *i32Ty = llvm::Type::getInt32Ty(ctx_);
    std::vector<llvm::Value *> indices = {
        llvm::ConstantInt::get(i32Ty, 0),
        builder_.CreateIntCast(indexVal, i32Ty, /*isSigned=*/false)};
    elemAddr = builder_.CreateInBoundsGEP(leftTy, leftAddr, indices);
  } else if (isVariadicViewType(node.left->type)) {
    auto *sliceTy =
        static_cast<llvm::StructType *>(toLLVMType(*node.left->type));
    auto *dataAddr =
        builder_.CreateStructGEP(sliceTy, leftAddr, 0, "varargs.data.addr");
    auto *dataPtrTy = llvm::cast<llvm::PointerType>(sliceTy->getElementType(0));
    auto *dataPtr = builder_.CreateLoad(dataPtrTy, dataAddr, "varargs.data");
    auto recordType =
        std::static_pointer_cast<zir::RecordType>(node.left->type);
    auto dataType = std::static_pointer_cast<zir::PointerType>(
        recordType->getFields()[0].type);
    auto *elemTy = toLLVMType(*dataType->getBaseType());
    elemAddr =
        builder_.CreateInBoundsGEP(elemTy, dataPtr, indexVal, "varargs.index");
  } else if (isStringType(node.left->type)) {
    if (evaluateAsAddr_) {
      throw std::runtime_error("String index access is not assignable.");
    }
    auto *ptr = builder_.CreateExtractValue(leftValue, {0}, "string.ptr");
    auto *i8Ty = llvm::Type::getInt8Ty(ctx_);
    elemAddr = builder_.CreateInBoundsGEP(i8Ty, ptr, indexVal, "string.index");
  } else {
    throw std::runtime_error("Type '" + node.left->type->toString() +
                             "' does not support indexing.");
  }
  if (evaluateAsAddr_) {
    lastValue_ = elemAddr;
  } else {
    auto *ty = toLLVMType(*node.type);
    lastValue_ = builder_.CreateLoad(ty, elemAddr, "index_access");
  }
}
References zir::Array, builder_, ctx_, evaluateAsAddr_, sema::BoundIndexAccess::index, lastValue_, sema::BoundIndexAccess::left, toLLVMType(), and sema::BoundExpression::type.
visit() [22/40]
void codegen::LLVMCodeGen::visit (sema::BoundIndirectCall & node) override virtual
Implements sema::BoundVisitor.
Definition at line 665 of file llvm_codegen_expr.cpp.
{
  node.callee->accept(*this);
  auto *calleePtr = lastValue_;
  const auto &fpType =
      static_cast<const zir::FunctionPointerType &>(*node.callee->type);
  std::vector<llvm::Type *> paramTypes;
  for (const auto &p : fpType.getParams())
    paramTypes.push_back(toLLVMType(*p));
  auto *fnTy = llvm::FunctionType::get(toLLVMType(*fpType.getReturnType()),
                                       paramTypes, false);
  std::vector<llvm::Value *> args;
  for (auto &arg : node.arguments) {
    arg->accept(*this);
    args.push_back(lastValue_);
  }
  lastValue_ = builder_.CreateCall(fnTy, calleePtr, args);
}
References sema::BoundIndirectCall::arguments, builder_, sema::BoundIndirectCall::callee, lastValue_, and toLLVMType().
visit() [23/40]
void codegen::LLVMCodeGen::visit (sema::BoundLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 169 of file llvm_codegen_expr.cpp.
{
  if (node.type->getKind() == zir::TypeKind::Record) {
    const auto &rt = static_cast<const zir::RecordType &>(*node.type);
    if (isStringRecordName(rt.getName())) {
      std::string gname;
      auto *ptrConst = getOrCreateGlobalString(node.value, gname);
      auto *lenConst =
          llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_),
                                 static_cast<uint64_t>(node.value.size()));
      auto *structTy = static_cast<llvm::StructType *>(toLLVMType(*node.type));
      std::vector<llvm::Constant *> elems;
      elems.push_back(ptrConst);
      elems.push_back(lenConst);
      lastValue_ = llvm::ConstantStruct::get(structTy, elems);
      return;
    }
  }
  auto *ty = toLLVMType(*node.type);
  if (ty->isIntegerTy(1)) {
    lastValue_ = llvm::ConstantInt::get(ty, node.value == "true" ? 1 : 0);
  } else if (ty->isIntegerTy(8)) {
    int64_t code = 0;
    if (!node.value.empty()) {
      if (node.value.size() >= 2 && node.value[0] == '\\') {
        switch (node.value[1]) {
        case 'n':
          code = '\n';
          break;
        case 't':
          code = '\t';
          break;
        case 'r':
          code = '\r';
          break;
        case '\\':
          code = '\\';
          break;
        case '\'':
          code = '\'';
          break;
        case '0':
          code = '\0';
          break;
        default:
          code = static_cast<unsigned char>(node.value[1]);
          break;
        }
      } else {
        code = static_cast<unsigned char>(node.value[0]);
      }
    }
    lastValue_ = llvm::ConstantInt::get(ty, code, /*isSigned=*/false);
  } else if (ty->isIntegerTy()) {
    uint64_t unsignedValue = parseIntegerLiteral(node.value);
    if (node.type->isUnsigned()) {
      lastValue_ = llvm::ConstantInt::get(ty, unsignedValue,
                                          /*isSigned=*/false);
    } else {
      lastValue_ = llvm::ConstantInt::get(ty, unsignedValue, /*isSigned=*/true);
    }
  } else if (ty->isFloatTy()) {
    lastValue_ = llvm::ConstantFP::get(ty, std::stof(node.value));
  } else if (ty->isDoubleTy()) {
    lastValue_ = llvm::ConstantFP::get(ty, std::stod(node.value));
  } else {
    lastValue_ = llvm::Constant::getNullValue(ty);
  }
}
References ctx_, getOrCreateGlobalString(), lastValue_, zir::Record, toLLVMType(), sema::BoundExpression::type, and sema::BoundLiteral::value.
visit() [24/40]
void codegen::LLVMCodeGen::visit (sema::BoundMemberAccess & node) override virtual
Implements sema::BoundVisitor.
Definition at line 782 of file llvm_codegen_expr.cpp.
{
  if (node.left->type->getKind() == zir::TypeKind::Class) {
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = false;
    node.left->accept(*this);
    auto *objectPtr = lastValue_;
    evaluateAsAddr_ = old;
    auto classType = std::static_pointer_cast<zir::ClassType>(node.left->type);
    int fieldIndex = -1;
    const auto &fields = classType->getFields();
    for (size_t i = 0; i < fields.size(); ++i) {
      if (fields[i].name == node.member) {
        fieldIndex = static_cast<int>(i + kClassFieldStartIndex);
        break;
      }
    }
    if (fieldIndex == -1)
      throw std::runtime_error("Field '" + node.member +
                               "' not found in class '" +
                               node.left->type->toString() + "'");
    auto *objectStructTy =
        structCache_.at(classType->getCodegenName() + ".obj");
    llvm::Value *fieldAddr = builder_.CreateStructGEP(objectStructTy, objectPtr,
                                                      fieldIndex, node.member);
    if (evaluateAsAddr_) {
      lastValue_ = fieldAddr;
    } else {
      lastValue_ =
          builder_.CreateLoad(toLLVMType(*node.type), fieldAddr, node.member);
    }
    return;
  }
  if (node.left->type->getKind() == zir::TypeKind::Pointer) {
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = false;
    node.left->accept(*this);
    llvm::Value *basePtr = lastValue_;
    evaluateAsAddr_ = old;
    auto pointerType =
        std::static_pointer_cast<zir::PointerType>(node.left->type);
    auto baseType = pointerType->getBaseType();
    // Some ABI paths pass aggregate parameters as an extra pointer wrapper.
    // Peel one pointer level transparently for member access.
    if (baseType->getKind() == zir::TypeKind::Pointer) {
      auto innerPtrType = std::static_pointer_cast<zir::PointerType>(baseType);
      auto *loaded = builder_.CreateLoad(toLLVMType(*baseType), basePtr,
                                         "member.ptr.unwrap");
      basePtr = loaded;
      baseType = innerPtrType->getBaseType();
    }
    if (baseType->getKind() == zir::TypeKind::Record) {
      auto recordType = std::static_pointer_cast<zir::RecordType>(baseType);
      int fieldIndex = -1;
      const auto &fields = recordType->getFields();
      for (size_t i = 0; i < fields.size(); ++i) {
        if (fields[i].name == node.member) {
          fieldIndex = static_cast<int>(i);
          break;
        }
      }
      if (fieldIndex == -1) {
        throw std::runtime_error("Field '" + node.member +
                                 "' not found in type '" +
                                 baseType->toString() + "'");
      }
      auto *structTy = static_cast<llvm::StructType *>(toLLVMType(*recordType));
      llvm::Value *fieldAddr =
          builder_.CreateStructGEP(structTy, basePtr, fieldIndex, node.member);
      if (evaluateAsAddr_) {
        lastValue_ = fieldAddr;
      } else {
        lastValue_ =
            builder_.CreateLoad(toLLVMType(*node.type), fieldAddr, node.member);
      }
      return;
    }
    if (baseType->getKind() == zir::TypeKind::Class) {
      auto classType = std::static_pointer_cast<zir::ClassType>(baseType);
      int fieldIndex = -1;
      const auto &fields = classType->getFields();
      for (size_t i = 0; i < fields.size(); ++i) {
        if (fields[i].name == node.member) {
          fieldIndex = static_cast<int>(i + kClassFieldStartIndex);
          break;
        }
      }
      if (fieldIndex == -1) {
        throw std::runtime_error("Field '" + node.member +
                                 "' not found in type '" +
                                 baseType->toString() + "'");
      }
      auto *objectStructTy =
          structCache_.at(classType->getCodegenName() + ".obj");
      llvm::Value *fieldAddr = builder_.CreateStructGEP(
          objectStructTy, basePtr, fieldIndex, node.member);
      if (evaluateAsAddr_) {
        lastValue_ = fieldAddr;
      } else {
        lastValue_ =
            builder_.CreateLoad(toLLVMType(*node.type), fieldAddr, node.member);
      }
      return;
    }
  }
  llvm::Value *leftAddr = nullptr;
  // Check if left is a dereference (*ptr).field
  auto *unary = dynamic_cast<sema::BoundUnaryExpression *>(node.left.get());
  if (unary && unary->op == "*") {
    // Evaluate the pointer directly, skip the dereference
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = false;
    unary->expr->accept(*this);
    leftAddr = lastValue_;
    evaluateAsAddr_ = old;
  } else {
    // Normal case: evaluate as address
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = true;
    node.left->accept(*this);
    leftAddr = lastValue_;
    evaluateAsAddr_ = old;
  }
  if (node.left->type->getKind() == zir::TypeKind::TaggedUnion &&
      node.member == "tag") {
    auto taggedUnionType =
        std::static_pointer_cast<zir::TaggedUnionType>(node.left->type);
    auto *structTy = llvm::cast<llvm::StructType>(toLLVMType(*taggedUnionType));
    auto *fieldAddr = builder_.CreateStructGEP(structTy, leftAddr, 0, "tag");
    if (evaluateAsAddr_) {
      lastValue_ = fieldAddr;
    } else {
      lastValue_ =
          builder_.CreateLoad(toLLVMType(*node.type), fieldAddr, node.member);
    }
    return;
  }
  auto recordType = std::static_pointer_cast<zir::RecordType>(node.left->type);
  int fieldIndex = -1;
  const auto &fields = recordType->getFields();
  for (size_t i = 0; i < fields.size(); ++i) {
    if (fields[i].name == node.member) {
      fieldIndex = static_cast<int>(i);
      break;
    }
  }
  if (fieldIndex == -1)
    throw std::runtime_error("Field '" + node.member + "' not found in type '" +
                             node.left->type->toString() + "'");
  llvm::StructType *structTy =
      static_cast<llvm::StructType *>(toLLVMType(*recordType));
  llvm::Value *fieldAddr =
      builder_.CreateStructGEP(structTy, leftAddr, fieldIndex, node.member);
  if (evaluateAsAddr_) {
    lastValue_ = fieldAddr;
  } else {
    lastValue_ =
        builder_.CreateLoad(toLLVMType(*node.type), fieldAddr, node.member);
  }
}
References builder_, zir::Class, evaluateAsAddr_, codegen::kClassFieldStartIndex, lastValue_, sema::BoundMemberAccess::left, sema::BoundMemberAccess::member, zir::Pointer, zir::Record, structCache_, zir::TaggedUnion, toLLVMType(), and sema::BoundExpression::type.
visit() [25/40]
void codegen::LLVMCodeGen::visit (sema::BoundModuleReference & node) override virtual
Implements sema::BoundVisitor.
Definition at line 906 of file llvm_codegen.cpp.
{
  (void)node;
  throw std::runtime_error("module reference reached codegen");
}
visit() [26/40]
void codegen::LLVMCodeGen::visit (sema::BoundNewExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1023 of file llvm_codegen_expr.cpp.
{
  auto *ptrTy = llvm::cast<llvm::PointerType>(toLLVMType(*node.classType));
  auto *objectTy = structCache_.at(node.classType->getCodegenName() + ".obj");
  auto *sizeOfObj = llvm::ConstantExpr::getSizeOf(objectTy);
  auto *sizeTy = llvm::Type::getInt64Ty(ctx_);
  llvm::Value *sizeValue = sizeOfObj;
  if (sizeValue->getType() != sizeTy) {
    sizeValue = builder_.CreateIntCast(sizeValue, sizeTy, /*isSigned=*/false);
  }
  auto mallocIt2 = functionMap_.find("malloc");
  if (mallocIt2 == functionMap_.end()) {
    auto *mallocTy = llvm::FunctionType::get(
        llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)), {sizeTy},
        false);
    auto *mallocFn = llvm::Function::Create(
        mallocTy, llvm::Function::ExternalLinkage, "malloc", *module_);
    mallocIt2 = functionMap_.emplace("malloc", mallocFn).first;
  }
  auto *rawPtr =
      builder_.CreateCall(mallocIt2->second, {sizeValue}, "class.alloc");
  auto *typedPtr = builder_.CreateBitCast(rawPtr, ptrTy, "class.obj");
  auto *refCountAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 0, "refcount.addr");
  builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_), 1),
                       refCountAddr);
  auto *weakCountAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 1, "weakcount.addr");
  builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt64Ty(ctx_), 0),
                       weakCountAddr);
  auto *aliveAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 2, "alive.addr");
  builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt8Ty(ctx_), 1),
                       aliveAddr);
  auto *gcMarkAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 3, "gcmark.addr");
  builder_.CreateStore(llvm::ConstantInt::get(llvm::Type::getInt8Ty(ctx_), 0),
                       gcMarkAddr);
  auto *releaseFnAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 4, "release.fn.addr");
  auto *releaseFnPtr = builder_.CreateBitCast(
      classReleaseFns_.at(node.classType->getName()),
      llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
  builder_.CreateStore(releaseFnPtr, releaseFnAddr);
  auto *destroyFnAddr =
      builder_.CreateStructGEP(objectTy, typedPtr, 5, "destroy.fn.addr");
  auto *destroyFnPtr = builder_.CreateBitCast(
      classDestroyFns_.at(node.classType->getName()),
      llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
  builder_.CreateStore(destroyFnPtr, destroyFnAddr);
  auto *metadataAddr = builder_.CreateStructGEP(
      objectTy, typedPtr, kClassMetadataIndex, "metadata.addr");
  auto *metadataPtr = builder_.CreateBitCast(
      classMetadataGlobals_.at(node.classType->getName()),
      llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_)));
  builder_.CreateStore(metadataPtr, metadataAddr);
  auto *vtableAddr = builder_.CreateStructGEP(objectTy, typedPtr,
                                              kClassVTableIndex, "vtable.addr");
  auto *i8PtrTy = llvm::PointerType::getUnqual(llvm::Type::getInt8Ty(ctx_));
  auto *vtablePtrTy = llvm::PointerType::getUnqual(i8PtrTy);
  auto *vtableGlobal = classVTables_.at(node.classType->getName());
  auto *zero = llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), 0);
  llvm::Constant *vtableIndices[] = {zero, zero};
  auto *vtablePtr = llvm::ConstantExpr::getInBoundsGetElementPtr(
      vtableGlobal->getValueType(), vtableGlobal, vtableIndices);
  builder_.CreateStore(llvm::ConstantExpr::getBitCast(vtablePtr, vtablePtrTy),
                       vtableAddr);
  for (size_t i = 0; i < node.classType->getFields().size(); ++i) {
    auto *fieldAddr = builder_.CreateStructGEP(
        objectTy, typedPtr, static_cast<unsigned>(i + kClassFieldStartIndex));
    builder_.CreateStore(llvm::Constant::getNullValue(
                             toLLVMType(*node.classType->getFields()[i].type)),
                         fieldAddr);
  }
  if (node.constructor) {
    auto *callee = functionMap_.at(node.constructor->linkName);
    std::vector<llvm::Value *> args;
    args.push_back(typedPtr);
    for (size_t i = 0; i < node.arguments.size(); ++i) {
      bool old = evaluateAsAddr_;
      if (i < node.argumentIsRef.size() && node.argumentIsRef[i])
        evaluateAsAddr_ = true;
      node.arguments[i]->accept(*this);
      args.push_back(lastValue_);
      evaluateAsAddr_ = old;
    }
    builder_.CreateCall(callee, args);
  }
  lastValue_ = typedPtr;
}
References sema::BoundNewExpression::argumentIsRef, sema::BoundNewExpression::arguments, builder_, classDestroyFns_, classMetadataGlobals_, classReleaseFns_, sema::BoundNewExpression::classType, classVTables_, sema::BoundNewExpression::constructor, ctx_, evaluateAsAddr_, functionMap_, codegen::kClassFieldStartIndex, codegen::kClassMetadataIndex, codegen::kClassVTableIndex, lastValue_, module_, structCache_, and toLLVMType().
visit() [27/40]
void codegen::LLVMCodeGen::visit (sema::BoundRecordDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1088 of file llvm_codegen.cpp.
{
  toLLVMType(*node.type);
}
References toLLVMType(), and sema::BoundRecordDeclaration::type.
visit() [28/40]
void codegen::LLVMCodeGen::visit (sema::BoundReturnStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 997 of file llvm_codegen.cpp.
{
  if (node.expression) {
    node.expression->accept(*this);
    if (isClassType(node.expression->type) &&
        !expressionProducesOwnedClass(node.expression.get())) {
      emitRetainIfNeeded(lastValue_, node.expression->type);
    } else if (isOwnedStringType(node.expression->type) &&
               !expressionProducesOwnedString(node.expression.get())) {
      lastValue_ = emitStringRetainIfNeeded(lastValue_, node.expression->type);
    }
    for (auto it = scopeClassLocals_.rbegin(); it != scopeClassLocals_.rend();
         ++it) {
      for (auto local = it->rbegin(); local != it->rend(); ++local) {
        auto *value = builder_.CreateLoad(toLLVMType(*local->first),
                                          local->second, "arc.ret.release");
        if (isWeakClassType(local->first))
          emitReleaseWeakIfNeeded(value, local->first);
        else
          emitReleaseIfNeeded(value, local->first);
      }
    }
    for (auto it = scopeStringLocals_.rbegin(); it != scopeStringLocals_.rend();
         ++it) {
      for (auto local = it->rbegin(); local != it->rend(); ++local) {
        auto *value = builder_.CreateLoad(toLLVMType(*local->first),
                                          local->second, "str.ret.release");
        emitStringReleaseIfNeeded(value, local->first);
      }
    }
    builder_.CreateRet(lastValue_);
  } else {
    for (auto it = scopeClassLocals_.rbegin(); it != scopeClassLocals_.rend();
         ++it) {
      for (auto local = it->rbegin(); local != it->rend(); ++local) {
        auto *value = builder_.CreateLoad(toLLVMType(*local->first),
                                          local->second, "arc.ret.release");
        if (isWeakClassType(local->first))
          emitReleaseWeakIfNeeded(value, local->first);
        else
          emitReleaseIfNeeded(value, local->first);
      }
    }
    for (auto it = scopeStringLocals_.rbegin(); it != scopeStringLocals_.rend();
         ++it) {
      for (auto local = it->rbegin(); local != it->rend(); ++local) {
        auto *value = builder_.CreateLoad(toLLVMType(*local->first),
                                          local->second, "str.ret.release");
        emitStringReleaseIfNeeded(value, local->first);
      }
    }
    builder_.CreateRetVoid();
  }
}
References builder_, emitReleaseIfNeeded(), emitReleaseWeakIfNeeded(), emitRetainIfNeeded(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), sema::BoundReturnStatement::expression, expressionProducesOwnedClass(), expressionProducesOwnedString(), isClassType(), isOwnedStringType(), isWeakClassType(), lastValue_, scopeClassLocals_, scopeStringLocals_, and toLLVMType().
visit() [29/40]
void codegen::LLVMCodeGen::visit (sema::BoundRootNode & node) override virtual
Implements sema::BoundVisitor.
Definition at line 681 of file llvm_codegen.cpp.
{
  for (const auto &extFn : node.externalFunctions) {
    auto *ft = buildFunctionType(*extFn->symbol);
    auto *f = llvm::Function::Create(ft, llvm::Function::ExternalLinkage,
                                     extFn->symbol->linkName, *module_);
    auto argIt = f->arg_begin();
    for (const auto &param : extFn->symbol->parameters) {
      if (param->is_variadic_pack) {
        argIt->setName(param->name + ".count");
        ++argIt;
        argIt->setName(param->name + ".data");
        ++argIt;
        continue;
      }
      argIt->setName(param->name);
      ++argIt;
    }
    functionMap_[extFn->symbol->linkName] = f;
  }
  for (const auto &fn : node.functions) {
    bool isEntryMain = !freestanding_ && fn->symbol->linkName == "main";
    auto *ft = buildFunctionType(*fn->symbol, isEntryMain);
    auto *f = llvm::Function::Create(ft, llvm::Function::ExternalLinkage,
                                     fn->symbol->linkName, *module_);
    auto argIt = f->arg_begin();
    if (isEntryMain) {
      argIt->setName("argc");
      ++argIt;
      argIt->setName("argv");
      ++argIt;
    }
    for (const auto &param : fn->symbol->parameters) {
      if (param->is_variadic_pack) {
        argIt->setName(param->name + ".count");
        ++argIt;
        argIt->setName(param->name + ".data");
        ++argIt;
        continue;
      }
      argIt->setName(param->name);
      ++argIt;
    }
    functionMap_[fn->symbol->linkName] = f;
    if (fn->symbol->isDestructor) {
      classDestructorFns_[fn->symbol->ownerTypeName] = f;
    }
    if (fn->symbol->vtableSlot >= 0) {
      classVirtualMethodFns_[fn->symbol->ownerTypeName]
                            [fn->symbol->vtableSlot] = f;
    }
  }
  for (const auto &rec : node.records) {
    if (rec->type && rec->type->getKind() == zir::TypeKind::Class) {
      ensureClassArcSupport(
          std::static_pointer_cast<zir::ClassType>(rec->type));
    }
  }
  for (const auto &global : node.globals)
    global->accept(*this);
  for (const auto &fn : node.functions)
    fn->accept(*this);
  for (const auto &rec : node.records)
    rec->accept(*this);
  for (const auto &en : node.enums)
    en->accept(*this);
  for (const auto &taggedUnion : node.taggedUnions)
    taggedUnion->accept(*this);
}
References buildFunctionType(), zir::Class, classDestructorFns_, classVirtualMethodFns_, ensureClassArcSupport(), sema::BoundRootNode::enums, sema::BoundRootNode::externalFunctions, freestanding_, functionMap_, sema::BoundRootNode::functions, sema::BoundRootNode::globals, module_, sema::BoundRootNode::records, and sema::BoundRootNode::taggedUnions.
visit() [30/40]
void codegen::LLVMCodeGen::visit (sema::BoundStructLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 964 of file llvm_codegen_expr.cpp.
{
  auto recordType = std::static_pointer_cast<zir::RecordType>(node.type);
  llvm::StructType *structTy =
      static_cast<llvm::StructType *>(toLLVMType(*recordType));
  // Create an alloca for the struct
  llvm::Value *structAddr =
      createEntryAlloca(currentFn_, "struct_literal", structTy);
  for (const auto &fieldInit : node.fields) {
    // Find field index
    int fieldIndex = -1;
    const auto &fields = recordType->getFields();
    for (size_t i = 0; i < fields.size(); ++i) {
      if (fields[i].name == fieldInit.first) {
        fieldIndex = static_cast<int>(i);
        break;
      }
    }
    fieldInit.second->accept(*this);
    llvm::Value *val = lastValue_;
    llvm::Value *fieldAddr =
        builder_.CreateStructGEP(structTy, structAddr, fieldIndex);
    builder_.CreateStore(val, fieldAddr);
  }
  if (evaluateAsAddr_) {
    lastValue_ = structAddr;
  } else {
    lastValue_ = builder_.CreateLoad(structTy, structAddr);
  }
}
References builder_, createEntryAlloca(), currentFn_, evaluateAsAddr_, sema::BoundStructLiteral::fields, lastValue_, toLLVMType(), and sema::BoundExpression::type.
visit() [31/40]
void codegen::LLVMCodeGen::visit (sema::BoundTaggedUnionDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1099 of file llvm_codegen.cpp.
{
  toLLVMType(*node.type);
}
References toLLVMType(), and sema::BoundTaggedUnionDeclaration::type.
visit() [32/40]
void codegen::LLVMCodeGen::visit (sema::BoundTaggedUnionLiteral & node) override virtual
Implements sema::BoundVisitor.
Definition at line 999 of file llvm_codegen_expr.cpp.
{
  auto taggedUnionType =
      std::static_pointer_cast<zir::TaggedUnionType>(node.type);
  auto *structTy = llvm::cast<llvm::StructType>(toLLVMType(*taggedUnionType));
  auto *addr = createEntryAlloca(currentFn_, "tagged_union_literal", structTy);
  auto *tagAddr = builder_.CreateStructGEP(structTy, addr, 0, "tag.addr");
  builder_.CreateStore(
      llvm::ConstantInt::get(llvm::Type::getInt32Ty(ctx_), node.tag), tagAddr);
  if (node.payload) {
    node.payload->accept(*this);
    auto *payloadAddr =
        builder_.CreateStructGEP(structTy, addr, 1, "payload.addr");
    builder_.CreateStore(lastValue_, payloadAddr);
  }
  if (evaluateAsAddr_) {
    lastValue_ = addr;
  } else {
    lastValue_ = builder_.CreateLoad(structTy, addr, "tagged_union");
  }
}
References builder_, createEntryAlloca(), ctx_, currentFn_, evaluateAsAddr_, lastValue_, sema::BoundTaggedUnionLiteral::payload, sema::BoundTaggedUnionLiteral::tag, toLLVMType(), and sema::BoundExpression::type.
visit() [33/40]
void codegen::LLVMCodeGen::visit (sema::BoundTernaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 422 of file llvm_codegen_expr.cpp.
{
  auto *thenBB = llvm::BasicBlock::Create(ctx_, "ternary.then", currentFn_);
  auto *elseBB = llvm::BasicBlock::Create(ctx_, "ternary.else", currentFn_);
  auto *mergeBB = llvm::BasicBlock::Create(ctx_, "ternary.merge", currentFn_);
  node.condition->accept(*this);
  auto *cond = lastValue_;
  builder_.CreateCondBr(cond, thenBB, elseBB);
  builder_.SetInsertPoint(thenBB);
  node.thenExpr->accept(*this);
  auto *thenVal = lastValue_;
  auto *actualThenBB = builder_.GetInsertBlock();
  builder_.CreateBr(mergeBB);
  builder_.SetInsertPoint(elseBB);
  node.elseExpr->accept(*this);
  auto *elseVal = lastValue_;
  auto *actualElseBB = builder_.GetInsertBlock();
  builder_.CreateBr(mergeBB);
  builder_.SetInsertPoint(mergeBB);
  auto *phiType = toLLVMType(*node.type);
  auto *phi = builder_.CreatePHI(phiType, 2, "ternary.res");
  phi->addIncoming(thenVal, actualThenBB);
  phi->addIncoming(elseVal, actualElseBB);
  lastValue_ = phi;
}
References builder_, sema::BoundTernaryExpression::condition, ctx_, currentFn_, sema::BoundTernaryExpression::elseExpr, lastValue_, sema::BoundTernaryExpression::thenExpr, toLLVMType(), and sema::BoundExpression::type.
visit() [34/40]
void codegen::LLVMCodeGen::visit (sema::BoundTryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1129 of file llvm_codegen_expr.cpp.
{
  (void)node;
  throw std::runtime_error(
      "BoundTryExpression should be lowered to ZIR before LLVMCodeGen.");
}
visit() [35/40]
void codegen::LLVMCodeGen::visit (sema::BoundUnaryExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 451 of file llvm_codegen_expr.cpp.
{
  if (node.op == "&") {
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = true;
    node.expr->accept(*this);
    evaluateAsAddr_ = old;
    return;
  } else if (node.op == "*") {
    bool old = evaluateAsAddr_;
    evaluateAsAddr_ = false;
    node.expr->accept(*this);
    evaluateAsAddr_ = old;
    auto *ptr = lastValue_;
    if (evaluateAsAddr_) {
      lastValue_ = ptr;
    } else {
      lastValue_ = builder_.CreateLoad(toLLVMType(*node.type), ptr, "deref");
    }
    return;
  }
  node.expr->accept(*this);
  if (node.op == "-") {
    lastValue_ = node.type->isFloatingPoint() ? builder_.CreateFNeg(lastValue_)
                                              : builder_.CreateNeg(lastValue_);
  } else if (node.op == "!") {
    lastValue_ = builder_.CreateNot(lastValue_);
  } else if (node.op == "~") {
    if (!node.type->isInteger()) {
      throw std::runtime_error("Unary '~' requires integer operand");
    }
    lastValue_ = builder_.CreateNot(lastValue_);
  }
}
References builder_, evaluateAsAddr_, sema::BoundUnaryExpression::expr, lastValue_, sema::BoundUnaryExpression::op, toLLVMType(), and sema::BoundExpression::type.
visit() [36/40]
void codegen::LLVMCodeGen::visit (sema::BoundVariableDeclaration & node) override virtual
Implements sema::BoundVisitor.
Definition at line 934 of file llvm_codegen.cpp.
{
  auto *ty = toLLVMType(*node.symbol->type);
  if (currentFn_) {
    if (node.symbol->is_ref) {
      // Ref var: alloca a pointer slot, store the address of the initializer
      auto *ptrTy = llvm::PointerType::getUnqual(ty);
      auto *alloca = createEntryAlloca(currentFn_, node.symbol->name, ptrTy);
      localValues_[node.symbol->name] = alloca;
      if (node.initializer) {
        bool old = evaluateAsAddr_;
        evaluateAsAddr_ = true;
        node.initializer->accept(*this);
        evaluateAsAddr_ = old;
        builder_.CreateStore(lastValue_, alloca);
      }
      return;
    }
    auto *alloca = createEntryAlloca(currentFn_, node.symbol->name, ty);
    localValues_[node.symbol->name] = alloca;
    if (isClassType(node.symbol->type) ||
        isOwnedStringType(node.symbol->type)) {
      builder_.CreateStore(llvm::Constant::getNullValue(ty), alloca);
    }
    if (node.initializer) {
      node.initializer->accept(*this);
      if (isOwnedStringType(node.symbol->type)) {
        emitStoreWithStringArc(
            alloca, lastValue_, node.symbol->type,
            expressionProducesOwnedString(node.initializer.get()));
      } else {
        emitStoreWithArc(alloca, lastValue_, node.symbol->type,
                         expressionProducesOwnedClass(node.initializer.get()));
      }
    }
    if (isClassType(node.symbol->type) && !scopeClassLocals_.empty()) {
      scopeClassLocals_.back().push_back({node.symbol->type, alloca});
    } else if (isOwnedStringType(node.symbol->type) &&
               !scopeStringLocals_.empty()) {
      scopeStringLocals_.back().push_back({node.symbol->type, alloca});
    }
  } else {
    llvm::Constant *initializer = nullptr;
    if (node.initializer) {
      node.initializer->accept(*this);
      initializer = llvm::dyn_cast<llvm::Constant>(lastValue_);
    }
    if (!initializer) {
      // If no initializer or initializer is not a constant, use null
      // initializer
      initializer = llvm::Constant::getNullValue(ty);
    }
    auto *gv = new llvm::GlobalVariable(*module_, ty, node.symbol->is_const,
                                        llvm::GlobalVariable::ExternalLinkage,
                                        initializer, node.symbol->linkName);
    globalValues_[node.symbol->linkName] = gv;
  }
}
References builder_, createEntryAlloca(), currentFn_, emitStoreWithArc(), emitStoreWithStringArc(), evaluateAsAddr_, expressionProducesOwnedClass(), expressionProducesOwnedString(), globalValues_, sema::BoundVariableDeclaration::initializer, isClassType(), isOwnedStringType(), lastValue_, localValues_, module_, scopeClassLocals_, scopeStringLocals_, sema::BoundVariableDeclaration::symbol, and toLLVMType().
visit() [37/40]
void codegen::LLVMCodeGen::visit (sema::BoundVariableExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 240 of file llvm_codegen_expr.cpp.
{
  llvm::Value *addr = nullptr;
  auto localIt = localValues_.find(node.symbol->name);
  if (localIt != localValues_.end()) {
    addr = localIt->second;
  } else {
    addr = globalValues_.at(node.symbol->linkName);
  }
  if (node.symbol->is_ref) {
    // addr is a pointer to the pointer passed as argument
    auto *ptrTy = llvm::PointerType::getUnqual(toLLVMType(*node.symbol->type));
    addr = builder_.CreateLoad(ptrTy, addr, node.symbol->name + ".ptr");
  }
  if (evaluateAsAddr_) {
    lastValue_ = addr;
  } else {
    auto *ty = toLLVMType(*node.symbol->type);
    lastValue_ = builder_.CreateLoad(ty, addr, node.symbol->name);
  }
}
References builder_, evaluateAsAddr_, globalValues_, lastValue_, localValues_, sema::BoundVariableExpression::symbol, and toLLVMType().
visit() [38/40]
void codegen::LLVMCodeGen::visit (sema::BoundWeakAliveExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1124 of file llvm_codegen_expr.cpp.
{
  node.weakExpression->accept(*this);
  lastValue_ = emitWeakAlive(lastValue_, node.weakExpression->type);
}
References emitWeakAlive(), lastValue_, and sema::BoundWeakAliveExpression::weakExpression.
visit() [39/40]
void codegen::LLVMCodeGen::visit (sema::BoundWeakLockExpression & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1119 of file llvm_codegen_expr.cpp.
{
  node.weakExpression->accept(*this);
  lastValue_ = emitWeakLock(lastValue_, node.weakExpression->type);
}
References emitWeakLock(), lastValue_, and sema::BoundWeakLockExpression::weakExpression.
visit() [40/40]
void codegen::LLVMCodeGen::visit (sema::BoundWhileStatement & node) override virtual
Implements sema::BoundVisitor.
Definition at line 1159 of file llvm_codegen.cpp.
{
  if (!currentFn_)
    throw std::runtime_error(
        "currentFn_ is null in visit(BoundWhileStatement)");
  auto *condBB = llvm::BasicBlock::Create(ctx_, "while.cond", currentFn_);
  auto *bodyBB = llvm::BasicBlock::Create(ctx_, "while.body", currentFn_);
  auto *endBB = llvm::BasicBlock::Create(ctx_, "while.end", currentFn_);
  builder_.CreateBr(condBB);
  builder_.SetInsertPoint(condBB);
  if (!node.condition)
    throw std::runtime_error("condition is null in BoundWhileStatement");
  node.condition->accept(*this);
  auto *cond = lastValue_;
  if (!cond)
    throw std::runtime_error(
        "lastValue_ is null after condition in BoundWhileStatement");
  builder_.CreateCondBr(cond, bodyBB, endBB);
  builder_.SetInsertPoint(bodyBB);
  loopBBStack_.push_back({condBB, endBB});
  if (node.body)
    node.body->accept(*this);
  loopBBStack_.pop_back();
  if (!builder_.GetInsertBlock()->getTerminator()) {
    builder_.CreateBr(condBB);
  }
  builder_.SetInsertPoint(endBB);
}
References sema::BoundWhileStatement::body, builder_, sema::BoundWhileStatement::condition, ctx_, currentFn_, lastValue_, and loopBBStack_.
Friends And Related Symbol Documentation
ClassArcEmitter
friend class ClassArcEmitter friend
Definition at line 191 of file llvm_codegen.hpp.
References ClassArcEmitter.
Referenced by ClassArcEmitter, and LLVMCodeGen().
Member Data Documentation
arcEmitter_
std::unique_ptr<ClassArcEmitter> codegen::LLVMCodeGen::arcEmitter_ private
Definition at line 102 of file llvm_codegen.hpp.
Referenced by emitReleaseIfNeeded(), emitReleaseWeakIfNeeded(), emitRetainIfNeeded(), emitRetainWeakIfNeeded(), emitScopeReleases(), emitStoreWithArc(), emitWeakAlive(), emitWeakLock(), ensureArcSupport(), ensureClassArcSupport(), expressionProducesOwnedClass(), isClassType(), isWeakClassType(), and LLVMCodeGen().
builder_
llvm::IRBuilder codegen::LLVMCodeGen::builder_ private
Definition at line 75 of file llvm_codegen.hpp.
Referenced by buildInlineAsmCall(), emitScopeReleases(), emitStoreWithStringArc(), emitStringConcat(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), emitZIRFunction(), emitZIRInstruction(), LLVMCodeGen(), lowerZIRCast(), lowerZIRRValue(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
classDestroyFns_
std::map<std::string, llvm::Function *> codegen::LLVMCodeGen::classDestroyFns_ private
Definition at line 94 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), and visit().
classDestructorFns_
std::map<std::string, llvm::Function *> codegen::LLVMCodeGen::classDestructorFns_ private
Definition at line 95 of file llvm_codegen.hpp.
Referenced by generate(), and visit().
classMetadataGlobals_
std::map<std::string, llvm::GlobalVariable *> codegen::LLVMCodeGen::classMetadataGlobals_ private
Definition at line 96 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), and visit().
classReleaseFns_
std::map<std::string, llvm::Function *> codegen::LLVMCodeGen::classReleaseFns_ private
Definition at line 93 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), and visit().
classRetainFns_
std::map<std::string, llvm::Function *> codegen::LLVMCodeGen::classRetainFns_ private
Definition at line 92 of file llvm_codegen.hpp.
classVirtualMethodFns_
std::map<std::string, std::map<int, llvm::Function *> > codegen::LLVMCodeGen::classVirtualMethodFns_ private
Definition at line 90 of file llvm_codegen.hpp.
Referenced by generate(), and visit().
classVTables_
std::map<std::string, llvm::GlobalVariable *> codegen::LLVMCodeGen::classVTables_ private
Definition at line 91 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), and visit().
compoundTargetAddr_
llvm::Value* codegen::LLVMCodeGen::compoundTargetAddr_ = nullptr private
Definition at line 83 of file llvm_codegen.hpp.
Referenced by visit(), and visit().
ctx_
llvm::LLVMContext codegen::LLVMCodeGen::ctx_ private
Definition at line 74 of file llvm_codegen.hpp.
Referenced by buildFunctionType(), buildFunctionType(), buildInlineAsmCall(), emitStringConcat(), emitStringReleaseIfNeeded(), emitZIRFunction(), emitZIRInstruction(), finalizeClassStruct(), generate(), getOrCreateClassStruct(), getOrCreateGlobalString(), initializeModule(), LLVMCodeGen(), lowerZIRCast(), lowerZIRConstant(), toLLVMAggregateFieldType(), toLLVMType(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
currentFn_
llvm::Function* codegen::LLVMCodeGen::currentFn_ = nullptr private
Definition at line 80 of file llvm_codegen.hpp.
Referenced by emitStringConcat(), emitZIRFunction(), emitZIRInstruction(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
currentZIRFunction_
const zir::Function* codegen::LLVMCodeGen::currentZIRFunction_ = nullptr private
Definition at line 115 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
cyclicClasses_
std::unordered_set<std::string> codegen::LLVMCodeGen::cyclicClasses_ private
Definition at line 97 of file llvm_codegen.hpp.
Referenced by computeCyclicClasses().
evaluateAsAddr_
bool codegen::LLVMCodeGen::evaluateAsAddr_ = false private
Definition at line 82 of file llvm_codegen.hpp.
Referenced by LLVMCodeGen(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
freestanding_
bool codegen::LLVMCodeGen::freestanding_ = false private
Definition at line 78 of file llvm_codegen.hpp.
Referenced by buildFunctionType(), emitZIRFunction(), LLVMCodeGen(), visit(), and visit().
functionMap_
std::map<std::string, llvm::Function *> codegen::LLVMCodeGen::functionMap_ private
Definition at line 87 of file llvm_codegen.hpp.
Referenced by declareZIRFunction(), emitStringConcat(), emitZIRFunction(), emitZIRInstruction(), generate(), lowerZIRValue(), visit(), visit(), visit(), visit(), and visit().
globalValues_
std::map<std::string, llvm::GlobalVariable *> codegen::LLVMCodeGen::globalValues_ private
Definition at line 86 of file llvm_codegen.hpp.
Referenced by generate(), lowerZIRValue(), visit(), and visit().
lastValue_
llvm::Value* codegen::LLVMCodeGen::lastValue_ = nullptr private
Definition at line 81 of file llvm_codegen.hpp.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
localValues_
std::map<std::string, llvm::Value *> codegen::LLVMCodeGen::localValues_ private
Definition at line 85 of file llvm_codegen.hpp.
Referenced by visit(), visit(), and visit().
loopBBStack_
std::vector<std::pair<llvm::BasicBlock *, llvm::BasicBlock *> > codegen::LLVMCodeGen::loopBBStack_ private
Definition at line 123 of file llvm_codegen.hpp.
Referenced by visit(), visit(), visit(), and visit().
module_
std::unique_ptr<llvm::Module> codegen::LLVMCodeGen::module_ private
Definition at line 76 of file llvm_codegen.hpp.
Referenced by buildInlineAsmCall(), declareZIRFunction(), emitAssemblyFile(), emitObjectFile(), emitStringConcat(), emitStringReleaseIfNeeded(), emitStringRetainIfNeeded(), emitZIRFunction(), emitZIRInstruction(), generate(), getOrCreateGlobalString(), initializeModule(), lowerZIRCast(), lowerZIRConstant(), printIR(), toLLVMType(), visit(), visit(), visit(), visit(), visit(), and visit().
nextStringId_
int codegen::LLVMCodeGen::nextStringId_ = 0 private
Definition at line 118 of file llvm_codegen.hpp.
Referenced by getOrCreateGlobalString(), and LLVMCodeGen().
refReturnValues_
std::unordered_set<const zir::Value *> codegen::LLVMCodeGen::refReturnValues_ private
Definition at line 104 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction().
scopeClassLocals_
std::vector<std::vector<std::pair<std::shared_ptr<zir::Type>, llvm::Value *> > > codegen::LLVMCodeGen::scopeClassLocals_ private
Definition at line 99 of file llvm_codegen.hpp.
Referenced by visit(), visit(), visit(), and visit().
scopeStringLocals_
std::vector<std::vector<std::pair<std::shared_ptr<zir::Type>, llvm::Value *> > > codegen::LLVMCodeGen::scopeStringLocals_ private
Definition at line 101 of file llvm_codegen.hpp.
Referenced by emitScopeReleases(), visit(), visit(), visit(), and visit().
structCache_
std::map<std::string, llvm::StructType *> codegen::LLVMCodeGen::structCache_ private
Definition at line 89 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), getOrCreateClassStruct(), toLLVMType(), visit(), visit(), and visit().
targetTriple_
std::string codegen::LLVMCodeGen::targetTriple_ private
Definition at line 77 of file llvm_codegen.hpp.
Referenced by emitAssemblyFile(), emitObjectFile(), initializeModule(), and LLVMCodeGen().
zirBlockExitMap_
std::unordered_map<std::string, llvm::BasicBlock *> codegen::LLVMCodeGen::zirBlockExitMap_ private
Definition at line 106 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirBlockMap_
std::unordered_map<std::string, llvm::BasicBlock *> codegen::LLVMCodeGen::zirBlockMap_ private
Definition at line 105 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), emitZIRInstruction(), and generate().
zirClassParamAllocas_
std::unordered_set<const zir::Value *> codegen::LLVMCodeGen::zirClassParamAllocas_ private
Definition at line 109 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirFunctionClassLocals_
std::vector<std::pair<std::shared_ptr<zir::Type>, llvm::Value *> > codegen::LLVMCodeGen::zirFunctionClassLocals_ private
Definition at line 112 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirFunctionMap_
std::map<std::string, const zir::Function *> codegen::LLVMCodeGen::zirFunctionMap_ private
Definition at line 88 of file llvm_codegen.hpp.
Referenced by emitZIRInstruction(), generate(), lowerZIRValue(), and visit().
zirFunctionStringLocals_
std::vector<std::pair<std::shared_ptr<zir::Type>, llvm::Value *> > codegen::LLVMCodeGen::zirFunctionStringLocals_ private
Definition at line 114 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirOwnedClassValues_
std::unordered_set<const zir::Value *> codegen::LLVMCodeGen::zirOwnedClassValues_ private
Definition at line 107 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirOwnedStringValues_
std::unordered_set<const zir::Value *> codegen::LLVMCodeGen::zirOwnedStringValues_ private
Definition at line 108 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirParamSpillIndex_
size_t codegen::LLVMCodeGen::zirParamSpillIndex_ = 0 private
Definition at line 116 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirPendingClassParamInitAllocas_
std::unordered_set<const zir::Value *> codegen::LLVMCodeGen::zirPendingClassParamInitAllocas_ private
Definition at line 110 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), and emitZIRInstruction().
zirValueMap_
std::unordered_map<const zir::Value *, llvm::Value *> codegen::LLVMCodeGen::zirValueMap_ private
Definition at line 103 of file llvm_codegen.hpp.
Referenced by emitZIRFunction(), emitZIRInstruction(), generate(), and lowerZIRValue().
The documentation for this class was generated from the following files:
src/codegen/llvm_codegen.hpp
src/codegen/llvm_codegen.cpp
src/codegen/llvm_codegen_arc.cpp
src/codegen/llvm_codegen_constants.cpp
src/codegen/llvm_codegen_expr.cpp
src/codegen/llvm_codegen_zir.cpp