ZAP: ConstInt Class Reference
ConstInt Class Reference
#include <const_int.hpp>
Public Member Functions
ConstInt ()=default
ConstInt (std::string value, std::string typeName="i32")
ConstInt (int64_t value, std::string typeName="i32")
int64_t value () const
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string value_
int64_t value_i64_ = 0
bool has_value_i64_ = false
std::string typeName_ = "i32"
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file const_int.hpp.
Constructor & Destructor Documentation
ConstInt() [1/3]
ConstInt::ConstInt () default
ConstInt() [2/3]
ConstInt::ConstInt (std::string value, std::string typeName = "i32") inline explicit
Definition at line 26 of file const_int.hpp.
      : value_(std::move(value)), typeName_(std::move(typeName)) {}
References typeName_, value(), and value_.
ConstInt() [3/3]
ConstInt::ConstInt (int64_t value, std::string typeName = "i32") inline
Definition at line 30 of file const_int.hpp.
      : value_(std::to_string(value)), value_i64_(value), has_value_i64_(true),
        typeName_(std::move(typeName)) {}
References has_value_i64_, typeName_, value(), value_, and value_i64_.
Member Function Documentation
accept()
void ConstInt::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 38 of file const_int.hpp.
{ v.visit(*this); }
References Visitor::visit().
value()
int64_t ConstInt::value () const inline
Definition at line 36 of file const_int.hpp.
{ return has_value_i64_ ? value_i64_ : 0; }
References has_value_i64_, and value_i64_.
Referenced by ConstInt(), and ConstInt().
Member Data Documentation
has_value_i64_
bool ConstInt::has_value_i64_ = false
Definition at line 18 of file const_int.hpp.
Referenced by ConstInt(), and value().
typeName_
std::string ConstInt::typeName_ = "i32"
Definition at line 21 of file const_int.hpp.
Referenced by ConstInt(), and ConstInt().
value_
std::string ConstInt::value_
Definition at line 12 of file const_int.hpp.
Referenced by ConstInt(), ConstInt(), and sema::Binder::visit().
value_i64_
int64_t ConstInt::value_i64_ = 0
Definition at line 17 of file const_int.hpp.
Referenced by ConstInt(), and value().
The documentation for this class was generated from the following file:
src/ast/const/const_int.hpp