ZAP: ConstDecl Class Reference
ConstDecl Class Reference
#include <const_decl.hpp>
Public Member Functions
ConstDecl () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
ConstDecl (std::string name, std::unique_ptr< TypeNode > type, std::unique_ptr< ExpressionNode > initializer)
void accept (Visitor &v) override
Public Member Functions inherited from StatementNode
virtual ~StatementNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string name_
std::unique_ptr< TypeNode > type_
std::unique_ptr< ExpressionNode > initializer_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file const_decl.hpp.
Constructor & Destructor Documentation
ConstDecl() [1/2]
ConstDecl::ConstDecl () const default noexcept
Referenced by ConstDecl().
ConstDecl() [2/2]
ConstDecl::ConstDecl (std::string name, std::unique_ptr< TypeNode > type, std::unique_ptr< ExpressionNode > initializer) inline
Definition at line 15 of file const_decl.hpp.
      : name_(name), type_(std::move(type)),
        initializer_(std::move(initializer)) {}
References ConstDecl(), initializer_, name_, and type_.
Member Function Documentation
accept()
void ConstDecl::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 20 of file const_decl.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
initializer_
std::unique_ptr<ExpressionNode> ConstDecl::initializer_
Definition at line 12 of file const_decl.hpp.
Referenced by ConstDecl(), and sema::Binder::visit().
name_
std::string ConstDecl::name_
Definition at line 10 of file const_decl.hpp.
Referenced by ConstDecl(), and sema::Binder::visit().
type_
std::unique_ptr<TypeNode> ConstDecl::type_
Definition at line 11 of file const_decl.hpp.
Referenced by ConstDecl(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/const_decl.hpp