ZAP: zir::Type Class Reference
zir::Type Class Reference abstract
#include <type.hpp>
Public Member Functions
virtual ~Type ()=default
virtual TypeKind getKind () const =0
virtual std::string toString () const =0
virtual bool isReferenceType () const
virtual bool isPointerLike () const
virtual bool isInteger () const
virtual bool isUnsigned () const
virtual bool isFloatingPoint () const
Detailed Description
Definition at line 33 of file type.hpp.
Constructor & Destructor Documentation
~Type()
virtual zir::Type::~Type () virtual default
Member Function Documentation
getKind()
virtual TypeKind zir::Type::getKind () const pure virtual
Implemented in zir::ArrayType, zir::ClassType, zir::EnumType, zir::PointerType, zir::PrimitiveType, and zir::RecordType.
Referenced by isFloatingPoint(), isInteger(), isPointerLike(), isUnsigned(), and codegen::LLVMCodeGen::toLLVMType().
isFloatingPoint()
virtual bool zir::Type::isFloatingPoint () const inline virtual
Definition at line 57 of file type.hpp.
{
    auto k = getKind();
    return k == TypeKind::Float || k == TypeKind::Float32 ||
           k == TypeKind::Float64;
  }
References zir::Float, zir::Float32, zir::Float64, and getKind().
isInteger()
virtual bool zir::Type::isInteger () const inline virtual
Definition at line 43 of file type.hpp.
{
    auto k = getKind();
    return k == TypeKind::Int8 || k == TypeKind::Int16 ||
           k == TypeKind::Int32 || k == TypeKind::Int64 ||
           k == TypeKind::UInt8 || k == TypeKind::UInt16 ||
           k == TypeKind::UInt32 || k == TypeKind::UInt64 ||
           k == TypeKind::Int || k == TypeKind::UInt;
  }
References getKind(), zir::Int, zir::Int16, zir::Int32, zir::Int64, zir::Int8, zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, and zir::UInt8.
isPointerLike()
virtual bool zir::Type::isPointerLike () const inline virtual
Definition at line 39 of file type.hpp.
{
    auto k = getKind();
    return k == TypeKind::Pointer || k == TypeKind::NullPtr;
  }
References getKind(), zir::NullPtr, and zir::Pointer.
isReferenceType()
virtual bool zir::Type::isReferenceType () const inline virtual
Reimplemented in zir::ClassType, zir::EnumType, zir::PointerType, and zir::RecordType.
Definition at line 38 of file type.hpp.
{ return false; }
isUnsigned()
virtual bool zir::Type::isUnsigned () const inline virtual
Definition at line 51 of file type.hpp.
{
    auto k = getKind();
    return k == TypeKind::UInt8 || k == TypeKind::UInt16 ||
           k == TypeKind::UInt32 || k == TypeKind::UInt64 ||
           k == TypeKind::UInt;
  }
References getKind(), zir::UInt, zir::UInt16, zir::UInt32, zir::UInt64, and zir::UInt8.
toString()
virtual std::string zir::Type::toString () const pure virtual
Implemented in zir::ArrayType, zir::ClassType, zir::EnumType, zir::PointerType, zir::PrimitiveType, and zir::RecordType.
Referenced by codegen::LLVMCodeGen::toLLVMType().
The documentation for this class was generated from the following file:
src/ir/type.hpp