ZAP: sema::FunctionSymbol Class Reference
sema::FunctionSymbol Class Reference
#include <symbol.hpp>
Public Member Functions
FunctionSymbol (std::string n, std::vector< std::shared_ptr< VariableSymbol > > params, std::shared_ptr< zir::Type > retType, std::string link="", std::string module="", Visibility vis=Visibility::Private, bool unsafe=false, bool cVariadic=false)
SymbolKind getKind () const noexcept override
bool hasVariadicParameter () const
bool acceptsExtraArguments () const
size_t fixedParameterCount () const
std::shared_ptr< VariableSymbol > variadicParameter () const
Public Member Functions inherited from sema::Symbol
virtual ~Symbol () noexcept=default
Public Attributes
std::vector< std::shared_ptr< VariableSymbol > > parameters
std::shared_ptr< zir::Type > returnType
bool isUnsafe = false
bool isCVariadic = false
Public Attributes inherited from sema::Symbol
std::string name
std::string linkName
std::string moduleName
std::shared_ptr< zir::Type > type
Visibility visibility = Visibility::Private
Additional Inherited Members
Protected Member Functions inherited from sema::Symbol
Symbol (std::string n, std::shared_ptr< zir::Type > t, std::string link="", std::string module="", Visibility vis=Visibility::Private)
Detailed Description
Definition at line 48 of file symbol.hpp.
Constructor & Destructor Documentation
FunctionSymbol()
sema::FunctionSymbol::FunctionSymbol (std::string n, std::vector< std::shared_ptr< VariableSymbol > > params, std::shared_ptr< zir::Type > retType, std::string link = "", std::string module = "", Visibility vis = Visibility::Private, bool unsafe = false, bool cVariadic = false) inline
Definition at line 55 of file symbol.hpp.
      : Symbol(std::move(n), nullptr, std::move(link), std::move(module), vis),
        parameters(std::move(params)), returnType(std::move(retType)),
        isUnsafe(unsafe), isCVariadic(cVariadic) {}
References isCVariadic, isUnsafe, parameters, Private, returnType, and sema::Symbol::Symbol().
Member Function Documentation
acceptsExtraArguments()
bool sema::FunctionSymbol::acceptsExtraArguments () const inline
Definition at line 70 of file symbol.hpp.
{
    return hasVariadicParameter() || isCVariadic;
  }
References hasVariadicParameter(), and isCVariadic.
fixedParameterCount()
size_t sema::FunctionSymbol::fixedParameterCount () const inline
Definition at line 74 of file symbol.hpp.
{
    return hasVariadicParameter() ? parameters.size() - 1 : parameters.size();
  }
References hasVariadicParameter(), and parameters.
getKind()
SymbolKind sema::FunctionSymbol::getKind () const inline override virtual noexcept
Implements sema::Symbol.
Definition at line 64 of file symbol.hpp.
{ return SymbolKind::Function; }
References sema::Function.
hasVariadicParameter()
bool sema::FunctionSymbol::hasVariadicParameter () const inline
Definition at line 66 of file symbol.hpp.
{
    return !parameters.empty() && parameters.back()->is_variadic_pack;
  }
References parameters.
Referenced by acceptsExtraArguments(), fixedParameterCount(), and variadicParameter().
variadicParameter()
std::shared_ptr< VariableSymbol > sema::FunctionSymbol::variadicParameter () const inline
Definition at line 78 of file symbol.hpp.
{
    return hasVariadicParameter() ? parameters.back() : nullptr;
  }
References hasVariadicParameter(), and parameters.
Member Data Documentation
isCVariadic
bool sema::FunctionSymbol::isCVariadic = false
Definition at line 53 of file symbol.hpp.
Referenced by acceptsExtraArguments(), codegen::LLVMCodeGen::buildFunctionType(), and FunctionSymbol().
isUnsafe
bool sema::FunctionSymbol::isUnsafe = false
Definition at line 52 of file symbol.hpp.
Referenced by FunctionSymbol().
parameters
std::vector<std::shared_ptr<VariableSymbol> > sema::FunctionSymbol::parameters
Definition at line 50 of file symbol.hpp.
Referenced by codegen::LLVMCodeGen::buildFunctionType(), fixedParameterCount(), FunctionSymbol(), hasVariadicParameter(), and variadicParameter().
returnType
std::shared_ptr<zir::Type> sema::FunctionSymbol::returnType
Definition at line 51 of file symbol.hpp.
Referenced by codegen::LLVMCodeGen::buildFunctionType(), and FunctionSymbol().
The documentation for this class was generated from the following file:
src/sema/symbol.hpp