ZAP: sema::BoundVisitor Class Reference
sema::BoundVisitor Class Reference abstract
#include <bound_nodes.hpp>
Public Member Functions
virtual ~BoundVisitor ()=default
virtual void visit (BoundRootNode &node)=0
virtual void visit (BoundFunctionDeclaration &node)=0
virtual void visit (BoundExternalFunctionDeclaration &node)=0
virtual void visit (BoundBlock &node)=0
virtual void visit (BoundVariableDeclaration &node)=0
virtual void visit (BoundReturnStatement &node)=0
virtual void visit (BoundAssignment &node)=0
virtual void visit (BoundExpressionStatement &node)=0
virtual void visit (BoundLiteral &node)=0
virtual void visit (BoundVariableExpression &node)=0
virtual void visit (BoundBinaryExpression &node)=0
virtual void visit (BoundUnaryExpression &node)=0
virtual void visit (BoundFunctionCall &node)=0
virtual void visit (BoundArrayLiteral &node)=0
virtual void visit (BoundIndexAccess &node)=0
virtual void visit (BoundRecordDeclaration &node)=0
virtual void visit (BoundEnumDeclaration &node)=0
virtual void visit (BoundMemberAccess &node)=0
virtual void visit (BoundStructLiteral &node)=0
virtual void visit (BoundIfExpression &node)=0
virtual void visit (BoundWhileStatement &node)=0
virtual void visit (BoundBreakStatement &node)=0
virtual void visit (BoundContinueStatement &node)=0
Detailed Description
Definition at line 36 of file bound_nodes.hpp.
Constructor & Destructor Documentation
~BoundVisitor()
virtual sema::BoundVisitor::~BoundVisitor () virtual default
Member Function Documentation
visit() [1/23]
virtual void sema::BoundVisitor::visit (BoundArrayLiteral & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [2/23]
virtual void sema::BoundVisitor::visit (BoundAssignment & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [3/23]
virtual void sema::BoundVisitor::visit (BoundBinaryExpression & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [4/23]
virtual void sema::BoundVisitor::visit (BoundBlock & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [5/23]
virtual void sema::BoundVisitor::visit (BoundBreakStatement & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [6/23]
virtual void sema::BoundVisitor::visit (BoundContinueStatement & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [7/23]
virtual void sema::BoundVisitor::visit (BoundEnumDeclaration & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [8/23]
virtual void sema::BoundVisitor::visit (BoundExpressionStatement & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [9/23]
virtual void sema::BoundVisitor::visit (BoundExternalFunctionDeclaration & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [10/23]
virtual void sema::BoundVisitor::visit (BoundFunctionCall & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [11/23]
virtual void sema::BoundVisitor::visit (BoundFunctionDeclaration & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [12/23]
virtual void sema::BoundVisitor::visit (BoundIfExpression & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [13/23]
virtual void sema::BoundVisitor::visit (BoundIndexAccess & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [14/23]
virtual void sema::BoundVisitor::visit (BoundLiteral & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [15/23]
virtual void sema::BoundVisitor::visit (BoundMemberAccess & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [16/23]
virtual void sema::BoundVisitor::visit (BoundRecordDeclaration & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [17/23]
virtual void sema::BoundVisitor::visit (BoundReturnStatement & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [18/23]
virtual void sema::BoundVisitor::visit (BoundRootNode & node) pure virtual
Implemented in zir::BoundIRGenerator.
Referenced by sema::BoundArrayLiteral::accept(), sema::BoundAssignment::accept(), sema::BoundBinaryExpression::accept(), sema::BoundBlock::accept(), sema::BoundBreakStatement::accept(), sema::BoundContinueStatement::accept(), sema::BoundEnumDeclaration::accept(), sema::BoundExpressionStatement::accept(), sema::BoundExternalFunctionDeclaration::accept(), sema::BoundFunctionCall::accept(), sema::BoundFunctionDeclaration::accept(), sema::BoundIfExpression::accept(), sema::BoundIndexAccess::accept(), sema::BoundLiteral::accept(), sema::BoundMemberAccess::accept(), sema::BoundRecordDeclaration::accept(), sema::BoundReturnStatement::accept(), sema::BoundRootNode::accept(), sema::BoundStructLiteral::accept(), sema::BoundUnaryExpression::accept(), sema::BoundVariableDeclaration::accept(), sema::BoundVariableExpression::accept(), and sema::BoundWhileStatement::accept().
visit() [19/23]
virtual void sema::BoundVisitor::visit (BoundStructLiteral & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [20/23]
virtual void sema::BoundVisitor::visit (BoundUnaryExpression & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [21/23]
virtual void sema::BoundVisitor::visit (BoundVariableDeclaration & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [22/23]
virtual void sema::BoundVisitor::visit (BoundVariableExpression & node) pure virtual
Implemented in zir::BoundIRGenerator.
visit() [23/23]
virtual void sema::BoundVisitor::visit (BoundWhileStatement & node) pure virtual
Implemented in zir::BoundIRGenerator.
The documentation for this class was generated from the following file:
src/sema/bound_nodes.hpp