ZAP: sema::Symbol Class Reference
sema::Symbol Class Reference abstract
#include <symbol.hpp>
Public Member Functions
virtual ~Symbol () noexcept=default
virtual SymbolKind getKind () const noexcept=0
Public Attributes
std::string name
std::shared_ptr< zir::Type > type
Protected Member Functions
Symbol (std::string n, std::shared_ptr< zir::Type > t)
Detailed Description
Definition at line 13 of file symbol.hpp.
Constructor & Destructor Documentation
~Symbol()
virtual sema::Symbol::~Symbol () virtual default noexcept
Symbol()
sema::Symbol::Symbol (std::string n, std::shared_ptr< zir::Type > t) inline protected
Definition at line 21 of file symbol.hpp.
      : name(std::move(n)), type(std::move(t)) {}
References name, Symbol(), and type.
Referenced by sema::FunctionSymbol::FunctionSymbol(), Symbol(), sema::TypeSymbol::TypeSymbol(), and sema::VariableSymbol::VariableSymbol().
Member Function Documentation
getKind()
virtual SymbolKind sema::Symbol::getKind () const pure virtual noexcept
Implemented in sema::FunctionSymbol, sema::TypeSymbol, and sema::VariableSymbol.
References getKind().
Referenced by getKind().
Member Data Documentation
name
std::string sema::Symbol::name
Definition at line 15 of file symbol.hpp.
Referenced by Symbol().
type
std::shared_ptr<zir::Type> sema::Symbol::type
Definition at line 16 of file symbol.hpp.
Referenced by Symbol().
The documentation for this class was generated from the following file:
src/sema/symbol.hpp