ZAP: zap::ArgHolder Class Reference
zap::ArgHolder Class Reference
Public Member Functions
ArgHolder (const std::vector< ArgVal > &args)
unsigned count (ArgTypes t) const noexcept
bool has (ArgTypes t) const noexcept
const ArgVal * get (ArgTypes argT) const noexcept
std::vector< const ArgVal * > getAll (ArgTypes argT) const noexcept
Private Attributes
uint16_t _posArray [(unsigned) ArgTypes::ARGS_END] {}
uint16_t _countArray [(unsigned) ArgTypes::ARGS_END] {}
const std::vector< ArgVal > & _args
Detailed Description
Definition at line 455 of file driver.cpp.
Constructor & Destructor Documentation
ArgHolder()
zap::ArgHolder::ArgHolder (const std::vector< ArgVal > & args) inline
Definition at line 461 of file driver.cpp.
                                           : _args(args) {
    unsigned pos = 0;
    for (const ArgVal &arg : _args) {
      unsigned idx = (unsigned)arg.type;
      _posArray[idx] = pos++;
      _countArray[idx]++;
    }
  }
References _args, _countArray, and _posArray.
Member Function Documentation
count()
unsigned zap::ArgHolder::count (ArgTypes t) const inline noexcept
Definition at line 470 of file driver.cpp.
{ return _countArray[(unsigned)t]; }
References _countArray.
Referenced by has().
get()
const ArgVal * zap::ArgHolder::get (ArgTypes argT) const inline noexcept
Definition at line 474 of file driver.cpp.
{
    if (!has(argT))
      return nullptr;
    return &_args[_posArray[(unsigned)argT]];
  }
References _args, _posArray, and has().
Referenced by zap::driver::parseArgs().
getAll()
std::vector< const ArgVal * > zap::ArgHolder::getAll (ArgTypes argT) const inline noexcept
Definition at line 480 of file driver.cpp.
{
    if (!has(argT))
      return {};
    std::vector<const ArgVal *> vec;
    for (const ArgVal &arg : _args) {
      if (arg.type == argT)
        vec.emplace_back(&arg);
    }
    return vec;
  }
References _args, and has().
Referenced by zap::driver::parseArgs().
has()
bool zap::ArgHolder::has (ArgTypes t) const inline noexcept
Definition at line 472 of file driver.cpp.
{ return count(t); }
References count().
Referenced by get(), getAll(), and zap::driver::parseArgs().
Member Data Documentation
_args
const std::vector<ArgVal>& zap::ArgHolder::_args private
Definition at line 458 of file driver.cpp.
Referenced by ArgHolder(), get(), and getAll().
_countArray
uint16_t zap::ArgHolder::_countArray[(unsigned) ArgTypes::ARGS_END] {} private
Definition at line 457 of file driver.cpp.
{};
Referenced by ArgHolder(), and count().
_posArray
uint16_t zap::ArgHolder::_posArray[(unsigned) ArgTypes::ARGS_END] {} private
Definition at line 456 of file driver.cpp.
{};
Referenced by ArgHolder(), and get().
The documentation for this class was generated from the following file:
src/driver/driver.cpp