ZAP: zap::lsp::JsonObject Class Reference
zap::lsp::JsonObject Class Reference
#include <lsp.hpp>
Public Types
enum class ObjectType {
OBJECT_T ,
LIST_T ,
INTEGER_T ,
STRING_T ,
BOOLEAN_T ,
NULL_T
}
using Object = std::unordered_map<std::string, JsonObject>
using List = std::vector<JsonObject>
using Integer = int64_t
using String = std::string
using Boolean = bool
using Null = std::nullptr_t
Public Member Functions
JsonObject () noexcept
JsonObject (Null) noexcept
JsonObject (Boolean boolean) noexcept
JsonObject (Integer integer) noexcept
JsonObject (const char *string)
JsonObject (std::string_view string)
JsonObject (std::string string)
JsonObject (List list)
JsonObject (Object object)
JsonObject (const JsonObject &)=default
JsonObject & operator= (const JsonObject &)=default
JsonObject (JsonObject &&) noexcept=default
JsonObject & operator= (JsonObject &&) noexcept=default
~JsonObject () noexcept=default
ObjectType getType () const noexcept
Object & getAsObject ()
List & getAsList ()
const Object & getAsObject () const
const List & getAsList () const
Integer getAsInteger () const
const String & getAsString () const
Boolean getAsBoolean () const
Null getAsNull () const
bool isObject () const noexcept
bool isList () const noexcept
bool isInteger () const noexcept
bool isString () const noexcept
bool isBoolean () const noexcept
bool isNull () const noexcept
Private Attributes
std::variant< Object, List, Integer, String, Boolean, Null > storage
Detailed Description
Definition at line 13 of file lsp.hpp.
Member Typedef Documentation
Boolean
using zap::lsp::JsonObject::Boolean = bool
Definition at line 19 of file lsp.hpp.
Integer
using zap::lsp::JsonObject::Integer = int64_t
Definition at line 17 of file lsp.hpp.
List
using zap::lsp::JsonObject::List = std::vector<JsonObject>
Definition at line 16 of file lsp.hpp.
Null
using zap::lsp::JsonObject::Null = std::nullptr_t
Definition at line 20 of file lsp.hpp.
Object
using zap::lsp::JsonObject::Object = std::unordered_map<std::string, JsonObject>
Definition at line 15 of file lsp.hpp.
String
using zap::lsp::JsonObject::String = std::string
Definition at line 18 of file lsp.hpp.
Member Enumeration Documentation
ObjectType
enum class zap::lsp::JsonObject::ObjectType strong
Enumerator
OBJECT_T
LIST_T
INTEGER_T
STRING_T
BOOLEAN_T
NULL_T
Definition at line 22 of file lsp.hpp.
{ OBJECT_T, LIST_T, INTEGER_T, STRING_T, BOOLEAN_T, NULL_T };
Constructor & Destructor Documentation
JsonObject() [1/11]
zap::lsp::JsonObject::JsonObject () inline noexcept
Definition at line 28 of file lsp.hpp.
: storage(nullptr) {}
References storage.
Referenced by JsonObject(), JsonObject(), operator=(), operator=(), and ~JsonObject().
JsonObject() [2/11]
zap::lsp::JsonObject::JsonObject (Null) inline noexcept
Definition at line 29 of file lsp.hpp.
: storage(nullptr) {}
JsonObject() [3/11]
zap::lsp::JsonObject::JsonObject (Boolean boolean) inline noexcept
Definition at line 30 of file lsp.hpp.
: storage(boolean) {}
JsonObject() [4/11]
zap::lsp::JsonObject::JsonObject (Integer integer) inline noexcept
Definition at line 31 of file lsp.hpp.
: storage(integer) {}
JsonObject() [5/11]
zap::lsp::JsonObject::JsonObject (const char * string) inline
Definition at line 32 of file lsp.hpp.
: storage(String(string ? string : "")) {}
References storage.
JsonObject() [6/11]
zap::lsp::JsonObject::JsonObject (std::string_view string) inline
Definition at line 33 of file lsp.hpp.
: storage(String(string)) {}
References storage.
JsonObject() [7/11]
zap::lsp::JsonObject::JsonObject (std::string string) inline
Definition at line 34 of file lsp.hpp.
: storage(std::move(string)) {}
References storage.
JsonObject() [8/11]
zap::lsp::JsonObject::JsonObject (List list) inline
Definition at line 35 of file lsp.hpp.
: storage(std::move(list)) {}
References storage.
JsonObject() [9/11]
zap::lsp::JsonObject::JsonObject (Object object) inline
Definition at line 36 of file lsp.hpp.
: storage(std::move(object)) {}
References storage.
JsonObject() [10/11]
zap::lsp::JsonObject::JsonObject (const JsonObject &) default
References JsonObject().
JsonObject() [11/11]
zap::lsp::JsonObject::JsonObject (JsonObject &&) default noexcept
References JsonObject().
~JsonObject()
zap::lsp::JsonObject::~JsonObject () default noexcept
References getAsBoolean(), getAsInteger(), getAsList(), getAsNull(), getAsObject(), getAsString(), getType(), isBoolean(), isInteger(), isList(), isNull(), isObject(), isString(), and JsonObject().
Member Function Documentation
getAsBoolean()
JsonObject::Boolean zap::lsp::JsonObject::getAsBoolean () const
Definition at line 358 of file lsp.cpp.
{ return std::get<Boolean>(storage); }
References storage.
Referenced by zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
getAsInteger()
JsonObject::Integer zap::lsp::JsonObject::getAsInteger () const
Definition at line 356 of file lsp.cpp.
{ return std::get<Integer>(storage); }
References storage.
Referenced by anonymous_namespace{lsp-main.cpp}::getIntegerField(), zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
getAsList() [1/2]
JsonObject::List & zap::lsp::JsonObject::getAsList ()
Definition at line 353 of file lsp.cpp.
{ return std::get<List>(storage); }
References storage.
Referenced by main(), zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
getAsList() [2/2]
const JsonObject::List & zap::lsp::JsonObject::getAsList () const
Definition at line 355 of file lsp.cpp.
{ return std::get<List>(storage); }
References storage.
getAsNull()
JsonObject::Null zap::lsp::JsonObject::getAsNull () const
Definition at line 359 of file lsp.cpp.
{ return std::get<Null>(storage); }
References storage.
Referenced by ~JsonObject().
getAsObject() [1/2]
JsonObject::Object & zap::lsp::JsonObject::getAsObject ()
Definition at line 352 of file lsp.cpp.
{ return std::get<Object>(storage); }
References storage.
Referenced by anonymous_namespace{lsp-main.cpp}::getField(), zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
getAsObject() [2/2]
const JsonObject::Object & zap::lsp::JsonObject::getAsObject () const
Definition at line 354 of file lsp.cpp.
{ return std::get<Object>(storage); }
References storage.
getAsString()
const JsonObject::String & zap::lsp::JsonObject::getAsString () const
Definition at line 357 of file lsp.cpp.
{ return std::get<String>(storage); }
References storage.
Referenced by anonymous_namespace{lsp-main.cpp}::getStringField(), zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonObject(), zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
getType()
JsonObject::ObjectType zap::lsp::JsonObject::getType () const noexcept
Definition at line 343 of file lsp.cpp.
{
  if (isObject()) return ObjectType::OBJECT_T;
  if (isList()) return ObjectType::LIST_T;
  if (isInteger()) return ObjectType::INTEGER_T;
  if (isString()) return ObjectType::STRING_T;
  if (isBoolean()) return ObjectType::BOOLEAN_T;
  return ObjectType::NULL_T;
}
References BOOLEAN_T, INTEGER_T, isBoolean(), isInteger(), isList(), isObject(), isString(), LIST_T, NULL_T, OBJECT_T, and STRING_T.
Referenced by zap::lsp::anonymous_namespace{lsp.cpp}::stringifyJson(), and ~JsonObject().
isBoolean()
bool zap::lsp::JsonObject::isBoolean () const noexcept
Definition at line 364 of file lsp.cpp.
{ return std::holds_alternative<Boolean>(storage); }
References storage.
Referenced by getType(), and ~JsonObject().
isInteger()
bool zap::lsp::JsonObject::isInteger () const noexcept
Definition at line 362 of file lsp.cpp.
{ return std::holds_alternative<Integer>(storage); }
References storage.
Referenced by anonymous_namespace{lsp-main.cpp}::getIntegerField(), getType(), and ~JsonObject().
isList()
bool zap::lsp::JsonObject::isList () const noexcept
Definition at line 361 of file lsp.cpp.
{ return std::holds_alternative<List>(storage); }
References storage.
Referenced by getType(), main(), and ~JsonObject().
isNull()
bool zap::lsp::JsonObject::isNull () const noexcept
Definition at line 365 of file lsp.cpp.
{ return std::holds_alternative<Null>(storage); }
References storage.
Referenced by ~JsonObject().
isObject()
bool zap::lsp::JsonObject::isObject () const noexcept
Definition at line 360 of file lsp.cpp.
{ return std::holds_alternative<Object>(storage); }
References storage.
Referenced by getType(), and ~JsonObject().
isString()
bool zap::lsp::JsonObject::isString () const noexcept
Definition at line 363 of file lsp.cpp.
{ return std::holds_alternative<String>(storage); }
References storage.
Referenced by anonymous_namespace{lsp-main.cpp}::getStringField(), getType(), zap::lsp::anonymous_namespace{lsp.cpp}::parseJsonObject(), and ~JsonObject().
operator=() [1/2]
JsonObject & zap::lsp::JsonObject::operator= (const JsonObject &) default
References JsonObject().
operator=() [2/2]
JsonObject & zap::lsp::JsonObject::operator= (JsonObject &&) default noexcept
References JsonObject().
Member Data Documentation
storage
std::variant<Object, List, Integer, String, Boolean, Null> zap::lsp::JsonObject::storage private
Definition at line 25 of file lsp.hpp.
Referenced by getAsBoolean(), getAsInteger(), getAsList(), getAsList(), getAsNull(), getAsObject(), getAsObject(), getAsString(), isBoolean(), isInteger(), isList(), isNull(), isObject(), isString(), JsonObject(), JsonObject(), JsonObject(), JsonObject(), JsonObject(), and JsonObject().
The documentation for this class was generated from the following files:
src/lsp/lsp.hpp
src/lsp/lsp.cpp