ZAP: AssignNode Class Reference
AssignNode Class Reference
#include <assign_node.hpp>
Public Member Functions
AssignNode () noexcept=default
AssignNode (std::unique_ptr< ExpressionNode > target, std::unique_ptr< ExpressionNode > expr)
void accept (Visitor &v) override
Public Member Functions inherited from StatementNode
virtual ~StatementNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::unique_ptr< ExpressionNode > target_
std::unique_ptr< ExpressionNode > expr_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file assign_node.hpp.
Constructor & Destructor Documentation
AssignNode() [1/2]
AssignNode::AssignNode () default noexcept
Referenced by AssignNode().
AssignNode() [2/2]
AssignNode::AssignNode (std::unique_ptr< ExpressionNode > target, std::unique_ptr< ExpressionNode > expr) inline
Definition at line 14 of file assign_node.hpp.
      : target_(std::move(target)), expr_(std::move(expr)) {}
References AssignNode(), expr_, and target_.
Member Function Documentation
accept()
void AssignNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 17 of file assign_node.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
expr_
std::unique_ptr<ExpressionNode> AssignNode::expr_
Definition at line 11 of file assign_node.hpp.
Referenced by AssignNode(), and sema::Binder::visit().
target_
std::unique_ptr<ExpressionNode> AssignNode::target_
Definition at line 10 of file assign_node.hpp.
Referenced by AssignNode(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/assign_node.hpp