ZAP: zap::frontend Namespace Reference
zap::frontend Namespace Reference
Classes
struct RuntimePaths
Typedefs
using ImportMap = std::unordered_map<std::string, std::string>
Functions
std::optional< std::filesystem::path > currentExecutablePath (const std::filesystem::path &argv0Hint)
std::filesystem::path stdlibRootPath (const RuntimePaths &paths)
std::filesystem::path coreRootPath (const RuntimePaths &paths)
std::filesystem::path stdlibObjectPath (const RuntimePaths &paths)
std::string stripSourceExtension (const std::filesystem::path &path)
static bool importPathMatchesAlias (const std::string &importPath, const std::string &alias)
std::string computeLogicalModulePath (const std::filesystem::path &canonicalPath, const RuntimePaths &paths, const ImportMap &importMap)
bool hasImplicitImport (const RootNode &root, std::string_view path)
void injectImplicitPreludeImportIfNeeded (sema::ModuleInfo &module, bool includePrelude)
static void setImportError (std::string *errorMessage, const std::filesystem::path &path)
bool resolveImportTargets (const std::filesystem::path &modulePath, const ImportNode &importNode, std::vector< std::filesystem::path > &targets, const ImportMap &importMap, const RuntimePaths &paths, std::string *errorMessage)
sema::ResolvedImport makeResolvedImport (const ImportNode &importNode, const std::vector< std::filesystem::path > &targets)
Typedef Documentation
ImportMap
using zap::frontend::ImportMap = std::unordered_map<std::string, std::string>
Definition at line 13 of file module_loader.hpp.
Function Documentation
computeLogicalModulePath()
std::string zap::frontend::computeLogicalModulePath (const std::filesystem::path & canonicalPath, const RuntimePaths & paths, const ImportMap & importMap)
Definition at line 94 of file module_loader.cpp.
{
  auto stdRoot = std::filesystem::weakly_canonical(stdlibRootPath(paths));
  auto coreRoot = std::filesystem::weakly_canonical(coreRootPath(paths));
  auto cwdRoot =
      std::filesystem::weakly_canonical(std::filesystem::current_path());
  auto buildRelative = [&](const std::filesystem::path &root,
                           const std::string &prefix =
                               "") -> std::optional<std::string> {
    auto rootText = root.generic_string();
    auto pathText = canonicalPath.generic_string();
    if (pathText == rootText || pathText.rfind(rootText + "/", 0) != 0) {
      return std::nullopt;
    }
    auto rel = std::filesystem::relative(canonicalPath, root);
    auto stripped = stripSourceExtension(rel);
    if (prefix.empty()) {
      return stripped;
    }
    return prefix + "/" + stripped;
  };
  for (const auto &[alias, target] : importMap) {
    std::error_code ec;
    auto root = std::filesystem::weakly_canonical(target, ec);
    if (ec) {
      continue;
    }
    if (auto logical = buildRelative(root, alias)) {
      return *logical;
    }
  }
  if (auto logical = buildRelative(coreRoot, "core")) {
    if (*logical == "core/core") {
      return "core";
    }
    return *logical;
  }
  if (auto logical = buildRelative(stdRoot, "std")) {
    return *logical;
  }
  if (auto logical = buildRelative(cwdRoot)) {
    return *logical;
  }
  return stripSourceExtension(canonicalPath.filename());
}
References coreRootPath(), stdlibRootPath(), and stripSourceExtension().
coreRootPath()
std::filesystem::path zap::frontend::coreRootPath (const RuntimePaths & paths)
Definition at line 45 of file module_loader.cpp.
{
  if (const char *configured = std::getenv("ZAPC_CORE_DIR")) {
    if (*configured != '\0') {
      return std::filesystem::path(configured);
    }
  }
  if (auto exePath = currentExecutablePath(paths.executablePath)) {
    auto siblingCore = exePath->parent_path() / "core";
    if (std::filesystem::exists(siblingCore) &&
        std::filesystem::is_directory(siblingCore)) {
      return siblingCore;
    }
  }
  return paths.configuredCoreDir;
}
References zap::frontend::RuntimePaths::configuredCoreDir, currentExecutablePath(), and zap::frontend::RuntimePaths::executablePath.
Referenced by computeLogicalModulePath(), zap::driver::parseArgs(), and resolveImportTargets().
currentExecutablePath()
std::optional< std::filesystem::path > zap::frontend::currentExecutablePath (const std::filesystem::path & argv0Hint)
Definition at line 10 of file module_loader.cpp.
{
  std::error_code ec;
  auto procPath = std::filesystem::read_symlink("/proc/self/exe", ec);
  if (!ec && !procPath.empty()) {
    return std::filesystem::weakly_canonical(procPath);
  }
  if (!argv0Hint.empty()) {
    auto resolved = argv0Hint.is_absolute()
                        ? argv0Hint
                        : std::filesystem::current_path() / argv0Hint;
    return std::filesystem::weakly_canonical(resolved, ec);
  }
  return std::nullopt;
}
Referenced by coreRootPath(), stdlibObjectPath(), and stdlibRootPath().
hasImplicitImport()
bool zap::frontend::hasImplicitImport (const RootNode & root, std::string_view path)
Definition at line 145 of file module_loader.cpp.
{
  for (const auto &child : root.children) {
    auto importNode = dynamic_cast<ImportNode *>(child.get());
    if (importNode && importNode->path == path) {
      return true;
    }
  }
  return false;
}
References RootNode::children.
Referenced by injectImplicitPreludeImportIfNeeded().
importPathMatchesAlias()
bool zap::frontend::importPathMatchesAlias (const std::string & importPath, const std::string & alias) static
Definition at line 89 of file module_loader.cpp.
{
  return importPath == alias || importPath.rfind(alias + "/", 0) == 0;
}
Referenced by resolveImportTargets().
injectImplicitPreludeImportIfNeeded()
void zap::frontend::injectImplicitPreludeImportIfNeeded (sema::ModuleInfo & module, bool includePrelude)
Definition at line 155 of file module_loader.cpp.
{
  if (!includePrelude) {
    return;
  }
  if (module.linkPath == "core" || module.linkPath.rfind("core/", 0) == 0 ||
      module.linkPath.rfind("std/", 0) == 0) {
    return;
  }
  if (!module.root || hasImplicitImport(*module.root, "std/prelude")) {
    return;
  }
  auto import = std::make_unique<ImportNode>("std/prelude");
  module.root->children.insert(module.root->children.begin(),
                               std::move(import));
}
References hasImplicitImport(), sema::ModuleInfo::linkPath, and sema::ModuleInfo::root.
Referenced by zap::anonymous_namespace{driver.cpp}::loadModuleGraph(), and zap::lsp::Workspace::loadModuleGraph().
makeResolvedImport()
sema::ResolvedImport zap::frontend::makeResolvedImport (const ImportNode & importNode, const std::vector< std::filesystem::path > & targets)
Definition at line 253 of file module_loader.cpp.
{
  sema::ResolvedImport resolved;
  resolved.rawPath = importNode.path;
  resolved.moduleAlias = importNode.moduleAlias;
  resolved.visibility = importNode.visibility_;
  resolved.span = importNode.span;
  for (const auto &binding : importNode.bindings) {
    resolved.bindings.push_back({binding.sourceName, binding.localName});
  }
  for (const auto &target : targets) {
    resolved.targetModuleIds.push_back(target.string());
  }
  return resolved;
}
References ImportNode::bindings, sema::ResolvedImport::bindings, ImportNode::moduleAlias, sema::ResolvedImport::moduleAlias, ImportNode::path, sema::ResolvedImport::rawPath, Node::span, sema::ResolvedImport::span, sema::ResolvedImport::targetModuleIds, sema::ResolvedImport::visibility, and TopLevel::visibility_.
resolveImportTargets()
bool zap::frontend::resolveImportTargets (const std::filesystem::path & modulePath, const ImportNode & importNode, std::vector< std::filesystem::path > & targets, const ImportMap & importMap, const RuntimePaths & paths, std::string * errorMessage)
Definition at line 183 of file module_loader.cpp.
{
  std::filesystem::path resolvedPath;
  const std::string &importPath = importNode.path;
  bool resolvedViaMap = false;
  for (const auto &[alias, target] : importMap) {
    if (importPathMatchesAlias(importPath, alias)) {
      std::string rest = importPath.substr(alias.size());
      if (!rest.empty() && rest[0] == '/') {
        rest = rest.substr(1);
      }
      resolvedPath = std::filesystem::path(target) / rest;
      resolvedViaMap = true;
      break;
    }
  }
  if (!resolvedViaMap) {
    if (importPath == "core") {
      resolvedPath = coreRootPath(paths) / "core";
    } else if (importPath.rfind("core/", 0) == 0) {
      resolvedPath =
          coreRootPath(paths) / importPath.substr(std::string("core/").size());
    } else if (importPath.rfind("std/", 0) == 0) {
      resolvedPath =
          stdlibRootPath(paths) / importPath.substr(std::string("std/").size());
    } else {
      resolvedPath = modulePath.parent_path() / importPath;
    }
  }
  resolvedPath = resolvedPath.lexically_normal();
  auto tryFile = [&](const std::filesystem::path &path) -> bool {
    if (std::filesystem::exists(path) &&
        std::filesystem::is_regular_file(path)) {
      targets.push_back(std::filesystem::weakly_canonical(path));
      return true;
    }
    return false;
  };
  if (tryFile(resolvedPath)) {
    return true;
  }
  if (resolvedPath.extension() != ".zp" &&
      tryFile(resolvedPath.string() + ".zp")) {
    return true;
  }
  if (std::filesystem::exists(resolvedPath) &&
      std::filesystem::is_directory(resolvedPath)) {
    for (const auto &entry :
         std::filesystem::directory_iterator(resolvedPath)) {
      if (entry.is_regular_file() && entry.path().extension() == ".zp") {
        targets.push_back(std::filesystem::weakly_canonical(entry.path()));
      }
    }
    std::sort(targets.begin(), targets.end());
    return !targets.empty();
  }
  setImportError(errorMessage, resolvedPath);
  return false;
}
References coreRootPath(), importPathMatchesAlias(), ImportNode::path, setImportError(), and stdlibRootPath().
Referenced by zap::anonymous_namespace{driver.cpp}::loadModuleGraph(), and zap::lsp::Workspace::loadModuleGraph().
setImportError()
void zap::frontend::setImportError (std::string * errorMessage, const std::filesystem::path & path) static
Definition at line 173 of file module_loader.cpp.
{
  if (!errorMessage) {
    return;
  }
  std::ostringstream out;
  out << "import path not found: " << path;
  *errorMessage = out.str();
}
References zap::out().
Referenced by resolveImportTargets().
stdlibObjectPath()
std::filesystem::path zap::frontend::stdlibObjectPath (const RuntimePaths & paths)
Definition at line 63 of file module_loader.cpp.
{
  if (const char *configured = std::getenv("ZAPC_STDLIB_PATH")) {
    if (*configured != '\0') {
      return std::filesystem::path(configured);
    }
  }
  if (auto exePath = currentExecutablePath(paths.executablePath)) {
    auto siblingObject = exePath->parent_path() / "stdlib.o";
    if (std::filesystem::exists(siblingObject) &&
        std::filesystem::is_regular_file(siblingObject)) {
      return siblingObject;
    }
  }
  return paths.configuredStdlibObject;
}
References zap::frontend::RuntimePaths::configuredStdlibObject, currentExecutablePath(), and zap::frontend::RuntimePaths::executablePath.
Referenced by zap::driver::link().
stdlibRootPath()
std::filesystem::path zap::frontend::stdlibRootPath (const RuntimePaths & paths)
Definition at line 27 of file module_loader.cpp.
{
  if (const char *configured = std::getenv("ZAPC_STDLIB_DIR")) {
    if (*configured != '\0') {
      return std::filesystem::path(configured);
    }
  }
  if (auto exePath = currentExecutablePath(paths.executablePath)) {
    auto siblingStd = exePath->parent_path() / "std";
    if (std::filesystem::exists(siblingStd) &&
        std::filesystem::is_directory(siblingStd)) {
      return siblingStd;
    }
  }
  return paths.configuredStdlibDir;
}
References zap::frontend::RuntimePaths::configuredStdlibDir, currentExecutablePath(), and zap::frontend::RuntimePaths::executablePath.
Referenced by computeLogicalModulePath(), zap::driver::parseArgs(), and resolveImportTargets().
stripSourceExtension()
std::string zap::frontend::stripSourceExtension (const std::filesystem::path & path)
Definition at line 81 of file module_loader.cpp.
{
  auto normalized = path.generic_string();
  if (path.extension() == ".zp" && normalized.size() >= 3) {
    normalized.resize(normalized.size() - 3);
  }
  return normalized;
}
Referenced by computeLogicalModulePath().