ZAP: WhileNode Class Reference
WhileNode Class Reference
#include <while_node.hpp>
Public Member Functions
WhileNode () noexcept=default
WhileNode (std::unique_ptr< ExpressionNode > condition, std::unique_ptr< BodyNode > body)
void accept (Visitor &v) override
Public Member Functions inherited from StatementNode
virtual ~StatementNode () noexcept=default
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::unique_ptr< ExpressionNode > condition_
std::unique_ptr< BodyNode > body_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file while_node.hpp.
Constructor & Destructor Documentation
WhileNode() [1/2]
WhileNode::WhileNode () default noexcept
Referenced by WhileNode().
WhileNode() [2/2]
WhileNode::WhileNode (std::unique_ptr< ExpressionNode > condition, std::unique_ptr< BodyNode > body) inline
Definition at line 13 of file while_node.hpp.
      : condition_(std::move(condition)), body_(std::move(body)) {}
References body_, condition_, and WhileNode().
Member Function Documentation
accept()
void WhileNode::accept (Visitor & v) inline override virtual
Reimplemented from StatementNode.
Definition at line 17 of file while_node.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
body_
std::unique_ptr<BodyNode> WhileNode::body_
Definition at line 11 of file while_node.hpp.
Referenced by sema::Binder::visit(), and WhileNode().
condition_
std::unique_ptr<ExpressionNode> WhileNode::condition_
Definition at line 10 of file while_node.hpp.
Referenced by sema::Binder::visit(), and WhileNode().
The documentation for this class was generated from the following file:
src/ast/while_node.hpp