ZAP: BodyNode Class Reference
BodyNode Class Reference
#include <body_node.hpp>
Public Member Functions
BodyNode () noexcept=default
~BodyNode () noexcept override=default
void addStatement (std::unique_ptr< Node > statement)
void setResult (std::unique_ptr< ExpressionNode > res)
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::vector< std::unique_ptr< Node > > statements
std::unique_ptr< ExpressionNode > result
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 8 of file body_node.hpp.
Constructor & Destructor Documentation
BodyNode()
BodyNode::BodyNode () default noexcept
Referenced by ~BodyNode().
~BodyNode()
BodyNode::~BodyNode () override default noexcept
References BodyNode().
Member Function Documentation
accept()
void BodyNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 28 of file body_node.hpp.
{ v.visit(*this); }
References Visitor::visit().
addStatement()
void BodyNode::addStatement (std::unique_ptr< Node > statement) inline
Definition at line 16 of file body_node.hpp.
{
    if (statement) {
      statements.push_back(std::move(statement));
    } else {
      std::cerr << "Cannot add a null statement to BodyNode" << std::endl;
    }
  }
References addStatement(), and statements.
Referenced by addStatement().
setResult()
void BodyNode::setResult (std::unique_ptr< ExpressionNode > res) inline
Definition at line 24 of file body_node.hpp.
{
    result = std::move(res);
  }
References result.
Member Data Documentation
result
std::unique_ptr<ExpressionNode> BodyNode::result
Definition at line 11 of file body_node.hpp.
Referenced by setResult(), and sema::Binder::visit().
statements
std::vector<std::unique_ptr<Node> > BodyNode::statements
Definition at line 10 of file body_node.hpp.
Referenced by addStatement(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/body_node.hpp