ZAP: zap::lsp::JsonRPC Class Reference
zap::lsp::JsonRPC Class Reference
#include <lsp.hpp>
Public Types
enum ErrorCodes {
ParseError = -32700 ,
InvalidRequest = -32600 ,
MethodNotFound = -32601 ,
InvalidParams = -32602 ,
InternalError = -32603
}
Public Member Functions
JsonRPC (const std::string &message)
JsonRPC (JsonObject object) noexcept
std::string_view getStr ()
const JsonObject & object () const noexcept
Private Attributes
std::string serialized_
JsonObject rpc_
Detailed Description
Definition at line 69 of file lsp.hpp.
Member Enumeration Documentation
ErrorCodes
enum zap::lsp::JsonRPC::ErrorCodes
Enumerator
ParseError
InvalidRequest
MethodNotFound
InvalidParams
InternalError
Definition at line 71 of file lsp.hpp.
                  {
    ParseError = -32700,
    InvalidRequest = -32600,
    MethodNotFound = -32601,
    InvalidParams = -32602,
    InternalError = -32603,
  };
Constructor & Destructor Documentation
JsonRPC() [1/2]
zap::lsp::JsonRPC::JsonRPC (const std::string & message)
Definition at line 381 of file lsp.cpp.
    : serialized_(message), rpc_(JsonParser::parse(serialized_)) {}
References rpc_, and serialized_.
JsonRPC() [2/2]
zap::lsp::JsonRPC::JsonRPC (JsonObject object) noexcept
Definition at line 384 of file lsp.cpp.
: rpc_(std::move(object)) {}
References rpc_.
Member Function Documentation
getStr()
std::string_view zap::lsp::JsonRPC::getStr ()
Definition at line 386 of file lsp.cpp.
{
  if (serialized_.empty()) {
    JsonParser::toString(serialized_, rpc_);
  }
  return serialized_;
}
References rpc_, serialized_, and zap::lsp::JsonParser::toString().
Referenced by zap::lsp::Server::sendMessage().
object()
const JsonObject & zap::lsp::JsonRPC::object () const inline noexcept
Definition at line 88 of file lsp.hpp.
{ return rpc_; }
References rpc_.
Referenced by main().
Member Data Documentation
rpc_
JsonObject zap::lsp::JsonRPC::rpc_ private
Definition at line 81 of file lsp.hpp.
Referenced by getStr(), JsonRPC(), JsonRPC(), and object().
serialized_
std::string zap::lsp::JsonRPC::serialized_ private
Definition at line 80 of file lsp.hpp.
Referenced by getStr(), and JsonRPC().
The documentation for this class was generated from the following files:
src/lsp/lsp.hpp
src/lsp/lsp.cpp