ZAP: ArrayLiteralNode Class Reference
ArrayLiteralNode Class Reference
#include <array_literal.hpp>
Public Member Functions
ArrayLiteralNode () noexcept=default
ArrayLiteralNode (std::vector< std::unique_ptr< ExpressionNode > > elements)
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::vector< std::unique_ptr< ExpressionNode > > elements_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 7 of file array_literal.hpp.
Constructor & Destructor Documentation
ArrayLiteralNode() [1/2]
ArrayLiteralNode::ArrayLiteralNode () default noexcept
Referenced by ArrayLiteralNode().
ArrayLiteralNode() [2/2]
ArrayLiteralNode::ArrayLiteralNode (std::vector< std::unique_ptr< ExpressionNode > > elements) inline explicit
Definition at line 12 of file array_literal.hpp.
      : elements_(std::move(elements)) {}
References ArrayLiteralNode(), elements_, and ExpressionNode::ExpressionNode().
Member Function Documentation
accept()
void ArrayLiteralNode::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 16 of file array_literal.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
elements_
std::vector<std::unique_ptr<ExpressionNode> > ArrayLiteralNode::elements_
Definition at line 9 of file array_literal.hpp.
Referenced by ArrayLiteralNode(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/array_literal.hpp