ZAP: zap::Stream Class Reference
zap::Stream Class Reference abstract
A base stream class.
#include <stream.hpp>
Public Types
using BufferChar = char
using BufferType = BufferChar *
Public Member Functions
Stream (const Stream &)=delete
Stream & operator= (const Stream &)=delete
Stream (size_t bufferSize=DEFAULT_BUFFER_SIZE)
Default stream constructor.
size_t getBufferSize () const noexcept
Stream & write (const BufferChar *ptr, size_t size)
Writes the provided characters to the stream.
void setBufferSize (size_t bufferSize=DEFAULT_BUFFER_SIZE)
Sets the buffer size of the stream.
void setNoBuffer () noexcept
Makes the stream unbuffered.
void flush ()
virtual bool onTTY () const
Returns whether or not the stream is in a console/terminal.
virtual bool hasColors () const
Returns whether or not this stream supports colors.
virtual ~Stream () noexcept
Stream & operator<< (std::nullptr_t)
Stream & operator<< (char c)
Stream & operator<< (unsigned char c)
Stream & operator<< (signed char c)
Stream & operator<< (bool b)
Stream & operator<< (const void *ptr)
Stream & operator<< (const char *str)
Stream & operator<< (const std::string &str)
Stream & operator<< (std::string_view str)
Stream & resetColor ()
template<typename T>
std::enable_if_t< std::is_arithmetic_v< T >, Stream & > operator<< (T val)
Stream & changeColor (Color col, bool bold=false, bool bg=false)
Stream & operator<< (Color col)
Static Public Attributes
static constexpr size_t DEFAULT_BUFFER_SIZE = 0x2000
Default buffer size if the buffer size arg is not set.
Private Member Functions
virtual void internalWrite (const BufferChar *ptr, size_t size)=0
Implementation for the write function, depends on the class.
virtual void internalFlush ()
Private Attributes
BufferType start
BufferType cur
BufferType end
Detailed Description
A base stream class.
Definition at line 37 of file stream.hpp.
Member Typedef Documentation
BufferChar
using zap::Stream::BufferChar = char
Definition at line 39 of file stream.hpp.
BufferType
using zap::Stream::BufferType = BufferChar *
Definition at line 40 of file stream.hpp.
Constructor & Destructor Documentation
Stream() [1/2]
zap::Stream::Stream (const Stream &) delete
References Stream().
Referenced by changeColor(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator=(), zap::SFStream::SFStream(), Stream(), and write().
Stream() [2/2]
zap::Stream::Stream (size_t bufferSize = DEFAULT_BUFFER_SIZE)
Default stream constructor.
Parameters
bufferSize What buffer size should it be, 0 for unbuffered.
Definition at line 14 of file stream.cpp.
{
  start = cur = end = nullptr;
  if (bufferSize) {
    setBufferSize(bufferSize);
  }
}
References cur, end, setBufferSize(), and start.
~Stream()
virtual zap::Stream::~Stream () inline virtual noexcept
Definition at line 88 of file stream.hpp.
{ setNoBuffer(); }
References setNoBuffer().
Member Function Documentation
changeColor()
Stream & zap::Stream::changeColor (Color col, bool bold = false, bool bg = false) inline
Definition at line 145 of file stream.hpp.
{
    if (hasColors()) {
      int code = int(col);
      if (bg) {
        code += 10;
      }
      *this << "\033[";
      if (bold)
        *this << "1;";
      *this << code << "m";
    }
    return *this;
  }
References hasColors(), and Stream().
Referenced by operator<<(), zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printDiagnostic().
flush()
void zap::Stream::flush () inline
Definition at line 74 of file stream.hpp.
               {
    if (cur != start) {
      internalWrite(start, cur - start);
      cur = start;
    }
    internalFlush();
  }
References cur, internalFlush(), internalWrite(), and start.
Referenced by setBufferSize(), and write().
getBufferSize()
size_t zap::Stream::getBufferSize () const inline noexcept
Definition at line 61 of file stream.hpp.
{ return end - cur; }
References cur, and end.
Referenced by setBufferSize(), and write().
hasColors()
virtual bool zap::Stream::hasColors () const inline virtual
Returns whether or not this stream supports colors.
Reimplemented in zap::StderrStream, and zap::StdoutStream.
Definition at line 86 of file stream.hpp.
{ return false; }
Referenced by changeColor(), and operator<<().
internalFlush()
virtual void zap::Stream::internalFlush () inline private virtual
Reimplemented in zap::SFStream.
Definition at line 51 of file stream.hpp.
{}
Referenced by flush().
internalWrite()
virtual void zap::Stream::internalWrite (const BufferChar * ptr, size_t size) private pure virtual
Implementation for the write function, depends on the class.
Implemented in zap::SFStream.
Referenced by flush(), and write().
onTTY()
virtual bool zap::Stream::onTTY () const inline virtual
Returns whether or not the stream is in a console/terminal.
Reimplemented in zap::StderrStream, and zap::StdoutStream.
Definition at line 83 of file stream.hpp.
{ return false; }
operator<<() [1/11]
Stream & zap::Stream::operator<< (bool b) inline
Definition at line 98 of file stream.hpp.
{
    return b ? write("true", 4) : write("false", 5);
  }
References Stream(), and write().
operator<<() [2/11]
Stream & zap::Stream::operator<< (char c) inline
Definition at line 92 of file stream.hpp.
{ return write(&c, sizeof(c)); }
References Stream(), and write().
operator<<() [3/11]
Stream & zap::Stream::operator<< (Color col) inline
Definition at line 161 of file stream.hpp.
{ return changeColor(col); }
References changeColor(), and Stream().
operator<<() [4/11]
Stream & zap::Stream::operator<< (const char * str) inline
Definition at line 113 of file stream.hpp.
{ return write(str, strlen(str)); }
References Stream(), and write().
operator<<() [5/11]
Stream & zap::Stream::operator<< (const std::string & str) inline
Definition at line 115 of file stream.hpp.
{
    return write(str.data(), str.size());
  }
References Stream(), and write().
operator<<() [6/11]
Stream & zap::Stream::operator<< (const void * ptr) inline
Definition at line 102 of file stream.hpp.
{
    char buff[sizeof(void *) * 2 + 2];
    auto res = std::to_chars(buff, buff + sizeof(buff), (uintptr_t)ptr, 16);
    if (res.ec == std::errc()) {
      write(buff, res.ptr - buff);
    }
    return *this;
  }
References Stream(), and write().
operator<<() [7/11]
Stream & zap::Stream::operator<< (signed char c) inline
Definition at line 96 of file stream.hpp.
{ return *this << char(c); }
References Stream().
operator<<() [8/11]
Stream & zap::Stream::operator<< (std::nullptr_t) inline
Definition at line 90 of file stream.hpp.
{ return write("null", 4); }
References Stream(), and write().
operator<<() [9/11]
Stream & zap::Stream::operator<< (std::string_view str) inline
Definition at line 119 of file stream.hpp.
{
    return write(str.data(), str.size());
  }
References Stream(), and write().
operator<<() [10/11]
template<typename T> std::enable_if_t< std::is_arithmetic_v< T >, Stream & > zap::Stream::operator<< (T val) inline
Definition at line 123 of file stream.hpp.
{
    char
        buff[(std::is_floating_point_v<T> ? std::numeric_limits<T>::max_digits10
                                          : std::numeric_limits<T>::digits10) +
             0x20];
    auto result = std::to_chars(buff, buff + sizeof(buff), val);
    if (result.ec == std::errc()) {
      write(buff, result.ptr - buff);
    }
    return *this;
  }
References hasColors(), Stream(), and write().
operator<<() [11/11]
Stream & zap::Stream::operator<< (unsigned char c) inline
Definition at line 94 of file stream.hpp.
{ return *this << char(c); }
References Stream().
operator=()
Stream & zap::Stream::operator= (const Stream &) delete
References DEFAULT_BUFFER_SIZE, and Stream().
resetColor()
Stream & zap::Stream::resetColor () inline
Definition at line 123 of file stream.hpp.
                       {
    if (hasColors()) {
      write("\033[0m", 4);
    }
    return *this;
  }
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printDiagnostic().
setBufferSize()
void zap::Stream::setBufferSize (size_t bufferSize = DEFAULT_BUFFER_SIZE)
Sets the buffer size of the stream.
Definition at line 22 of file stream.cpp.
{
  if (bufferSize == getBufferSize())
    return;
  flush();
  delete[] start;
  start = cur = end = nullptr;
  if (bufferSize) {
    start = cur = new BufferChar[bufferSize];
    end = start + bufferSize;
  }
}
References cur, end, flush(), getBufferSize(), and start.
Referenced by setNoBuffer(), and Stream().
setNoBuffer()
void zap::Stream::setNoBuffer () inline noexcept
Makes the stream unbuffered.
Definition at line 72 of file stream.hpp.
{ setBufferSize(0); }
References setBufferSize().
Referenced by zap::SFStream::~SFStream(), and ~Stream().
write()
Stream & zap::Stream::write (const BufferChar * ptr, size_t size)
Writes the provided characters to the stream.
Parameters
ptr Pointer to the characters.
size How many of them.
Definition at line 37 of file stream.cpp.
{
  size_t bufferSize = getBufferSize();
  if (!bufferSize) {
    internalWrite(ptr, size);
    return *this;
  }
  size_t bytesLeft = size;
  while (bytesLeft) {
    size_t spaceLeft = end - cur;
    if (bytesLeft >= bufferSize) {
      flush();
      internalWrite(ptr, size);
      break;
    }
    if (!spaceLeft) {
      flush();
      spaceLeft = bufferSize;
    }
    size_t toCpy = std::min(bytesLeft, spaceLeft);
    std::memcpy(cur, ptr, toCpy);
    cur += toCpy;
    ptr += toCpy;
    bytesLeft -= toCpy;
  }
  return *this;
}
References cur, end, flush(), getBufferSize(), internalWrite(), and Stream().
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), and operator<<().
Member Data Documentation
cur
BufferType zap::Stream::cur private
Definition at line 46 of file stream.hpp.
Referenced by flush(), getBufferSize(), setBufferSize(), Stream(), and write().
DEFAULT_BUFFER_SIZE
size_t zap::Stream::DEFAULT_BUFFER_SIZE = 0x2000 static constexpr
Default buffer size if the buffer size arg is not set.
Definition at line 43 of file stream.hpp.
Referenced by operator=().
end
BufferType zap::Stream::end private
Definition at line 46 of file stream.hpp.
Referenced by getBufferSize(), setBufferSize(), Stream(), and write().
start
BufferType zap::Stream::start private
Definition at line 46 of file stream.hpp.
Referenced by flush(), setBufferSize(), and Stream().
The documentation for this class was generated from the following files:
src/utils/stream.hpp
src/utils/stream.cpp