ZAP: ConstBool Class Reference
ConstBool Class Reference
#include <const_bool.hpp>
Public Member Functions
ConstBool () noexcept=default
ConstBool (bool value) noexcept
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
bool value_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 5 of file const_bool.hpp.
Constructor & Destructor Documentation
ConstBool() [1/2]
ConstBool::ConstBool () default noexcept
Referenced by ConstBool().
ConstBool() [2/2]
ConstBool::ConstBool (bool value) inline noexcept
Definition at line 9 of file const_bool.hpp.
: value_(value) {}
References ConstBool(), and value_.
Member Function Documentation
accept()
void ConstBool::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 11 of file const_bool.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
value_
bool ConstBool::value_
Definition at line 7 of file const_bool.hpp.
Referenced by ConstBool(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/const/const_bool.hpp