ZAP: ConstId Class Reference
ConstId Class Reference
#include <const_id.hpp>
Public Member Functions
ConstId () noexcept(std::is_nothrow_default_constructible< std::string >::value)=default
ConstId (std::string value)
void accept (Visitor &v) override
Public Member Functions inherited from ExpressionNode
virtual ~ExpressionNode () noexcept=default
ExpressionNode () noexcept=default
void accept (Visitor &v) override
Public Member Functions inherited from Node
virtual ~Node () noexcept=default
Public Attributes
std::string value_
Public Attributes inherited from Node
SourceSpan span
Detailed Description
Definition at line 4 of file const_id.hpp.
Constructor & Destructor Documentation
ConstId() [1/2]
ConstId::ConstId () const default noexcept
Referenced by ConstId().
ConstId() [2/2]
ConstId::ConstId (std::string value) inline
Definition at line 8 of file const_id.hpp.
: value_(value) {}
References ConstId(), and value_.
Member Function Documentation
accept()
void ConstId::accept (Visitor & v) inline override virtual
Implements Node.
Definition at line 10 of file const_id.hpp.
{ v.visit(*this); }
References Visitor::visit().
Member Data Documentation
value_
std::string ConstId::value_
Definition at line 6 of file const_id.hpp.
Referenced by ConstId(), and sema::Binder::visit().
The documentation for this class was generated from the following file:
src/ast/const/const_id.hpp