ZAP: zap::lsp::Server Class Reference
zap::lsp::Server Class Reference
The main class for the LSP server.
#include <lsp.hpp>
Public Types
enum class MessageType {
Error = 1 ,
Warning = 2 ,
Info = 3 ,
Log = 4
}
Used for sendMessage().
Public Member Functions
Server ()=default
Server (const Server &)=delete
Server & operator= (const Server &)=delete
Server (Server &&)=default
Server & operator= (Server &&)=default
~Server () noexcept=default
void logMessage (MessageType type, std::string_view message)
Request the client to show a message to the user.
std::string processMessage (std::string &line)
Should be called in the while loop in main.
void send ()
Sends all queued messages.
void sendMessage (JsonRPC &msg)
Queues a message.
void sendMessage (JsonObject &msg)
Queues a json message.
Private Member Functions
void sendMessageRaw (std::string_view message)
Used internally to send JSON RPC.
Private Attributes
std::string buffer
Detailed Description
The main class for the LSP server.
Definition at line 149 of file lsp.hpp.
Member Enumeration Documentation
MessageType
enum class zap::lsp::Server::MessageType strong
Used for sendMessage().
Enumerator
Error
Warning
Info
Log
Definition at line 169 of file lsp.hpp.
{
    Error = 1,
    Warning = 2,
    Info = 3,
    Log = 4
  };
Constructor & Destructor Documentation
Server() [1/3]
zap::lsp::Server::Server () default
Referenced by operator=(), operator=(), Server(), and Server().
Server() [2/3]
zap::lsp::Server::Server (const Server &) delete
References Server().
Server() [3/3]
zap::lsp::Server::Server (Server &&) default
References Server().
~Server()
zap::lsp::Server::~Server () default noexcept
Member Function Documentation
logMessage()
void zap::lsp::Server::logMessage (MessageType type, std::string_view message) inline
Request the client to show a message to the user.
Definition at line 176 of file lsp.hpp.
{
    JsonObject rpc(JsonObject::Object{});
    rpc.getAsObject()["jsonrpc"] = JsonObject(std::string_view("2.0"));
    rpc.getAsObject()["method"] = JsonObject(std::string_view("window/logMessage"));
    JsonObject params(JsonObject::Object{});
    params.getAsObject()["type"] = JsonObject(JsonObject::Integer(type));
    params.getAsObject()["message"] = JsonObject(message);
    rpc.getAsObject()["params"] = std::move(params);
    sendMessage(rpc);
  }
References zap::lsp::JsonObject::getAsObject(), and sendMessage().
Referenced by main().
operator=() [1/2]
Server & zap::lsp::Server::operator= (const Server &) delete
References Server().
operator=() [2/2]
Server & zap::lsp::Server::operator= (Server &&) default
References Server().
processMessage()
std::string zap::lsp::Server::processMessage (std::string & line)
Should be called in the while loop in main.
Parameters
line String parameter outside of main, used as an arg for performance.
Returns
JSON Message.
Definition at line 285 of file lsp.cpp.
{
  unsigned content_length = 0;
  while(std::getline(std::cin, line)) {
    if(line.empty() || line == "\r") break;
    if(line.rfind(prefix, 0) == 0) {
      std::from_chars(line.data() + prefix.size(), line.data() + line.size(), content_length);
    }
  }
  std::string message(content_length, '\0');
  std::cin.read(message.data(), content_length);
  return message;
}
References zap::lsp::prefix.
Referenced by main().
send()
void zap::lsp::Server::send () inline
Sends all queued messages.
Definition at line 197 of file lsp.hpp.
             {
    std::cout << buffer;
    buffer.clear();
  }
References buffer.
Referenced by main().
sendMessage() [1/2]
void zap::lsp::Server::sendMessage (JsonObject & msg) inline
Queues a json message.
Parameters
msg The message to queue.
Definition at line 212 of file lsp.hpp.
{
    std::string s;
    JsonParser::toString(s, msg);
    sendMessageRaw(s);
  }
References sendMessageRaw(), and zap::lsp::JsonParser::toString().
sendMessage() [2/2]
void zap::lsp::Server::sendMessage (JsonRPC & msg) inline
Queues a message.
Parameters
msg The message to queue.
Use send() to flush the messages.
Definition at line 206 of file lsp.hpp.
{
    sendMessageRaw(msg.getStr());
  }
References zap::lsp::JsonRPC::getStr(), and sendMessageRaw().
Referenced by logMessage().
sendMessageRaw()
void zap::lsp::Server::sendMessageRaw (std::string_view message) private
Used internally to send JSON RPC.
Parameters
message JSON RPC.
This adds content length to the message.
Definition at line 269 of file lsp.cpp.
{
  buffer += prefix;
  char buff[std::numeric_limits<unsigned>::digits10 + 0x20];
  auto result = std::to_chars(buff, buff + sizeof(buff), message.length());
  constexpr const char* crlf = "\r\n\r\n";
  std::copy(crlf, crlf + 4, result.ptr);
  result.ptr += 4;
  buffer.append(buff, result.ptr - buff);
  buffer += message;
}
References buffer, and zap::lsp::prefix.
Referenced by sendMessage(), and sendMessage().
Member Data Documentation
buffer
std::string zap::lsp::Server::buffer private
Definition at line 150 of file lsp.hpp.
Referenced by send(), and sendMessageRaw().
The documentation for this class was generated from the following files:
src/lsp/lsp.hpp
src/lsp/lsp.cpp