ZAP: zap::DiagnosticTextFormatter Class Reference
zap::DiagnosticTextFormatter Class Reference
#include <diagnostics.hpp>
Static Public Member Functions
static void print (Stream &os, const std::vector< Diagnostic > &diagnostics, const std::string &source)
static void print (std::ostream &os, const std::vector< Diagnostic > &diagnostics, const std::string &source)
Static Private Member Functions
static std::string levelToText (DiagnosticLevel level)
static Color levelToColor (DiagnosticLevel level)
static void printDiagnostic (Stream &os, const Diagnostic &diagnostic, const std::string &source)
static void printDiagnostic (std::ostream &os, const Diagnostic &diagnostic, const std::string &source)
static void printContext (Stream &os, const Diagnostic &diagnostic, const std::string &source)
static void printContext (std::ostream &os, const Diagnostic &diagnostic, const std::string &source)
Detailed Description
Definition at line 35 of file diagnostics.hpp.
Member Function Documentation
levelToColor()
Color zap::DiagnosticTextFormatter::levelToColor (DiagnosticLevel level) inline static private
Definition at line 64 of file diagnostics.hpp.
{
    switch (level) {
      case DiagnosticLevel::Note: return Color::BLUE;
      case DiagnosticLevel::Warning: return Color::YELLOW;
      case DiagnosticLevel::Error: return Color::RED;
    }
    return Color::WHITE;
  }
References zap::BLUE, zap::Error, zap::Note, zap::RED, zap::Warning, zap::WHITE, and zap::YELLOW.
Referenced by printContext(), and printDiagnostic().
levelToText()
std::string zap::DiagnosticTextFormatter::levelToText (DiagnosticLevel level) inline static private
Definition at line 54 of file diagnostics.hpp.
{
    switch (level) {
      case DiagnosticLevel::Note: return "note";
      case DiagnosticLevel::Warning: return "warning";
      case DiagnosticLevel::Error: return "error";
    }
    return "unknown";
  }
References zap::Error, zap::Note, and zap::Warning.
Referenced by printDiagnostic(), and printDiagnostic().
print() [1/2]
void zap::DiagnosticTextFormatter::print (std::ostream & os, const std::vector< Diagnostic > & diagnostics, const std::string & source) inline static
Definition at line 45 of file diagnostics.hpp.
{
    for (const auto& diagnostic : diagnostics) {
      printDiagnostic(os, diagnostic, source);
    }
  }
References printDiagnostic().
print() [2/2]
void zap::DiagnosticTextFormatter::print (Stream & os, const std::vector< Diagnostic > & diagnostics, const std::string & source) inline static
Definition at line 37 of file diagnostics.hpp.
{
    for (const auto& diagnostic : diagnostics) {
      printDiagnostic(os, diagnostic, source);
    }
  }
References printDiagnostic().
Referenced by zap::DiagnosticEngine::printText(), and zap::DiagnosticEngine::printText().
printContext() [1/2]
void zap::DiagnosticTextFormatter::printContext (std::ostream & os, const Diagnostic & diagnostic, const std::string & source) inline static private
Definition at line 174 of file diagnostics.hpp.
{
    SourceSpan span = diagnostic.span;
    size_t lineStart = 0;
    if (span.offset <= source.size()) {
      size_t searchStart = span.offset;
      while (searchStart > 0 && source[searchStart - 1] != '\n') {
        searchStart--;
      }
      lineStart = searchStart;
    } else {
      size_t line = 1;
      size_t i = 0;
      while (i < source.length() && line < span.line) {
        if (source[i] == '\n') {
          line++;
          lineStart = i + 1;
        }
        i++;
      }
    }
    size_t lineEnd = lineStart;
    while (lineEnd < source.length() && source[lineEnd] != '\n') {
      lineEnd++;
    }
    std::string lineContent = source.substr(lineStart, lineEnd - lineStart);
    std::string lineNumStr = std::to_string(span.line);
    os << " " << lineNumStr << " | " << lineContent << "\n";
    size_t prefixLen = lineNumStr.length() + 4;
    for (size_t j = 0; j < prefixLen; ++j) os << " ";
    size_t startIdx = 0;
    if (span.offset >= lineStart && span.offset <= lineEnd) {
      startIdx = span.offset - lineStart;
    } else if (span.column > 0) {
      startIdx = span.column - 1;
    }
    if (startIdx > lineContent.size()) {
      startIdx = lineContent.size();
    }
    for (size_t j = 0; j < startIdx; ++j) {
      os << (lineContent[j] == '\t' ? '\t' : ' ');
    }
    size_t len = span.length > 0 ? span.length : 1;
    if (startIdx >= lineContent.size()) {
      len = 1;
    } else {
      size_t maxAvailable = lineContent.size() - startIdx;
      if (len > maxAvailable) len = maxAvailable;
    }
    const size_t MAX_UNDERLINE = 40;
    if (len > MAX_UNDERLINE) {
      size_t half = MAX_UNDERLINE / 2;
      for (size_t k = 0; k < half; ++k) os << "^";
      os << "...";
      for (size_t k = 0; k < half; ++k) os << "^";
    } else {
      for (size_t j = 0; j < len; ++j) {
        os << "^";
      }
    }
    os << std::endl;
  }
References SourceSpan::column, len(), SourceSpan::length, SourceSpan::line, SourceSpan::offset, and zap::Diagnostic::span.
printContext() [2/2]
void zap::DiagnosticTextFormatter::printContext (Stream & os, const Diagnostic & diagnostic, const std::string & source) inline static private
Definition at line 99 of file diagnostics.hpp.
{
    SourceSpan span = diagnostic.span;
    size_t lineStart = 0;
    if (span.offset <= source.size()) {
      size_t searchStart = span.offset;
      while (searchStart > 0 && source[searchStart - 1] != '\n') {
        searchStart--;
      }
      lineStart = searchStart;
    } else {
      size_t line = 1;
      size_t i = 0;
      while (i < source.length() && line < span.line) {
        if (source[i] == '\n') {
          line++;
          lineStart = i + 1;
        }
        i++;
      }
    }
    size_t lineEnd = lineStart;
    while (lineEnd < source.length() && source[lineEnd] != '\n') {
      lineEnd++;
    }
    std::string lineContent = source.substr(lineStart, lineEnd - lineStart);
    std::string lineNumStr = std::to_string(span.line);
    os << " " << lineNumStr << " | " << lineContent << "\n";
    size_t prefixLen = lineNumStr.length() + 4;
    for (size_t j = 0; j < prefixLen; ++j) os << " ";
    size_t startIdx = 0;
    if (span.offset >= lineStart && span.offset <= lineEnd) {
      startIdx = span.offset - lineStart;
    } else if (span.column > 0) {
      startIdx = span.column - 1;
    }
    if (startIdx > lineContent.size()) {
      startIdx = lineContent.size();
    }
    for (size_t j = 0; j < startIdx; ++j) {
      os << (lineContent[j] == '\t' ? '\t' : ' ');
    }
    os.changeColor(levelToColor(diagnostic.level), true);
    size_t len = span.length > 0 ? span.length : 1;
    if (startIdx >= lineContent.size()) {
      len = 1;
    } else {
      size_t maxAvailable = lineContent.size() - startIdx;
      if (len > maxAvailable) len = maxAvailable;
    }
    const size_t MAX_UNDERLINE = 40;
    if (len > MAX_UNDERLINE) {
      size_t half = MAX_UNDERLINE / 2;
      for (size_t k = 0; k < half; ++k) os << "^";
      os << "...";
      for (size_t k = 0; k < half; ++k) os << "^";
    } else {
      for (size_t j = 0; j < len; ++j) {
        os << "^";
      }
    }
    os.resetColor();
    os << '\n';
  }
References zap::Stream::changeColor(), SourceSpan::column, len(), SourceSpan::length, zap::Diagnostic::level, levelToColor(), SourceSpan::line, SourceSpan::offset, zap::Stream::resetColor(), and zap::Diagnostic::span.
Referenced by printDiagnostic(), and printDiagnostic().
printDiagnostic() [1/2]
void zap::DiagnosticTextFormatter::printDiagnostic (std::ostream & os, const Diagnostic & diagnostic, const std::string & source) inline static private
Definition at line 88 of file diagnostics.hpp.
{
    os << levelToText(diagnostic.level) << ": " << diagnostic.message << '\n';
    os << " --> " << diagnostic.fileName << ":"
       << diagnostic.range.start.line << ":" << diagnostic.range.start.column
       << '\n';
    printContext(os, diagnostic, source);
  }
References zap::DiagnosticPosition::column, zap::Diagnostic::fileName, zap::Diagnostic::level, levelToText(), zap::DiagnosticPosition::line, zap::Diagnostic::message, printContext(), zap::Diagnostic::range, and zap::DiagnosticRange::start.
printDiagnostic() [2/2]
void zap::DiagnosticTextFormatter::printDiagnostic (Stream & os, const Diagnostic & diagnostic, const std::string & source) inline static private
Definition at line 74 of file diagnostics.hpp.
{
    os.changeColor(levelToColor(diagnostic.level), true);
    os << levelToText(diagnostic.level);
    os.resetColor();
    os << ": " << diagnostic.message << '\n';
    os << " --> " << diagnostic.fileName << ":"
       << diagnostic.range.start.line << ":" << diagnostic.range.start.column
       << '\n';
    printContext(os, diagnostic, source);
  }
References zap::Stream::changeColor(), zap::DiagnosticPosition::column, zap::Diagnostic::fileName, zap::Diagnostic::level, levelToColor(), levelToText(), zap::DiagnosticPosition::line, zap::Diagnostic::message, printContext(), zap::Diagnostic::range, zap::Stream::resetColor(), and zap::DiagnosticRange::start.
Referenced by print(), and print().
The documentation for this class was generated from the following file:
src/utils/diagnostics.hpp