ZAP: zap::detail Namespace Reference
zap::detail Namespace Reference
Functions
size_t tabWidth ()
bool isUtf8ContinuationByte (unsigned char c)
size_t utf8CodePointLength (unsigned char lead)
uint32_t decodeUtf8At (const std::string &s, size_t i, size_t *lenOut)
bool isCombining (uint32_t cp)
bool isWide (uint32_t cp)
size_t displayWidthOfCodePoint (uint32_t cp, size_t currentColumn)
size_t findLineStartByOffset (const std::string &source, size_t offset)
size_t findLineStartByLine (const std::string &source, size_t line1)
size_t findLineEnd (const std::string &source, size_t lineStart)
size_t clampToCodePointBoundary (const std::string &s, size_t pos)
size_t visualColumnsForBytes (const std::string &line, size_t bytesUpto)
std::string expandTabsForDisplay (const std::string &line)
std::pair< size_t, size_t > computeUnderlineColumns (const SourceSpan &span, const std::string &lineContent, size_t lineStartOffset)
std::string levelToText (DiagnosticLevel level)
Color levelToColor (DiagnosticLevel level)
Function Documentation
clampToCodePointBoundary()
size_t zap::detail::clampToCodePointBoundary (const std::string & s, size_t pos) inline
Definition at line 162 of file diagnostics.hpp.
{
  size_t p = std::min(pos, s.size());
  while (p > 0 && p < s.size() &&
         isUtf8ContinuationByte(static_cast<unsigned char>(s[p]))) {
    --p;
  }
  return p;
}
References isUtf8ContinuationByte().
Referenced by computeUnderlineColumns().
computeUnderlineColumns()
std::pair< size_t, size_t > zap::detail::computeUnderlineColumns (const SourceSpan & span, const std::string & lineContent, size_t lineStartOffset) inline
Definition at line 222 of file diagnostics.hpp.
{
  size_t startByteInLine = 0;
  if (span.offset >= lineStartOffset) {
    startByteInLine = span.offset - lineStartOffset;
  } else if (span.column > 0) {
    // Approx fallback when offset is unavailable: best-effort by characters.
    startByteInLine = std::min(span.column - 1, lineContent.size());
  }
  startByteInLine = clampToCodePointBoundary(lineContent, startByteInLine);
  startByteInLine = std::min(startByteInLine, lineContent.size());
  size_t endByteInLine = startByteInLine;
  if (span.length > 0) {
    size_t desired = startByteInLine + span.length;
    endByteInLine =
        clampToCodePointBoundary(lineContent, std::min(desired, lineContent.size()));
  } else {
    // zero-length span: point to the next visible cell
    endByteInLine = startByteInLine;
  }
  size_t startCol = visualColumnsForBytes(lineContent, startByteInLine);
  size_t endCol = visualColumnsForBytes(lineContent, endByteInLine);
  size_t width = (endCol > startCol) ? (endCol - startCol) : 1;
  return {startCol, width};
}
References clampToCodePointBoundary(), SourceSpan::column, SourceSpan::length, SourceSpan::offset, and visualColumnsForBytes().
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printContext().
decodeUtf8At()
uint32_t zap::detail::decodeUtf8At (const std::string & s, size_t i, size_t * lenOut) inline
Definition at line 53 of file diagnostics.hpp.
{
  if (i >= s.size()) {
    if (lenOut)
      *lenOut = 0;
    return 0;
  }
  const unsigned char lead = static_cast<unsigned char>(s[i]);
  const size_t len = std::min(utf8CodePointLength(lead), s.size() - i);
  if (len == 1) {
    if (lenOut)
      *lenOut = 1;
    return lead;
  }
  // Validate continuation bytes; if invalid, treat as single-byte char.
  for (size_t j = 1; j < len; ++j) {
    if (!isUtf8ContinuationByte(static_cast<unsigned char>(s[i + j]))) {
      if (lenOut)
        *lenOut = 1;
      return lead;
    }
  }
  uint32_t cp = 0;
  if (len == 2) {
    cp = (lead & 0x1F);
  } else if (len == 3) {
    cp = (lead & 0x0F);
  } else {
    cp = (lead & 0x07);
  }
  for (size_t j = 1; j < len; ++j) {
    cp = (cp << 6) | (static_cast<unsigned char>(s[i + j]) & 0x3F);
  }
  if (lenOut)
    *lenOut = len;
  return cp;
}
References isUtf8ContinuationByte(), len(), and utf8CodePointLength().
Referenced by expandTabsForDisplay(), and visualColumnsForBytes().
displayWidthOfCodePoint()
size_t zap::detail::displayWidthOfCodePoint (uint32_t cp, size_t currentColumn) inline
Definition at line 116 of file diagnostics.hpp.
{
  if (cp == '\t') {
    const size_t t = tabWidth();
    const size_t rem = currentColumn % t;
    return rem == 0 ? t : (t - rem);
  }
  if (cp < 0x20 || cp == 0x7F)
    return 1;
  if (isCombining(cp))
    return 0;
  if (isWide(cp))
    return 2;
  return 1;
}
References isCombining(), isWide(), and tabWidth().
Referenced by expandTabsForDisplay(), and visualColumnsForBytes().
expandTabsForDisplay()
std::string zap::detail::expandTabsForDisplay (const std::string & line) inline
Definition at line 193 of file diagnostics.hpp.
{
  std::string out;
  out.reserve(line.size());
  size_t i = 0;
  size_t col = 0;
  while (i < line.size()) {
    size_t len = 0;
    uint32_t cp = decodeUtf8At(line, i, &len);
    if (len == 0)
      break;
    if (cp == '\t') {
      const size_t spaces = displayWidthOfCodePoint(cp, col);
      out.append(spaces, ' ');
      col += spaces;
      i += len;
      continue;
    }
    out.append(line, i, len);
    col += displayWidthOfCodePoint(cp, col);
    i += len;
  }
  return out;
}
References decodeUtf8At(), displayWidthOfCodePoint(), len(), and zap::out().
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printContext().
findLineEnd()
size_t zap::detail::findLineEnd (const std::string & source, size_t lineStart) inline
Definition at line 155 of file diagnostics.hpp.
{
  size_t i = std::min(lineStart, source.size());
  while (i < source.size() && source[i] != '\n')
    ++i;
  return i;
}
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printContext().
findLineStartByLine()
size_t zap::detail::findLineStartByLine (const std::string & source, size_t line1) inline
Definition at line 139 of file diagnostics.hpp.
{
  if (line1 <= 1)
    return 0;
  size_t line = 1;
  size_t i = 0;
  size_t lineStart = 0;
  while (i < source.size() && line < line1) {
    if (source[i] == '\n') {
      ++line;
      lineStart = i + 1;
    }
    ++i;
  }
  return lineStart;
}
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printContext().
findLineStartByOffset()
size_t zap::detail::findLineStartByOffset (const std::string & source, size_t offset) inline
Definition at line 131 of file diagnostics.hpp.
{
  const size_t start = std::min(offset, source.size());
  size_t i = start;
  while (i > 0 && source[i - 1] != '\n')
    --i;
  return i;
}
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printContext().
isCombining()
bool zap::detail::isCombining (uint32_t cp) inline
Definition at line 102 of file diagnostics.hpp.
{
  return (cp >= 0x0300 && cp <= 0x036F) || (cp >= 0x1AB0 && cp <= 0x1AFF) ||
         (cp >= 0x1DC0 && cp <= 0x1DFF) || (cp >= 0x20D0 && cp <= 0x20FF) ||
         (cp >= 0xFE20 && cp <= 0xFE2F);
}
Referenced by displayWidthOfCodePoint().
isUtf8ContinuationByte()
bool zap::detail::isUtf8ContinuationByte (unsigned char c) inline
Definition at line 39 of file diagnostics.hpp.
{ return (c & 0xC0) == 0x80; }
Referenced by clampToCodePointBoundary(), and decodeUtf8At().
isWide()
bool zap::detail::isWide (uint32_t cp) inline
Definition at line 108 of file diagnostics.hpp.
{
  return (cp >= 0x1100 && cp <= 0x115F) || (cp >= 0x2329 && cp <= 0x232A) ||
         (cp >= 0x2E80 && cp <= 0xA4CF) || (cp >= 0xAC00 && cp <= 0xD7A3) ||
         (cp >= 0xF900 && cp <= 0xFAFF) || (cp >= 0xFE10 && cp <= 0xFE19) ||
         (cp >= 0xFE30 && cp <= 0xFE6F) || (cp >= 0xFF00 && cp <= 0xFF60) ||
         (cp >= 0xFFE0 && cp <= 0xFFE6) || (cp >= 0x1F300 && cp <= 0x1FAFF);
}
Referenced by displayWidthOfCodePoint().
levelToColor()
Color zap::detail::levelToColor (DiagnosticLevel level) inline
Definition at line 263 of file diagnostics.hpp.
{
  switch (level) {
  case DiagnosticLevel::Note:
    return Color::BLUE;
  case DiagnosticLevel::Warning:
    return Color::YELLOW;
  case DiagnosticLevel::Error:
    return Color::RED;
  }
  return Color::WHITE;
}
References zap::BLUE, zap::Error, zap::Note, zap::RED, zap::Warning, zap::WHITE, and zap::YELLOW.
Referenced by zap::DiagnosticTextFormatter::printContext(), and zap::DiagnosticTextFormatter::printDiagnostic().
levelToText()
std::string zap::detail::levelToText (DiagnosticLevel level) inline
Definition at line 251 of file diagnostics.hpp.
{
  switch (level) {
  case DiagnosticLevel::Note:
    return "note";
  case DiagnosticLevel::Warning:
    return "warning";
  case DiagnosticLevel::Error:
    return "error";
  }
  return "unknown";
}
References zap::Error, zap::Note, and zap::Warning.
Referenced by zap::DiagnosticTextFormatter::printDiagnostic(), and zap::DiagnosticTextFormatter::printDiagnostic().
tabWidth()
size_t zap::detail::tabWidth () inline
Definition at line 37 of file diagnostics.hpp.
{ return 4; }
Referenced by displayWidthOfCodePoint().
utf8CodePointLength()
size_t zap::detail::utf8CodePointLength (unsigned char lead) inline
Definition at line 41 of file diagnostics.hpp.
{
  if ((lead & 0x80) == 0x00)
    return 1;
  if ((lead & 0xE0) == 0xC0)
    return 2;
  if ((lead & 0xF0) == 0xE0)
    return 3;
  if ((lead & 0xF8) == 0xF0)
    return 4;
  return 1; // invalid lead byte fallback
}
Referenced by decodeUtf8At().
visualColumnsForBytes()
size_t zap::detail::visualColumnsForBytes (const std::string & line, size_t bytesUpto) inline
Definition at line 171 of file diagnostics.hpp.
{
  size_t i = 0;
  size_t col = 0;
  const size_t end = std::min(bytesUpto, line.size());
  while (i < end) {
    size_t len = 0;
    uint32_t cp = decodeUtf8At(line, i, &len);
    if (len == 0)
      break;
    // Prevent stepping beyond requested byte count.
    if (i + len > end)
      break;
    col += displayWidthOfCodePoint(cp, col);
    i += len;
  }
  return col;
}
References decodeUtf8At(), displayWidthOfCodePoint(), and len().
Referenced by computeUnderlineColumns().