name: Build and test

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build-and-test:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Install LLVM
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 21

      - name: Build project
        run: .\build.sh

      - name: Run test script
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
