name: Build and test

on:
  pull_request:
    types: [ opened, synchronize, labeled ]

jobs:
  build-and-test:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build build-essential python3

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh 
          sudo ./llvm.sh 21 all

      - name: Build project
        run: |
          chmod +x ./build.sh
          export PATH="/usr/lib/llvm-21/bin:$PATH"
          export CC=clang-21
          export CXX=clang++-21
          export LLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm
          ./build.sh

      - name: Run test script
        run: |
          chmod +x ./run_tests.sh
          export PATH="/usr/lib/llvm-21/bin:$PATH"
          export CC=clang-21
          export CXX=clang++-21
          export LLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm
          ./run_tests.sh

  sanitizers:
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build build-essential clang python3

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21 all

      - name: Run sanitizer suite
        run: |
          chmod +x ./scripts/run_sanitizers.sh
          export PATH="/usr/lib/llvm-21/bin:$PATH"
          export CC=clang-21
          export CXX=clang++-21
          export LLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm
          ./scripts/run_sanitizers.sh
